### ISSUE TITLE
Pulumi Exception without mention of Resource or User code

### ISSUE THREAD

**Issue by iridian-ks** [pulumi/pulumi#5366] opened 2020-09-14 22:53 UTC
## Expected Behavior

If an exception is thrown by Pulumi then it should show where in the user's code that came from and/or which resource caused the exception.

## Current Behavior

Sometimes, exceptions are thrown and it's impossible to find out where in the code it's coming from or why.

## Steps to Reproduce

I can't give specific steps since I don't know where in my code this is coming from. My steps were this:

1. Write code
2. Bring up infrastructure
3. Upgrade Pulumi and Providers
4. Pulumi throws exception that can't be traced

## Context (Environment)

This is thrown during the Preview phase.

Here is the exception:

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 426, in do_register
        await rpc.resolve_outputs(res, resolver.serialized_props, resp.object, resolvers)
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 502, in resolve_outputs
        translated_value = translate_output_properties(value, res.translate_output_property, types.get(key))
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 452, in translate_output_properties
        for k, v in output.items()
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 452, in <dictcomp>
        for k, v in output.items()
      File "/usr/local/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 436, in translate_output_properties
        raise AssertionError(f"Unexpected type; expected 'dict' got '{typ}'")
    AssertionError: Unexpected type; expected 'dict' got '<class 'str'>'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

I'm deploying Hashicorp's vault-helm chart, which deployed successfully in a previous Pulumi version. No code changes since then.

Here is what the preview shows:

```
Previewing update (master):
     Type                                                       Name                               Plan       Info
     pulumi:pulumi:Stack                                        vault-inf-master                              3 errors; 8193 debugs
~   ├─ pulumi:providers:rancher2                               rancher-provider                   update     [diff: +apiUrl,caCerts,tokenKey-api_url,ca_certs,token_key]
~   ├─ pulumi:providers:vault                                  vault-provider                     update     [diff: ~ca_cert_file]
     └─ rei:helm:VaultRelease                                   vault-release
          └─ kubernetes:helm.sh:Chart                             vault
               └─ kubernetes:rbac.authorization.k8s.io:RoleBinding  vault/vault-discovery-rolebinding             1 warning
```

It's unclear if one of the kubernetes resources is causing this error or not. In `--debug` mode I am not getting any additional context but it does consistently get thrown after:

```
    debug: waiting for quiescence; 15 RPCs outstanding
    error: Program failed with an unhandled exception:
```

**Comment by iridian-ks** [comment] 2020-09-15 17:39
Luckily, I was using Docker so I deleted my local image and repulled a prebuilt image that I had with all of the previous versions and things are working again. Seems like a regression. Possibly in the kubernetes provider but I can't be certain where. I can reproduce by rebuilding the image again locally.

**Comment by justinvp** [comment] 2020-09-16 23:45
@iridian-ks, sorry for the trouble, but thanks for filing the issue! This error message and similar ones could definitely be improved to help narrow down the root cause.

In the meantime, what are the versions of the PyPi packages you're using (i.e. `pip3 list`)?

**Comment by mikhailshilkov** [comment] 2022-07-12 10:39
This issue has been open for nearly two years with no repro or follow-up comments and upvotes. I'll go ahead and close it for now. If anyone is experiencing a similar problem, please open a new issue with your repro steps. Thank you!

**Closed by mikhailshilkov** 2022-07-12 10:39 UTC
Labels: kind/bug, language/python, resolution/no-repro
