### ISSUE TITLE
[Python] Pulumi hangs when assigning a single input to a sequence

### ISSUE THREAD

**Issue by PlusMinus0** [pulumi/pulumi#7198] opened 2021-06-03 07:45 UTC
Python version 3.9.5
Pulumi version 3.3.1

When providing a single Object, when a sequence is required, as in the example below, the python interpreter does not complain about the object not being a sequence and pulumi will simply hang indefinitely.
```python
role_binding = RoleBinding(
    role_binding_name,
    metadata=ObjectMetaArgs(name=role_binding_name, namespace=namespace_name),
    subjects=SubjectArgs(kind='ServiceAccount', name='default'),  # <-- This is missing [] brackets
    role_ref=RoleRefArgs(kind='Role', name=role_name, api_group='rbac.authorization.k8s.io'),
)
```

Expectation is that either the python interpreter or pulumi would complain.

**Comment by infin8x** [comment] 2021-06-04 23:18
Duplicate of #6981

The hang is tracked by https://github.com/pulumi/pulumi/issues/6981 and the underlying issue is tracked https://github.com/pulumi/pulumi-terraform-bridge/issues/251. So, resolving this duplicate.

**Closed by infin8x** 2021-06-04 23:18 UTC
Labels: kind/bug, language/python, resolution/duplicate
