### ISSUE TITLE
Cannot import lambda function with zip package type

### ISSUE THREAD

**Issue by BenElgar** [pulumi/pulumi#6540] opened 2021-03-16 14:36 UTC
`pulumi import` does not appear to work to import AWS lambda functions with a package type of "Zip". Note that this lambda function was originally created using Pulumi.

## Expected behavior

The lambda function should be appropriately imported into the Pulumi state.

## Current behavior

The `pulumi import` raises an error as follows:

```
❯ pulumi import -f import.json
Previewing import (deref/playground)

View Live: https://app.pulumi.com/deref/playground/playground/previews/56ed8bac-f7df-4cfe-80d0-ff52edc2bd36

     Type                    Name                    Plan       Info
     pulumi:pulumi:Stack     playground-playground              1 error
 =   └─ aws:lambda:Function  registry-crawl-0debfea  import     1 error

Diagnostics:
  pulumi:pulumi:Stack (playground-playground):
    error: preview failed

  aws:lambda:Function (registry-crawl-0debfea):
    error: Preview failed: diffing urn:pulumi:playground::playground::aws:lambda/function:Function::registry-crawl-0debfea: handler and runtime must be set when PackageType is Zip
```
`import.json`:
```json
{
  "nameTable": {
    "aws-us-west-2": "urn:pulumi:playground::playground::pulumi:providers:aws::provider-us-west-2"
  },
  "resources": [
    {
      "id": "registry-crawl-0debfea",
      "name": "registry-crawl-0debfea",
      "provider": "aws-us-west-2",
      "type": "aws:lambda/function:Function"
    }
  ]
}
```

```
❯ aws lambda get-function --function-name registry-crawl-0debfea
{
    "Configuration": {
        "FunctionName": "registry-crawl-0debfea",
        "FunctionArn": "arn:aws:lambda:us-west-2:054744317839:function:registry-crawl-0debfea",
        "Runtime": "nodejs12.x",
        "Role": "arn:aws:iam::054744317839:role/registry-crawl-67b8a59",
        "Handler": "__index.handler",
        "CodeSize": 2526,
        "Description": "",
        "Timeout": 180,
        "MemorySize": 128,
        "LastModified": "2021-03-01T17:53:53.737+0000",
        "CodeSha256": "xGiikxFSA5Tm22gRX1Ckiym5ZpKDM40YveAbseClGC0=",
        "Version": "$LATEST",
        "TracingConfig": {
            "Mode": "PassThrough"
        },
        "RevisionId": "b31f0cae-c85d-417e-8634-649e43bf4365",
        "State": "Active",
        "LastUpdateStatus": "Successful",
        "PackageType": "Zip"
    },
    "Code": {
        "RepositoryType": "S3",
        "Location": "<URL OMITTED>"
    }
}
```

## Steps to reproduce

1. Create a lambda function using `aws.cloudwatch.onSchedule` (from `@pulumi/aws`), providing an inline function
2. Attempt to import the created lambda function into a different Pulumi stack using `pulumi import` with an import file similar to the one above

## Context (Environment)

We're trying to create tools to allow people to generate Pulumi import files for arbitrary infrastructure. Dogfooding this on our own infrastructure, which is itself mostly managed via Pulumi, we run into issues. The specific case of handling resources that are already managed by Pulumi is not particularly important for us but it uncovers an issue with importing lambda functions more widely.

## Affected feature

`pulumi import`

**Comment by leviathanbadger** [comment] 2021-07-16 19:48
This may be related: https://github.com/pulumi/pulumi-aws/issues/1379

**Comment by lukehoban** [comment] 2021-08-13 17:58
Closing as dupe of #1379 given the additional details now in that issue.

**Closed by lukehoban** 2021-08-13 17:58 UTC
Labels: kind/bug, resolution/duplicate, area/import

**Comment by joeduffy** [comment] 2021-08-14 19:29
For what it's worth, I _think_ this is a core Pulumi issue, and not specific to AWS. I still don't know how we intend to support importing assets that were transformed from string paths to actual assets in the provider. I could be wrong, though.
