### ISSUE TITLE
Intermittent concurrent map writes error during update preview

### ISSUE THREAD

**Issue by stelmod** [pulumi/pulumi#11156] opened 2022-10-26 12:48 UTC
### What happened?

Intermittent failures when updating a stack. This is happening on two different pulumi projects and different stacks within each. 

### Steps to reproduce

Hard to tell how to reproduce, given that it only happens sometimes for us. The command we run is `pulumi update --yes`

### Expected Behavior

Successful stack update

### Actual Behavior

Failure with one of these errors:
* concurrent map read and map write ([trace](https://gist.github.com/stelmod/215657aa619e9f4d2cc3171d0b2b348c))
* concurrent map writes ([trace](https://gist.github.com/stelmod/ff7fc1176a576121ae2f9adbdb4ad4e1))

### Additional context

This is happening both when running pulumi on a dev laptop as well as CircleCI, all running the latest versions of pulumi.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment] 2022-10-26 14:23
Hi there @stelmod thank you for reporting this issue! Looking at the stack trace, it looks like this is the same issue we fixed today in https://github.com/pulumi/pulumi/pull/11151 and we will rollout a patch version as soon as possible. I will be closing this as duplicate of #11153

**Closed by Zaid-Ajaj** 2022-10-26 14:23 UTC
Labels: kind/bug, needs-triage

**Comment by stelmod** [comment] 2022-10-26 15:17
Thank you!
