### ISSUE TITLE
Provide better error message when resource properties are ConflictsWith

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5586] opened 2020-10-18 19:03 UTC
#### Problem

If I define a resource that has properties that conflict with each other, I get an error, but with no details about the properties that actually conflict.

#### Error output

```
p-r53-zone-conflictproperty % pulumi pre
Previewing update (dev)

View Live: https://app.pulumi.com/clstokes/p-r53-zone-conflictproperty/dev/previews/85bf8bbe-c092-4c4a-97c8-80ed8ea1e093

     Type                   Name                             Plan       Info
 +   pulumi:pulumi:Stack    p-r53-zone-conflictproperty-dev  create     
 +   ├─ aws:route53:Zone    acme-zone                        create     
 +   ├─ aws:s3:Bucket       main                             create     
     └─ aws:route53:Record  acme-apex-record                            1 error
 
Diagnostics:
  aws:route53:Record (acme-apex-record):
    error: aws:route53/record:Record resource 'acme-apex-record' has a problem: ConflictsWith
```

#### Suggestions for a fix

Provide a more detailed error message. For example:

```
error: aws:route53/record:Record resource 'acme-apex-record' has a problem: ConflictsWith: `ttl`, `aliases` cannot be set together
```

#### Steps to reproduce

```
git clone https://gist.github.com/35b843ffd74e10b5821d60ed3ed5a81a.git
cd 35b843ffd74e10b5821d60ed3ed5a81a
pulumi stack init dev
pulumi pre
```

**Comment by clstokes** [comment] 2020-10-23 21:00
Related https://github.com/pulumi/pulumi-aws/issues/1184.

**Comment by lukehoban** [comment] 2020-12-15 00:35
Closing this as a dupe of pulumi/pulumi-terraform-bridge#309 which is the underlying issue to improve the diagnostic message.

**Closed by lukehoban** 2020-12-15 00:35 UTC
