### ISSUE TITLE
^C doesn't cancel plugin installation

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3649] opened 2019-12-12 15:30 UTC
I'm apparently was missing a plugin, such that `pulumi preview` lazily started downloading it. I'm on a plane and so that's a very slow thing and I didn't want to wait. I hit ^C.

It appears we don't actually cancel plugin installations, however:

```
$ pulumi preview
Previewing update (dev):
[resource plugin aws-1.15.0] installing
     Type                 Name      Plan
     pulumi:pulumi:Stack  pu17-dev

System Messages
  ^C received; cancelling. If you would like to terminate immediately, press ^C again.
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
Downloading plugin: 1.78 MiB / 58.39 MiB [>---------------------]   3.04% 16m23s
```

**Comment by julienp** [comment] 2024-11-12 20:05
Dupe of https://github.com/pulumi/pulumi/issues/17594

**Closed by julienp** 2024-11-12 20:05 UTC
Labels: kind/bug, area/cli, resolution/duplicate
