### ISSUE TITLE
Mismatches in secretness in CLI vs programming model is confusing

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#6414] opened 2021-02-24 02:11 UTC
I have to admit, I still get tripped up a fair bit by our secrets model. Namely, I can specify secretness at the CLI, and in the programming model, and they don't need to match, and I get (IMHO) confusing results when they differ.

By that, I mean, I can choose to say `--secret` when configuring a variable at the CLI, and I can choose to say `getSecret` from the config bag in my program (or any permutation of those choices).

For example, consider a program that has a single config variable, `supasecret`. There are a few possibilities:

* Neither. Obvious result (everything is plaintext).
* Both. Obvious result (everything is marked secret: CLI output, state file).
* Just CLI. CLI output containing the secret value is marked secret (`[secret]`), stored in plaintext in state file. (And, as a result, shown in the Service Console.)
* Just Programming Model. CLI outputs print plaintext value, but state file is encrypted (including Service Console).

I would posit that anytime these differ from one another, the end user probably made a mistake and we should error/warn.

**Comment by lukehoban** [comment] 2021-02-24 02:59
Same or similar to https://github.com/pulumi/pulumi/issues/3139. 

We may want to consider a breaking change in 3.0 here (or at least a warning).

**Comment by joeduffy** [comment] 2021-02-24 16:17
Ah, yes, I guess I had the exact same reaction 1½ years later. I'm happy to close as a dupe. I think it's ok to do a warning; it seems super simple, and then that way we don't need to wait for (or tackle) a breaking change.

**Comment by lukehoban** [comment] 2021-04-26 18:56
Closing as a dupe of #3139.

**Closed** 2021-04-26 19:01 UTC
Labels: kind/bug, resolution/duplicate
