### ISSUE TITLE
could not use SignedURL warning in GCP bucket

### ISSUE THREAD

**Issue by confiq** [pulumi/pulumi#4485] opened 2020-04-24 06:54 UTC
each time when I run `pulumi up` I get this warning

> warning: Could not get signed url for stack location: blob (key ".pulumi/stacks/deploy.json") (code=Unknown): to use SignedURL, you must call OpenBucket with a valid Options.GoogleAccessID and exactly one of Options.PrivateKey or Options.SignBytes

Many questions rises here, like, why would you use SignedURL for GCP bucket? 

About the setup, 
pulumi project 

> pulumi init -> `pulumi stack init --secrets-provider="gcpkms://projects/whatever...`

pulumi auth
> `pulumi login --cloud-url gs://pulumi-config/`

What is important to say that bucket `pulumi-config` has customer-manage key (KMS) for encryption and the bug started around that. 

![image](https://user-images.githubusercontent.com/277770/80183492-33cb2380-8609-11ea-82bd-f81b52c4bb95.png)

**Comment by stack72** [comment] 2021-01-04 16:53
Going to close this out as a dupe of #4029 

Apologies we have not interacted with it until this point

Paul

**Closed by stack72** 2021-01-04 16:53 UTC
