### ISSUE TITLE
Server crashes on resource errors

### ISSUE THREAD

**Issue by vahagn-madatyan** [pulumi/pulumi#11163] opened 2022-10-26 18:52 UTC
### What happened?

I am trying to deploy a vpc using Automation API over HTTP method. If the user passes the right cidr block, everything deploys fine. But if the user passes wrong cidr block, the vpc resource creation fails(as it should) however that also crashes the whole node js server. 

I know I will need to validate the data, however I am trying to understand how can I catch the exception and handle it in backend so it does not crash the backend server.

See below:

The AWS Error:
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/74753362/198110355-15c63273-6348-4b31-b2de-5c3da840eaff.png">

Server crash:

<img width="990" alt="Screen Shot 2022-10-26 at 11 47 16 AM" src="https://user-images.githubusercontent.com/74753362/198111298-8e921242-2996-47f6-831e-b42f1e907872.png">
hes:

I am using the pulumi automation example for typescript http.

### Steps to reproduce

1. Clone pulumi api automation http example for typescript
2. Replace s3 bucket with vpc creation
3. put wrong cidr block 10.0.0.1/16
4. Run create request
5. Watch server crash

### Expected Behavior

I expect the server not to crash and exception be thrown that I can catch.

### Actual Behavior

An exception is not thrown that I can catch and handle, since this appears to be cli error.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment] 2022-10-28 14:23
> however that also crashes the whole node js server.

Hi there @vahagn-madatyan can you please provide more information about how your server is setup? Crashing the server can happen if our code is forcefully exiting the nodejs process. Simply throwing an error is usually catched by either you (using a try-catch block) or the web server framework you are using.

**Comment by vahagn-madatyan** [comment] 2022-10-30 18:26
Hi @Zaid-Ajaj,

I have the whole code wrapped in try { } catch {e}, I am using the example from [Automation example ts](https://github.com/pulumi/automation-api-examples/tree/main/nodejs/pulumiOverHttp-ts) and just changed it from s3 to vpc create, in the example the whole stack creation is wrapped in try/catch, I changed the actual stack resources, see below:

![image](https://user-images.githubusercontent.com/74753362/198894933-e8f4c52e-c6c8-413c-afb0-adabf70bfefd.png)


The actual application is using NestJS but isolating the problem to the example you guys have, it does not seem NestJS issue.

I run the following curl:
`curl --header "Content-Type: application/json"   --request POST   --data '{"id":"vpctestpulumi","content":"hello world\n"}'   http://localhost:1337/sites`

See the full stack error below:
`server running on :1337
Updating (vpctestpulumi):



 +  pulumi:pulumi:Stack pulumi_over_http-vpctestpulumi creating (0s) 

    aws:ec2:Vpc vpc1  error: aws:ec2/vpc:Vpc resource 'vpc1' has a problem: expected cidr_block to contain a valid network Value, expected 10.0.0.0/16, got 10.0.0.1/16. Examine values at 'Vpc.CidrBlock'.

 +  pulumi:pulumi:Stack pulumi_over_http-vpctestpulumi created 
    aws:ec2:Vpc vpc1 **failed** 1 error
 
Diagnostics:
  aws:ec2:Vpc (vpc1):
    error: aws:ec2/vpc:Vpc resource 'vpc1' has a problem: expected cidr_block to contain a valid network Value, expected 10.0.0.0/16, got 10.0.0.1/16. Examine values at 'Vpc.CidrBlock'.
 
Resources:
    + 1 created

Duration: 4s


/Users/vahagn.madatyan/Documents/ACN/CNO/CNO POC/node_modules/@pulumi/pulumi/runtime/resource.js:219
    const preallocError = new Error();
                          ^

<ref *1> Error: failed to register new resource vpc1 [aws:ec2/vpc:Vpc]: Resource monitor is terminating
    at Object.registerResource (/Users/vahagn.madatyan/Documents/ACN/CNO/CNO POC/node_modules/@pulumi/runtime/resource.ts:292:27)
    at new Resource (/Users/vahagn.madatyan/Documents/ACN/CNO/CNO POC/node_modules/@pulumi/resource.ts:401:13)
    at new CustomResource (/Users/vahagn.madatyan/Documents/ACN/CNO/CNO POC/node_modules/@pulumi/resource.ts:780:9)
    at new Vpc (/Users/vahagn.madatyan/Documents/ACN/CNO/CNO POC/node_modules/@pulumi/ec2/vpc.ts:263:9)
    at /Users/vahagn.madatyan/Documents/ACN/CNO/CNO POC/index.ts:20:15
    at Generator.next (<anonymous>)
    at /Users/vahagn.madatyan/Documents/ACN/CNO/CNO POC/bin/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/vahagn.madatyan/Documents/ACN/CNO/CNO POC/bin/index.js:4:12)
    at Object.init (/Users/vahagn.madatyan/Documents/ACN/CNO/CNO POC/index.ts:19:61) {
  code: 14,
  promise: Promise { <rejected> [Circular *1] }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by nitinpgaikwad** [comment] 2023-02-16 22:49
Same issue is happening with below pulumi versions and its reproducible. When there is any error while creating or updating resource then its causing server to hang. we use NestJs.
    "@pulumi/aws": "5.29.1",
    "@pulumi/pulumi": "3.54.0",

error:
`../services/node_modules/@pulumi/pulumi/node_modules/@grpc/grpc-js/src/call.ts:81
  return Object.assign(new Error(message), status);
                       ^
Error: Resource monitor is terminating
    at Object.callErrorFromStatus (../services/node_modules/@pulumi/pulumi/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (../services/node_modules/@pulumi/pulumi/node_modules/@grpc/grpc-js/src/client.ts:338:36)
    at Object.onReceiveStatus (../services/node_modules/@pulumi/pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (../services/node_modules/@pulumi/pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at ../services/node_modules/@pulumi/pulumi/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (node:internal/process/task_queues:7
`

**Comment by justinvp** [comment] 2023-04-26 18:27
Closing this as a duplicate of https://github.com/pulumi/pulumi/issues/10744

**Closed by justinvp** 2023-04-26 18:27 UTC
Labels: kind/bug, resolution/duplicate
