### ISSUE TITLE
Pulumi can't find the resource in a stack which exists in it

### ISSUE THREAD

**Issue by mate201** [pulumi/pulumi#6557] opened 2021-03-17 15:41 UTC
## Expected behavior
Pulumi should be able to work on the resource if it's specified.

## Current behavior
Pulumi can't see and delete the resource which exists in the stack.

## Steps to reproduce
1. First of all create a few simple network objects in AWS
```
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';

const main_vpc = new aws.ec2.Vpc(
    'Test_VPC',
    {
        cidrBlock: '10.10.0.0/16',
        tags:  { Name: 'Test_VPC' }
    }
);

const main_subnet_a = new aws.ec2.Subnet(
    'Test_VPC_Subnet_A',
    {
        vpcId: main_vpc.id,
        cidrBlock: '10.10.0.0/24',
        availabilityZone: 'eu-central-1a',
        tags: { Name: 'Test_VPC_Subnet_A'}
    },
);
```

2. `Pulumi up`
3. Change subnet variable, name and tag
```
const main_subnet_a0 = new aws.ec2.Subnet(
    'Test_VPC_Subnet_A0',
    {
        vpcId: main_vpc.id,
        cidrBlock: '10.10.0.0/24',
        availabilityZone: 'eu-central-1a',
        tags: { Name: 'Test_VPC_Subnet_A0'}
    },
);
```
4. `pulumi up --diff`
Pulumi will fail with following error:

```
Previewing update (dev):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::sandbox::pulumi:pulumi:Stack::sandbox-dev]
    + aws:ec2/subnet:Subnet: (create)
        [urn=urn:pulumi:dev::sandbox::aws:ec2/subnet:Subnet::Test_VPC_Subnet_A0]
        [provider=urn:pulumi:dev::sandbox::pulumi:providers:aws::default_3_28_0::**********************8]
        assignIpv6AddressOnCreation: false
        availabilityZone           : "eu-central-1a"
        cidrBlock                  : "10.10.0.0/24"
        mapPublicIpOnLaunch        : false
        tags                       : {
            ManagedBy : "Pulumi"
            Name      : "Test_VPC_Subnet_A0"
            Owner     : "************"
        }
        vpcId                      : "vpc-*****"
    - aws:ec2/subnet:Subnet: (delete)
        [id=subnet-****]
        [urn=urn:pulumi:dev::sandbox::aws:ec2/subnet:Subnet::Test_VPC_Subnet_A]
        [provider=urn:pulumi:dev::sandbox::pulumi:providers:aws::default_3_28_0::***************************]
        assignIpv6AddressOnCreation: false
        availabilityZone           : "eu-central-1a"
        cidrBlock                  : "10.10.0.0/24"
        mapPublicIpOnLaunch        : false
        tags                       : {
            ManagedBy : "Pulumi"
            Name      : "Test_VPC_Subnet_A"
            Owner     : "******"
        }
        vpcId                      : "vpc-******"
Resources:
    + 1 to create
    - 1 to delete
    2 changes. 2 unchanged
Permalink: ***********
Do you want to perform this update? yes
Updating (dev):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::sandbox::pulumi:pulumi:Stack::sandbox-dev]
    + aws:ec2/subnet:Subnet: (create)
        [urn=urn:pulumi:dev::sandbox::aws:ec2/subnet:Subnet::Test_VPC_Subnet_A0]
        [provider=urn:pulumi:dev::sandbox::pulumi:providers:aws::default_3_28_0::**************************]
        assignIpv6AddressOnCreation: false
        availabilityZone           : "eu-central-1a"
        cidrBlock                  : "10.10.0.0/24"
        mapPublicIpOnLaunch        : false
        tags                       : {
            ManagedBy : "Pulumi"
            Name      : "Test_VPC_Subnet_A0"
            Owner     : "*************"
        }
        vpcId                      : "vpc-******"
error: 1 error occurred:
        * error creating subnet: InvalidSubnet.Conflict: The CIDR '10.10.0.0/24' conflicts with another subnet
        status code: 400, request id: *********************


error: update failed
Resources:
    2 unchanged

Duration: 4s
```

This is expected error from AWS.

5. Let's try to delete the previous subnet via CLI. Execute: `pulumi up -t urn:pulumi:dev::sandbox::aws:ec2/subnet:Subnet::Test_VPC_Subnet_A `

```
Previewing update (dev):
     Type                 Name               Plan       Info
     pulumi:pulumi:Stack  sandbox-dev                   1 error
 -   └─ aws:ec2:Subnet    Test_VPC_Subnet_A  delete
Diagnostics:
  pulumi:pulumi:Stack (sandbox-dev):
    error: Target 'urn:pulumi:dev::sandbox::aws:ec2/subnet:Subnet::Test_VPC_Subnet_A' could not be found in the stack. Did you forget to escape $ in your shell?
```
This resource could be prefectly found in a stack, but Pulumi can't see it for some reason.

`Pulumi v2.19.0`

packages.json
```
{
    "name": "sandbox",
    "devDependencies": {
        "@types/node": "^10.17.54"
    },
    "dependencies": {
        "@pulumi/aws": "3.28.0",
        "@pulumi/pulumi": "2.19.0"
    }
}
```

**Comment by EvanBoyle** [comment] 2021-07-24 00:38
closing as duplicate of https://github.com/pulumi/pulumi/issues/6422

**Closed by EvanBoyle** 2021-07-24 00:38 UTC
Labels: kind/bug, resolution/duplicate
