### ISSUE TITLE
v3.104.0: error: could not deserialize deployment: constructing secrets manager of type "cloud" occurring after v3.104.0 upgrade

### ISSUE THREAD

**Issue by liam-auror** [pulumi/pulumi#15329] opened 2024-01-31 22:06 UTC
### What happened?

After running a stack update using v3.104.0, further operations fail with a
`error: could not deserialize deployment: constructing secrets manager of type "cloud": illegal base64 data at input byte 0` error. In some cases, a different error message is emitted:
`error: could not deserialize deployment: constructing secrets manager of type "cloud": secrets (code=InvalidArgument): keyvault.BaseClient#Decrypt: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Content of 'value' is not base64url.\r\nProperty 'value' is required.\r\n"`

Reverting to previous versions (3.103.1, 3.100.0) has no effect. Likewise updating project dependencies to latest also doesn't affect anything.

Project uses Pulumi Cloud w/ Azure Key Vault for secrets encryption. No changes have been made to the Key Vault or key. Key can be successfully retrieved on same system via Az CLI. Az CLI version hasn't changed either since last successful operation.

### Example

1. Update Pulumi CLI to v3.104.0
2. Run a stack operation on existing stack w/ AKV secrets provider
3. Operation will fail will above error

### Output of `pulumi about`

```
CLI          
Version      3.104.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.24.0
nodejs        unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/[redacted]/.nvm/versions/node/v18.19.0/bin/node' version='v18.19.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/liam-auror
User           liam-auror
Organizations  [redacted]
Token type     personal

Dependencies:
NAME                          VERSION
@azure/storage-file-datalake  12.16.0
@pulumi/azure-native          2.24.0
@pulumi/pulumi                3.100.0
@types/node                   18.19.5
typescript                    5.3.3
@azure/identity               3.4.1
@azure/keyvault-secrets       4.7.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: constructing secrets manager of type "cloud": illegal base64 data at input byte 0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-01-31 22:42
Thanks just a sanity check that we hadn't missed a strange variation of those, but that looks standard.

**Comment by Frassle** [comment] 2024-01-31 22:46
I think I know what caused this. Fixing this is probably going to require some state editing for your stack.
I suggest you downgrade pulumi to pre-3.104 and use `pulumi stack export` to get your stack JSON and remove the "secrets_providers" field from it and then reimport that with `pulumi stack import`. If you then rerun `stack change-secrets-provider` to the same key url I think it should fix the stack state with the correct data.

**Comment by Frassle** [comment] 2024-01-31 23:06
Well yes the problem is the encrypted key in the secret state is just a base64 string, but the format of that changed between gocloud versions and it looks like some part of the system hasn't accounted for that.

If import can't handle that it will make fixing this more tricky. I'll have to look into the code to see if I can spot anything to fix this.

**Comment by danielbichuetti** [comment] 2024-01-31 23:08
Same issues here with Azure KeyVault:

`error: getting snapshot: constructing secrets manager of type "cloud": illegal base64 data at input byte 2`

All our stacks, which used KeyVault, panicked after the update.

**Comment by Frassle** [comment] 2024-02-01 00:15
Yup that should work. I've got a change open to also add some code to just fix state forward. We'll try and get that merged and released as soon as possible.

**Closed** 2024-02-01 10:30 UTC
Labels: kind/bug, p1, area/secrets, impact/regression

**Comment by Frassle** [comment] 2024-02-01 10:56
We'll be getting release 3.104.2 out shortly, it should fix this going forward and also contains some code to auto-fix any stacks that ended up with broken state.

**Comment by Frassle** [comment] 2024-02-26 19:43
> have you ever considered removing gocloud.dev dependency?

It was considered and decided that it was unlikely we could do any better by ourselves.
