### ISSUE TITLE
Panic when HTTP request is interrupted

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3483] opened 2019-11-11 05:27 UTC
I was on a flight and the WiFi cut out mid-operation. A panic resulted:

```
$ pulumi --logtostderr -v=9 preview
I1110 20:42:11.361318   78082 backend.go:408] found username for access token
I1110 20:42:46.362007   78082 sink.go:154] defaultSink::Error(error: performing HTTP request: Get https://api.pulumi.com/api/stacks/joeduffy/dotplay/dev: EOF
github.com/pulumi/pulumi/pkg/backend/httpstate/client.pulumiAPICall
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/api.go:207
github.com/pulumi/pulumi/pkg/backend/httpstate/client.pulumiRESTCall
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/api.go:276
github.com/pulumi/pulumi/pkg/backend/httpstate/client.(*Client).restCall
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/client.go:68
github.com/pulumi/pulumi/pkg/backend/httpstate/client.(*Client).GetStack
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/client/client.go:261
github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).GetStack
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:558
github.com/pulumi/pulumi/pkg/backend/state.CurrentStack
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/state/stacks.go:41
github.com/pulumi/pulumi/cmd.requireCurrentStack
	/Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/util.go:198
github.com/pulumi/pulumi/cmd.requireStack
	/Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/util.go:155
github.com/pulumi/pulumi/cmd.newPreviewCmd.func1
	/Users/travis/gopath/src/github.com/pulumi/pulumi/cmd/preview.go:93
github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:112
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:766
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:852
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute
	/Users/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:800
main.main
	/Users/travis/gopath/src/github.com/pulumi/pulumi/main.go:49
runtime.main
	/Users/travis/.gimme/versions/go1.12.9.darwin.amd64/src/runtime/proc.go:200
runtime.goexit
	/Users/travis/.gimme/versions/go1.12.9.darwin.amd64/src/runtime/asm_amd64.s:1337
)
error: performing HTTP request: Get https://api.pulumi.com/api/stacks/joeduffy/dotplay/dev: EOF
```

**Comment by dixler** [comment] 2023-10-16 21:17
I was unable to repro this bug on the most recent version of the CLI.

I ran multiple updates under strange internet conditions. I turned off/toggled my internet during update. (I even pulled out my router cable). I was unable to reproduce this issue. The update at worst, would time out (after a long period of time).

I then added a sleep before the body of
```
httpstate/backend.go:825 github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).GetStack
```
turned off my internet and it timed out instead of panicking like in the previous case.
```
% pulumi pre
error: performing HTTP request: Get "https://api.pulumi.com/api/stacks/kyle-pulumi-corp/k8s-prog/dev": dial tcp: lookup api.pulumi.com on [::1]:53: read udp [::1]:53869->[::1]:53: read: connection refused
```

I'm going to close this as no-repro.

If someone manages to run into this again on a recent version of pulumi, lmk.

**Closed by dixler** 2023-10-16 21:17 UTC
Labels: kind/bug, area/cli, impact/panic, resolution/no-repro, impact/non-specific
