### ISSUE TITLE
ComponentResource does not fully "materialize" during a unit test

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#6562] opened 2021-03-17 20:04 UTC
When attempting to test a ComponentResource that creates multiple resources, all resources defined in the component's constructor do not fully "materialize" unless all are awaited.

## Expected behavior

The constructor and all resources should fully complete.

## Current behavior

Only awaited resources from the component are created.

For example, if a component's constructor defines three resources: 
```
export class LandingZone extends pulumi.ComponentResource {
    constructor(name: string, args: LandingZoneArgs, opts?: pulumi.ComponentResourceOptions) {
        super("custom:x:LandingZone", name, args, opts);

        this.vpc = new aws.ec2.Vpc(name, {
        }, { parent: this });

        this.internetGateway = new aws.ec2.InternetGateway(`${name}-public`, {
        }, { parent: this});

        this.publicSubnetRouteTable = new aws.ec2.RouteTable(`${name}-public`, {
        }, { parent: this});

        this.registerOutputs()
    }
}
```

and my unit test only awaits/tests `vpc` and `internetGateway`, then the rest of the component is not fully constructed.

## Steps to reproduce

Will update with full repro shortly.

## Context (Environment)

This seems specific to `ComponentResource`.

**Comment by infin8x** [comment] 2021-04-05 15:11
Duplicate of #6666

**Closed** 2021-04-05 15:11 UTC
Labels: area/testing, kind/bug, resolution/duplicate
