### ISSUE TITLE
Exception has occurred: Error: 14 UNAVAILABLE: No connection established

### ISSUE THREAD

**Issue by XBeg9** [pulumi/pulumi#6457] opened 2021-03-03 06:55 UTC
Automation API

## Expected behavior

Every subsequent request to Automation API should work the same way as an initial one

## Current behavior

Every subsequent request fails

## Steps to reproduce

Run the REST Api endpoint a second time without restarting the server, gives me an error
`Exception has occurred: Error: 14 UNAVAILABLE: No connection established inside @grpc/grpc-js/src/call.ts:79:24)`

```js
private createPulumiStack(appName: string) {
  return async () => {
    const resourceGroup = new azurePulumi.core.ResourceGroup(
      'resource-group',
      {
        name: `${appName}-rg`,
        location: 'centralus'
      }
    );

    return {
      resourceGroupName: resourceGroup.name,
      fqdn: 'http://hello-world.com'
    };
  };
}

const projectName = 'cms';

const stack = await LocalWorkspace.createOrSelectStack({
  stackName: `Team/sandbox`,
  projectName,
  program: this.createPulumiStack(deploymentConfig.appName)
});

console.info('setting up config');
await stack.setAllConfig(STACK_CONFIG(projectName));
console.info('config set');

console.info('refreshing stack...');
await stack.refresh({ onOutput: console.info });

stack.up({ onOutput: console.info });
```

**Comment by vtereshyn** [comment] 2021-03-03 10:08
I was testing your example under https://github.com/pulumi/automation-api-examples/tree/main/nodejs/pulumiOverHttp-ts and here are steps to reproduce the problem which appears even in your code:

- yarn start (as `README` says)
- create a new stack (as `README` says)
- DON'T stop the server (this is important)
- update existing stack (should be good)
- update existing stack again

After the last step, you should get an error

It can be fixed by adding `await stack.refresh()` after `await stack.setConfig("aws:region", { value: "us-west-2" })` in your code, but case that @XBeg9 described above uses Azure and looks like refreshing doesn't work in Azure case.

**Comment by XBeg9** [comment] 2021-03-04 05:59
@EvanBoyle @komalali team, could you please give us some workarounds over here? this is a blocker for us :( and we don't know how to move on, instead of just ejecting the Automation API from our architecture. Thanks

**Comment by komalali** [comment] 2021-03-04 06:25
Hey @XBeg9,

I have this on my list of things to look into tomorrow 🙏. Thanks for your patience, definitely want to make sure we get this squared away.

**Comment by EvanBoyle** [comment] 2021-03-04 16:44
@XBeg9 @vtereshyn What version of pulumi/pulumi and the azure/aws provider are you using? 

I tried to reproduce the issue outlined by @vtereshyn and was unable to (subsequent updates worked as expected). I did however specify the latest versions of dependencies:

```
    "@pulumi/aws": "^3.31.0",
    "@pulumi/pulumi": "^2.22.0",
```

@XBeg9 do you have a complete program that can reproduce this error reliably?

**Comment by EvanBoyle** [comment] 2021-07-21 23:42
Going to close this out as I was unable to repro. Feel free to reopen if you have more details on a repro with the latest pulumi/pulumi and dependencies.

**Closed by EvanBoyle** 2021-07-21 23:42 UTC
Labels: area/automation-api, kind/bug, language/javascript, needs-repro, resolution/no-repro
