### ISSUE TITLE
Custom Resources - `no resource plugin 'pulumi-nodejs' found in the workspace or on your $PATH` Error

### ISSUE THREAD

**Issue by adrians5j** [pulumi/pulumi#8374] opened 2021-11-07 15:29 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Well.. I'm not sure if this is related to our setup or it's a bug...

So.. I was about to create a custom resource, something like (code simplified):

```ts
import * as pulumi from "@pulumi/pulumi";

class SomeProvider implements pulumi.dynamic.ResourceProvider {
    async create() {
        return { id: "test" };
    }

    async update() {
        return {};
    }

    async diff() {
        return { changes: true };
    }
}

class SomeResource extends pulumi.dynamic.Resource {
    constructor(name: string, inputs: any, options?: pulumi.CustomResourceOptions) {
        super(new SomeProvider(), name, inputs, options);
    }
}

export class DeploySomething extends pulumi.ComponentResource {
    constructor(name: string, inputs: any, options?: any) {
        super("DeploySomething", name, options);
        new SomeResource(
            `${name}-deploy-something`,
            {
                ...inputs,
                resourceId: pulumi.output<string>("xyz")
            },
            { parent: this }
        );
    }
}

```

But, once I try to actually use it / deploy it, the CLI throws the following error `no resource plugin 'pulumi-nodejs' found in the workspace or on your $PATH`:

![image](https://user-images.githubusercontent.com/5121148/140650730-b67ab73c-d0a8-4edf-a30f-314b5b3a94cf.png)

Now, I suspect this might be related to the setup we have in place.

So, the thing is, for Webiny users, we download the Pulumi CLI automatically for them. It is downloaded via the `https://get.pulumi.com/releases/sdk/...` link, and placed into user's `<project-root>/.webiny/pulumi-cli/{OS}/` folder:

![image](https://user-images.githubusercontent.com/5121148/140651032-a0901594-d120-4bb6-866b-b9c00f5c6c79.png)

Then, when actually invoking the Pulumi CLI programatically, so via the `<project-root>/.webiny/pulumi-cli/{OS}/pulumi/pulumi` executable, we also provide `PULUMI_HOME` variable. It's again the same `<project-root>/.webiny/pulumi-cli/{OS}`.

We've been using this setup for a long time and never had any issues with it. The issue outlined above is only showing when I'm using a custom resource. The moment I comment it out, everything starts to work again.

Is it possible that we simply misconfigured something here? Or maybe there's an error in the custom resource code?

### Steps to reproduce

1. Download Pulumi binary in a custom folder
2. Run commands via the downloaded binary, with the `PULUMI_HOME` env var set like explained above
3. Create custom resource via TS code
4. Deploy it

Expected: Custom resource to be deployed.
Actual: Custom resource not deployed - `no resource plugin 'pulumi-nodejs' found in the workspace or on your $PATH`: error thrown

**Comment by doitadrian** [comment] 2021-11-07 15:39
Just wanted to add that I'll try playing more with this and if I find something, I'll let you know.

**Comment by Pavel910** [comment] 2021-11-10 08:50
There's [this commit](https://github.com/pulumi/pulumi/commit/c878916901a997a9c0ffcbed23560e19e224a6f1) which describes the correct behavior. And, if that's how things work, everything should be working fine, because all binaries are located next to each other, and we _do_ set PULUMI_HOME variable:

![image](https://user-images.githubusercontent.com/3920893/141080656-4c5d59d1-d853-48f0-9d61-479906569e6b.png)

But unfortunately, it doesn't work. However, if I point $PATH to that folder, things start to work.

**Comment by pgavlin** [comment] 2021-11-18 23:02
> There's this commit which describes the correct behavior. And, if that's how things work, everything should be working fine, because all binaries are located next to each other, and we do set PULUMI_HOME variable:

Unfortunately I think that probing behavior is specific to language plugins, not resource plugins. Is adding that folder to the `PATH` a viable workaround for you for now?

**Comment by Pavel910** [comment] 2021-11-19 09:34
> Unfortunately I think that probing behavior is specific to language plugins, not resource plugins. Is adding that folder to the `PATH` a viable workaround for you for now?

We were able to bypass this limitation by passing a modified `PATH` when executing pulumi binary from a custom folder, with `execa`. Looks something like  this (pseudo-code):

```
await execa(pathToPulumiBinary, ["up"], { env: { PATH: `${process.env.PATH};${pathToPulumiFolder}` } } );
```

This way only that spawned process will have the custom PATH variable, and we do not mess with user's OS settings.

So we're not blocked, but it was a surprise that different plugins are treated differently. Would be really convenient if pulumi knew how to handle its stuff automatically :)

**Comment by justinvp** [comment] 2023-07-27 07:32
Looks like a dupe of #9381 which has been fixed.

**Closed by justinvp** 2023-07-27 07:32 UTC
Labels: kind/bug, area/cli, resolution/duplicate
