### ISSUE TITLE
Node codegen makes too many files for azure-native

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#11504] opened 2022-12-01 15:06 UTC
### What happened?

NPM started rejecting publishing pulumi-azure-native, see:

https://github.com/pulumi/pulumi-azure-native/issues/2108

Worked around by downgrading Node codegen to 3.46.1

The root cause is https://github.com/pulumi/pulumi/pull/10831 generating more files. The are now too many files and NPM registry rejects the publication.

### Steps to reproduce

regenerate pulumi-azure-native with latest codegen, observe large file count

### Expected Behavior

pulumi-azure-native can upgrade to latest codegen

### Actual Behavior

pulumi-azure-native cannot upgrade to latest codegen

### Additional context

It would be lovely to find the file count cutoff deemed acceptable by NPM so we can gauge the problem, but I've not found it from quick searches.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2022-12-01 15:14
Failure details:

```npm notice === Tarball Details ===
69097
npm notice name:          @pulumi/azure-native
69098
npm notice version:       1.88.0-alpha.1669848800
69099
npm notice filename:      @pulumi/azure-native-1.88.0-alpha.1669848800.tgz
69100
npm notice package size:  22.7 MB
69101
npm notice unpacked size: 374.9 MB
69102
npm notice shasum:        cb8d65bb6e126ba5daac0ec8915790547faf3ab3
69103
npm notice integrity:     sha512-3OM8NuK+6knsB[...]m34CJ6ESt6kIA==
69104
npm notice total files:   69045
69105
npm notice
69106
npm notice Publishing to https://registry.npmjs.org/
69107
npm ERR! code E415
69108
npm ERR! 415 Unsupported Media Type - PUT https://registry.npmjs.org/@pulumi%2fazure-native - Too many files.
```

Previous success:
https://github.com/pulumi/pulumi-azure-native/actions/runs/3527293627/jobs/5917543380#step:21:59911

```
npm notice === Tarball Details ===
59911
npm notice name:          @pulumi/azure-native
59912
npm notice version:       1.87.0
59913
npm notice package size:  23.4 MB
59914
npm notice unpacked size: 385.8 MB
59915
npm notice shasum:        557733433aaff97b84a9a0bb5cf56bcb90ac6e36
59916
npm notice integrity:     sha512-+5/QCe1U0GWJv[...]OjWlce4xDZzcQ==
59917
npm notice total files:   59869
59918
npm notice
```

**Comment by RobbieMcKinstry** [comment] 2022-12-15 19:11
@t0yv0 I think this was addressed by https://github.com/pulumi/pulumi/pull/11534
Can we close? I'll link this in to [the tracking issue](https://github.com/pulumi/pulumi/issues/11558) related to file splitting.

**Comment by lukehoban** [comment] 2023-06-27 14:30
Closing as duplicate of #11534 and #11558.

**Closed by lukehoban** 2023-06-27 14:30 UTC
Labels: kind/bug, language/javascript, area/codegen, resolution/duplicate
