### ISSUE TITLE
Document Options for `pulumi convert`

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi#14125] opened 2023-10-06 21:29 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As a user of the Pulumi CLI, when I want to magically transform my code from one language to another, I would like to know what my options are.
Specifically, I would like to know valid, supported inputs for the `--from` and `--language` flags during convert.
Additionally I would like to [see a few examples on the public facing docs](https://www.pulumi.com/docs/cli/commands/pulumi_convert/).

### Affected area/feature

Pulumi pkg/cmd

**Comment by Frassle** [comment] 2023-10-06 21:32
As discussed on slack there are some complexities to this because it's all plugin driven.

I think in my perfect world we'd have converter and language plugins registered at the Pulumi registry and we'd use that to fill in these lists.

Until then I think the best we can do is enumerate the currently installed plugins, maybe add well known ones (i.e. poor mans registry by hardcoding lists in the CLI), and somehow indicate it's plugin driven so there might be others to install.

**Comment by justinvp** [comment] 2023-10-30 14:44
Duplicate of #12720

**Closed by justinvp** 2023-10-30 14:44 UTC
Labels: area/cli, kind/enhancement, resolution/duplicate
