### ISSUE TITLE
Can pass an output into a resource name

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#17934] opened 2024-12-05 10:32 UTC
### What happened?

If you pass an output in as a resource name parameter then the URN gets messed up because it's expecting a string:

```
"urn": "urn:pulumi:dev::output-resource-name-ts::random:index/randomPet:RandomPet::Calling [toString] on an [Output\u003cT\u003e] is not supported.\n\nTo get the value of an Output\u003cT\u003e as an Output\u003cstring\u003e consider either:\n1: o.apply(v =\u003e `prefix${v}suffix`)\n2: pulumi.interpolate `prefix${v}suffix`\n\nSee https://www.pulumi.com/docs/concepts/inputs-outputs for more details.\n\nOr use ESLint with https://github.com/pulumi/eslint-plugin-pulumi to warn or\nerror lint on using Output\u003cT\u003e in template literals.\nThis function may throw in a future version of @pulumi/pulumi.-pet2",
```

I expected that it would throw some error and not let me do this.

You can see this in the `pulumi about` response below.

### Example

```typescript
import * as random from "@pulumi/random";

const pet = new random.RandomPet("pet1")

const pet2 = new random.RandomPet(`${pet.id}-pet2`)
```

### Output of `pulumi about`

```
CLI
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown
resource  random  4.16.7

Host
OS       darwin
Version  15.1.1
Arch     arm64

This project is written in nodejs: executable='/Users/piers/.nvm/versions/node/v20.11.1/bin/node' version='v20.11.1'

Current Stack: pierskarsenbarg/output-resource-name-ts/dev

TYPE                              URN
pulumi:pulumi:Stack               urn:pulumi:dev::output-resource-name-ts::pulumi:pulumi:Stack::output-resource-name-ts-dev
pulumi:providers:random           urn:pulumi:dev::output-resource-name-ts::pulumi:providers:random::default_4_16_7
random:index/randomPet:RandomPet  urn:pulumi:dev::output-resource-name-ts::random:index/randomPet:RandomPet::pet1
random:index/randomPet:RandomPet  urn:pulumi:dev::output-resource-name-ts::random:index/randomPet:RandomPet::Calling [toString] on an [Output<T>] is not supported.

                                  To get the value of an Output<T> as an Output<string> consider either:
                                  1: o.apply(v => `prefix${v}suffix`)
                                  2: pulumi.interpolate `prefix${v}suffix`

                                  See https://www.pulumi.com/docs/concepts/inputs-outputs for more details.

                                  Or use ESLint with https://github.com/pulumi/eslint-plugin-pulumi to warn or
                                  error lint on using Output<T> in template literals.
                                  This function may throw in a future version of @pulumi/pulumi.-pet2


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg, team-ce, munich-workshop, demo, ai-demo
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.142.0
@pulumi/random  4.16.7
@types/node     18.19.67
typescript      5.7.2

Pulumi locates its logs in /var/folders/x8/cdd9j87s607fwpy0q62mfmmw0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-12-05 10:41
I'm going to close this as a duplicate of https://github.com/pulumi/pulumi/issues/4261. Its exactly the same issue that you can inadvertently go from `Output<T>` to `string`.

**Closed** 2024-12-05 10:41 UTC
Labels: kind/bug, area/sdks, resolution/duplicate
