### ISSUE TITLE
`ignoreChanges` does not respect paths with bracket notation

### ISSUE THREAD

**Issue by geigerzaehler** [pulumi/pulumi#9054] opened 2022-02-26 10:47 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
 
The [`ignoreChanges`](https://www.pulumi.com/docs/intro/concepts/resources/options/ignorechanges/) option does not respect property paths that use brackets and quotes like `x.y["z"]`. This is a particular problem for Kubernetes resources where annotation keys include `.`

Using v3.25.0 and the TypeScript SDK

### Steps to reproduce
1. Define the following resource
   ```typescript
   const service = new gcp.cloudrun.Service(
     "my-service",
     {
       name: "my-service",
       location: "europe-west1",
       template: {
         metadata: {
           annotations: {
             foo: "bar",
           },
         },
         spec: {
           containers: [
             {
               image: "us-docker.pkg.dev/cloudrun/container/hello",
             },
           ],
         },
        },
     },
     {
       ignoreChanges: [`template.metadata.annotations["foo"]`],
     },
   )
   ```
2. Run `pulumi up`.
3. Change the value of `templte.metadata.annotation.foo` to `qux`. 
4. Run `pulumi preview --diff`

Expected: The diff is empty.
Actual: The diff tells me that `bar` will be changed to `qux`.

If I use the following path in `ignoreChanges`, the diff is empty as expected
```typescript
{
  ignoreChanges: [`template.metadata.annotations.foo`],
}
```

**Comment by ysong6** [comment] 2023-01-10 04:31
How to ignore the whole annotations?  Can I ignore the whole annotations like this?
{
  ignoreChanges: [`template.metadata.annotations`],
}

**Comment by lucasweb3** [comment] 2023-01-25 22:19
+1 that this doesn't work and is critical for things like cloudrun where GCP injects attributes in metadata.annotations that have special characters in them like `"run.googleapis.com/operation-id"`. This is supported properly in plain terraform

**Comment by johnpena** [comment] 2023-03-13 20:07
I was able to ignore some properties like the ones @lucasweb3 mentions up until recently. I recently upgraded to pulumi `v3.57.1` and since upgrading I've noticed properties in my ignore changes list starting to appear in diffs. I unfortunately don't know which version of pulumi was working properly. I've resolved this issue by ignoring the entire property where needed (e.g. `metadata.annotations`) instead of the specific sub-property (e.g. `metadata.annotations["run.googleapis.com/client-version"]`).

**Comment by litalslice** [comment] 2023-06-05 15:46
Are there any updates on a fix for this issue?

I also have a problem ignoring the resources mentioned above:  `'template.metadata.annotations[client.knative.dev/user-image'` (and more fields like this one)

**Comment by dixler** [comment] 2023-06-05 16:29
Related to:
- https://github.com/pulumi/pulumi/issues/12581
- https://github.com/pulumi/pulumi/pull/13035

**Comment by nick-catalist** [comment] 2023-10-24 18:50
Bumping this -- I really don't know what to do when I _need_ Pulumi to manage some annotations for a GCP Cloud Run Service and _need_ it to ignore the ones that are automatically maintained by Google.

**Comment by PollRobots** [comment] 2023-11-29 23:33
I have attempted to reproduce this issue using the exact steps originally described by @geigerzaehler 

Behavior currently appears to be correct regardless of the format of the `ignoreChanges` property path.

I have tried both
- [X] `template.metadata.annotations["foo"]`
  - With a strings formatted as 
    ``` TypeScript
    'template.metadata.annotations["foo"]'
    `template.metadata.annotations["foo"]`
    "template.metadata.annotations[\"foo\"]"
    ```
- [X] 'template.metadata.annotations.foo'

In both of these scenarios:
- All changes to the `template.metadata.annotations.foo` property are ignored and do not appear in the diff
- changes to other annotations do appear in the diff.

I have tried 
- [X] changing the property name in the ignoreChanges string from `foo` to `bar` &mdash; i.e. `'template.metadata.annotations["baz"]'`

In this scenario
- property changes to `template.metadata.annotations.foo`  appear in the diff as expected

I suspect that the issue has been collaterally fixed in recent changes to property path handling.

I am closing this as **can't repo**

**Closed by PollRobots** 2023-11-29 23:33 UTC
Labels: kind/bug, area/engine, area/resource-options

**Comment by daaain** [comment] 2024-10-15 17:22
This is still broken for anything more complicated than simple letters.

None of these work:

```
      ignoreChanges: [
        'template.metadata.annotations["run.googleapis.com/client-name"]',
        'template.metadata.annotations[run.googleapis.com/client-name]',
        'template.metadata.annotations.run.googleapis.com/client-name',
      ],
```
