### ISSUE TITLE
Pulumi KMS secrets provider can't handle assumed web roles

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi#11482] opened 2022-11-29 08:24 UTC
### What happened?

I am using GitLab with the following guide:
https://docs.gitlab.com/ee/ci/cloud_services/aws/

It allows GitLab to use OpenId Connect to retrieve temporary AWS credentials by assuming a role. This is perfect, because it allows me to have GitLab runners which do not need permanent AWS credentials as variables in my project.

However, even though my script sets the `AWS_ACCESS_KEY_ID`, the `AWS_SECRET_ACCESS_KEY` and the `AWS_SESSION_TOKEN` of the temporary credentials, I get the following error when I try to run `pulumi up`:

> error: constructing secrets manager of type "cloud": secrets (code=Unknown): operation error KMS: Decrypt, https response error StatusCode: 400, RequestID: xxx, api error AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

This is despite the fact that I can retrieve an encrypted Parameter Store parameter that has been encrypted with the same key, from the AWS CLI:

```
aws ssm get-parameter --name "some-encrypted-parameter" --with-decryption
```

This verifies that my temporary credentials are working, but not in Pulumi. It's almost as if it doesn't support assumed roles?

Here's my code that sets up the temporary credentials (as per GitLab's guide).

```yaml
script:
  - >
    export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
    $(aws sts assume-role-with-web-identity
    --role-arn ${ROLE_ARN}
    --role-session-name "gitlab-session"
    --web-identity-token $CI_JOB_JWT_V2
    --duration-seconds 3600
    --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
    --output text))
```

### Steps to reproduce

1. Set up an encryption provider for Pulumi in KMS.
2. Create a key policy for the key which allows full access for the role and assumed role.
3. Assume the role and set environment variables based on the temporary AWS credentials.
4. Verify that the key works with an assumed role (for instance, decrypt a dummy parameter store value) via the AWS CLI.
5. Try doing any `pulumi config` operation or `pulumi up`, and see the error pop up.

### Expected Behavior

I expected Pulumi to respect the credentials that are present in the environment variables, even when it's for an assumed role (and with temporary credentials), also when using the secrets provider.

### Actual Behavior

> error: constructing secrets manager of type "cloud": secrets (code=Unknown): operation error KMS: Decrypt, https response error StatusCode: 400, RequestID: xxx, api error AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

### Output of `pulumi about`

```
CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.20.0
aws-native  0.40.2
dotnet      unknown
random      4.8.2
tls         4.6.1

Host     
OS       darwin
Version  13.0.1
Arch     arm64

This project is written in dotnet: executable='/usr/local/share/dotnet/dotnet' version='7.0.100'

Dependencies:
NAME              VERSION
Newtonsoft.Json   13.0.1
Pulumi            3.46.1
Pulumi.Aws        5.20.0
Pulumi.AwsNative  0.40.2
Pulumi.Random     4.8.2
Pulumi.Tls        4.6.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2022-11-29 12:09
Might be this needs the v2 sdk setup to work, have you tried adding "?awssdk=v2" to the pulumi secret manager url. Something like "awskms://example?awssdk=v2".

**Comment by ffMathy** [comment] 2022-11-29 12:32
Yes, that's already there.

**Comment by Frassle** [comment] 2022-11-29 17:11
OK got a couple of simple tests written up that demonstrate that those envvars aren't working as expected: https://github.com/pulumi/pulumi/pull/11484

This is _probably_ an issue in gocloud given how little logic is in pulumi itself to deal with this stuff, will dig into it.

**Comment by ffMathy** [comment] 2022-11-29 20:54
Awesome stuff @Frassle! Keep me posted.

**Comment by Frassle** [comment] 2022-12-02 15:23
I've [merged in some tests](https://github.com/pulumi/pulumi/pull/11484) to check the basics of using aws kms. It seems at least setting AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN for my session token is working. I didn't have any luck writing a test with a new assumed role (Still planning on doing that, but aws kept giving me an access denied via the sdk even though it would let me do it via the console).

**Comment by ffMathy** [comment] 2022-12-06 07:07
Maybe that last thing you describe with access denied is the true problem. Figuring out the root of that could be the solution.

**Comment by ffMathy** [comment] 2022-12-06 10:28
Hmmm alright. Perhaps my issue stems from something else then.

**Comment by Frassle** [comment] 2022-12-06 12:39
Yeh possibly, I'll try to find some time to get that assumed role test working. It would be good to have just for sanity and stability regardless of this issue, but it _might_ flag up something as well.

**Comment by Frassle** [comment] 2023-01-14 21:30
I haven't forgotten about this, just Christmas and other priorities pulled me away for a bit. I finally got a test running that shows that we can create a new role, give that role perms to the KMS key, then assume that role and use the key.

It's not using web identity roles, that would be the next test to write up but I'd be surprised if they behaved any differently in our test setup given it just results in the access key environment variables at the end same as any other role.

**Comment by ffMathy** [comment] 2023-01-15 05:49
Hmmm okay. It's just so strange that when I use a token directly I works, but not via Pulumi.

**Comment by Frassle** [comment] 2023-01-15 09:57
Yeh I'd suggest taking this to https://github.com/google/go-cloud/issues. I'd think it would just be picking up the same env var tokens as the aws cli, but the go-cloud team will know better.

**Comment by jaxxstorm** [comment] 2023-01-15 17:35
Can you try setting `AWS_SDK_LOAD_CONFIG=1` ?

**Comment by mlarose** [comment] 2023-03-08 14:31
@ffMathy I ran into the same _KMS Decrypt AccessDeniedException_ problem yesterday.

The underlying issue in our case was that the role used to execute pulumi did not have the permission to use the KMS key needed to decrypt the `encryptedkey` in our pulumi configuration.

If that's the case, while making sure that `aws sts get-caller-identity` returns what you expect, you should be able to reproduce that with something similar to:

```
pulumi config --show-secrets -s <your stack>
```

and also

```
aws kms decrypt --ciphertext-blob  '<value of encryptedkey in your pulumi config>'
```


If these fails, then I believe it's a matter of fixing your KMS Key policy & IAM role policy & permissions accordingly.

**Comment by justinvp** [comment] 2024-02-29 20:00
@ffMathy, is this still an issue for you? We've tried to reproduce with an assumed web role but haven't been able to reproduce the error you're getting.

**Comment by justinvp** [comment] 2024-11-11 23:23
Since we haven't heard back, I'm going to go ahead and close this as no repro. If you're still having the issue, please let us know!

**Closed by justinvp** 2024-11-11 23:23 UTC
Labels: kind/bug, area/secrets, awaiting-feedback, resolution/no-repro, customer/feedback
