### ISSUE TITLE
`ignoreChanges`: wildcard on array property doesn't work

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#12581] opened 2023-04-03 10:13 UTC
### What happened?

I specified this in the `ignoreChanges` resource property for an Azure Windows VirtualMachine resource:

```
            ignoreChanges: [
                "storageProfile.dataDisks[*].caching",
                "storageProfile.dataDisks[*].deleteOption",
                "storageProfile.dataDisks[*].diskSizeGB",
                "storageProfile.dataDisks[*].managedDisk.storageAccountType",
                "storageProfile.dataDisks[*].name",
                "storageProfile.dataDisks[*].toBeDetached",
                "storageProfile.osDisk.deleteOption",
                "storageProfile.osDisk.managedDisk.id",
            ]
```

but still got this as the diff:

```
         ~ storageProfile: {
              ~ dataDisks: [
                  ~ [0]: {
                          - caching     : "None"
                          - deleteOption: "Detach"
                          - diskSizeGB  : 1024
                          ~ managedDisk : {
                              - storageAccountType: "Premium_LRS"
                            }
                          - name        : "dataDisk1"
                          - toBeDetached: false
                        }
                ]
            }
```

### Expected Behavior

The wildcard should match the given properties for *each* object in the array, with no diff as a result. 

Listing a specific object index in the array worked:

```
            ignoreChanges: [
                "storageProfile.dataDisks[0].caching",
                "storageProfile.dataDisks[0].deleteOption",
                "storageProfile.dataDisks[0].diskSizeGB",
                "storageProfile.dataDisks[0].managedDisk.storageAccountType",
                "storageProfile.dataDisks[0].name",
                "storageProfile.dataDisks[0].toBeDetached",
                "storageProfile.osDisk.deleteOption",
                "storageProfile.osDisk.managedDisk.id",
            ]
```

### Steps to reproduce

Create a resource with an array property. Add `ignoreChanges` to one or more of the properties of an object in the array, like the docs specify:

```
root.array[*].field
root.array["*"].field
```

See the properties not being ignored.

### Output of `pulumi about`

CLI          
Version      3.59.1
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.38.0
azure-native  1.98.1
nodejs        unknown

Host     
OS       darwin
Version  13.3
Arch     arm64

This project is written in nodejs: executable='/Users/ringods/.volta/bin/node' version='v16.19.1'

Current Stack: team-ce/pulumiRefreshIssue/dev

TYPE                                            URN
removed the resource list as it came from a customer project

Found no pending operations associated with team-ce/dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ringods
User           ringods
Organizations  ringods, team-ce

Dependencies:
NAME                  VERSION
@types/node           16.18.21
@pulumi/azure-native  1.98.1
@pulumi/azure         5.38.0
@pulumi/pulumi        3.59.1

### Additional context

This should work according the docs:

```
root.array[*].field
root.array["*"].field
```

https://www.pulumi.com/docs/intro/concepts/resources/options/ignorechanges/

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2023-05-22 19:06
Is this azure-native or azure-classic? AFAIK the bridge implements ignoreChanges support so if the issue is in the bridged provider consider moving to pulumi-terraform-bridge.

**Comment by Frassle** [comment] 2023-05-23 08:33
Put together a quick test in the engine test framework that looks like `[*]` isn't being handled at all, so this is _at least_ an engine bug, I'll get that fixed then we can see if bridge also needs updating.

**Comment by t0yv0** [comment] 2023-05-23 13:41
The bridge should handle '*', but I'm open to testing it out if it's in doubt.

On the pre-PF code we have this recursive walk that is applied to the results of Diff:

https://github.com/pulumi/pulumi-terraform-bridge/blob/6a992d9ffc9684ed4a64e87ce06f8b5ff76c84e5/pkg/tfbridge/diff.go#L235-#L235

On the PF code, we had some debate as to what's the *right* thing for ignoreChanges to do, and ended up going with a simpler implementation that works at Pulumi level exclusively (not dropping to Terraform level) and is more in line with a verbatim read of the docs page on ignoreChanges. Likewise it should handle '*'. 

https://github.com/pulumi/pulumi-terraform-bridge/blob/6a992d9ffc9684ed4a64e87ce06f8b5ff76c84e5/pf/tfbridge/ignore_changes.go#L24-#L24

**Comment by ringods** [comment] 2023-05-24 06:06
@t0yv0 this comes from the Azure native provider. Only the `azure-native.compute.VirtualMachine` resource has a `storageProfile` property.

**Comment by t0yv0** [comment] 2023-05-24 13:09
Thank you Ringo! IN that case the bridge comments are not relevant there.

**Closed** 2023-06-21 22:49 UTC
Labels: kind/bug, area/sdks, customer/feedback, customer/lighthouse, area/resource-options
