### ISSUE TITLE
Nuget version 3.66.1-alpha.949ae7f throws Method not found: 'Pulumi.Output`1<!!0>

### ISSUE THREAD

**Issue by kle-sd** [pulumi/pulumi#16933] opened 2024-08-09 19:04 UTC
### What happened?

Was using bleeding edge 3.X for the `Pulumi` Nuget package when a non-related commit to our CI resulted in this exception:
```
 error: Running program '/home/runner/work/drop/drop/server/Drop.Infrastructure.Driver/bin/Debug/net8.0/Drop.Infrastructure.Driver.dll' failed with an unhandled exception:
      System.MissingMethodException: Method not found: 'Pulumi.Output`1<!!0> Pulumi.DeploymentInstance.Invoke(System.String, Pulumi.InvokeArgs, Pulumi.InvokeOptions)'.
         at Output<GetConnectionStringResult> Lbrlabs.PulumiPackage.Cockroach.GetConnectionString.Invoke(GetConnectionStringInvokeArgs args, InvokeOptions options)
```

The alpha version was `3.66.1-alpha.949ae7f` or `3.66.1-alpha.375c9f9`.

Downgrading to Pulumi 3.65.0 resolved the issue.

### Example

  var connectionString = Cockroach.GetConnectionString.Invoke(new Cockroach.GetConnectionStringInvokeArgs
  {
      Id = "cluster-id",
      Database = "database-name",
  });

### Output of `pulumi about`

CLI          
Version      3.125.0
Go Version   go1.22.5
Go Compiler  gc

Host     
OS       darwin
Version  14.5
Arch     arm64

Pulumi locates its logs in /var/folders/5c/txs7zcc56sg2jyx7sf7cjbf00000gp/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment] 2024-08-09 19:13
Hi there @kle-sd thanks for filing the issue! It is currently being addressed via https://github.com/pulumi/pulumi-dotnet/pull/318

Downgrading to v3.65.0 is indeed the recommended workaround, we have unlisted v3.66.0 from nuget but it seems like users are still able to download it

I will be closing this as duplicate of https://github.com/pulumi/pulumi-azure-native/issues/3510

**Closed** 2024-08-09 19:13 UTC
Labels: kind/bug, needs-triage, resolution/duplicate
