### ISSUE TITLE
Master build broken

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#6132] opened 2021-01-18 04:10 UTC
https://github.com/pulumi/pulumi/actions/runs/489227048

```
Error: pulumi/rpc.go:415:56: cannot convert ref.ID (type resource.PropertyValue) to type ID
Error: pulumi/rpc.go:423:8: ref.HasID undefined (type resource.ResourceReference has no field or method HasID)
Error: pulumi/rpc.go:424:54: cannot convert ref.ID (type resource.PropertyValue) to type ID
Error: pulumi/rpc.go:598:10: ref.HasID undefined (type resource.ResourceReference has no field or method HasID)
Error: pulumi/rpc.go:599:26: cannot convert ref.ID (type resource.PropertyValue) to type string
```

**Comment by stack72** [comment] 2021-01-19 14:39
I have reverted the said PR so that we can keep master clear

The issue is that https://github.com/pulumi/pulumi/pull/6125 was merged before https://github.com/pulumi/pulumi/pull/6116 and changes in #6125 are needed to be carried into #6116

**Closed by stack72** 2021-01-19 14:39 UTC
Labels: area/build, priority/P1
