### ISSUE TITLE
CloudWatch onSchedule should not depend on node_modules being in the current directory.

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi#4780] opened 2020-06-09 01:09 UTC
I have a minimal example Pulumi project with only the Pulumi code and yaml files in the project directory. The package.json, node_modules and all other typescript/javascript configuration is in a parent directory. In most cases, this works fine. When Pulumi has to use *pulumi/runtime/closure/codePaths* to bundle up dependencies to put into a lambda, it doesn't work.

For example, with this index.ts:
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const example: aws.cloudwatch.EventRuleEventSubscription = aws.cloudwatch.onSchedule(
  "example",
  "cron(0 12 ? * SAT *)", // Or any other expression
  async (event: aws.cloudwatch.EventRuleEvent) => { }); // Or any other code.
```

I can run `pulumi preview` and get errors like this:
```typescript
    Error: Error reading file '/pulumi/projects/main/pulumi/projects/autostop/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/pulumi/projects/main/pulumi/projects/autostop/package.json'
        at readFile (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:167:19)
        at computeDependenciesDirectlyFromPackageFile (/pulumi/projects/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:150:22)
        at /pulumi/projects/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:115:36
        at /pulumi/projects/node_modules/read-package-tree/rpt.js:162:20
```

It looks to my novice eyes like the function `allFoldersForPackages` in *pulumi/runtime/closure/codePaths.ts* shouldn't be hard-coding `"."` as the first parameter to `readPackageTree`, since all other uses of *package.json* allow it to be in the current directory or any ancestor directory.

I have put this issue in this project because it looks like most of the work to resolve it would have to be in *pulumi/runtime/closure/codePaths.ts*.

**Comment by leezen** [comment] 2020-06-09 03:27
I believe this is the same issue as https://github.com/pulumi/pulumi/issues/2661 and am closing this as a dupe of it. Please re-open if I've misunderstood.

**Comment by tenwit** [comment] 2020-06-09 20:18
The problem in #2661 seems to be that node_modules and package.json are in different directories. In my case, they are in the same directory, but it's not the directory that Pulumi.yaml is in, it's an ancestor directory.

I think it's not the same issue, but it is likely to be fixed at the same time. It almost certainly needs a different test to prove it though. I'm not using yarn, and everything is working fine when running pulumi (which it doesn't seem to be in #2661). I'm not familiar enough with rpt or yarn to say any more than that though.

**Comment by tenwit** [comment] 2020-06-09 20:23
Also, the workaround for #2661 (described in the issue) doesn't help. I'm already using that workaround to get my nested Pulumi project working (so I've voted for #2661, since I would benefit from it being resolved). But this issue is happening and (afaict) cannot be worked around.

**Comment by tenwit** [comment] 2020-06-09 20:25
> I believe this is the same issue as #2661 and am closing this as a dupe of it. Please re-open if I've misunderstood.

Since there's no workaround I think it should be reopened, but I don't seem to have the ability to do that?

**Comment by tenwit** [comment] 2020-06-09 20:38
The assumptions described in #4349 describe the problem in this case. I think it is likely that the same solution will resolve all three issues. I think that this issue describes a different use-case and warrants a different test to prove it.

**Comment by tenwit** [comment] 2020-06-09 21:12
Aha, found a better duplication: #2619. Specifically this comment: https://github.com/pulumi/pulumi/issues/2619#issuecomment-592543664

**Comment by leezen** [comment] 2020-06-09 21:15
Indeed :) Thanks for finding the correct one. Clearly, there are a bunch of not-so-great assumptions around where `package.json` and `Pulumi.yaml` live and in what relation to one another.

**Closed by leezen** 2020-06-09 21:15 UTC
