### ISSUE TITLE
1.10.1 release

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3885] opened 2020-02-06 19:08 UTC
- [x] language SDKs and CLI
- [ ] homebrew
- [ ] dockerhub
- [ ] docs and marked as latest-version
- [ ] Chocolatey

**Comment by stack72** [comment] 2020-02-06 19:10
@lukehoban this is a duplicate of #3883

**Closed** 2020-02-06 19:10 UTC
Labels: priority/P1
