### ISSUE TITLE
Importing gcp IAMMember from terraform fails

### ISSUE THREAD

**Issue by ill-eye** [pulumi/pulumi#14479] opened 2023-11-02 14:46 UTC
### What happened?

Trying to import existing infra into Pulumi from TF I get errors for all of the IAMMember resources.

### Example

Given this (edited, but it's the same for a real one) `my.tfstate`

```
{
  "version": 4,
  "terraform_version": "1.3.9",
  "serial": 2,
  "lineage": "df1d8fe7-b4c6-00d6-1f80-e4bb67f36710",
  "outputs": {
  },
  "resources": [
    {
      "mode": "managed",
      "type": "google_project_iam_member",
      "name": "log-accessor",
      "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "condition": [],
            "etag": "BwYJAnQ1LSM=",
            "id": "myProject/roles/logging.viewAccessor/serviceAccount:my-eks-acc@myProject.iam.gserviceaccount.com",
            "member": "serviceAccount:my-eks-acc@myProject.iam.gserviceaccount.com",
            "project": "myProject",
            "role": "roles/logging.viewAccessor"
          }
        }
      ]
    }
  ],
  "check_results": null
}
```

`pulumi import --from terraform my.tfstate`

results in an error like this: 

```  
gcp:projects:IAMMember (log-accessor):
    error: Preview failed: importing myProject/roles/logging.viewAccessor/serviceAccount:my-eks-acc@myProject.iam.gserviceaccount.com: Wrong number of parts to Member id [myProject/roles/logging.viewAccessor/serviceAccount:my-eks-acc@myProject.iam.gserviceaccount.com]; expected 'resource_name role member [condition_title]'.
```

Same is true for ` gcp:serviceAccount:IAMMember`, `gcp:storage:BucketIAMMember` and `gcp:spanner:DatabaseIAMMember`, but my guess is that it's true for all of them.
 

### Output of `pulumi about`

CLI
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.67.0
python  unknown

Host
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.11.5'

Backend
Name           m-F5KFF0B5K7GF
URL            gs://boatgame-pulumi-state
User           ilya.pavlenkov
Organizations
Token type     personal

Dependencies:
NAME        VERSION
pip         23.3.1
pulumi-gcp  6.67.0
setuptools  68.2.2
wheel       0.41.3

Pulumi locates its logs in /var/folders/b0/x1sgmny10tj23cwxl0vbtpd80000gn/T/ by default
warning: Failed to get information about the current stack: No current snapshot

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2023-11-02 15:53
Another instance of https://github.com/pulumi/pulumi-converter-terraform/issues/43 I think

**Comment by justinvp** [comment] 2023-11-03 23:01
Thanks for opening the issue, @ill-eye. This looks like a duplicate of https://github.com/pulumi/pulumi-converter-terraform/issues/67

**Closed by justinvp** 2023-11-03 23:01 UTC
Labels: kind/bug, resolution/duplicate
