### ISSUE TITLE
AWS ACM validation timing issue on create.

### ISSUE THREAD

**Issue by jonjitsu** [pulumi/pulumi#3063] opened 2019-08-09 21:40 UTC
With the following pulumi program:
```
const cert = new aws.acm.Certificate("cert", {
    domainName: 'example.com',
    subjectAlternativeNames: ['www.example.com'],
    validationMethod: "DNS",
});

const zone = pulumi.output(aws.route53.getZone({
    name: 'example.com',
    privateZone: false,
}));

const v1 = new aws.route53.Record("v1", {
    name: cert.domainValidationOptions[0].resourceRecordName,
    records: [cert.domainValidationOptions[0].resourceRecordValue],
    ttl: 60,
    type: cert.domainValidationOptions[0].resourceRecordType,
    zoneId: zone.id,
});

const v2 = new aws.route53.Record("v2", {
    name: cert.domainValidationOptions[1].resourceRecordName,
    records: [cert.domainValidationOptions[1].resourceRecordValue],
    ttl: 60,
    type: cert.domainValidationOptions[1].resourceRecordType,
    zoneId: zone.id,
});

const certValidation = new aws.acm.CertificateValidation("cert", {
    certificateArn: cert.arn,
    validationRecordFqdns: [
        v1.fqdn,
        v2.fqdn,
    ],
});
```

When I run `pulumi up -y`, the first invocation fails with the error:
```
     Type                    Name                           Status         Info
 +   pulumi:pulumi:Stack     mystack                        created
 +   ├─ aws:acm:Certificate  cert                           created
     └─ aws:route53:Record   v2                             **failed**     1 error

Diagnostics:
  aws:route53:Record (v2):
    error: unexpected null property records[0]
```

the second invocation succeeds though. So if I effectively run pulumi with `pulumi up -y || pulumi up -y` I get a successful build.

There appears to be some kind of timing issue going on.

**Comment by jonjitsu** [comment] 2019-08-14 19:01
Switching node version from 11.3.0 to 8.11.4 fixed this issue.

**Comment by lukehoban** [comment] 2019-08-19 23:41
@stack72 Can we reproduce this and understand whether there is a Pulumi issue, or an upstream issue here?

**Comment by lukehoban** [comment] 2019-08-20 04:17
I tried this several times, and with a few different configurations, and was not able to reproduce it.

I strongly suspect this was fixed a couple weeks ago with https://github.com/pulumi/pulumi/pull/3014.  One variant of the issue that that PR resolved was https://github.com/pulumi/pulumi/issues/2433, which happened to trigger the same `error: unexpected null property` as is seen here.  It's also somewhat consistent with the commentary above about this happening only initially - as that issue effectively only triggered on initial preview.

This was fixed in `@pulumi/pulumi`, so if you ensure you are running at least [`1.0.0-beta.1`](https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#100-beta1-2019-08-13) of that library (check your `package-lock.json`) then I would expect you will not see this.

**Closed by lukehoban** 2019-08-20 04:17 UTC
Labels: feature/q3, kind/bug

**Comment by lukehoban** [comment] 2019-08-20 04:48
Actually - there is another way to hit this which may be the more likely case for those seeing it.

If you ran a program that was slightly different than what's above - you could trigger this - specifically if you remove `subjectAlternativeNames: ['www.example.com'],`.  In that case, `cert.domainValidationOptions` will return only a single item (for `example.com`), and then `cert.domainValidationOptions[1].resourceRecordValue` will be undefined, which will trigger the same `error: unexpected null property records[0]` error.  This error is technically correct - a null/undefined value was passed in for `records[0]`, which is not supported as legal input to a `aws.route53.Record`.  This couldn't be caught during the preview in this case, so would only be reported as part of the initial update.

In this case things appear to be behaving as intended, expect the error message could be more helpful.  Opened https://github.com/pulumi/pulumi-terraform/issues/467 on improving the error message.

```
$ pulumi up
Previewing update (dev):

     Type                              Name            Plan       
 +   pulumi:pulumi:Stack               pulumi3063-dev  create     
 +   ├─ aws:acm:Certificate            cert            create     
 +   ├─ aws:route53:Record             v2              create     
 +   ├─ aws:route53:Record             v1              create     
 +   └─ aws:acm:CertificateValidation  cert            create     
 
Resources:
    + 5 to create

Do you want to perform this update? yes
Updating (dev):

     Type                    Name            Status         Info
 +   pulumi:pulumi:Stack     pulumi3063-dev  created        
 +   ├─ aws:acm:Certificate  cert            created        
 +   ├─ aws:route53:Record   v1              created        
     └─ aws:route53:Record   v2              **failed**     1 error
 
Diagnostics:
  aws:route53:Record (v2):
    error: unexpected null property records[0]
```
