### ISSUE TITLE
Python SDK output combinators treats lists and tuples differently

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#8321] opened 2021-11-01 15:25 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It is slightly surprising that the following behavior differs:

```python

def fail(result):
  raise Exception()

# When using tuples, apply runs and the program fails:
pulumi.Output.from_input({'key': (unknown(), 1)}).apply(fail)

# When using lists, apply does not run and the program does not fail:
pulumi.Output.from_input({'key': [unknown(), 1]}).apply(fail)

```

It seems that the reason for this is that Pulumi SDK constructs recur into lists and dicts but not tuples. It can be surprising to a Python user. But an argument can also be made for this being by design. 

### Steps to reproduce

Expected:  lists and tuples behave similarly for the purposes of Pulumi core construct semantics
Actual: Pulumi core constructs recur into lists but not tuples when finding nested outputs

**Comment by justinvp** [comment] 2023-07-27 07:23
Duplicate of https://github.com/pulumi/pulumi/issues/6635

**Closed by justinvp** 2023-07-27 07:23 UTC
Labels: kind/bug, area/sdks, language/python, resolution/duplicate
