### ISSUE TITLE
Extremely slow `pulumi up`/`pulumi refresh` performance due to many sequential `api/encryptValue` calls

### ISSUE THREAD

**Issue by mccutchen** [pulumi/pulumi#16921] opened 2024-08-08 22:09 UTC
### What happened?

We have a Pulumi project that uses Pulumi Cloud to store both resource state and secrets where we are experiencing pathologically slow performance on `pulumi refresh` and `pulumi up` commands, seemingly due to many sequential `api/encryptValue` calls.

This makes pulumi painful for our team to work with, so we'd really like to learn whether there are any steps we can take to improve this situation, short of painstakingly splitting this project into smaller projects. Should we not be using Pulumi Cloud? Should we have chosen a different secrets backend?

Any advice or guidance you can provide would be welcome!  More details on the behavior we're observing added below.

#### `pulumi refresh` behavior

The behavior we see during a no-op `pulumi refresh` is that pulumi itself reports that the refresh is finished quickly (in 10-20 seconds), but then the command consistently hangs for more than a minute on our smallest stack (~600 resources) and for more than 8 minutes on our largest stack (~1700 resources) before finally exiting.

Execution traces (via `pulumi refresh --tracing=...`) indicate that — in the case of our largest stack — the entire time the process is hung after the refresh has completed, it is executing somewhere north of 1000 sequential calls to `api/encryptValue`.

(I can't give a concrete number because Cmd-F in my browser only reports "More than 1000" matches and my browser freezes when I try to export the trace as JSON.)

An example run, w/ Pulumi's own timings and the output from `time`:

```
Refreshing (REDACTED/production)

View in Browser (Ctrl+O): https://app.pulumi.com/REDACTED/production/updates/729

...

Resources:
    1659 unchanged

Duration: 18s
```
```
pulumi  25.20s user 4.82s system 5% cpu 8:22.05 total
```

#### `pulumi up` behavior

We see similar behavior during a no-op `pulumi up`, except that the process hangs at the beginning instead of the end (immediately after printing the `View in Browser (Ctrl+O):` link and `Type Name Status` headers). For that same ~1700 resource stack, it consistently hangs for 10+ minutes before taking any observable action.

Execution traces show that the hang is again 1000+ sequential calls to `api/encryptValue` before we begin to see some `Diff`/`api/patchCheckpointDelta`/`api/postEngineEventBatch`/etc event spans mixed in with continued `api/encryptValue` spans.

Example run:

```
Updating (REDACTED/production)

View in Browser (Ctrl+O): https://app.pulumi.com/REDACTED/production/updates/730

...

Resources:
    1657 unchanged

Duration: 11m9s
```
```
pulumi    39.22s user 9.54s system 7% cpu 11:28.89 total
```

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.128.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.39.0
resource  aws-native  0.108.2
language  go          unknown
resource  kubernetes  4.13.1
resource  random      4.16.2
resource  tls         4.11.1

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in go

[redacted stack resource list]

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mccutchen
User           mccutchen
Organizations  mccutchen, REDACTED
Token type     personal

Dependencies:
NAME                                        VERSION
github.com/apparentlymart/go-cidr           v1.1.0
github.com/healthbyro/rodeo                 v1.96.1714661570
github.com/pulumi/pulumi-aws-native/sdk     v0.108.2
github.com/pulumi/pulumi-aws/sdk/v6         v6.39.0
github.com/pulumi/pulumi-kubernetes/sdk/v4  v4.13.1
github.com/pulumi/pulumi-random/sdk/v4      v4.16.2
github.com/pulumi/pulumi-tls/sdk/v4         v4.11.1
github.com/pulumi/pulumi/sdk/v3             v3.119.0
github.com/rs/zerolog                       v1.31.0
gopkg.in/yaml.v2                            v2.4.0
```

### Additional context

If it would be useful, I'd be happy to provide example execution traces, or a summary of the resources in this project, or details about our Pulumi account, or anything else.  Just let me know!

Note: This seems similar to https://github.com/pulumi/pulumi/issues/7682, but the traces on that issue look meaningfully different from the traces we're seeing.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-08-09 07:32
I think this is looks like the same core issue as https://github.com/pulumi/pulumi/issues/15293. We have had some internal conversations about why this is, some of that is tracked by an internal ticket (https://github.com/pulumi/pulumi-service/issues/4942).

I'm going to close this as a duplicate of #15293, but thanks for the extra information on this.

**Closed by Frassle** 2024-08-09 07:32 UTC
Labels: kind/bug, impact/performance, resolution/duplicate
