### ISSUE TITLE
Pulumi Automation API

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#3901] opened 2020-02-10 01:36 UTC
**Update:** _we have shipped the preview of the Automation API! Read more [here](https://www.pulumi.com/blog/automation-api/). This issue will be used to track completion of this feature._

Every language should have runtime APIs that allows for pulumi program execution. 

Executing a program today looks like:

```sh
cd  some_pulumi_project
pulumi stack init
pulumi set config --foo=bar
pulumi up
```

Users should be able to achieve the same outcome from something as simple as:

```sh
node pulumi_program.js
dotnet run PulumiProject.csproj
go run pulumi_program.go
python pulumi_program.py
```

The focus here should be on ergonomics. We have ways to do this today with our go based integration test framework. This still requires that the pulumi program exists on the local filesystem with the appropriate yaml description and config file. 

Ideally, a runtime API allows execution of not just files on disk, but arbitrary function entry points:
```ts
// some_program.ts
// running `tsnode some_program.ts` results in an S3 bucket getting created. 

import * from "@pulumi/pulumi";
import { S3 } from "@pulumi/aws";

// our "entrypoint" function
const createBucket = () => {
  new S3.Bucket("mybucket")
}

const stackDescription = {
  name: 'myOrg/myStack',
  createIfNotExists: 'true'
};

const updateOptions = {
  expectNoChanges: false,
  pulumiCreds: { /* allow specifying access tolken to pulumi service, or read ambient env vars */ }
};

const updateResult = await pulumi.up(createBucket, stackDescription, updateOptions);
if(updateResult.err) {
  const code = updateResult.err.code
  /* respond to structured output*/
}
```

This enables multiple scenarios:
1. Integration testing: programmatically stand up and tear down stacks.
2. Rich tooling for deployment automation. Respond to events like pending deletions that fail a deployment.
3. Enable runtime resource creation scenarios like SaaS. Enable a runtime workflow where a new stack is stood up in response to a new user signup. 
4. Use existing package/dep managers (go mod, npm, pip, nuget) to version and pin the "engine runtime".

**Comment by damianh** [comment] 2020-03-05 01:10
Thanks for creating this issue! I wrote the below in slack; I think we are on the same page!

> Some feedback from when I demonstrate pulumi .net support to .net people - "why can't I just run my program?". The initial impressions are that requiring pulumi CLI to run the IaC instead of the standard dotnet run  is "non-standard" and "against the grain".  The expectation is that the .net program should be spawning the pulumi "engine" and not the other way around. And to be honest, I can see their point.
There was also a couple of other comments
> - "I want to do other things in my program as part of deployment such as a db migration." 
> - "I want to use this to define resources of my own services"

> This got me thinking a bit that it inverts things and turns pulumi into more of a platform and a bit more into orchestration which is bit of a fundamental architectural shift, afaik.
Anyway,  just thought it would be interesting to share

**Comment by clstokes** [comment] 2020-03-05 16:53
Related to https://github.com/pulumi/pulumi/issues/2506.

**Comment by gsuess** [comment] 2020-03-17 22:14
This would also allow for constructors to not have side-effects on the environment.

When I do `new S3.Bucket()` I don't want to do anything with that bucket definition unless I pass it to `pulumi.up()` or some other function that consumes it. If it goes out of scope, then it should be garbage collected and not held in some registry in the background.

With that there should be no need for wrapping the construction of these objects into functions.

I would prefer an api like this:

```js
const context = pulumi.createContext();
const bucket = new S3.Bucket("myBucket");

context.add(bucket);

pulumi.up(context, ...options);
```

**Comment by sergeyr87** [comment] 2020-04-15 15:03
> This would also allow for constructors to not have side-effects on the environment.
> 
> When I do `new S3.Bucket()` I don't want to do anything with that bucket definition unless I pass it to `pulumi.up()` or some other function that consumes it. If it goes out of scope, then it should be garbage collected and not held in some registry in the background.
> 
> With that there should be no need for wrapping the construction of these objects into functions.
> 
> I would prefer an api like this:
> 
> ```js
> const context = pulumi.createContext();
> const bucket = new S3.Bucket("myBucket");
> 
> context.add(bucket);
> 
> pulumi.up(context, ...options);
> ```

It would be great if we could do like in the example above 
make my life much easier

**Comment by lukehoban** [comment] 2020-04-15 15:36
> It would be great if we could do like in the example above make my life much easier

Curious to hear more about this.  I definitely understand the desire for this style of API from an aesthetic (and conceptual) perspective - but curious to understand what scenarios it would enable or make easier?

**Comment by mtparet** [comment] 2020-04-17 07:57
>  but curious to understand what scenarios it would enable or make easier?

It's already nice to use current programmation language within pulimi but the world is currently not implemented within pulimini. 
So we cannot use pulimi inside our current world and I think we are missing 80% of what pulimi could bring.

For example I am writing an operator using https://github.com/zalando-incubator/kopf and I would like to manage resources inside it using pulimi but I cannot. It's too bad because historically we are on terraform but we would have switched to pulimi if we could use it everywhere.

**Comment by mazamats** [comment] 2020-04-19 19:26
> > but curious to understand what scenarios it would enable or make easier?
> 
> It's already nice to use current programmation language within pulimi but the world is currently not implemented within pulimini.
> So we cannot use pulimi inside our current world and I think we are missing 80% of what pulimi could bring.
> 
> For example I am writing an operator using https://github.com/zalando-incubator/kopf and I would like to manage resources inside it using pulimi but I cannot. It's too bad because historically we are on terraform but we would have switched to pulimi if we could use it everywhere.

I see a lot of value being able to run pulumi inside of operators.

State management sucks to implement, especially if your operator creates a large amount of resources. If the operator creates non k8s resources you now have to use cloud provider sdk's.

This could make cleanup of operator created resources a lot easier too, especially in scenarios where you're changing naming schemas for resources.

**Comment by hausdorff** [comment] 2020-04-22 18:27
> Curious to hear more about this. I definitely understand the desire for this style of API from an aesthetic (and conceptual) perspective - but curious to understand what scenarios it would enable or make easier?

It's reasonably common to need to create resources in response to dynamic user requests. Suppose a user sends you some HTTP POST to upload an attachment, and in response you create/upload to S3 bucket. It's reasonably easy to do this by invoking the relevant SDKs from your server, and it's hard to do in any principled way with Pulumi. In general any time you go to a website and sign up a new account and it gives you a waiting screen that's like "we're setting up your account"—they're doing that.

IME most of these use cases revolve around having to provision storage rather than compute or networking though—so it's common to have to provision a database or S3 bucket (and anything they need, like roles) but much less common to provision a new EC2 instance (unless you're deploying a database on it). I've personally had to do all of these things myself, I'll have to do it again, and it's always a pain.

In Kubernetes there are a different set of GitOps-related use cases, and I got asked about them 1-2 times a week when I worked on the Kubernetes provider. Making this work really well is not going to be as simple as opening up the runtime API though. You'll need a way to report success and failure back to users, for example, since the operator would be continuously running. Users could still wire all that up themselves, but that is probably a long-ish road full of painful things to debug.

**Comment by thejosephstevens** [comment] 2020-04-22 23:58
Hey all! I'm glad I ran into this thread, I actually hadn't realized yet that Pulumi can't quite be triggered directly from a live service without setting up a new process.

I'm just starting design work on a service that will expose internal infrastructure configuration options to users of our product (starting with basic autoscaling config, but hoping to extend to broader management of kubernetes and cloud resources). The way I had been looking at the design initially was to just run the service like a cron job - pick up configuration from MySQL, apply it, and hopefully don't crash in the process. Unfortunately that doesn't actually answer a number of questions about the service like interactivity (I push a button and set min nodes to 5, I'd like to get some sort of feedback that it's happening or error logs if it fails). That lends itself a bit better to a live service that is handling these requests as they come in. What it sounds like is I'll still have to treat Pulumi like a one-shot executor that I may call from some central manager, and manage the reality that I have to handle all of the lifecycle edge cases of jobs rather than a service (scraping output from kube rather than responses on some connection, sanity checking termination cases, scheduling a secondary resource in order to run jobs rather than kicking off goroutines...).

It would simplify things a bit if I could just put together a single service that triggers pulumi.up on various events for various contexts (potentially with more than one context managed simultaneously by one service).

**Comment by orangelabs-dev** [comment] 2020-04-23 08:02
Personally I'd like to see this come to life, in particular, triggering `pulumi up` from a web interface. I can definitely also see that throughout various stages of deploying resources, I would want to leverage something like WebSockets to push progress updates to the web UI ensuring a user has a pleasant user experience.

**Comment by ringods** [comment] 2020-04-23 14:55
> Curious to hear more about this. I definitely understand the desire for this style of API from an aesthetic (and conceptual) perspective - but curious to understand what scenarios it would enable or make easier?

@lukehoban it depends a bit on how "big" this transformation would be. If this would just be a thin wrapper around the CLI, it wouldn't bring much benefit. But if this issue is about rethinking the architecture so that the language runtime becomes the driver and Pulumi  a language library or framework, you open not a can of worms, but a barrel of opportunities. v3.0? 😉 

Currently, it is the Pulumi CLI which is in charge of starting the runtime. This makes it hard for Pulumi to catch up with all possible options and evolution each of these runtimes have. In this mode, I assume you will play catch-up for the years to come.

In my specific case, I refer to running Pulumi with Yarn v2 in [Plug'n'Play](https://yarnpkg.com/features/pnp) mode. In such a setup, there isn't a `node_modules` folder. See my initial work in #4349 which I eventually had to stall because I don't know enough of both the Pulumi internals as well as the Yarn v2 internals *and* NodeJS module resolution. 

Besides Yarn as the successor to NPM, there is also [`pnpm`](https://pnpm.js.org/) as another NodeJS package manager. Also, no luck there with Pulumi CLI in the driver seat. And then there is also the Deno runtime (#3838)...

Another aspect which you are investigating is using Pulumi code written for one runtime and invoking it from another runtime, e.g. a Pulumi Python project using Pulumi abstractions written in Typescript. This is tracked in #2430. The multi-language aspect is already something worked on by Oracle in the [GraalVM](https://www.graalvm.org) project. They name such multi-language setups [polyglot applications](https://www.graalvm.org/docs/reference-manual/polyglot/).

**Comment by a-robu** [comment] 2020-05-13 20:23
> This got me thinking a bit that it inverts things and turns pulumi into more of a platform and a bit more into orchestration which is bit of a fundamental architectural shift, afaik.

This makes me think of [the difference between frameworks and libraries](https://www.freecodecamp.org/news/the-difference-between-a-framework-and-a-library-bd133054023f/) (frameworks tend to impose themselves on source code, while libraries are made to be easily used in source code).

### Experimenting with new libraries

In my case, I would get a better feel of how Pulumi works if I could experiment with it in a REPL. For example, I would like to be able to:
- declare a few some in the REPL,
- store the resource declarations in variables and explore the properties available on those objects,
- ask Pulumi which actions it would take to _if_ I asked it to provision those resources,
- manually trigger any of those individual provisioning actions from the REPL,
- and so on.

### Motivating example

Here's an example of how I would have found these features useful: I tried to define a new type of resource dynamically (a `#cloud-config` configuration with a random key pair) and I while writing this code I wanted to know if I succeeded in linking the provider to the resource correctly, but this was difficult to infer because the only way to execute the code was by running `pulumi up`. This command is slowish (can take seconds to run) and provides little information other than a success/failure. I just tried to get the provider working through trial and error and then gave up after a while.

**Comment by shoubamzlibap** [comment] 2020-05-29 08:47
I like the idea. 
My use case: after I have created infrastructure with pulumi, I would like to work on my infrastructure with ansible. There are several way to do this and my way might not be the best, however I would still like to describe it.
What I would like to do is to use my python code that uses pulumi, and also create the ansible inventory (file) from that code. The problem is, its not so easy to aggregate all the IP information from all servers in one place, since they are all Output Objects ... so having some method that would block until the information is available, and then just return it as a string would be helpful.

**Comment by mvila** [comment] 2020-06-07 01:45
I plan to build a tool using Pulumi internally, and I'd like to distribute this tool as an NPM package so it can be easily consumed by any Node.js developers. Since Pulumi would be an internal dependency of my tool, I don't want to expose it to the user. For example, my tool should work even without the Pulumi CLI installed on the user's machine.

I love Pulumi, and I would really like to use it in my tool, but not being able to embed it is a real blocker.

**Comment by donovanmuller** [comment] 2020-06-13 12:16
@mazamats I am [similarly](https://github.com/pulumi/pulumi/issues/3901#issuecomment-616211363) intrigued with using Pulumi inside Kubernetes Operators/controllers and it feels like a runtime API (this issue)  combined with https://github.com/pulumi/pulumi/issues/2058#issuecomment-643614411 would make that much simpler to implement.

Allowing a Pulumi based alternative to [Kubeform](https://kubeform.com/) or this experimental [Rancher Terraform controller](https://github.com/rancher/terraform-controller).

**Comment by clstokes** [comment] 2020-07-08 22:37
Related https://github.com/pulumi/pulumi/issues/4705.

**Comment by unthought** [comment] 2020-07-13 12:05
To provide another usecase: Pulumi currently assumes that it can go from the state recorded in the state file to the state expressed in the current resource DAG directly, and that the `dependsOn` and other constraints expressed in Pulumi itself are sufficient. However, it's really hard to do certain transitions in one step. A few examples:

Upgrading cert-manager on k8s seems to always devolve into a multi-step operation, where you undeploy the old one, and then deploy the new one, trying to somehow restore (and convert) the certificate resources you had on the old one faithfully enough for dependent stacks to not get completely confused (this is probably true for anything that doesn't guarantee api stability).

Upgrading a database major version isn't always possible in-place, be that for compatibility reasons, because the cloud provider doesn't support it, or just because you'd like to do it with minimal downtime. Then that means that you want to do something like this:
* create a clone of the cluster and start receiving replication events.
* block the old cluster from accepting writes and fail all apps over to the new master.
* rewrite the urns of the old and new resources so that the old cluster urns are backed by the new resources, and the old resources are independent (btw quite tricky to achieve with aliases only).
* shut down the old resources
This involves a lot of manual work currently with pulumi, and if you're adventurous, a lot of shell scripts. If you have a lot of almost identical deployments, this is a lot of repetition, and a lot of opportunity for human error.

My biggest complaint with Pulumi (or any other IaC solution, out of which I like Pulumi the best) is that infrastructure transitions are not treated as first class citizens, but are a substantial part of the problems faced in reality. One thing that makes IaC so difficult is that you basically are migrating (distributed) state all the time. In regular programming, you have a bug, you fix it, and you don't have to worry (in most cases) about converting old state to new state. In IaC it's inverted, you almost always have to worry about old state, and how your change will impact it, and what steps you have to go to go from all currently running stacks of that resource to the new desired one, possibly requiring interim steps (and cross your fingers to not forget something, or you'll be fixing state manually).

If pulumi was really a library that can be called, you can apply all sorts of interesting solutions to it. You could express workflows like the above in code, and put it behind a workflow engine, with manual approvals and gates (can be somewhat achieved today with clever conditional global transformations, but it's a quite limited, because you can't freely edit the DAG in transformations, eg. AFAIK you can't create or remove resources during transformation).

So definitely interested, even if it requires probably a non-trivial 3.0 upgrade path from an API perspective.

**Comment by gitfool** [comment] 2020-08-04 19:22
Nobody mentioned it, probably because it's obvious, but this would make debugging much more natural and hence easier to orchestrate. For example, right now I have to jump through hoops to debug with .NET Core and either Visual Studio or Visual Studio Code, and it gets messy when using containers to capture the development environment.

**Comment by djvs** [comment] 2020-08-10 14:15
This is absolutely necessary for my current project, being forced to use only a CLI interface would force me to containerize or execute shell commands to handle deployments on an abstract level; considering leaving Pulumi over this.

**Comment by EvanBoyle** [comment] 2020-09-02 15:14
# Automation API - Go Alpha
We're really excited to announce the alpha for [Automation API](https://github.com/pulumi/pulumi/tree/master/sdk/go/x/auto), available today for [Go](https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto?tab=doc#pkg-overview). The Automation API is the programmatic interface interface for driving Pulumi programs without the CLI. It was designed for a multitude of complex deployment orchestration and tooling scenarios such as:

- Driving pulumi deployments within CI/CD workflows
- Integration testing
- Multi-stage deployments such as blue-green deployment patterns
- Deployments involving application code like database migrations
- Building higher level tools, custom CLIs over pulumi, application frameworks, etc.
- Using pulumi behind a REST or GRPC API
- Fully featured debugging of "inline" Pulumi programs as they execute

## Overview

### Inline Programs

We've eliminated the need for a separate Pulumi project. With `inline` pulumi programs your deployment code is just another function:

```go
 bucketOutputKey := "bucketName"
 stack, err := NewStackInlineSource(ctx, "myOrg/myProj/myStack", func(pCtx *pulumi.Context) error {
	bucket, err := s3.NewBucket(pCtx, "bucket", nil)
	if err != nil {
		return err
	}
	pCtx.Export(bucketOutputKey, bucket.Bucket)
	return nil
 })
```

You can set config, perform updates, and manage the full lifecycle all from the same `main.go`:

```go
// set required config for our stack
stack.SetConfig(ctx, "aws:region", auto.ConfigValue{ Value:"us-west-2", Secret: false })
// perform the up
result, err := stack.Up(ctx)
// get structured output including the outputs from our update
fmt.Println(result.Outputs[bucketOutputKey].Value.(string))
```

Inline programs mean that declarative infrastructure can be just another part of your app. It enables creating higher level tooling and application frameworks. We prototyped a Heroku-like tool called [halloumi](https://github.com/EvanBoyle/halloumi) (Heroku + Pulumi = halloumi 😎) to demonstrate the sort of abstractions that are possible to build:

```go
app := app.NewApp("petStore")

// a cloud web service that returns a number [0-100)
// halloumi creates all of the AWS infrastructure including 
// an ecs cluster, ecr registry, ecs tasks, load balalancers...
randomNumberService := web.NewWebService("randomNumber", func() http.Handler {
    // a normal HTTP handler, halloumi takes care of running this in the cloud
    r := mux.NewRouter()
    handler := func(w http.ResponseWriter, r *http.Request) {
        rand.Seed(time.Now().UnixNano())
        fmt.Fprintf(w, "%d", rand.Intn(100))
    }
    r.HandleFunc("/", handler)
    return r
})

app.Register(randomNumberService)
```

We're excited to see what sort of open source tools and frameworks are possible with Automation API.

### Git Repo Programs

Automation API also includes primitives to easily work with programs in remote git repositories. In this example we deploy a static website example from the [Pulumi examples repo](https://github.com/pulumi/examples/tree/master/aws-go-s3-folder):

```go
// fetch the static website program from this git repo and create a new stack
stack, err := NewStackRemoteSource(ctx, "myOrg/myProj/myStack", GitRepo{
	URL:         "https://github.com/pulumi/examples.git",
	ProjectPath: filepath.Join("aws-go-s3-folder"),
})
stack.SetConfig(ctx, "aws:region", auto.ConfigValue{ Value:"us-west-2", Secret: false })
// perform the up
result, err := stack.Up(ctx)
// print the website URL to the console
fmt.Println(result.Outputs["websiteUrl"].Value.(string))
```

Notably, the Pulumi Kubernetes Operator is a greate example of this kind of workflow. We're updating it under the hood [to use the automation API](https://github.com/pulumi/pulumi-kubernetes-operator/compare/metral/automation-api).

Working with git repos isn't limited to Go projects. You can fetch and work with Pulumi programs in any language including the [Pulumi EKS package](https://github.com/pulumi/pulumi-eks), [KX](https://github.com/pulumi/pulumi-kubernetesx), and [AWSX](https://github.com/pulumi/pulumi-awsx). Automation API enables different teams to author components in different languages, serving as the glue that orchestrates it all together into a fully functioning distributed system.

### Existing CLI Programs
Automation API of course works with existing CLI programs that you're working with today. Just specify a relative path to the working directory and project and stack settings (Pulumi.yaml, Pulumi.stack.yaml) will be ambiently picked up:

```go
stack, err := NewStackLocalSource(ctx, "myOrg/myProj/myStack", filepath.Join("..", "path", "to", "project"))
```

Check out [this example](https://github.com/EvanBoyle/automation-api-examples/tree/main/inline_local_hybrid) that shows how to refactor your package structure allowing a hybrid between debuggable inline programs and a local CLI driven program to get the the best of both worlds.

## Docs and Examples

We've written comprehensive GoDocs, as well as a suite of examples. We'll be adding more in the coming weeks and look forward to your contributions as well:

- [GoDoc](https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto?tab=doc#pkg-overview) with comprehensive examples across the API surface area
- [Automation API Examples](https://github.com/EvanBoyle/automation-api-examples): a repo with end to end walkthroughs for multiple facets including [inline programs](https://github.com/EvanBoyle/automation-api-examples/tree/main/inline_program), [git workflows](https://github.com/EvanBoyle/automation-api-examples/tree/main/git_repo_program), [inline/cli hybrid programs](https://github.com/EvanBoyle/automation-api-examples/tree/main/inline_local_hybrid), and [multi-stack orchestration](https://github.com/EvanBoyle/automation-api-examples/tree/main/multi_stack_orchestration)
- The [source code](https://github.com/pulumi/pulumi/tree/master/sdk/go/x/auto) for Automation API
- [halloumi](https://github.com/EvanBoyle/halloumi): a prototype of a heroku-like tools that shows what sort of powerful abstractions can be built when infrastructure is just another part of your application code.
- The [Pulumi Kubernetes Operator](https://github.com/pulumi/pulumi-kubernetes-operator/compare/metral/automation-api): a real world example of exposing Pulumi behind an API.

## Try It Today

The Automation API still requires a Pulumi CLI installation. You'll need a CLI version >= [v2.9.2](https://www.pulumi.com/docs/get-started/install/versions/). Clone a project from the [Automation Examples Repo](https://github.com/EvanBoyle/automation-api-examples) and get started!

## Alpha Period and Feedback

The Automation API is currently in Alpha. We need your help kicking the tires over the next few weeks. We do expect for some minor breaking changes, but these will mostly be additive. We need to know if this enables your automation needs, and where the API falls short.

We have a [list of known issues](https://github.com/pulumi/pulumi/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Fautomation-api), and we'd love for you to add notes, give your feedback, and open more issues.

Come hangout in the [#automation-api community slack channel](https://pulumi-community.slack.com/archives/C019YSXN04B) to talk automation and share what you're building.

Automation API was initially developed in Go due to all of the reusable code and types available from the Pulumi engine which is also written in Go. We know that folks have asked for this to be available in every Pulumi language. At the end of the alpha, we plan on starting development on the other Pulumi languages (nodejs, python, .NET). If this is something you'd like to see in your favorite Pulumi language, please let us know! The Go Automation API can drive programs written in any language, so even if your Pulumi program isn't written in Go you can still use Automation API today.

🏭🏭🏭 Happy automating! 🏭🏭🏭

**Comment by EvanBoyle** [comment] 2020-09-17 01:06
A bunch of new features just landed in Automation API. This will require updating your CLI to [v2.10.1](https://www.pulumi.com/docs/get-started/install/versions/). You can see the full [changelog here](https://github.com/pulumi/pulumi/blame/master/CHANGELOG.md#L9-L33), but some highlights:

- Stack name validations have been relaxed at the Automation API layer. This change was made to enable local backends.
- Output from Up/Refresh/Preview can now be streamed to a list of io.Writer: [example](https://github.com/EvanBoyle/automation-api-examples/blob/main/inline_program/main.go#L127-L131)
- Support added for private git repo authentication: [examples](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/example_test.go#L209-L260)
- Helper functions to extract permalink from update result: [example](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/example_test.go#L943-L945)
- cancel/import/export recovery APIs: [example](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/example_test.go#L1081-L1109)
- upsert stack helper methods (create or select): [example](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/example_test.go#L735)
- workspace scoped environment variables (useful for setting passphrase envs for local backends): [example](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/example_test.go#L319-L328)
- Support for non-default secrets providers: [example](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/example_test.go#L373-L392)

Docs and examples are up to date as well:
- [godoc](https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto)
- [automation-api-examples](https://github.com/EvanBoyle/automation-api-examples)
- [halloumi](https://github.com/evanboyle/halloumi)

:factory:  Thanks for all of the great feedback so far! :factory:

**Comment by EvanBoyle** [comment] 2020-10-14 22:16
The Pulumi CLI v2.12.0 is here, and with it comes the Automation API for Node.js! There's a blog post coming soon with more examples, but here some pointers to get you started:

- Automation API examples have been added for node: https://github.com/pulumi/automation-api-examples
- Node.js docs: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/x/automation/
- CLI release page where you can find v2.12.0 (required for Automation API + Node.js): https://www.pulumi.com/docs/get-started/install/versions/
- A list of known issues you can chime in on and add to: https://github.com/pulumi/pulumi/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fautomation-api+label%3Alanguage%2Fjavascript

**Comment by AlexLeung** [comment] 2020-10-14 22:27
Awesome work! Are there plans to have an Automation API which can run in the browser?

**Comment by EvanBoyle** [comment] 2020-10-14 22:39
> Awesome work! Are there plans to have an Automation API which can run in the browser?

Not at the moment, but feel free to open an issue with details. The core Pulumi engine is written in Go and makes heavy use of gRPC servers. The Automation API has a dependency on that binary (currently distributed via the CLI installation). 

You can definitely run Automation API within a web service (express, lambda, etc) and call it from the browser though!

**Comment by EvanBoyle** [comment] 2020-10-19 16:32
We just published a blog post that shows off some of the amazing things you can do with Automation API, with multi-language examples. There's an update in there about our plans for `python` and `c#`!

https://www.pulumi.com/blog/automation-api/

**Comment by CanRau** [comment] 2020-10-29 21:09
😍 So exciting 🎉
Is there a plan to drop the CLI dependency? So a single Go binary could be shipped including everything necessary?
That would be fabulastic 🚀😁

**Comment by EvanBoyle** [comment] 2020-11-02 16:39
> Is there a plan to drop the CLI dependency? So a single Go binary could be shipped including everything necessary?

There are no plans for this at the moment. I'm curious to learn a little more about your use case and what you have in mind here. Would you mind opening a new issue with some details? @CanRau

**Comment by EvanBoyle** [comment] 2020-11-11 15:47
Opened https://github.com/pulumi/docs/issues/4564 to capture updating our tool comparison docs. 

Seems like there's a great deal of demand for the software-driven workflow that Automation API supports from other ecosystems:

- https://github.com/aws/aws-cdk/issues/601
- https://github.com/hashicorp/waypoint/issues/630

**Comment by afoninsky** [comment] 2020-11-12 14:52
> There are no plans for this at the moment. I'm curious to learn a little more about your use case and what you have in mind here. Would you mind opening a new issue with some details? @CanRau

One example why it can be need - is to avoid influence of the environment, think in terms of programming but not in terms of scripting. Like here:
https://gist.github.com/afoninsky/4c7656ef906749f1c4b3edef95821eef

**Comment by EvanBoyle** [comment] 2020-11-12 16:40
@afoninsky what you describe there is a bug, would you mind opening an issue? We plan to swap the underlying implementation from being CLI backed to using direct RPC calls into the engine over time. In most cases, if the underlying CLI is leaking through it is a bug and we'll work on fixing it.

**Comment by komalali** [comment] 2021-02-09 20:18
**Update**

We have just shipped Automation API for Python! Running your Pulumi program is now as simple as running `python my_file.py` Check out the [blog post](https://www.pulumi.com/blog/automation-api-python/) to learn more. 

**Examples**

We have a number of examples ready for you to take for a spin over in the [examples repo](https://github.com/pulumi/automation-api-examples#python-examples), and we'd love to see your contributions for how you are using automation API in your projects.

* [Inline Program](https://github.com/pulumi/automation-api-examples/tree/main/python/inline_program)
* [Local Program](https://github.com/pulumi/automation-api-examples/tree/main/python/local_program)
* [Cross-Language Program](https://github.com/pulumi/automation-api-examples/tree/main/python/cross_language)
* [Database Migration](https://github.com/pulumi/automation-api-examples/tree/main/python/database_migration)
* [Pulumi over HTTP](https://github.com/pulumi/automation-api-examples/tree/main/python/pulumi_over_http)

**Try it out!**

The Automation API still requires a Pulumi CLI installation. You'll need a [CLI version](https://www.pulumi.com/docs/get-started/install/versions/) >= v2.9.2 and >=v2.17.1 of the [pulumi package](https://pypi.org/project/pulumi/).

We'd love to hear your feedback as you start using Automation API in your own projects. We have a [list of known issues](https://github.com/pulumi/pulumi/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Fautomation-api+sort%3Aupdated-desc) and we encourage you to leave notes and open more issues as you come across them.

🏭🏭🏭 Happy automating! 🏭🏭🏭

**Comment by infin8x** [comment] 2021-03-05 18:59
The Automation API is now available in all 4 Pulumi languages! We're excited for you to get started with it. Here's some jumping off points:

- The [Pulumi blog](https://www.pulumi.com/blog/tag/automation-api/) has some great posts on how to use automation API, how we've seen it used out in the wild, and more
- There's a wealth of examples in [pulumi/automation-api-examples](https://github.com/pulumi/automation-api-examples)
- @jaxxstorm's [Ploy](https://github.com/jaxxstorm/ploy) tool shows how to use Automation API to create a Heroku-like tool for deploying Docker images to Kubernetes clusters
- If you'd like to follow along with future improvements, the [`area/automation-api`](https://github.com/pulumi/pulumi/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fautomation-api) label has you covered!

**Comment by almson** [comment] 2021-04-17 07:21
If Pulumi is written in Go, and the "Automation API" is written in Go, why isn't Go the default language? Why are things like AWSX written in TS?

It's great that Pulumi lets you write code. It's great that Pulumi is open source. It's great that you finally you opened up Pulumi as a library. But what good is all of it when different layers are written in different languages and you can't just step through things with a debugger? It's like whoever came up with Pulumi doesn't grok programming. It's like they secretly love Terraform, but thought they'd make money by creating a startup that tries to please these other weird people.

**Comment by komalali** [comment] 2021-04-17 21:45
Closing this issue since Automation API is now available in all supported languages. Any further issues will be tracked individually in this repo.

🏭 Happy automating! 🏭

**Closed** 2021-04-17 21:45 UTC
Labels: kind/epic, resolution/fixed, team/platform
