### ISSUE TITLE
[python] Disallow infinite `pulumi.Output` iteration

### ISSUE THREAD

**Issue by stohrendorf** [pulumi/pulumi#5554] opened 2020-10-12 08:31 UTC
In python, a `pulumi.Output` allows infinite iteration. In other words, `for x in y`, where `y` is a `pulumi.Output`, is an infinite loop. On the other hand, when doing `for x in y.items()`, pulumi correctly complains that you can't call a `pulumi.Output` object.

## Expected Behavior
pulumi doesn't allow iterating a `pulumi.Output` object.

## Current Behavior
`for x in y`, where `y` is a `pulumi.Output`, is an infinite loop.

## Steps to Reproduce
Should be obvious.

## Context (Environment)
`",".join(foo)`, where `foo` stems from a stack reference, leads to OOM.

**Comment by leezen** [comment] 2020-10-14 02:30
This looks like a dupe of https://github.com/pulumi/pulumi/issues/5028 -- please comment if you feel otherwise.

**Closed by leezen** 2020-10-14 02:30 UTC
Labels: needs-triage
