### ISSUE TITLE
IgnoreChanges works differently on refresh than it does on update

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#16391] opened 2024-06-13 15:41 UTC
### What happened?

I created a load balancer with a couple of listeners that have weight assigned to them and added the `ignoreChanges` flag:

```typescript
const listener = new aws.lb.Listener("listener", {
    loadBalancerArn: lb.arn,
    port: 80,
    defaultActions: [{
        type: "forward",
        forward: {
            targetGroups: [
              {
                arn: tg.arn,
                weight: 1,
              },
              {
                arn: tg2.arn,
                weight: 0,
              },
            ],
          },
    }]
}, {ignoreChanges: ["defaultActions[*].forward.targetGroups[*].weight"]});
```

and run `pulumi up` then great everything is there.

If I then swap round the `weight` inputs:

```typescript
const listener = new aws.lb.Listener("listener", {
    loadBalancerArn: lb.arn,
    port: 80,
    defaultActions: [{
        type: "forward",
        forward: {
            targetGroups: [
              {
                arn: tg.arn,
                weight: 1,
              },
              {
                arn: tg2.arn,
                weight: 0,
              },
            ],
          },
    }]
}, {ignoreChanges: ["defaultActions[*].forward.targetGroups[*].weight"]});
```

and run `pulumi up` then no changes.

If I then go into the AWS console and change the weights around there and run `pulumi refresh` the ignoreChanges statement is ignored.

If I set the `ignoreChanges` to be `defaultActions[0].forward` then it ignores everything, but it also means I can't add or remove any new target groups.

### Example

GitHub repo: https://github.com/pierskarsenbarg/elb-ignore-changes-refresh

### Output of `pulumi about`

```
CLI
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.39.0
resource  awsx    2.11.0
resource  docker  4.5.4
resource  docker  3.6.1
language  nodejs  unknown

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/Users/piers/.nvm/versions/node/v20.11.1/bin/node' version='v20.11.1'

Current Stack: pierskarsenbarg/elb-ignore-changes-bug/dev

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:dev::elb-ignore-changes-bug::pulumi:pulumi:Stack::elb-ignore-changes-bug-dev
pulumi:providers:awsx                                urn:pulumi:dev::elb-ignore-changes-bug::pulumi:providers:awsx::default_2_11_0
awsx:ec2:Vpc                                         urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc::lb-vpc
pulumi:providers:aws                                 urn:pulumi:dev::elb-ignore-changes-bug::pulumi:providers:aws::default_6_37_1
aws:ec2/vpc:Vpc                                      urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc::lb-vpc
aws:ec2/internetGateway:InternetGateway              urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::lb-vpc
aws:ec2/subnet:Subnet                                urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::lb-vpc-ecs-public-subnet-2
aws:ec2/subnet:Subnet                                urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::lb-vpc-ecs-public-subnet-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::lb-vpc-ecs-public-subnet-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::lb-vpc-ecs-public-subnet-1
aws:ec2/route:Route                                  urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::lb-vpc-ecs-public-subnet-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::lb-vpc-ecs-public-subnet-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::lb-vpc-ecs-public-subnet-1
aws:ec2/route:Route                                  urn:pulumi:dev::elb-ignore-changes-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::lb-vpc-ecs-public-subnet-1
pulumi:providers:pulumi                              urn:pulumi:dev::elb-ignore-changes-bug::pulumi:providers:pulumi::default
pulumi:providers:aws                                 urn:pulumi:dev::elb-ignore-changes-bug::pulumi:providers:aws::default_6_39_0
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:dev::elb-ignore-changes-bug::aws:ec2/securityGroup:SecurityGroup::lbSg
aws:lb/loadBalancer:LoadBalancer                     urn:pulumi:dev::elb-ignore-changes-bug::aws:lb/loadBalancer:LoadBalancer::lb
aws:lb/targetGroup:TargetGroup                       urn:pulumi:dev::elb-ignore-changes-bug::aws:lb/targetGroup:TargetGroup::tg2
aws:lb/targetGroup:TargetGroup                       urn:pulumi:dev::elb-ignore-changes-bug::aws:lb/targetGroup:TargetGroup::tg
aws:lb/listener:Listener                             urn:pulumi:dev::elb-ignore-changes-bug::aws:lb/listener:Listener::listener


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/awsx    2.11.0
@pulumi/pulumi  3.119.0
@types/node     18.19.34
typescript      5.4.5
@pulumi/aws     6.39.0

Pulumi locates its logs in /var/folders/x8/cdd9j87s607fwpy0q62mfmmw0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lunaris** [comment] 2024-06-17 10:08
After some investigation, I think this is an issue in the provider (or rather, our bridging of the AWS provider), potentially due to the issues around handling sets and the reordering problems that ensue (see https://github.com/pulumi/pulumi-terraform-bridge/issues/1904). Indeed, in that issue @t0yv0 predicts that it may have a knock-on effect on refreshes performing full diffs.

Reasons I'm inclined to say this isn't a bug that `refresh` has introduced:
* We are calling the exact same `Diff` method with the exact same arguments (including the passing of `IgnoreChanges`), and the provider has no way to know whether this is being called in response to a `refresh` or an `update`, so it shouldn't be able to introduce new (broken) behaviour.
* If I manually modify my state using `export`/`import` to reorder the two target groups until they (presumably) match the order the provider is going to pick, I still get diffs. If I use `PULUMI_DEBUG_GRPC` to dump the calls, I can see that a diff is being reported against the ARNs, even though they are byte-for-byte identical. This leads me to think it is the reordering issue -- the bridged provider spots the diff, Pulumi then reports it but it doesn't make sense/visually surface because our handling of the sets means that our consistent ordering masks the diff (see below where `defaultActions[0].forward.targetGroups[0].arn` is identical across all resource states).
```
{
  "method": "/pulumirpc.ResourceProvider/Diff",
  "request": {
    "id": "arn:aws:elasticloadbalancing:us-east-1:616138583583:listener/app/lb-c02916b/da56acbc7fbff239/0edf8d54df1a8fe7",
    "urn": "urn:pulumi:dev::elb-ignore-changes-bug::aws:lb/listener:Listener::listener",
    "olds": {
      ...
      "arn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:listener/app/lb-c02916b/da56acbc7fbff239/0edf8d54df1a8fe7",
      "defaultActions": [
        {
          ...
          "forward": {
            "stickiness": {
              "duration": 3600,
              "enabled": false
            },
            "targetGroups": [
              {
                "arn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:targetgroup/tg2-06f4221/b767b73c9c873857",
                "weight": 3
              },
              {
                "arn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:targetgroup/tg-17e0b6b/f084db5525f1dd3a",
                "weight": 2
              }
            ]
          },
          "order": 1,
          "redirect": null,
          "targetGroupArn": "",
          "type": "forward"
        }
      ],
      "id": "arn:aws:elasticloadbalancing:us-east-1:616138583583:listener/app/lb-c02916b/da56acbc7fbff239/0edf8d54df1a8fe7",
      "loadBalancerArn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:loadbalancer/app/lb-c02916b/da56acbc7fbff239",
      ...
    },
    "news": {
      "__defaults": [],
      "defaultActions": [
        {
          "__defaults": [],
          "forward": {
            "__defaults": [],
            "stickiness": {
              "duration": 3600
            },
            "targetGroups": [
              {
                "__defaults": [],
                "arn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:targetgroup/tg2-06f4221/b767b73c9c873857",
                "weight": 2
              },
              {
                "__defaults": [],
                "arn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:targetgroup/tg-17e0b6b/f084db5525f1dd3a",
                "weight": 1
              }
            ]
          },
          "type": "forward"
        }
      ],
      "loadBalancerArn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:loadbalancer/app/lb-c02916b/da56acbc7fbff239",
      "port": 80
    },
    "ignoreChanges": [
      "defaultActions[*].forward.targetGroups[*].weight"
    ],
    "oldInputs": {
      "__defaults": [],
      "defaultActions": [
        {
          "__defaults": [],
          "forward": {
            "__defaults": [],
            "stickiness": {
              "duration": 3600
            },
            "targetGroups": [
              {
                "__defaults": [],
                "arn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:targetgroup/tg2-06f4221/b767b73c9c873857",
                "weight": 3
              },
              {
                "__defaults": [],
                "arn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:targetgroup/tg-17e0b6b/f084db5525f1dd3a",
                "weight": 2
              }
            ]
          },
          "type": "forward"
        }
      ],
      "loadBalancerArn": "arn:aws:elasticloadbalancing:us-east-1:616138583583:loadbalancer/app/lb-c02916b/da56acbc7fbff239",
      "port": 80
    }
  },
  "response": {
    "stables": [
      "loadBalancerArn"
    ],
    "changes": "DIFF_SOME",
    "diffs": [
      "defaultActions",
      "defaultActions",
      "defaultActions",
      "defaultActions"
    ],
    "detailedDiff": {
      "defaultActions[0].forward.targetGroups[0].arn": {
        "kind": "UPDATE"
      },
      "defaultActions[0].forward.targetGroups[0].weight": {
        "kind": "UPDATE"
      },
      "defaultActions[0].forward.targetGroups[1].arn": {
        "kind": "UPDATE"
      },
      "defaultActions[0].forward.targetGroups[1].weight": {
        "kind": "UPDATE"
      }
    },
    "hasDetailedDiff": true
  },
  "metadata": {
    "kind": "resource",
    "mode": "client",
    "name": "aws"
  }
}

``` 
* There appears to be some funkiness with this specific example because e.g. a "clean" `refresh` seems very difficult -- the provider will set `defaultActions[0].forward.stickiness.duration = 3600`, for instance, which also shows up in the diff. If I fudge my state file using `export`/`import` to get rid of this, I can get rid of this but it could also be contributing since `IgnoreChanges` only affects what is shown, not what is applied to state.

My proposal would therefore be to close this in favour of https://github.com/pulumi/pulumi-terraform-bridge/issues/1904. Thoughts?

**Comment by pierskarsenbarg** [comment] 2024-06-17 11:31
Should this be closed or moved to the AWS provider repo?

**Comment by lunaris** [comment] 2024-06-21 08:54
I'm going to close it and mark as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/1904; hopefully this is an acceptable resolution :pray:

**Closed** 2024-06-21 08:55 UTC
Labels: kind/bug, resolution/duplicate, customer/feedback, area/engine
