### ISSUE TITLE
Pulumi doesn't create subfolder per project when using cloud storage to store state

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi#5585] opened 2020-10-17 22:19 UTC
This is more of a question than a bug.

I'm using azure cloud storage and was planning to use the same blob storage for multiple projects, where all projects has a dev, test and prod stack. Setting up the first project was somewhat smooth, but now when I'm setting up the second one pulumi complains that the stacks already exists. Looking at what is stored in the storage container I do understand the message since the stacks are stored in a structure like: `<container>/.pulumi/stacks/<stack>.json`. I was somewhat surprised by this since I expected the project name to be somewhere in the path, like `<container>/.pulumi/<project name>/stacks/<stack>.json` to make it easier to use the same container for multiple projects.

With the current structure I think I need to login to the correct cloud storage container for every single project, which will be annoying in the long term.

Am I doing something wrong or is it a good reason to why it is structured like this. Using the service works as expected since there you sort of gets stacks per repository per repository owner, so no conflicts with stacks having the same name as I have now using cloud storage.

**Comment by alastairs** [comment] 2020-10-18 12:21
@mastoj We have worked around this by defining the `backend.url` setting in our Pulumi.yaml project files to point to our Azure Storage container, with the project name as a path suffix on that URL. It works smoothly enough for us, especially with a custom template to populate that field, and you'll only need to `pulumi login` once (if at all), but note that some Pulumi features—most especially `StackReference`s—will not work with this approach. We decided that the loss of this feature was acceptable for the overall usability improvement, and have worked around the lack of `StackReference`s by sharing stack outputs via Vault secrets.

**Comment by mastoj** [comment] 2020-10-18 20:44
@alastairs, thank for your input. I really appreciate the `StackReference` functionality and I also think we will start using the paid version when we have proven its value, so I don't want to trade that away. 

I think my workaround will be to add the name as part a part of the stack for now.

**Comment by leezen** [comment] 2020-10-21 05:20
I believe this is a dupe of https://github.com/pulumi/pulumi/issues/2522, so closing in favor of that, but please comment if you feel otherwise.

**Closed by leezen** 2020-10-21 05:20 UTC
Labels: needs-triage
