### ISSUE TITLE
Panic when trying to fetch logs with resource that has malformed URN

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#4076] opened 2020-03-13 03:25 UTC
I stood up a stack with a custom resource that defined the type as `"pulumi-apps:AccessKeyRotator"`. For example:

```
export class AccessKeyRotator extends pulumi.ComponentResource {
    public readonly user: aws.iam.User;
    public readonly interval: string;

    constructor(name: string, args: AccessKeyRotatorArgs, opts?: pulumi.ComponentResourceOptions) {
        super("pulumi-apps:AccessKeyRotator", name, opts);
```

TBH I wasn't sure about the format of the type, but as it turns out I got it wrong. When I later ran `pulumi logs` the CLI panic trying to parse the URN, or something?

```
$ pulumi logs
Collecting logs for stack dev since 2020-03-12T19:20:37.000-07:00.

panic: fatal: An assertion has failed: Module member token 'pulumi-apps:AccessKeyRotator' missing module member delimiter

goroutine 38 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc000b83c00, 0x537c1eb, 0x38, 0xc000296c30, 0x1, 0x1)
        /Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x197
github.com/pulumi/pulumi/pkg/tokens.ModuleMember.Module(0xc000b83c00, 0x1c, 0x0, 0x18)
```

The resource appears to have been created successful and can be found in the checkpoint file:

```
...
{
                "urn": "urn:pulumi:dev::aws-access-key-rotator::pulumi-apps:AccessKeyRotator::rotator",
                "custom": false,
                "type": "pulumi-apps:AccessKeyRotator",
                "parent": "urn:pulumi:dev::aws-access-key-rotator::pulumi:pulumi:Stack::aws-access-key-rotator-dev"
            },
...
```

It seems like if we require the URN to be of a specific format, then we need to enforce that for user-defined custom components too. (Rather than allowing the update to proceed, and then aborting when we see the malformed data later.)

Update: as expected, changing the `ComponentResource`'s type to `"pulumi-eng:apps:AccessKeyRotator"` (so it has two colons in it instead of just one), I can now run `pulumi logs` after updating the stack.

**Comment by lukehoban** [comment] 2020-03-13 04:02
This is a dupe of https://github.com/pulumi/pulumi/issues/3432.

**Closed by lukehoban** 2020-03-13 04:02 UTC
Labels: kind/bug
