### ISSUE TITLE
Pulumi Ignores environment variables when credentials files exist

### ISSUE THREAD

**Issue by bricef** [pulumi/pulumi#5190] opened 2020-08-18 21:43 UTC
When creating a new project with the new command, pulumi `v2.8.2` fails to create a stack with an authentication error even though the AWS CLI can authenticate without issue.

## Steps to Reproduce
```
$ pulumi login --cloud-url s3://cg-infra-state
Logged in to Brices-MBP.lan as brice (s3://cg-infra-state)
$ pulumi new digitalocean-python
[...]
Sorry, could not create stack 'dev': could not create stack: An IO error occurred while writing the new snapshot file: blob (key ".pulumi/stacks/dev.json") (code=Unknown): AccessDenied: No AWSAccessKey was presented.
	status code: 403, request id: XXX, host id: XXX
```

However, the AWS CLI seem to be configured properly:

```
$ aws sts get-caller-identity
{
    "UserId": "XXX",
    "Account": "XXX",
    "Arn": "XXX"
}
$ aws s3 cp test.yaml  s3://cg-infra-state
upload: ./test.yaml to s3://cg-infra-state/Pulumi.yaml
```

I am using environment variables for AWS credentials.

I am using MFA auth, which means I have the `AWS_SESSION_TOKEN` variable set and configured. ~I have not tried without MFA as this violates our account policies.~ This issue persist with normal credentials that do not require MFA (tried it in our dev account).

## Expected Behavior
Pulumi should pick up the environment variable and access S3 for state storage.

**Comment by bricef** [comment] 2020-08-18 22:38
For some reason, the environment variables failed to override the credentials configured in `~/.aws/crednetials`. removing the AWS credentials file seems to have fixed the issue. This is still a bug, as env vars are expected to override the AWS cred files, as they do for the AWS command line.

**Comment by leezen** [comment] 2020-08-19 14:08
This is pretty surprising given I think the underlying code simply uses the AWS SDK's precedence to make it work. The times I've seen this differ is due to differences in the AWS SDKs themselves (e.g. Python SDK which the AWS CLI uses vs. Go SDK). A couple thoughts on debugging this:
- Do you have `AWS_SDK_LOAD_CONFIG` set to a truthy value and do you have `AWS_PROFILE` set as an environment variable? I think that would lead to trying to use the credentials file vs. the other environment variables.
- Do you rely on `cli/cache` for the credentials in some way? This isn't implemented in the AWS Go SDK but is in the others: https://github.com/aws/aws-sdk-go/issues/3186

**Comment by leezen** [comment] 2021-01-31 22:28
Closing issue due to inability to reproduce.

**Closed by leezen** 2021-01-31 22:28 UTC
Labels: area/backends, kind/bug, resolution/no-repro
