### ISSUE TITLE
pulumi throws long error message when one of the s3 buckets is missing in import command

### ISSUE THREAD

**Issue by faizanakram99** [pulumi/pulumi#7200] opened 2021-06-03 09:16 UTC
pulumi import command fails.

I think one of the s3 buckets was missing which lead to this error. Instead of showing a proper message it throws this scary error

Here is the stack trace

```
================================================================================
Pulumi Version:   v3.3.1
Go Version:       go1.16.4
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            fatal: An assertion has failed: Module member token 'aws:s3/Bucket' missing module member delimiter

goroutine 1 [running]:
runtime/debug.Stack(0xc000adb490, 0x19c88e0, 0xc00179a420)
        /Users/runner/hostedtoolcache/go/1.16.4/x64/src/runtime/debug/stack.go:24 +0x9f
main.panicHandler()
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x76
panic(0x19c88e0, 0xc00179a420)
        /Users/runner/hostedtoolcache/go/1.16.4/x64/src/runtime/panic.go:965 +0x1b9
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x7ffe5603de00, 0x1d8aae2, 0x38, 0xc000adb6e0, 0x1, 0x1)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.ModuleMember.Module(0x7ffe5603dee6, 0xd, 0xc0017824e0, 0x0)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/tokens/tokens.go:192 +0xd2
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.ModuleMember.Package(0x7ffe5603dee6, 0xd, 0x2053110, 0x1)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/tokens/tokens.go:187 +0x35
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.Type.Package(0x7ffe5603dee6, 0xd, 0x2a, 0x1d2968d)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/tokens/tokens.go:227 +0x70
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(0xc00120c380, 0xc0011f6a20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:177 +0x470
github.com/pulumi/pulumi/pkg/v3/engine.update(0xc00120c380, 0xc0011f6a20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/engine/update.go:439 +0x4e7
github.com/pulumi/pulumi/pkg/v3/engine.Import(0x20b0130, 0xc001627a70, 0xc00120c380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, ...)
        /Users/runner/work/pulumi/pulumi/pkg/engine/import.go:43 +0x56e
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).apply(0xc0007b2900, 0x20bc768, 0xc0000c6010, 0x1d3efed, 0xf, 0x20d8a28, 0xc001510c60, 0xc0007a6380, 0xc00079f180, 0x2a, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:609 +0x1385
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt(0x20bc768, 0xc0000c6010, 0x1d3efed, 0xf, 0x20d8a28, 0xc001510c60, 0xc0007a6380, 0xc00079f180, 0x2a, 0xc0007b24e0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/apply.go:115 +0x133
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute(0x20bc768, 0xc0000c6010, 0x1d3efed, 0xf, 0x20d8a28, 0xc001510c60, 0xc0007a6380, 0xc00079f180, 0x2a, 0xc0007b24e0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/apply.go:200 +0x1a8
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).Import(0xc0007b2900, 0x20bc768, 0xc0000c6010, 0x20d8a28, 0xc001510c60, 0xc0007a6380, 0xc00079f180, 0x2a, 0xc0007b24e0, 0x1, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:502 +0x193
github.com/pulumi/pulumi/pkg/v3/backend.ImportStack(0x20bc768, 0xc0000c6010, 0x20d8a28, 0xc001510c60, 0xc0007a6380, 0xc00079f180, 0x2a, 0x0, 0x0, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/stack.go:91 +0xe5
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Import(0xc001510c60, 0x20bc768, 0xc0000c6010, 0xc0007a6380, 0xc00079f180, 0x2a, 0x0, 0x0, 0x0, 0xc0014ff308, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/stack.go:77 +0xc8
main.newImportCmd.func1(0xc000c07340, 0xc00079a6c0, 0x3, 0x3, 0x0, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/import.go:462 +0xd05
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000c07340, 0xc00079a6c0, 0x3, 0x3)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000c07340, 0xc00079a690, 0x3, 0x3, 0xc000c07340, 0xc00079a690)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003cb340, 0xc0000a4000, 0xc00006e748, 0x2cd60c0)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d

```

**Comment by lukehoban** [comment] 2021-06-03 17:11
The format required for the type token is `aws:s3/bucket:Bucket`.  The fact that this panics instead of providing a useful error message is being tracked in https://github.com/pulumi/pulumi/issues/6990.  I'll close this one out as a dupe of that.

**Closed by lukehoban** 2021-06-03 17:11 UTC
Labels: kind/bug, resolution/duplicate
