### ISSUE TITLE
Provider coexistence bug: parenting to a resource from another provider

### ISSUE THREAD

**Issue by ebashmakov** [pulumi/pulumi#5656] opened 2020-10-31 06:49 UTC
runtime: nodejs

When I use the same `opts` object while creating a resource from `azure` provider and a resource from `az
ure-nextgen` provider I get the following error on `pulumi preview` command:

```
pulumi:providers:azure-nextgen (default_3_12_1):
    error: no resource plugin 'azure-nextgen-v3.12.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure-nextgen v3.12.1`
```

Example:

package.json
```
{
    "name": "myinfra",
    "version": "1.0.0",
    "devDependencies": {
        "@types/node": "^14.0.0",
        "ts-node": "^8.10.2",
        "typescript": "^3.9.7"
    },
    "dependencies": {
        "@pulumi/azure": "^3.0.0",
        "@pulumi/azure-nextgen": "^0.2.3",
        "@pulumi/pulumi": "^2.0.0"
    }
}
```

index.ts
```
import * as azure from "@pulumi/azure";
import * as storage from "@pulumi/azure-nextgen/storage/latest";

const group = new azure.core.ResourceGroup(
    "mygroup",
    {
        name: "rg",
        location: "SoutheastAsia"
    });

const sharedArgs = {
    resourceGroupName: group.name,
    location: group.location,
};
const sharedOptions = { parent: group }; // Shared opts breaks things

const storageAccount1 = new azure.storage.Account(
    "mystorage1",
    {
        ...sharedArgs,
        accountReplicationType: "LRS",
        accountTier: "Standard",
    },
    sharedOptions);

const storageAccount2 = new storage.StorageAccount(
    "mystorage2",
    {
        ...sharedArgs,
        accountName: "myuniquename2",
        sku: { name: "Standard_LRS" },
        kind: "StorageV2",
    },
    sharedOptions); // Replace `sharedOptions` with `{ parent: group }` and it works
```

**Comment by Frassle** [comment] 2022-06-13 10:54
Duplicate of https://github.com/pulumi/pulumi/issues/9801

**Closed by Frassle** 2022-06-13 10:54 UTC
Labels: kind/bug, language/python, resolution/duplicate
