### ISSUE TITLE
Expose provider resources in Python

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#1713] opened 2018-08-07 00:56 UTC
Just what it says on the tin.

**Comment by lukehoban** [comment] 2018-10-30 21:49
Per #220 which was closed as a dupe of this - we need to make sure that `tfgen` is also updated to emit these instances for each provider.

**Comment by swgillespie** [comment] 2019-01-07 22:45
Blocked on https://github.com/pulumi/pulumi-terraform/issues/271, which needs to be fixed first. First-class providers are basically useless without a fix to https://github.com/pulumi/pulumi-terraform/issues/271.

**Closed** 2019-01-17 00:54 UTC
Labels: feature/providers, language/python2, language/python3
