### ISSUE TITLE
Add stack tags to automation API

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#9975] opened 2022-06-27 14:29 UTC
We currently don't support tagging stacks using automation API

**Comment by mikhailshilkov** [comment] 2022-06-28 05:26
Sounds like a dupe of https://github.com/pulumi/pulumi/issues/5681

**Closed by mikhailshilkov** 2022-06-28 05:26 UTC
Labels: kind/enhancement, area/automation-api, resolution/duplicate

**Comment by joeduffy** [comment] 2022-06-28 05:29
What does “as not planned” mean?

**Comment by susanev** [comment] 2022-06-28 05:48
@joeduffy it seems to be a class of issues including won't fix, duplicate, can't repro, and stale at least according to the tool tip. I think that language is pretty confusing. @mikhailshilkov can we make that language more clear?

**Comment by mikhailshilkov** [comment] 2022-06-28 07:31
It's a github feature - I don't think the message is customizable... https://github.blog/changelog/2022-03-10-the-new-github-issues-march-10th-update/#%F0%9F%95%B5%F0%9F%8F%BD%E2%99%80%EF%B8%8F-issue-closed-reasons
