### ISSUE TITLE
Pulumi v2.8.1 is reformatting my Pulumi.*.yaml files

### ISSUE THREAD

**Issue by ChronosWS** [pulumi/pulumi#5126] opened 2020-08-06 22:18 UTC
Now any time I run `pulumi up`, it is rewriting my `.yaml` files to reorder all keys (including sub keys) alphabetically, and removes end-of-line comments.  This is unexpected and undesired and pollutes my changelists, making testing changes before commits cumbersome.

Please make it stop, or specify how to disable this behavior.  I'd also suggest if this is desired behavior it be disabled by default.

**Comment by lukehoban** [comment] 2020-08-07 01:52
This also appears to lead to a `Pulumi.<stackname>.yaml` file being generated for stacks without any config with the contents `{}` which is surprising and not ideal.

This is a regression due to https://github.com/pulumi/pulumi/pull/5031/files#diff-3f847126106f20e8ef7d74186b6108b0R50-R52.  This is a pretty serious usability regression.

We should look into either/both:
1. Ensuring we don't touch the `Pulumi.<stackname>.yaml` unless absolutely required
2. Using a YAML parser that can maintain ordering and whitespace

**Comment by stack72** [comment] 2020-08-07 12:22
Hi @ChronosWS 

I am just about to open the fix for this bug - I apologise for this usability regression

Paul

**Comment by justinvp** [comment] 2020-08-07 20:30
> 2\. Using a YAML parser that can maintain ordering and whitespace

Note: this is tracked by https://github.com/pulumi/pulumi/issues/423

**Closed** 2020-08-07 20:32 UTC
Labels: area/cli, kind/bug, priority/P1
