### ISSUE TITLE
Pulumi Login fails with latest version 3.101.0

### ISSUE THREAD

**Issue by TobiasBreuer** [pulumi/pulumi#15126] opened 2024-01-10 07:38 UTC
### What happened?

Using the latest v3.101.0 version of the CLI in our Azure DevOps pipeline, the step to login fails.
Pulumi Login is working without an issue in version 3.100.0

### Example

Following the log output for the failing attempt to login:
![image](https://github.com/pulumi/pulumi/assets/17617068/055c36e9-2bcf-4b41-ab8b-d2573ab97231)

When reverting back to the previous version v3.100.0, everything works again as expected:
![image](https://github.com/pulumi/pulumi/assets/17617068/86755f5f-1259-471b-beb8-8e1ffb93a4d6)

### Output of `pulumi about`

See screenshot

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by TobiasBreuer** [comment] 2024-01-10 07:52
From the change-log I would assume that this issue is related to #15011 - but this is more of a rough guess than an educated one 😉

**Comment by xenon8** [comment] 2024-01-10 10:19
Hi Pulumi, this is the second time a change like this has broken authentication with Azure KeyVault, please can you add some smoke tests to your PR process to ensure that this does not happen again in the future.

**Comment by thecodetinker** [comment] 2024-01-10 10:25
Boo :( If it's relevant, there is also this item related to Key Vault auth still open on the Azure Native provider: https://github.com/pulumi/pulumi-azure-native/issues/2432.

**Comment by Frassle** [comment] 2024-01-10 13:53
> https://github.com/pulumi/pulumi/pull/15011

Yes, it will be due to that.

> https://github.com/pulumi/pulumi-azure-native/issues/2432

Unrelated, the cli has its own separate systems for using azure compare to what azure-native uses.

**Comment by tgummerer** [comment] 2024-01-10 14:55
Thanks for the report.  We're reverting the gocloud.dev upgrade in #15128 and will add more tests before we try again. This slipped through both the automated and manual testing I've done for the change, and we'll try to work out why exactly that happened.

**Comment by tgummerer** [comment] 2024-01-11 00:11
Closing this out, as we released Pulumi 3.101.1 which addresses this.  I opened https://github.com/pulumi/pulumi/issues/15138 to investigate what exactly happened and to attempt another upgrade once we figured out what caused this issue.

**Closed by tgummerer** 2024-01-11 00:11 UTC
Labels: kind/bug, p1, area/backends, impact/regression

**Comment by tgummerer** [comment] 2024-01-17 11:44
@TobiasBreuer or anyone else reading this thread:  I'm trying to reproduce this, so I can write a test to avoid the same problem in the future, but am currently failing to do so.  Would you be willing to share a little more detail for 

1) which method you are using for logging into Azure (`az login` directly/the `azure/login` GitHub action/something else?) 
2) which type of login are you using (OIDC connect/client secrets/etc.)?
3) which roles does the login you are using have (I'm guessing one of `Storage Blob Data {Contributer,Owner}`, and maybe `Storage Queue Data Contributor`?

**Comment by justinvp** [comment] 2024-01-26 21:53
Heads up that the next minor version of Pulumi (tentatively v3.104.0 to be released on 1/31/2024) will use the latest version of [Go Cloud Development Kit](https://gocloud.dev). We believe the login failure from this issue has been addressed with a regression test in place.

If you'd like to try the new CLI before it is officially released next week, you can install a dev build with the following commands:

## Linux / macOS

```sh
curl -sSL https://get.pulumi.com | sh -s -- --version dev
```

## Windows

Open a new command prompt windows (<kbd>WIN</kbd>+<kbd>R</kbd>: `cmd.exe`)

```bat
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://get.pulumi.com/install.ps1')) -version dev" && SET "PATH=%PATH%;%USERPROFILE%\.pulumi\bin"
```

## GitHub Action

```yaml
- uses: pulumi/actions@v5
  with:
    pulumi-version: dev
```

If you try the dev build and do encounter a problem, please open a new issue at https://github.com/pulumi/pulumi/issues/new/choose

Thank you!
