### ISSUE TITLE
403 expired token

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#3182] opened 2019-09-04 23:46 UTC
During an update the lease token expired. This "shouldn't happen", but does from time to time. (Problem to address 1.) As a result, the update failed to be marked as completed because the request returned a 403. This in-turn lead to a panic (Problem to address 2.)

Travis CI log of the failure:
https://api.travis-ci.com/v3/job/231227810/log.txt

Stack trace:
```
 i-eks/nodejs/eks/examples/tags ] Permalink: https://app.pulumi.com/moolumi/example-tags/p-it-travis-job-tags-dc52f686/updates/1

[ i-eks/nodejs/eks/examples/tags ] error: failed to complete update: [403] Forbidden

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).runEngineAction

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:925

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).apply

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:777

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/pkg/backend.PreviewThenPromptThenExecute

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/apply.go:208

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).Update

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:651

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/pkg/backend.UpdateStack

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/stack.go:86

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudStack).Update

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:146

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/cmd.newUpCmd.func1

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/cmd/up.go:114

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/cmd.newUpCmd.func3

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/cmd/up.go:345

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:112

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:766

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:852

[ i-eks/nodejs/eks/examples/tags ] github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:800

[ i-eks/nodejs/eks/examples/tags ] main.main

[ i-eks/nodejs/eks/examples/tags ] 	/home/travis/gopath/src/github.com/pulumi/pulumi/main.go:49
```

Request ID for one of the 403s that caused it:
```
(req 38127ece-eeac-4e8f-aa54-7847eb9f538d pulumi-bot) The lease token provided in the request is no longer valid (update IDs match: true, expired: true)
```

Seems like this is the cause of https://github.com/pulumi/pulumi-eks/issues/244, and likely other issues elsewhere, too.

**Comment by metral** [comment] 2019-09-05 16:42
> Seems like this is the cause of #3182, and likely other issues elsewhere, too.

Did you mean to link to a different issue? This is the current issue here 😃

**Comment by chrsmith** [comment] 2019-09-20 20:56
Spent some time reproing this and looking into the issue, and the root cause is that we setup a timer to be called back so we can refresh the lease token that isn't actually getting called in a timely fashion. (Such as our "sleep for 2.5m" not resuming for 5m+.)

Since it ultimately has to do with the OS scheduler and the overall CPU-resources available on the system, there isn't a whole lot we can do to fix this. But we can make some changes to how we request refresh tokens so that we are less dependent on tickers firing at the specific time we want. And I think we can also eliminate a goroutine or two elsewhere in the CLI, which might also help cut down on scheduling contention within the process.

**Comment by chrsmith** [comment] 2019-10-04 22:44
Closing this out for the time being.

There isn't actually a panic in the CLI, we just return an error when at the tail end of an update the API request to "complete" the update fails. This will happen, for example, if the machine is under heavy load and the current update's lease token has expired.

PR #3265 included some notes on what we could do to mitigate the likelihood of a lease token expiring, but ultimately we opted to not accept that change set. (And instead wait until we better understand these "heavy load" situations and why the timers involved wouldn't update the lease token in time.)

**Comment by metral** [comment] 2019-12-16 16:32
Been recently seeing this error re-surface in `pulumi/eks`:

```
[ ts/replace-cluster-add-subnets ]  +  awsx:x:ec2:NatGateway test-replace-cluster-add-subnets-1 creating error: 
pre-step event returned an error:
failed to save snapshot: [403] The provided update token has expired.
```

Recent Travis Run: https://travis-ci.com/pulumi/pulumi-eks/builds/141158475
Raw Logs for Travis Run: https://gist.github.com/337cb4d1593c323bf5a48a7b01974aac

cc @chrsmith

**Comment by metral** [comment] 2020-01-07 14:28
When CI runs experience a slew of failed tests, e.g in pulumi/eks, this exhausts travis even further and can intro this error across many tests. It's been occurring regularly in pulumi/eks over the last month when other unrelated issues arise (e.g. https://github.com/pulumi/pulumi-eks/issues/300)

**Comment by metral** [comment] 2020-01-29 17:11
We're hitting the 403 and `error: [409] Conflict: Another update is currently in progress.` errors consistently the last few days in EKS CI, where the Travis runtime is likely hitting resource starvation due to leaky tests (e.g. https://github.com/pulumi/pulumi-eks/issues/312).

While the leaky tests are likely the root cause here, it does like we're possibly hitting some sort of timing window w.r.t the tokens being leased to us by the service, and that not playing nice with updates causing them to 409 in addition to the token 403'ing.

For context, there are currently 12 tests in CI, running in parallel with each test running only once, and pulumi/examples has about ~90 tests, so theoretically we should not be seeing this based on quantity of tests.

**Comment by lukehoban** [comment] 2020-01-31 19:18
We currently believe this is due to https://github.com/pulumi/pulumi-eks/issues/312 which is itself due to https://github.com/pulumi/pulumi/issues/3850.  The 403s are a (roughly expected) symptom of OOMing the Node processes.  I'm going to close this out as I don't believe there is anything actionable here.  If we see this in non-OOM scenarios in the future - let's open an issue with a repro for investigation.

**Closed by lukehoban** 2020-01-31 19:18 UTC
Labels: kind/bug, priority/P1
