### ISSUE TITLE
Persistent 429 Rate limit errors from GCS bucket when using GCS State backend for Pulumi

### ISSUE THREAD

**Issue by AgrimPrasad** [pulumi/pulumi#4258] opened 2020-04-01 09:36 UTC
Since yesterday (31 March 2020), we have been seeing persistent 429 rate limit errors with the GCS state backend for pulumi. See this error irrespective of the size of pulumi stacks (even on newly created stacks) and even when only a single object from the stack is being created or modified.  Also tried `pulumi up --parallel 1` for single threaded execution, but still see this error.

```
Diagnostics:
  gcp:kms:CryptoKeyIAMBinding (xxx-permissions):
    error: post-step event returned an error: failed to save snapshot: An IO error occurred during the current operation: blob (key ".pulumi/stacks/<stack-name>.json") (code=Unknown): googleapi: Error 429: The rate of change requests to the object <gcs-bucket-name>/.pulumi/stacks/<stack-name>.json exceeds the rate limit. Please reduce the rate of create, update, and delete requests., rateLimitExceeded

  pulumi:pulumi:Stack (<pulumi-project-name>-<stack-name>):
    error: update failed
```

Sometimes, the state file gets deleted in this process too when 429 errors are received, which is weird.

We may have to give up on using GCS buckets entirely for storing pulumi state. Does anybody know about what could be causing this issue or any workarounds? Thanks.

**Comment by AgrimPrasad** [comment] 2020-04-01 09:49
Our GCS bucket is in the region `asia-east1 (Taiwan)` if that matters.

**Comment by AgrimPrasad** [comment] 2020-04-01 12:51
Tried a multi-region (ASIA) bucket too, and still see 429 errors.

**Comment by jaxxstorm** [comment] 2020-04-01 17:45
This isn't the first report we've heard of this specifically with the GCS backend, but I'm unable to reproduce it at this time on our gcloud account. Nothing has changed with regard to Pulumi's implementation.

I did notice as a result of checking this that we aren't effectively doing retries on the bucket like we do with the HTTP state backend, which might help with this but probably won't alleviate the issue.

We use the [gocloud library](https://github.com/google/go-cloud) to implement the buckets. There isn't any mechanism in that library to retry or back off, but I feel like there should be, so I opened
https://github.com/google/go-cloud/issues/2765 upstream to see if they'll implement it.

If other people are experiencing this or can help with reproducing it, please comment here.

**Comment by rawkode** [comment] 2020-04-01 19:14
Perhaps I'm confused, but why does Pulumi write multiple times? Can't it write local and sync remote at the end, it even periodically?

**Comment by matzkoh** [comment] 2020-04-01 19:14
I've started running into this problem as well.

Downgraded to 1.13.0 and worked perfectly again.

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/873d3245fb27476ee90551f8d43ad15af384dc48/Formula/pulumi.rb`

**Comment by lukehoban** [comment] 2020-04-01 19:42
> Perhaps I'm confused, but why does Pulumi write multiple times? Can't it write local and sync remote at the end, or even periodically?

A core part of the consistency model of Pulumi updates is that we will not proceed with the deployment unless we can successfully write the checkpoint. This ensures that the minimal possible divergence occurs between what’s commuted and what changes have been made in the cloud provider. This is not something I would expect to want to relax.

**Comment by jaxxstorm** [comment] 2020-04-01 19:43
@matzkoh can you keep trying this and let me know if it reappears? We've had at least 1 report of this not being fixed by downgrading, and [diffing the commits ](https://github.com/pulumi/pulumi/compare/v1.13.0...v1.13.1)between `1.13.0` and `1.13.1` gives me no indication anything related to the backend would have changed to rectify this

**Comment by lukehoban** [comment] 2020-04-01 19:43
> Downgraded to 1.13.0 and worked perfectly again.

Is anyone seeing this issue on Pulumi <=1.13.0?

**Comment by AgrimPrasad** [comment] 2020-04-02 00:47
I'll try with v1.13.0 and report back (I've seen it reported on Pulumi slack that this didn't help though), but I think the fundamental issue could be that Pulumi writes to the same object more than once per second, which is the rate limit defined for GCS buckets by Google at https://cloud.google.com/storage/docs/key-terms#immutability

```
There is no limit to how frequently you can create or update different objects in a bucket. However, a single particular object can only be updated or overwritten up to once per second. For example, if you have an object bar in bucket foo, then you should only upload a new copy of foo/bar about once per second. Updating the same object more frequently than once per second may result in 429 Too Many Requests errors.

You should retry failed requests using truncated exponential backoff.
```

Perhaps Google started enforcing this rate limit since 31st March, whereas this wasn't enforced as strictly earlier? They've had [multiple outages in recent days](https://status.cloud.google.com/), and I've seen reports of similar [rate limits being enforced at Azure](https://www.theregister.co.uk/2020/03/29/microsoft_azure_usage_surge_coronavirus/) recently

Until the retry with backoff logic is in place, I guess reducing the rate of writes to slightly slower than once per second could be an acceptable compromise?

**Comment by AgrimPrasad** [comment] 2020-04-03 06:25
@lukehoban I've run 5-6 builds so far with Pulumi v1.13.0 and this issue hasn't re-occurred for me so far. While I can't be 100% sure that v1.13.0 doesn't show this issue, indicators are that this issue was only introduced in v1.13.1

**Comment by jaxxstorm** [comment] 2020-04-03 15:37
@AgrimPrasad would you be able to send me verbose logs from `v1.13.1` and `v1.13.0` (I reached out to you on slack). 

I still can't repo this locally and would like to try and track down the cause

**Comment by AgrimPrasad** [comment] 2020-04-04 08:30
@jaxxstorm I've sent you part of the debug logs with v1.13.1 where this issue was hit as it's difficult to sanitize so many lines of logs. If you would like additional logs for debugging, please let me know.

**Comment by jaxxstorm** [comment] 2020-04-04 19:34
Thanks! I'll go through them on Monday

**Comment by jaxxstorm** [comment] 2020-04-08 18:34
Sorry for the delay here:
@AgrimPrasad - I went through the logs you sent me and diffed them as best as possible, and I can't see any real differences between the two outputs until GCP starts to throw the 429 response.

I also compared the differences between release `v1.13.0` and `v1.13.1` [here](https://github.com/pulumi/pulumi/compare/v1.13.0...v1.13.1) - while we changed a lot of files between these releases, I can't see any functional differences between the versions.

I'm fairly sure that GCS has started more strictly enforcing their documented rate limits on buckets. We do probably need to do something about this, so I'll leave this open for triage.

**Comment by akoenig** [comment] 2020-04-08 20:06
@jaxxstorm: I'm also chiming in here. I also think that some kind of back-off logic has to be implemented. Especially the case that the state file gets deleted, burned by evening today 😱 Don't get me wrong, don't want to sound reproachful in any way, but this is serious imho. 😕

**Comment by CristhianGarzon** [comment] 2020-04-14 07:18
I've tried using pulumi v1.13.0 but it didn't work, as workaround I'm downloading the state files to my local machine, then `pulumi login file://.` , then run pulumi up locally and once it finishes, I copy back to GCS the new pulumi state.
We started getting this error a week ago when we upgraded to the latest version of pulumi.

**Comment by maxromanovsky** [comment] 2020-04-14 07:29
I had to migrate to local state storage because I've lost my state couple of times (json file was removed from the bucket). Had to pull from bak and remove pending operations. One time even bak file was missing. Good thing I had versioning enabled, so pulled from previous version.

> A core part of the consistency model of Pulumi updates is that we will not proceed with the deployment unless we can successfully write the checkpoint. This ensures that the minimal possible divergence occurs between what’s committed to state storage and what changes have been made in the cloud provider. This is not something I would expect to want to relax.

So much for the consistency when one can end up with no current state whatsoever.

Disclaimer: I am not blaming Pulumi for what appears to be GCP issue (and I haven't even found any SLA/documentation on read/write request limit for GCS!). I am just trying to say, sometimes there ought to be some trade-offs, at least something that end-users can configure (let's say, caching state file locally, and periodically syncing with GCS sounds like a good trade-off to me)

**Comment by jaxxstorm** [comment] 2020-04-14 21:38
I met with some of the team regarding this issue on Friday to see if we could figure out a path forward. Here's where we ended up:

- The first intention is to try and recreate this behaviour locally, which has been something of a struggle. We decided to change course and instead of attempting to recreate GCS's rate limiting, mock a backend that will sporadically throw 429 responses. This should help us drive improvements. Unfortunately, it may be that any potential improvements here might be dependent on us rethinking the way handle state files on the cloud provider backends

- We acknowledge that we need to drive some improvements on the cloud provider backends across the board. There are several limitations to the current implementation which aren't helping with this issue, such as writing all state objects to a single blob.

To cut a long story short - we realize there is work to do here and that this is a painful experience for everyone using this backend and we're going to work hard on getting fixes out for this as soon as possible.

**Comment by AgrimPrasad** [comment] 2020-04-21 14:42
Hi, any update on this issue yet? We are excited about Pulumi v2 but this prevents us from upgrading beyond 1.13.0

**Comment by jaxxstorm** [comment] 2020-04-21 23:55
I've done some more investigation - here's what I know so far.

1. The underlying gocloud.dev library [performs retries](https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#pkg-overview) assuming you don't cancel the context passed.
2. During a saveStack call, we run `WriteAll` to save the [stack state](https://github.com/pulumi/pulumi/blob/master/pkg/backend/filestate/state.go#L187-L189) as part of the step execution. We cancel the context if [there is an error](https://github.com/pulumi/pulumi/blob/master/pkg/resource/deploy/step_executor.go#L333-L335) which there technically is from the GCS backend.

The potential solutions I can see here aren't great in the short term. Some ideas:

- We could try and catch the error during the `WriteAll` call and implement our own retry/backoff logic there. Unfortunately, the error code that is thrown has an `unknown` code (example: `(code=Unknown): googleapi: Error 429: The rate of change requests to the object <pulumi-gcs-bucket-name>/.pulumi/stacks/<pulumi-stack-name>.json exceeds the rate limit. Please reduce the rate of create, update, and delete requests., rateLimitExceeded
`) so we may swallow some important errors..
- We could not cancel the context if it's a `saveStack` operation. I'm not sure what the implications of this would be

Things I still don't know about this issue:

- Why some users see a significant improvement on `1.13.0` vs newer versions

@lukehoban @leezen - any ideas on how you'd like to proceed here?

**Comment by Place1** [comment] 2020-04-22 01:41
> Why some users see a significant improvement on 1.13.0 vs newer versions

anecdotally i've found versions of pulumi newer than 1.13 to be much faster so perhaps that's why some have better luck on 1.13 🤷‍♂️

**Comment by gorilych** [comment] 2020-04-23 08:31
I see the same issue with Pulumi 2.0.0

**Comment by krystian-kulgawczuk** [comment] 2020-04-23 17:13
I downgraded a couple of days ago from 1.14 to 1.13. Today I upgraded to 2.0.0 and again started getting this error.

**Comment by lukehoban** [comment] 2020-04-24 05:47
I've been able to reproduce consistently with:
1. Create a "multi-region" GCS bucket in Asia and `pulumi login` to it
2. Run a program that creates 100 `aws.s3.BucketObject` resources
3. About half the resource operations fail with 429 errors
4. The statefile ends up deleted from storage and `pulumi stack ls` no longer thinks the stack exists (though there is a `.bak` file).

> We could try and catch the error during the WriteAll call and implement our own retry/backoff logic there

Yeah - this sounds like the most immediately addressable option.  The patch below appears to fix this for me.  I'm not sure this is the way we want to actually fix this (if you open a PR, would be good to get @pgavlin's input) - but something like this may be a pragmatic step to prevent the current issue while we look into deeper rearchitecture to allow this to be done more specifically targeted at the GCS API calls.

```patch
diff --git a/pkg/backend/filestate/backend.go b/pkg/backend/filestate/backend.go
index 1bb4fce5..de3ce3f0 100644
--- a/pkg/backend/filestate/backend.go
+++ b/pkg/backend/filestate/backend.go
@@ -25,6 +25,7 @@ import (
 	"path/filepath"
 	"regexp"
 	"strings"
+	"sync"
 	"time"
 
 	"github.com/pkg/errors"
@@ -72,6 +73,7 @@ type localBackend struct {
 	url         string
 
 	bucket Bucket
+	mutex  sync.Mutex
 }
 
 type localBackendReference struct {
diff --git a/pkg/backend/filestate/state.go b/pkg/backend/filestate/state.go
index be274a1a..adc33cb2 100644
--- a/pkg/backend/filestate/state.go
+++ b/pkg/backend/filestate/state.go
@@ -24,6 +24,8 @@ import (
 	"strings"
 	"time"
 
+	"github.com/pulumi/pulumi/sdk/v2/go/common/util/retry"
+
 	"github.com/pulumi/pulumi/pkg/v2/engine"
 
 	"github.com/pkg/errors"
@@ -162,6 +164,9 @@ func (b *localBackend) getCheckpoint(stackName tokens.QName) (*apitype.Checkpoin
 }
 
 func (b *localBackend) saveStack(name tokens.QName, snap *deploy.Snapshot, sm secrets.Manager) (string, error) {
+	b.mutex.Lock()
+	defer b.mutex.Unlock()
+
 	// Make a serializable stack and then use the encoder to encode it.
 	file := b.stackPath(name)
 	m, ext := encoding.Detect(file)
@@ -183,9 +188,21 @@ func (b *localBackend) saveStack(name tokens.QName, snap *deploy.Snapshot, sm se
 	// Back up the existing file if it already exists.
 	bck := backupTarget(b.bucket, file)
 
-	// And now write out the new snapshot file, overwriting that location.
-	if err = b.bucket.WriteAll(context.TODO(), file, byts, nil); err != nil {
-		return "", errors.Wrap(err, "An IO error occurred during the current operation")
+	_, _, err = retry.Until(context.TODO(), retry.Acceptor{
+		Accept: func(try int, nextRetryTime time.Duration) (bool, interface{}, error) {
+			// And now write out the new snapshot file, overwriting that location.
+			err := b.bucket.WriteAll(context.TODO(), file, byts, nil)
+			if err != nil {
+				if try > 10 {
+					return false, nil, errors.Wrap(err, "An IO error occurred during the current operation")
+				}
+				return false, nil, nil
+			}
+			return true, nil, nil
+		},
+	})
+	if err != nil {
+		return "", err
 	}
 
 	logging.V(7).Infof("Saved stack %s checkpoint to: %s (backup=%s)", name, file, bck)
```

**Comment by johnnyrun** [comment] 2020-04-26 05:05
@lukehoban  thanks. May you mention the version are you patching? on master patching fails.

**Comment by johnnyrun** [comment] 2020-04-27 10:08
> @lukehoban thanks. May you mention the version are you patching? on master patching fails.

2.0.0 works fine. Thanks for patch

**Comment by jaxxstorm** [comment] 2020-04-28 04:16
Hi all! We have a feature build with a fix available, I'd love it if some of the community members affected by this issue could give it a try.

You can install it using our bash script install method:

```
curl -fsSL https://get.pulumi.com/ | bash -s -- --version "2.1.0-alpha.1588034617"
```

If you'd prefer to just download the tarball, grab them from here:

Linux:
```
curl https://get.pulumi.com/releases/sdk/pulumi-v2.1.0-alpha.1588034617-linux-x64.tar.gz --output pulumi-v2.1.0-alpha.1588034617-linux-x64.tar.gz
```

Darwin:

```
curl https://get.pulumi.com/releases/sdk/pulumi-v2.1.0-alpha.1588034617-darwin-x64.tar.gz --output pulumi-v2.1.0-alpha.1588034617-darwin-x64.tar.gz
```

Please let us know if this solves your issues, and sorry for the delay in getting this fix out

**Comment by AgrimPrasad** [comment] 2020-04-29 03:42
Thanks, I tried that alpha release locally on Mac OS.

First try ran fine (although there were no changes to be made in the stack).

On the second try, got a seemingly unrelated fatal error:

```
Diagnostics:
  pulumi:pulumi:Stack (<pulumi-project>-<pulumi-stack>):
    #
    # Fatal error in , line 0
    # Check failed: result.second.
    #
    #
    #
    #FailureMessage Object: 0x7ffeefbfd760
     1: 0x1000d5142 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/usr/local/bin/node]
     2: 0x100a18c31 V8_Fatal(char const*, ...) [/usr/local/bin/node]
     3: 0x100378436 v8::internal::GlobalBackingStoreRegistry::Register(std::__1::shared_ptr<v8::internal::BackingStore>) [/usr/local/bin/node]
     4: 0x10018d9e7 v8::ArrayBuffer::GetBackingStore() [/usr/local/bin/node]
     5: 0x100063174 node::Buffer::New(node::Environment*, char*, unsigned long, void (*)(char*, void*), void*) [/usr/local/bin/node]
     6: 0x100062f0b node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/usr/local/bin/node]
     7: 0x108200fda grpc::node::ByteBufferToBuffer(grpc_byte_buffer*) [<path-to-pulumi-project>/node_modules/grpc/src/node/extension_binary/node-v83-darwin-x64-unknown/grpc_node.node]
     8: 0x10820555b grpc::node::ReadMessageOp::GetNodeValue() const [<path-to-pulumi-project>/node_modules/grpc/src/node/extension_binary/node-v83-darwin-x64-unknown/grpc_node.node]
     9: 0x108202128 grpc::node::CompleteTag(void*, char const*) [<path-to-pulumi-project>/node_modules/grpc/src/node/extension_binary/node-v83-darwin-x64-unknown/grpc_node.node]
    10: 0x10820c0aa grpc::node::drain_completion_queue(uv_prepare_s*) [<path-to-pulumi-project>/node_modules/grpc/src/node/extension_binary/node-v83-darwin-x64-unknown/grpc_node.node]
    11: 0x1006d46c7 uv__run_prepare [/usr/local/bin/node]
    12: 0x1006cf2d0 uv_run [/usr/local/bin/node]
    13: 0x1000b5561 node::NodeMainInstance::Run() [/usr/local/bin/node]
    14: 0x10005d190 node::Start(int, char**) [/usr/local/bin/node]
    15: 0x7fff73086cc9 start [/usr/lib/system/libdyld.dylib]
    16: 0x13

    error: an unhandled error occurred: Program exited with non-zero exit code: -1
```

**Comment by jaxxstorm** [comment] 2020-05-01 16:15
Thanks for the feedback @AgrimPrasad - did that error persist? I'm hoping to get more feedback on this particular issue from users if possible!

**Comment by rueian** [comment] 2020-05-01 17:44
I am using the pulumi v2.1.0 binary which is installing from the homebrew and meet the same error almost every `pulumi up`.

```
$ pulumi version
v2.1.0
```

<img width="1452" alt="截圖 2020-05-02 上午1 35 58" src="https://user-images.githubusercontent.com/2727535/80827335-616e2900-8c16-11ea-865b-f3021fa86f3c.png">

**Comment by jaxxstorm** [comment] 2020-05-01 17:58
@rueian - this is a known issue with `2.1.0` - we are looking for people to test the fix here: https://github.com/pulumi/pulumi/issues/4258#issuecomment-620370816

Would you mind giving it a try?

**Comment by rueian** [comment] 2020-05-02 05:39
Yes, I have already tried the `2.1.0-alpha.1588034617+gc07e95e1`, and it is great. no Error 429 anymore.

**Comment by AgrimPrasad** [comment] 2020-05-03 11:36
> Thanks for the feedback @AgrimPrasad - did that error persist? I'm hoping to get more feedback on this particular issue from users if possible!

I've tried it 5-6 times since then and it's been working well so far. 👍

**Comment by JanVoracek** [comment] 2020-05-03 20:54
Hi, I've been using the patch for several days and everything looks fine 🎉

**Comment by AgrimPrasad** [comment] 2020-05-04 03:45
Hit the fatal error from my previous comment again once, so seems it happens in around 10% of runs for me with this alpha build. https://github.com/pulumi/pulumi/issues/4258#issuecomment-620973527

**Comment by AgrimPrasad** [comment] 2020-05-04 10:40
Can we get the fix into a 2.x release soon? I'm now waiting for a feature in `pulumi/gcp` which requires a 2.x release (specifically Bigquery Dataset Access resource).

**Comment by jaxxstorm** [comment] 2020-05-04 16:50
@AgrimPrasad we just merged this into master, which means it'll be in our next release. Thanks for your patience!

**Closed** 2020-05-04 16:50 UTC

**Comment by rawkode** [comment] 2020-05-08 15:03
@jaxxstorm Any chance we can cut a release?

**Comment by confiq** [comment] 2020-05-11 16:16
I just had this bug where I lost my state... Yes, the version was [v2.1.0](https://github.com/pulumi/pulumi/releases)

**Comment by jaxxstorm** [comment] 2020-05-11 19:14
@confiq can you provide any further information for that? Perhaps open a new issue if possible.

**Comment by confiq** [comment] 2020-05-11 21:03
I did the search so I didn't want to open a new issue. I've recover this from my clipboard history

> error: post-step event returned an error: failed to save snapshot: An IO error occurred while writing the new snapshot file: blob (key ".pulumi/stacks/infra.environments.develop.json") (code=Unknown): googleapi: Error 429: The rate of change requests to the object b81-pulumi/.pulumi/stacks/infra.environments.develop.json exceeds the rate limit. Please reduce the rate of create, update, and delete requests., rateLimitExceeded

There was an error before that, but I just assume that post-step could not write/move new file and I lost state file. 
I had to copy from .bkp

Since I can't reproduce this, I'm not sure it's best to open an issue...

**Comment by jaxxstorm** [comment] 2020-05-11 22:10
@confiq I just noticed you're using `2.1.0`, this fix isn't in that release. We're cutting a `2.1.1` with this included

**Comment by omidraha** [comment] 2023-11-21 21:01
I tried to remove installed `longhorn` chart and received this `BackoffLimitExceeded` error

https://github.com/omidraha/pulumi_example/tree/main/longhorn

```
Updating (example):
     Type                                 Name                    Status                  Info
     pulumi:pulumi:Stack                  longhorn-example        **failed**              1 error; 6 messages
     ├─ eks:index:Cluster                 cluster-exp                                     
     │  └─ aws:eks:Cluster                cluster-exp-eksCluster                          
     └─ kubernetes:core/v1:Namespace      longhorn-system-exp                             
 -      └─ kubernetes:helm.sh/v3:Release  longhorn-exp            **deleting failed**     1 error

Diagnostics:
  kubernetes:helm.sh/v3:Release (longhorn-exp):
    error: 1 error occurred:
    	* job failed: BackoffLimitExceeded

  pulumi:pulumi:Stack (longhorn-example):
    [base.vpc.create_eip]
    [base.vpc.create_vpc]
    [base.cluster.create_cluster]
    [base.provider.create_provider]
    [develop_sdk.namespace.create_namespace]
    [devops_sdk.longhorn.Setup.up]
    error: update failed
```
