### ISSUE TITLE
Allow Pulumi resources to be extracted into relative modules

### ISSUE THREAD

**Issue by JakeGinnivan** [pulumi/pulumi#3669] opened 2019-12-16 23:14 UTC
I have been playing around with trying to move lambda callback functions into their own files to try and make the index.ts file easier to follow. When setting up a structure something like this, it works, except the local dependencies in the callback function are not included in the zip file?

<img width="194" alt="image" src="https://user-images.githubusercontent.com/453152/70950663-3a1a2380-209c-11ea-8e07-f80c0b3cecb8.png">

Is this sort of setup supported? Or is it expected the entire Pulumi application is inside index.ts?

**Comment by leezen** [comment] 2020-02-27 07:14
You don't need to have the entire application in index.ts. Could you please describe your setup more? In general, we should be packaging up the dependencies as part of the lambda function as described at https://www.pulumi.com/docs/tutorials/aws/serializing-functions/#determining-the-appropriate-node-modules-packages-to-include-with-a-lambda

**Comment by xai1983kbu** [comment] 2020-06-25 09:05
Hello @leezen!

I am using AWS AppSync with help of Pulumi.
My setup was taken from with article https://medium.com/@wesselsbernd/bff-back-end-for-front-end-architecture-as-of-may-2019-5d09b913a8ed

I have multiple Lambda functions which serve as Resolvers for AppSync. I have one index.js file which generates or checks updates for all Resolvers(Lambdas).
The problem is that all these Lambda Functions use all packages specified in the root node_module. It means that all packages are uploading for all Lambda Functions even if they don't use all of them.

I tried to isolate one Resolver (see on picture - \lambdas\Query\withDependencies\auroraDB).

![github](https://user-images.githubusercontent.com/14042193/85688481-77f6a500-b6da-11ea-9ada-dcd88bfd16a4.png)

But packages were not picked up.
Is it possible to modify Lambda Function so that it will pick up only packages that are imported in that specific function?

**Comment by leezen** [comment] 2020-06-25 16:10
This is unrelated to the original issue (and I'm going to close this issue actually since I haven't seen anything new on it).

@xai1983kbu  In some ways, your issue is related to https://github.com/pulumi/pulumi/issues/2619 and https://github.com/pulumi/pulumi/issues/2980

As a workaround for your current issue, you might want to take a look at using `CodePathOptions` which is documented here: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/runtime/closure/#CodePathOptions to exclude the extra packages.

**Closed by leezen** 2020-06-25 16:10 UTC

**Comment by xai1983kbu** [comment] 2020-06-25 19:21
@leezen thank you!
Before writing my previous post I looked at `CodePathOptions` but I didn't find an example of its usage and I still don't understand how to use it with `aws.lambda.CallbackFunction`.

I managed to solve my problem by using Layers. But I feel the better solution exists.
```
const createLambda = (
  lambdaCallbackFunction,
  lambdaCallbackFactory,
  resolverName
) => {
  // console.log(timeoutForLambda[resolverName])
  return new aws.lambda.CallbackFunction(
    `lambdaCallbackFunction_${resolverName}`,
    {
      callback: lambdaCallbackFunction,
      callbackFactory: lambdaCallbackFactory,
      runtime: 'nodejs12.x',
      timeout: timeoutForLambda.hasOwnProperty(resolverName)
        ? timeoutForLambda[resolverName]
        : 20,
      policies: environmentsForLambda.hasOwnProperty(resolverName)
        ? policiesForLambda[resolverName]
        : [aws.iam.ManagedPolicies.AWSLambdaFullAccess],
      environment: {
        ...(environmentsForLambda.hasOwnProperty(resolverName)
          ? {
              variables: environmentsForLambda[resolverName]['variables']
            }
          : { variables: { dummy: '123' } })
      },
      layers: layersForLambda.hasOwnProperty(resolverName)
        ? [layersForLambda[resolverName]]
        : []
    }
  )
}
```

**Comment by leezen** [comment] 2020-06-25 19:30
In your example above, I'm confused why you have both the factory and the callback specified? You should only need one.

`codePathOptions` is one of the args available to the CallbackFunction constructor arguments, e.g.

```typescript
new aws.lambda.CallbackFunction(
    `lambdaCallbackFunction_${resolverName}`,
    {
      callback: lambdaCallbackFunction,
      runtime: 'nodejs12.x',
      ...
      codePathOptions: {
          extraExcludePackages: ["package-a", "package-b", ...],
      }
    });
```

**Comment by xai1983kbu** [comment] 2020-06-25 20:11
@leezen thank you soo much! 

related to my example - yes I pass only one of them and `undefined` - for the second one.
