### ISSUE TITLE
Feature Request: Track StackReference Dependencies

### ISSUE THREAD

**Issue by dustinboss** [pulumi/pulumi#6994] opened 2021-05-07 21:03 UTC
StackReference is a powerful tool for building microservice architectures because it allows each service to own its own resources, as well as reference others'. However, it's a pain to keep track of which stacks reference one another. This is particularly important when determining if the variable name of an Output can be refactored on any given Stack.

Example of the problem: Let's say I have two projects: `Project A` and `Project B`. `Project A` has an output called `lambdaArn` and `Project B` reads that output via a StackReference. Now, if I decide to rename the output in `Project A` from `lambdaArn` to `imageResizerLambdaArn`, it will break my next `Project B` build, unless I remember to also update `Project B`. Currently, I have to keep track of those dependencies manually. This problem gets more complex as the number of dependencies increase and as the number of developers working on various projects increases.

It would be awesome if Pulumi kept track of the StackReference requests and could create a dependency map. Being able to quickly reference which other Projects depended on a particular Stack (as well as see what Outputs the dependent Stack makes reference to) would make it much easier to support interdependency between projects. 

## Affected feature

* StackReference
* Outputs

**Comment by lblackstone** [comment] 2021-05-11 17:47
I believe this is a duplicate of https://github.com/pulumi/pulumi/issues/2309

**Closed by lblackstone** 2021-05-11 17:47 UTC
Labels: resolution/duplicate
