### ISSUE TITLE
AttributeError:  object has no attribute '_transformations'

### ISSUE THREAD

**Issue by ebr** [pulumi/pulumi#14736] opened 2023-12-04 16:17 UTC
### What happened?

Trying to set up inheritance of a resource that itself inherits from `pulumi.ComponentResource` results in a failing check for `_transformations` attribute on the parent resource.

Since the parent resource inherits from `pulumi.ComponentResource`, I expect it to have `_transformations = []` by default.

Inheritance works as expected when the resource inherits directly from `pulumi.ComponentResource`.

### Example

```
class Application(pulumi.ComponentResource):

    def __init__(
        self,
        name: str,
        namespace: str,
        spec: Mapping[str, Any],
        opts: Optional[ResourceOptions] | None = None,
        labels: Optional[Mapping[str, str]] = None,
        annotations: Optional[Mapping[str, str]] = None,
    ):
    
    super().__init__("pkg:index:Application", name, None, opts)
```

```
class WidgetFactory(Application):
    def __init__(self, cluster, opts: Optional[ResourceOptions] = None) -> None:
        self.opts = ResourceOptions.merge(opts, ResourceOptions(parent=self))

        self.service_account_role = ServiceAccountRole(  #ServiceAccountRole also inherits from pulumi.componentResource
            cluster=cluster,
            service_account_name=self.name,
            namespace=self.namespace,
            opts=self.opts,
        )
```

``` 
File "/path/to/.venv/lib/python3.11/site-packages/pulumi/resource.py", line 799, in __init__                                                                               
        (parent._transformations or []) if parent is not None else []                                    
         ^^^^^^^^^^^^^^^^^^^^^^^                                                                           
    AttributeError: 'WidgetFactory' object has no attribute '_transformations'
```

### Output of `pulumi about`

CLI                                                                                                      
Version      3.94.2                                                                                      
Go Version   go1.21.4                                                                                    
Go Compiler  gc                                                                                          
                                                                                                         
Plugins                                                                                                  
NAME        VERSION                                                                                      
aws         6.9.0                                                                                        
aws-native  0.85.0                                                                                       
awsx        2.1.1                                                                                        
docker      4.4.5                                                                                        
eks         2.0.0                                                                                        
kubernetes  4.5.4                                                                                        
python      unknown                                                                                      
                                                                                                         
Host                                                                                                     
OS       debian                                                                                          
Version  bookworm/sid                                                                                    
Arch     x86_64 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2023-12-09 07:59
@ebr, it looks like the problem is you're missing a call to `super().__init__(...)` at the beginning of `WidgetFactory`'s `__init__`.

This minimal example works for me:

```python
from typing import Optional
from pulumi import ComponentResource, ResourceOptions

class ServiceAccountRole(ComponentResource):
    def __init__(self, name: str, opts: Optional[ResourceOptions] = None):
        super().__init__("pkg:index:ServiceAccountRole", name, None, opts)

class Application(ComponentResource):
    def __init__(self, name: str, opts: Optional[ResourceOptions] = None):
        super().__init__("pkg:index:Application", name, None, opts)

class WidgetFactory(Application):
    def __init__(self, name: str, opts: Optional[ResourceOptions] = None):
        super().__init__(name, opts) # <------ super().__init__ called before anything else
        self.opts = ResourceOptions.merge(opts, ResourceOptions(parent=self))
        self.service_account_role = ServiceAccountRole(f"{name}-account-role", opts=self.opts)

WidgetFactory("factory")
```

However, if I change `WidgetFactory` to have the `super().__init__` call at the end, then I get the same error you're seeing:

```python
class WidgetFactory(Application):
    def __init__(self, name: str, opts: Optional[ResourceOptions] = None):
        self.opts = ResourceOptions.merge(opts, ResourceOptions(parent=self))
        self.service_account_role = ServiceAccountRole(f"{name}-account-role", opts=self.opts)
        super().__init__(name, opts) # <------ at the end, results in AttributeError: 'WidgetFactory' object has no attribute '_transformations'
```

Hope this helps! I'm going to close the issue as "no repro".

**Closed by justinvp** 2023-12-09 07:59 UTC
Labels: kind/bug, area/sdks, language/python, resolution/no-repro
