### ISSUE TITLE
Pulumi Auto does not save provider versions in state

### ISSUE THREAD

**Issue by chomey** [pulumi/pulumi#11285] opened 2022-11-08 18:42 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When running Pulumi via auto for CI/CD flows, we see the following saved in the state:
```
      pulumi:providers:random:
        [id=c63ef00b-4d49-450b-82d6-c66a03e4c370]
        [urn=urn:pulumi:stool-pulumi::pulumi-prototype::pulumi:providers:random::random]

```

When we run `pulumi up` from the terminal, we see:
```
    ~ pulumi:providers:random: (update)
        [id=c63ef00b-4d49-450b-82d6-c66a03e4c370]
        [urn=urn:pulumi:stool-pulumi::pulumi-prototype::pulumi:providers:random::random]
      + version: "4.8.2"
```

It looks like the automation API just doesn't track the providers we've configured via the providers map:
```
	randomProvider, err := random.NewProvider(ctx, "random", &random.ProviderArgs{})
	if err != nil {
		return err
	}
	err = ctx.RegisterComponentResource("mycomponent", "name", component, pulumi.ProviderMap(map[string]pulumi.ProviderResource{
		"random": randomProvider,
	}))

```

### Affected area/feature

Automation API

**Comment by Frassle** [comment] 2022-11-11 10:23
I think this is actually a Go codegen bug not automation api. 
Compare [dotnet](https://github.com/pulumi/pulumi-random/blob/master/sdk/dotnet/Provider.cs#L29) which defaults the resource options Version field, to [Go](https://github.com/pulumi/pulumi-random/blob/master/sdk/go/random/provider.go#L29) which does nothing to automatically fill in the version based on the current SDK version.

**Comment by justinvp** [comment] 2023-07-26 22:56
Dupe of https://github.com/pulumi/pulumi/issues/13012

**Closed by justinvp** 2023-07-26 22:56 UTC
Labels: kind/bug, language/go, area/codegen, resolution/duplicate
