### ISSUE TITLE
Newer versions of the Pulumi CLI break dynamic resource name that was working with an older version

### ISSUE THREAD

**Issue by migueloller** [pulumi/pulumi#14605] opened 2023-11-17 14:39 UTC
### What happened?

Pulumi commands started failing in our developer's machine, but not on CI. We were seeing errors like this when running `pulumi preview`:

```bash
Diagnostics:
  pulumi:pulumi:Stack (orion-staging):
    error: Error: failed to register new resource orion-staging-db-migrate [kubernetes:batch/v1:Job]: 3 INVALID_ARGUMENT: invalid dependency URN: invalid URN "urn:pulumi:staging::orion::pulumi-nodejs:dynamic:Resource::stripe::WebhookEndpoint::orion-staging"
        at Object.registerResource (/Users/miguel/Code/cosmos/node_modules/.pnpm/@pulumi+pulumi@3.6.1/node_modules/@pulumi/pulumi/runtime/resource.js:219:27)
        at new Resource (/Users/miguel/Code/cosmos/node_modules/.pnpm/@pulumi+pulumi@3.6.1/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/miguel/Code/cosmos/node_modules/.pnpm/@pulumi+pulumi@3.6.1/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new Job (/Users/miguel/Code/cosmos/node_modules/.pnpm/@pulumi+kubernetes@3.5.0/node_modules/@pulumi/batch/v1/job.ts:105:9)
        at Object.<anonymous> (/Users/miguel/Code/cosmos/packages/orion/pulumi/program/app.ts:203:22)
        at Module._compile (node:internal/modules/cjs/loader:1256:14)
        at Module.m._compile (/Users/miguel/Code/cosmos/node_modules/.pnpm/ts-node@7.0.1/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/miguel/Code/cosmos/node_modules/.pnpm/ts-node@7.0.1/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:1119:32)
```

Given these weren't happening in CI we installed the same version of the Pulumi CLI, `3.6.1`, and the issue wasn't there.

### Example

 It seems that newer versions of the CLI don't accept resource names that have `::` as a separator. In our case here's the code for defining the dynamic resource mentioned in the error above:

```ts
  constructor(name: string, args: WebhookEndpointResourceArgs, opts?: CustomResourceOptions) {
    super(
      webhookEndpointProvider,
      `stripe::WebhookEndpoint::${name}`, // Note the `::` separators
      args as ResourceArgs<WebhookEndpointArgs & Partial<Stripe.WebhookEndpoint>>,
      opts,
    )

    this.secret = secret(this.secret)
  }
```

### Output of `pulumi about`

```
CLI          
Version      3.94.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in nodejs: executable='/Users/miguel/Library/Caches/fnm_multishells/13880_1700159356947/bin/node' version='v18.17.1'

Current Stack: makeswift/orion/staging

TYPE                                         URN
pulumi:pulumi:Stack                          urn:pulumi:staging::orion::pulumi:pulumi:Stack::orion-staging
pulumi:providers:pulumi-nodejs               urn:pulumi:staging::orion::pulumi:providers:pulumi-nodejs::default
pulumi:providers:gcp                         urn:pulumi:staging::orion::pulumi:providers:gcp::default_5_11_0
pulumi-nodejs:dynamic:Resource               urn:pulumi:staging::orion::pulumi-nodejs:dynamic:Resource::stripe::WebhookEndpoint::orion-staging
pulumi-nodejs:dynamic:Resource               urn:pulumi:staging::orion::pulumi-nodejs:dynamic:Resource::stripe::WebhookEndpoint::orion-staging-data-sync
gcp:sql/database:Database                    urn:pulumi:staging::orion::gcp:sql/database:Database::staging
pulumi:providers:random                      urn:pulumi:staging::orion::pulumi:providers:random::default_4_2_0
pulumi:providers:pulumi                      urn:pulumi:staging::orion::pulumi:providers:pulumi::default
random:index/randomString:RandomString       urn:pulumi:staging::orion::random:index/randomString:RandomString::orion-service-account-prefix
pulumi:providers:auth0                       urn:pulumi:staging::orion::pulumi:providers:auth0::default_2_2_0
gcp:pubsub/topic:Topic                       urn:pulumi:staging::orion::gcp:pubsub/topic:Topic::table-exports
auth0:index/resourceServer:ResourceServer    urn:pulumi:staging::orion::auth0:index/resourceServer:ResourceServer::orion-staging
gcp:serviceAccount/account:Account           urn:pulumi:staging::orion::gcp:serviceAccount/account:Account::orion
gcp:redis/instance:Instance                  urn:pulumi:staging::orion::gcp:redis/instance:Instance::orion-bullmq
gcp:storage/bucket:Bucket                    urn:pulumi:staging::orion::gcp:storage/bucket:Bucket::table-exports
gcp:redis/instance:Instance                  urn:pulumi:staging::orion::gcp:redis/instance:Instance::orion-cache
gcp:sql/databaseInstance:DatabaseInstance    urn:pulumi:staging::orion::gcp:sql/databaseInstance:DatabaseInstance::cosmos-staging
pulumi:pulumi:StackReference                 urn:pulumi:staging::orion::pulumi:pulumi:StackReference::makeswift/aquila/staging
pulumi:pulumi:StackReference                 urn:pulumi:staging::orion::pulumi:pulumi:StackReference::makeswift/renderer/staging
gcp:pubsub/subscription:Subscription         urn:pulumi:staging::orion::gcp:pubsub/subscription:Subscription::table-exports
gcp:storage/bucketIAMMember:BucketIAMMember  urn:pulumi:staging::orion::gcp:storage/bucketIAMMember:BucketIAMMember::table-exports
gcp:serviceAccount/key:Key                   urn:pulumi:staging::orion::gcp:serviceAccount/key:Key::orion
gcp:storage/bucketIAMMember:BucketIAMMember  urn:pulumi:staging::orion::gcp:storage/bucketIAMMember:BucketIAMMember::orion
pulumi:pulumi:StackReference                 urn:pulumi:staging::orion::pulumi:pulumi:StackReference::makeswift/cluster/staging
pulumi:providers:kubernetes                  urn:pulumi:staging::orion::pulumi:providers:kubernetes::cluster
kubernetes:core/v1:Secret                    urn:pulumi:staging::orion::kubernetes:core/v1:Secret::orion-service-account-key
kubernetes:batch/v1:Job                      urn:pulumi:staging::orion::kubernetes:batch/v1:Job::orion-staging-db-migrate
kubernetes:apps/v1:Deployment                urn:pulumi:staging::orion::kubernetes:apps/v1:Deployment::orion-staging
kubernetes:core/v1:Service                   urn:pulumi:staging::orion::kubernetes:core/v1:Service::orion-staging-auto-deploy
kubernetes:networking.k8s.io/v1:Ingress      urn:pulumi:staging::orion::kubernetes:networking.k8s.io/v1:Ingress::orion-staging-auto-deploy-v1
```

### Additional context

Note, the output of `pulumi about` above is when `pulumi preview` _doesn't_ work. A simple downgrade to `3.6.1` fixes it:

```bash
curl -fsSL https://get.pulumi.com | sh -s -- --version 3.6.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2023-11-17 14:53
Duplicate of https://github.com/pulumi/pulumi/issues/13968

**Closed by Frassle** 2023-11-17 14:53 UTC
Labels: kind/bug, resolution/duplicate
