### ISSUE TITLE
`pulumi new` cancel is a bit awkward

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#1781] opened 2018-08-16 00:34 UTC
When you do something like:

```sh
pulumi new https://github.com/pulumi/templates/tree/justin/k8s/kubernetes-typescript
```

and then cancel partway through, the CLI does not seem to clean up after itself. In particular, the directory contains a bunch of files, and the stack may or may not have been created, depending on how far you get.

The major pain of this is that if you try to re-run the command, you are not in charge of deleting all the stuff. I believe that what we really want to do is to delete this proactively on behalf of the user if we don't make it completely through init. (This is essentially what we did in ksonnet and believe me when I say it saved us so much heartache.)

**Comment by lukehoban** [comment] 2023-03-27 18:38
Closing as dupe of #12524 since there's a little more detail on how to go about addressing this there.

**Closed by lukehoban** 2023-03-27 18:38 UTC
Labels: area/cli, kind/enhancement, resolution/duplicate
