### ISSUE TITLE
[CLI] Output of stack status remains on `Creating (16s)` when run has finished.

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#11260] opened 2022-11-04 16:18 UTC
### What happened?

After running `pulumi up`, the status of the stack remained in `Creating (16s)` even when the run completed.

![pulumi-cli-status](https://user-images.githubusercontent.com/77923/200022554-48df1a1e-7fef-49b7-b952-8adaafc869a5.png)

### Steps to reproduce

Not yet.

### Expected Behavior

The status in the CLI should be updated to `Created (16s)`

### Actual Behavior

The status remained in `Creating (16s)`

### Output of `pulumi about`

Pulumi CLI 3.46.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment] 2023-01-06 19:27
Hey, @ringods I'd love to fix this issue, but I'm having difficulty reproducing it.

I have a couple of follow-up questions:
- Do you have a minimal repro?
- Do you have pulumi environment variables or CLI flags set that may change the behavior of the engine?

**Comment by justinvp** [comment] 2023-03-31 22:16
I'm going to close this since we haven't been able to reproduce it. @ringods, if you're able to repro again, please re-open the issue. Thanks!

**Closed by justinvp** 2023-03-31 22:16 UTC
Labels: kind/bug, area/cli, awaiting-feedback, resolution/no-repro
