### ISSUE TITLE
Pulumi automation can not handle objectValue in Config

### ISSUE THREAD

**Issue by ncd** [pulumi/pulumi#6809] opened 2021-04-19 10:14 UTC
I made pulumi config as an object.
```yaml
ram:
    roles:
    - assume_policy: autoscaler_assume
      name: cluster-autoscaler
      policy_attachments:
        custom_policies:
        - cluster_autoscaler
```
When I run stack refresh/up using pulumi.x.automation module --> I always failed due to an error: unexpected keyword argument 'objectValue'.
Recheck with pulumi stack history command:
```
"devops-ram:ram": {
        "value": "{\"roles\":[{\"assume_policy\":\"autoscaler_assume\",\"name\":\"cluster-autoscaler\",\"policy_attachments\":{\"custom_policies\":[\"cluster_autoscaler\"]}}]}",
        "objectValue": {
          "roles": [
            {
              "assume_policy": "autoscaler_assume",
              "name": "cluster-autoscaler",
              "policy_attachments": {
                "custom_policies": [
                  "cluster_autoscaler"
                ]
              }
            }
          ]
        },
        "secret": false
      }
    }
```

## Expected behavior

The code will run normally

## Current behavior

The code has error

## Steps to reproduce

1. Run pulumi automation with configuration is in object type.

**Comment by leezen** [comment] 2021-04-20 19:04
I believe this is a duplicate of https://github.com/pulumi/pulumi/issues/5506, which has some suggestions for potential workarounds.

**Comment by komalali** [comment] 2021-04-20 19:08
Hi, okay looking at this again I think I see what's going on here and it's not a dupe of #5506.

@ncd it looks like you're using automation API with python. Is that right? What version are you using?

**Comment by komalali** [comment] 2021-04-21 20:42
Okay, I just rechecked that we did indeed fix this issue in Pulumi 2.21.0 and we have tests for it, so I'm going to close this out. If you are using the latest version and are somehow still hitting this error, please reopen.

**Comment by followben** [comment] 2021-04-21 23:27
I'm striking the same issue.  I have a similar code & setup as [the local python example](https://github.com/pulumi/automation-api-examples/blob/main/python/local_program/automation/main.py) generates the following stacktrace on trying perform either the `refresh` or `up` operation on a stack:

```
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    up_res = stack.up(on_output=print)
  File "/Users/bstovold/Documents/venv/lib/python3.8/site-packages/pulumi/automation/_stack.py", line 279, in up
    summary = self.info()
  File "/Users/bstovold/Documents/venv/lib/python3.8/site-packages/pulumi/automation/_stack.py", line 578, in info
    history = self.history(page_size=1)
  File "/Users/bstovold/Documents/venv/lib/python3.8/site-packages/pulumi/automation/_stack.py", line 559, in history
    summary = UpdateSummary(kind=summary_json["kind"],
  File "/Users/bstovold/Documents/venv/lib/python3.8/site-packages/pulumi/automation/_stack.py", line 91, in __init__
    self.config[key] = ConfigValue(**config[key])
TypeError: __init__() got an unexpected keyword argument 'objectValue'
```

**Comment by ncd** [comment] 2021-04-22 02:38
@komalali  Thank Komal, the updated code has fixed my issue.

**Closed** 2021-04-22 16:00 UTC
Labels: area/automation-api
