### ISSUE TITLE
Give users the ability to throw errors for "Calling [toString] on an [Output<T>] is not supported"

### ISSUE THREAD

**Issue by hcharley** [pulumi/pulumi#5665] opened 2020-11-02 19:33 UTC
https://pulumi-community.slack.com/archives/CJ909TL6P/p1604120367076300

**Comment by clstokes** [comment] 2020-11-02 20:22
Sharing a screenshot of the conversation from Community Slack for when this rolls past the 10,000 message limit.

![image](https://user-images.githubusercontent.com/293763/97915183-e6d9af80-1d05-11eb-9c18-3fc41cc5728c.png)

**Comment by mikhailshilkov** [comment] 2022-07-14 12:48
Dupe of #4261

**Closed by mikhailshilkov** 2022-07-14 12:48 UTC
Labels: kind/enhancement, area/core, resolution/duplicate
