### ISSUE TITLE
Consider failing Config.require if the config value is a secret

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#16383] opened 2024-06-12 16:01 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Suppose a config variable is set as a secret:

```
pulumi config set --secret secret-variable secret-value
```

And consider the following toy example:

```ts
const config = new pulumi.Config();
const secretValue = config.require("secret-variable");
const r = new SomeResource("foo", {
  value: secretValue,
});
```

The use of `require` here means that its result is a plain value with its secretness removed. There is no error or warning, but now the state file and stack outputs will leak the secret value. The `pulumi up` operation will actually mask `secret-value` if it appears somewhere in stdout (e.g. in stack outputs printed) but this gives a false confidence to the user: they don't see the value, but it's still exposed (e.g. in `pulumi stack output` or in state JSON).

Consider a warning and pointing users to `requireSecret` instead. This is probably a breaking change, but let's brainstorm if we have a path to introduce it.

Tested with TypeScript, Python, C#.

### Affected area/feature

Config SDKs

**Comment by justinvp** [comment] 2024-06-21 07:37
This is a dupe of https://github.com/pulumi/pulumi/issues/7127

**Closed by justinvp** 2024-06-21 07:37 UTC
Labels: kind/enhancement, resolution/duplicate, area/config
