### ISSUE TITLE
pulumi up fails when provider plugin cannot be updated

### ISSUE THREAD

**Issue by robwruck** [pulumi/pulumi#7143] opened 2021-05-26 20:51 UTC
Given an existing project with an existing stack that uses a previous version of the provider plugin (aws 4.2.0),
when a new plugin version cannot be installed automatically (for example because /pulumi/home is owned by root, like in a docker container),
`pulumi up` fails with `no resource plugin 'aws-v4.5.1'` even though the plugin version referenced in the stack is installed.

`pulumi refresh` works without problems. So does `pulumi destroy`.

## Expected behavior
- `pulumi up` should not try to update plugins that are already installed (related to #4607 ?).
- even if it does, failure to do so should not abort `pulumi up` if a suitable plugin version is already installed.

## Current behavior
```
[resource plugin aws-4.5.1] installing
Downloading plugin: 0 B / 73.43 MiB [-------------------------------]   0.00% 0s
     Type                     Name                Plan     Info
     pulumi:pulumi:Stack      mystack-dev           
     └─ pulumi:providers:aws  default_4_5_1                1 error
 
Diagnostics:
  pulumi:providers:aws (default_4_5_1):
    error: no resource plugin 'aws-v4.5.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.5.1`
```

## Steps to reproduce
Since there seems to be no way to stop `pulumi up` from updating plugins, you'd have to do
- `pulumi up`
- Make $PULUMI_HOME read-only
- Wait for next release of provider plugin
- `pulumi up`
:-(

## Context (Environment)
Using docker image: pulumi/pulumi-nodejs:3.2.1

**Comment by lukehoban** [comment] 2021-05-28 23:48
It is currently the case that if you are using the `4.5.1` version of a package (from NPM, PyPI, NuGet, etc.), then you need to be able to acquire and use the `4.5.1` version of the corresponding plugin to do an update with that program code.  That is to ensure that the API you are using in your program exactly matches the implementation in the provider you are using. Allowing these to not match can lead to inconsistencies and unexpected failures.

You can pin the version of the provider you want to use in your program to a specific version to avoid moving to a new version dependency both of the package and of the plugin.

Because of that, you do need to run `pulumi up` in a context in which the plugins required by your program are either already installed, or can be installed on demand.  

This is not the case for `refresh` or `destroy` as those use the provider version from the last successfull deployment (the version in the state file), and do not require loading or running your program.

We may revisit some of this in the future, but I'll close this out as working as intended for now.

**Closed by lukehoban** 2021-05-28 23:48 UTC
Labels: kind/bug, resolution/by-design
