### ISSUE TITLE
Bad error message if policy pack isn't found

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#3945] opened 2020-02-20 18:49 UTC
If you try to run a policy pack, sometimes you get a pretty awful error message "failed to load plugin ... fork/exec ... no such file or directory"

```zsh
$ PULUMI_DEBUG_COMMANDS=true pulumi up \
    --cwd ./iam-user-reader \
    --policy-pack ./policy-pack \
    --skip-preview

error: policy pack "/Users/chris/go/src/github.com/chrsmith/pulumi-iam-user-validator/iam-user-reader/policy-pack/bin/index.js" failed to start: failed to load plugin /Users/chris/.pulumi/bin/pulumi-analyzer-policy: fork/exec /Users/chris/.pulumi/bin/pulumi-analyzer-policy: no such file or directory
```

The relevant information is in there, but it's hard to tease out. For example, in my case, I needed to set the `--policy-pack` flag to `../policy-pack`.

Ultimately we should detect this specific error and provide a more use-friendly message, since it's probably going to be a common occurrence.

**Comment by clstokes** [comment] 2020-02-20 22:22
Duplicate of https://github.com/pulumi/pulumi-policy/issues/198.

**Comment by chrsmith** [comment] 2020-02-21 16:30
Sorry for filing the dupe! Thanks for linking to it @clstokes , I recall you seeing this error but didn't find it (when I looked in this repo). While you did beat me to the punch in filing it, I closed out the `pulumi-policy` issue just because the code fix needs to be done in the `pulumi` repo. Sorry for the noise.

**Closed** 2020-02-28 20:48 UTC
Labels: kind/enhancement, pac
