### ISSUE TITLE
snapshot integrity failure; refusing to use it: child resource comes after it

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#13736] opened 2023-08-18 18:53 UTC
### What happened?

We currently receive the following error 1 out of 12 times, Approximately. We are running an hourly cron against the same code in ci. 1 out of 12 errors. 

Error: ```
stderr: error: getting snapshot: snapshot integrity failure; refusing to use it: child resource urn:pulumi:example-upgrade::standard-cluster::cluster:aws:eks$acs:aws:eks/eks:Cluster$cluster:eks:nodegroup$aws:ec2/launchConfiguration:LaunchConfiguration::default-launch-config's parent urn:pulumi:example-upgrade::standard-cluster::cluster:aws:eks$cluster:aws:eks:00000$cluster:eks:nodegroup::default comes after it```

### Expected Behavior

It should write the order correctly every time. 

### Steps to reproduce

I don't currently have that. 

### Output of `pulumi about`

CLI          
Version      3.76.12023-08-08.1758
Go Version   go1.20.7
Go Compiler  gc

Plugins

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ericrudder** [comment] 2023-09-05 18:05
Risk to Apple rollout

**Comment by justinvp** [comment] 2023-09-06 12:33
Summary of what the customer is doing when hitting this:

- They have a Python library (v0.6) for Pulumi that their users use. It was originally written for Pulumi 2.x and uses some older providers.
- They're upgrading their Python library (v0.7) to Pulumi 3.x and more recent provider versions.
- Note: They've re-parented some resource between v0.6 and v0.7 of their library, with aliases.
- They have tests that use v3.76.1 of the CLI that first deploys a program using v0.6 of their library, and then runs a subsequent deployment to upgrade to 0.7, which succeed.
- When the test destroys the stack, in roughly 1 out of 12 runs, they are running into this error, when a resource fails to delete (either it times out, or auth key expires)
- Originally, it was just K8s resources in the cluster that would fail during destroy (as that appears to be the most common type in their testing). However, they are running into a stack that was corrupted because it could not delete a DNS name (due to the auth key for that DNS system expiring during the run). So it's not limited to K8s resources.

**Comment by lukehoban** [comment] 2023-09-19 15:56
> When the test destroys the stack, in roughly 1 out of 12 runs, they are running into this error, when a resource fails to delete (either it times out, or auth key expires)

Do we have more details on this?

Is the operation that fails with this error a `pulumi destroy`?  Or does the `pulumi destroy` fail with a different error and then a subsequent `pulumi up` or `pulumi destroy` fails with this error?

If in the same operation, what do the failures look like exactly?  There's a timeout on some resource, and then immediately after that is shown there is another error with this snapshot integrity failure?

Also - is this with a filestate or http state backend?

**Comment by joeduffy** [comment] 2023-09-23 15:56
Has anybody noticed, and wondered why, the parent's type tree does not match the child's?

If we pick apart the child URN, `urn:pulumi:example-upgrade::standard-cluster::cluster:aws:eks$acs:aws:eks/eks:Cluster$cluster:eks:nodegroup$aws:ec2/launchConfiguration:LaunchConfiguration::default-launch-config`, we get a type tree of:

```
cluster:aws:eks$
acs:aws:eks/eks:Cluster$
cluster:eks:nodegroup$
aws:ec2/launchConfiguration:LaunchConfiguration::
```

And if we pick apart the parent's URN, `urn:pulumi:example-upgrade::standard-cluster::cluster:aws:eks$cluster:aws:eks:00000$cluster:eks:nodegroup::default`, we get:

```
cluster:aws:eks$
cluster:aws:eks:00000$
cluster:eks:nodegroup::
```

Wouldn't we have expected the latter to have been:

```
cluster:aws:eks$
acs:aws:eks/eks:Cluster$
cluster:eks:nodegroup::
```

given the child URN above? Is there some weird aliasing going on? And what is up with the four part type token names, in the child's case, `acs:aws:eks/eks:Cluster`, and in the parent's, `cluster:aws:eks:00000`.

Also, where did those `0000`s come from? Is that really in the program itself? It looks suspiciously machine-generated.

**Comment by justinvp** [comment] 2023-09-23 16:13
There are aliases involved here. The four part type tokens are from their Python library, which has regular Python components with four part type tokens. The 0000 numbers are also from the library.

**Comment by joeduffy** [comment] 2023-09-23 16:55
> There are aliases involved here. 

But when you alias a resource's parent, the intended behavior is that:

* All children get new URNs with the parent's new URN
* All children get aliases referring to their old URN containing the parent's old URN

In this example, I assume `acsd:aws:eks/eks:Cluster` was renamed to `cluster:aws:eks:00000`, and an alias was used to reparent the children without perturbing them?

If yes, why does the child still refer to the old URN?

**Comment by joeduffy** [comment] 2023-09-23 17:53
Another thought:

Although we obviously want to get to the root cause, if the resources are topologically sortable -- which I assume would be true unless somehow a cycle got introduced -- then we could in fact "fix" the state file in response to this error.

**Comment by Frassle** [comment] 2023-09-24 08:26
> If yes, why does the child still refer to the old URN?

This was a bug that was fixed in 3.83 by https://github.com/pulumi/pulumi/pull/13935.

But customer is reporting they're still seeing integrity failures _after_ that fix. So looks like something else is going on as well.

> then we could in fact "fix" the state file in response to this error.

Maybe, I'm a little worried about trying to auto-fix these because it's not clear what the real state of the world is anymore. It might not be safe to trust the ordering, this might more be palatable once we understand what exactly is the invalid operation happening.

**Comment by joeduffy** [comment] 2023-09-24 15:54
> This was a bug that was fixed in 3.83 by https://github.com/pulumi/pulumi/pull/13935.

Given how many versions are flying around, wouldn't the most likely explanation be that these state files are still somehow written by the buggy CLI?

Also, two follow-up questions:

1. Assume that was the root cause, is it clear why that would lead to the ordering problem (parent came after child)?

2. Given that the buggy CLI exists, it would seem we want to handle "upgrading" the old state -- it will always exist as a possibility since we shipped at least one version of the buggy CLI (do we know what version range it affected?)

**Comment by justinvp** [comment] 2023-09-25 05:26
> Given how many versions are flying around, wouldn't the most likely explanation be that these state files are still somehow written by the buggy CLI?

According to @rshade, the customer is running the steps in https://github.com/pulumi/pulumi/issues/13736#issuecomment-1708261641 all with 3.83.0 and still running into the stack integrity error. It had 5 successful runs before it failed.

**Comment by Frassle** [comment] 2023-09-25 08:59
> Assume that was the root cause, is it clear why that would lead to the ordering problem (parent came after child)?

I don't think it is the root cause. The parent URN mismatched fixed some other cases but this seems to be more complicated. The issue here is a re-ordering where the parent is ending up after the child in the snapshot but it's not clear how that can happen in the snapshot code. The best reproduction I've managed is that if we issue a delete for a parent and child at the same time but fail the parent deletion. But the delete scheduler never seems to issue a parent and child together.

> Given that the buggy CLI exists, it would seem we want to handle "upgrading" the old state

Yes probably. I think we can just fix up URNs given Parent fields, the order shouldn't even need fixing for #13935. I'm a bit worried about re-sorting state files to try and fix this issue when we don't understand what's causing it in the first place.

However even for the first it's not clear it's really worth having that extra code in the engine, this is only going to come from partial deployments before 3.83 and anyone who has hit that has probably already worked around it from backups because the state file is totally unusable once it's hit.

**Comment by justinvp** [comment] 2023-09-25 22:27
With the fix from https://github.com/pulumi/pulumi/issues/13903, we no longer get this error. Instead, we get a different error, captured in https://github.com/pulumi/pulumi/issues/14041. I'm going to close this in favor of https://github.com/pulumi/pulumi/issues/14041, which has a fix available for the underlying issue.

**Closed by justinvp** 2023-09-25 22:27 UTC
Labels: kind/bug, p0, resolution/duplicate, customer/feedback, area/engine, customer/lighthouse
