### ISSUE TITLE
Renaming of (fresh?) stack fails

### ISSUE THREAD

**Issue by jabbrwcky** [pulumi/pulumi#8769] opened 2022-01-18 13:53 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

While trying to wrap my head around the stack/project organization I was moving stacks around, causing pulumi CLI to crash.

State is stored in an AWS S3 bucket.
The stack was moved nonetheless.

```
 pulumi stack rename -s cost_usage_report/093278092578 093278092578
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.22.1
Go Version:       go1.17.5
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: slice bounds out of range [-1:]

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.17.5/libexec/src/runtime/debug/stack.go:24 +0x88
main.panicHandler()
	/private/tmp/pulumi-20220114-86930-8af235/pkg/cmd/pulumi/main.go:29 +0x48
panic({0x101df5ac0, 0x140007bc168})
	/opt/homebrew/Cellar/go/1.17.5/libexec/src/runtime/panic.go:1038 +0x21c
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).renameHistory(0x140009408a0, {0x16f8e2e6f, 0x1e}, {0x16f8e2e8e, 0xc})
	/private/tmp/pulumi-20220114-86930-8af235/pkg/backend/filestate/state.go:406 +0x490
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localBackend).RenameStack(0x140009408a0, {0x101f352e8, 0x1400013c008}, {0x101f67a40, 0x14000bf4570}, {0x16f8e2e8e, 0xc})
	/private/tmp/pulumi-20220114-86930-8af235/pkg/backend/filestate/backend.go:429 +0x2a8
github.com/pulumi/pulumi/pkg/v3/backend.RenameStack({0x101f352e8, 0x1400013c008}, {0x101f67a40, 0x14000bf4570}, {0x16f8e2e8e, 0xc})
	/private/tmp/pulumi-20220114-86930-8af235/pkg/backend/stack.go:72 +0x74
github.com/pulumi/pulumi/pkg/v3/backend/filestate.(*localStack).Rename(0x14000bf4570, {0x101f352e8, 0x1400013c008}, {0x16f8e2e8e, 0xc})
	/private/tmp/pulumi-20220114-86930-8af235/pkg/backend/filestate/stack.go:64 +0x54
main.newStackRenameCmd.func1(0x14000821080, {0x1400011be00, 0x1, 0x3})
	/private/tmp/pulumi-20220114-86930-8af235/pkg/cmd/pulumi/stack_rename.go:65 +0x15c
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunFunc.func1(0x14000821080, {0x1400011be00, 0x1, 0x3})
	/private/tmp/pulumi-20220114-86930-8af235/sdk/go/common/util/cmdutil/exit.go:96 +0x48
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000821080, {0x1400011be00, 0x1, 0x3})
	/private/tmp/pulumi-20220114-86930-8af235/sdk/go/common/util/cmdutil/exit.go:112 +0x48
github.com/spf13/cobra.(*Command).execute(0x14000821080, {0x14000ab4510, 0x3, 0x3})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14000134580)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x404
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/pulumi-20220114-86930-8af235/pkg/cmd/pulumi/main.go:48 +0x40
```

### Steps to reproduce

1. Create a fresh state (maybe import stack into new stack)
2. Rename stack

Expected: Move the state without errors
Actual: State is moved with errors (Maybe related to stack not having been used for real yet)

**Comment by mikhailshilkov** [comment] 2022-06-30 06:58
This is a dupe of #6526, so I'll close this issue to track a fix in #6526

**Closed by mikhailshilkov** 2022-06-30 06:58 UTC
Labels: kind/bug, area/backends, impact/panic, resolution/duplicate
