### ISSUE TITLE
[403] The provided update token has expired

### ISSUE THREAD

**Issue by JonCanning** [pulumi/pulumi#4619] opened 2020-05-13 09:08 UTC
I'm creating an Azure redis cache, a notoriously slow process, so I created a custom timeout since it was taking longer than the default 20 mins. However, I now get the following error:

`post-step event returned an error: failed to save snapshot: [403] The provided update token has expired.`

**Comment by leezen** [comment] 2020-05-14 03:18
What backend are you using and how do you provide credentials to that backend?

**Comment by GaboFDC** [comment] 2020-09-24 21:58
I'm getting a similar error `error: failed to complete update: [403] The provided update token has expired` when runing some infra with github provider. I'm mimgrating from s3 backend to pulumi.com. On s3 i had no issues.

https://app.pulumi.com/GaboFDC/github/github.singular/updates/1

**Comment by lukehoban** [comment] 2020-09-25 00:49
@GaboFDC Have you seen this on multiple updates? Or just the once?  Did the update take a long time, and/or was there a very large number of resource operations happening?  Anything else you can share with details on your environment when you hit this?

**Comment by GaboFDC** [comment] 2020-09-25 11:23
Just on this one. It's a lot of resources as I'm migrating a state that already existed. And it does takes a really long time to run. I'm running it from wsl. I also think that gihub provider is kind of slow when Creaton labels, and I'm creating a lot of them per repo

**Comment by lukehoban** [comment] 2021-05-21 03:55
Closing out as a dupe of https://github.com/pulumi/pulumi/issues/7094 which has a little bit of additional detail on what the expected problem is here.

**Closed by lukehoban** 2021-05-21 03:55 UTC
Labels: impact/reliability, kind/bug, resolution/duplicate
