### ISSUE TITLE
Fatal Error on Destroy

### ISSUE THREAD

**Issue by tomathom15** [pulumi/pulumi#9834] opened 2022-06-10 12:37 UTC
### What happened?

Trying to remove an existing stack

### Steps to reproduce

pulumi destroy

### Expected Behavior

destroyed stack

### Actual Behavior

Pulumi Version:   v3.34.0
Go Version:       go1.18.3
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/debug/stack.go:24 +0x68
main.panicHandler()
        /private/tmp/pulumi-20220608-46578-12kzc8y/pkg/cmd/pulumi/main.go:29 +0x38
panic({0x10481b9c0, 0x1058d51a0})
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/panic.go:838 +0x204
main.newDestroyCmd.func1(0x1f?, {0x14000c22500?, 0x14000915d58?, 0x10308d3d4?})
        /private/tmp/pulumi-20220608-46578-12kzc8y/pkg/cmd/pulumi/destroy.go:152 +0x764
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000bea500?, {0x105934f68, 0x0, 0x0})
        /private/tmp/pulumi-20220608-46578-12kzc8y/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000bea500, {0x105934f68, 0x0, 0x0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x14000a55900)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /private/tmp/pulumi-20220608-46578-12kzc8y/pkg/cmd/pulumi/main.go:48 +0x40

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2022-06-10 12:47
Duplicate of https://github.com/pulumi/pulumi/issues/9815. Will be fixed by the patch release 3.34.1 going out today.

**Closed by Frassle** 2022-06-10 12:47 UTC
Labels: kind/bug, resolution/duplicate
