### ISSUE TITLE
Create a mechanism to iterate over pulumi collections

### ISSUE THREAD

**Issue by alexandr-x-ursul** [pulumi/pulumi#12095] opened 2023-02-07 14:29 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I've been leveraging Pulumi to build up our IaC, and in the process I've found some workflows lacking.

Namely, I found no obvious way to iterate over any Pulumi collections, for example types like pulumi.StringArray, pulumi.StringMap, etc.. (I am using Go). Let me try to describe the functionality that I'm looking for, then I'll give examples of how I do it currently in Pulumi, and how a similar thing is done in Terraform, and finish with observations and a conclusion.

### The functionality
I built a custom component called "network", this component abstracts creation of an AWS network (VPC, subnets, routes, route tables, NAT Gateways, various associations, etc...), it exposes some basic inputs to allow for some customization.
This network component exports outputs, which may be useful to other components, for example it exports CIDR blocks or IDs of its private and public subnets. 

I also built another component, this one is called "nfs", it once against abstracts creation of resources, with the goal of simplifying the creation of an AWS EFS file system. Similarly, it exposes inputs for configuration. One such input is a collection of subnets in which to create mount targets, allowing these subnets to independently connect to the network file system. This component obviously does not know ahead of time how many such mount targets to create, because it depends on how many subnets you pass to it on input, equally the network component doesn't know how many subnet CIDR blocks or IDs it's going to export, because that depends on its own input. 

When these two components work together, the nfs component simply uses network component exports on its input.

---

### How I do this with Pulumi (Go)
Much of the code is cut for brevity
```
...
fs, err := efs.NewFileSystem(..., pulumi.Parent(&fileSystem), pulumi.Protect(true), pulumi.IgnoreChanges([]string{"creationToken"}))
	if err != nil {
		return nil, err
	}
...
_ = fsInput.Subnets.ToMapOutput().ApplyT(func(m map[string]interface{}) string {
		for k, v := range m {
			_, err = efs.NewMountTarget(..., &efs.MountTargetArgs{
				FileSystemId:   fs.ID(),
				SubnetId:       pulumi.String(reflect.ValueOf(v).String()),
				...
			}, pulumi.Parent(&fileSystem), pulumi.Protect(true))
			if err != nil {
				break
			}
		}
		return ""
	}).(pulumi.StringOutput)
...
```
---

### How a similar workflow might look like in Terraform
```
resource "aws_efs_file_system" "xxx" {
...
} 

resource "aws_efs_mount_target" "xxx" {
for_each = toset(var.subnetIDs)
file_system_id = aws_efs_file_system.xxx.id
subnet_id = each.value
...
}
```
---
### Observations and conclusion
In the Pulumi code, we can see that I am getting a pulumi.Map on input, which I have to convert into an output, then unpack with ApplyT, and only then do I get to manipulate with the underlying data. It is worth to note that this procedure is not recommended based on the docs here:https://www.pulumi.com/docs/intro/concepts/inputs-outputs/#apply
ApplyT is simply not meant for this purpose, my understanding is that this is more for pulumi type conversions, for which I have also used this elsewhere, also supported by the enforced callback signature with a required pulumi.Output type on return.
This procedure is overall very clunky, uncomfortable, and as far as I can tell, there is no actual recommended way to do this.

In contrast, in Terraform this is done with ease, the variable subnetIDs is referencing a module input which connects to the network module outputting subnet IDs, this is then converted from a list to a set to avoid index shifting causing resource recreation when a subnet is deleted.

The workflow that I would ideally want and frankly is what I first tried when I started out with Pulumi was simply:
```
// where myCollection is any pulumi collection type, like pulumi.Map, or pulumi.StringArray for example
for k, v := range myCollection {
...
}
```
---

### Final words
Please let me know if there is a proper way to solve this with Pulumi, I tried searching, but found nothing. 
If not, then adding a proper way to account for this basic abstraction workflow would be splendid. 
  
Thank you

**Comment by abhinav** [comment] 2023-02-07 22:25
Hello @alexandr-x-ursul, thanks for the detailed issue.
You're correct—this is correctly a limitation in Pulumi.
We've discussed this to some degree in #4834.
We don't currently have a solution to this,
but we _are_ continuing to think about this problem.

I'll mark this as a duplicate of #4834.

Please feel free to open another issue if you have more questions.
Thanks!

**Closed by abhinav** 2023-02-07 22:25 UTC
Labels: kind/enhancement, resolution/duplicate
