### ISSUE TITLE
`pulumi import` change name of resources 

### ISSUE THREAD

**Issue by oleksandr-kinship** [pulumi/pulumi#14733] opened 2023-12-04 15:03 UTC
### What happened?

Try to made bulk import of big amount the resources, some of imports were success but fine the issue that makes the process more complex. import command just add postfix because of name isn't unique. but names itself don't have to be unique in case if this different resources types, so `urn` can be correct and unique

### Example

As we all know resource should have `urn`, in the case important to know last parts of it `resource type` and `name`. 
here is few of resources that I want to import:
```
...
    {
      "id": "bla-bla-bla-1",
      "type": "kong:index/route:Route",
      "name": "subscription-svc",
      "provider": "kong"
    },
    {
      "id": "bla-bla-bla-2",
      "type": "kong:index/consumer:Consumer",
      "name": "subscription-svc",
      "provider": "kong"
    },
    {
      "id": "bla-bla-bla-3",
      "type": "kong:index/service:Service",
      "name": "subscription-svc",
      "provider": "kong"
    },
    ...
```
during run of command : `pulumi import --file import.json -s <my_stack>`
I got next output: 
```
Previewing import (<my_stack>):
     Type                           Name                                         Plan       
     pulumi:pulumi:Stack            infrastructure-<my_stack>          
 =   ├─ kong:index:Consumer         subscription-svc_1                   import     
 =   ├─ kong:index:Service              subscription-svc_2                   import     
 =   ├─ kong:index:Route                 subscription-core-svc             import
```

as we see to names were added postfix  _1, _2,_3 that not expect and wrong.
This lead to issue with recreating of resources and other issue, that should be avoided. 

### Output of `pulumi about`

CLI          
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.13.0
docker      3.4.1
kong        4.5.0
kubernetes  4.0.3
kubernetes  3.30.2
kubernetes  3.21.1
mysql       3.1.0
newrelic    5.1.0
nodejs      unknown

Host     
OS       darwin
Version  13.5.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v21.2.0'

<other non informative and sensitive data >

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2023-12-04 15:21
Yup known issue, hopefully have a fix for this this week.

Duplicate of https://github.com/pulumi/pulumi/issues/14618.

**Closed** 2023-12-04 15:22 UTC
Labels: kind/bug, resolution/duplicate, area/import
