### ISSUE TITLE
`_ListProxy` when creating `aws.autoscaling.Group`

### ISSUE THREAD

**Issue by doublethink13** [pulumi/pulumi#13618] opened 2023-07-28 15:17 UTC
### What happened?

when running `pulumi preview`, i'm getting the following error:

```txt
error: Exception calling application: '_ListProxy' object has no attribute 'get'
```

### Expected Behavior

no errors should appear

### Steps to reproduce

create an asg like so:

```python
aws.autoscaling.Group(
    name,
    aws.autoscaling.GroupArgs(
        launch_template=aws.autoscaling.GroupLaunchTemplateArgs(
            id=launch_template.id,
            version="$Latest",
        ),
        max_size=3,
        min_size=1,
        name=name,
        tags=[
            aws.autoscaling.GroupTagArgs(
                key=key, value=value, propagate_at_launch=False
            )
            for key, value in tags.items()
        ],
        target_group_arns=target_group_arns,
        vpc_zone_identifiers=private_subnets_ids,
    ),
)
```

### Output of `pulumi about`

```txt
CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
aws-native  0.69.0
awsx        1.0.2
cloudinit   1.3.0
docker      3.6.1
python      3.11.2

Host     
OS       ubuntu
Version  22.04
Arch     x86_64
```

### Additional context

if i pass an empty list to `tags`, it works

if i use `tags_collection` instead, it also works as expected

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2023-07-31 19:18
I think `_ListProxy` is from using python's multiprocessing module: https://docs.python.org/3/library/multiprocessing.html#proxy-objects

**Comment by doublethink13** [comment] 2023-08-01 07:20
> Could you let me know the type of the tags variable that you're calling tags.items() on to help me better reproduce the issue?

`dict[str,str]`

**Comment by dixler** [comment] 2023-08-01 15:05
> > Could you let me know the type of the tags variable that you're calling tags.items() on to help me better reproduce the issue?
> 
> `dict[str,str]`

I tried reproducing your issue with the following code blob and was unable to.

```python
import pulumi
import pulumi_aws as aws

name = "thing"
tags = {
    "a": "a",
    "b": "b",
    "c": "c",
}


launch_template = aws.ec2.LaunchTemplate("foobar",
    name_prefix="lt-",
    image_id="ami-0f34c5ae932e6f0e4",
    instance_type="t2.micro")

aws.autoscaling.Group(
    name,
    aws.autoscaling.GroupArgs(
        launch_template=aws.autoscaling.GroupLaunchTemplateArgs(
            id=launch_template.id,
            version="$Latest",
        ),
        max_size=3,
        min_size=1,
        name=name,
        tags=[
            aws.autoscaling.GroupTagArgs(
                key=key, value=value, propagate_at_launch=False
            )
            for key, value in tags.items()
        ],
        availability_zones=["us-east-1a"],
        #target_group_arns=target_group_arns,
        #vpc_zone_identifiers=private_subnets_ids,
    ),
)
```

From an earlier suggestion, are you using the `multiprocessing` library with pulumi?

**Comment by dixler** [comment] 2023-08-01 17:34
Interesting. It might be due to async pulumi internals. I'll try to tease it out more and let you know.

**Comment by dixler** [comment] 2023-08-01 22:39
How are the following variables defined?

```python
target_group_arns
private_subnets_ids
```

**Comment by doublethink13** [comment] 2023-08-02 07:12
```python
private_subnets_ids: Output[list[str]]
target_group_arns: list[Output[str]]
```

**Comment by estyrke** [comment] 2024-02-06 14:14
I also had this problem. Turns out, I have a resource policy which checks that required tags are present.  It contains the code

```python
ts = args.props.get("tags", {})
for rt in required_tags:
    if not ts or not ts.get(rt, None):
```

The problem is that, for aws.autoscaling.Group, the tags property is not a dict but a list (and hence has no `get` property). 

The solution was to add special handling for this resource type:
```python
        if args.resource_type == "aws:autoscaling/group:Group":
            # autoscaling groups have a special format for their tags property
            ts = {tag["key"]: tag["value"] for tag in ts}
```

Not sure if this is the OP:s exact case, but most likely there is some code somewhere which tries to treat the group's tags property as a dict when it is not.

**Comment by justinvp** [comment] 2024-12-20 22:33
Closing as no repro. I suspect this is indeed the issue that estyrk mentions.

**Closed by justinvp** 2024-12-20 22:33 UTC
Labels: kind/bug, language/python, resolution/no-repro, needs-repro
