### ISSUE TITLE
Redirects and pipes cause a golang exception

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi#5643] opened 2020-10-28 21:57 UTC
When piping or redirecting the CLI's stdout, I see an exception on stdout (and nothing on stderr).
Note that I am running through Docker (pulumi/pulumi-nodejs:2.12.1).

## Expected Behavior
stdout and stderr redirection should work "as expected". Colour off, stderr and stdout handled separately, no clever cursor movement, etc.

## Current Behavior
Both piping and redirecting stdout causes this exception:
```
panic: fatal: An assertion has failed: action must be non empty

goroutine 42 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0x0, 0x1cce43e, 0x18, 0x0, 0x0, 0x0)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/pkg/v2/backend/display.makeActionProgress(0x2b00940, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:59 +0xe5
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).refreshColumns(0xc000ebe000, 0x2b00940, 0x1, 0xc001b1f770, 0x5, 0x5, 0xc001564e40, 0x5, 0x5)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:410 +0x10e
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).refreshAllRowsIfInTerminal(0xc000ebe000)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:628 +0x373
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processNormalEvent(0xc000ebe000, 0x1cb7cca, 0xc, 0x1b07820, 0xc000a30f00)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:1107 +0x396
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processEvents(0xc000ebe000, 0xc001ac8050, 0xc001aaa540)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:1175 +0x145
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents.func1(0xc000ebe000, 0xc001ac8050, 0xc001aaa540, 0xc001aaa6c0)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:314 +0x3f
created by github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:313 +0x416
```
Piping or redirecting stderr (while leaving stdout going to the console) works fine.

## Steps to Reproduce
Run `pulumi preview > file.txt` or `pulumi up > file.txt`. It may have to be via Docker (I don't have Pulumi installed locally).

## Context (Environment)
Redirecting and piping are useful when processing a command in a CI script, or when there's lots of output. Running "pulumi preview --debug --show-replacement-steps" directly in the console is almost pointless, but it's the only option right now...

**Comment by viveklak** [comment] 2020-11-04 17:14
@tenwit thanks for opening the issue! We do have code to detect if it is running in a terminal or  (pulumi <cmd> | tee xx or pulumi <cmd> > /tmp/xx) both work and disable colorization etc. Could you provide the docker run command you are using? Could you also try adding `--non-interactive` flag?

**Comment by lukehoban** [comment] 2020-11-04 17:15
Note this is likely related to https://github.com/pulumi/pulumi/issues/4904 which is the same error.  And to https://github.com/pulumi/pulumi/issues/3935 which was fixed some time ago, but seemingly not completely.

**Comment by leezen** [comment] 2020-12-16 21:56
As part of looking at #5959, I looked at this issue as well since the panic seems to originate in a similar place. I tried to reproduce this a number of ways both via running interactively w/in the bash environment in the image and `docker run` and redirecting the output (tried both with redirecting the docker CLI stdout as well as the command I'm passing in). In all cases, the redirect succeeded (this was against specifically `pulumi/pulumi-nodejs:2.12.1`). I wonder if there are other conflating things at play (perhaps whatever terminal environment the container is being executed within?). I'm closing this for now assuming that it's the same issue. But please re-open if you're able to provide reproduction steps.

**Closed by leezen** 2020-12-16 21:56 UTC
Labels: kind/bug, kind/panic, needs-triage

**Comment by tenwit** [comment] 2020-12-21 22:03
Sorry for the late reply. This now working in 2.14.

> @tenwit thanks for opening the issue! We do have code to detect if it is running in a terminal or (pulumi | tee xx or pulumi > /tmp/xx) both work and disable colorization etc. Could you provide the docker run command you are using? Could you also try adding `--non-interactive` flag?

I'm using docker-compose, which doesn't have `--non-interactive`, but this part of it was sorted by adding the `-T` (disable pseudo-TTY allocation) flag. Without the `-T` flag, the redirects do still work, but with all the colour and movement escape codes included.
