### ISSUE TITLE
pulumi.yaml template config ignored

### ISSUE THREAD

**Issue by gsuess** [pulumi/pulumi#10581] opened 2022-09-02 01:08 UTC
### What happened?

Default configuration for stacks in `pulumi.yaml` under `template.config` have no effect.

https://www.pulumi.com/docs/reference/pulumi-yaml/#template-options

### Steps to reproduce

Create project with the following pulumi.yaml

```yaml
name: My Pulumi Project
runtime: nodejs
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: eu-central-1
```

Create a new stack

```bash
pulumi stack init
```

Get `aws:region`

```bash
pulumi config get aws:region
``` 

### Expected Behavior

Returns eu-central-1

### Actual Behavior

```
error: configuration key 'aws:region' not found for stack 'gsuess-dev-3'
```

### Output of `pulumi about`

CLI          
Version      3.39.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.5
Arch     arm64

This project is written in nodejs: executable='/Users/gsuess/.nvm/versions/node/v18.7.0/bin/node' version='v18.7.0'

Current Stack: gsuess-dev-3

Found no resources associated with gsuess-dev-3

Found no pending operations associated with gsuess-dev-3

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/gsuess
User           gsuess
Organizations  gsuess, Qualifyze

Dependencies:
NAME                              VERSION
shx                               0.3.4
@types/pg                         8.6.5
jest                              28.1.3
@typescript-eslint/parser         4.33.0
eslint-plugin-prettier            3.4.1
eslint                            7.32.0
lint-staged                       11.2.6
ts-node                           10.9.1
@changesets/changelog-github      0.4.6
@pulumi/random                    4.8.2
@typescript-eslint/eslint-plugin  4.33.0
pg                                8.8.0
prettier                          2.7.1
ts-jest                           28.0.8
typescript                        4.7.4
@pulumi/postgresql                3.6.0
@types/node-fetch                 2.6.2
@pulumi/aws                       5.13.0
eslint-config-prettier            8.5.0
husky                             7.0.4
is-ci                             3.0.1
jest-ts-webcompat-resolver        1.0.0
@changesets/cli                   2.24.3
@pulumi/aws-quickstart-vpc        0.0.2

Pulumi locates its logs in /var/folders/_j/n3zrsq6n373c_18tsgvfs2yc0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment] 2022-09-02 16:10
Hi there @gsuess I believe this part of our work towards #10602 and will be fixed when hierarchical config is implemented

**Comment by mikhailshilkov** [comment] 2022-09-02 19:36
To elaborate on Zaid's answer:

- `template.config` has no effect on stack configs. It's sole purpose is to query for config values when a user generates their program from a template (e.g. `pulumi new aws-typescript` will ask for AWS region)
- we plan to implement "hierarchical config" which will use the top-level `config` section that will enable you to set project value configuration values

I'll go ahead and close this issue as by design, we'll track the project config in https://github.com/pulumi/pulumi/issues/2307#issuecomment-1225592223

**Closed by mikhailshilkov** 2022-09-02 19:36 UTC
Labels: kind/bug, resolution/by-design, area/config

**Comment by gsuess** [comment] 2022-09-05 16:59
Okay, but then at least the documentation should clarify that the effect that one would expect from it.

**Comment by susanev** [comment] 2022-09-05 17:03
i agree! ive opened up https://github.com/pulumi/pulumi-hugo/issues/1906 to fix
