### ISSUE TITLE
Attempt to initialize with Azure Keyvault Secrets Provider fails with low signal error

### ISSUE THREAD

**Issue by SirensOfTitan** [pulumi/pulumi#6332] opened 2021-02-13 14:26 UTC
When either changing a stack to use an Azure Keyvault, or when initializing a new pulumi project, it fails to initialize with an error.

## Expected behavior
When running something like:
```
pulumi new azure-typescript --secrets-provider azurekeyvault://foobar.vault.azure.net/keys/foo
```

... it should initialize a new project with the secrets provider set.

## Current behavior
What occurs now is when running the command above, I type in the project name, project description, and stack name, then it errors out like so:
```
Sorry, could not create stack 'dev': open keeper azurekeyvault://kintabapulumi.vault.azure.net/keys/pulumisecret: failed to Dial default KeyVault: Invoking Azure CLI failed with the following error:
```

`AZURE_KEYVAULT_AUTH_VIA_CLI="true"` is set in environment, as without it, the pulumi process just hangs (it sticks on the `Created stack 'dev'` line and doesn't do anything past that).

## Steps to reproduce

1. Source my env file, which sets `AZURE_STORAGE_KEY` to the correct blob storage (using the `az` util), and sets `AZURE_KEYVAULT_AUTH_VIA_CLI` to `"true"`.  
2. Run `pulumi new azure-typescript --secrets-provider azurekeyvault://foo.vault.azure.net/keys/pulumisecret` (I've tried this with the key existing, not existing, and by specifying the key version after the key, e.g. `azurekeyvault://foo.vault.azure.net/keys/pulumi/6068ccb396e34e1b9f18eeb42c567eda`
3. Notice that `pulumi` fails out with the error listed above.   There is no message after `Invoking Azure CLI failed with the following error:`, and I've ensured `az` works (and that I'm logged in).

As I mentioned above, if one unsets the `AZURE_KEYVAULT_AUTH_VIA_CLI` environment variable, the script just hangs after emitting the message `Created stack 'dev'`.

I've also tried creating the pulumi project using the default passphrase-based secrets provider, then switching over, i.e. `pulumi stack change-secrets-provider azurekeyvault://[...]` with the same result as above.

## Context (Environment)

I'm trying to set up an Azure environment using Azure Keyvault and Azure-blob based state management for a Pulumi project.  I cannot actually set it up, and don't want to use passphrase-based encryption.

I'm running on Pulumi `v2.20.0`.  I've tried initializing a project of `azure-nextgen-typescript` and `azure-typescript` just to be exhaustive.  The `az` client works correctly, as I use it in an env script to initialize the `AZURE_STORAGE_ACCOUNT` variable. 

I'm running pulumi from my local device, without using a service user (as I want my team to be able to auth and use `pulumi` using their azure credentials).

## Affected feature

Azure secrets provider seems to be the issue.

**Comment by stack72** [comment] 2021-02-16 20:57
Hi @SirensOfTitan 

I am going to close this out as a duplicate of https://github.com/pulumi/pulumi/issues/4209

We can use that initial issue to track any changes here

Paul

**Closed by stack72** 2021-02-16 20:57 UTC
