### ISSUE TITLE
Ignore Support for FileArchive

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi#9884] opened 2022-06-17 16:30 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`FileArchive` allows us to treat a directory as an input to some other Pulumi resources, meaning that when files are changed we can rebuild. However, there's no way to specify that certain files within the archive should be ignored. I'd like to see us support `.gitignore`, `.dockerignore`, or arbitrary ignore list of strings within the code itself.

**Comment by Frassle** [comment] 2022-06-17 17:44
Duplicate of https://github.com/pulumi/pulumi/issues/9059

**Comment by Frassle** [comment] 2022-06-17 17:44
Although I am going to copy your comment about ignore files to that other ticket.

**Closed by Frassle** 2022-06-17 17:44 UTC
Labels: kind/enhancement, resolution/duplicate
