### ISSUE TITLE
Bug in python doc generation. 

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#12056] opened 2023-02-03 12:32 UTC
### What happened?

There is currently a bug in python doc generation where the inner `_` is not escaped, see: https://github.com/pulumi/pulumi-aws/pull/2347#discussion_r1095157137

### Expected Behavior

Docs are generated correctly

### Steps to reproduce

Not Required

### Output of `pulumi about`

Not Required

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment] 2023-02-05 22:04
Hey there Richard! You're right; good catch! I'm going to close this as a duplicate of https://github.com/pulumi/pulumi/issues/12075 which landed just shortly before your issue did.

**Closed by RobbieMcKinstry** 2023-02-05 22:04 UTC
Labels: kind/bug, resolution/duplicate
