### ISSUE TITLE
Update `pulumi` CLI plugin download process to use location in Pulumi Package

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi#6932] opened 2021-04-29 21:14 UTC
We want the experience of consuming a Pulumi Package to be straightforward:

1. Find the package on your package manager of choice (npm, NuGet, PyPI, GitHub (for Go modules)
2. Add it to your Pulumi program (e.g. via `npm i [package] --save` or adding it to your `requirements.txt`)
3. Write code
4. Run `pulumi up` (and have the Pulumi Package's plugin acquired automatically behind the scenes, just like it is for cloud provider Pulumi Packages today)

Accordingly, the work in this issue is to react to the new metadata introduced in #6931 and ensure that the plugin download process uses that metadata.

**Comment by infin8x** [comment] 2021-12-09 18:29
@justinvp @iwahbe  I think I can close this as a duplicate of all the other work you're working on, right?

**Comment by iwahbe** [comment] 2021-12-09 18:48
Yes, this is a duplicate of https://github.com/pulumi/pulumi/issues/7242.

**Closed** 2021-12-09 18:48 UTC
Labels: kind/enhancement, area/multi-language-components, size/S, resolution/duplicate
