### ISSUE TITLE
delete-replace on parent resource causes updates to fail

### ISSUE THREAD

**Issue by beetahnator** [pulumi/pulumi#2327] opened 2018-12-28 14:41 UTC
If you specify the `parent` under [CustomResourceOptions](https://pulumi.io/reference/pkg/nodejs/@pulumi/pulumi/#CustomResourceOptions) to a resource that will be `delete-replace`'d, the update will fail.

cc @hausdorff 

![Failure Log](https://dropbox.azam.at/Screen-Shot-2018-12-28-15-46-51.png)

Can be reproduced using this example:

```javascript
"use strict";
const pulumi = require("@pulumi/pulumi");
const k8s = require("@pulumi/kubernetes");
const date = new Date();

let currentTime = date.getMinutes().toString();

let pod = {
  metadata: {
    labels: { app: 'redis' },
  },
  spec: {
    containers: [{
      name: 'redis',
      image: 'redis',
      imagePullPolicy: "Always"
    }]
  }
}

let statefulSet = new k8s.apps.v1.StatefulSet('redis', {
  metadata: { name: 'redis' },
  spec: {
    serviceName: 'redis',
    replicas: 2,
    updateStrategy: { type: "RollingUpdate" },
    podManagementPolicy: "Parallel",
    selector: { matchLabels: pod.metadata.labels },
    template: pod,
    volumeClaimTemplates: [{
      metadata: { name: "data" },
      spec: {
        accessModes: [ "ReadWriteOnce" ],
        storageClassName: "gp2",
        resources: {
          requests: { storage: `${currentTime}Gi`}
        }
      }
    }]
  }
});

let service = new k8s.core.v1.Service('redis', {
  metadata: {
    name: 'redis'
  },
  spec: {
    type: "NodePort",
    ports: [{
        name: 'redis',
        port: 6379
    }],
    selector: pod.metadata.labels
  }
}, { parent: statefulSet });
```

**Comment by swgillespie** [comment] 2019-01-04 23:08
Thanks for the report - the engine should never be deleting a parent before its child. Breaking that invariant is what leads to the "post-step event returned an error" failure.

**Comment by mazamats** [comment] 2019-01-05 02:13
In some cases deleting the child doesn't really make sense though.

In the above example it would delete the service which would cause the load balancer to be recreated.

**Comment by swgillespie** [comment] 2019-01-07 17:04
> In some cases deleting the child doesn't really make sense though.

In that case, I'd think that the child probably shouldn't actually be a child of its parent resource, but instead the child resource should depend on the parent resource in the normal way.

I'm actually not sure what the engine's semantics should be here. I figure there are a few options available to the engine when it deletes a resource with children:

1. It transitively deletes all children eagerly, like a delete-before-replace
2. It issues an error, e.g. "you can't cause the deletion of a resource with children"
3. We change the engine's snapshot verification to relax the requirement that parent resources be in the snapshot.

3 sounds like trouble. 1 is not that great either since, as @mazamats says, it would cause resources to get deleted and re-created unnecessarily. I'd have to ponder this some more but I'm almost leaning towards 2 at this point.

cc @pgavlin, curious about your thoughts?

**Comment by mazamats** [comment] 2019-01-07 18:37
> It issues an error, e.g. "you can't cause the deletion of a resource with children"

Works for me

**Comment by pgavlin** [comment] 2019-01-07 18:51
I think that (2) is fine for now. It may be the case that we have to relax this in the future, but clarifying the issue should be immediately helpful.

**Comment by pgavlin** [comment] 2019-08-07 20:07
We could also approach this by re-parenting all of the children from the resource to be deleted to that resource's parent as part of the deletion. @lukehoban @ellismg what do you think? I'm considering that or making this an error for Q3.

**Comment by stang** [comment] 2019-08-27 15:57
Hi,

We ended up in this situation - is there currently any workaround to manually recover from it?

**Comment by joeduffy** [comment] 2021-12-31 18:39
I tried to reproduce this just now, and could not. Is it possible we fixed this along the way?

I actually don't see why this wouldn't "just work" since the dependency is on the URN which doesn't change simply because you replaced a resource. Indeed, we seem to have done the work (via things like pendingReplacement) to ensure replacement is "atomic" even in the face of the resource replacement failing. Perhaps at the time, we hadn't done some of this work and so there would be periods of time where the parent was missing in the checkpoint, hence the failure?

For example, here is what I believe to be a simple repro program:

```typescript
import * as aws from "@pulumi/aws";

const bucket1 = new aws.s3.Bucket("my-bucket", {
    bucket: "bba111-1298724",
});
const bucket2 = new aws.s3.Bucket("my-bucket2", {
    bucket: "bba111-1298722",
}, { parent: bucket1 });
```

The following things work fine:

* Change `my-bucket`'s `bucket`, triggering a replacement
* Change `my-bucket`'s `bucket` to an invalid bucket name (like `bbaa1111------------------`); it fails, but still works fine
* Change `my-bucket`'s name to something else, causing it to get a new URN
* Do any of the above to `my-bucket2`

I am closing this out but please reopen with more details if I misunderstood or missed something.

**Closed** 2021-12-31 18:39 UTC
Labels: kind/bug, area/providers, resolution/no-repro
