### ISSUE TITLE
Undefined value in `pulumi.all` confuses preview that there are always changes to apply

### ISSUE THREAD

**Issue by pbzdyl** [pulumi/pulumi#2313] opened 2018-12-20 08:32 UTC
I have the following use case:

I create a GKE cluster:

```
const cluster = new gke.Cluster('my-cluster', {
    name: 'my-cluster',
    project: 'my-project',
    ....
})
```

Then I create kubeconfig - notice that in order to support both regional and zonal clusters I use either `cluster.zone` or `cluster.regional` [whichever is available](https://www.terraform.io/docs/providers/google/r/container_cluster.html#zone) to construct the k8s context name (I would like to have the function to create kubeconfig yaml in a utility function which might be called with either types of GKE clusters):

```
const k8sConfig = pulumi.
    all([ cluster.project, cluster.name, cluster.endpoint, cluster.masterAuth, cluster.zone, cluster.region ]).
    apply(([ project, name, endpoint, auth, zone, region ]) => {
        const location = zone || region
        const context = `${project}_${location}_${name}`
        return `apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${auth.clusterCaCertificate}
    server: https://${endpoint}
  name: ${context}
contexts:
- context:
    cluster: ${context}
    user: ${context}
  name: ${context}
current-context: ${context}
kind: Config
preferences: {}
users:
- name: ${context}
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
`;
    });
```

And then I used it to construct my k8s provider and create a configmap:

```
const k8sProvider = new k8s.Provider('k8s-cluster', {
    kubeconfig: k8sConfig
})

const appConfig = new k8s.core.v1.ConfigMap('app-config', {
    data: { 'app-config.txt': 'sample contents'}
}, {
    provider: k8sProvider
})
```

The issue is that if one of the inputs is `undefined` (`region` in my scenario) then whenever I run `pulumi preview` there will be a change detected to be applied even though there was no change in my code. When I remove `region` from `all` and `apply` arguments array and use just `zone` the issue disappears.

**Comment by pgavlin** [comment] 2019-07-11 20:56
cc @CyrusNajmabadi

**Comment by lukehoban** [comment] 2019-07-25 17:35
> there will be a change detected

Can you share what change is proposed?

Is this perhaps somehow related to https://github.com/pulumi/pulumi/issues/2433?

**Comment by pbzdyl** [comment] 2019-07-30 06:46
Unfortunately, I don't have this information and I don't have time to reproduce the issue now :(

**Comment by CyrusNajmabadi** [comment] 2019-08-06 00:43
@pbzdyl So here's a potential workaround you can apply locally.  Here's the basic  issue, during preview only one of these values is known, and the other is not, and we don't run the lambdas passed to `.apply` in that case because we're concerned it may crash if passed an undefined value.  Clearly in your case, you still want the lambda to run, and you're resilient to that issue.

To help with that, I've created a helper function you can put in your code like so:

```ts
        function or<T>(output1: Output<T>, output2: Output<T>): Output<T>;
        function or<T>(output1: any, output2: any): any {
            const val1 = output1.promise();
            const val2 = output2.promise();
            return new Output<T>(
                new Set([...output1.resources(), ...output2.resources()]),
                Promise.all([val1, val2])
                       .then(([val1, val2]) => val1 || val2),
                Promise.all([val1, output1.isKnown, output2.isKnown])
                       .then(([val1, isKnown1, isKnown2]) => val1 ? isKnown1 : isKnown2),
                Promise.all([val1, output1.isSecret, output2.isSecret])
                       .then(([val1, isSecret1, isSecret2]) => val1 ? isSecret1 : isSecret2));
        }
```

The body isn't really relevant.  But, effectively, what it's saying is "if i have two outputs, and one is known and the other isn't, give me the one that is known."  With this you can change your above code to:

```ts
const k8sConfig = pulumi.
    all([ cluster.project, cluster.name, cluster.endpoint, cluster.masterAuth, or(cluster.zone, cluster.region) ]).
    apply(([ project, name, endpoint, auth, location ]) => {
        // same as before
```

this should now run and should give you the semantics you want.  i.e. that it will pick cluter.zone if it is known, or cluster.region otherwise.  in other words, it's kinda like `a || b` in JavaScript, except now for Outputs!  It will give you the first one if it's truthy, otherwise you get the second one.

Let me know if htis works for you.  If so, we can consider making this a built-in function provided by the platform.  Thanks!

**Comment by CyrusNajmabadi** [comment] 2019-08-06 19:59
There's a root cause for this that we're looking into fixing.  But, in the meantime, the 'hacky' approach i listed above should hopefully work for you.  Closing out for now as we track things through the other bug.  If you still have an issue here even with the workaround, please let us know!

**Closed by CyrusNajmabadi** 2019-08-06 19:59 UTC
Labels: feature/q3
