### ISSUE TITLE
Oracle Cloud, the world's unambiguous IaaS champion, not supported

### ISSUE THREAD

**Issue by hugbubby** [pulumi/pulumi#6446] opened 2021-03-01 21:01 UTC
This tool lacks support for the officially GOATed IaaS provider: Oracle Cloud Infrastructure. Oracle cloud is twice as cheap and twice as performant as AWS for most workloads; in some cases, like bandwidth heavy products, the difference is 10x. This is the only defining factor for kubernetes cloud installations; the entire point of container orchestration systems is to abstract the other details, and oracle has full support for all the important Kubernetes primitives. There are issues with plugin support, but those are inconsiderable compared to the cost savings, provided you are actually good at systems administration and are not afraid of mildly inconvenient technical problems. Only brainwashed technology professionals constantly grasping for the newest most hip toys, spooked instantly by the brand name (that being their only way to evaluate different products), even consider using the outmoded alternatives. By not supporting this god-tier offering Pulumi is probably inducing losses of up to a million+ a year simply by encouraging startups to begin elsewhere.

**Comment by stack72** [comment] 2021-03-01 21:07
Hi @hugbubby 

Thanks for opening this issue - this is something that was requested in https://github.com/pulumi/pulumi/issues/5948 so I am going to close this out as duplicate of that issue

By linking this issue here we can ensure that we can see it's tracked 

Thanks again

Paul

**Comment by hugbubby** [comment] 2021-03-01 21:08
> Hi @hugbubby
> 
> Thanks for opening this issue - this is something that was requested in #5948 so I am going to close this out as duplicate of that issue
> 
> By linking this issue here we can ensure that we can see it's tracked
> 
> Thanks again
> 
> Paul

Frankly I think that issue should be closed and merged into this one, as I do not feel it reflects the gravity of the situation.

**Comment by stack72** [comment] 2021-03-01 21:10
> > Hi @hugbubby
> > Thanks for opening this issue - this is something that was requested in #5948 so I am going to close this out as duplicate of that issue
> > By linking this issue here we can ensure that we can see it's tracked
> > Thanks again
> > Paul
> 
> Frankly I think that issue should be closed and merged into this one, as I do not feel it reflects the gravity of the situation.

Hi @hugbubby 

We close the most recent so we can track the entire process of request -> complete

Paul

**Closed by stack72** 2021-03-01 21:10 UTC
Labels: area/providers
