### ISSUE TITLE
Deprecated inputs on functions in python are always shows (regardless of if the input is used)

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#17965] opened 2024-12-09 11:31 UTC
### What happened?

When a user ran a program that invoked a function with a deprecated input, the warning for the field was printed, even though the user **did not** use the deprecated field. I have been able to reproduce locally.

Similar to https://github.com/pulumi/pulumi/issues/12546

### Example

From https://github.com/pulumi/pulumi-hcloud/issues/651.

```python
import pulumi_hcloud as hcloud

core_network = hcloud.Network(
    "core1",
    name="core1",
    ip_range="10.123.0.0/24",
)


hcloud.get_network_output(id=core_network.id.apply(int))
```

`Pulumi.dev.yaml`:

```yaml
environment:
  - providers/all
```

### Output of `pulumi about`

```
CLI          
Version      3.142.1-dev.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  cloudflare  5.40.1
resource  gcp         8.3.1
resource  hcloud      1.20.1
language  python      3.134.2-dev.0
resource  vault       6.3.0

Host     
OS       darwin
Version  15.1.1
Arch     arm64

This project is written in python: executable='/Users/iwahbe/Projects/pulumi/langs/python/venv/bin/python' version='3.12.7'

Current Stack: pulumi/ian-test-python/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME               VERSION
pip                24.0
pulumi_cloudflare  5.40.1
pulumi_gcp         8.3.1
pulumi_hcloud      1.20.1
pulumi_vault       6.3.0

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Additional context

Tracing the call stack of `hcloud.get_network_output`, we see (with comments removed):

```python
@_utilities.lift_output_func(get_network)
def get_network_output(id: Optional[pulumi.Input[Optional[int]]] = None,
                       ip_range: Optional[pulumi.Input[Optional[str]]] = None,
                       labels: Optional[pulumi.Input[Optional[Mapping[str, str]]]] = None,
                       most_recent: Optional[pulumi.Input[Optional[bool]]] = None,
                       name: Optional[pulumi.Input[Optional[str]]] = None,
                       with_selector: Optional[pulumi.Input[Optional[str]]] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetNetworkResult]:
    ...
```

```python
def get_network(id: Optional[int] = None,
                ip_range: Optional[str] = None,
                labels: Optional[Mapping[str, str]] = None,
                most_recent: Optional[bool] = None,
                name: Optional[str] = None,
                with_selector: Optional[str] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNetworkResult:
    __args__ = dict()
    __args__['id'] = id
    __args__['ipRange'] = ip_range
    __args__['labels'] = labels
    __args__['mostRecent'] = most_recent
    __args__['name'] = name
    __args__['withSelector'] = with_selector
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('hcloud:index/getNetwork:getNetwork', __args__, opts=opts, typ=GetNetworkResult).value

    return AwaitableGetNetworkResult(
        delete_protection=pulumi.get(__ret__, 'delete_protection'),
        expose_routes_to_vswitch=pulumi.get(__ret__, 'expose_routes_to_vswitch'),
        id=pulumi.get(__ret__, 'id'),
        ip_range=pulumi.get(__ret__, 'ip_range'),
        labels=pulumi.get(__ret__, 'labels'),
        most_recent=pulumi.get(__ret__, 'most_recent'),
        name=pulumi.get(__ret__, 'name'),
        with_selector=pulumi.get(__ret__, 'with_selector'))
```

```python
class AwaitableGetNetworkResult(GetNetworkResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNetworkResult(
            delete_protection=self.delete_protection,
            expose_routes_to_vswitch=self.expose_routes_to_vswitch,
            id=self.id,
            ip_range=self.ip_range,
            labels=self.labels,
            most_recent=self.most_recent, # <--- PROBLEM HERE
            name=self.name,
            with_selector=self.with_selector)
```

The issue is that `self.most_recent` in the `AwaitableGetNetworkResult` block invokes the field getter, which prints the warning message. Changing `self.most_recent` to `pulumi.get(self, 'most_recent')` fixes the bug:

```patch
 class AwaitableGetNetworkResult(GetNetworkResult):
     # pylint: disable=using-constant-test
     def __await__(self):
         if False:
             yield self
         return GetNetworkResult(
             delete_protection=self.delete_protection,
             expose_routes_to_vswitch=self.expose_routes_to_vswitch,
             id=self.id,
             ip_range=self.ip_range,
             labels=self.labels,
-            most_recent=self.most_recent,
+            most_recent=pulumi.get(self, "most_recent"),
             name=self.name,
             with_selector=self.with_selector)
```

This change will obviously need to be made to all fields used in this context.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-12-09 11:36
Suspect this will be similar to the issue with deprecated resource fields.

**Comment by justinvp** [comment] 2024-12-20 00:28
Closing as a dupe of #16848

**Closed by justinvp** 2024-12-20 00:28 UTC
Labels: kind/bug, language/python, area/codegen, resolution/duplicate
