### ISSUE TITLE
Generate and publish NPM package with install-pulumi-plugin.js

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#13195] opened 2023-06-17 20:46 UTC
Recently published NPM packages by the ecosystem team have failed to install, on failing to execute a script `scripts/install-pulumi-plugin.js`. See:
- pulumi/pulumi-azure#1301
- pulumi/pulumi-package-publisher#10

**Comment by Frassle** [comment] 2023-06-17 22:49
Commented on https://github.com/pulumi/pulumi-package-publisher/issues/10#issuecomment-1595878850 so just linking that here for visibility.

**Comment by justinvp** [comment] 2023-07-18 06:26
I think the root cause of this is actually a Node.js sdkgen bug. We do emit the `scripts/install-pulumi-plugin.js` file as part of sdkgen, but when running `tsc` to build, the JavaScript file doesn't actually get copied into `bin/scripts` because it isn't a TypeScript file and isn't listed in `tsconfig.json`.

Originally, sdkgen did not emit this file at all. Our publishing script injected it into the package before publishing: https://github.com/pulumi/scripts/blob/b6ee1692954d2b39e7a22b0db80b8cc4b735c101/ci/publish-tfgen-package#L33-L42. This ends up running [add-plugin-installer-script.js](https://github.com/pulumi/scripts/blob/b6ee1692954d2b39e7a22b0db80b8cc4b735c101/ci/add-plugin-installer-script.js), which adds [this copy of `install-pulumi-plugin.js`](https://github.com/pulumi/scripts/blob/b6ee1692954d2b39e7a22b0db80b8cc4b735c101/ci/install-pulumi-plugin.js) into the package.

Eventually we changed sdkgen to emit this file in https://github.com/pulumi/pulumi/pull/8730, but since this file never got "built" and copied into the built directory along with all the other compiled javascript, it was never actually included in the published package. Instead the variant of `install-pulumi-plugin.js` from the https://github.com/pulumi/scripts repo was being published.

We should fix the Node.js sdkgen to emit a `scripts/install-pulumi-plugin.ts` TypeScript file (rather than a JavaScript file), and list it in `tsconfig.json` so that it is copied to the `bin/scripts/install-pulumi-plugin.js` as part of compiling the TypeScript to JavaScript. (Or, possibly use `"allowJs": true` in `tsconfig.json` and list the `.js` file there, so it is copied over to the built dir).

We may have to update any publish scripts and commands to avoid injecting a `scripts/install-pulumi-plugin.js` if one already exists.

**Comment by Frassle** [comment] 2023-07-18 13:25
Honestly wonder if we should just do https://github.com/pulumi/pulumi/issues/13075 and drop these files entirely. NodeJS is going to be the only language where this works via library files, not totally sure it's worth the special treatment.

**Comment by Frassle** [comment] 2023-09-01 21:04
Closing this as we've changed codegen to drop these files entirely now.

**Closed** 2023-09-01 21:04 UTC
Labels: kind/bug, language/javascript, area/codegen, resolution/fixed
