### ISSUE TITLE
AWS MSK cluster updates fail

### ISSUE THREAD

**Issue by fedenusy** [pulumi/pulumi#4888] opened 2020-06-24 23:03 UTC
Hi, I successfully imported an AWS MSK cluster into my Pulumi stack.

Now when I try to change any AWS MSK cluster attributes (eg tags or volume size), I get the following error:
```
Diagnostics:
  pulumi:pulumi:Stack (bos-production):
    error: update failed

    panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:production::bos::aws:msk/cluster:Cluster::kafka
    goroutine 99 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.4.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0xc001104000, 0x67997d6, 0x48, 0xc001173790, 0x1, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.4.0/go/common/util/contract/assert.go:33 +0x197
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Update(0xc0007621a0, 0x717cee0, 0xc00117a660, 0xc000522000, 0xc0007621a0, 0x5ab3c01, 0xc00136c300)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.4.1-0.20200611172440-d3f6b9ed94d9/pkg/tfbridge/provider.go:835 +0x81d
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler.func1(0x717cee0, 0xc00117a660, 0x64df980, 0xc000522000, 0x64d6100, 0xaaf8268, 0x717cee0, 0xc00117a660)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.4.0/proto/go/provider.pb.go:1920 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x717cee0, 0xc0011414d0, 0x64df980, 0xc000522000, 0xc00176a160, 0xc00176a180, 0x0, 0x0, 0x70c6680, 0xc000521290)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler(0x6590a40, 0xc0007621a0, 0x717cee0, 0xc0011414d0, 0xc0004c6960, 0xc000750180, 0x717cee0, 0xc0011414d0, 0xc001168a80, 0x9b8)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.4.0/proto/go/provider.pb.go:1922 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000762000, 0x719dee0, 0xc00075c600, 0xc00031e800, 0xc00082ef90, 0xaabc498, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1082 +0x50a
    google.golang.org/grpc.(*Server).handleStream(0xc000762000, 0x719dee0, 0xc00075c600, 0xc00031e800, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1405 +0xcc9
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00004e9d0, 0xc000762000, 0x719dee0, 0xc00075c600, 0xc00031e800)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xa1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1
```

(I am on the latest versions of the binaries & SDKs: pulumi 2.4.0, pulumi-aws 2.10.1)

Thank you in advance for your support.

**Comment by stack72** [comment] 2020-06-24 23:22
Hi

Please can you help us by giving us some code to help reproduce this issue

Thanks

Paul

**Comment by fedenusy** [comment] 2020-06-24 23:43
@stack72 here are repro steps:
* Create MSK cluster manually via AWS console
* Import MSK cluster into Pulumi stack
* Modify MSK cluster by adding tags, then run `pulumi up`, and you should see this bug

**Comment by fedenusy** [comment] 2020-06-25 17:32
I found even simpler repro steps:
* Create MSK cluster via Pulumi
* Change MSK cluster tags, and you should see this bug

**Comment by komalali** [comment] 2020-11-12 06:12
@fedenusy I wasn't able to get a repro of this panic using the steps you described with the latest pulumi-aws (3.12.1). It's possible that this issue has been resolved in the time since you first reported this. 

If it hasn't been and you are able to get a repro, please feel free to open up this ticket again with the details.

**Closed by komalali** 2020-11-12 06:12 UTC
