### ISSUE TITLE
[QUESTION] could not create stack: [404] Not Found: Organization XXX not found?

### ISSUE THREAD

**Issue by scheung38** [pulumi/pulumi#3541] opened 2019-11-20 18:32 UTC
Mac OS
```
$ pulumi new aws-typescript -s <USERNAME>/aws-typescript/dev --force

project name: (aws-typescript) 
project description: (A minimal AWS TypeScript Pulumi program) 
Created project 'aws-typescript'

error: could not create stack: [404] Not Found: Organization <USERNAME> not found
```

where USERNAME is my Pulumi login name
and <USERNAME>/aws-typescript/dev is already created in portal

**Comment by pgavlin** [comment] 2019-11-20 18:43
@justinvp do we accept an org name in `-s` as part of `pulumi new`?

**Comment by EvanBoyle** [comment] 2019-11-20 18:46
I tried this command and it worked for me. 

@scheung38 can you double check the value of your personal org?

![Screen Shot 2019-11-20 at 10 39 53 AM](https://user-images.githubusercontent.com/2553171/69267812-c4956300-0b82-11ea-81f9-a36b34c6d087.png)

If you navigate to app.pulumi.com, and select your personal org from the menu, it will take you to a page with a URL like `app.pulumi.com/<ORGNAME>`. Can you verify that the value you specified is the exact same as the `<ORGNAME>` that you see?

**Comment by scheung38** [comment] 2019-11-20 19:12
also:

pulumi new aws-typescript

error: authorization failed.

But this is after successful login to Pulumi? or is it referring to the fact that I have not configured AWS and login to AWS?

**Comment by lukehoban** [comment] 2019-12-09 03:13
Closing as dupe of #3568 as these look to be tracking the same issue - and #3568  is a little more explicit about the problem.

**Closed by lukehoban** 2019-12-09 03:13 UTC
