### ISSUE TITLE
Investigate why Python tests take so long

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4849] opened 2020-06-17 22:34 UTC
Recent PR in Travis:

```
PASS: TestConfigBasicPythonVenv (630.92s)
PASS: TestEmptyPythonVenv (1295.25s)
PASS: TestDynamicPythonVenv (1646.11s)
PASS: TestConfigBasicPython (100.23s)
PASS: TestEmptyPython (1296.61s)
PASS: TestDynamicPython (1751.41s)
```

GHA (Windows):

```
PASS: TestConfigBasicPythonVenv (95.05s)
PASS: TestEmptyPythonVenv (78.40s)
PASS: TestDynamicPythonVenv (288.19s)
PASS: TestConfigBasicPython (134.05s)
PASS: TestEmptyPython (74.19s)
PASS: TestDynamicPython (286.01s)
```

**Comment by komalali** [comment] 2020-06-24 22:13
So this isn't just a python issue. Our tests are taking much longer on travis builds than they do locally. For example:

| Test | Local (s) | Travis (s) |
|---|---|---|
| TestLargeResourceNode | 23 | 102 |
| TestLargeResourcePython | 34 | 277 |
| TestLargeResourceGo | 29 | 127 |
| TestLargeResourceDotNet | 38 | 190 |

**Comment by justinvp** [comment] 2020-06-24 23:43
I wonder if Travis being slow is a significant factor here. Of course, there still may be other things we need to do to cut down the time. @jaxxstorm, how far off are we from moving this repo to GHA for everything?

**Comment by komalali** [comment] 2020-06-24 23:46
I don't think this was included in the build updates. We specifically targeted providers only from what I understand. @leezen are pulumi/pulumi build updates planned?

**Comment by leezen** [comment] 2020-06-25 01:14
@komalali @justinvp Correct, the original build work was specifically targeting providers as a first step to getting GHA working in our repos, getting mileage on that, and then coming back at some point to revisit w/ `pulumi/pulumi`. There's currently no planned work on this in the near future, but we could discuss this in the next team planning meeting on reprioritizing that work.

**Comment by komalali** [comment] 2020-06-25 05:09
There's definitely a python-specific thing going on too though. This step is consistently taking forever in each python test: `pip install -e /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/python/env/src'`

There are a lot of instances of the `Still running command '/tmp/p-it-travis-job-pylint-f9f808b1-728867305/venv/bin/pip install -e /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/python/env/src'` message which is emitted every 2 minutes if a command isn't complete. It seems to show up about 3 times for each test, meaning that command is taking between 6 and 8 minutes to complete.

**Comment by justinvp** [comment] 2020-06-25 05:28
> This step is consistently taking forever in each python test: `pip install -e /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/python/env/src`

Perhaps due to the locking we're doing in `runVirtualEnvCommand` and `runPipenvCommand`?

https://github.com/pulumi/pulumi/blob/b77ec919d4957cae450003bd8d28cf634a9703fe/pkg/testing/integration/program.go#L902-L941

It's not clear to me we still need to do the locking. Or, if multiple processes writing to "PKG-INFO" is still a problem, I wonder that wouldn't happen if we forced "PKG-INFO" to be created before any of the Python tests run (not sure if this would work; or if it always gets written-to, regardless if it already exists).

**Comment by komalali** [comment] 2020-06-25 05:36
> Perhaps due to the locking we're doing in `runVirtualEnvCommand` and `runPipenvCommand`?

Ooh interesting, that might be it. I can confirm that the "Still running command..." messages started when the https://github.com/pulumi/pulumi/pull/4775 PR landed.

I'll try to unravel that thread tomorrow.

**Comment by komalali** [comment] 2020-06-25 22:43
> So, if I turn off everything except the python integration tests in Travis they take *much* less time. Like tests that have been taking 400-1200+ seconds take 40-100 seconds.

**Comment by komalali** [comment] 2020-06-25 22:49
I think the issues we are seeing may be an artifact of overloading the travis build, and since we are planning on putting an effort into moving from travis to GHA for the build in the near future I'm inclined to close this out until we can see the results of that effort.

**Comment by komalali** [comment] 2020-07-07 17:16
Closing this issue out as it appears the slowdown problems are actually related to go tests using large amounts of memory to build the program, and we have upcoming work to split this build by language.

**Closed by komalali** 2020-07-07 17:16 UTC
