### ISSUE TITLE
Resource provider seg fault on Debian

### ISSUE THREAD

**Issue by efleurine** [pulumi/pulumi#2064] opened 2018-10-16 20:09 UTC
## Error
I am trying the creating a project exemple with AWS and I cannot get through because of this error (see below). 

```
Previewing update of stack 'ahoy-pulumi-dev'
Previewing changes:

     Type                 Name                         Plan          Info
 +   pulumi:pulumi:Stack  ahoy-pulumi-ahoy-pulumi-dev  create
 *   └─ global            global                       no change     1 error

Diagnostics:
  global: global
    error: could not read plugin [/home/eph/.pulumi/plugins/resource-aws-v0.16.0/pulumi-resource-aws] stdout: EOF

error: an error occurred while advancing the preview
```

## Step to reproduce

In my case just doing the `Creating a project exemple` here https://pulumi.io/tour/basics-projects.html I tried multiple times for the same result.

## System info

I am using
NodeJS  `v8.11.4`
uname -a `Linux clover 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux`

thanks for any help

**Comment by lukehoban** [comment] 2018-10-16 20:30
Thanks for the report - we’re looking into this.

**Comment by ellismg** [comment] 2018-10-16 21:43
Hi @efleurine 

This error means that the resource provider (which actually manages the interaction with AWS to create resources) failed to launch of some reason.  Are you able to invoke `/home/eph/.pulumi/plugins/resource-aws-v0.16.0/pulumi-resource-aws` from the console directly?  If so, does it give you an error message like `error: fatal: could not connect to host RPC; missing argument` or does something else happen?

**Comment by efleurine** [comment] 2018-10-18 21:40
@ellismg I tried the invokation like you suggested with no success

1 - I tried this command `/home/eph/.pulumi/plugins/resource-aws-v0.16.0/pulumi-resource-aws` and it said `Segmentation fault`

2 - I not sure if this way the right way to invoke it and I also tried `node /home/eph/.pulumi/plugins/resource-aws-v0.16.0/pulumi-resource-aws` and it said
```
(function (exports, require, module, __filename, __dirname) { ELF
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.j
```

Thanks -

by the way which one way is correct?

**Comment by ellismg** [comment] 2018-10-18 22:01
> by the way which one way is correct?

The first way you tried is correct.  The providers are actually compiled go binaries, so they aren't invokable via node.

The segmentation fault is the problem. If the provider crashes at startup (as it is here) then we would fail in the way that you saw.

Can you tell me what distro and version you are using?  My hunch was some version of mint based on the clover token in uname and the debian packages, but I don't the exact version.  I'm going to try to get something set up locally so I can reproduce this.  Is there anything else you can think of that is interesting about your setup?

**Comment by efleurine** [comment] 2018-10-19 17:29
Ok here my info @ellismg . I am also using KDE Plasma for the desktop

```
uname -a
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
```

```
cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
 cat /proc/version
Linux version 4.9.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08)
```

thanks

**Comment by ellismg** [comment] 2018-12-01 13:01
Try as I might, I have been unable to reproduce the segmentation fault on any of my Debian setups. I have tried in docker, in VMs and on real hardware, to no avail.

I also know that other folks have been successful using Pulumi with Debian 9, so it's not clear to me there is a structural issue here.

My only thought at this point is that perhaps somehow the plugin was corrupted in some manner, leading to a segfault.  On my machine, this is the SHA256 sum of the plugin:

```
[ellism@ellism-local cmdutil]$ sha256sum ~/.pulumi/plugins/resource-aws-v0.16.0/pulumi-resource-aws 
ef26356253dd81dd4495ef9f7a8eecd27aa40b04be87279c7872228d9cb868e5  /home/ellism/.pulumi/plugins/resource-aws-v0.16.0/pulumi-resource-aws
```

This launches without error on Debian 9.

If you're still running into this, @efleurine, here's a few things to try:

1. Do you see the same hash for your plugin as I do?  If not, you can remove the `~/.pulumi/plugins/resource-aws-v0.16.0` folder and re-install the plugin by running `pulumi plugin install resource aws 0.16.0`
2. If you have the same hash, you might try just upgrading to the latest version of the plugin by running `pulumi plugin install resource aws 0.16.2`.  Between 0.16.0 and 0.16.2, we upgraded the version of golang we use when compiling the plugin.
3. If things continue not to work, perhaps try invoking the plugin directly under `strace`.  This may help us see a bit about what the plugin was doing before it crashed, and we might be able to use that to debug.

I'm going to close this for now, but if you are still able to reproduce this and can capture a trace with `strace`, please do share the log (either as a gist or by sending it directly to me, `matt <at> pulumi <dot> com`) and we'll see if we can make more progress together.

**Closed by ellismg** 2018-12-01 13:01 UTC
Labels: customer/feedback, priority/P1
