### ISSUE TITLE
Secrets inside config objects behave weird.

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/pulumi#6531] opened 2021-03-15 15:12 UTC
## Expected behavior
Pulumi allows to have secrets inside config objects i.e:
```yaml
config:
  proj:data:
    services:
      foo: bar
      priv:
        secure: AAABAB+T(...)sEmx8=
```

This is briefly touched in the documentation. These secrets should be easy to use and manage. But these secrets behave weird, and the documentation about them could be more extensive.

## Current behavior
To read these secrets, you can either:
```py
import pulumi

pulumi_config = pulumi.Config()
conf1 = pulumi_config.require_object("data")
# or
conf2 = pulumi_config.require_secret_object("data")
```

Using the first way, `conf1` is a dict, but the secret is not in plain text. is just a python str that says "[secure]" when printed. But if used, like for other configs, or to setup some infra, pulumi parses it correctly.

`{'services': {'foo': 'bar', 'priv': '[secret]'}}`

This dict, is useful, because I can iterate over it, and use all dict features. But when working with this dict, some times I require to know if some value should be a secret or not, but I have not found any way to do it, so I can't use different behaviors for the foo key than the priv key, if I have no programmatic way to differentiate which of them is a secret and which is not.

Using the second way, `conf2` is a pulumi Output, but I can't iterate over it, and if I explicitly get the values, for the foo or priv keys, I get also pulumi Outputs, and using `.is_secret()` says true for any of them.

## Steps to reproduce

You can config this secrects, like this:
```sh
$ pulumi config set --path 'data.services.foo' bar
$ pulumi config set --path --secret data.services.priv accesstokenvalue
```

And then try to use them in the code:

```py
import pulumi

pulumi_config = pulumi.Config()
conf1 = pulumi_config.require_object("data")
# or
conf2 = pulumi_config.require_secret_object("data")

print("conf1")
print(conf1)
print(type(conf1))

print("conf2")
print(conf2)
print(type(conf2))


print(conf1["services"])
print(type(conf1["services"]))

print(conf2["services"])
print(type(conf2["services"]))

for i in conf1["services"]:
    print(i)
    print(type(i))
    print(conf1["services"][i])
    print(type(conf1["services"][i]))


# This will make an infinite loop
#for i in conf2["services"]:
#    print(i)
#    print(type(i))


print(conf2["services"]["foo"])
print(type(conf2["services"]["foo"]))
if conf2["services"]["foo"].is_secret():
    print("foo is secret")

print(conf2["services"]["priv"])
print(type(conf2["services"]["priv"]))
if conf2["services"]["priv"].is_secret():
    print("priv is secret")
```

**Comment by justinvp** [comment] 2021-03-16 18:52
> Using the first way, `conf1` is a dict, but the secret is not in plain text. is just a python str that says "[secure]" when printed. But if used, like for other configs, or to setup some infra, pulumi parses it correctly.

The value actually is the plaintext value. What you're seeing is that when _printing_ we replace all known-secrets with `[secret]` in the outputted text.

If you run `print(conf1["services"]["priv"] == "accesstokenvalue")`, it'll print `True` indicating the value is indeed the plaintext value.

> This dict, is useful, because I can iterate over it, and use all dict features. But when working with this dict, some times I require to know if some value should be a secret or not, but I have not found any way to do it, so I can't use different behaviors for the foo key than the priv key, if I have no programmatic way to differentiate which of them is a secret and which is not.

Can you provide more details on why your program needs to know whether a particular value is secret or not? What will the program be doing differently in each case?

> Using the second way, `conf2` is a pulumi Output, but I can't iterate over it, and if I explicitly get the values, for the foo or priv keys, I get also pulumi Outputs, and using `.is_secret()` says true for any of them.

If you're planning to use these values as inputs to when creating resources, you can access the individual items with an `apply`, e.g. `conf2.apply(lambda d: <iterate over d and return whatever value you need>)`.

**Comment by mikhailshilkov** [comment] 2022-07-27 20:38
I feel like the question has been answered and this behavior is by design. I'll go ahead and close the issue, feel free to open a new one with API improvement suggestions.

**Closed by mikhailshilkov** 2022-07-27 20:38 UTC
Labels: kind/bug, language/python, area/secrets, resolution/by-design
