### ISSUE TITLE
Pulumi became so slow (~7x times) since version 2.16.2

### ISSUE THREAD

**Issue by shinebayar-g** [pulumi/pulumi#6197] opened 2021-01-25 22:11 UTC
## Expected Behavior
Smooth & Fast runtime experience.

## Current Behavior
Lately we've noticed `pulumi up` was taking longer than usual.

## Steps to Reproduce

1. `curl -fsSL https://get.pulumi.com | sh -s -- --version 2.16.2` (or any version above)
2. `pulumi up`

## Context (Environment)
I tracked down the issue and tried every single release. Here is the brief output of different versions and their runtime information.

### 2.15.6

```
$ time pulumi up --suppress-outputs
Previewing update (prod):
     Type                 Name       Plan
     pulumi:pulumi:Stack  prod

Resources:
    236 unchanged

Permalink: https://mybucket.s3.amazonaws.com/....
Do you want to perform this update? yes
Updating (prod):
     Type                 Name       Status
     pulumi:pulumi:Stack  prod

Resources:
    236 unchanged

Duration: 48s

Permalink: https://mybucket.s3.amazonaws.com/....
warning: A new version of Pulumi is available. To upgrade from version '2.15.6' to '2.18.2', run
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

real    1m4.206s
user    0m8.295s
sys     0m1.480s
```

### 2.16.1

```
$ time pulumi up --suppress-outputs
Previewing update (prod):
     Type                 Name       Plan
     pulumi:pulumi:Stack  prod

Resources:
    236 unchanged

Permalink: https://mybucket.s3.amazonaws.com/....
Do you want to perform this update? yes
Updating (prod):
     Type                 Name       Status
     pulumi:pulumi:Stack  prod

Resources:
    236 unchanged

Duration: 49s

Permalink: https://mybucket.s3.amazonaws.com/....
warning: A new version of Pulumi is available. To upgrade from version '2.16.1' to '2.18.2', run
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

real    1m8.144s
user    0m8.883s
sys     0m1.951s
```

### 2.16.2

```
$ time pulumi up --suppress-outputs
Previewing update (prod):
     Type                 Name       Plan
     pulumi:pulumi:Stack  prod

Resources:
    236 unchanged

Permalink: https://mybucket.s3.amazonaws.com/....
Do you want to perform this update? yes
Updating (prod):
     Type                 Name       Status
     pulumi:pulumi:Stack  prod

Resources:
    236 unchanged

Duration: 5m45s

Permalink: https://mybucket.s3.amazonaws.com/....
warning: A new version of Pulumi is available. To upgrade from version '2.16.2' to '2.18.2', run
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

real    6m4.890s
user    0m34.030s
sys     0m4.367s
```

### 2.18.2

```
$ time pulumi up --suppress-outputs
Previewing update (prod):
     Type                 Name       Plan
     pulumi:pulumi:Stack  prod

Resources:
    236 unchanged

Permalink: https://mybucket.s3.amazonaws.com/....
Do you want to perform this update? yes
Updating (prod):
     Type                 Name       Status
     pulumi:pulumi:Stack  prod

Resources:
    236 unchanged

Duration: 5m58s

Permalink: https://mybucket.s3.amazonaws.com/....

real    6m16.338s
user    0m28.163s
sys     0m2.973s
```

### Additional info

```
$ pulumi stack export | wc -c
2633995
```

- Backend: s3
- OS: Ubuntu 20.04.1 LTS (WSL2)
- Language: TypeScript
- Cloud Provider: AWS

v2.15.6 Profile files:

[2156.14400.cpu.zip](https://github.com/pulumi/pulumi/files/6012886/2156.14400.cpu.zip)
[2156.14400.mem.zip](https://github.com/pulumi/pulumi/files/6012888/2156.14400.mem.zip)

v2.16.2 Profile files:

[2162.11978.cpu.zip](https://github.com/pulumi/pulumi/files/6012892/2162.11978.cpu.zip)
[2162.11978.mem.zip](https://github.com/pulumi/pulumi/files/6012893/2162.11978.mem.zip)

v2.18.2 Profile files:

[2182.15426.cpu.zip](https://github.com/pulumi/pulumi/files/6012894/2182.15426.cpu.zip)
[2182.15426.mem.zip](https://github.com/pulumi/pulumi/files/6012895/2182.15426.mem.zip)

**Comment by mikhailshilkov** [comment] 2021-01-26 08:21
These are the two PRs that were in 2.16.2: 

- https://github.com/pulumi/pulumi/pull/6006/
- https://github.com/pulumi/pulumi/pull/5868/

The latter is for the Go SDK, so it doesn't seem related. @pgavlin anything about #6006 that could slow us down?

**Comment by pgavlin** [comment] 2021-01-26 23:25
> @pgavlin anything about #6006 that could slow us down?

I don't believe so, no. @shinebayar-g can you collect and share profiling data by adding the `--profiling` flag to your `pulumi` invocation?

**Comment by shinebayar-g** [comment] 2021-01-27 16:08
Does profiling files include any private information?

**Comment by pgavlin** [comment] 2021-01-27 21:51
> Does profiling files include any private information?

The memory and CPU profiles will not contain private information, no. You can email them to me directly if you'd like.

**Comment by shinebayar-g** [comment] 2021-01-27 21:52
Ok, I got prepared 3 different profiling information for version 2.15.6, 2.16.2, 2.18.2
Sending them to you right now.

**Comment by shinebayar-g** [comment] 2021-01-27 22:00
Do you need `.trace` files too? Those are big.

**Comment by pgavlin** [comment] 2021-01-27 22:49
> @pgavlin Do you need .trace files too? Those are big.

Not at the moment.

**Comment by JakeGinnivan** [comment] 2021-02-01 06:34
We have a similar regression after 2.15.6.

2.15.6 - ~13m
2.16.2 - ~35m

Let me know if you would like us to profile as well.

**Comment by joeduffy** [comment] 2021-02-04 02:48
For what it's worth, I tried reproducing this with the `pulumi new aws-typescript` template (no luck), as well as a program that creates an S3 bucket and 250 objects, since I see that @shinebayar-g's stack had 236 resources (also no luck). In both cases, 2.16.2 completed in the same amount of time as 2.16.1 did, both of which were reasonable.

The stack isn't quite as big, but it's not small either:

```
$ pulumi stack export | wc -c
  569305
```

Do we have an example program that exhibits this behavior, by any chance? It may be specific to the program somehow.

I also notice the backend appears to be S3, given the `Permalink: https://mybucket.s3.amazonaws.com/....`, but it wasn't clear whether and why that would impact this.

**Comment by JakeGinnivan** [comment] 2021-02-04 05:12
Our projects also use s3 as the backend. May be something to do with that?

Downgrading to 2.15.2 improved the performance of multiple projects.

**Comment by leezen** [comment] 2021-02-05 17:37
@JakeGinnivan Yes, profiling would be helpful. Do you mind posting the traces back to this issue?

**Comment by zyv** [comment] 2021-02-19 20:51
Hi folks, pulumi is awesome, but it's pretty much unusable for anything beyond toy projects - on a medium-sized project with ~200 resources I have to wait 10-15 minutes for each up, and it's getting worse every release :(

I have collected a profile and made a trace, but I fear that traces might contain private data - I can share per e-mail if required. I understood that CPU / memory profiles do not contain private data, so I'm uploading them to this ticket.

[moneymeets.13305.cpu.gz](https://github.com/pulumi/pulumi/files/6012863/moneymeets.13305.cpu.gz)
[moneymeets.13305.mem.gz](https://github.com/pulumi/pulumi/files/6012865/moneymeets.13305.mem.gz)

/cc @marns93

**Comment by shinebayar-g** [comment] 2021-02-19 20:59
I just edited the original post & included profiling files that I sent to the pgavlin

**Comment by zyv** [comment] 2021-02-19 21:32
For what it's worth, we are also using S3 backend and...

```
$ pulumi stack export | wc -c
839511
```

**Comment by lukehoban** [comment] 2021-02-19 23:39
@zyv (or others seeing this) Any chance you could share the results of both of the troubleshooting steps noted in https://www.pulumi.com/docs/troubleshooting/#diagnosing-issues?

These may contain sensitive data - so please review and scrub as needed before-hand and reach out on the Pulumi Community Slack (I'm `@Luke`) instead of sharing here on GitHub.

```
$ TF_LOG=TRACE pulumi up --logtostderr -v=9 2> out.txt
$ pulumi up --tracing=file:./up.trace
```

**Comment by zyv** [comment] 2021-02-20 12:20
Hey @lukehoban, thanks for reaching out! I've tried to write a simple scrubber for trace files (public domain / CC0), that preserves the parsability (seems to be the case) - could someone please have a look and comment on whether this is a meaningful approach and the results are still useful? I think something like this would free up many people to posting their traces to help the cause.

[trace_scrubber.py.gz](https://github.com/pulumi/pulumi/files/6014913/trace_scrubber.py.gz)

**Comment by lukehoban** [comment] 2021-02-21 04:46
>  I've tried to write a simple scrubber for trace files (public domain / CC0), that preserves the parsability 

Great - thanks!

>  I think something like this would free up many people to posting their traces to help the cause.

Definitely - this is also tracked in https://github.com/pulumi/pulumi/issues/2715.

**Comment by lukehoban** [comment] 2021-02-21 05:03
The data @zyv shared confirmed the cause of this - his deployment had 253 resources that did not change (were `same`). 42 of those were recognized as not needing to write a state file (almost no `same` steps should require writing the state file - as nothing changed).  But 211 of them decided they did need to write the state file - to the filestate backend in his case (I believe S3). Each of those writes took ~2s, and those writes must be serialized, which added up to ~7min of wall-clock time.  The entire update took ~8min, so it appears the vast majority of the time was spent doing these state file writes that should most likely not have been necessary.

We had a similar issue to this in https://github.com/pulumi/pulumi/pull/3860, which was fixed a year ago.  

Given that this was introduced in 2.16.2, my hypothesis is that it was somehow indirectly related to https://github.com/pulumi/pulumi/pull/6006.  But I am not yet clear how exactly that leads to this, and have not yet been able to reproduce this myself in isolation.  Will continue to investigate.

**Comment by lukehoban** [comment] 2021-02-21 23:38
I still can't repro myself - but nearly certain this is due to https://github.com/pulumi/pulumi/pull/6006/files#diff-1fd47e1ff18121659c96a8f47296a2c0c715eb2662c64c7297fa0c5c1ad25c19R290.  That change can trigger the exact same problem that was fixed in https://github.com/pulumi/pulumi/pull/3860 (and see  specifically https://github.com/pulumi/pulumi/pull/3860#discussion_r374997416).  In this case, it looks like it must be impacting the `Inputs` and/or `Outputs`.

**Comment by zyv** [comment] 2021-02-22 03:01
@lukehoban I think you are not able to reproduce it yourself, because your Internet connection is way too fast and you are probably not using S3 backend ;-) I have just tried it on a 250/50 Mbit FFTB leased line from our second office, and the problem almost disappeared o_O

**Comment by lukehoban** [comment] 2021-02-22 03:14
> @lukehoban I think you are not able to reproduce it yourself, because your Internet connection is way too fast and you are probably not using S3 backend ;-)

I do think that is part of why we haven't seen more reports of this - even though the issue would affect most users to some degree. 

But when I said I couldn't repro it, I meant I couldn't even trigger a case where mustWrite returned true. That said - I am fairly confident that the fix in the linked PR will address this.

**Closed** 2021-02-22 22:04 UTC
Labels: area/cli, impact/performance, p1, team/platform

**Comment by zyv** [comment] 2021-02-23 17:54
Hi @lukehoban - awesome, I've just tested again with the same project I shared the logs of, and..

```
(pulumi-infrastructure-rbWWuQW3-py3.9) zaytsev@parallels:~/src/XXX-pulumi/projects/github-management$ pulumi up
Previewing update (XXX):
     Type                 Name                          Plan     
     pulumi:pulumi:Stack  github-management-XXX           
 
Resources:
    256 unchanged

Do you want to perform this update? yes
Updating (XXX):
   Type  Name  Status     
 
Resources:
    256 unchanged

Duration: 1m43s
```

1m43s vs 15mXXs makes a huge difference for us! Thank you very much for taking care of it so quickly 👍
