### ISSUE TITLE
Support configuring `--server` flag to plugin installation in all languages

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#5991] opened 2020-12-21 20:03 UTC
Currently we have support for metadata in NodeJS `package.json` to tell plugin installation to use a customer server URL (via passing `--server` to `pulumi plugin install`).  We do not have equivalent support in other languages yet - and will need to do so to support custom plugin hosting for 3rd party components.

Related to https://github.com/pulumi/pulumi-tf-provider-boilerplate/issues/13 and https://github.com/pulumi/pulumi/issues/5937.

There are several aspects of this tracked as individual issues:

- [x] [#7243] Python
  - Need to handle non `pulumi-` prefixed packages when searching for packages that need plugins
- [x] [#7244] .NET
  - Need to adopt `pulumiplugin.json` to support custom server URLs
  - Allow non-`Pulumi.` packages when searching for packages that need plugins
- [x] [#7245] Go
  - Need to adopt `pulumiplugin.json` to be able to specify custom server URL for Go
  - Need to handle non-Pulumi prefixed modules
- [ ] [#7242] When determining required plugins for an existing stack by looking for providers in the state, we need a way to determine if any of those providers came from a custom server URL so we can properly install the required plugins.

**Comment by justinvp** [comment] 2021-02-25 13:44
There are several aspects of this:

- When determining required plugins for an existing stack by looking for providers in the state, we need a way to determine if any of those providers came from a custom server URL so we can properly install the required plugins.
- .NET
  - Need to adopt `pulumiplugin.json` to support custom server URLs
  - Allow non-`Pulumi.` packages when searching for packages that need plugins
- Go
  - Need to adopt `pulumiplugin.json` to be able to specify custom server URL for Go
  - Need to handle non-Pulumi prefixed modules
- Python
  - Need to handle non `pulumi-` prefixed packages
- Node.js
  - Confirm there is nothing else needed here

**Comment by infin8x** [comment] 2021-12-09 18:32
@justinvp @iwahbe another one we might be able to close as duplicate?

**Comment by iwahbe** [comment] 2021-12-09 18:46
>@justinvp @iwahbe another one we might be able to close as duplicate?

@infin8x I'm not sure what you mean?

**Comment by infin8x** [comment] 2021-12-09 18:48
ah sorry, was moving quickly. I think this is a duplicate of pulumi/home#1655, and figured it might be good to close this one as duplicate of that one to reduce issue debt. but, happy to leave this open if it represents something different.

**Comment by iwahbe** [comment] 2021-12-09 18:51
>  I think this is a duplicate of pulumi/home#1655, and figured it might be good to close this one as duplicate of that one to reduce issue debt.

@infin8x I think you are right. I just wasn't sure what you were saying.

**Comment by infin8x** [comment] 2021-12-09 18:55
Duplicate of pulumi/home#1655

Sounds good! Sorry for the poor communication on my part. Will go ahead and close.

**Closed by infin8x** 2021-12-09 18:55 UTC
Labels: kind/enhancement, area/multi-language-components, resolution/duplicate, size/M

**Comment by emiliza** [comment] 2021-12-09 23:15
I'll keep this closed, but I've gone ahead and copied the engineering work list for the community's awareness of where this currently is at
