### ISSUE TITLE
Unable to retrieve a provider schema

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#12457] opened 2023-03-19 01:36 UTC
### What happened?

([context](https://pulumi.slack.com/archives/C02FXTZEZ6W/p1679187944786049))

I'm currently trying to download a provider schema (pulumi-aws) but the CLI keeps returning an error.

`pulumi package get-schema 'aws@5.24.0'`, `pulumi package get-schema aws-native`, `pulumi package get-schema azure` and `pulumi package get-schema azure-native`
```
error: json: error calling MarshalJSON for type schema.FunctionSpec: cannot specify both Outputs and ReturnType when marshalling FunctionSpec because they are mutually exclusive
```

This [used to work](https://app.slack.com/client/T4PBPMA8J/C02VCJEBT2N/thread/C02VCJEBT2N-1672194078.274339) late last year.

Though, running `pulumi package get-schema 'kubernetes@3.24.2'` works fine.

### Expected Behavior

The CLI outputs a provider's schema

### Steps to reproduce

1. Install the latest CLI (v3.58.0)
2. run `pulumi package get-schema 'aws@5.24.0'`

### Output of `pulumi about`

```
CLI          
Version      3.58.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.24.0
aws-native  unknown
yaml        unknown

Host     
OS       debian
Version  11.6
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment] 2023-03-20 19:33
Nice catch @aureq! I'm able to reproduce this error; and it looks fairly straightforward. It appears that somewhere along the line we changed the format of the schema, breaking this command. I'm surprised this wasn't caught during integration testing.

**Comment by RobbieMcKinstry** [comment] 2023-03-20 20:36
I opened a quick PR to fix this, though I'm not sure (a) if it's the best fix for this bug (b) how to add an integration test to prevent this class of bug from happening again. In theory, running `pulumi package get-schema` with any major provider would have caught this regression.

**Comment by RobbieMcKinstry** [comment] 2023-03-22 17:08
My PR is insufficient to fix the issue but it's on the right track! I'll have to dig a little deeper to understand how to make `get-schema` compatible with the the function `Ouputs` deprecation.

**Closed** 2023-04-05 14:51 UTC
Labels: kind/bug, area/cli, area/tooling, size/S, impact/regression

**Comment by RobbieMcKinstry** [comment] 2023-04-05 18:43
This turned out to be a very easy one after all! It lagged for a few weeks due to some CI failures but they weren't all that important, it turns out.
