### ISSUE TITLE
Target Group state deletion panics

### ISSUE THREAD

**Issue by Luciam91** [pulumi/pulumi#10562] opened 2022-09-01 10:25 UTC
### What happened?

After a manual change was made in the AWS account, I'm trying to update the Pulumi state by deleting the resources which were manually altered.

### Steps to reproduce

1. Create a Target Group using Pulumi
2. Delete target group within AWS
3. Run `pulumi state delete <tg urn>`

### Expected Behavior

Target group is removed from state

### Actual Behavior

Pulumi panics with the below:

```
Pulumi Version:   v3.38.0
Go Version:       go1.19
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: slice bounds out of range [:-2]

goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.19.0/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x34
panic({0x1065d5880, 0x14000476a98})
	/Users/runner/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x204
gopkg.in/AlecAivazis/survey%2ev1.paginate(0x140003ee737?, {0x14000402400?, 0x140008f5408?, 0x104dc3fe0?}, 0x140008f53d8?)
	/Users/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:254 +0xe0
gopkg.in/AlecAivazis/survey%2ev1.(*Select).Prompt(0x14000bbd860)
	/Users/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/select.go:199 +0xf8
gopkg.in/AlecAivazis/survey%2ev1.Ask({0x140008f56c0, 0x1, 0x5?}, {0x1062d7520?, 0x14000bea2a0}, {0x0, 0x0, 0x14000bbd860?})
	/Users/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:148 +0x1b0
gopkg.in/AlecAivazis/survey%2ev1.AskOne({0x1066fb5f0?, 0x14000bbd860?}, {0x1062d7520?, 0x14000bea2a0?}, 0x1?, {0x0?, 0x0?, 0x0?})
	/Users/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:94 +0x6c
main.locateStackResource({{0x105d76e75, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:113 +0x614
main.runStateEdit.func1({{0x105d76e75, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:129 +0x50
main.runTotalStateEdit({0x1066fce68, 0x140001a2000}, {0x0, 0x0}, 0x1, 0x140008f5b98)
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:175 +0x378
main.runStateEdit({0x1066fce68?, 0x140001a2000?}, {0x0?, 0x140009f3950?}, 0xa8?, {0x16b3cb3e4?, 0x1063d01e0?}, 0x14000b6d050?)
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:128 +0x54
main.newStateDeleteCommand.func1(0xe?, {0x140003a9840, 0x1, 0x104c1e674?})
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_delete.go:59 +0xc0
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000b8a280?, {0x140003a9840, 0x1, 0x2})
	/Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000b8a280, {0x140003a9820, 0x2, 0x2})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x14000af8c80)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x3c
```

### Output of `pulumi about`

CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.11.0
aws     1.31.0
docker  3.4.1
go      unknown

Host     
OS       darwin
Version  12.2.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.19 darwin/arm64'

TYPE                            URN
pulumi:pulumi:Stack             urn:pulumi:prod::starship-infra::pulumi:pulumi:Stack::starship-infra-prod
pulumi:providers:aws            urn:pulumi:prod::starship-infra::pulumi:providers:aws::default
aws:lb/targetGroup:TargetGroup  urn:pulumi:prod::starship-infra::aws:lb/targetGroup:TargetGroup::web-tg
aws:lb/targetGroup:TargetGroup  urn:pulumi:prod::starship-infra::aws:lb/targetGroup:TargetGroup::web-tg

Dependencies:
NAME                                           VERSION
github.com/aws/aws-sdk-go-v2/service/dynamodb  1.15.13
github.com/pulumi/pulumi-aws/sdk               1.31.0
github.com/pulumi/pulumi-aws/sdk/v5            5.11.0
github.com/pulumi/pulumi-docker/sdk/v3         3.4.1
github.com/pulumi/pulumi/sdk/v3                3.38.0
github.com/stretchr/testify                    1.7.0

Pulumi locates its logs in /var/folders/jg/j0vp_nsj7ks6202vrcy3v2200000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2022-09-01 10:48
Duplicate of https://github.com/pulumi/pulumi/issues/10450. The fix for this will be in the next release (3.39 being released right now). In the meantime, use a cli version prior to 3.38.0 to run this command.

**Closed by Frassle** 2022-09-01 10:48 UTC
Labels: kind/bug, resolution/duplicate
