### ISSUE TITLE
Allow to recover stack state with `pulumi stack history` similar to `pulumi stack export`

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#12179] opened 2023-02-14 22:58 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I think I just lost my stack state after performing `pulumi refresh` in CI under the wrong credential, which dropped resources from the stack... And while finding `pulumi stack history` it seems that it is unable to recover the past known stack state in the same format as `pulumi stack export`, which would have been very handy in this scenario.

**Comment by susanev** [comment] 2023-02-14 23:02
i think this is a duplicate of https://github.com/pulumi/pulumi-github/issues/255

**Comment by t0yv0** [comment] 2023-02-14 23:04
https://github.com/pulumi/pulumi-github/issues/255 is indeed my scenario but I don't think it's a duplicate! Thanks for the find btw! It would be lovely to have Pulumi backup states and allow recovery in many sticky situations not just the GitHub one.

**Comment by susanev** [comment] 2023-02-14 23:04
oh right sry was not thinking clearly, not a duplicate!

**Comment by Frassle** [comment] 2023-02-15 09:16
`stack export` has a `--version` argument, if your using SASS history that should work.

**Comment by Frassle** [comment] 2023-02-16 14:45
Internal comms suggests `--version` covers this. Closing.

**Closed by Frassle** 2023-02-16 14:45 UTC
Labels: kind/enhancement, resolution/fixed
