### ISSUE TITLE
consider stating the name of the stack you are operating on at the bottom of the preview

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#12247] opened 2023-02-18 19:24 UTC
i really really want the bottom of the preview to tell me the stack im operating on (like right above the yes/no question). maybe its cause im just always full of anxiety. but at least with stacks with a lot of output, and you have to scroll way back up to confirm ur operating on what you think ur operating on.

**Comment by dixler** [comment] 2023-02-19 07:08
https://github.com/pulumi/pulumi/issues/10579

May be related

**Comment by dixler** [comment] 2023-02-28 17:20
duplicate of https://github.com/pulumi/pulumi/issues/10780

**Closed by dixler** 2023-02-28 17:20 UTC
Labels: area/cli, kind/enhancement, impact/usability, resolution/duplicate
