### ISSUE TITLE
Tests hang on Go 1.13

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3196] opened 2019-09-06 22:13 UTC
When building and running tests with Go 1.13, the following test step hangs (130% CPU for last 35 minutes):

```
GO_TEST_FAST = PATH="$(PULUMI_BIN):$(PATH)" go test -short -count=1 -cover -timeout 1h -parallel ${TESTPARALLELISM}
```

**Comment by lukehoban** [comment] 2019-09-17 19:08
@stack72 Is this fixed as part of your work on Go 1.13?

**Comment by stack72** [comment] 2019-09-17 20:15
@lukehoban yessir - no test hangs now it seems. Got an issue to deal with on a stale go.mod entry but that will take care of it

**Comment by stack72** [comment] 2019-09-27 14:22
I am going to push this to 0.28 - we are still not in a situation where we can have builds of go1.12.9 and go1.13 in the same repo

We need to make a decision on this - so if we are going to support go1.13 then we need to go for it

**Comment by pgavlin** [comment] 2019-11-06 17:50
Seems like this is taken care of. Going to close as a dupe of https://github.com/pulumi/home/issues/582.

**Closed by pgavlin** 2019-11-06 17:50 UTC
Labels: kind/engineering
