### ISSUE TITLE
Add `pulumi bug` command

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#4045] opened 2020-03-09 20:57 UTC
The command would do the following:

1. Collect environment information `pulumi -v`, `pulumi plugin ls`, etc.
2. Populate this info in an issue template via https://github.com/pulumi/pulumi/issues/new

Would be very helpful in getting complete, reproducible bug reports.

**Comment by clstokes** [comment] 2020-03-09 20:58
Related: https://github.com/pulumi/pulumi/issues/2715

**Comment by stack72** [comment] 2020-04-18 13:03
Hi @EvanBoyle 

should this be closed as a dupe of #2715 which has more information of support details needed?

Paul

**Closed** 2020-05-11 04:53 UTC
