### ISSUE TITLE
Failed to run pulumi refresh

### ISSUE THREAD

**Issue by tuanlc** [pulumi/pulumi#12089] opened 2023-02-07 02:11 UTC
### What happened?

I got an error when running `pulumi refresh`

### Expected Behavior

Should be able to run the command line

### Steps to reproduce

- Run `pulumi refresh`

### Output of `pulumi about`

```
Pulumi Version:   3.46.1
Go Version:       go1.19.3
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            send on closed channel

goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
main.panicHandler()
        github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/main.go:29 +0x3d
panic({0x55df86c5ad00, 0x55df86f9d250})
        runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0x0?, 0xc001b0d230)
        github.com/pulumi/pulumi/sdk/v3@v3.46.0/go/common/resource/plugin/host.go:253 +0xbd
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).Provider(0xc000c22000, {0xc0015c636b, 0x3}, 0xc00044a3c0)
        github.com/pulumi/pulumi/sdk/v3@v3.46.0/go/common/resource/plugin/host.go:329 +0xb6
github.com/pulumi/pulumi/pkg/v3/resource/deploy/providers.loadProvider({0xc0015c636b?, 0x3?}, 0xc001044270?, {0x55df86fcc438?, 0xc000c22000?}, {0x55df86fce8a0?, 0xc001b0d0e0?})
        github.com/pulumi/pulumi/pkg/v3/resource/deploy/providers/registry.go:107 +0xb7
github.com/pulumi/pulumi/pkg/v3/resource/deploy/providers.NewRegistry({0x55df86fcc438?, 0xc000c22000}, {0xc000488400, 0x65, 0xc001049040?}, 0x1, {0x55df86fce8a0?, 0xc001b0d0e0?})
        github.com/pulumi/pulumi/pkg/v3/resource/deploy/providers/registry.go:149 +0x3f2
github.com/pulumi/pulumi/pkg/v3/resource/deploy.NewDeployment(0xc000e41360, 0xc00097e440, 0xc001b6c6c0, 0x0, {0x55df86fbd7b8?, 0xc001bf8680}, {0x55df87fccfa8, 0x0, 0x0}, 0x1, ...)
        github.com/pulumi/pulumi/pkg/v3/resource/deploy/deployment.go:459 +0x347
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        github.com/pulumi/pulumi/pkg/v3/engine/deployment.go:189 +0x407
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        github.com/pulumi/pulumi/pkg/v3/engine/update.go:454 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Refresh({0x55df86fb9978, _}, _, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
        github.com/pulumi/pulumi/pkg/v3/engine/refresh.go:56 +0x670
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc0001d41e0, {0xc00037ff40, 0x2e}, ...}, ...)
        github.com/pulumi/pulumi/pkg/v3/backend/httpstate/backend.go:1173 +0x9af
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc0001d41e0, {0xc00037ff40, 0x2e}, ...}, ...)
        github.com/pulumi/pulumi/pkg/v3/backend/httpstate/backend.go:1076 +0x418
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0xc0001d41e0, {0xc00037ff40, 0x2e}, {0x0, ...}, ...}, ...)
        github.com/pulumi/pulumi/pkg/v3/backend/apply.go:115 +0x17a
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc0001d41e0, {0xc00037ff40, 0x2e}, {0x0, ...}, ...}, ...)
        github.com/pulumi/pulumi/pkg/v3/backend/apply.go:217 +0x125
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Refresh(_, {_, _}, {_, _}, {0xc0001d41e0, {0xc00037ff40, 0x2e}, {0x0, 0x0, ...}, ...})
        github.com/pulumi/pulumi/pkg/v3/backend/httpstate/backend.go:970 +0xb8
github.com/pulumi/pulumi/pkg/v3/backend.RefreshStack({_, _}, {_, _}, {0xc0001d41e0, {0xc00037ff40, 0x2e}, {0x0, 0x0, 0x0}, ...})
        github.com/pulumi/pulumi/pkg/v3/backend/stack.go:103 +0xbb
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Refresh(_, {_, _}, {0xc0001d41e0, {0xc00037ff40, 0x2e}, {0x0, 0x0, 0x0}, 0xc00104ee70, ...})
        github.com/pulumi/pulumi/pkg/v3/backend/httpstate/stack.go:162 +0x68
main.newRefreshCmd.func1(0x0?, {0x55df87fccfa8, 0x0, 0x0?})
        github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/refresh.go:263 +0x1730
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000d5db80?, {0x55df87fccfa8, 0x0, 0x0})
        github.com/pulumi/pulumi/sdk/v3@v3.46.0/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000d5db80, {0x55df87fccfa8, 0x0, 0x0})
        github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c46c80)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        github.com/pulumi/pulumi/pkg/v3/cmd/pulumi/main.go:48 +0x45
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2023-02-07 09:23
I suspect this might be a similar case to https://github.com/pulumi/pulumi/issues/10310 where that panic is because the engine was canceled.

Can you confirm that you didn't try to Ctrl-C the process, and that the above panic is reproducible just running `refresh`?

**Comment by tuanlc** [comment] 2023-02-08 07:00
I'm not sure 100% but yeah, I did `Ctrl-C`. Now it works for me.

I created the ticket because there was an message from Pulumi suggested that.

**Comment by abhinav** [comment] 2023-02-09 20:12
Thanks for the ticket @tuanlc.
Yeah, if you cancel the operation with Ctrl-C while it's running, the CLI may misbehave and panic if it's in the middle of something critical.
Glad to hear that `pulumi refresh` is working, though.
I'll close this as resolved, but if you run into any more issues, please feel free to open another ticket.

**Closed by abhinav** 2023-02-09 20:12 UTC
Labels: kind/bug, resolution/by-design
