### ISSUE TITLE
pulumi stack ls does not list stacks with a passphrase

### ISSUE THREAD

**Issue by robwruck** [pulumi/pulumi#7004] opened 2021-05-10 08:57 UTC
Initially, `pulumi stack ls` lists all stacks for the current project.
However, when a stack uses a `secrets_providers` and a secret is not set via `PULUMI_CONFIG_PASSPHRASE` or `PULUMI_CONFIG_PASSPHRASE_FILE`, that stack is not listed anymore (not even by `pulumi stack ls -a`).
Confirmed for `file:` and `s3:`

## Expected behavior
`pulumi stack ls` should list all stacks
`pulumi stack export -s dev` should prompt for the passphrase if not configured.

## Current behavior
`pulumi stack ls` does not list stacks with a passphrase.
In addition, `pulumi stack export` in this case won't prompt for a passphrase but simply show the `error: constructing secrets manager of type "passphrase"` instead.

## Steps to reproduce
Using local backend with a random passphrase when prompted:
```
pulumi login --local
pulumi stack init test
pulumi stack ls
```
-> Stack `test` is listed.

```
pulumi up -s test
pulumi stack ls
```
-> The first command prompts for the passphrase.
-> The second command doesn't list stack `test` anymore.

```
PULUMI_CONFIG_PASSPHRASE=123 pulumi stack ls
```
-> This lists all stacks again, *no matter what value you set*.

## Context (Environment)
Using docker image: pulumi/pulumi-nodejs:3.2.1

**Comment by lukehoban** [comment] 2021-05-10 09:07
I believe this is due to https://github.com/pulumi/pulumi/issues/4798?

**Comment by robwruck** [comment] 2021-05-10 10:41
Uh, indeed.

**Comment by lukehoban** [comment] 2021-08-17 19:22
Closing out as a a dupe of #4798 which was fixed recently.

**Closed by lukehoban** 2021-08-17 19:22 UTC
Labels: resolution/duplicate
