### ISSUE TITLE
Allow `pulumi new` to be used from scripts

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2614] opened 2019-04-02 00:43 UTC
`eksctl` allows you to do something like the following:

```
	eksctl create cluster \
		--name $(CLUSTER_NAME) \
		--asg-access \
		--full-ecr-access \
		--nodes 1 \
		--nodes-min 1 \
		--nodes-max $(MAX_NODES) \
		--node-type $(EC2_VM) \
		--node-volume-size $(DISK_SIZE) \
		--max-pods-per-node 250 \
		--region $(EC2_REGION) \
		--set-kubeconfig-context
```

This "flaggy" style is _very_ useful for scripts. The equivalent `pulumi new` (AFAICT) has no ability to do this, or to be used from inside a script generally, unless you want only default values.

I think we should very seriously consider doing this in M22 or M23. cc @justinvp @joeduffy @lukehoban

**Comment by justinvp** [comment] 2019-04-02 01:53
@hausdorff, can you provide an example of what you want the `pulumi new` command to look like? It already supports specifying the template, project name, description, stack, and config as flags without the interactive prompting. `pulumi new --help`.

**Comment by hausdorff** [comment] 2019-04-02 02:01
For [this] repository, how about something like:

```sh
pulumi new https://github.com/pulumi/apps/eks
    --instanceType="t2.medium" \
    --desiredCapacity=2 \
    --minSize=1 \
    --maxSize=2 \
    --storageClass=gp2 \
    --deployDashboard=true \
```


[this]: https://github.com/pulumi/apps/tree/master/eks

**Comment by joeduffy** [comment] 2019-04-02 20:49
I thought this was already possible. But I just tried it, and couldn't get `pulumi new` to function at all, in a non-interactive mode. @justinvp Am I just passing the wrong flags?

This is what I thought would work:

```
pulumi new https://github.com/pulumi/apps/eks \
    -p my-eks -s prod \
    -c "instanceType=t2.medium"
```

I'm unsure of the `-c` syntax. But no matter, because even if I leave it off, I get

```
error: no Pulumi project found in the current working directory
```

Is something broken here?

**Comment by justinvp** [comment] 2019-04-14 01:19
This command _should_ work:

```bash
pulumi new https://github.com/pulumi/apps/eks \
    -n my-eks \
    -d "My EKS app" \
    -s prod \
    -c "aws:region=us-west-2" \
    -c "instanceType=t2.medium" \
    -c "desiredCapacity=2" \
    -c "minSize=1" \
    -c "maxSize=2" \
    -c "storageClass=gp2" \
    -c "deployDashboard=true"
```

But it looks like this was broken when we changed stack identities to include the project name, and we didn't have a test in place to catch the regression.

When we parse the specified stack name, it attempts to lookup the project name (if the project name wasn't part of the stack name), but fails because we're doing this before we've laid down the template files so the Pulumi.yaml file doesn't exist.

https://github.com/pulumi/pulumi/blob/bdc687e6544b7e5a46814a15454dd8f7be492f43/pkg/backend/httpstate/backend.go#L416-L423

**Comment by justinvp** [comment] 2019-04-15 22:55
If you fully specify the owner and project as part of the stack name, the following works today:

```bash
pulumi new https://github.com/pulumi/apps/eks \
    -n my-eks \
    -d "My EKS app" \
    -s justinvp/my-eks/prod \
    -c "aws:region=us-west-2" \
    -c "instanceType=t2.medium" \
    -c "desiredCapacity=2" \
    -c "minSize=1" \
    -c "maxSize=2" \
    -c "storageClass=gp2" \
    -c "deployDashboard=true"
```

**Comment by joeduffy** [comment] 2019-05-11 16:37
@justinvp @ellismg I am trying to use `pulumi config` with a stack provisioned using our templates (`pulumi up https://...`). So, I don't actually even have a `Pulumi.yaml` file. I assumed I'd be able to run `pulumi config -s joeduffy/project/stack`, but no matter what I get `error: no Pulumi project found in the current working directory`. Is this all related to the same root cause, or am I doing something wrong?

**Comment by justinvp** [comment] 2019-05-13 17:42
> Is this all related to the same root cause, or am I doing something wrong?

Pretty sure it's unrelated. `pulumi config` isn't going to work with stacks provisioned with `pulumi up <template>`, because `pulumi config` is designed to store config for stacks alongside your source code. It just updates the local config value in the `Pulumi.<stack>.yaml` file, and then you have to do a `pulumi up` to deploy with any config changes. When using `pulumi up <template>` there's no local source directory, so there's no place for `pulumi config` to store config locally for the stack.

Today, if you want to update the config for a stack provisioned with `pulumi up <template>`, you'll have to do another update (e.g. `pulumi up <template> -s <stack>`), and it will fetch the existing stack's config and prompt you for the values (with the existing values as defaults). If you want, you can specify the config values on the command line (e.g. `pulumi up <template> -s <stack> -c "key1:value1" -c "key2:value2"`), and it'll use any specified values without prompting.

Some limitations:
 - You can't currently delete config values
 - It'd be nice if you didn't have to specify a template for existing stacks provisioned from a template (if not specified, it should just use the template that was originally used)

**Comment by justinvp** [comment] 2019-08-09 14:19
I'm going to close this. The scriptable scenario is already possible today (see https://github.com/pulumi/pulumi/issues/2614#issuecomment-483448617), it's just the experience is not as nice as it should be because it requires specifying the project name twice: once in the `-n` arg and also as part of the full stack identity with the `-s` arg (owner/project/stack). Improving this is tracked in #2880.

**Closed by justinvp** 2019-08-09 14:20 UTC
Labels: area/cli, kind/bug
