### ISSUE TITLE
dependsOn misses resources in create such as ec2.Route on v.3.34.0

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi#9927] opened 2022-06-22 14:39 UTC
### What happened?

Weird behavior with our AWS provisioning with 
pulumi/pulumi v3.34.0.

The first image is v3.33.2. Preview shows 54 to create, all are created, in the correct order, as expected and in line with many many previous runs of this project.
![1_Updated_pulumi_v3_33_2_preview_shows_54_resources_and_54_are_created](https://user-images.githubusercontent.com/5281839/175055722-d3e32d70-904d-49be-a4dd-077b812a4433.png)

The second image is after bumping both the provider and  project to `v3.34.0`. Preview shows `54` to create but only `46` are created. The `8` missed resources are `ec2.Route` resources that come last in the `dependsOn` chain. They depend on a set of Nat Gateways, but when the Nat Gateways have been created Pulumi finishes as “**successful**” without creating the last `8 route resources`.
![2_pulumi_v3_34_0_preview_shows_54_resources_only_46_are_created-2](https://user-images.githubusercontent.com/5281839/175056198-aafa78d4-88aa-4b8d-a8af-a9da675ea3a0.png)

Running update(pulumi up) again (image 3) identifies the resources are missing from the previous run and shows them to be created, and are created successfully.
![3_pulumi_v3_34_0_preview_shows_8_missing_resources_and_8_are_created](https://user-images.githubusercontent.com/5281839/175056340-549078c2-3540-434f-83b9-81922791527c.png)

### Steps to reproduce

This is in typescript and pending code

### Expected Behavior

Preview shows 54 to create, all are created, in the correct order, as expected and in line with many many previous runs of this project.

### Actual Behavior

Preview shows `54` to create but only `46` are created. The `8` missed resources are `ec2.Route` resources that come last in the `dependsOn` chain.

### Versions used

pulumi/pulumi v3.34.0 - missing resources
pulumi/pulumi v3.34.1- same behavior of missing resources
pulumi/pulumi v3.33.2 - all resources get created correctly.

### Additional context

Destroying and reverting back to v3.33.2 solves the issue, with all resources created successfully again in a single update. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2022-06-22 15:09
> Versions used
pulumi/pulumi v3.34.0 - missing resources
pulumi/pulumi v3.34.1- same behavior of missing resources
pulumi/pulumi v3.33.2 - all resources get created correctly.

Can we confirm if this is referring to the cli version or the npm package version? A useful data point would be if they can confirm that _just_ changing the npm package and using the same version of the pulumi cli can repro the issue.

**Comment by contrarianchris** [comment] 2022-06-22 22:19
@Frassle The versions refer to the npm package version. The CLI was the same v3.34.1 throughout.

**Comment by contrarianchris** [comment] 2022-06-23 00:38
I have put together a reproduction in https://github.com/contrarianchris/pulumi-provider-missing-resources-repro

It is the https://github.com/pulumi/pulumi-component-provider-ts-boilerplate template with the VPC component added, and the provider's `@pulumi/pulumi` package pinned to 3.34.1. No other changes. Local CLI is still 3.34.1 as well.

Following the standard "Build and Test" steps in the README show the issue:
- Preview: 58 to create
- Update: 50 created

The output from `pulumi about` for this...

```
CLI
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown
xyz     0.0.1

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/chris/.nvm/versions/node/v16.15.0/bin/node' version='v16.15.0'

Current Stack: test

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:test::simple::pulumi:pulumi:Stack::simple-test
pulumi:providers:xyz                                 urn:pulumi:test::simple::pulumi:providers:xyz::default_0_0_1
xyz:index:StaticPage                                 urn:pulumi:test::simple::xyz:index:StaticPage::page
pulumi:providers:aws                                 urn:pulumi:test::simple::pulumi:providers:aws::default_4_38_1
aws:s3/bucket:Bucket                                 urn:pulumi:test::simple::xyz:index:StaticPage$aws:s3/bucket:Bucket::page
xyz:index:Vpc                                        urn:pulumi:test::simple::xyz:index:Vpc::vpc
aws:s3/bucketPolicy:BucketPolicy                     urn:pulumi:test::simple::xyz:index:StaticPage$aws:s3/bucket:Bucket$aws:s3/bucketPolicy:BucketPolicy::bucketPolicy
aws:s3/bucketObject:BucketObject                     urn:pulumi:test::simple::xyz:index:StaticPage$aws:s3/bucket:Bucket$aws:s3/bucketObject:BucketObject::page
aws:ec2/vpc:Vpc                                      urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc::simple-test-vpc
aws:ec2/eip:Eip                                      urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/eip:Eip::simple-test-natgw-eip-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::simple-test-private-rt-0
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-public-subnet-0
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-eks-subnet-0
aws:ec2/routeTable:RouteTable                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::simple-test-private-rt-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::simple-test-eks-rt-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::simple-test-eks-rt-0
aws:ec2/routeTable:RouteTable                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::simple-test-eks-rt-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::simple-test-private-rt-2
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-public-subnet-1
aws:ec2/eip:Eip                                      urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/eip:Eip::simple-test-natgw-eip-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::simple-test-eks-rt-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable::simple-test-private-rt-3
aws:ec2/defaultRouteTable:DefaultRouteTable          urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/defaultRouteTable:DefaultRouteTable::simple-test-public-rt
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-public-subnet-2
aws:ec2/internetGateway:InternetGateway              urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::simple-test-igw
aws:ec2/eip:Eip                                      urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/eip:Eip::simple-test-natgw-eip-0
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-private-subnet-0
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-eks-subnet-1
aws:ec2/eip:Eip                                      urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/eip:Eip::simple-test-natgw-eip-1
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-private-subnet-3
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-public-subnet-3
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-eks-subnet-2
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-private-subnet-1
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-private-subnet-2
aws:ec2/subnet:Subnet                                urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::simple-test-eks-subnet-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-eks-rt-association-0
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/defaultRouteTable:DefaultRouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-public-rt-association-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/defaultRouteTable:DefaultRouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-public-rt-association-0
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-private-rt-association-0
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/defaultRouteTable:DefaultRouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-public-rt-association-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-eks-rt-association-1
aws:ec2/route:Route                                  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/defaultRouteTable:DefaultRouteTable$aws:ec2/route:Route::simple-test-public-route
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-private-rt-association-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/defaultRouteTable:DefaultRouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-public-rt-association-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-eks-rt-association-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-private-rt-association-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-private-rt-association-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::simple-test-eks-rt-association-3
aws:ec2/natGateway:NatGateway                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::simple-test-natgw-1
aws:ec2/natGateway:NatGateway                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::simple-test-natgw-0
aws:ec2/natGateway:NatGateway                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::simple-test-natgw-2
aws:ec2/natGateway:NatGateway                        urn:pulumi:test::simple::xyz:index:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/natGateway:NatGateway::simple-test-natgw-3


Found no pending operations associated with test

Backend
Name           pulumi.com
URL            https://app.pulumi.com/contrarianchris
User           contrarianchris
Organizations  contrarianchris, laybuy

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.35.0
@types/node     10.17.60

Pulumi locates its logs in /tmp by default
```

**Comment by contrarianchris** [comment] 2022-06-23 00:42
Of note, using this same `Vpc` component (copy and paste) in a regular Pulumi project outside of an MLC provider does not exhibit this issue. All resources are created properly when using the latest Pulumi versions.

**Comment by Frassle** [comment] 2022-06-23 08:52
Thanks for all the information, should help with tracking down what's gone wrong here. Interesting that it seems MLC and sdk version specific.

**Comment by Frassle** [comment] 2022-06-23 16:41
I've had no issue reproducing the bug where some of the Route resources aren't created in the first call to up. What I _haven't_ been able to reproduce is seeing this working on old versions of Pulumi. Rebuilding the MLC and the test project with 3.33.2 still results in the Route resources not being created.

**Comment by contrarianchris** [comment] 2022-06-27 03:46
I still have missing routes when building the MLC with 3.35.0, but with 3.35.1 they are created.

- 3.34.1 CLI, 3.34.1 Project, 3.34.1 MLC = ❌
- 3.34.1 CLI, 3.34.1 Project, 3.35.0 MLC = ❌
- 3.34.1 CLI, 3.34.1 Project, 3.35.1 MLC = ✅

Bumping up everything else to match is successful as well...

- 3.35.1 CLI, 3.35.1 Project, 3.35.1 MLC = ✅

I am setting explicit versions in the `package.json` files in `provider/cmd/pulumi-resource-xyz` and `examples/simple`.
```
    "dependencies": {
        "@pulumi/pulumi": "3.35.1",
```

**Comment by contrarianchris** [comment] 2022-11-24 06:55
I think this can be closed. I have not seen a repeat of this since 3.35.1.

**Comment by aureq** [comment] 2023-01-11 20:43
Thank you @theplatformer and glad to hear everything appears to be working. I'm closing this issue since there has been no re-occurrence since.

**Closed by aureq** 2023-01-11 20:43 UTC
Labels: kind/bug, area/component-packages, resolution/fixed, needs-repro
