### ISSUE TITLE
pulumi refresh pulling in extra inputs

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi#6241] opened 2021-02-02 19:19 UTC
The `pulumi refresh`  is bringing in extra inputs that are not there. 
This is causing the pulumi preview to `fail` to run.  
Sample error:
```
aws:ec2:Instance (my-instance):
    error: aws:ec2/instance:Instance resource 'my-instance' has a problem: Computed attribute cannot be set
```

cloud:  aws

Example extra inputs that are brought into inputs for instance:
```
 "rootBlockDevice": {
                        "deviceName": "/dev/sda1",
                        "volumeId": "vol-066026c3014c804f4",
                     }
```

```
 "ebsBlockDevices": {
                             ..
                            "volumeId": "vol-0a41d4ab9db6c076a",
                            ..
                    }
```

**Comment by pgavlin** [comment] 2021-02-22 22:02
Quick update here:

This specific issue is due to the adapter we use to extract input properties from state in our Terraform bridge. Many Terraform resources have properties that are both inputs and outputs. The behavior of these properties is a bit unusual: during an update, if the user provides a value, Terraform uses that value and will detect differences with respect to the state; if the user does not provide a value, Terraform will assume that the property has not changed. Among other challenges, this makes it impossible to _unset_ an inout in TF by simply removing the property from config. The current implementation of `Read` in the bridge conservatively assumes that any property that is an input and is present in the state should be treated as a user input. This behavior was intended primarily to make difference detection possible prior to the introduction of provider-side diffs. This behavior differs from the aforementioned Terraform semantics, which causes these sorts of failures because the values of the properties in resource state are not guaranteed to meet the same validation criteria to which input properties are subject.

My suggested fix is to only update values for properties that are present in the existing inputs, if any, and to only pull _pure_ inputs from the state if there are no existing inputs (as is the case in import). The latter is simple, and will hopefully result in a better user experience than we have today, as it should cause fewer properties to be required when importing a resource programmatically or output when importing via `pulumi import`. The former is a bit more complicated, as it interacts with the default value semantics of the bridge: in particular, it is not clear whether or not we should continue to regard a defaulted property as defaulted if its value has changed in the state. The current implementation opts not to do so, but this means that a user must explicitly edit their program if the refreshed value is acceptable. Opting to change the default value to reflect the state would prevent these edits, but would also obscure the fact that the value has changed.

@lukehoban any ideas on the defaults point?

**Comment by lukehoban** [comment] 2021-02-23 08:54
> @lukehoban any ideas on the defaults point?

Do you have a concrete example of this?  A specific resource and default property, and a refresh-then-code-change that you are worried would behave unexpectedly?

**Comment by pgavlin** [comment] 2021-02-24 17:19
> Do you have a concrete example of this? A specific resource and default property, and a refresh-then-code-change that you are worried would behave unexpectedly?

Unfortunately I do not. I'll see if I can pull one together--it would require an optional computed with a default value.

**Comment by lukehoban** [comment] 2021-03-18 03:20
There's not a concrete repro here to verify for sure - but I am reasonably confident this has been fixed by https://github.com/pulumi/pulumi-terraform-bridge/pull/330.  Closing out.

**Closed by lukehoban** 2021-03-18 03:20 UTC
Labels: p1
