### ISSUE TITLE
[go] `pulumi pre|up` panics when moving from `pulumi-vault` 5.6.0 to 5.7.0 and above

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#12300] opened 2023-02-27 23:16 UTC
### What happened?

A panic occurs for the below program when using `pulumi-vault` 5.7.0 or greater. This program does not panic on `pulumi-vault` 5.6.0 or less.

Error: ` panic: interface conversion: pulumi.Output is pulumi.StringOutput, not pulumi.StringPtrOutput`

### Expected Behavior

No panic

### Steps to reproduce

Run the below program with `pulumi-vault` 5.7.0 or greater.

```golang
package main

import (
	"github.com/pulumi/pulumi-vault/sdk/v5/go/vault/azure"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		clientId := pulumi.String("my-token")
		subId := pulumi.String("my-subid")
		tenantId := pulumi.String("my-token")
		_, err := azure.NewBackend(ctx, "az", &azure.BackendArgs{
			ClientId:       pulumi.ToSecret(clientId).(pulumi.StringPtrOutput),
			Environment:    pulumi.String("AzurePublicCloud"),
			Path:           pulumi.String("azure"),
			SubscriptionId: pulumi.ToSecret(subId).(pulumi.StringOutput),
			TenantId:       pulumi.ToSecret(tenantId).(pulumi.StringOutput),
		})

		if err != nil {
			return err
		}

		return nil
	})
}
```

### Output of `pulumi about`

Dependencies:
NAME                                   VERSION
github.com/pulumi/pulumi-vault/sdk/v5  5.8.0
github.com/pulumi/pulumi/sdk/v3        3.48.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by abhinav** [comment] 2023-02-28 16:40
A copy of the stack trace will help.

First, panicking on the following line makes sense.

```go
clientId := pulumi.String("my-token")
pulumi.ToSecret(clientId).(pulumi.StringPtrOutput)
```

`clientId` is a String, not a StringPtr.
ToSecret should not automatically convert a string to a string pointer,
and the `x.(foo)` form will only convert to what the value "already" is.

However, I agree that this is a bug in pu/pu: probably in the codegen.
BackendArgs.ClientId is defined as a StringPtr:

```go
type BackendArgs struct {
	// - The OAuth2 client id to connect to Azure.
	ClientId pulumi.StringPtrInput
```

`NewBackend` passes that into ToSecret and back to a StringPtrOutput:

```go
func NewBackend(ctx *pulumi.Context,
	name string, args *BackendArgs, opts ...pulumi.ResourceOption) (*Backend, error) {
	// ...
	if args.ClientId != nil {
		args.ClientId = pulumi.ToSecret(args.ClientId).(pulumi.StringPtrOutput)
	}
```

If the ClientId is a String, pulumi.ToSecret will return a pulumi.StringOutput, not a StringPtrOutput.
The issue here is that pulumi.String is a valid StringPtrInput, but it's being left as a String.
Somewhere in there, there needs to be a call to `ToStringPtrOutput()`—either before or after the ToSecret,
because ToSecret can't know that the pulumi.String is meant to be a StringPtr.

If the ClientId is a String, not StringPtr, pu/pu should auto-cast that to StringPtr (since String is a valid StringPtrInput).

**Comment by iwahbe** [comment] 2023-03-01 09:19
I don't think this is a bug in codegen, but in the Pulumi Go SDK itself (not a provider go sdk). The panic occurs before `azure.BackendArgs` is constructed. If the original example ever ran correctly, that means that `pulumi.ToSecret(clientId).(pulumi.StringPtrOutput)` was valid. 

I would swap `area/codegen` for `area/sdks`, `language/go`.

**Comment by abhinav** [comment] 2023-03-01 18:26
I must have misunderstood what line the panic is coming from.
I assumed it was the codegen because of the snippets I included above.

If the panic is not from the generated code, then this is not a bug.
The following should panic:

```go
clientId := pulumi.String("my-token")
pulumi.ToSecret(clientId).(pulumi.StringPtrOutput)
```

String goes in, StringOutput comes out. Not StringPtr.

However, StringOutput implements StringPtrInput,
so casting to that shouldn't panic (and doesn't).

```go
clientId := pulumi.String("my-token")
pulumi.ToSecret(clientId).(pulumi.StringPtrInput)
```

But casting from a plain String to StringPtrOutput should and does panic.

**Comment by iwahbe** [comment] 2023-03-01 18:31
@phillipedwards Can you post the version of `"github.com/pulumi/pulumi/sdk/v3/go/pulumi"` used when your repro didn't panic, and post the full stack trace (redacted if necessary)? We want to confirm on which line the panic originates from.

**Comment by dixler** [comment] 2023-03-02 21:42
I also concur with @abhinav. This seems like the user used a type assertion in a fragile manner.

I'd recommend changing to either:

1. `clientId := pulumi.StringPtr("my-token")`
2. ` ClientId:       pulumi.ToSecret(clientId).(pulumi.StringOutput).ToStringPtrOutput(),`

I'm going to close this as by-design

**Closed by dixler** 2023-03-02 21:42 UTC
Labels: kind/bug, p1, area/codegen, resolution/by-design, customer/feedback, customer/lighthouse

**Comment by phillipedwards** [comment] 2023-03-02 22:51
@dixler using a type assertion in a fragile manner or not is irrelevant to the issue. While I agree with you, the issue is a once valid block of code became invalid across a minor provider version bump because _somthing_ (not user code) changed. I'm not going to re-open it because I think your recommended changes are appropriate.

@iwahbe version of `pulumi/pulumi` is 3.48.0 but also reproduces with 3.55.0. Stack traces for both below.

Stack trace:
```
// 3.48.0
    panic: interface conversion: pulumi.Output is pulumi.StringOutput, not pulumi.StringPtrOutput
    goroutine 1 [running]:
    main.main.func1(0xe44200?)
        /home/pedwards/repos/snowflake/vault-type-issue/main.go:15 +0x205
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc000192420, 0xeae9a0)
        /home/pedwards/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.48.0/go/pulumi/run.go:120 +0x199
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.runErrInner(0xc0000021a0?, 0xead2f0, {0x0, 0x0, 0x408959?})
        /home/pedwards/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.48.0/go/pulumi/run.go:96 +0x2f1
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0x0?, {0x0?, 0xca3ce0?, 0xc0000021a0?})
        /home/pedwards/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.48.0/go/pulumi/run.go:48 +0x2e
    main.main()
        /home/pedwards/repos/snowflake/vault-type-issue/main.go:9 +0x27

    error: an unhandled error occurred: program exited with non-zero exit code: 2

// 3.55.0
    panic: interface conversion: pulumi.Output is pulumi.StringOutput, not pulumi.StringPtrOutput
    goroutine 1 [running]:
    main.main.func1(0xe22100?)
        /home/pedwards/repos/snowflake/vault-type-issue/main.go:15 +0x205
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.RunWithContext(0xc0000ca580, 0xe8cc78)
        /home/pedwards/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.55.0/go/pulumi/run.go:121 +0x1aa
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.runErrInner(0xc0000021a0?, 0xe8b5d0, {0x0, 0x0, 0x408959?})
        /home/pedwards/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.55.0/go/pulumi/run.go:97 +0x317
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.Run(0x0?, {0x0?, 0xc80380?, 0xc0000021a0?})
        /home/pedwards/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.55.0/go/pulumi/run.go:49 +0x2e
    main.main()
        /home/pedwards/repos/snowflake/vault-type-issue/main.go:9 +0x27

    error: an unhandled error occurred: program exited with non-zero exit code: 2
```
