### ISSUE TITLE
Abilityto generate code via `pulumi import` without importing resources into code.

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi#13451] opened 2023-07-11 06:23 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add the ability to run `pulumi import --dry-run` or something like that in order to see the generated pulumi code _without_ importing the resource into state.

Reasoning:
As a dev working on reuse modules and importing legacy cloud resources into already authored reuse modeles I often times find myself in the situation to simply wanting to look at how a specific cloud resource would look like in pulumi - incl. all it's flags etc.
This actually happens quite frequently and arguably more often than actual desired state imports. Therefore it would be great to have the ability to use pulumi simply for code generation of existing cloud resources without importing it right away into state.
One idea would be to add a flag `--dry-run` to `pulumi import` but I'm also fine with another command name or so e.g. `pulumi generate <urn-to-cloud-resource`. In the latter case we may even omit the resource id from the command flags for simplicity because all we care is about the generated code but not much the specific resource urn / id being assigned by pulumi.

**Comment by Frassle** [comment] 2023-07-11 07:02
Duplicate of https://github.com/pulumi/pulumi/issues/13451

**Closed by Frassle** 2023-07-11 07:02 UTC
Labels: kind/enhancement, resolution/duplicate
