### ISSUE TITLE
[Bug]: CLoudfront ignore_changes=['origins[*].originPath']

### ISSUE THREAD

**Issue by Rez0k** [pulumi/pulumi#15125] opened 2024-01-10 06:57 UTC
### Expected Behavior

When adding the ignore_changes=['origins[*].originPath'] to cloudfront.Distribution(opts=...) I expect the origin path to be ignored (we change the path very often)

If I try to ignore_changes=['origins'] I will get the error:
```
aws:cloudfront/distribution:Distribution resource 'XXX' has a problem: origin.0.origin_access_control_id must not be empty, got . Examine values at 'XXX.origins'.
```
I have 2 origins, s3 bucket which has an origin_access_control_id and a lb origin which does not has origin_access_control_id
why am I getting this error?
If I remove the ignore_changes everything is working just fine.

note: I am using refresh: always

### Actual Behavior

The origin path does get ignored but pulumi wants to change the origin(!) to a different one,
I have 2 origins, one that point to a load balancer and one that point to a s3 bucket.
I have origin_path set only on the s3 bucket origin, but when I use the ignore originPath, pulumi set the originPath to the lb instead of the s3!

```
~ [2]: {
                      ~ connectionAttempts   : 3 => 3
                      ~ connectionTimeout    : 10 => 10
                      + customOriginConfig   : {
                          + httpPort              : 80
                          + httpsPort             : 443
                          + originKeepaliveTimeout: 5
                          + originProtocolPolicy  : "https-only"
                          + originReadTimeout     : 30
                          + originSslProtocols    : [
                          +     [0]: "TLSv1.2"
                            ]
                        }
                      ~ domainName           : "<original origin (s3 bucket)>" => "<second origin (should not be here -> alb)>"
                      - originAccessControlId: "XXXXXX"
                      ~ originId             : "<original origin (s3 bucket)>" => "<second origin (should not be here -> alb)>"
                      ~ originPath           : "<stays the same>" => "<stays the same>"
                    }
```

### Output of `pulumi about`

CLI          
Version      3.97.0
Go Version   go1.21.5
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Rez0k** [comment] 2024-01-14 09:32
?

**Comment by justinvp** [comment] 2024-02-14 06:24
Hi @Rez0k. Thanks for opening this issue and sorry for the trouble. I see you opened https://github.com/pulumi/pulumi-aws/issues/3396 and have more details there. I'm going to close this issue as a duplicate, but if the underlying root cause is in the core pulumi engine, we can transfer that issue to this repository.

**Closed by justinvp** 2024-02-14 06:24 UTC
Labels: kind/bug, resolution/duplicate
