### ISSUE TITLE
Config yaml file is reformatted during preview using the AKV secrets provider

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi#6848] opened 2021-04-22 16:01 UTC
I experience this issue with Pulumi 3.0 and Azure Key Vault as secrets provider. Whenever I make a preview the yaml file is reformatted by Pulumi.

**Comment by komalali** [comment] 2021-04-22 17:48
@lblackstone is this expected after the roundtripping yaml work?

**Comment by lblackstone** [comment] 2021-04-27 15:23
The changes that will fix this were reverted and are still [in progress](https://github.com/pulumi/pulumi/pull/6489). I'm going to close this as a duplicate of #423

**Closed by lblackstone** 2021-04-27 15:23 UTC
Labels: kind/bug, resolution/duplicate
