### ISSUE TITLE
404 getting pulumi-language-nodejs

### ISSUE THREAD

**Issue by mausch** [pulumi/pulumi#11703] opened 2022-12-21 13:05 UTC
### What happened?

Can't init a new project using TypeScript.

### Steps to reproduce

```
$ nix shell nixpkgs#pulumi nixpkgs#nodejs-18_x
$ pulumi login s3://my-bucket
$ pulumi new typescript --force

This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (infra) 
project description: (A minimal TypeScript Pulumi program) 
Created project 'infra'

stack name: (dev) develop
Created stack 'develop'
Enter your passphrase to protect config/secrets: 
Re-enter your passphrase to confirm: 

warning: A new version of Pulumi is available. To upgrade from version '3.49.0' to '3.50.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
error: failed to load language plugin nodejs: Could not automatically download and install language plugin 'pulumi-language-nodejs', install the plugin using `pulumi plugin install language nodejs`.
Underlying error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-nodejs/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens

$ pulumi plugin install language nodejs
warning: A new version of Pulumi is available. To upgrade from version '3.49.0' to '3.50.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-nodejs/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

### Expected Behavior

Project initialised

### Actual Behavior

404

### Output of `pulumi about`

```
CLI          
Version      3.49.0
Go Version   go1.19.4
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           mauricio-Precision-Tower-5810
URL            s3://my-bucket
User           mauricio
Organizations  

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the plugin: failed to load language plugin nodejs: Could not automatically download and install language plugin 'pulumi-language-nodejs', install the plugin using `pulumi plugin install language nodejs`.
Underlying error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-nodejs/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
warning: Failed to load language plugin nodejs: Could not automatically download and install language plugin 'pulumi-language-nodejs', install the plugin using `pulumi plugin install language nodejs`.
Underlying error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-nodejs/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
warning: Failed to get information about the current stack: No current snapshot
warning: A new version of Pulumi is available. To upgrade from version '3.49.0' to '3.50.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Additional context

As a Nix user I understand needing to manage plugins myself. 
In fact I see there's a "[pulumi-language-nodejs](https://github.com/NixOS/nixpkgs/blob/ff17e9982d84ac30855d838d277816f60b9b663f/pkgs/tools/admin/pulumi-packages/pulumi-language-nodejs.nix)" nix package, I'll see how that works.
But getting a 404 trying to download something seems weird?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mausch** [comment] 2022-12-21 14:32
BTW the `pulumi-bin` package works fine.
According to [this](https://github.com/NixOS/nixpkgs/commit/35657c42623f858deff6f3a9990224e47a0884a0) `pulumi` is built from source and `pulumi-bin` is packaged from binaries.
So maybe it's some kind of nix packaging issue? Dunno.

**Comment by mausch** [comment] 2022-12-21 22:02
> Can you post the file tree located under $PULUMI_HOME?

`$PULUMI_HOME` is not set.

> references a repo that doesn't exist:

Seems to come from https://github.com/pulumi/pulumi/blob/40e0ac20c9217443af5c4f332db210cbbeda145c/sdk/go/common/workspace/plugins.go#L239 ? 
It seems that pulumi expects this plugin to be always present (and probably usually is, as distributed by Pulumi)?
So the issue happens when things aren't distributed as expected?
Just some wild guesses :slightly_smiling_face:

**Comment by RobbieMcKinstry** [comment] 2022-12-22 15:05
Hi @mausch Yes, you're got it exactly right.

`pulumi plugin install language nodejs` just doesn't work -- I asked around, and we don't intend to support this command (at least for now) because we expect the installation of the NodeJS language plugin as part of package distribution. i.e. with homebrew, you will always get the NodeJS language plugin installed when you install or update your package.

For now, I'd like to improve the error message to show `language nodejs` isn't supported for plugin installation (same for Go and Python).

In the long run, we should pull down the latest tarbar (_e.g._ https://github.com/pulumi/pulumi/releases/download/v3.50.2/pulumi-v3.50.2-darwin-arm64.tar.gz`), unpack `pulumi-language-nodejs` and install it. This would let `pulumi plugin install language nodejs` work as intended.

For now, unfortunately, I suggest you work around the issue by doing that -- pulling down the tarball for your operating system, unpacking it, and extracting `pulumi-*-nodejs` files into `$PATH`.

**Comment by RobbieMcKinstry** [comment] 2022-12-22 15:16
@mausch oh, I see there's another package that explicitly builds the nodejs and python runtimes. 
`pulumiPackages` has support for nodejs, python, and some major providers too, and the maintainers of the package are the same.

NodeJS is only available on the unstable channel. 

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=pulumiPackages

Sounds like you might be able to workaround the problem by installing this package after installing the first package.

**Comment by mausch** [comment] 2022-12-22 22:15
> For now, I'd like to improve the error message to show language nodejs isn't supported for plugin installation (same for Go and Python).

Yep sounds good.

> pulumiPackages has support for nodejs...

Yep that's the one I mentioned in my original message.

The issue for pulumi here is just improving the error message, that's all.

**Comment by jamesloosli** [comment] 2023-04-25 16:26
I'm having this issue as well.

We're using github self-hosted runners, with a container we built to include the pulumi binary. Relevant dockerfile lines;

```
# Pulumi
RUN curl -fsSL https://get.pulumi.com | sh && \
  mv ~/.pulumi/bin/pulumi /usr/local/bin/pulumi
```

I'm wondering if moving the bin into our path is the issue.

**Comment by jamesloosli** [comment] 2023-04-25 16:39
I dug into the pulumi install tarball, and realized that the default plugins are all separate files;

![Screenshot 2023-04-25 at 11 35 24](https://user-images.githubusercontent.com/3769605/234344804-4f024dcf-33bc-462e-b7d6-a4a7e68dd3f9.png)

Altered our Dockerfile to suit. 

```
# Pulumi
RUN curl -fsSL https://get.pulumi.com/ | sh && \
  mv ~/.pulumi/bin/* /usr/local/bin/
```

Will return and report.

**Comment by justinvp** [comment] 2023-07-27 08:03
Closing this as By Design. The `pulumi-language-nodejs` binary should live next to the `pulumi` binary, which is how we distribute it. Third party package managers should do the same.

**Comment by mausch** [comment] 2023-07-27 08:40
> The pulumi-language-nodejs binary should live next to the pulumi binary, which is how we distribute it. Third party package managers should do the same.

Just to be clear this issue was never about Pulumi distribution or packages.
It's about the opaque error message.

**Comment by Frassle** [comment] 2023-07-27 08:48
Reopened. We should fix up "plugin install" to error that these bundled plugins aren't really plugins to be installed via that command, and fix up the error message when they're missing to report that the pulumi installation is not complete.

**Comment by RobbieMcKinstry** [comment] 2023-07-27 21:06
As a friendly reminder ❤️ , there's an open PR to resolve this issue here. https://github.com/pulumi/pulumi/pull/12575

**Comment by Frassle** [comment] 2023-07-28 09:14
Thanks for that reminder @RobbieMcKinstry, I'll get that finished off :)

**Closed** 2023-08-08 11:40 UTC
Labels: kind/bug, impact/usability, good-first-issue, size/S, impact/quality, area/plugins, area/language-host
