### ISSUE TITLE
Add ability to name Python packages

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#6867] opened 2021-04-24 19:11 UTC
[DotNet](https://github.com/pulumi/pulumi/blob/a8ea363df970c58709097b3ab28e82afc5a0d9ce/pkg/codegen/internal/test/testdata/random.json#L738-L740), [JavaScript](https://github.com/pulumi/pulumi/blob/a8ea363df970c58709097b3ab28e82afc5a0d9ce/pkg/codegen/internal/test/testdata/random.json#L755) and Go modules all support the ability to override the name of the packages we emit with codegen. The exception to this is python.

[Python's package management system](https://github.com/pypa/warehouse/issues/2589) doesn't yet support any kind of namespacing in warehouse, which means a user's best effort approach would be to name their python package something like `jaxxstorm-pulumi-awsvpc`

However, there is nothing in the schema/spec to support this.

**Comment by infin8x** [comment] 2021-05-02 16:23
@jaxxstorm is this a duplicate of #6427?

**Comment by jaxxstorm** [comment] 2021-05-06 17:53
yes, closing!

**Closed** 2021-05-06 17:59 UTC
Labels: kind/enhancement, resolution/duplicate
