### ISSUE TITLE
Removing dependent resource in StackReference is not handled

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#5232] opened 2020-08-26 18:47 UTC
In this particular case, we have 2 projects: p1 and p2. In p1 we have a GCP Cloud SQL `DatabaseInstance`, and in p2 we have a Cloud SQL `User`. In p1 the instance had to be recreated due to a change. In p2, which references the `DatabaseInstance` via `StackReference`, when running `refresh` or `up`, it results in an error.

I created this issue here rather than in `pulumi-gcp` as I believe this to be a core issue of pulumi, and not 100% related to the particular provider.

## Expected Behavior
The expected behavior is that since the `User` in p2 depends upon the `DatabaseInstance` in p1, that it would detect that the resource does not exist anymore.

## Current Behavior
up:
```
 gcp:sql:User (wallet-api):
    error: deleting urn:pulumi:staging::wallet-api::gcp:sql/user:User::wallet-api: Error, failed to deleteuser wallet-api-576ae7b in instance wallet-database-bc88562: googleapi: Error 400: Invalid request: Invalid request since instance is not running., invalid
```

refresh:
```
gcp:sql:User (wallet-api):
    error: Preview failed: refreshing urn:pulumi:staging::wallet-api::gcp:sql/user:User::wallet-api: Error when reading or editing SQL User "wallet-api-576ae7b" in instance "wallet-database-bc88562": googleapi: Error 400: Invalid request: Invalid request since instance is not running., invalid
```

**Comment by leezen** [comment] 2020-08-27 02:55
Does this mean that the stack output somehow didn't change as a result of the instance replacement?

**Comment by nesl247** [comment] 2020-08-27 20:41
I believe it did but not 100% sure.

**Comment by leezen** [comment] 2020-08-27 23:31
Re-reading the issue, I'm wondering if the following is happening, in which case, this would be expected?

In `p2` the `User` is dependent on the `DatabaseInstance` which has changed. As such, an update to `p2` should result in a `replace` operation where the user is first deleted then created against the new instance. However, the delete operation fails since the instance no longer exists.

On refresh, the `User` cannot be read since the `DatabaseInstance` no longer exists.

The workaround here would be to `pulumi state delete` the user so that it can be created against the new instance correctly.

I guess the issue here is that resources across stacks aren't connected in a dependency graph and updates are not coordinated. If the two resources were part of the same stack, the user would have been deleted first as part of replacing the instance (since the dependency graph would track this). @nesl247 Would this be a correct re-statement of the issue: you want to be able to track dependencies across stacks and perform a multi-stack deployment that coordinates said dependencies?

**Comment by nesl247** [comment] 2020-08-27 23:33
Yes, that is an accurate description and the expected behavior given it's using a `StackReference`.

**Comment by leezen** [comment] 2020-08-27 23:40
@nesl247 Thanks. I believe this is already covered via https://github.com/pulumi/pulumi/issues/2209 and https://github.com/pulumi/pulumi/issues/2309 -- it'd be great to get your feedback in those issues on how you'd expect the feature to work. I'm closing this issue as a dupe of those, but please let me know if you feel otherwise.

**Closed by leezen** 2020-08-27 23:40 UTC
Labels: kind/bug

**Comment by nesl247** [comment] 2020-08-27 23:42
Those are exactly it. I've actually been subscribed to these for a long time. It's unfortunately been open for so long I forgot about those.

Thanks.
