### ISSUE TITLE
registerStackTransformations not registering

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi#6214] opened 2021-01-28 13:39 UTC
When I try to add a set of tags to all resources in the stack, nothing happens.

## Expected Behavior
Tagging all AWS specific items that can be tagged.

## Current Behavior
Nothing, it doesn't even appear to be called as I don't see the console.log appear in the output. It does work if I pass the same function as a resource level transformation.

## Steps to Reproduce

**Transformation function**: `isTaggable` matches [this example](https://github.com/joeduffy/aws-tags-example/tree/master/autotag-ts).

```
export function defaultTags(): pulumi.ResourceTransformation {
    return (args) => {
        const metadata = new pulumi.Config("tetrate").requireObject<metadata>("metadata")
        console.log(args.type)
        if (isTaggable(args.type)) {
            args.props["tags"] = { ...args.props["tags"], ...{
                "pulumi:project": pulumi.getProject(),
                "pulumi:stack": pulumi.getStack(),
                "tetrate:owner": metadata.owner,
                "tetrate:source": metadata.source,
            } }
            return { props: args.props, opts: args.opts }
        }
        return undefined
    }
}

interface metadata {
    owner: string
    source: string
}
```

**Project `index.ts`**: (`export class VPC extends awsx.ec2.Vpc`)
```
import * as pulumi from "@pulumi/pulumi"
import { VPC } from '@tetrate/aws'
import { PrivateSubnet, PublicSubnet, IsolatedSubnet } from '@tetrate/aws'
import { defaultTags } from '@tetrate/aws'

pulumi.runtime.registerStackTransformation(defaultTags())

const opsVpc = new VPC("cloudops", {
    cidrBlocks: ["10.10.0.0/16"],
    subnets: [
        new PrivateSubnet(22),
        new PublicSubnet(24),
        new IsolatedSubnet(24)
    ]
})

export const cloudops = opsVpc.output
```

## Context (Environment)
Typescript: 2.19.0

**Comment by leezen** [comment] 2021-01-28 17:18
I'm unable to reproduce this with the following:

**index.ts**
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";
import { defaultTags } from "./tagging";

pulumi.runtime.registerStackTransformation(defaultTags());

const vpc = new awsx.ec2.Vpc("test", {});
```

**tagging.ts**
```
import * as pulumi from "@pulumi/pulumi";

// isTaggable copied from the same link as you pointed to

export function defaultTags(): pulumi.ResourceTransformation {
    return (args) => {
        console.log(args.type)
        if (isTaggable(args.type)) {
            args.props["tags"] = { ...args.props["tags"], ...{
                "pulumi:project": pulumi.getProject(),
                "pulumi:stack": pulumi.getStack(),
            } }
            return { props: args.props, opts: args.opts }
        }
        return undefined
    }
}
```

When I run this program via `pulumi pre --diff` I get the following:

```
Previewing update (dev)

View Live: https://app.pulumi.com/leezen/scratch-pulumi-ts/dev/previews/***

+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:dev::scratch-pulumi-ts::pulumi:pulumi:Stack::scratch-pulumi-ts-dev]
awsx:x:ec2:Vpc          

    + awsx:x:ec2:Vpc: (create)
        [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc::test]
aws:ec2/vpc:Vpc         

awsx:x:ec2:Subnet

aws:ec2/subnet:Subnet

aws:ec2/routeTable:RouteTable

aws:ec2/routeTableAssociation:RouteTableAssociation

awsx:x:ec2:Subnet

aws:ec2/subnet:Subnet

aws:ec2/routeTable:RouteTable

aws:ec2/routeTableAssociation:RouteTableAssociation

awsx:x:ec2:Subnet

aws:ec2/subnet:Subnet

aws:ec2/routeTable:RouteTable

aws:ec2/routeTableAssociation:RouteTableAssociation

awsx:x:ec2:Subnet

aws:ec2/subnet:Subnet

aws:ec2/routeTable:RouteTable

aws:ec2/routeTableAssociation:RouteTableAssociation

awsx:x:ec2:NatGateway

aws:ec2/eip:Eip

aws:ec2/natGateway:NatGateway

awsx:x:ec2:NatGateway

aws:ec2/eip:Eip

aws:ec2/natGateway:NatGateway

aws:ec2/route:Route

aws:ec2/route:Route

awsx:x:ec2:InternetGateway

aws:ec2/internetGateway:InternetGateway

aws:ec2/route:Route

aws:ec2/route:Route

        + awsx:x:ec2:Subnet: (create)
            [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet::test-private-0]
        + awsx:x:ec2:NatGateway: (create)
            [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway::test-0]
        + awsx:x:ec2:Subnet: (create)
            [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet::test-private-1]
        + awsx:x:ec2:Subnet: (create)
            [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet::test-public-1]
        + awsx:x:ec2:NatGateway: (create)
            [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway::test-1]
        + awsx:x:ec2:InternetGateway: (create)
            [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:InternetGateway::test]
        + awsx:x:ec2:Subnet: (create)
            [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet::test-public-0]
        + aws:ec2/vpc:Vpc: (create)
            [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$aws:ec2/vpc:Vpc::test]
            [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
            assignGeneratedIpv6CidrBlock: false
            cidrBlock                   : "10.0.0.0/16"
            enableDnsHostnames          : true
            enableDnsSupport            : true
            instanceTenancy             : "default"
            tags                        : {
                pulumi:project: "scratch-pulumi-ts"
                pulumi:stack  : "dev"
            }
            + aws:ec2/eip:Eip: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::test-0]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                tags      : {
                    Name          : "test-0"
                    pulumi:project: "scratch-pulumi-ts"
                    pulumi:stack  : "dev"
                }
                vpc       : true
            + aws:ec2/eip:Eip: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::test-1]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                tags      : {
                    Name          : "test-1"
                    pulumi:project: "scratch-pulumi-ts"
                    pulumi:stack  : "dev"
                }
                vpc       : true
            + aws:ec2/routeTable:RouteTable: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTable:RouteTable::test-private-1]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                tags      : {
                    pulumi:project: "scratch-pulumi-ts"
                    pulumi:stack  : "dev"
                }
                vpcId     : output<string>
            + aws:ec2/routeTable:RouteTable: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTable:RouteTable::test-public-0]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                tags      : {
                    pulumi:project: "scratch-pulumi-ts"
                    pulumi:stack  : "dev"
                }
                vpcId     : output<string>
            + aws:ec2/internetGateway:InternetGateway: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:InternetGateway$aws:ec2/internetGateway:InternetGateway::test]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                tags      : {
                    pulumi:project: "scratch-pulumi-ts"
                    pulumi:stack  : "dev"
                }
                vpcId     : output<string>
            + aws:ec2/subnet:Subnet: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/subnet:Subnet::test-private-0]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                assignIpv6AddressOnCreation: false
                availabilityZone           : "us-west-2a"
                cidrBlock                  : "10.0.128.0/18"
                ipv6CidrBlock              : output<string>
                mapPublicIpOnLaunch        : false
                tags                       : {
                    Name      : "test-private-0"
                    type      : "private"
                }
                vpcId                      : output<string>
            + aws:ec2/routeTable:RouteTable: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTable:RouteTable::test-private-0]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                tags      : {
                    pulumi:project: "scratch-pulumi-ts"
                    pulumi:stack  : "dev"
                }
                vpcId     : output<string>
            + aws:ec2/subnet:Subnet: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/subnet:Subnet::test-public-0]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                assignIpv6AddressOnCreation: false
                availabilityZone           : "us-west-2a"
                cidrBlock                  : "10.0.0.0/18"
                ipv6CidrBlock              : output<string>
                mapPublicIpOnLaunch        : true
                tags                       : {
                    Name      : "test-public-0"
                    type      : "public"
                }
                vpcId                      : output<string>
            + aws:ec2/subnet:Subnet: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/subnet:Subnet::test-public-1]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                assignIpv6AddressOnCreation: false
                availabilityZone           : "us-west-2b"
                cidrBlock                  : "10.0.64.0/18"
                ipv6CidrBlock              : output<string>
                mapPublicIpOnLaunch        : true
                tags                       : {
                    Name      : "test-public-1"
                    type      : "public"
                }
                vpcId                      : output<string>
            + aws:ec2/routeTable:RouteTable: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTable:RouteTable::test-public-1]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                tags      : {
                    pulumi:project: "scratch-pulumi-ts"
                    pulumi:stack  : "dev"
                }
                vpcId     : output<string>
            + aws:ec2/subnet:Subnet: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/subnet:Subnet::test-private-1]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                assignIpv6AddressOnCreation: false
                availabilityZone           : "us-west-2b"
                cidrBlock                  : "10.0.192.0/18"
                ipv6CidrBlock              : output<string>
                mapPublicIpOnLaunch        : false
                tags                       : {
                    Name      : "test-private-1"
                    type      : "private"
                }
                vpcId                      : output<string>
            + aws:ec2/route:Route: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::test-public-0-ig]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                destinationCidrBlock: "0.0.0.0/0"
                gatewayId           : output<string>
                routeTableId        : output<string>
            + aws:ec2/routeTableAssociation:RouteTableAssociation: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTableAssociation:RouteTableAssociation::test-private-0]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                routeTableId: output<string>
                subnetId    : output<string>
            + aws:ec2/routeTableAssociation:RouteTableAssociation: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTableAssociation:RouteTableAssociation::test-public-0]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                routeTableId: output<string>
                subnetId    : output<string>
            + aws:ec2/route:Route: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::test-public-1-ig]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                destinationCidrBlock: "0.0.0.0/0"
                gatewayId           : output<string>
                routeTableId        : output<string>
            + aws:ec2/routeTableAssociation:RouteTableAssociation: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTableAssociation:RouteTableAssociation::test-public-1]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                routeTableId: output<string>
                subnetId    : output<string>
            + aws:ec2/routeTableAssociation:RouteTableAssociation: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/routeTableAssociation:RouteTableAssociation::test-private-1]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                routeTableId: output<string>
                subnetId    : output<string>
            + aws:ec2/natGateway:NatGateway: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/natGateway:NatGateway::test-0]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                allocationId: output<string>
                subnetId    : output<string>
                tags        : {
                    pulumi:project: "scratch-pulumi-ts"
                    pulumi:stack  : "dev"
                }
            + aws:ec2/natGateway:NatGateway: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:NatGateway$aws:ec2/natGateway:NatGateway::test-1]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                allocationId: output<string>
                subnetId    : output<string>
                tags        : {
                    pulumi:project: "scratch-pulumi-ts"
                    pulumi:stack  : "dev"
                }
            + aws:ec2/route:Route: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::test-private-0-nat-0]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                destinationCidrBlock: "0.0.0.0/0"
                natGatewayId        : output<string>
                routeTableId        : output<string>
            + aws:ec2/route:Route: (create)
                [urn=urn:pulumi:dev::scratch-pulumi-ts::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/route:Route::test-private-1-nat-1]
                [provider=urn:pulumi:dev::scratch-pulumi-ts::pulumi:providers:aws::default_3_25_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                destinationCidrBlock: "0.0.0.0/0"
                natGatewayId        : output<string>
                routeTableId        : output<string>
Resources:              
    + 31 to create
```

I don't have access to your VPC class, but any chance the transformations are being elided in the parent somehow?

**Comment by liamawhite** [comment] 2021-01-28 20:02
Maybe I'm misunderstanding what the function does? This is my VPC class.

```
export class VPC extends awsx.ec2.Vpc {
    constructor(name: string, args: VpcArgs) {
        super(name, {
            cidrBlock: args.cidrBlocks[0],
            subnets: buildVpcSubnetArgs(args.subnets),
            numberOfAvailabilityZones: 3,
            tags: {"Name": name},
        })
        
        // Attach additional CIDR Blocks
        args.cidrBlocks.forEach((cidr, index) => {
            if (index == 0) {return}
            const _ = new aws.ec2.VpcIpv4CidrBlockAssociation(`${name}-${index}`, {
                vpcId: this.id,
                cidrBlock: cidr
            },{parent: this})
        });
    }
```

**Comment by leezen** [comment] 2021-01-29 01:34
Trying something similar to what you have above, I'm still not able to reproduce the issue and I see tags proposed for all the relevant resources. Using the simple example I had above, are you able to have your stack transformation execute? Could you please provide the pulumi package version you're using that's recorded in `package-lock.json` or `yarn.lock`? I'm running the above against pulumi 2.19.0 (both `@pulumi/pulumi` as well as the CLI)

**Comment by liamawhite** [comment] 2021-01-29 02:37
```
        "@pulumi/pulumi": {
            "version": "2.19.0",
            "resolved": "https://registry.npmjs.org/@pulumi/pulumi/-/pulumi-2.19.0.tgz",
            "integrity": "sha512-+nMPYLAF7gNCAEuYgtcWnJiR4spLgk2zRavVnYKJ+FudOH9aK3S0pl9xbfbMVEBgXN1sCRE0AVWF1aYlMBaLKw==",
            "requires": {
                "@grpc/grpc-js": "^0.6.15",
                "@pulumi/query": "^0.3.0",
                "google-protobuf": "^3.5.0",
                "js-yaml": "^3.14.0",
                "minimist": "^1.2.0",
                "normalize-package-data": "^2.4.0",
                "protobufjs": "^6.8.6",
                "read-package-tree": "^5.3.1",
                "require-from-string": "^2.0.1",
                "semver": "^6.1.0",
                "source-map-support": "^0.4.16",
                "ts-node": "^7.0.1",
                "typescript": "~3.7.3",
                "upath": "^1.1.0"
            }
        },
```

```
pulumi version
v2.19.0
```

**Comment by leezen** [comment] 2021-01-29 03:25
Odd. I'm not really sure what's going on as it sounds like we have very similar execution environments at this point. One other thing to try might be just blow away `node_modules` and reinstall the dependencies.

**Comment by leezen** [comment] 2021-01-29 19:28
Just an update for posterity, after corresponding on community Slack. I think this could have to do with bringing in a separate `@pulumi/pulumi` module in a local development environment.

**Comment by liamawhite** [comment] 2021-02-01 13:21
As discussed, here is the information for the issue where subnets aren't getting tagged. I add a console.log for the tags of each object and it appears that subnet tags are Pulumi outputs.

```    
	aws:ec2/routeTable:RouteTable undefined
    aws:ec2/subnet:Subnet OutputImpl {
      __pulumiOutput: true,
      resources: [Function],
      allResources: [Function],
      isKnown: Promise { <pending> },
      isSecret: Promise { <pending> },
      promise: [Function],
      toString: [Function],
      toJSON: [Function]
    }
    aws:ec2/routeTable:RouteTable undefined
    aws:ec2/eip:Eip { Name: 'cloudops-0' }
    aws:ec2/natGateway:NatGateway undefined
```

The function is the same as in my original comment but with the log modified to this `console.log(args.type, args.props["tags"])`.

**Comment by leezen** [comment] 2021-02-04 06:01
Sorry for the confusion here. I took a deeper look and it looks like what's happening is due to the way the `awsx` library has structured the `Subnet` resource: https://github.com/pulumi/pulumi-awsx/blob/7d655fc2ea91a8cab42f84092252c9e138d6fcbc/nodejs/awsx/ec2/vpc.ts#L160 -- you'll see in that line that `utils.mergeTags` which is what's ultimately causing this to return an `Output`

This is a bit of an unfortunate case where you'll need to account for this. What you could do here is the following to account for when the tags are an output:

```
export function defaultTags(): pulumi.ResourceTransformation {
    return (args) => {
        if (isTaggable(args.type)) {
            const tags = args.props["tags"];
            if (pulumi.Output.isInstance(tags)) {
                args.props["tags"] = args.props["tags"].apply((t: any) => {
                    return {
                        ...t,
                        ...{
                            "pulumi:project": pulumi.getProject(),
                            "pulumi:stack": pulumi.getStack(),
                        }
                    };
                })
            } else {
                args.props["tags"] = { ...args.props["tags"], ...{
                    "pulumi:project": pulumi.getProject(),
                    "pulumi:stack": pulumi.getStack(),
                    "hi": "ho",
                } }
            }
            return { props: args.props, opts: args.opts }
        }
        return undefined
    }
}
```

**Comment by Pavel910** [comment] 2021-02-26 23:14
@liamawhite have you managed to find a solution? I'm facing the same problem, using the same `2.19.0` version. The callback passed to `pulumi.runtime.registerStackTransformation` just doesn't get invoked, no matter what resource I use.

**Comment by Pavel910** [comment] 2021-02-26 23:35
> Just an update for posterity, after corresponding on community Slack. I think this could have to do with bringing in a separate `@pulumi/pulumi` module in a local development environment.

This helped me solve the problem. I have a monorepo, and I had 2 versions of pulumi pulled in, so `@pulumi/aws` was resolving to 1 version, and `@pulumi/pulumi` to a different version. Solved that, and tags are working 🎉

**Comment by DavidHe1127** [comment] 2021-06-17 10:54
@leezen Hey I can confirm `registerStackTransformation` stops being triggered with the setup below:

```
    "@pulumi/pulumi": "^3.0.0",
    "@pulumi/aws": "^3.0.0",
```

It's still working with `2.x.x`. Looking further I found `this.__transformations` has zero element which it shouldn't. Instead it should include the custom callback being passed into `pulumi.runtime.registerStackTransformation`. See below
https://github.com/pulumi/pulumi/blob/a952140b34c667d005116ee53be08077b5863948/sdk/nodejs/resource.ts#L236

can you please have a look?

**Comment by leezen** [comment] 2021-06-17 21:54
@DavidHe1127 The setup you specified above is going to have a similar situation to what's discussed above -- you'll end up with two copies of `@pulumi/pulumi` as aws 3.x brings in `@pulumi/pulumi` 2.x. You'll likely want to upgrade to `@pulumi/aws` 4.x.

**Comment by DavidHe1127** [comment] 2021-06-18 05:39
@leezen Thanks for your quick reply. I can confirm it's working after bump `aws` version to `4.8.0`.

**Comment by clstokes** [comment] 2021-09-03 19:40
Reopening this as it seems this can still occur if their upgrade paths lead them to introducing new occurrences of side-by-side pulumi packages that weren't there previously.

The one big known issue is with `registerStackTransformations` which will only register against the copy of the SDK it is run against.

(paraphrased some of those from an internal convo with @lukehoban)

**Comment by harryttd** [comment] 2021-11-09 01:55
I'm finding that the only resources being handled by the registerStackTransformations func is mainly vpc and aws:ec2 resources. I have iam policies being created, and they don't show when logging the args of the registerStackTransformations callback.

**Closed** 2022-06-30 10:04 UTC
Labels: kind/bug, kind/question, language/javascript, area/core, customer/feedback
