### ISSUE TITLE
pulumi convert --from terraform does not work

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi#16183] opened 2024-05-13 08:54 UTC
### What happened?

similar to #13866 

```
pulumi convert --from terraform --language typescript --out pulumi
Converting from terraform...
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-kms/locals.tf:2,15-91: Function not yet implemented; Function contains not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-kms/locals.tf:3,15-56: Function not yet implemented; Function contains not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-kms/main.tf:5,28-39: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-kms/main.tf:5,12-8,5: Function not yet implemented; Function templatefile not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-kms/main.tf:14,19-53: Function not yet implemented; Function contains not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-s3/locals.tf:14,26-71: Function not yet implemented; Function contains not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-s3/locals.tf:21,10-24,5: Function not yet implemented; Function merge not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-s3/main.tf:54,28-39: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-s3/main.tf:54,12-60,5: Function not yet implemented; Function templatefile not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-iam/main.tf:3,40-51: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-iam/main.tf:3,24-6,5: Function not yet implemented; Function templatefile not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-iam/main.tf:12,28-39: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-iam/main.tf:12,12-20,5: Function not yet implemented; Function templatefile not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:4,75-86: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:4,64-126: Function not yet implemented; Function fileset not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:4,145-156: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:7,69-80: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:7,58-95: Function not yet implemented; Function fileset not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:7,114-125: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:10,43-54: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:16,18-29: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:17,9-20: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:21,29-40: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:24,26-37: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:34,20-31: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:33,20-31: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:56,29-59: Function not yet implemented; Function tostring not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:57,29-62: Function not yet implemented; Function tostring not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:61,29-56: Function not yet implemented; Function tostring not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:62,29-59: Function not yet implemented; Function tostring not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-lambda/main.tf:81,14-54: Function not yet implemented; Function toset not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-acm/main.tf:1,1-45: converting create_before_destroy lifecycle hook is not supported;
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-step-function/locals.tf:2,26-62: Function not yet implemented; Function contains not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-step-function/main.tf:8,32-43: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/modules/terraform-aws-ca-step-function/main.tf:8,16-14,5: Function not yet implemented; Function templatefile not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/main.tf:74,14-40: Function not yet implemented; Function toset not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/main.tf:80,21-29: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/main.tf:81,29-37: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/main.tf:87,14-34: Function not yet implemented; Function toset not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/main.tf:93,21-29: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/main.tf:94,29-37: Terraform input not yet implemented; path
warning: <REDACTED>._/tf2pu/terraform-aws-ca/outputs.tf:7,17-49: Function not yet implemented; Function contains not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/outputs.tf:12,17-49: Function not yet implemented; Function contains not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/outputs.tf:17,17-49: Function not yet implemented; Function contains not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/outputs.tf:22,17-49: Function not yet implemented; Function contains not yet implemented
warning: <REDACTED>._/tf2pu/terraform-aws-ca/outputs.tf:27,17-49: Function not yet implemented; Function contains not yet implemented
Converting to nodejs...
================================================================================
The Pulumi CLI encountered a code generation error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.116.0
error: main.pp:30,1-40,2: circular reference;
error: could not generate output program

```

### Example

```
pulumi convert --from terraform --language typescript --out pulumi
Converting from terraform...
warning: <REDACTED>._/tf2pu/terraform-aws-ca
```

### Output of `pulumi about`

CLI
Version      3.116.0
Go Version   go1.22.2
Go Compiler  gc

Host
OS       darwin
Version  14.4.1
Arch     arm64

Pulumi locates its logs in /var/folders/79/bvt24ns10_n58z24g_klmhmm0000gn/T/ by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from <REDACTED>._/tf2pu/terraform-aws-ca). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Could not access the backend: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2024-05-14 06:53
Hi @1oglop1, thanks for opening the issue and sorry for the trouble. The `circular reference` issue is a known issue. I'm going to close this as a duplicate of #13581.

In the meantime, you may be able to workaround this by temporarily commenting out any circular references in your TF code. Then do the conversion to get it to succeed. Then go back and manually fix it up to make it work.

**Closed by justinvp** 2024-05-14 06:53 UTC
Labels: kind/bug, area/codegen, resolution/duplicate
