### ISSUE TITLE
Unable to output a value with a single backslash

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5076] opened 2020-07-29 14:43 UTC
When trying to output a string with a single backslash, `pulumi` seems to apply its own escaping to outputs and is turning `\` into `\\`.

I've tested this across TypeScript, CSharp, and Python and get the same results.

#### Code
```ts
import * as pulumi from "@pulumi/pulumi";

const region = "us-west-2";
const bucket = "foo-bar";

export let x = `\\\\${region}\\${bucket}`;
console.log(`X: ${x}`);

export let y = pulumi.interpolate`\\\\${region}\\${bucket}`;
y.apply(y => console.log(`Y: ${y}`));

export let z = "\\\\" + region + "\\" + bucket;
console.log(`Z: ${z}`);
```

#### Output
```
Diagnostics:
  pulumi:pulumi:Stack (interp-dev):
    X: \\us-west-2\foo-bar
    Z: \\us-west-2\foo-bar
    Y: \\us-west-2\foo-bar
Outputs:
    x: "\\\\us-west-2\\foo-bar"
    y: "\\\\us-west-2\\foo-bar"
    z: "\\\\us-west-2\\foo-bar"
```

**Comment by fa-bwilliams** [comment] 2023-05-02 20:09
This is still not fixed. /smh

**Comment by abhinav** [comment] 2023-05-02 20:25
@clstokes @fa-bwilliams 
Pulumi is not transforming the output.
This is just an artifact of the output being YAML-encoded.

The actual value is still:

```
\\us-west-2\foo-bar
```

You can verify this by looking at the stack output:

```
% pulumi stack output
Current stack outputs (3):
    OUTPUT  VALUE
    x       \\us-west-2\foo-bar
    y       \\us-west-2\foo-bar
    z       \\us-west-2\foo-bar
```

You can also get a JSON-encoded version which will escape the `\` symbols,
and get the actual value with a tool like jq.

```
% pulumi stack output --json
{
  "x": "\\\\us-west-2\\foo-bar",
  "y": "\\\\us-west-2\\foo-bar",
  "z": "\\\\us-west-2\\foo-bar"
}

% pulumi stack output --json | jq -r .x
\\us-west-2\foo-bar
```

If you were to consume this value from another stack, for example, it would receive the original input value:

```typescript
import * as pulumi from "@pulumi/pulumi";

export = async() => {
	const stackRef = new pulumi.StackReference("organization/pu-5076/dev")
	const got = (await stackRef.getOutputDetails("x")).value;
	const want = "\\\\us-west-2\\foo-bar";

	if (got !== want) {
		throw new Error(`got: ${got}, want: ${want}`);
	}

	console.log("success: got: %s, want: %s", got, want);
}
```

This will print:

```
Diagnostics:
  pulumi:pulumi:Stack (consumer-dev):
    success: got: \\us-west-2\foo-bar, want: \\us-west-2\foo-bar
```

**Comment by abhinav** [comment] 2023-05-02 21:06
Closing this since this is by design.
Please feel free to leave a comment or re-open if you have any questions.
Thanks!

**Closed by abhinav** 2023-05-02 21:06 UTC
Labels: kind/bug, area/cli, resolution/by-design
