### ISSUE TITLE
Dynamic resource lost its outputs during pulumi version updates

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi#3002] opened 2019-07-30 17:15 UTC
I have a dynamic resource (code below) which is designed to generate a value and store that value in the stack state forevermore. 

Today I upgraded from 0.17.26 to 0.17.27 and the outputs were blanked out such that my calls to `(new PartnerToken("test")).token` started returning `undefined.undefined` and redeployed all dependent resources.

The only difference I know of was for the final deployment of .26 we used our ubuntu CI server and for .27 I ran the update on windows (we maintain the stack state on git).

Thanks a lot

```tyepscript
import * as hashjs from "hash.js";
import * as pulumi from "@pulumi/pulumi";
import * as crypto from "crypto";
import { CreateResult } from "@pulumi/pulumi/dynamic";

export type PartnerTokenResult = {
    tokenId: string;
    tokenValue: string;
}

export const generatePartnerToken = (): PartnerTokenResult => {

    const entropyLength = 20;
    const tokenIdLength = 4;

    var bytes = crypto.randomBytes(20);

    var tokenIdbytes = bytes.slice(0, tokenIdLength);
    var tokenValuebytes = bytes.slice(tokenIdLength, entropyLength);

    var tokenId = tokenIdbytes.toString('hex');
    var tokenValue = hashjs.sha256().update(tokenValuebytes).digest("hex").slice(0, 32);

    return ({
        tokenId: tokenId,
        tokenValue: tokenValue
    });
}

export class PartnerTokenProvider implements pulumi.dynamic.ResourceProvider {
    async create(_: any): Promise<CreateResult> {
        var token = generatePartnerToken();
        return { id: token.tokenId, outs: token };
    }
}

export default class PartnerToken extends pulumi.dynamic.Resource {

    public readonly tokenId: pulumi.Output<string>;
    public readonly tokenValue: pulumi.Output<string>;
    get token(): pulumi.Output<string> { return pulumi.interpolate`${this.tokenId}.${this.tokenValue}`; }

    constructor(name: string, args: {} = {}, opts?: pulumi.CustomResourceOptions) {
        super(new PartnerTokenProvider(), name, { ...args, tokenId: undefined, tokenValue: undefined }, opts);
    }
}
```

**Comment by oliverholliday** [comment] 2019-07-30 17:41
I've tried to reproduce this in a new local stack and I can't which leads me to believe it's related to our CI running sometimes on windows and sometimes on ubuntu. Is that plausible?

**Comment by oliverholliday** [comment] 2019-07-30 17:50
Another thing that I've noticed is in my local .pulumi/history folder between the .16 to .21 update I have 3 x.checkpoint.json files which don't list any resources, yet all my non-dynamic resources weren't deleted. Is that related or likely a red herring?

**Comment by oliverholliday** [comment] 2019-07-30 18:07
I've extracted the relevant parts from our checkpoint files showing one of the resources and the overall stack outputs. The dnsPrefix stack outputs are generated by another dynamic resource but which only stores data in the .id field - as you can see from the stable values it wasn't affected.

sandbox01-apps-1564484369659380220.checkpoint.json on Ubuntu CI server
```
{
    "version": 3,
    "checkpoint": {
        "stack": "sandbox01-apps",
        "latest": {
            "manifest": {
                "time": "2019-07-30T10:59:29.508600955Z",
                "magic": "2c373ef2ae4cf5fe104117e95424664634be518ba9df6a97645e9a99338706f8",
                "version": "v0.17.26"
            },
            "secrets_providers": {
                "type": "passphrase",
                "state": {
                    "salt": "v1:qrKPz3rRJKg=:v1:uvWssgZ2owKMGxzS:3a16rC2+j5y47oXbttSDpceqHStoZA=="
                }
            },
            "resources": [
                {
                    "urn": "urn:pulumi:sandbox01-apps::sandbox01-apps::pulumi:pulumi:Stack::sandbox01-apps-sandbox01-apps",
                    "custom": false,
                    "type": "pulumi:pulumi:Stack",
                    "outputs": {
                        "default": {
                            "ccv": {
                                "dnsPrefix": "pgtkim",
                                "partnerToken": "173e97e9.1d574b21bfe6a8afbbe59b5be37b68a2"
                            },
                            "gbx": {
                                "dnsPrefix": "pbthob",
                                "partnerToken": "d6be9033.75755c0aa3a165733e5f539b077c6f62"
                            },
                            "thx": {
                                "dnsPrefix": "wgvalq",
                                "partnerToken": "23b17233.a114a0649f98156766150f96e39810b6"
                            }
                        }
                    },
                    "customTimeouts": {
                        "Create": 0,
                        "Update": 0,
                        "Delete": 0
                    }
                },
                {
                    "urn": "urn:pulumi:sandbox01-apps::sandbox01-apps::pulumi-nodejs:dynamic:Resource::gbx-token",
                    "custom": true,
                    "id": "d6be9033",
                    "type": "pulumi-nodejs:dynamic:Resource",
                    "inputs": {
                        "__provider": "exports.handler = __f0;\n\nvar __provider_proto = {};\n__f1.prototype = __provider_proto;\nObject.defineProperty(__provider_proto, \"constructor\", { configurable: true, writable: true, value: __f1 });\nvar __exports = {generatePartnerToken: __f4};\nObject.defineProperty(__provider_proto, \"create\", { configurable: true, writable: true, value: __f2 });\nvar __provider = Object.create(__provider_proto);\n\nfunction __f1() {\n  return (function() {\n    with({  }) {\n\nreturn function /*constructor*/() { };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f3(__0, __1, __2, __3) {\n  return (function() {\n    with({  }) {\n\nreturn function (thisArg, _arguments, P, generator) {\n    return new (P || (P = Promise))(function (resolve, reject) {\n        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }\n        function rejected(value) { try { step(generator[\"throw\"](value)); } catch (e) { reject(e); } }\n        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }\n        step((generator = generator.apply(thisArg, _arguments || [])).next());\n    });\n};\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f4() {\n  return (function() {\n    with({ crypto: require(\"crypto\"), hashjs: require(\"hash.js/lib/hash.js\") }) {\n\nreturn () =\u003e {\n    const entropyLength = 20;\n    const tokenIdLength = 4;\n    var bytes = crypto.randomBytes(20);\n    var tokenIdbytes = bytes.slice(0, tokenIdLength);\n    var tokenValuebytes = bytes.slice(tokenIdLength, entropyLength);\n    var tokenId = tokenIdbytes.toString('hex');\n    var tokenValue = hashjs.sha256().update(tokenValuebytes).digest(\"hex\").slice(0, 32);\n    return ({\n        tokenId: tokenId,\n        tokenValue: tokenValue\n    });\n};\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f2(__0) {\n  return (function() {\n    with({ __awaiter: __f3, exports: __exports }) {\n\nreturn function /*create*/(_) {\n        return __awaiter(this, void 0, void 0, function* () {\n            var token = exports.generatePartnerToken();\n            return { id: token.tokenId, outs: token };\n        });\n    };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f0() {\n  return (function() {\n    with({ provider: __provider }) {\n\nreturn () =\u003e provider;\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n"
                    },
                    "outputs": {
                        "__provider": "exports.handler = __f0;\n\nvar __provider_proto = {};\n__f1.prototype = __provider_proto;\nObject.defineProperty(__provider_proto, \"constructor\", { configurable: true, writable: true, value: __f1 });\nvar __exports = {generatePartnerToken: __f4};\nObject.defineProperty(__provider_proto, \"create\", { configurable: true, writable: true, value: __f2 });\nvar __provider = Object.create(__provider_proto);\n\nfunction __f1() {\n  return (function() {\n    with({  }) {\n\nreturn function /*constructor*/() { };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f3(__0, __1, __2, __3) {\n  return (function() {\n    with({  }) {\n\nreturn function (thisArg, _arguments, P, generator) {\n    return new (P || (P = Promise))(function (resolve, reject) {\n        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }\n        function rejected(value) { try { step(generator[\"throw\"](value)); } catch (e) { reject(e); } }\n        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }\n        step((generator = generator.apply(thisArg, _arguments || [])).next());\n    });\n};\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f4() {\n  return (function() {\n    with({ crypto: require(\"crypto\"), hashjs: require(\"hash.js/lib/hash.js\") }) {\n\nreturn () =\u003e {\n    const entropyLength = 20;\n    const tokenIdLength = 4;\n    var bytes = crypto.randomBytes(20);\n    var tokenIdbytes = bytes.slice(0, tokenIdLength);\n    var tokenValuebytes = bytes.slice(tokenIdLength, entropyLength);\n    var tokenId = tokenIdbytes.toString('hex');\n    var tokenValue = hashjs.sha256().update(tokenValuebytes).digest(\"hex\").slice(0, 32);\n    return ({\n        tokenId: tokenId,\n        tokenValue: tokenValue\n    });\n};\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f2(__0) {\n  return (function() {\n    with({ __awaiter: __f3, exports: __exports }) {\n\nreturn function /*create*/(_) {\n        return __awaiter(this, void 0, void 0, function* () {\n            var token = exports.generatePartnerToken();\n            return { id: token.tokenId, outs: token };\n        });\n    };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f0() {\n  return (function() {\n    with({ provider: __provider }) {\n\nreturn () =\u003e provider;\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n",
                        "tokenId": "d6be9033",
                        "tokenValue": "75755c0aa3a165733e5f539b077c6f62"
                    },
                    "parent": "urn:pulumi:sandbox01-apps::sandbox01-apps::pulumi:pulumi:Stack::sandbox01-apps-sandbox01-apps",
                    "provider": "urn:pulumi:sandbox01-apps::sandbox01-apps::pulumi:providers:pulumi-nodejs::default::83a523a9-5421-4b98-8bf8-aeea1d4a695a",
                    "propertyDependencies": {
                        "__provider": null
                    },
                    "customTimeouts": {
                        "Create": 0,
                        "Update": 0,
                        "Delete": 0
                    }
                },
```

sandbox01-apps-1564489949496578800.checkpoint.json ran locally on Windows
```
{
    "version": 3,
    "checkpoint": {
        "stack": "sandbox01-apps",
        "latest": {
            "manifest": {
                "time": "2019-07-30T13:32:29.2777135+01:00",
                "magic": "0c50563722bf294be98c718619d35c1ec948ed39ac65c47c58a3be789edae144",
                "version": "v0.17.27"
            },
            "secrets_providers": {
                "type": "passphrase",
                "state": {
                    "salt": "v1:qrKPz3rRJKg=:v1:uvWssgZ2owKMGxzS:3a16rC2+j5y47oXbttSDpceqHStoZA=="
                }
            },
            "resources": [
                {
                    "urn": "urn:pulumi:sandbox01-apps::sandbox01-apps::pulumi:pulumi:Stack::sandbox01-apps-sandbox01-apps",
                    "custom": false,
                    "type": "pulumi:pulumi:Stack",
                    "outputs": {
                        "default": {
                            "ccv": {
                                "dnsPrefix": "pgtkim",
                                "partnerToken": "undefined.undefined"
                            },
                            "gbx": {
                                "dnsPrefix": "pbthob",
                                "partnerToken": "undefined.undefined"
                            },
                            "thx": {
                                "dnsPrefix": "wgvalq",
                                "partnerToken": "undefined.undefined"
                            }
                        }
                    },
                    "customTimeouts": {
                        "Create": 0,
                        "Update": 0,
                        "Delete": 0
                    }
                },
                {
                    "urn": "urn:pulumi:sandbox01-apps::sandbox01-apps::pulumi-nodejs:dynamic:Resource::gbx-token",
                    "custom": true,
                    "id": "d6be9033",
                    "type": "pulumi-nodejs:dynamic:Resource",
                    "inputs": {
                        "__provider": "exports.handler = __f0;\n\nvar __provider_proto = {};\n__f1.prototype = __provider_proto;\nObject.defineProperty(__provider_proto, \"constructor\", { configurable: true, writable: true, value: __f1 });\nvar __exports = {generatePartnerToken: __f4};\nObject.defineProperty(__provider_proto, \"create\", { configurable: true, writable: true, value: __f2 });\nvar __provider = Object.create(__provider_proto);\n\nfunction __f1() {\n  return (function() {\n    with({  }) {\n\nreturn function /*constructor*/() { };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f3(__0, __1, __2, __3) {\n  return (function() {\n    with({  }) {\n\nreturn function (thisArg, _arguments, P, generator) {\r\n    return new (P || (P = Promise))(function (resolve, reject) {\r\n        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }\r\n        function rejected(value) { try { step(generator[\"throw\"](value)); } catch (e) { reject(e); } }\r\n        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }\r\n        step((generator = generator.apply(thisArg, _arguments || [])).next());\r\n    });\r\n};\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f4() {\n  return (function() {\n    with({ crypto: require(\"crypto\"), hashjs: require(\"hash.js/lib/hash.js\") }) {\n\nreturn () =\u003e {\r\n    const entropyLength = 20;\r\n    const tokenIdLength = 4;\r\n    var bytes = crypto.randomBytes(20);\r\n    var tokenIdbytes = bytes.slice(0, tokenIdLength);\r\n    var tokenValuebytes = bytes.slice(tokenIdLength, entropyLength);\r\n    var tokenId = tokenIdbytes.toString('hex');\r\n    var tokenValue = hashjs.sha256().update(tokenValuebytes).digest(\"hex\").slice(0, 32);\r\n    return ({\r\n        tokenId: tokenId,\r\n        tokenValue: tokenValue\r\n    });\r\n};\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f2(__0) {\n  return (function() {\n    with({ __awaiter: __f3, exports: __exports }) {\n\nreturn function /*create*/(_) {\r\n        return __awaiter(this, void 0, void 0, function* () {\r\n            var token = exports.generatePartnerToken();\r\n            return { id: token.tokenId, outs: token };\r\n        });\r\n    };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f0() {\n  return (function() {\n    with({ provider: __provider }) {\n\nreturn () =\u003e provider;\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n"
                    },
                    "outputs": {
                        "__provider": "exports.handler = __f0;\n\nvar __provider_proto = {};\n__f1.prototype = __provider_proto;\nObject.defineProperty(__provider_proto, \"constructor\", { configurable: true, writable: true, value: __f1 });\nvar __exports = {generatePartnerToken: __f4};\nObject.defineProperty(__provider_proto, \"create\", { configurable: true, writable: true, value: __f2 });\nvar __provider = Object.create(__provider_proto);\n\nfunction __f1() {\n  return (function() {\n    with({  }) {\n\nreturn function /*constructor*/() { };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f3(__0, __1, __2, __3) {\n  return (function() {\n    with({  }) {\n\nreturn function (thisArg, _arguments, P, generator) {\r\n    return new (P || (P = Promise))(function (resolve, reject) {\r\n        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }\r\n        function rejected(value) { try { step(generator[\"throw\"](value)); } catch (e) { reject(e); } }\r\n        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }\r\n        step((generator = generator.apply(thisArg, _arguments || [])).next());\r\n    });\r\n};\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f4() {\n  return (function() {\n    with({ crypto: require(\"crypto\"), hashjs: require(\"hash.js/lib/hash.js\") }) {\n\nreturn () =\u003e {\r\n    const entropyLength = 20;\r\n    const tokenIdLength = 4;\r\n    var bytes = crypto.randomBytes(20);\r\n    var tokenIdbytes = bytes.slice(0, tokenIdLength);\r\n    var tokenValuebytes = bytes.slice(tokenIdLength, entropyLength);\r\n    var tokenId = tokenIdbytes.toString('hex');\r\n    var tokenValue = hashjs.sha256().update(tokenValuebytes).digest(\"hex\").slice(0, 32);\r\n    return ({\r\n        tokenId: tokenId,\r\n        tokenValue: tokenValue\r\n    });\r\n};\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f2(__0) {\n  return (function() {\n    with({ __awaiter: __f3, exports: __exports }) {\n\nreturn function /*create*/(_) {\r\n        return __awaiter(this, void 0, void 0, function* () {\r\n            var token = exports.generatePartnerToken();\r\n            return { id: token.tokenId, outs: token };\r\n        });\r\n    };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f0() {\n  return (function() {\n    with({ provider: __provider }) {\n\nreturn () =\u003e provider;\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n"
                    },
                    "parent": "urn:pulumi:sandbox01-apps::sandbox01-apps::pulumi:pulumi:Stack::sandbox01-apps-sandbox01-apps",
                    "provider": "urn:pulumi:sandbox01-apps::sandbox01-apps::pulumi:providers:pulumi-nodejs::default::83a523a9-5421-4b98-8bf8-aeea1d4a695a",
                    "propertyDependencies": {
                        "__provider": null
                    },
                    "customTimeouts": {
                        "Create": 0,
                        "Update": 0,
                        "Delete": 0
                    }
                },
```

**Comment by ellismg** [comment] 2019-07-30 18:10
> Today I upgraded from 0.17.26 to 0.17.27 and the outputs were blanked out such that my calls to (new PartnerToken("test")).token started returning undefined.undefined and redeployed all dependent resources.

Did you upgrade the CLI version or the version of `@pulumi/pulumi` you depend on (or both?).  Do you use a lock file to ensure you are tied to a specific version of the `@pulumi/pulumi` package, and if so do you know what version that is?

**Comment by oliverholliday** [comment] 2019-07-30 18:10
I've tried to reproduce the issue in a new stack (https://app.pulumi.com/olliholliday/pulumi-test/dev) but couldn't reproduce it just doing version upgrades on windows.

**Comment by oliverholliday** [comment] 2019-07-30 18:23
Our CI that ran the first update above had @pulumi/pulumi: 0.17.27 but the 0.17.26 binary.

My local windows machine has 0.17.27 version of the binary.

**Comment by oliverholliday** [comment] 2019-07-30 18:34
I've just noticed that the windows serialised __provider has \r\n and the ubuntu one has \n. 

It's likely my git config is fiddling with those on checkout but it seems to me it could be related to the issue.

**Comment by ellismg** [comment] 2019-07-30 19:31
While I'm certain there is likely to be an issue here (and I suspect you are correct in your hunch that it is related to line endings across platforms and there interactions with serialized code for a function), one thing to note is that for this specific case you could decide to stop using a dynamic provider for this specific case.  We now have the `@pulumi/random` package, which allows you to generate random numbers once and store them in the checkpoint, as your dynamic provider is doing here.

**Comment by ellismg** [comment] 2019-07-30 19:33
@CyrusNajmabadi is this something you could take a look at?  It may be interesting to look at the behavior of a dynamic provider when you first do an update on Windows, and then do a future update on *nix to see how the serialized code changes, due to line ending issues?

**Comment by ellismg** [comment] 2019-08-05 20:24
Adding the Q3 Label - Let's take a brief amount of time to understand if moving between windows and *nix when using the dynamic provider provides a reasonable experience, via some manual directed testing when storing state with the Pulumi service.  If there's problems there, let's fix them, and lets defer any other work here (that my be due to storing state in git and having autocrlf rules applied) for a later milestone.

**Comment by CyrusNajmabadi** [comment] 2019-08-12 23:03
Hrmm..  I may need more information from you @oliverholliday .  I've been unable to repro this locally.  The part that is missing is this bit:

> I've extracted the relevant parts from our checkpoint files showing one of the resources and the overall stack outputs. The dnsPrefix stack outputs are generated by another dynamic resource but which only stores data in the .id field - as you can see from the stable values it wasn't affected.

Just so my repro code is as close to yours as possible, could you show me your code that interacts with these dynamic providers and which finally exports the ccv, gbx and thx values?  I just want to make sure i'm not doing something obviously different from you.

Once i get that, i can try to repro again including all the steps of upgrading packages.  Thanks!

**Comment by lukehoban** [comment] 2019-08-21 18:01
@oliverholliday Closing this out for now as we've been unable to repro.  But we'd love to look into it more if you can provide more details (or if anyone else sees a similar issue).  Let us know and we'll reopen.

**Closed by lukehoban** 2019-08-21 18:01 UTC
Labels: area/providers, kind/bug

**Comment by JakeGinnivan** [comment] 2021-05-05 00:29
Hey @lukehoban,

I can reproduce this, we had been using webpack to build Pulumi (to resolve modules in the same repo) and just switching back to the native ts-node approach using ts-config-paths instead.

This causes the code in __provider to change and when it does the outputs for the resource get cleared. My work around is to export the state of the target stack before the switch, overwrite the __provider from a stack which has been updated. Then I can safely up without the outputs getting cleared.

I have been meaning to write the blog post about this particular dynamic provider so I can do that today so you have access to the source of the provider in case it's something to do with the way the provider is written in addition to changing the way it's compiled.

**Comment by JakeGinnivan** [comment] 2021-05-05 01:55
For reference the provider under outputs has changed from

```
"__provider": "exports.handler = __f0;\n\n__getModuleExports.arguments = null;\n__getModuleExports.caller = null;\n__getModuleExports.a = require(\"aws-sdk/clients/elbv2.js\");\n__0_getModuleExports.arguments = null;\n__0_getModuleExports.caller = null;\n__0_getModuleExports.a = require(\"aws-sdk/lib/node_loader.js\");\nvar __pulumi_pulumi__WEBPACK_IMPORTED_MODULE_0__ = {log: require(\"@pulumi/pulumi/log/index.js\")};\n__1_getModuleExports.arguments = null;\n__1_getModuleExports.caller = null;\n__1_getModuleExports.a = require(\"cuid/index.js\");\nvar __provider = {create: __f1};\n\nfunction __getModuleExports() {\n  return (function() {\n    with({ module: require(\"aws-sdk/clients/elbv2.js\"), getModuleExports: __getModuleExports }) {\n\nreturn function /*getModuleExports*/() { return module; };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __0_getModuleExports() {\n  return (function() {\n    with({ module: require(\"aws-sdk/lib/node_loader.js\"), getModuleExports: __0_getModuleExports }) {\n\nreturn function /*getModuleExports*/() { return module; };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __1_getModuleExports() {\n  return (function() {\n    with({ module: require(\"cuid/index.js\"), getModuleExports: __1_getModuleExports }) {\n\nreturn function /*getModuleExports*/() { return module; };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f1(__0) {\n  return (function() {\n    with({ aws_sdk_clients_elbv2__WEBPACK_IMPORTED_MODULE_2___default: __getModuleExports, aws_sdk__WEBPACK_IMPORTED_MODULE_3___default: __0_getModuleExports, _pulumi_pulumi__WEBPACK_IMPORTED_MODULE_0__: __pulumi_pulumi__WEBPACK_IMPORTED_MODULE_0__, cuid__WEBPACK_IMPORTED_MODULE_1___default: __1_getModuleExports }) {\n\nreturn async function /*create*/({ awsRegion, assumeRole, loadBalancerArnsToCheck, }) {\n        var _a, _b;\n        const elb = new aws_sdk_clients_elbv2__WEBPACK_IMPORTED_MODULE_2___default.a({\n            region: awsRegion,\n            credentials: assumeRole\n                ? new aws_sdk__WEBPACK_IMPORTED_MODULE_3___default.a.TemporaryCredentials({\n                    RoleSessionName: 'LeastUsedLoadBalancer',\n                    RoleArn: assumeRole,\n                })\n                : undefined,\n        });\n        const listenerWithRules = await Promise.all(loadBalancerArnsToCheck.map(async (loadBalancer) =\u003e {\n            return {\n                loadBalancer,\n                rules: await elb\n                    .describeRules({\n                    ListenerArn: loadBalancer.webListernerArn,\n                    PageSize: 100,\n                })\n                    .promise(),\n            };\n        }));\n        const sorted = listenerWithRules.sort((a, b) =\u003e {\n            var _a, _b;\n            return (((_a = a.rules.Rules) === null || _a === void 0 ? void 0 : _a.length) || 0) - (((_b = b.rules.Rules) === null || _b === void 0 ? void 0 : _b.length) || 0);\n        });\n        _pulumi_pulumi__WEBPACK_IMPORTED_MODULE_0__[\"log\"].info(`Load balancers:\n\n${sorted.map((item) =\u003e {\n            var _a;\n            return `${item.loadBalancer.albArn}: ${((_a = item.rules.Rules) === null || _a === void 0 ? void 0 : _a.length) || 'unknown rules length'}\n`;\n        })}`);\n        _pulumi_pulumi__WEBPACK_IMPORTED_MODULE_0__[\"log\"].info(`Using load balancer: ${(_a = sorted[0]) === null || _a === void 0 ? void 0 : _a.loadBalancer.albArn}`);\n        return {\n            id: cuid__WEBPACK_IMPORTED_MODULE_1___default()(),\n            outs: {\n                loadBalancerToUse: (_b = sorted[0]) === null || _b === void 0 ? void 0 : _b.loadBalancer,\n            },\n        };\n    };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f0() {\n  return (function() {\n    with({ provider: __provider }) {\n\nreturn () =\u003e provider;\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n",
```

to


```
"__provider": "exports.handler = __f0;\n\nvar __elbv2_1 = {default: require(\"aws-sdk/clients/elbv2.js\")};\nvar __aws_sdk_1 = {default: require(\"aws-sdk/lib/node_loader.js\")};\nvar __pulumi = {log: require(\"@pulumi/pulumi/log/index.js\")};\nvar __cuid_1 = {default: require(\"cuid/index.js\")};\nvar __provider = {create: __f1};\n\nfunction __f1(__0) {\n  return (function() {\n    with({ tslib_1: require(\"tslib/tslib.js\"), elbv2_1: __elbv2_1, aws_sdk_1: __aws_sdk_1, pulumi: __pulumi, cuid_1: __cuid_1 }) {\n\nreturn function /*create*/({ awsRegion, assumeRole, loadBalancerArnsToCheck, }) {\n        var _a, _b;\n        return tslib_1.__awaiter(this, void 0, void 0, function* () {\n            const elb = new elbv2_1.default({\n                region: awsRegion,\n                credentials: assumeRole\n                    ? new aws_sdk_1.default.TemporaryCredentials({\n                        RoleSessionName: 'LeastUsedLoadBalancer',\n                        RoleArn: assumeRole,\n                    })\n                    : undefined,\n            });\n            const listenerWithRules = yield Promise.all(loadBalancerArnsToCheck.map((loadBalancer) =\u003e tslib_1.__awaiter(this, void 0, void 0, function* () {\n                return {\n                    loadBalancer,\n                    rules: yield elb\n                        .describeRules({\n                        ListenerArn: loadBalancer.webListernerArn,\n                        PageSize: 100,\n                    })\n                        .promise(),\n                };\n            })));\n            const sorted = listenerWithRules.sort((a, b) =\u003e {\n                var _a, _b;\n                return (((_a = a.rules.Rules) === null || _a === void 0 ? void 0 : _a.length) || 0) - (((_b = b.rules.Rules) === null || _b === void 0 ? void 0 : _b.length) || 0);\n            });\n            pulumi.log.info(`Load balancers:\n\n${sorted.map((item) =\u003e {\n                var _a;\n                return `${item.loadBalancer.albArn}: ${((_a = item.rules.Rules) === null || _a === void 0 ? void 0 : _a.length) || 'unknown rules length'}\n`;\n            })}`);\n            pulumi.log.info(`Using load balancer: ${(_a = sorted[0]) === null || _a === void 0 ? void 0 : _a.loadBalancer.albArn}`);\n            return {\n                id: cuid_1.default(),\n                outs: {\n                    loadBalancerToUse: (_b = sorted[0]) === null || _b === void 0 ? void 0 : _b.loadBalancer,\n                },\n            };\n        });\n    };\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n\nfunction __f0() {\n  return (function() {\n    with({ provider: __provider }) {\n\nreturn () =\u003e provider;\n\n    }\n  }).apply(undefined, undefined).apply(this, arguments);\n}\n",
```
