### ISSUE TITLE
"snapshot integrity failure" after a child resource has been destroyed in a previous incomplete destroy

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#17082] opened 2024-08-27 23:25 UTC
### What happened?

Customer is running into a "snapshot integrity failure":

> I've got a refresh on stack with a custom resource failing because one of its sub resources has been destroyed in a previous incomplete destroy
>
> The error I'm getting is:
> `error: getting snapshot: snapshot integrity failure; refusing to use it:
property dependency <aws.secretsmanager.Secret urn> (from property kmsKeyId) refers to missing resource`
> 
> In the stack state there is just the secret and the custom resource - the kms key was the first thing removed in a destroy I ran that was unsuccessful
> 
> the setup is
> ```typescript
>   constructor(
>     public name: string,
>     args?: SecretsResourceArgs,
>   ) {
>     const { argOpts } = args || {};
> 
>     super('foo:aws:resource-secrets', name, argOpts?.args, argOpts?.opts, argOpts?.remote);    
>     this.kmsKey = new aws.kms.Key(keyName, keyArgs, opts);
>     const kmsKeyId = this.kmsKey.id;
> 
>     this.secrets = new aws.secretsmanager.Secret(
>       name,
>       { kmsKeyId, ...args?.SecretArgs.args },
>       {
>         ...args?.SecretArgs.opts,
>         parent: this,
>       },
>     );
> 
>     this.registerOutputs({
>       secrets: this.secrets,
>       kmsKey: this.kmsKey,
>     });
> }
> ```
>
> I would have thought if it was aware of the dependency as its failing due to it but then not sure how the kms key got removed in a previous destroy before the secret did
and it is using the output of another resource

### Example

na

### Output of `pulumi about`

todo

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lunaris** [comment] 2024-09-23 11:43
Closing this after discussion since we are unable to reproduce/gather more data to reproduce and there is a chance it will have been fixed by one of the other recent fixes released in 3.133.0.

**Closed by lunaris** 2024-09-23 11:43 UTC
Labels: kind/bug, p1, resolution/no-repro, area/engine, impact/snapshot-integrity
