### ISSUE TITLE
Support Vercel.com provider

### ISSUE THREAD

**Issue by thanhtoan1196** [pulumi/pulumi#7723] opened 2021-08-09 08:56 UTC
## Affected feature

Support Vercel.com provider

**Comment by stack72** [comment] 2021-08-09 12:32
Hi @thanhtoan1196 

Thanks for the request here - I am going to close this out as a duplicate of https://github.com/pulumi/pulumi/issues/7615

You can track this request in that issue

Paul

**Closed by stack72** 2021-08-09 12:32 UTC
Labels: kind/enhancement, area/providers, resolution/duplicate
