### ISSUE TITLE
[sdk/go] exporting resources after calling`To[Resource]Output()` results in panic

### ISSUE THREAD

**Issue by alexlokshin** [pulumi/pulumi#7517] opened 2021-07-11 14:27 UTC
In GCP, I've created a network, a sub-network, registered a private IP, and trying to create a VPC connection. As a result, I always get a fatal error. Initially saw it with 3.6.0, same issue kept on occurring with 3.6.1.

## Steps to reproduce
1. Here's the Pulumi code I am trying to execute:
```go
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v5/go/gcp/compute"
	"github.com/pulumi/pulumi-gcp/sdk/v5/go/gcp/servicenetworking"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		myNetwork, err := compute.NewNetwork(ctx, "myNetwork", &compute.NetworkArgs{
			Name:                  pulumi.String("my-network"),
			AutoCreateSubnetworks: pulumi.Bool(false),
		})
		if err != nil {
			return err
		}

		ctx.Export("myNetwork", myNetwork.ID())

		mySubnetwork, err := compute.NewSubnetwork(ctx, "my-subnetwork", &compute.SubnetworkArgs{
			Name:        pulumi.String("container-subnetwork"),
			Description: pulumi.String("My little sub-network"),
			IpCidrRange: pulumi.String("10.100.0.0/24"),
			Region:      pulumi.String("us-central1"),
			Network:     myNetwork.ID(),
			SecondaryIpRanges: compute.SubnetworkSecondaryIpRangeArray{
				&compute.SubnetworkSecondaryIpRangeArgs{
					RangeName:   pulumi.String("range-1"),
					IpCidrRange: pulumi.String("172.30.0.0/16"),
				},
				&compute.SubnetworkSecondaryIpRangeArgs{
					RangeName:   pulumi.String("range-2"),
					IpCidrRange: pulumi.String("10.200.0.0/16"),
				},
			},
		}, pulumi.DependsOn([]pulumi.Resource{
			myNetwork,
		}))
		if err != nil {
			return err
		}

		ctx.Export("my-subnetwork", mySubnetwork.ID())

		dbPrivateRange, err := compute.NewGlobalAddress(ctx, "dbPrivateIpAddress", &compute.GlobalAddressArgs{
			Name:         pulumi.String("db-private-ip"),
			Purpose:      pulumi.String("VPC_PEERING"),
			AddressType:  pulumi.String("INTERNAL"),
			PrefixLength: pulumi.Int(16),
			Network:      myNetwork.ID(),
		})
		if err != nil {
			return err
		}
		ctx.Export("dbPrivateIpAddress", dbPrivateRange.Address.ToStringOutput())
		dbPrivateVpcConnection, err := servicenetworking.NewConnection(ctx, "dbPrivateVpcConnection", &servicenetworking.ConnectionArgs{
			Network: myNetwork.ID(),
			Service: pulumi.String("servicenetworking.googleapis.com"),
			ReservedPeeringRanges: pulumi.StringArray{
				dbPrivateRange.Name,
			},
		})
		if err != nil {
			return err
		}
		ctx.Export("dbPrivateVpcConnection", dbPrivateVpcConnection.ToConnectionOutput())

		return nil
	})
}

func toPulumiStringArray(arr []string) pulumi.StringArrayInput {
	var pulumiArr pulumi.StringArray
	for _, v := range arr {
		pulumiArr = append(pulumiArr, pulumi.String(v))
	}
	return pulumiArr
}

```
2. `pulumi up` causes the fatal error, even though all resources are created.

Expected: Successful completion
Actual: I get the fatal error:

```
Diagnostics:
  pulumi:pulumi:Stack (alexlokshin-dev):
    panic: fatal: An assertion has failed
    goroutine 89 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.1/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.1/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputAndDetermineSecret(0x1e0e300, 0xc0001b6580, 0x20a4920, 0x1ca3ce0, 0xc000611801, 0x109e5f2, 0x1cf1740, 0x1, 0xc0006118d8, 0x109ce25, ...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.1/go/pulumi/rpc.go:272 +0x36f0
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(0x1ea7f00, 0xc0000d0230, 0x20a4920, 0x1ca3ce0, 0x1ea7f01, 0xc0000d0230, 0x1cf1740, 0xc000028ea0, 0x94, 0x1, ...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.1/go/pulumi/rpc.go:170 +0x73
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputAndDetermineSecret(0x1d50760, 0xc00051a270, 0x20a4920, 0x1cccb40, 0xc0005b9e01, 0x178456f, 0x1da3ce0, 0xc0001ccac0, 0x20a4920, 0x1bee720, ...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.1/go/pulumi/rpc.go:358 +0x100a
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(0x1d50760, 0xc00051a270, 0x20a4920, 0x1ca3ce0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.1/go/pulumi/rpc.go:170 +0x73
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).RegisterResourceOutputs.func1(0xc0001e4000, 0x209da98, 0xc000524190, 0xc00051a270)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.1/go/pulumi/context.go:1169 +0x13c
    created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).RegisterResourceOutputs
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.6.1/go/pulumi/context.go:1156 +0x96
    exit status 2
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

**Comment by lukehoban** [comment] 2021-07-13 22:40
The callstack looks similar to (though not quite the same as?) https://github.com/pulumi/pulumi/issues/7504.

**Comment by emiliza** [comment] 2021-07-14 16:09
@alexlokshin can you try against 3.7.0 and let me know if you can still repro? If by chance it is related to 7504, we just released a fix for this yesterday

**Comment by alexlokshin** [comment] 2021-07-14 23:24
@emiliza I was able to reproduce in 3.7.0 as well.

```
  pulumi:pulumi:Stack (avsatum-dev):
    panic: fatal: An assertion has failed
    goroutine 44 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputAndDetermineSecret(0x1e5f3a0, 0xc0005a8280, 0x20c6340, 0x1cc1f00, 0xc0003f3801, 0x109e5f2, 0x1d0f960, 0x1, 0xc0003f3898, 0x109ce25, ...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/rpc.go:273 +0x3790
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(0x1ec66a0, 0xc00068e4d0, 0x20c6340, 0x1cc1f00, 0x1ec6601, 0xc00068e4d0, 0x1d0f960, 0xc00064ca80, 0x94, 0x1, ...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/rpc.go:171 +0x73
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputAndDetermineSecret(0x1d6ea40, 0xc000584780, 0x20c6340, 0x1cead60, 0xc000077e01, 0x1784aaf, 0x1dc1fc0, 0xc00053c250, 0x20c6340, 0x1c0c940, ...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/rpc.go:367 +0xf6a
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(0x1d6ea40, 0xc000584780, 0x20c6340, 0x1cc1f00, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/rpc.go:171 +0x73
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).RegisterResourceOutputs.func1(0xc000530140, 0x20c09b8, 0xc00013a150, 0xc000584780)
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/context.go:1400 +0x13d
    created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).RegisterResourceOutputs
        /Users/alexlokshin/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.7.0/go/pulumi/context.go:1387 +0x96
    exit status 2
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

**Comment by EvanBoyle** [comment] 2021-07-15 21:55
@alexlokshin If you remove the call to `ToConnectionOutput()` and export the resource directly you can work around the panic:

```go
ctx.Export("dbPrivateVpcConnection", dbPrivateVpcConnection)
```

However, that method should not panic in this context and we'll prepare a fix.

**Comment by EvanBoyle** [comment] 2021-07-15 23:58
This appears to repro for all resources:

A minimal repro:

```go
		myNetwork, err := compute.NewNetwork(ctx, "myNetwork", &compute.NetworkArgs{
			Name:                  pulumi.String("my-network"),
			AutoCreateSubnetworks: pulumi.Bool(false),
		})
		if err != nil {
			return err
		}

		ctx.Export("myNetwork", myNetwork.ToNetworkOutput())
```

So far, I've observed that the resource state on the URN attached to the resource is `nil`, which causes the URN to be unknown when it is awaited, thus the panic. Needs more investigation.

**Comment by EvanBoyle** [comment] 2021-07-16 00:43
Did some bisecting, and it looks like this has never worked. I checked all the way back to pulumi 2.0 where we added resource references.

**Comment by EvanBoyle** [comment] 2021-07-16 01:50
Altering the GCP SDK code to wait for the resource to wait for the URN does fixes the panic, but causes a resource reference to be emitted in the stack outputs rather than the full resource:

```diff
diff --git a/sdk/go/gcp/compute/network.go b/sdk/go/gcp/compute/network.go
index 09d22c615..8adc77050 100644
--- a/sdk/go/gcp/compute/network.go
+++ b/sdk/go/gcp/compute/network.go
@@ -320,7 +320,9 @@ func (*Network) ElementType() reflect.Type {
 }
 
 func (i *Network) ToNetworkOutput() NetworkOutput {
-       return i.ToNetworkOutputWithContext(context.Background())
+       return i.URN().ApplyT(func(u pulumi.URN) *Network {
+               return i
+       }).(NetworkOutput)
 }
 
 func (i *Network) ToNetworkOutputWithContext(ctx context.Context) NetworkOutput {
```

```
Outputs:
    myNetwork: {
        URN: "urn:pulumi:dev::gcppanic::gcp:compute/network:Network::myNetwork"
        ID : "projects/921927215178/global/networks/my-network"
        PackageVersion: ""
    }
```

**Comment by EvanBoyle** [comment] 2021-07-16 01:52
ResourcePointer outputs also appear to be broken:

```go
ctx.Export("myNetwork", myNetwork.ToNetworkPtrOutput())
```

Results in a type assertion panic:

```
  pulumi:pulumi:Stack (gcppanic-dev):
    panic: interface conversion: pulumi.Output is compute.NetworkOutput, not compute.NetworkPtrOutput
    goroutine 1 [running]:
    github.com/pulumi/pulumi-gcp/sdk/v5/go/gcp/compute.(*Network).ToNetworkPtrOutputWithContext(...)
    	/Users/evanboyle/go/src/github.com/pulumi/pulumi-gcp/sdk/go/gcp/compute/network.go:337
```

**Comment by EvanBoyle** [comment] 2021-07-16 02:18
This snippet is illustrative:

```
		ctx.Export("myNetwork", pulumi.All(myNetwork.ToNetworkOutput(), myNetwork.URN()).ApplyT(func(args []interface{}) *compute.Network {
			net := args[0].(*compute.Network)
			fmt.Println("net URN")
			fmt.Println(net.URN())
			return net
		}).(compute.NetworkOutput))
```

```
    net URN
    {<nil>}
```

**Comment by alexlokshin** [comment] 2021-07-19 15:05
Issue still exists in 3.7.1, workaround suggested by @EvanBoyle indeed works!

**Comment by emiliza** [comment] 2021-07-26 18:07
@pgavlin what's the intended design here?

**Comment by AaronFriel** [comment] 2022-02-24 22:52
This same panic documented above also occurs in this small Go program, involving an improper use of `pulumi.Any`. A smaller repro might be easier for future debugging.

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Create an AWS resource (S3 Bucket)
		bucket, err := s3.NewBucket(ctx, "my-bucket", nil)
		if err != nil {
			return err
		}

		ctx.Export("bucket", pulumi.Any(&bucket))
		return nil
	})
}
```

**Comment by hariprasadiit** [comment] 2022-08-03 16:50
facing the same problem. I'm using Typescript and Exporting the resource directly from the inline stack works, where as exporting the return value in object form panics

**Comment by lukehoban** [comment] 2022-08-03 18:32
I've confirmed that the original repro in https://github.com/pulumi/pulumi/issues/7517#issue-943879694 and the most recent repro in https://github.com/pulumi/pulumi/issues/7517#issuecomment-1050339921 both no longer panic.

I believe this was fixed in https://github.com/pulumi/pulumi/pull/9106.

@hariprasadiit It sounds like you are seeing an issue in TypeScript, which would be separate from this.  Could you open a new issue with details of the error you are seeing?

**Closed by lukehoban** 2022-08-03 18:32 UTC
Labels: kind/bug, impact/panic, resolution/fixed
