### ISSUE TITLE
Bulk import fails exits non-zero if 2 resources have the same name

### ISSUE THREAD

**Issue by denniswebb** [pulumi/pulumi#9116] opened 2022-03-04 15:29 UTC
- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We are migrating from CloudFormation to Pulumi. This requires importing a lot of resources. While using the bulk import feature of Pulumi, we are getting errors about resources having the same name, even though Pulumi supports this as long as the resource type is different.

A snippet of my import file to recreate this issue follows:

```json
{
  "nameTable": {
    "analytics-component": "urn:pulumi:dennis-webb-us-west-2::dennis-webb-enterprise::dennis-webb:modules:analytics::analytics",
    "analytics-component-analytics": "urn:pulumi:dennis-webb-us-west-2::dennis-webb-enterprise::dennis-webb:modules:analytics$dennis-webb:s3:bucket::analytics"
  },
  "resources": [
    {
      "type": "aws:s3/bucket:Bucket",
      "name": "analytics",
      "id": "dennis-webb-backend-analytics-analyticsbucket-1aqip8hsitkmw",
      "parent": "analytics-component-analytics"
    },
    {
      "type": "aws:athena/workgroup:Workgroup",
      "name": "analytics",
      "id": "PantherAnalyticsWorkGroup",
      "parent": "analytics-component"
    }
  ]
}
```

This is just a small portion of our app, coming from our **analytics** portion, hence the common naming.

The import actually succeeds, but the error is thrown afterwards and `pulumi` exits non-zero.

Below is a snippet of the output of the import and the error.

```
Resources:
    22 unchanged

Duration: 1s

error: internal error: Error: "analytics" already declared

  on anonymous.pp line 0:
   1: resource analytics "aws:s3/bucket:Bucket" {
```

If I import these in separate files, no error is thrown.  I have also experienced something similar if the **key** for an item in the `nameTable` is the same as a resource, leading me for now to add `-component` to the end of those entries to prevent an odd `circular reference` error from occurring.

### Steps to reproduce

1. Create an import file named `import.json` with the following contents:
```json
{
  "resources": [
    {
      "type": "random:index/randomInteger:RandomInteger",
      "name": "random",
      "id": "1,1,1"
    },
    {
      "type": "random:index/randomId:RandomId",
      "name": "random",
      "id": "test-pet"
    }
  ]
}
```
2. `pulumi import -f import.json`

Expected: Imports resources and exit 0
Actual: Imports resources, but exits non-0

**Comment by Frassle** [comment] 2022-03-04 16:20
Duplicate of https://github.com/pulumi/pulumi/issues/6032.

**Comment by lukehoban** [comment] 2022-03-04 17:12
Closing out as duplicate - and added an update on #6032.

**Closed by lukehoban** 2022-03-04 17:12 UTC
Labels: kind/bug, resolution/duplicate
