### ISSUE TITLE
Investigate reusing plugin process across steps

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi#13987] opened 2023-09-18 23:25 UTC
Investigation of https://github.com/pulumi/pulumi-aws/issues/2799 seems to indicate that we are waiting for a resource plugin to start 4 times during a normal `pulumi up`: before CheckConfig and Configure during preview, and then in both those places again for actual update. For larger providers this wait can actually get to be somewhat substantial (100's of ms), so it would be a noticeable improvement if we were able to reuse the running process.

**Comment by t0yv0** [comment] 2023-09-19 14:23
I've taken a look here and was able to reproduce. I modify pulumi-aws plugin to create random files in /tmp upon startup. I use examples/aws-ts-s3-folder.  I've verified that the example code does not use explicit providers which would start multiple instances of the plugin by design.

Here's the findings:

- using pulumi 3.7.0, pulumi up starts pulumi-resource-aws 2 times
- using pulumi 3.74.0, pulumi up starts pulumi-resoruce-aws 4 times 

I've not bisected this range yet but there is some regression that doubles the number of times plugins are started.

This normally is not a huge deal but this currently slows down pulumi-aws users because it turns out we do a fair amount of work on startup. On the providers side we need to look into moving this work so it only happens when needed say for the first gRPC call, or try some other schemes.

**Comment by Frassle** [comment] 2023-09-19 14:57
I'd expect it to start up twice, we assume provider processes are stateful and so can't be re-used between preview and up. Not sure why its spinning up two extra times.

**Comment by t0yv0** [comment] 2023-09-19 15:06
Yeah I think spinning up twice is what we want. This is not a terribly high priority ask since it sounds like we need to slim down cost of init anyway, but at some point going from 4 back to 2 is going to help everything across the board.

**Comment by mikhailshilkov** [comment] 2023-09-19 16:40
> This is not a terribly high priority ask

Well, it's one half of impact in https://github.com/pulumi/pulumi-aws/issues/2799 which is a P1... So it's a (P1)/2 :)

**Comment by Frassle** [comment] 2023-09-19 16:42
If it's easy for you to find which version started doing 4 loads that would help a lot.

**Comment by t0yv0** [comment] 2023-09-19 18:57
Yeah sure I can bisect quickly.

**Comment by t0yv0** [comment] 2023-09-19 21:02
Looks like I can't repro this reliably. I must have miscounted something in the repro setup. @mjeffryes do you have a good repro for N=4, I'm consistently hitting N=2 as expected now.

**Comment by mjeffryes** [comment] 2023-09-20 16:30
hmmm... I don't have a convenient repro handy yet. I was inferring from the trace. I'll see if I can come up with something more obvious.

**Comment by t0yv0** [comment] 2023-09-20 17:50
I've been injecting some effects like temples in provider main. Another utility to consider is q.Q but beware that q.Q clobbers itself when used from multiple concurrent processes.

**Comment by mjeffryes** [comment] 2023-09-20 18:45
I built a version of the provider that writes a timestamp to a file every time it starts and experimented a bit. What I've found so far is that the initial `pulumi up -f` only starts the provider once, but if I immediately run `pulumi up -f` a second time (to test and empty update), the provider is started twice. (and dropping `-f` doubles the count for both as you might expect.

**Comment by mjeffryes** [comment] 2023-09-20 18:57
Doesn't seem to be specific to empty updates, I see two provider binary starts for the second (and all subsequent) `pulumi up -f` regardless of whether there's anything to actually update.

**Comment by t0yv0** [comment] 2023-09-20 19:09
Yeah that's consistent with current Pulumi process model. Every invocation of `pulumi` starts provider process > 1 times. Once for every up/preview, and within those once for every explicit provider configuration (if you use explicit providers you get more of these). This is done because of state. The providers are stateful boxes and currently the only way we can isolate their states is by giving each provider its own process, which gets killed as soon as pulumi is done with it. 

Rearchitecting this is pretty significant scope  so I suggest we close this for now as cannot reproduce.

**Comment by t0yv0** [comment] 2023-09-20 19:10
I got a nice tool out of this https://github.com/t0yv0/pulumi-bisect - that's hopefully going to be useful later, but this feels like not a real bug but more works by design.

**Comment by Frassle** [comment] 2023-09-20 19:16
Agreed, this all sounds as by-design for now.

**Comment by mjeffryes** [comment] 2023-09-20 20:32
Maybe I'm misunderstanding the model for when providers are started, but I still think we're starting the provider more often than expected eg. here's a sample log file from a recent test:
```
before initial up
1695236067423
before empty up
1695236071443
1695236072364
after empty up
1695236074290
1695236075176
after non-empty up
1695236076550
1695236076970
```

that was produced by this script:
``` bash
#!/bin/bash

set -eu -o pipefail

export PULUMI_CONFIG_PASSPHRASE=""
mkdir -p state
pulumi login --cloud-url "file://$PWD/state"
pulumi stack select organization/test/test --create

echo before initial up > touched_file.txt
time pulumi up      -f --yes --tracing file:./cmd.trace

echo before empty up >> touched_file.txt
time pulumi up       -f --yes --tracing file:./cmd.trace

echo after empty up >> touched_file.txt

cp cmd.trace www/
time pulumi up       -f --yes --tracing file:./cmd.trace 
echo after non-empty up >> touched_file.txt

pulumi destroy  --yes
pulumi stack rm --yes
pulumi logout
rm -Rf "$PWD/state"
```

using an aws plugin that writes a timestamp to `touched_file.txt`

You can see in the log that the first `pulumi up -f` only launches the provider once, but every subsequent `pulumi up -f` launches the provider twice. I don't understand why the provider would need to be invoked an extra time for the subsequent updates, especially since the number of configure+ check config RPCs to the provider seems to be the same each time.

**Comment by Frassle** [comment] 2023-09-20 20:38
Oh your running with skip preview yeh that is odd, I'd expect it to only be needed once for that.

**Comment by mjeffryes** [comment] 2023-10-05 21:49
I've done a bit more analysis on the logs. Here's what I think is happening:

### For the first update (ie. no previous state, need to create everything):
1) Launch a new plugin and run CheckConfig:
```
I1004 17:00:31.441049    9284 log.go:80] Launching plugin 'aws (resource)' from '/Users/mjeffryes/workspace/pulumi/aws/bin/pulumi-resource-aws' with args: 127.0.0.1:50911
...
I1004 17:00:31.876099    9284 log.go:80] Provider[aws, 0x140004ea320].CheckConfig(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0) executing (#olds=0,#news=1)
```
2) CheckConfig succeeded, save the provider in the registry under the UnknownID
```
I1004 17:00:32.317486    9284 log.go:80] Provider[aws, 0x140004ea320].CheckConfig(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0) success: inputs=#5 failures=#0
I1004 17:00:32.317493    9284 log.go:80] setProvider(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9)
```
3) Provider is new so run the Create step, which loads the provider saved under the UnknownID and calls Configure
```
I1004 17:00:32.318444    9284 log.go:80] ProviderRegistry.Create(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0) executing (#news=5)
I1004 17:00:32.318448    9284 log.go:80] GetProvider(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9)
I1004 17:00:32.318452    9284 log.go:80] Provider[aws, 0x140004ea320].Configure() executing (#vars=5)
I1004 17:00:32.318463    9284 log.go:80] Marshaling property for RPC[Provider[aws, 0x140004ea320].Configure().inputs]: region={us-west-2}
```

### For the second update (where state already exists and we don't need to change anything):
1) Launch a new plugin and run CheckConfig
```
I1004 17:00:35.656634    9300 log.go:80] Launching plugin 'aws (resource)' from '/Users/mjeffryes/workspace/pulumi/aws/bin/pulumi-resource-aws' with args: 127.0.0.1:50937
...
I1004 17:00:36.093077    9300 log.go:80] Provider[aws, 0x140015fc230].CheckConfig(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0) executing (#olds=5,#news=1)
```
2) CheckConfig succeeded, save the provider in the registry under the UnknownID
```
I1004 17:00:36.536866    9300 log.go:80] Provider[aws, 0x140015fc230].CheckConfig(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0) success: inputs=#5 failures=#0
I1004 17:00:36.536887    9300 log.go:80] setProvider(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9)
```
3) Use the provider stored under UnknownID to DiffConfig
```
I1004 17:00:36.536896    9300 log.go:80] ProviderRegistry.Diff(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0,9681f9d5-cc02-43fc-a217-fc5aae82c42c): executing (#olds=5,#news=5)
I1004 17:00:36.536901    9300 log.go:80] GetProvider(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9)
I1004 17:00:36.536906    9300 log.go:80] Provider[aws, 0x140015fc230].DiffConfig(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0) executing (#olds=5,#news=5)
```
4) Diff Config indicates no change, look up the provider id from the state and try to use it for Configure step:
```
I1004 17:00:36.537491    9300 log.go:80] Provider[aws, 0x140015fc230].DiffConfig(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0) success: changes=0 #replaces=[] #stables=[] delbefrepl=false, diffs=#[]
I1004 17:00:36.537502    9300 log.go:80] ProviderRegistry.Diff(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0,9681f9d5-cc02-43fc-a217-fc5aae82c42c): executed (1, []resource.PropertyKey{})
I1004 17:00:36.537513    9300 log.go:80] Planner decided not to update 'urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0' after diff (same) (inputs=map[region:{us-west-2} skipCredentialsValidation:{false} skipMetadataApiCheck:{true} skipRegionValidation:{true} version:{6.1.0}])
I1004 17:00:36.537518    9300 log.go:80] Checking step same for urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0
I1004 17:00:36.537525    9300 log.go:80] StepExecutor worker(-2): worker received chain for execution
I1004 17:00:36.537543    9300 log.go:80] StepExecutor worker(-2): worker waiting for incoming chains
I1004 17:00:36.537548    9300 log.go:80] StepExecutor worker(1): launching oneshot worker
I1004 17:00:36.537567    9300 log.go:80] SnapshotManager: Beginning mutation for step `same` on resource `urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0`
I1004 17:00:36.537582    9300 log.go:80] StepExecutor worker(1): applying step same on urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0 (preview false)
I1004 17:00:36.537596    9300 log.go:80] Same(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0::9681f9d5-cc02-43fc-a217-fc5aae82c42c)
I1004 17:00:36.537599    9300 log.go:80] GetProvider(urn:pulumi:test::test::pulumi:providers:aws::default_6_1_0::9681f9d5-cc02-43fc-a217-fc5aae82c42c)
```
5) There's no plugin registered under the id from the state, so launch a new one, then start Configure:
```
I1004 17:00:36.537690    9300 log.go:80] Launching plugin 'aws (resource)' from '/Users/mjeffryes/workspace/pulumi/aws/bin/pulumi-resource-aws' with args: 127.0.0.1:50937
I1004 17:00:36.981373    9300 log.go:80] Provider[aws, 0x14001662550].GetPluginInfo() executing
I1004 17:00:36.983025    9300 log.go:80] Provider[aws, 0x14001662550].GetPluginInfo() success (#version=6.4.0-alpha.1696355760+d2289e40.dirty) success
I1004 17:00:36.983061    9300 log.go:80] Provider[aws, 0x14001662550].Configure() executing (#vars=5)
```


----

### Logs

First run of update -f (no previous state): [up_no_preview_no_state.log](https://github.com/pulumi/pulumi/files/12823454/up_no_preview_no_state.log)
Second run of update -f (state exists): 
[up_no_preview_with_state_no_change.log](https://github.com/pulumi/pulumi/files/12823455/up_no_preview_with_state_no_change.log)

**Comment by mjeffryes** [comment] 2023-10-05 23:18
I don't have all the context on the reasoning around when we relaunch the plugin, so I'm not sure the best way forward here. I can see two options:

1) The easiest thing would be to let the "Same" step fall back to the provider stored under the UnknownID when it fails to find one from the key in the state. This is a very local change and we do something like this in the Diff method (https://github.com/pulumi/pulumi/blob/2442c07cbe0e2c586031c349c824434e096f2eea/pkg/resource/deploy/providers/registry.go#L366-L366), but I don't know why we store the providers under different ids, to begin with so I'm not sure if this would be ok?

2) More difficult would be to store the provider created for CheckConfig and DiffConfig under the id read from the state. This seems tricky because it means looking at the state before CheckConfig.

**Comment by mikhailshilkov** [comment] 2023-10-06 11:42
@mjeffryes Do you think any of this has regressed recently, or has it always been like this?

**Comment by Frassle** [comment] 2023-10-06 12:57
> Do you think any of this has regressed recently, or has it always been like this?

This _might_ have changed in https://github.com/pulumi/pulumi/pull/12657, can take a look.

**Comment by Frassle** [comment] 2023-10-06 14:02
OK I don't think #12657 changed this, because that would have loaded it once for the old provider then loaded it again in Check. Sort of the opposite of what we do now. 

I agree it looks like we should be able to just re-use the one started by Check in Same, but there's some complexities here regarding replacements (where we need to Same and Create the same URN). But I think we can fix this.

**Closed** 2023-10-12 21:27 UTC
Labels: kind/bug, area/plugins
