### ISSUE TITLE
Suppress warning about expired trial or a cancelled subscription

### ISSUE THREAD

**Issue by cowwoc** [pulumi/pulumi#17758] opened 2024-11-12 20:24 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Please remove this warning or provide an option to suppress it:
> warning: Your Pulumi organization is on an expired trial or a canceled subscription. Update your subscription to maintain organization access: https://app.pulumi.com/.../settings/billing-usage

So long as I am using the free features of Pulumi, I don't need to be reminded of this fact.

**Comment by justinvp** [comment] 2024-11-16 17:18
Thanks for the suggestion, @cowwoc!

**Comment by meagancojocar** [comment] 2024-11-18 18:29
> So long as I am using the free features of Pulumi, I don't need to be reminded of this fact.

@cowwoc Thanks for raising this! You should not receive this warning if you are using the free features of Pulumi Cloud, which is an individual account. Using an Organization requires a credit card and there is a free tier of 200 resources before charges incur ([details on the pricing page](https://www.pulumi.com/pricing/)). If you start a trial and do not enter a credit card but continue using it, you will receive this message. 

Closing this issue as by design, but let us know if you are receiving this warning on an individual account and we can re-open it as a bug!

**Closed by meagancojocar** 2024-11-18 18:29 UTC
Labels: area/cli, kind/enhancement, resolution/by-design

**Comment by cowwoc** [comment] 2024-11-18 20:46
@meagancojocar Using an Organization does not require a credit card. My account does not have a credit card on file, nor do I recall ever starting a trial period for a paid tier. I simply signed up for the free tier as an Organization.

If you go to https://www.pulumi.com/pricing/, the button for "free tier" reads "Create an Organization" whereas the paid tiers read "Start free trial". I just created an organization.

What I am saying is that as long as I do not try using any paid feature, then I shouldn't receive warning message about an expired trial or cancelled subscription because that is factually incorrect for my case.

**Comment by meagancojocar** [comment] 2024-11-19 02:01
Ah I see what you are saying, I really appreciate your feedback on this! It sounds like our pricing page added some confusion here. When you create an organization it outlines you are starting a trial of paid features:

![Image](https://github.com/user-attachments/assets/1cb8cf8d-910f-44c4-bc33-e921e495a0e4)

Organization = paid feature, with 14 day trial period. Individual = free everything, always. Given the create organization button on the pricing page being on the Free column it added confusion. I'll open an issue on that repo to clarify some of the language.

**Comment by cowwoc** [comment] 2024-11-19 14:56
Thank you for the clarification.

So are you saying that although I am free to continue using 200 free IaC resources per month, Pulumi prefers to "remind" (nag) me to subscribe to a paid tier, regardless of whether I try using paid features or not?

Are you willing to remove this warning for when I do not attempt to use any paid features?
