### ISSUE TITLE
Panic when Aborting Operation with Ctrl-C 

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi#10431] opened 2022-08-18 01:00 UTC
### What happened?

As reported by @stack72, canceling a running program resulted in the following stack trace:

```go
panic: send on closed channel

goroutine 762 [running]:
github.com/pulumi/pulumi/pkg/v3/engine.diagEvent(0x140001744c8, 0x14000f1de00, {0x14000709940, 0x1c}, {0x14001d617a0, 0x51}, {0x10355ca13, 0x5}, 0x0)
	/Users/runner/work/pulumi/pulumi/pkg/engine/events.go:461 +0x150
github.com/pulumi/pulumi/pkg/v3/engine.(*eventEmitter).diagErrorEvent(...)
	/Users/runner/work/pulumi/pulumi/pkg/engine/events.go:485
github.com/pulumi/pulumi/pkg/v3/engine.(*eventSink).Errorf(0x140001744c8, 0x7c?, {0x0?, 0x2d?, 0x140014eff08?})
	/Users/runner/work/pulumi/pulumi/pkg/engine/eventsink.go:88 +0xf8
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0x140017d4b40, 0x103eedbf0?, {0x14000c198a0?, 0x1, 0x0?})
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:262 +0x264
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1()
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:439 +0xb4
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
	/Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:436 +0x21c
```

### Steps to reproduce

* (With Ctrl-C) Cancel a running Pulum Program…

* …right as the step executor is sending an engine event.

### Expected Behavior

Graceful shutdown to occur, with no panic

### Actual Behavior

Program panic

### Additional context

[Internal link](https://pulumi.slack.com/archives/C02VCJEBT2N/p1660774877880689) to Slack thread

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2022-08-23 21:39
Is the program an update or preview? It may help narrowing down. 

I'm having trouble reproducing this exact stack trace. 

By static analysis, assuming this is an update, what seems to be happening is that eventEmitter got closed before one of the step executor workers finished; this worker tried to emit a diagnostic event but the channel was already closed.

This however seems impossible from reading the code:

```
engine/update.go:
  func update() {
     defer emitter.Close()
     return deployment.run(...)
  }

engine/deployment.go:
  func (deployment *deployment) run() {
     deployment.Deployment.Execute()
  }

resource/deploy/deployment.go:
  func (d *Deployment) Execute() {
     return deploymentExec.Execute()
  }

resource/deploy/deployment_executor.go:
  func (d *deploymentExecutor) Execute() {
    ex.stepExec = newStepExecutor(ctx, cancel, ex.deployment, opts, preview, false)
    ...
    ex.stepExec.WaitForCompletion()
  }
```

It would seem that control flow always reaches WaitForCompletion() before returning from run(), and I don't see issues in the WaitGroup code inside WaitForCompletion, it seems accurate. 

Perhaps there is a nested panic somehow? So Execute() panics before WaitForCompletion bu that triggers `defer emitter.Close()`? We could try panic-proofing ex.stepExec.WaitForCompletion with a defer statement also?

Alternatively we could go with teaching the eventEmitter to drop events after close instead of sending them on a closed channel. This would get rid of the panic but possibly mask underlying  concurrency issues.

**Comment by stack72** [comment] 2022-08-23 22:30
You are correct this was a panic from an update

I had the same panic tonight when I ran this program:

```
import { local } from "@pulumi/command";

for (let i = 0; i < 1000; i++) {
    new local.Command("cmd-" + i, {
        create: "echo ''",
    });
}
```

ad then cancelled out half way through

**Comment by t0yv0** [comment] 2022-08-23 22:32
I'll try again tomorrow with this, a repro would be awfully nice.

**Comment by t0yv0** [comment] 2022-08-24 22:36
Here are repro steps I got to use, still non-deterministic but high probability of reproducing.

```typescript
import { local } from "@pulumi/command";

for (let i = 0; i < 25; i++) {
    if (i !== 1) {
        new local.Command("cmd-" + i, {
            create: "echo ''",
        });
    } else {
        new local.Command("interrupt", {
            create: "./interrupt.sh",
        });
    }
}
```

```
#!/usr/bin/env bash
# interrupt.sh
P=$(pgrep -a pulumi)
sleep 1
kill -s SIGINT $P
kill -s SIGINT $P
kill -s SIGINT $P
sleep 1
kill -s SIGINT $P
kill -s SIGINT $P
kill -s SIGINT $P
sleep 1
kill -s SIGINT $P
kill -s SIGINT $P
kill -s SIGINT $P
sleep 1
kill -s SIGINT $P
kill -s SIGINT $P
kill -s SIGINT $P
sleep 1
kill -s SIGINT $P
kill -s SIGINT $P
kill -s SIGINT $P
sleep 1
kill -s SIGINT $P
kill -s SIGINT $P
kill -s SIGINT $P
sleep 1
kill -s SIGINT $P
kill -s SIGINT $P
kill -s SIGINT $P
```

```
pulumi stack init devrandom
pulumi up --yes
```

**Comment by t0yv0** [comment] 2022-08-24 22:38
Q debugging session demonstrating race between stepExecutor workers and eventEmitter.Close.

```
[22:10:22 pulumi/util.go:747 main.cancellationScopeSource.NewScope]
0.002s NewScope isPreview=bool(false)

[22:10:22 engine/events.go:239 github.com/pulumi/pulumi/pkg/v3/engine.makeEventEmitter]
0.001s fmt.Sprintf("makeEventEmitter() => [ch=%p]\n", channel)=makeEventEmitter() => [ch=0xc000ddb440]


[22:10:22 engine/deployment.go:257 github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run]
0.001s spawning deployment.run()

[22:10:25 pulumi/util.go:775 main.cancellationScopeSource.NewScope.func1]
0.002s RECEIVED SIGNAL -> cancelSource.Terminate()

[22:10:25 engine/deployment.go:295 github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run]
0.001s cancelCtx.Cancel.Terminated()!!!

[22:10:25 deploy/step_executor.go:233 github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).WaitForCompletion]
0.001s stepExecutor.WaitForCompletion() START p=0xc001800b40

[22:10:25 engine/events.go:356 github.com/pulumi/pulumi/pkg/v3/engine.(*eventEmitter).Close]
0.001s fmt.Sprintf("eventEmitter[ch=%p].Close()\n", channel)=eventEmitter[ch=0xc000ddb440].Close()

[22:10:25 deploy/step_executor.go:237 github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).WaitForCompletion]
0.001s stepExecutor.WaitForCompletion() END p=0xc001800b40
```

**Comment by t0yv0** [comment] 2022-08-24 22:41
Story: we have this NewScope function https://github.com/pulumi/pulumi/blob/2bd79f3b8213d5338b552ef805417ae1f388ec1e/pkg/cmd/pulumi/util.go#L751 that encodes the distinction between cancellation and termination. It seems that the intent is on first Ctrl+C to initiate cooperative cancellation and warn the user that work may be lost, but on a second Ctrl+C to initiate a less cooperative termination. It is the termination branch that results in the panic. If the code is edited to execute termination code right away the condition is much easier to repro.

**Comment by t0yv0** [comment] 2022-08-24 22:45
So when processing termination we get here:

https://github.com/pulumi/pulumi/blob/2bd79f3b8213d5338b552ef805417ae1f388ec1e/pkg/engine/deployment.go#L289

And the code no longer waits on `<-done:`. This means this line https://github.com/pulumi/pulumi/blob/2bd79f3b8213d5338b552ef805417ae1f388ec1e/pkg/engine/deployment.go#L271 is not guaranteed to be completed, but we go ahead and unroll the stack that ends up doing `defer eventEmitter.Close()`. 

In the meanwhile stepExecutor workers still may be going, though they're trying to gracefully cancel at this point - this seems to be about stopping in between steeps in a chain if cancel is detected. When these workers finish up they try to emit a diag event but that panics on a closed emitter.

**Comment by t0yv0** [comment] 2022-08-24 22:50
I'm wondering what the right fix is.

- changing lifetimes seems invasive, like making eventEmitter live until Deployment.Execute is done

- it seems that code is intentional about not waiting on stepExecutor workers in case of termination; they may be stuck and not making progress, and the user is requesting to quit now

So I'm leaning toward a local change simply safeguarding the eventEmitter class. Instead of doing channel sends, it will first check if it's been closed. If it has been closed it will do nothing. Perhaps in `-debug` mode it can spit out the event it hasn't been able to send via logs.

**Comment by RobbieMcKinstry** [comment] 2022-08-25 13:53
> Instead of doing channel sends, it will first check if it's been closed. If it has been closed it will do nothing.

If I'm understanding correctly, the fix you're suggesting would work like this:

1. Check if channel is closed.
2. If closed, do nothing.
3. If not closed, send on the channel.

If I'm understanding that correctly, there's still a race if 1 through 3 aren't atomic.
Suppose you see that the channel is opened, but before you can send on the channel, another thread closes the channel. Since the "check-and-send" operation isn't atomic, someone else could close the channel between the check and the send.

That could still be "good enough" for now, since it will drastically reduce the likelihood of a panic.

**Comment by t0yv0** [comment] 2022-08-25 16:44
Sorry @RobbieMcKinstry reading the comment after the PR got merged already; the https://github.com/pulumi/pulumi/pull/10489 was rewritten to avoid the race scenario. LMK If this still needs work I will reopen.

**Closed** 2022-08-25 16:43 UTC
Labels: kind/bug, p1, impact/panic, area/engine
