### ISSUE TITLE
Can not input the password when using StackReference

### ISSUE THREAD

**Issue by a523** [pulumi/pulumi#14275] opened 2023-10-18 09:49 UTC
### What happened?

This is my code:
```python 
stack_ref = pulumi.StackReference(f"xxx", stack_name=config.require("xxx"))
```
 when you use `StackReference` in your pulumi code,  you need to input another password of other stacks, in this case, The CLI  dialog box keeps blinking， It is hard to input the right password. How I can resolve this problem?
I think this is a bug that can be easily fixed. 

### Example

the always flicker. 

![image](https://github.com/pulumi/pulumi/assets/21216466/916f841e-fe2f-403c-8051-7ee0871a5097)

### Output of `pulumi about`

CLI          
Version      3.89.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.26.0
python  unknown
random  4.8.1

Host     
OS       darwin
Version  13.6
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2023-10-18 09:56
I think this is pretty much just https://github.com/pulumi/pulumi/issues/2823, although maybe we've tweaked some internals now so this shows as a prompt rather than just failing now.

**Comment by justinvp** [comment] 2023-10-18 19:16
Closing as a duplicate of https://github.com/pulumi/pulumi/issues/2823

**Closed by justinvp** 2023-10-18 19:16 UTC
Labels: kind/bug, resolution/duplicate
