### ISSUE TITLE
Raw 500 error when `pulumi stack rm` a stack with resources still in it

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#698] opened 2017-12-11 22:11 UTC
If I forget to do `pulumi destroy` prior to `pulumi stack rm` - I get:

```
luke:~/go/src/github.com/pulumi/pulumi-cloud/examples/todo (testgetlogs *)
$ pulumi stack rm
This will permanently remove the 'luke-cloud' stack!
Please confirm that this is what you'd like to do by typing ("luke-cloud"): luke-cloud
error: [500] Internal Server Error
```

**Comment by chrsmith** [comment] 2018-10-30 15:18
I was unable to reproduce the 500 error just now, so I assume this has just been fixed in the post-PPC world.

**Closed by chrsmith** 2018-10-30 15:18 UTC
Labels: area/service, help wanted, kind/bug
