### ISSUE TITLE
Parent providers not propagating to `kubernetes.yaml.ConfigGroup` in a `pulumi.ComponentResource`

### ISSUE THREAD

**Issue by pawelprazak** [pulumi/pulumi#10961] opened 2022-10-07 14:26 UTC
### What happened?

It would appear that a combination of `pulumi:disable-default-providers` a `pulumi.ComponentResource` and `kubernetes.yaml.ConfigGroup` result in this error:
```
    error: TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at Object.transferProperties (/Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@pulumi/runtime/rpc.ts:43:28)
        at /Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@pulumi/runtime/resource.ts:504:27
        at Generator.next (<anonymous>)
        at /Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@pulumi/pulumi/runtime/resource.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@pulumi/pulumi/runtime/resource.js:17:12)
        at prepareResource (/Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@pulumi/pulumi/runtime/resource.js:340:12)
        at Object.registerResource (/Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@pulumi/runtime/resource.ts:286:24)
        at new Resource (/Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@pulumi/resource.ts:401:13)
    error: Error: Invoke: Default provider for 'kubernetes' disabled. 'kubernetes:yaml:decode' must use an explicit provider.
        at Object.callback (/Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/pprazak/repos/reflek/infrastructure-cloud/typesense/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### Steps to reproduce

Disable default kubernetes provider:
```
pulumi:disable-default-providers:
  - kubernetes
```

Create a custom component that contains a `ConfigGroup`, a fragment example:
```
export class TypesenseCluster extends pulumi.ComponentResource {
    ...
    constructor(name: string, args: TypesenseClusterArgs, opts?: pulumi.ComponentResourceOptions) {
        super("reflek-io:typesense:TypesenseCluster", name, {}, opts);
        ...
        const glbConfig = pulumi.all([args.namespace, this.internalHostname]).apply(
            ([ns, hs]) => new kubernetes.yaml.ConfigGroup(
                `${publicServiceName}-glb-config`,
                {
                    yaml: [
                        `apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ${publicServiceName}
  namespace: ${ns}
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /health
    port: ${args.apiPort || defaultApiPort}
`, `
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ${publicServiceName}
  namespace: ${ns}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
`]
                }, {
                    parent: this,
                }
            ));
```

Use the component while passing the provider explicitly:
```
    providers: {
        kubernetes: k8sProvider, // make sure we use explicit Kubernetes provider, not the default
    },
```

### Expected Behavior

I've expected parent provider (from component) to propagate to `ConfigGroup`.

### Actual Behavior

The parent provider (from component) did not propagate to `ConfigGroup`.

### Output of `pulumi about`

CLI
Version      3.41.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  12.6
Arch     x86_64

Current Stack: typesense-rio-test

Found no resources associated with typesense-rio-test

Found no pending operations associated with typesense-rio-test

Backend
Name           Pawes-MBP
URL            gs://rio-pulumi-backend
User           pprazak
Organizations

Pulumi locates its logs in /var/folders/nr/rqhf2hvn3wn8q_mjysz2gq6m0000gn/T/ by default
warning: Failed to get information about the project runtime: unknown method About for service pulumirpc.LanguageRuntime
warning: Failed to get information about the Pulumi program's dependencies: unknown method GetProgramDependencies for service pulumirpc.LanguageRuntime

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment] 2022-10-11 17:06
@pawelprazak thanks for finding this, I'll look into this issue.

In the meantime, could you try setting the `provider` (no s) option explicitly, as a workaround? Let me know if that works or not while I investigate this issue with the `providers` map option.

**Comment by AaronFriel** [comment] 2022-10-11 17:13
@iwahbe pointed me in the direction of #10640, which we think this is a duplicate of and he is working on. Closing in favor of that issue - please subscribe to notifications there and when that is fixed & released we'll check the Kubernetes use case.

**Closed by AaronFriel** 2022-10-11 17:13 UTC
Labels: kind/bug, area/providers, resolution/duplicate
