### ISSUE TITLE
FileArchives do not preserve file modes

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#5010] opened 2020-07-14 22:40 UTC
Consider code like this:

```typescript
const handlerFunc = new aws.lambda.Function("handler", {
    code: new pulumi.asset.FileArchive("bin"),
    runtime: "go1.x",
    handler: "handler",
    role: convertHandlerRole.arn,
    timeout: 300,
});
```

where the `bin/` directory contains an executable file -- the Go lambda handler -- named `handler`:

```
-rwxr-xr-x  1 joeduffy  staff  43223189 Jul 14 15:30 handler
```

Unfortunately, the executable bits seem to get stripped somewhere along the way, resulting in an error from Lambda:

```
fork/exec /var/task/handler: permission denied: PathError
```

Indeed, downloading and unpacking the function's code reveals that the binary isn't executable:

```
-rw-r--r--@ 1 joeduffy  staff  43223189 Dec 31  1989 handler
```

I would hope it's possible to preserve the file mode during the zipping and uploading process. I'm filing this in the pulumi/pulumi repro because I suspect this is happening in the core asset/archive logic itself.

**Comment by leezen** [comment] 2020-07-14 22:48
I believe this is a dupe of https://github.com/pulumi/pulumi/issues/3593

**Comment by joeduffy** [comment] 2020-07-14 22:51
Also note that this form doesn't work either:

```typescript
    code: new pulumi.asset.AssetArchive({
        "handler": new pulumi.asset.FileAsset(path.join("bin", "handler")),
    }),
```

**Comment by joeduffy** [comment] 2020-07-14 22:52
@leezen Looks like it, agree. Missed that when searching.

**Closed** 2020-07-15 21:55 UTC
