### ISSUE TITLE
[nodejs] Dynamic providers seem to be serializing requests

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#6716] opened 2021-04-07 01:18 UTC
Discovered as a part of recent dynamic provider failure mode explorations. If you implement diff/check with async work that you await (a sleep in our example) then preview time increases linearly with the number of resources. 

Example code that does a `sleep(3000)` for check/diff:

```ts
import * as pulumi from "@pulumi/pulumi";

function timeout(ms: any) {
    return new Promise(resolve => setTimeout(resolve, ms));
}
async function sleep(fn: any, ...args: any) {
    await timeout(3000);
    return fn(...args);
}


const myProvider: pulumi.dynamic.ResourceProvider = {
    async create(inputs) {
        await sleep(() => { })

        return { id: "foo", outs: {} };
    },
    async diff(inputs) {
        await sleep(() => { })
        return {}
    },
    async check(inputs) {
        await sleep(() => { })
        return { inputs }
    }
}

class MyResource extends pulumi.dynamic.Resource {
    constructor(name: string, props: {}, opts?: pulumi.CustomResourceOptions) {
        super(myProvider, name, props, opts);
    }
}

class Component extends pulumi.ComponentResource {
    constructor(name: string, args = {}, opts = {}) {
        super("lotsofdynamics", name, args, opts);
        let arr = Array.from(Array(30).keys())

        arr.forEach((i) => {
            new MyResource(name+i.toString(), {})
        })
    }
}

export = async () => {

    ["foo"].forEach(n => {
        new Component(n)
    })

    return {
        foo: "abc"
    }
}

```

I varied the number of resources created and collected a few data points for a first preview (should only call check and not diff): 

| Resource Count      | Preview Time (s) |
| ----------- | ----------- |
| 5      | 17       |
| 10   | 31        |
| 20   | 62        |
| 30   | 93        |

Runtime is roughly (num resources * 3 seconds) and appears to be perfectly linear:

![Screen Shot 2021-04-06 at 6 16 09 PM](https://user-images.githubusercontent.com/2553171/113796565-5cf2a000-9704-11eb-83f7-d443008a6503.png)

Requires more investigation to understand the root cause of this. Perhaps there is a gRPC setting we are missing somewhere?

**Comment by EvanBoyle** [comment] 2021-04-07 01:21
These tests were done with all of the recent caching enhancements enabled.

**Comment by lukehoban** [comment] 2021-04-07 01:57
I believe this is actually the more general issue captured in https://github.com/pulumi/pulumi/issues/3302.

**Comment by lukehoban** [comment] 2021-04-07 03:19
Closing out as dupe of #3302.

**Closed** 2021-04-07 03:19 UTC
Labels: area/providers, kind/enhancement, language/javascript, resolution/duplicate
