### ISSUE TITLE
pyright fails on get_config as of 1.4.5

### ISSUE THREAD

**Issue by doy-materialize** [pulumi/pulumi#17219] opened 2024-09-04 15:14 UTC
### Describe what happened

the python type signature for `get_config` changed in https://github.com/pulumi/pulumi-cloudinit/pull/386 and now trying to use `get_config` produces a pyright error

### Sample program

```python
# pyright: strict

import pulumi_cloudinit


pulumi_cloudinit.get_config()
```

### Log output

```
$ pyright __main__.py
/home/doy/tmp/pulumi-pyright/__main__.py
  /home/doy/tmp/pulumi-pyright/__main__.py:6:1 - error: Type of "get_config" is partially unknown
    Type of "get_config" is "(base64_encode: bool | None = None, boundary: str | None = None, gzip: bool | None = None, parts: Sequence[GetConfigPartArgs | Unknown] | None = None, opts: InvokeOptions | None = None) -> AwaitableGetConfigResult" (reportUnknownMemberType)
1 error, 0 warnings, 0 informations
```

### Affected Resource(s)

`pulumi_cloudinit.get_config`, `pulumi_cloudinit.get_config_output`

### Output of `pulumi about`

```
CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME       VERSION
resource  cloudinit  1.4.5
language  python     unknown

Host     
OS       arch
Version  
Arch     x86_64

This project is written in python: executable='/home/doy/tmp/pulumi-pyright/venv/bin/python' version='3.12.4'

Current Stack: doy-materialize-com/pulumi-pyright/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/doy-materialize-com
User           doy-materialize-com
Organizations  doy-materialize-com, materialize
Token type     personal

Dependencies:
NAME              VERSION
pip               24.2
pulumi_cloudinit  1.4.5
setuptools        74.1.1
wheel             0.44.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2024-09-12 14:52
The error happens because `GetConfigPartArgsDict` is used in 

```
parts: Optional[Sequence[Union['GetConfigPartArgs', 'GetConfigPartArgsDict']]] = None
```

but it doesn't seem to be defined anywhere.

Likely, a regression coming from https://github.com/pulumi/pulumi/pull/16704, marking as such.

**Closed** 2024-09-20 18:35 UTC
Labels: kind/bug, p1, language/python, area/codegen, impact/regression, customer/feedback
