### ISSUE TITLE
Regression in the `@pulumi/pulumi` 3.128.0 for `PULUMI_CONFIG` env variable?

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#16974] opened 2024-08-14 10:04 UTC
### What happened?

Customer reports they may have found a regression in the `@pulumi/pulumi` NPM package.

> We were using 3.127.0 and tried updating to 3.129.0 this morning but all of our unit tests which set the config using `process.env.PULUMI_CONFIG` started failing with `Missing required configuration variable xyz`. Rolling back to 3.127.0 fixed the issue.

### Example

No repro yet.

### Output of `pulumi about`

`@pulumi/pulumi` v3.129.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ringods** [comment] 2024-08-14 10:30
Customer was able to narrow it down to v3.128.0.

**Comment by justinvp** [comment] 2024-08-14 17:44
I'm not seeing any obvious changes in `@pulumi/pulumi` between 3.127.0 and 3.128.0 that could impact this. Could they share a minimal snippet of a unit test that demonstrates the issue?

**Comment by ringods** [comment] 2024-08-19 13:03
@justinvp the general setup of the customer their unit test code is like this:

```ts
import * as pulumi from '@pulumi/pulumi';
import { getDefaults } from '@customer-private-package';

process.env.PULUMI_CONFIG = JSON.stringify({
    'project:defaults': '{"foo":"bar"}',
});

pulumi.runtime.setMocks(
...
);

describe('Example', () => {
    it('should get the config', () => {
        const defaults = getDefaults();
        expect(defaults).toEqual({ foo: 'bar' });
    });
});
```

Since `@pulumi/pulumi@v3.128.0`, there is a cyclic import dependency between `pulumi.runtime.state` and `pulumi.runtime.rpc`, introduced in #13240:

* [`rpc` -> `state`](https://github.com/pulumi/pulumi/blob/v3.128.0/sdk/nodejs/runtime/rpc.ts#L23)
* [`state` -> `rpc`](https://github.com/pulumi/pulumi/blob/v3.128.0/sdk/nodejs/runtime/state.ts#L22)

The `@customer-private-package` uses code from the core Pulumi SDK. I haven't been able to pinpoint exactly which line it is, but I assume for now the cyclic dependency between `runtime.state` and `runtime.rpc` is what leads to a different evaluation order. Supporting this assumption, I asked the customer to move the import of their own package after the `setMocks` invocation:

```ts
import * as pulumi from '@pulumi/pulumi';

process.env.PULUMI_CONFIG = JSON.stringify({
    'project:defaults': '{"foo":"bar"}',
});

pulumi.runtime.setMocks(
...
);

import { getDefaults } from '@customer-private-package';

describe('Example', () => {
    it('should get the config', () => {
        const defaults = getDefaults();
        expect(defaults).toEqual({ foo: 'bar' });
    });
});
```

This resolved the error they reported using `@pulumi/pulumi` v3.128.0.

**Comment by justinvp** [comment] 2024-08-27 05:33
Thanks for the details @ringods! One more question: What does the implementation of `getDefaults` do?

**Comment by justinvp** [comment] 2024-08-27 05:39
The `import type` _should_ be erased at runtime, so it'd be interesting if this was indeed a cycle at runtime.

https://github.com/pulumi/pulumi/blob/4c0ccfa6ad6f4ce1191a6d649a561100f058d740/sdk/nodejs/runtime/state.ts#L22

**Comment by justinvp** [comment] 2024-08-27 06:20
Another question @ringods: What are they using for the unit test? Sounds like possibly jest? Are they using ts-jest? I'm trying to put together a repro project, but haven't been able to reproduce the issue (works on 3.127.0 and latest 3.130.0).

**Comment by ringods** [comment] 2024-08-27 07:55
The implementation of `getDefaults` is like this:

```ts
export interface Defaults {
  tags: {
    feature: string
    <plus other strings - no nested objects>
  }
}

export const getDefaults = () => {
  const config = new pulumi.Config();
  let defaults = config.getObject<Defaults>('defaultTags');
  if (defaults === undefined) {
    defaults = config.requireObject<Defaults>('defaults');
  }
  return defaults;
};
```

**Comment by justinvp** [comment] 2024-09-06 06:39
I still can't reproduce this. I've created https://github.com/justinvp/pulumi-16974. When running the test, it succeeds. This is on macOS with Node v20.9.0.

@ringods, are you able to reproduce the regression?

**Comment by justinvp** [comment] 2024-12-20 22:38
I'm going to close this since we haven't been able to reproduce the problem. Importing their package after the class to `setMocks` is appropriate. Even further would be doing something like what is done in the jest example: https://github.com/pulumi/examples/blob/master/testing-unit-ts-mocks-jest/index.spec.ts#L12-L47

**Closed by justinvp** 2024-12-20 22:38 UTC
Labels: kind/bug, area/sdks, p1, language/javascript, blocked, resolution/no-repro, needs-repro, impact/regression, customer/feedback
