### ISSUE TITLE
Slow pulumi preview due to python runtime issues

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#10333] opened 2022-08-09 19:12 UTC
### What happened?

Run `pulumi preview` for a python stack that uses many nested classes takes a long time to return (at least 5 minutes for a small stack and upwards of 20 minutes for bigger stacks).
Initial analysis and trace files indicate an issue in the python runtime.

### Steps to reproduce

I am not at liberty to share the code. Contact me for details.

### Expected Behavior

`pulumi preview` should return quickly.

### Actual Behavior

`pulumi preview` takes at least about 20 minutes to return.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2022-08-16 20:27
The slowdown in this program is caused by [aliases](https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/) Pulumi resource option implementation. In Pulumi v3.37.2 aliases cause slowdown when there are long parent-child resource chains with aliases option set. Confusingly, the user program does not set aliases, but Azure Native provider does under the hood. The user program does a parent chain with VirtualWan -> VirtualHub -> AzureFirewall, causing the program to slowdown:

```
 +   │  ├─ azure-native:network:VirtualWan            ...  create
 +   │  │  └─ azure-native:network:VirtualHub         ...  create
 +   │  │     ├─ azure-native:network:AzureFirewall   ...  create
 +   │  │     └─ azure-native:network:VirtualNetwork  ...  create
```

## Workaround 1

If possible, the recommended workaround is to flatten this parent-child chain of azure-native resources, so that an azure-native resource is never a parent of another resource. Note that it is fine to have Component Resources as parents to group azure-native resources. 

## Workaround 2

This is not recommended as it depends on Python SDK internals and may get out of sync, but I got the given program to speedup by wrapping azure-native resources in subclasses that disable aliases:

```python
from pulumi_azure_native import resources
from pulumi_azure_native import network

class _ResourceGroup(resources.ResourceGroup):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self._aliases = []

class _AzureFirewall(network.AzureFirewall):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self._aliases = []

class _VirtualHub(network.VirtualHub):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self._aliases = []

class _VirtualWan(network.VirtualWan):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        self._aliases = []

```

If these subclasses are used in place of proper resources, the program seems to work as expected but much faster.


## See also

pulumi/pulumi#10010

**Comment by t0yv0** [comment] 2022-08-22 18:06
Closing for now as I confirmed with Mitch they have what's needed for a workaround. We still need to fix the underlying issue with aliases slowdown as time permits.

**Closed by t0yv0** 2022-08-22 18:06 UTC
Labels: kind/bug, area/sdks, impact/performance, language/python, resolution/duplicate
