### ISSUE TITLE
[NodeJS] Split `types/input.d.ts` and `types/output.d.ts` in several dedicated files per namespace

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi#6571] opened 2021-03-18 09:39 UTC
## Affected feature

At least in nodejs version, `types/input.d.ts` and `types/ouput.d.ts` are a big file with a typescript namespace per azure namespace.
This is not the case with `enums`.

So currently we could import inputs and enums like this:
```ts
import { authorization as authorizationTypes } from '@pulumi/azure-native/types/input'
import * as authorizationEnums from '@pulumi/azure-native/types/enums/authorization'
```

It would be great to be able to import only selected namespace like for enums:
```ts
import * as authorizationTypes  from '@pulumi/azure-native/types/input/authorization'
import * as authorizationEnums from '@pulumi/azure-native/types/enums/authorization'

// and we can be more specific by including a single type
import { AccessReviewInstance }  from '@pulumi/azure-native/types/input/authorization'


```

It's more consistent, and may improve performance.

[Side question] I wonder why all versions are present in `enums` but not in `input`?

**Comment by mikhailshilkov** [comment] 2021-03-18 10:15
Moved to `pulumi/pulumi` which owns the codegen for this

**Comment by mikhailshilkov** [comment] 2021-03-18 10:17
> I wonder why all versions are present in enums but not in input?

Can you give an example of what's missing in `input`? All versions should be there.

**Comment by boillodmanuel** [comment] 2021-03-18 10:28
> Can you give an example of what's missing in input? All versions should be there.

You're right! I haven't seen nested namespaces ;)
Thanks

**Comment by RobbieMcKinstry** [comment] 2023-03-31 20:04
I believe this issue is a duplicate of https://github.com/pulumi/pulumi/issues/8613 
The good news is I've made some progress in that dimension. The bad news was we had to back out my initial PR, and revisit it with a new design.

**Closed by RobbieMcKinstry** 2023-03-31 20:04 UTC
Labels: kind/enhancement, language/javascript, area/codegen, resolution/duplicate
