### ISSUE TITLE
import command cannot import resources with same name

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#7557] opened 2021-07-16 18:32 UTC
If I try to import `ResourceType1` named `main` and `ResourceType2` named `main` using `pulumi import --file resources-to-import.json`, the code generation step will fail with `Error: "main" already declared`.

## Steps to reproduce

1. `pulumi up` the code below
2. `pulumi stack output resourcesToImport > resources-to-import.json`
3. `pulumi stack init imported`
3. `pulumi import --file resources-to-import.json -y`
4. observe error

Expected: expect it to not fail
Actual: it fails

## error from `pulumi import`

```
p-import-duplicate-name % pulumi import --file resources-to-import.json -y
Previewing import (imported)

View Live: https://app.pulumi.com/clstokes/p-import-duplicate-name/imported/previews/08e9d63b-1cea-4c46-8505-005a2795b6e6

     Type                 Name                              Plan       
 +   pulumi:pulumi:Stack  p-import-duplicate-name-imported  create     
 =   ├─ aws:ec2:Vpc       main                              import     
 =   └─ aws:s3:Bucket     main                              import     
 
Resources:
    + 1 to create
    = 2 to import
    3 changes

Importing (imported)

View Live: https://app.pulumi.com/clstokes/p-import-duplicate-name/imported/updates/1

     Type                 Name                              Status       
 +   pulumi:pulumi:Stack  p-import-duplicate-name-imported  created      
 =   ├─ aws:ec2:Vpc       main                              imported     
 =   └─ aws:s3:Bucket     main                              imported     
 
Resources:
    + 1 created
    = 2 imported
    3 changes

Duration: 7s

error: internal error: Error: "main" already declared

  on anonymous.pp line 0:
   1: resource main "aws:s3/bucket:Bucket" {
   2:     acl = "private"
   3:     bucket = "main-4ffaf9d"
   4:     forceDestroy = false
   5: options {
   6: protect =true
   8: }
  10: }

"main" already declared

```

## code to reproduce 

```ts
import * as aws from "@pulumi/aws";

const bucket = new aws.s3.Bucket("main");

const vpc = new aws.ec2.Vpc("main", { cidrBlock: "10.0.0.0/16" });

export const resourcesToImport = {
    "resources": [
        {
            "type": "aws:s3/bucket:Bucket",
            "name": "main",
            "id": bucket.id
        },
        {
            "type": "aws:ec2/vpc:Vpc",
            "name": "main",
            "id": vpc.id
        }
    ]
};
```

**Comment by emiliza** [comment] 2021-07-16 18:49
Sounds like a dupe of https://github.com/pulumi/pulumi/issues/6032

**Comment by clstokes** [comment] 2021-07-16 21:17
> Sounds like a dupe of #6032

Yep, closing this one.

**Closed** 2021-07-16 21:17 UTC
Labels: kind/bug, resolution/duplicate
