### ISSUE TITLE
Old secret-y value is displayed in clear text

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3075] opened 2019-08-13 13:39 UTC
I defined a secret value

```
pulumi config set v secret1 --secret
```
and used it in my program with `require` (*not* `requireSecret`):
``` ts
export const value = new pulumi.Config().require("v");
```
the output is still shown as a secret (which is good):
```
Outputs:
  value: "[secret]"
```
now I change the value and run `up` again
```
pulumi config set v secret2 --secret
pulumi up -y
```
to get
```
Outputs:
  ~ value: "secret1" => "[secret]"
```
so my old secret value is now in clear text.

I realize I should be using `requireSecret` but even `require` *seems* to work but gives this glitch on change. This probably happens because we clean the output with a regex matching the new secret value, but not the old secret value.

Feel free to close if that's by design.

**Comment by ellismg** [comment] 2019-08-13 18:59
> I realize I should be using requireSecret but even require seems to work but gives this glitch on change. This probably happens because we clean the output with a regex matching the new secret value, but not the old secret value..

Correct.  Note that by not using requireSecret it also means that the plaintext value of your output is stored in the state file as well.  If you had used requireSecret, it would have ended up encrypted (but the tradeoff is you'd have to read this value in as an Output<T>, which a little worse to program against).

> Feel free to close if that's by design.

I do think it would be worthwhile at some point to start having `require` and friends issue warnings that you are reading a secret configuration value as plain text and consider doing `requireSecret` instead and perhaps deprecate and then throw on these cases.

**Comment by lukehoban** [comment] 2019-08-14 03:43
Right - I think this is by design, and ultimately will be “fixed” by deprecating `require` on Secrets. 

We should possibly open a separate issue to track doing that, which I expect we’ll want to do in 1.1. But I’ll close this one out as I don’t think there’s anything in particular we’ll change directly related to this.

**Closed by lukehoban** 2019-08-14 03:43 UTC
