### ISSUE TITLE
aws.BucketObjectArgs.Bucket doesn't accept a aws.Bucket

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#11709] opened 2022-12-21 19:25 UTC
### What happened?

We generate the following definition of a BucketObjectArgs for aws (classic).

```c#
        /// <summary>
        /// Name of the bucket to put the file in. Alternatively, an [S3 access point](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html) ARN can be specified.
        /// </summary>
        [Input("bucket", required: true)]
        public Input<string> Bucket { get; set; } = null!;
```

https://github.com/pulumi/pulumi-aws/blob/64c83a9e5556bbb17d1f20e12a24614c32a81655/sdk/dotnet/S3/BucketObject.cs#L377-L381

Bucket is defined as accepting either an actual bucket or a string (the buckets id):

Path: `.resources.aws:s3/bucketObject:BucketObject.inputProperties.bucket`
```json
                "bucket": {
                    "type": "string",
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "string",
                            "$ref": "#/types/aws:s3/bucket:Bucket"
                        }
                    ],
                    "description": "Name of the bucket to put the file in. Alternatively, an [S3 access point](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html) ARN can be specified.\n",
                    "willReplaceOnChanges": true
                },
 ```

https://github.com/pulumi/pulumi-aws/blob/64c83a9e5556bbb17d1f20e12a24614c32a81655/provider/cmd/pulumi-resource-aws/schema.json#L533558-L533572

### Steps to reproduce

Look at current codegen (v3.50.1)

### Expected Behavior

We respect the union in C#, just like other languages.

### Actual Behavior

We don't.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2024-08-15 17:50
Dupe of #8412

**Closed by justinvp** 2024-08-15 17:50 UTC
Labels: kind/bug, language/dotnet, area/codegen, resolution/duplicate
