### ISSUE TITLE
panic when updating an Azure AppService's AppSettings

### ISSUE THREAD

**Issue by srfabio** [pulumi/pulumi#6161] opened 2021-01-21 15:12 UTC
**Description**
The following error message is shown whenever I try to update the AppSettings through Pulumi.
```    
panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 131 [running]:
    github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/web.expandAppServiceLogs(0x59674a0, 0xc001a37d40, 0x4, 0x59674a0, 0xc001a37d40, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-azurerm@v1.41.1-0.20210115140001-d6cdec37b22c/azurerm/internal/services/web/app_service.go:1415 +0xf25
    github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/web.resourceAppServiceUpdate(0xc000ca3880, 0x5afbfc0, 0xc0001c2300, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-azurerm@v1.41.1-0.20210115140001-d6cdec37b22c/azurerm/internal/services/web/app_service_resource.go:515 +0x1d12
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0008efd40, 0xc00157d450, 0xc0002e4800, 0x5afbfc0, 0xc0001c2300, 0x1, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/resource.go:316 +0x273
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc001708000, 0xc0011df5e0, 0xc00157d450, 0xc0002e4800, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/provider.go:294 +0xa5
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v1.v1Provider.Apply(0xc001708000, 0x62cd260, 0x13, 0x69f4320, 0xc000cddf50, 0x6a39d20, 0xc0002e4800, 0x0, 0x6a39d20, 0xc0002e4800, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.16.0/pkg/tfshim/sdk-v1/provider.go:97 +0x106
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Update(0xc0000021e0, 0x69f02e0, 0xc001907c50, 0xc001798d80, 0xc0000021e0, 0x5b6f601, 0xc000cbcf80)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.16.0/pkg/tfbridge/provider.go:977 +0x96b
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler.func1(0x69f02e0, 0xc001907c50, 0x5fb29e0, 0xc001798d80, 0x5f98520, 0xa263ae0, 0x69f02e0, 0xc001907c50)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.15.1-0.20201202214525-260620430c4c/proto/go/provider.pb.go:2305 +0x90
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x69f02e0, 0xc001907560, 0x5fb29e0, 0xc001798d80, 0xc002c03440, 0xc002c03460, 0x0, 0x0, 0x6975220, 0xc0005e0940)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x302
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler(0x6073f40, 0xc0000021e0, 0x69f02e0, 0xc001907560, 0xc000d52600, 0xc000d080a0, 0x69f02e0, 0xc001907560, 0xc000c98000, 0x1271)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.15.1-0.20201202214525-260620430c4c/proto/go/provider.pb.go:2307 +0x152
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0010ac000, 0x6a3ace0, 0xc000104d80, 0xc0000a2400, 0xc000d0bda0, 0xa21d1f8, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
    google.golang.org/grpc.(*Server).handleStream(0xc0010ac000, 0x6a3ace0, 0xc000104d80, 0xc0000a2400, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xce5
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000889d60, 0xc0010ac000, 0x6a3ace0, 0xc000104d80, 0xc0000a2400)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa8
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd

    error: update failed
```
However, the preview correctly detects the changes required, and inspecting the details I can see the diff is also as expected.

**Steps to reproduce**
1. Create a Pulumi stack with a Resource Group, App Service Plan, and an App Service (Tier = "Free", Size = "F1")
2. Run `pulumi up`
3. Add a new app setting to the AppSettings of the AppService created in 1.
4. Run `pulumi up` again

**Details**
Pulumi cli version: 2.17.2
Runtime: .netcore 3.1
Pulumi.Azure Package version: 3.*

**Comment by mikhailshilkov** [comment] 2021-01-21 15:21
Dupe of https://github.com/pulumi/pulumi-azure/issues/740

**Closed by mikhailshilkov** 2021-01-21 15:21 UTC
