### ISSUE TITLE
Git Bash / ConEmu thinks I'm always non-interactive

### ISSUE THREAD

**Issue by themese** [pulumi/pulumi#6467] opened 2021-03-04 15:39 UTC
## Summary
Hi,

I'm facing an issue I've seen in a few closed tickets, however I wasn't able to fix it by myself with the info already provided.

Whenever I try to use any Pulumi command I receive the following message:
`error: --yes must be passed in to proceed when running in non-interactive mode`

I don't want to use the --yes flag as I want to be able to see the preview, but again, I'm unable to fix it with the info provided.
Any ideas?

## Context (Environment)
I'm using an admin Git Bash console via ConEmu in Windows 10. 

It works fine using PowerShell for example, so I don't think it's something due to environmental variables.

Let me know any info I can provide.

Thanks a lot

**Comment by leezen** [comment] 2021-03-04 18:47
I believe this is a duplicate of https://github.com/pulumi/pulumi/issues/5407

**Closed by leezen** 2021-03-04 18:47 UTC
Labels: kind/bug, resolution/duplicate

**Comment by themese** [comment] 2021-03-04 22:26
Don't think it's a 100% duplicate but the same issue at hand.
I can give you the list of the env variables if that helps but at the end of the day I don't think it would as in the issue you linked the envs were not the problem if I understood it correctly.

If you consider this should be closed that's fine, I'm just on the hunt to find why Pulumi hates my console!

**Comment by leezen** [comment] 2021-03-04 23:16
The issue isn't so much the environment variables as mentioned at the beginning of the issue, but the underlying `golang` support for such terminals (see https://github.com/pulumi/pulumi/issues/5407#issuecomment-713768747)

**Comment by themese** [comment] 2021-03-05 08:31
Oh, apologies then, didn't understand it properly.
