### ISSUE TITLE
localBackend GetStack returned non-localStack

### ISSUE THREAD

**Issue by JoseAlban** [pulumi/pulumi#6649] opened 2021-03-30 15:09 UTC
I was requested to report a stack trace by cli

## Expected behavior
would apply changes

## Current behavior
fatal error

## Steps to reproduce
dunno

## Context (Environment)
trying to pulumi-apply after a few pulumi-applies on same shell
after trying again, it's succeeded showing me a list of stacks to choose from

## Affected feature

`pulumi up`

output:
```
Pulumi Version:   v2.4.0
Go Version:       go1.14.4
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed: localBackend GetStack returned non-localStack

goroutine 1 [running]:
runtime/debug.Stack(0xc001fd8ea0, 0x5070980, 0xc002113dd0)
	/Users/travis/.gimme/versions/go1.14.4.darwin.amd64/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x6e
panic(0x5070980, 0xc002113dd0)
	/Users/travis/.gimme/versions/go1.14.4.darwin.amd64/src/runtime/panic.go:969 +0x166
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0xc0007a4b00, 0x53a6839, 0x2d, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:33 +0x197
github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).ListStacks(0xc0007a4b40, 0x57213a0, 0xc0000c4008, 0x0, 0xc000b08490, 0x0, 0x0, 0xc000294e40, 0xc0010471d0, 0x48a8ea2, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:330 +0x15c
main.chooseStack(0x5745100, 0xc0007a4b40, 0x5745101, 0x5363d20, 0x6, 0x1000000000000, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/util.go:263 +0x135
main.requireCurrentStack(0x43c0a01, 0x5363d20, 0x6, 0x1000000000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/util.go:236 +0x16f
main.requireStack(0x0, 0x0, 0x772eb01, 0x5363d20, 0x6, 0x1000000000000, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/util.go:185 +0x4f4
main.newUpCmd.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:76 +0x125
main.newUpCmd.func3(0xc0002d7600, 0x6330fe8, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:372 +0x4e1
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc0002d7600, 0x6330fe8, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc0002d7600, 0x6330fe8, 0x0, 0x0, 0xc0002d7600, 0x6330fe8)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002d7080, 0x15, 0x0, 0x0)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d
```

**Comment by JoseAlban** [comment] 2021-03-30 15:10
might be dupe of https://github.com/pulumi/pulumi/issues/5658

**Comment by komalali** [comment] 2021-03-30 17:51
Closing out as a dupe of #5658

**Closed by komalali** 2021-03-30 17:51 UTC
Labels: resolution/duplicate
