### ISSUE TITLE
intermittent `pulumi update` panic on slow connection

### ISSUE THREAD

**Issue by emiliza** [pulumi/pulumi#7390] opened 2021-06-29 23:04 UTC
```
panic: send on closed channel
goroutine 7427 [running]:
github.com/pulumi/pulumi/pkg/v3/engine.diagEvent(0xc00259c9d8, 0xc0027a8f30, 0xc001ef49c0, 0x1c, 0xc002806b40, 0x51, 0x29eb256, 0x5, 0x0)
	/workspace/pkg/engine/events.go:578 +0x20c
github.com/pulumi/pulumi/pkg/v3/engine.(*eventEmitter).diagErrorEvent(...)
	/workspace/pkg/engine/events.go:602
github.com/pulumi/pulumi/pkg/v3/engine.(*eventSink).Errorf(0xc00259c9d8, 0xc0027a8f30, 0x0, 0x0, 0x0)
	/workspace/pkg/engine/eventsink.go:88 +0x127
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc002306400, 0x36, 0xc001ffdca0, 0x1, 0x1)
	/workspace/pkg/resource/deploy/step_executor.go:231 +0x38a
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1(0xc002306400, 0x36, 0xc001ffdca0, 0x1, 0x1, 0xc00273c000)
	/workspace/pkg/resource/deploy/step_executor.go:377 +0xc5
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
	/workspace/pkg/resource/deploy/step_executor.go:374 +0x2c8
panic: send on closed channel
goroutine 4236 [running]:
github.com/pulumi/pulumi/pkg/v3/engine.diagEvent(0xc00259c9d8, 0xc002616720, 0xc00272e5e0, 0x1c, 0xc0018a7380, 0x51, 0x29eb256, 0x5, 0x0)
	/workspace/pkg/engine/events.go:578 +0x20c
github.com/pulumi/pulumi/pkg/v3/engine.(*eventEmitter).diagErrorEvent(...)
	/workspace/pkg/engine/events.go:602
github.com/pulumi/pulumi/pkg/v3/engine.(*eventSink).Errorf(0xc00259c9d8, 0xc002616720, 0x0, 0x0, 0x0)
	/workspace/pkg/engine/eventsink.go:88 +0x127
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc002306400, 0x3c, 0xc00331ac10, 0x1, 0x1)
	/workspace/pkg/resource/deploy/step_executor.go:231 +0x38a
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1(0xc002306400, 0x3c, 0xc00331ac10, 0x1, 0x1, 0xc00273c840)
	/workspace/pkg/resource/deploy/step_executor.go:377 +0xc5
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
	/workspace/pkg/resource/deploy/step_executor.go:374 +0x2c8
panic: send on closed channel
goroutine 7445 [running]:
github.com/pulumi/pulumi/pkg/v3/engine.diagEvent(0xc00259c9d8, 0xc0026bfbf0, 0xc00263ef80, 0x1c, 0xc000f29c80, 0x51, 0x29eb256, 0x5, 0x0)
	/workspace/pkg/engine/events.go:578 +0x20c
github.com/pulumi/pulumi/pkg/v3/engine.(*eventEmitter).diagErrorEvent(...)
	/workspace/pkg/engine/events.go:602
github.com/pulumi/pulumi/pkg/v3/engine.(*eventSink).Errorf(0xc00259c9d8, 0xc0026bfbf0, 0x0, 0x0, 0x0)
	/workspace/pkg/engine/eventsink.go:88 +0x127
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc002306400, 0x3a, 0xc000cd0e80, 0x1, 0x1)
	/workspace/pkg/resource/deploy/step_executor.go:231 +0x38a
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1(0xc002306400, 0x3a, 0xc000cd0e80, 0x1, 0x1, 0xc00194f5c0)
	/workspace/pkg/resource/deploy/step_executor.go:377 +0xc5
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
	/workspace/pkg/resource/deploy/step_executor.go:374 +0x2c8
panic: send on closed channel
goroutine 7379 [running]:
github.com/pulumi/pulumi/pkg/v3/engine.diagEvent(0xc00259c9d8, 0xc00223b0b0, 0xc002a22540, 0x1c, 0xc0018625a0, 0x51, 0x29eb256, 0x5, 0x0)
	/workspace/pkg/engine/events.go:578 +0x20c
github.com/pulumi/pulumi/pkg/v3/engine.(*eventEmitter).diagErrorEvent(...)
	/workspace/pkg/engine/events.go:602
github.com/pulumi/pulumi/pkg/v3/engine.(*eventSink).Errorf(0xc00259c9d8, 0xc00223b0b0, 0x0, 0x0, 0x0)
	/workspace/pkg/engine/eventsink.go:88 +0x127
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc002306400, 0x38, 0xc00317b5e0, 0x1, 0x1)
	/workspace/pkg/resource/deploy/step_executor.go:231 +0x38a
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1(0xc002306400, 0x38, 0xc00317b5e0, 0x1, 0x1, 0xc00067f920)
	/workspace/pkg/resource/deploy/step_executor.go:377 +0xc5
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
	/workspace/pkg/resource/deploy/step_executor.go:374 +0x2c8
panic: send on closed channel
goroutine 4235 [running]:
github.com/pulumi/pulumi/pkg/v3/engine.diagEvent(0xc00259c9d8, 0xc001be23f0, 0xc001a00020, 0x1c, 0xc000cb0de0, 0x51, 0x29eb256, 0x5, 0x0)
	/workspace/pkg/engine/events.go:578 +0x20c
github.com/pulumi/pulumi/pkg/v3/engine.(*eventEmitter).diagErrorEvent(...)
	/workspace/pkg/engine/events.go:602
github.com/pulumi/pulumi/pkg/v3/engine.(*eventSink).Errorf(0xc00259c9d8, 0xc001be23f0, 0x0, 0x0, 0x0)
	/workspace/pkg/engine/eventsink.go:88 +0x127
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc002306400, 0x39, 0xc001cda950, 0x1, 0x1)
	/workspace/pkg/resource/deploy/step_executor.go:231 +0x38a
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1(0xc002306400, 0x39, 0xc001cda950, 0x1, 0x1, 0xc00194f260)
	/workspace/pkg/resource/deploy/step_executor.go:377 +0xc5
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
	/workspace/pkg/resource/deploy/step_executor.go:374 +0x2c8
```

Ultimately this appears to be triggered here: https://github.com/pulumi/pulumi/blob/master/pkg/resource/deploy/step_executor.go#L231:L231

can't easily repro it. It appeared to be triggered by a SIGINT during an update on a moderately slow connection

**Comment by lukehoban** [comment] 2021-07-01 23:36
Looks like we'll need to find a way to repro this so we can identify the right fix for the panic.

**Comment by emiliza** [comment] 2021-07-06 22:16
This was intermittent and hard to repro, removing the `p1` since it's most likely a rare edge case. I'll keep this open to see if others face the same problem and can provide more repro steps.

**Comment by lukehoban** [comment] 2022-02-09 20:53
We have not been able to reproduce, and have not had additional reports.  Closing this out for now - but if others encounter this - please do share details that might help with investigation and we can reopen.

**Closed by lukehoban** 2022-02-09 20:53 UTC
Labels: kind/bug, impact/panic, resolution/no-repro, needs-repro
