### ISSUE TITLE
Pulumi CLI Login with Browser Issue

### ISSUE THREAD

**Issue by toriancrane** [pulumi/pulumi#16842] opened 2024-07-30 09:16 UTC
### What happened?

I have noticed that if I am not already signed into the Pulumi Cloud, it does not complete the Pulumi CLI login process after I sign in. It only seems to work if I am already signed into Pulumi Cloud before running the `pulumi login` command.

### Example

I have included a recording that shows the behavior for the following:
- Logging into the CLI without first being logged into the Pulumi console
- Logging into the CLI while already being logged into the Pulumi console

https://github.com/user-attachments/assets/34ed014f-2c5f-4cb6-8c8d-da5c012909a2

### Output of `pulumi about`

```
$ pulumi about
CLI
Version      3.127.0
Go Version   go1.22.5
Go Compiler  gc

Host
OS       Microsoft Windows 11 Home
Version  10.0.22631 Build 22631
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/v-torian-pulumi-corp
User           v-torian-pulumi-corp
Organizations  v-torian-pulumi-corp, zephyr, pulumi
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment] 2024-07-30 09:29
This is a duplicate of https://github.com/pulumi/pulumi/issues/15460, but with a much better description, so I'll close that issue out.

Also linking the internal pulumi service issue: https://github.com/pulumi/pulumi-service/issues/18263

/cc @pulumi/service

**Comment by toriancrane** [comment] 2024-09-10 07:37
Seems to be resolved at least as of Sept 4th

**Closed** 2024-09-10 09:06 UTC
Labels: kind/bug, area/backends, resolution/fixed
