### ISSUE TITLE
Pulumi hangs indefinitely after python package upgrade(pulumi-eks) when previewing or upping

### ISSUE THREAD

**Issue by Sefiris** [pulumi/pulumi#7886] opened 2021-09-01 15:37 UTC
I've been working with the same project and stack for the past 3 weeks(a dev and alpha environment to test our initial application deployments to) and pulumi has been running fine, now I'm running into something that I cannot recover or find any information about.
Attempted to upgrade from `pulumi-eks==0.31.0` to `pulumi-eks==0.33.0` with 1 eks cluster and 1 managed node group that has already been provisioned, afterwards this caused all commands(`pulumi preview`, `pulumi up`, `pulumi up --skip-preview`) to completely hang and just run indefinitely. Some digging i found the `pulumi preview --logtostderr -v=7` command to get more info out on where it is freezing/hanging. this outputs a whole lotta information that I have no idea what to do with, all my google fu regarding outstanding RPCs or `waiting for quiescence` are coming up empty handed.
## Steps to reproduce

Code has not changed in between the upgrade of the pulumi-eks package, a rollback from 0.33.0 -> 0.31.0 has not worked either and I'm afraid this is completely borked. The last thing I've tried is completely nuking the python venv and starting over but this has once again had no effect 

pulumi.exe v`3.8.0`
python package versions
* pulumi-3.11.0
* pulumi_aws-4.18
* pulumi_eks-0.31.0
* pulumi_kubernetes-3.5.1

Here is the output from the last command that logs in `v=7`
``` 
I0901 17:17:45.615736   16640 eventsink.go:59] waiting for quiescence; 91 RPCs outstanding
I0901 17:17:45.616324   16640 eventsink.go:59] waiting for quiescence; 90 RPCs outstanding
I0901 17:17:45.616857   16640 eventsink.go:59] waiting for quiescence; 89 RPCs outstanding
I0901 17:17:45.617375   16640 eventsink.go:59] waiting for quiescence; 88 RPCs outstanding
I0901 17:17:45.617897   16640 eventsink.go:59] waiting for quiescence; 87 RPCs outstanding
I0901 17:17:45.617922   16640 eventsink.go:59] waiting for quiescence; 86 RPCs outstanding
I0901 17:17:45.618997   16640 eventsink.go:59] waiting for quiescence; 85 RPCs outstanding
I0901 17:17:45.619529   16640 eventsink.go:59] waiting for quiescence; 84 RPCs outstanding
I0901 17:17:45.620062   16640 eventsink.go:59] waiting for quiescence; 83 RPCs outstanding
I0901 17:17:45.620801   16640 eventsink.go:59] waiting for quiescence; 82 RPCs outstanding
I0901 17:17:45.621380   16640 eventsink.go:59] waiting for quiescence; 81 RPCs outstanding
I0901 17:17:45.621913   16640 eventsink.go:59] waiting for quiescence; 80 RPCs outstanding
I0901 17:17:45.622446   16640 eventsink.go:59] waiting for quiescence; 79 RPCs outstanding
I0901 17:17:45.622446   16640 eventsink.go:59] waiting for quiescence; 78 RPCs outstanding
I0901 17:17:45.623422   16640 eventsink.go:59] waiting for quiescence; 77 RPCs outstanding
     pulumi:pulumi:Stack  alpha-v1-dev  running
```
This will run like the above indefinitely(past 1 hour in my last try after finding some archaic post about somebody saying there was an hour timeout) and when I `CTRL+C` to cancel it the following happens
```
I0901 17:23:54.455082   16640 step_executor.go:327] StepExecutor worker(-2): worker exiting due to cancellation
I0901 17:23:54.455621   16640 deployment_executor.go:126] deploymentExecutor.Execute(...): signalling cancellation to providers...
I0901 17:23:54.455621   16640 deployment_executor.go:251] deploymentExecutor.Execute(...): context finished: context canceled
I0901 17:23:54.456156   16640 step_executor.go:327] StepExecutor worker(-1): StepExecutor.waitForCompletion(): waiting for worker threads to exit
I0901 17:23:54.456663   16640 step_executor.go:327] StepExecutor worker(-1): StepExecutor.waitForCompletion(): worker threads all exited
     Type                 Name          Plan        Info
     pulumi:pulumi:Stack  alpha-v1-dev  running     error: preview canceled
I0901 17:23:54.481431   16640 langruntime_plugin.go:193] langhost[python].Run(pwd=C:\vsc\AWS\alpha-v1,program=.,...,dryrun=true) failed: err=transport is closing
I0901 17:23:54.481940   16640 host.go:412] Error closing 'aws' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.502151   16640 host.go:412] Error closing 'kubernetes' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.504494   16640 ignore.go:44] Explicitly ignoring and discarding error: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.505493   16640 source_eval.go:183] EvalSourceIterator ended with an error: transport is closing
I0901 17:23:54.505493   16640 deployment_executor.go:206] deploymentExecutor.Execute(...): incoming events goroutine exiting
I0901 17:23:54.512491   16640 host.go:412] Error closing 'eks' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.530059   16640 host.go:412] Error closing 'aws' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.553154   16640 host.go:412] Error closing 'kubernetes' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.576832   16640 host.go:412] Error closing 'eks' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.611576   16640 host.go:412] Error closing 'aws' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.647061   16640 host.go:412] Error closing 'eks' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.680843   16640 host.go:412] Error closing 'kubernetes' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.712291   16640 host.go:412] Error closing 'eks' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.736019   16640 host.go:412] Error closing 'aws' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.750186   16640 host.go:412] Error closing 'kubernetes' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.760911   16640 host.go:412] Error closing 'aws' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.772962   16640 host.go:412] Error closing 'kubernetes' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.784710   16640 host.go:412] Error closing 'aws' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.794527   16640 host.go:412] Error closing 'aws' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.804144   16640 host.go:412] Error closing 'kubernetes' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.812836   16640 host.go:412] Error closing 'kubernetes' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.812836   16640 deployment_executor.go:129] deploymentExecutor.Execute(...): failed to signal cancellation to providers: 19 errors occurred:
        * Error signaling cancellation to resource provider 'aws': rpc error: code = Unavailable desc = transport is closing
        * Error signaling cancellation to resource provider 'kubernetes': rpc error: code = Unavailable desc = transport is closing
        * Error signaling cancellation to resource provider 'eks': rpc error: code = Unavailable desc = transport is closing
        * Error signaling cancellation to resource provider 'aws': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'eks': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'eks': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'kubernetes': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'eks': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'aws': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'kubernetes': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'aws': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'kubernetes': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'aws': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'aws': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'kubernetes': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'kubernetes': rpc error: code = Canceled desc = grpc: the client connection is closing
        * Error signaling cancellation to resource provider 'aws': rpc error: code = Canceled desc = grpc: the client connection is closing

I0901 17:23:54.823162   16640 host.go:412] Error closing 'aws' resource plugin during shutdown; ignoring: 1 error occurred:
        * TerminateProcess: Access is denied.

I0901 17:23:54.823698   16640 ignore.go:44] Explicitly ignoring and discarding error: rpc error: code = Canceled desc = grpc: the client connection is closing
I0901 17:23:54.831682   16640 host.go:417] Error closing 'python' language plugin during shutdown; ignoring: 1 error occurred:
     Type                 Name          Plan     Info
     pulumi:pulumi:Stack  alpha-v1-dev           1 error

Diagnostics:
  pulumi:pulumi:Stack (alpha-v1-dev):
    error: preview canceled
```

I really hope somebody knows what's going on here because i am at my whit's end and cannot continue my project with this broken

**Comment by benesch** [comment] 2021-09-01 18:58
Hey @Sefiris, I'm not affiliated with Pulumi but just happened to stumble across this. I'm 99% sure this is the same issue I ran into! See if https://github.com/pulumi/pulumi/issues/7862 describes your situation. Some workarounds in there too. If it is #7862, the issue is not the version of Pulumi EKS but the version of the Pulumi Python SDK; the regression was introduced in v3.10.1.

**Comment by emiliza** [comment] 2021-09-01 23:13
Thanks for jumping in here @benesch! 

This does read as a duplicate of #7862 - I'll be closing this out in favor of that. @Sefiris please track #7862 for latest updates - we're currently working on fixing this. Thanks!

**Closed by emiliza** 2021-09-01 23:13 UTC
Labels: kind/bug, resolution/duplicate

**Comment by Sefiris** [comment] 2021-09-02 06:56
@benesch and @emiliza, thanks for the quick response and linking to #7862 removing the explicit parent/child relation option  indeed fixed my issue, so for anyone wondering after stumbling on this post from a google here's a code snippet from my code that fixed it

```python
    for managed_ng in managed_node_groups:
      eks.ManagedNodeGroup(f"{cluster_name}-{managed_ng.node_group_name_prefix}",
        cluster=cluster.core,
        node_group_name=f"{cluster_name}-{managed_ng.node_group_name_prefix}",
        node_role_arn=mng_shared_iam_role.arn,
        version=managed_ng.kube_version,
        scaling_config=managed_ng.scaling_config,
        disk_size=managed_ng.disk_size,
        instance_types=managed_ng.instance_types,
        subnet_ids=managed_ng.subnet_ids,
        labels=managed_ng.labels,
        tags={"Name": f"{cluster_name}-{managed_ng.node_group_name_prefix}"},
        # Comment this and any other references to the eks cluster resource as a parent in your code
        # opts=pulumi.ResourceOptions(parent=cluster)
      )
```
```python
alpha_01_eks_cluster = eks.create_simple_cluster(
    cluster_name=const.EKS_ALPHA_01_NAME,
    cluster_version="1.21",
    vpc_id=net.vpc.id,
    public_subnet_ids=[net.dmz_subnet_01.id, net.dmz_subnet_02.id],
    private_subnet_ids=[net.apps_subnet_01.id, net.apps_subnet_02.id],
    enable_managed_node_groups=ENABLE_EKS_NODEGROUPS,
    managed_node_groups=[
      eks.ManagedNodeGroupListItem(
        node_group_name_prefix="kube-system-mng-1",
        kube_version="1.21",
        scaling_config=aws.eks.NodeGroupScalingConfigArgs(
          desired_size=4,
          min_size=4,
          max_size=4
        ),
        disk_size=20,
        instance_types=["t3.medium"],
        subnet_ids=[net.apps_subnet_01.id, net.apps_subnet_02.id],
        labels={
          "node-group-name": "supportive-apps"
        }
      )
    ]
  )

  # Expose a k8s provider instance of the cluster.
  alpha01_provider = k8s.Provider(f"{alpha_01_eks_cluster._name}-provider-custom",
    k8s.ProviderArgs(kubeconfig=alpha_01_eks_cluster.kubeconfig),
    # Comment this and any other references to the eks cluster resource as a parent in your code
    # opts=pulumi.ResourceOptions(parent=alpha_01_eks_cluster)
  )
```

**Comment by t0yv0** [comment] 2021-09-02 15:39
Thanks @Sefiris I'm going to try my fix against your example.

**Comment by t0yv0** [comment] 2021-09-02 20:01
The fix does seem to address preview issues in the simplified version of the program:

```

import pulumi
import pulumi_aws as aws
import pulumi_eks as eks
import pulumi_kubernetes as k8s

cluster = eks.Cluster(
    "example",
    vpc_id="doesntmatter",
    skip_default_node_group=True,
)

provider = k8s.Provider(
    f"{cluster._name}-provider-custom",
    k8s.ProviderArgs(kubeconfig=cluster.kubeconfig),
    opts=pulumi.ResourceOptions(parent=cluster))

for managed_ng in [1, 2, 3]:
    eks.ManagedNodeGroup(
        f"{cluster.name}-{managed_ng}",
        cluster=cluster.core,
        node_role_arn='mng_shared_iam_role.arn',
        opts=pulumi.ResourceOptions(parent=cluster))
```
