### ISSUE TITLE
Upgraded to pulumi v0.16.4 and node v11.2. Doing `pulumi new` failing on `npm install`

### ISSUE THREAD

**Issue by dfinke** [pulumi/pulumi#2217] opened 2018-11-16 18:37 UTC
Here is a transcript.

[log.txt](https://github.com/pulumi/pulumi/files/2590469/log.txt)

**Comment by lukehoban** [comment] 2018-11-16 18:59
This appears to be the same issue as https://github.com/pulumi/pulumi/issues/2157.

**Comment by ellismg** [comment] 2018-11-16 19:56
There are a bunch of issues with gRPC on Node 11, which are all due to the fact that there are not prebuilt binaries for gRPC available.  The linked grpc issue points out that there are bugs in node-pre-gyp due to breaking changes in node 11 that can cause builds to race in some cases.

In this case, it doesn't look like a problem with the builds racing, but just the fact that the build of the gRPC native bits fail on this specific Windows machine.

For example, in the log, we the VC++ compiler crashed when trying to build boring SSL

```
..\deps\grpc\third_party\boringssl\crypto\asn1\a_enum.c(156): fatal error C1903: unable to recover from previous error(s); stopping compilation [C:\trypulumi\azure-stuff\node_modules\grpc\build\boringssl.vcxproj]
  Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe.  You will be prompted to send an error report to Microsoft later.
  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
```

@dfinke Would it be possible for you to tell us what version of CL is being used here?  I'll try on my windows machine as well and see if I can get this building with the newest release visual c++ build tools.

Of course, it's not just Windows where we have problems.  I've personally hit issues where the c++ compiler on my linux machine issues some warnings on code which are then promoted to errors and I have to set `CXXFLAGS="-Wno-error"` before running `npm install`.

**Comment by dfinke** [comment] 2018-11-16 20:07
Microsoft Visual C++ 2017 x64 - 14.10.25008

**Comment by ellismg** [comment] 2018-11-16 22:03
> I'll try on my windows machine as well and see if I can get this building with the newest release visual c++ build tools.

I was able to reproduce the same errors you ran into @dfinke, but Microsoft's Download Center is having an outage so I can't actually update to the latest version of the tools to see if that actually fixes the issue.  I'll come back to this once that's working again.

In the mean time, if you downgrade to Node 10.13, I would expect that everything would work, since there should be prebuilt binaries available.

Luke opened #2218 which we'll use to see if we can just get off this native dependency.

**Comment by dfinke** [comment] 2018-11-16 23:44
Downgraded. Getting `Access is denied` doing the  `npm install`
[log.txt](https://github.com/pulumi/pulumi/files/2591254/log.txt)

**Comment by joeduffy** [comment] 2018-11-17 00:56
Strange, it looks like (from the log) this is an access denied writing to your home directory:

```
error: installing [resource plugin azure-0.16.4] from https://api.pulumi.com: rename C:\Users\Douglas\.pulumi\plugins\resource-azure-v0.16.4.tmp C
:\Users\Douglas\.pulumi\plugins\resource-azure-v0.16.4: Access is denied.
```

@ellismg @pgavlin  Does this have sometime to do with the new "download to temp and then rename" logic?

**Comment by ellismg** [comment] 2018-11-17 01:14
> @ellismg @pgavlin Does this have sometime to do with the new "download to temp and then rename" logic?

It must.  I was able to reproduce this just now and I'm taking a look.

**Comment by ellismg** [comment] 2018-11-17 01:57
Okay, I understand what the problem is here now.  The issue is related to this code:

https://github.com/pulumi/pulumi/blob/v0.16.4/pkg/workspace/plugins.go#L155-L195

Note that we use `defer` to ensure we close our handle to the file we are unpacking when we encounter a file in the tarball.  However, the defers don't run until the containing function ends, so when we go to do the rename, or process still has a bunch of open file handles, which prevents the directory from being renamed because it is "in use".

I'm going to do a hotfix.

**Comment by ellismg** [comment] 2018-11-17 02:02
@dfinke To unblock you for the next hour or so, until we can get a new CLI out, you can revert back to 0.16.3 of Pulumi, which won't have this issue. You could also unblock yourself by just doing the rename "by hand" in explorer or on the command line, and that should prevent `pulumi` from complaining in this case.

BTW, it looks like the gRPC folks just released a new version of gRPC, `1.16.1`, and there are now prebuilt binaries for Node 11, so `npm install` should no longer try to build binaries even when running on Node 11.

**Comment by ellismg** [comment] 2018-11-17 04:44
Okay, @dfinke, I did a new release of the CLI 0.16.5 which includes a fix for this issue.  I'm still in the process of updating the version that get.pulumi.com will give you, but in the mean time you can download https://get.pulumi.com/releases/sdk/pulumi-v0.16.5-windows-x64.zip directly and just take the files in the `Pulumi\bin` folder in that zip file and overwrite the versions in `%USERPROFILE%\.pulumi\bin`

Sorry for the trouble here.

**Comment by dfinke** [comment] 2018-11-17 14:45
Thanks! Back in business.

Just a note, I saw an issue logged about the Ansi control characters, before 0.16.4, wasn't getting the color coding in the console, that's back now. 

![image](https://user-images.githubusercontent.com/67258/48662246-60126600-ea4d-11e8-81ea-388d41b53cfc.png)

**Comment by joeduffy** [comment] 2018-11-17 15:53
Fascinating, does this maybe mean that https://github.com/pulumi/pulumi/issues/2214 is resolved, @ellismg @CyrusNajmabadi

**Closed** 2018-11-19 19:32 UTC
Labels: customer/feedback, priority/P0
