### ISSUE TITLE
Unable to run `pulumi import` on `aws:ec2/routeTableAssociation`

### ISSUE THREAD

**Issue by alexponyrko** [pulumi/pulumi#8335] opened 2021-11-02 18:18 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm unable to run `pulumi import` on an existing `aws:ec2/routeTableAssociation`.

### Steps to reproduce

1. Find an existing Subnet with an associated Route Table in AWS Console
2. Run `pulumi import aws:ec2/routeTableAssociation:RouteTableAssociation private-us-west-2a subnet-xxx/rtb-xxx`, replacing `xxx` with the actual resource IDs

Expected: 
Route Table Association state should import and the resource definition code should be available for copy+paste.

Actual: 
Actual example output:

```
❯ pulumi import aws:ec2/routeTableAssociation:RouteTableAssociation private-us-west-2a subnet-xxx/rtb-xxx -d
Previewing import (xxx/xxx)

View Live: https://app.pulumi.com/xxx

     Type                              Name                        Plan       Info
     pulumi:pulumi:Stack               my-project             1 error; 10 debugs
 =   └─ aws:ec2:RouteTableAssociation  private-us-west-2a          import     3 errors
 
Diagnostics:
  pulumi:pulumi:Stack (my-project):
    debug: Attempting to use session-derived credentials
    debug: Successfully derived credentials from session
    debug: AWS Auth provider used: "SSOProvider"
    debug: Truncating attribute path of 0 diagnostics for TypeSet
    debug: Attempting to use session-derived credentials
    debug: Successfully derived credentials from session
    debug: AWS Auth provider used: "SSOProvider"
    debug: Trying to get account information via iam:GetUser
    debug: Trying to get account information via sts:GetCallerIdentity
    debug: Importing route table association, target: subnet-xxx, route table: rtb-xxx
    error: preview failed
 
  aws:ec2:RouteTableAssociation (private-us-west-2a):
    error: aws:ec2/routeTableAssociation:RouteTableAssociation resource 'private-us-west-2a' has a problem: Invalid combination of arguments: "gateway_id": one of `gateway_id,subnet_id` must be specified. Examine values at 'RouteTableAssociation.GatewayId'.
    error: aws:ec2/routeTableAssociation:RouteTableAssociation resource 'private-us-west-2a' has a problem: Invalid combination of arguments: "subnet_id": one of `gateway_id,subnet_id` must be specified. Examine values at 'RouteTableAssociation.SubnetId'.
    error: Preview failed: one or more inputs failed to validate
```

**Comment by emiliza** [comment] 2021-11-04 23:41
Hi @alexponyrko - unfortunately this is an issue with our current implementation of import. This is a duplicate of https://github.com/pulumi/pulumi/issues/7978 which we've closed out in favor of https://github.com/pulumi/pulumi/issues/7160 which is the larger issue we're using to track current import issues.

Sorry for the inconvenience!

**Closed by emiliza** 2021-11-04 23:41 UTC
Labels: kind/bug, resolution/duplicate
