### ISSUE TITLE
Exceptions in Python applies are swallowed

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#4168] opened 2020-03-25 00:04 UTC
I expected that raising an unhandled exception inside of an `apply` would lead to an unhandled error that fails the deployment. It seems we silently swallow such errors, however.

For example:

```python
import sys
import pulumi_aws as aws

def boom(args):
    raise Exception('boom')

host = aws.ec2.Instance('server',
    ami=...,
    instance_type='t3.micro',
)
host.public_dns.apply(boom)
```

This program completes just fine. Adding a bit of logging inside of the `boom` function, however, reveals that the code is indeed executed and an exception is thrown:

```python
def boom(args):
    try:
        raise Exception('boom')
    except:
        print(f'Unexpected error: {sys.exc_info()[0]}')
        raise
```

Yields:

```
Diagnostics:
  pulumi:pulumi:Stack (foldinghome-dev):
    Unexpected error: <class 'Exception'>
```

**Comment by lukehoban** [comment] 2020-03-25 00:11
I suspect this is the cause of https://github.com/pulumi/pulumi/issues/3611.

**Comment by lukehoban** [comment] 2020-03-25 00:22
Actually - looking at the specific example - it’s possible this is just another case of https://github.com/pulumi/pulumi/issues/3991. 

Does the same happen if there is code explicitly waiting on the apply?  Like passing the result of the apply as an input somewhere or exporting it from the stack?

**Comment by joeduffy** [comment] 2020-03-25 00:43
It does look like if I use the value it fails the program. In this case, I just exported it and got:

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 50, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 440, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 68, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 95, in serialize_property
        props.append(await serialize_property(elem, deps, input_transformer))
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 173, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 159, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/output.py", line 114, in get_value
        val = await self._future
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/output.py", line 155, in run
        value = await self._future
      File "/Users/joeduffy/dev/code/src/github.com/joeduffy/folding@home/venv/lib/python3.7/site-packages/pulumi/output.py", line 176, in run
        transformed: Input[U] = func(value)
      File "./__main__.py", line 74, in boom
        raise Exception('boom')
    Exception: boom
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by lukehoban** [comment] 2020-03-25 04:45
Okay - this is the same issue as https://github.com/pulumi/pulumi/issues/3991 then.  I've fixed the title on that and will close this one out as a dupe.

**Closed by lukehoban** 2020-03-25 04:45 UTC
Labels: kind/bug, language/python3
