### ISSUE TITLE
Error with Dynamic Provider: Identifier 'exports' has already been declared

### ISSUE THREAD

**Issue by Talljoe** [pulumi/pulumi#11942] opened 2023-01-21 04:59 UTC
### What happened?

I am trying to build a dynamic provider. Running Pulumi Preview I get an error that looks to be related to the serialization of the provider.

### Steps to reproduce

[Repro gist](https://gist.github.com/Talljoe/da5ce158d60385864a33fac1cf4569fa)

* `pulumi new aws-typescript`
* Edit `index.ts` to match below
* `pulumi preview`

### index.ts
```Typescript
import { Input, Output,  CustomResourceOptions, output } from "@pulumi/pulumi"
import { ResourceProvider, Resource } from "@pulumi/pulumi/dynamic";

interface ReproResourceInputs {
    example: Input<string>
}

interface ReproInputs {
    example: string
}

class ReproProvider implements ResourceProvider {
    async create(inputs: ReproInputs) {
        return { id: "nothing", outs: {
            example: output(inputs.example)
        }};
    }
}

class Repro extends Resource {
    constructor(name: string, args: ReproResourceInputs, opts?: CustomResourceOptions) {
        super(new ReproProvider(), name, args, opts);
    }
}

const reproResource = new Repro("test", { example: "words"});
```

### Expected Behavior

No error.
```
Previewing update (dev)

View Live: https://app.pulumi.com/Talljoe/pulumi-repro/dev/previews/cce05216-a335-48e4-abad-dc600b1cba9a

     Type                               Name              Plan       
 +   pulumi:pulumi:Stack                pulumi-repro-dev  create     
 +   └─ pulumi-nodejs:dynamic:Resource  test              create     


Resources:
    + 2 to create
```

### Actual Behavior

```
Previewing update (dev)

View Live: https://app.pulumi.com/Talljoe/pulumi-repro/dev/previews/3a156175-78a0-4e04-912d-1d6d3c1f2012

     Type                               Name              Plan       Info
 +   pulumi:pulumi:Stack                pulumi-repro-dev  create     14 messages
     └─ pulumi-nodejs:dynamic:Resource  test                         1 error

Diagnostics:
  pulumi:pulumi:Stack (pulumi-repro-dev):
    SyntaxError: Identifier 'exports' has already been declared: :90
    const exports = require("@pulumi/pulumi/output.js");
          ^
    SyntaxError: Identifier 'exports' has already been declared
        at internalCompileFunction (node:internal/vm:73:18)
        at wrapSafe (node:internal/modules/cjs/loader:1159:20)
        at Module._compile (node:internal/modules/cjs/loader:1203:27)
        at requireFromString (/home/talljoe/dev/pulumi-repro/node_modules/require-from-string/index.js:28:4)
        at getProvider (/home/talljoe/dev/pulumi-repro/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:70:20)
        at Object.<anonymous> (/home/talljoe/dev/pulumi-repro/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:115:30)
        at Generator.next (<anonymous>)
        at /home/talljoe/dev/pulumi-repro/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/talljoe/dev/pulumi-repro/node_modules/@pulumi/pulumi/cmd/dynamic-provider/index.js:17:12)
```

### Output of `pulumi about`
```
CLI          
Version      3.52.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.27.0
awsx    1.0.1
docker  3.6.1
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/talljoe/.local/share/nvm/v19.4.0/bin/node' version='v19.4.0'

Current Stack: Talljoe/pulumi-repro/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/Talljoe
User           Talljoe
Organizations  Talljoe, sendowl

Dependencies:
NAME            VERSION
@pulumi/aws     5.27.0
@pulumi/awsx    1.0.1
@pulumi/pulumi  3.52.1
@types/node     16.18.11

Pulumi locates its logs in /tmp by default
```

### Additional context

It seems as soon as I reference `Output<T>` or `output()` this bug is triggered. Removing lines 5 and 15 of index.ts will cause the command to succeed.

I tried various versions of Node (19.4.0, 19.1.0, 18.1.0) and it reproduced in each.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2023-01-24 10:10
Looks like the issue that https://github.com/pulumi/pulumi/pull/11843 was working towards resolving.

**Comment by andreujuanc** [comment] 2023-02-27 23:23
We had this issue today, and switching back to 3.25 did the trick. :/

**Comment by andreujuanc** [comment] 2023-02-27 23:40
OK, so this change https://github.com/pulumi/pulumi/commit/cc4e34586e93a5e1ef6ab0b475240b8e2c3af97d was introduced a few month ago and broke our projects.

That commit was done on Nov 29th 2020, and the previous version was v3.48.0.

Not sure what's going to happen now :(

**Comment by RobbieMcKinstry** [comment] 2023-04-13 14:25
I [made a branch](https://github.com/pulumi/pulumi/compare/master...mckinstry/dynamic-shadow) to tackle this issue, borrowing the change from #11843. I added a regression test, which is currently red with the patch.

The output is rather opaque (`Unexpected struct type`, which isn't greppable in the codebase). I suspect there's another issue with the input program used as a reproduction. I'm not particularly familiar with Dynamic providers. I can come back to this after lunch.

```
 +  pulumi:pulumi:Stack nodejs_resource_type_name-p-it-robbie-nodejs-sha-08e74532 creating (0s)
 +  pulumi-nodejs:dynamic:Resource test creating (0s)
 +  pulumi-nodejs:dynamic:Resource test creating (0s) error: Unexpected struct type.
 +  pulumi-nodejs:dynamic:Resource test **creating failed** error: Unexpected struct type.
 +  pulumi:pulumi:Stack nodejs_resource_type_name-p-it-robbie-nodejs-sha-08e74532 creating (0s) error: update failed
 +  pulumi:pulumi:Stack nodejs_resource_type_name-p-it-robbie-nodejs-sha-08e74532 **creating failed (0.34s)** 1 error

Diagnostics:
  pulumi:pulumi:Stack (nodejs_resource_type_name-p-it-robbie-nodejs-sha-08e74532):
    error: update failed

  pulumi-nodejs:dynamic:Resource (test):
    error: Unexpected struct type.

Resources:
    + 1 created
```

**Comment by andreujuanc** [comment] 2023-04-14 10:16
@RobbieMcKinstry the "exports" issue AFAIK comes from a side effect of JS transpilation where two (or more?) items are exported in the same file, and also one of them is also used within it. 
That basically makes the serializer think that the variable to export is called "exports" because the file contains something like:

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SomeClass= exports.SomeClass= void 0;
exports.SomeConst= { };
class SomeClass{
    constructor() {
            this.someProp= exports.SomeConst;
    }
   
}
exports.SomeClass= SomeClass;
```

As you can see `exports.SomeConst` is used as a variable and that makes the serializer use that name.

This is going to be a very difficult fix TBH. Changing the variable name will require a transpiler-like operation.
Using `let` instead of `const` might break things by changing values of a scope that's colliding (I might be wrong on this one),

**Comment by andreujuanc** [comment] 2023-04-17 09:05
Another update:

I've got a lambda which has this import:
`import { SiweMessage } from 'siwe'`

And this is part of the output in the code:
```javascript
const exports = require("siwe/dist/client.js");

function __f6() {
  return (function() {
    with({  }) {

return function /*toMessage*/() {
        // .... code removed for brevity
        if (!this.nonce) {
            this.nonce = (0, exports.generateNonce)();
        }
        // ... code removed for brevity
        return [prefix, suffix].join('\n');
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}
```

I think the problem here is that part of the module is being extracted.
What is the point of this if it is going to be included in the deployed node_modules?

Notice the `exports` used as a variable, and that's because that's how it's used in the transpiled library.

I think it might be worth testing a way of keeping the module intact without extracting the first function out of it. That would get rid of 3rd party "exports errors" and local ones can be fixed as per my previous comment.

**Comment by swwu** [comment] 2023-07-31 01:01
Any updates on this? We're still on 3.48 because any version after that breaks with our dynamic providers.

**Comment by scottmack11** [comment] 2023-12-22 13:09
@justinvp also chasing this up - we are having to revert back down to 3.48 for the same issue breaking our dynamic providers as @swwu.

Is this being worked on or has this gone stale?

**Comment by Dynatrace-Paul-Anderson** [comment] 2024-03-15 00:30
This has been sitting around for a long time. Is there any workaround to get dynamic providers past this issue? Our entire interaction with our search vendor depends on a dynamic provider that we wrote, and we're stuck on v3.48 until this is fixed.

**Comment by lunaris** [comment] 2024-04-11 09:42
Hey all. A fix for this has been merged (https://github.com/pulumi/pulumi/pull/15879) and should be in the next version. This should hopefully fix several of the use cases here, though as for the initial report (in which `pulumi.output` is used in a dynamic provider), I don't believe this behaviour is currently supported, and so this use case will run into other issues (e.g. the `Unexpected struct type` error in https://github.com/pulumi/pulumi/issues/11942#issuecomment-1507065880, whereby we fail to serialise the output object's closure fields over gRPC).

My understanding of the initial report is that the code submitted never worked, but if you are using dynamic providers with `pulumi.output` and they worked previously, it would be good to get more information on these use cases. If you are looking to write a dynamic provider, the docs at https://www.pulumi.com/docs/concepts/resources/dynamic-providers/ give several examples (in which you'll see we don't use/currently support anything other than raw values -- that is, values not wrapped in e.g. `pulumi.output` or `pulumi.secret`).

If there are no examples of dynamic provider use cases that worked with `pulumi.output` previously, I'll close this issue after a little while (happy to open up new issues or requests for these features though if they don't already exist).

**Comment by banool** [comment] 2024-04-23 12:09
I opened an issue to track first class support for this feature: https://github.com/pulumi/pulumi/issues/16041.

**Comment by roderickgroeneveld-iott** [comment] 2024-04-25 21:18
I've got this issue while using dynamic providers and I'm on version 3.113.3! It seems it's not fixed (yet)...

**Comment by lunaris** [comment] 2024-05-08 09:43
Hi @roderickgroeneveld-iott, I reached out on the community Slack but am reposting here -- can you confirm that this is still an issue in the latest version? Do you have a reproduction/snippet we can look at if so? If not I'll look to close this.

**Comment by lunaris** [comment] 2024-05-17 08:25
I'm going to close this issue -- we can reopen if we have a reproduction on the latest Pulumi version.

**Closed by lunaris** 2024-05-17 08:25 UTC
Labels: kind/bug, language/javascript, impact/regression, area/callback-functions
