### ISSUE TITLE
Very slow `pulumi up` leads to expired token error

### ISSUE THREAD

**Issue by draconisNoctis** [pulumi/pulumi#9348] opened 2022-04-05 08:49 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have a pulumi project to setup our Buddy CI (via https://www.npmjs.com/package/pulumi-buddy).
As there are 981 resources in this project I expected a somehow slow execution, but it is so slow, that I get an `[403] The provided update token has expired` error.

**What I could find out:**
- The first log output started nearly 3 minutes after `pulumi up` was started
- Nearly 4 minutes between the logs `Stack *** being updated to version xxx` and `Starting Update(preview=true)`
- A newly created project with ~110 resources runs without any issues

I started pulumi with this command: `pulumi up --tracing=file:./buddy.trace --logtostderr -v9 2>./buddy.log`.  
Log- and Trace-file can be provided, but not to a public issue.

**Comment by Frassle** [comment] 2022-04-05 08:56
Duplicate of #7094

**Closed by Frassle** 2022-04-05 08:56 UTC
Labels: kind/bug, resolution/duplicate
