### ISSUE TITLE
Try/Catch for StackReferences

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#11275] opened 2022-11-07 20:57 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There are use-cases where being able to use try/catch logic around the creation of a StackReference is helpful.
Currently, if the stack the StackReference is pointing at does not exist, the pulumi program fails and try/catch does not work to avoid this.

This could be a variation of this use-case: https://github.com/pulumi/pulumi/issues/3364
So either the same mechanism eventually implemented to address that issue should apply to StackReferences, or if possible, StackReferences should support try/catch logic.

### Affected area/feature

Creating a StackReference.

**Comment by Frassle** [comment] 2023-02-01 10:23
I've reopened https://github.com/pulumi/pulumi/issues/3364 so I'm going to close this as a duplicate of that.

**Closed by Frassle** 2023-02-01 10:23 UTC
Labels: area/sdks, kind/enhancement, resolution/duplicate, area/engine
