### ISSUE TITLE
Panic after dependabot update

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi#14075] opened 2023-09-30 15:42 UTC
### What happened?

We recently enabled Dependabot for our project. A gazillion packages were updated, including some Pulumi packages. Everything is now up to date to the latest version, but we are getting a panic from Pulumi. Both locally and on the build server.

I believe the updates are the cause. I'd love to figure out which update caused this, but there were so many, and we also had an issue with our build server that didn't exit on exit code 1 (causing things to be merged for some time without them actually passing), so it is hundreds of builds I would have to look through to find when exactly it happened.

### Example

```
    panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 174 [running]:
    github.com/hashicorp/go-cty/cty.Value.GetAttr({{{0xe4e4848?, 0x400c489da0?}}, {0x0?, 0x0?}}, {0xcf4e377, 0x8})
        /home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:711 +0x258
    github.com/hashicorp/terraform-provider-aws/internal/provider.tagsResourceInterceptor.run({0x40013c2dc0?, 0xd23a318?, 0xd23a310?}, {0xe4e4420, 0x4002d96150}, {0xe4f4f18, 0x400c54c780}, {0xcee25c0?, 0x4001f248c0?}, 0x1, ...)
        /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/provider/intercept.go:250 +0xea4
    github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Update.interceptedHandler[...].func10(0x0?, {0xcee25c0?, 0x4001f248c0?})
        /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/provider/intercept.go:100 +0x11c
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xe4e4500?, {0xe4e4500?, 0x18f957e0?}, 0xd?, {0xcee25c0?, 0x4001f248c0?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230912190043-e6d96b3b8f7e/helper/schema/resource.go:812 +0x64
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x400142c700, {0xe4e4500, 0x18f957e0}, 0x400a2212b0, 0x400c54c500, {0xcee25c0, 0x4001f248c0})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230912190043-e6d96b3b8f7e/helper/schema/resource.go:924 +0x658
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x4000149f80?, {0x400118e080?, 0x400c62a740?, 0x400abdaea0?}}, {0xcf66ad0, 0xc}, {0xe4e4938?, 0x400c4d41c8}, {0xe4f49e0?, 0x400c54c500})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.60.2-0.20230927165309-e3fd9503f2d3/pkg/tfshim/sdk-v2/provider.go:100 +0x140
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Update(0x40002322c0, {0xe4e4420?, 0x4002cca1b0?}, 0x400c480900)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.60.2-0.20230927165309-e3fd9503f2d3/pkg/tfbridge/provider.go:975 +0x6d0
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Update.func1({0xe5137d8?, 0x40002322c0?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20230801203955-5d215c892096/muxer.go:356 +0x3c
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0x40019e17c0?, 0x400c707788, 0x400c707768?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20230801203955-5d215c892096/muxer.go:303 +0xc4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Update(0x400c7077c8?, {0xe4e4420?, 0x4002cca1b0?}, 0xaa73da0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20230801203955-5d215c892096/muxer.go:355 +0x5c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1({0xe4e4420, 0x4002cca1b0}, {0xcaf7520?, 0x400c480900})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.81.0/proto/go/provider_grpc.pb.go:609 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xe4e4420, 0x4002cb7b30}, {0xcaf7520, 0x400c480900}, 0x400c4b2fa0, 0x400c4d4060)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler({0xcd50660?, 0x40019e17c0}, {0xe4e4420, 0x4002cb7b30}, 0x400c4b1810, 0x400168c080)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.81.0/proto/go/provider_grpc.pb.go:611 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x400067c000, {0xe4f6d80, 0x400ae041a0}, 0x400c4bd200, 0x40075f9a10, 0x18f43110, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0xc04
    google.golang.org/grpc.(*Server).handleStream(0x400067c000, {0xe4f6d80, 0x400ae041a0}, 0x400c4bd200, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0x7c4
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 37
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x154
```

### Output of `pulumi about`

CLI          
Version      3.84.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       debian
Version  12.1
Arch     aarch64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.18.0'

Current Stack: organization/iac/sandbox

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ericrudder** [comment] 2023-09-30 15:48
@ffMathy I'm sorry for your situation, especially with so many moving parts; we will huddle up and get back to you with some ideas to help debug shorty.

**Comment by lukehoban** [comment] 2023-09-30 16:23
This appears to be the same issue tracked in https://github.com/pulumi/pulumi-aws/issues/2815. Will close this out as a dupe - but if you have any more information related to the discussion there please do add a note there. 

Specifically, this is coming from Pulumi-aws. Though I am not certain which versions exactly are affected.

**Closed by lukehoban** 2023-09-30 16:23 UTC
Labels: kind/bug, p0, needs-triage, resolution/duplicate

**Comment by lukehoban** [comment] 2023-09-30 16:25
Also note this comment from that issue which may over a viable workaround for your case as well ahead of getting the underlying issue fixed. 

https://github.com/pulumi/pulumi-aws/issues/2815#issuecomment-1722196745

**Comment by ffMathy** [comment] 2023-09-30 17:35
That worked, but why was this necessary? Shouldn't we solve the root cause here, so this doesn't happen again?

**Comment by ericrudder** [comment] 2023-09-30 18:18
@ffMathy Yes, we should absolutely diagnose the root cause; we are trying to get a simpler repro ... if you are able to share a minimal case, that could speed us along, however, we'll get to the bottom of this.
