### ISSUE TITLE
Pulumi new git repo encountered a fatal error

### ISSUE THREAD

**Issue by pyousefi** [pulumi/pulumi#16637] opened 2024-07-12 04:42 UTC
### What happened?

The Pulumi CLI encountered a fatal error. This is a bug!

### Example

```
C:\Users\azureuser\development>pulumi new git@gitlab.azure.ssci.com:de_infrastructure/pu-py-az-keyvault.git`
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.122.0
Go Version:       go1.22.4
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.4/x64/src/runtime/debug/stack.go:24 +0x5e
main.panicHandler(0xc0020bff17)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x45
panic({0x2c06480?, 0x5206bc0?})
        /opt/hostedtoolcache/go/1.22.4/x64/src/runtime/panic.go:770 +0x132
github.com/go-git/go-git/v5/plumbing/transport/ssh.(*PublicKeysCallback).ClientConfig(0x0)
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/plumbing/transport/ssh/auth_method.go:216 +0x17
github.com/go-git/go-git/v5/plumbing/transport/ssh.(*command).connect(0xc00203c410)
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/plumbing/transport/ssh/common.go:124 +0x9d
github.com/go-git/go-git/v5/plumbing/transport/ssh.(*runner).Command(0x52a5448, {0x3088e17, 0xf}, 0xc0020386e0, {0x25073e275b8, 0x0})
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/plumbing/transport/ssh/common.go:57 +0xc5
github.com/go-git/go-git/v5/plumbing/transport/internal/common.(*client).newSession(0x5209860, {0x3088e17, 0xf}, 0x47?, {0x25073e275b8?, 0x0?})
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/plumbing/transport/internal/common/common.go:116 +0x4a
github.com/go-git/go-git/v5/plumbing/transport/internal/common.(*client).NewUploadPackSession(0x0?, 0x0?, {0x25073e275b8?, 0x0?})
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/plumbing/transport/internal/common/common.go:93 +0x32
github.com/go-git/go-git/v5.newUploadPackSession({0xc0021c6c80?, 0xc0020be368?}, {0x25073e275b8, 0x0}, 0xa8?, {0x0?, 0xfac72e?, 0xc0021abe30?}, {{0x0, 0x0}, ...})
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/remote.go:529 +0x96
github.com/go-git/go-git/v5.(*Remote).fetch(0xc0020046a8, {0x3bbbb88, 0x5340380}, 0xc0020be600)
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/remote.go:418 +0x1d2
github.com/go-git/go-git/v5.(*Repository).fetchAndUpdateReferences(0xc0021aba10, {0x3bbbb88, 0x5340380}, 0xc0020be600, {0xc0020033f0, 0xf})
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/repository.go:1070 +0x8f
github.com/go-git/go-git/v5.(*Repository).clone(0xc0021aba10, {0x3bbbb88, 0x5340380}, 0xc0020be8c8)
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/repository.go:925 +0x553
github.com/go-git/go-git/v5.PlainCloneContext({0x3bbbb88, 0x5340380}, {0xc002016d40, 0x40}, 0x0, 0xc0020be8c8)
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/repository.go:486 +0xcd
github.com/go-git/go-git/v5.PlainClone(...)
        /home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.12.0/repository.go:459
github.com/pulumi/pulumi/sdk/v3/go/common/util/gitutil.gitCloneOrPull({0xc0021c6280?, 0x47?}, {0xc0020033f0, 0xf}, {0xc002016d40, 0x40}, 0x1)
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/gitutil/git.go:477 +0x12a
github.com/pulumi/pulumi/sdk/v3/go/common/util/gitutil.GitCloneOrPull({0xc0021c6280, 0x47}, {0xc0020033f0, 0xf}, {0xc002016d40, 0x40}, 0x1)
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/gitutil/git.go:461 +0x20c
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.RetrieveGitFolder({0xc0000521e0?, 0xc0021c6160?}, {0xc002016d40, 0x40})
        /home/runner/work/pulumi/pulumi/sdk/go/common/workspace/templates.go:420 +0x6e9
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.retrieveURLTemplates({0xc0000521e0, 0x41}, 0x0?, 0x0?)
        /home/runner/work/pulumi/pulumi/sdk/go/common/workspace/templates.go:314 +0x8e
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.RetrieveTemplates({0xc0000521e0, 0x41}, 0x0, 0x0)
        /home/runner/work/pulumi/pulumi/sdk/go/common/workspace/templates.go:291 +0x1be
main.runNew({_, _}, {{0x5340380, 0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/new.go:192 +0x9d4
main.newNewCmd.func2(0x0?, {0xc00200b6d0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/new.go:594 +0x108
main.newNewCmd.RunFunc.func4(0x0?, {0xc00200b6d0?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x1c
main.newNewCmd.RunFunc.RunResultFunc.func7(0xc0019b8008, {0xc00200b6d0, 0x1, 0x1})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x38
github.com/spf13/cobra.(*Command).execute(0xc0019b8008, {0xc00200b6a0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc000efbb08)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x58
```

### Output of `pulumi about`

CLI
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Host
OS       Microsoft Windows 11 Enterprise multi-session
Version  10.0.22631 Build 22631
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/pyousefi
User           pyousefi
Organizations  pyousefi, bookerdimaio
Token type     personal

Pulumi locates its logs in C:\Users\azureuser\AppData\Local\Temp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from C:\Users\azureuser\development). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from C:\Users\azureuser\development). If you have not created a project yet, use `pulumi new` to do so: no project file found

### Additional context

Brand new azure VM environment where I was going to create / clone a pulumi project from a repo.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by julienp** [comment] 2024-07-12 10:52
I can reproduce this on an Azure VM by running `pulumi new git@gitlab.azure.ssci.com:de_infrastructure/pu-py-az-keyvault.git`.

This VM can't resolve `gitlab.azure.ssci.com`

```
nslookup gitlab.azure.ssci.com
Server:  UnKnown
Address:  168.63.129.16

*** UnKnown can't find gitlab.azure.ssci.com: Non-existent domain
```

The same error occurs with other unknown domains. I assume this is an internal domain. Is your VM missing some configuration to access this domain?

On macOS pulumi provides a reasonably useful error message and does not panic:

```
error: failed to retrieve git folder: failed to clone ref 'refs/heads/main': dial tcp: lookup gitlab.azure.ssci.com: no such host
``` 

Clearly on Windows we should report a similar error.

**Comment by julienp** [comment] 2024-07-12 16:15
After further investigation, the panic is actually related to us passing through a nil value for the authentication method to the git library. This was due to bad caching in the case of errors, fixed in https://github.com/pulumi/pulumi/pull/16652

**Closed** 2024-07-16 15:57 UTC
Labels: kind/bug, area/cli, p1, impact/panic
