### ISSUE TITLE
Some tsconfig.json options are unintentionally overridden which can result in non-obvious TS compiler errors

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4829] opened 2020-06-15 22:12 UTC
We use [ts-node](https://github.com/TypeStrong/ts-node) when running Node.js Pulumi programs and policy packs.

https://github.com/pulumi/pulumi/blob/2513709089ca20ceb95ed910c7396534baae3fc9/sdk/nodejs/cmd/run/run.ts#L146-L164

The same code is duplicated for policy packs [here](https://github.com/pulumi/pulumi/blob/2513709089ca20ceb95ed910c7396534baae3fc9/sdk/nodejs/cmd/run-policy-pack/run.ts#L159-L178) (consolidating is tracked by https://github.com/pulumi/pulumi-policy/issues/48).

We provide some reasonable default values for when `tsconfig.json` doesn't exist. Unfortunately, the way this is written causes the specified defaults to override any values set in the actual `tsconfig.json` file. So if `target` is set to `es2016` in `tsconfig.json`, the value that ends up being used is `es6`.

This can lead to non-obvious TypeScript compiler errors, such as `error TS2339: Property 'includes' does not exist on type 'string[]'`, which would work if targeting `es2016`, but doesn't work when targeting `es6` (when `@types/node` is not installed). (A workaround in this particular case would be to include `@types/node` as a dependency. Or set `lib` to be `es2016` so that TS will use the ES2016 type declaration library, even though its codegen is targeting ES6).

We should fix this to only set the default values when `tsconfig.json` doesn't exist. (For compatibility, we may actually want to load `tsconfig.json` and set these default values if they aren't defined in `tsconfig.json`.)

Also, related to https://github.com/pulumi/templates/issues/116. As part of fixing this, we should update the default `target` to `es2018`, which has [broad support in Node 10+](https://node.green/#ES2018) (all the versions of Node we support).

**Comment by leezen** [comment] 2020-06-15 22:32
Note that this is documented behavior per https://www.pulumi.com/docs/intro/languages/javascript/#disabling-built-in-typescript-support and if we do update the ES target, we should also update the above documentation.

**Comment by justinvp** [comment] 2020-06-15 22:56
> this is documented behavior

And looks intentional per https://github.com/pulumi/pulumi/pull/1569#issuecomment-410792461:

> We set the following compiler options (this is what we set in our existing `tsconfig.json`'s):
>
> ```
> compilerOptions: {
>   target: "es6",
>   module: "commonjs",
>   moduleResolution: "node",
>   sourceMap: "true",
> },
> ```
>
> Any additional options in a `tsconfig.json` will be merged in. If you want to change one of the above, you'll have to fall back to using tsc directly, since ts-node prefers the options we explicitly set to ones in tfconfig.json.

But definitely worth revisiting whether we want to continue to force `es6`.

**Comment by leezen** [comment] 2020-06-16 02:49
Definitely agree it's worth revisiting. It's not clear to me why we need to force `es6`

**Comment by tmccombs** [comment] 2020-07-31 17:06
I think this might be a duplicate of  #2673 (although there is more information on this issue). 

> And looks intentional per

I'm not sure if that was intention though, or just a side-effect of passing options in case tsconfig.json is missing.

**Closed** 2021-08-16 01:58 UTC
Labels: kind/enhancement, language/javascript
