### ISSUE TITLE
Old inputs should be passed to `Diff`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#1309] opened 2018-05-02 18:49 UTC
Deciding whether an update to a Kubernetes resource requires a replacement fundamentally depends on three inputs. The first two are already supplied by Pulumi:

1. **The updated resource supplied by the user.**
1. **The "live" version of that resource as it exist in Kubernetes.** Kubernetes will auto-populate some values if they don't exist (_e.g._ `.metadata.namespace` becomes `"default"` if it does not exist, _etc_.), so the "live" version of the object is quite often not the same as the last version submitted by the user.

The last is not, but is still critically important:

3. **The last update supplied by the user.**

This is necessary for a few reasons. First, because the Kubernetes API server auto-populates some fields, we need to be able to diff between the version of the resource being submitted by the user for update, and the version passed to the API server during the last update. This is not such a big deal because most of the time (though not always!) the auto-populated values could instigate a replacement (_e.g._, `.spec.type` in `v1/Service`).

Second, some things update resources out-of-band, _e.g._, admission controllers, which will intercept a resource definition after the user submits it, and alter it before it's committed to etcd. `Diff` needs to check whether _user's_ changes to the resource definition will cause a replacement, but if we only diff between the current state and the live state, the diff will erroneously report the injected changes as being a part of the user's changes, which could cause us to report a replacement erroneously.

**Work-around:** We can jam the old inputs into the output of `Create` to work around this, but simply providing these as a first-class citizen is strictly more powerful than the existing gRPC interface, and the change represents a strict superset of what's required to make the AWS, Azure, and GCP providers work.

**Comment by lukehoban** [comment] 2018-07-12 22:57
@pgavlin Is this the same as https://github.com/pulumi/pulumi/issues/1108?

**Comment by pgavlin** [comment] 2018-07-12 23:23
It's not fully the same, but we should try to make these changes at the same time.

**Comment by swgillespie** [comment] 2018-08-14 17:53
@pgavlin do you think we should try to take this and #1108 in M17?

**Comment by lukehoban** [comment] 2018-08-27 13:57
Moving out to match #1108.

**Comment by lukehoban** [comment] 2018-12-07 02:31
I think we can safely close this as a dupe of #1108.  In practice we don't expect to make a change for this issue independent of a larger change in #1108.

**Closed by lukehoban** 2018-12-07 02:31 UTC
