### ISSUE TITLE
Running `pulumi package get-schema` outputs extra data that's not schema related

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#13724] opened 2023-08-15 00:19 UTC
### What happened?

Running `pulumi package get-schema provider@version` gets the `schema.json` from a package and sends it to `stdout`.

However, when running `pulumi package get-schema kubernetes@4.0.1 > 4.0.1.json` for the 1st time, the CLI needs to download the provider in the 1st place (✅).

However, when the CLI downloads the provider because it's not available locally, it also sends  the message `Downloading provider: kubernetes` to `stdout`.

Finally, the command completes by sending the `schema.json` to `stdout` as well.

This results in an invalid JSON because the JSON data starts with the informative message (as shown below in red).
```json
Downloading provider: kubernetes
{
  "name": "kubernetes",
  "displayName": "Kubernetes",

```

### Expected Behavior

The message `Downloading provider: kubernetes` is sent to `stderr` so it doesn't interfere with the JSON data.

### Steps to reproduce

1. Run `pulumi package get-schema kubernetes@4.0.1 > 4.0.1.json`
2. Open `4.0.1.json`
3. Check the 1st line and the invalid start of the JSON ❌
4. Running from step 1 again with the same version doesn't cause the issue since the provider is locally available. ✅

### Output of `pulumi about`

```
CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Host     
OS       debian
Version  12.1
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi
```

### Additional context

I think the error message should be sent to `stderr` to avoid conflicting with the JSON data. Maybe it's related to this line of code https://github.com/pulumi/pulumi/blob/v3.78.1/pkg/workspace/plugin.go#L71

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment] 2023-08-22 09:58
Definitely a bug, `get-schema` shouldn't write out anything other than the schema. Alternatively we could add an option like `--out` to specify where the generated schema should be written out. I believe this is in line with `gen-sdk` as well

**Comment by mikhailshilkov** [comment] 2024-06-14 12:23
Dupe of #14252, resolved in https://github.com/pulumi/pulumi/pull/14134

**Closed by mikhailshilkov** 2024-06-14 12:23 UTC
Labels: kind/bug, area/cli, resolution/duplicate
