### ISSUE TITLE
Preview failure: "unexpected unknown property value"

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#6004] opened 2020-12-23 06:22 UTC
Received multiple reports of previews failing in 2.16.0/2.16.1 with the following error:
```
error: Preview failed: unexpected unknown property value
```
See https://pulumi-community.slack.com/archives/CQ2QFLNFL/p1608677840119700 and https://pulumi-community.slack.com/archives/C84L4E3N1/p1608688886492700

**Comment by joeduffy** [comment] 2020-12-23 17:14
It looks like this popped up over here too: https://github.com/pulumi/pulumi-aws/issues/1270. It's not clear the incorrect asset had anything to do with the error, since it was for a different resource than the error, but worth mentioning in case it's a clue.

**Comment by mikhailshilkov** [comment] 2021-01-06 17:09
I got the same error while running https://github.com/pulumi/examples/tree/master/azure-ts-functions-raw

```
     Type                                    Name                     Status         Info
     pulumi:pulumi:Stack                     azure-functions-raw-dev                 
 +   ├─ azure:appservice:ArchiveFunctionApp  http-premium             created        
 +   ├─ azure:appservice:ArchiveFunctionApp  http-powershell          created        
 +   ├─ azure:appservice:ArchiveFunctionApp  http-node                created        
 +   ├─ azure:appservice:ArchiveFunctionApp  http-dotnet              created        
 +   ├─ azure:appservice:ArchiveFunctionApp  http-java                created        
 +   ├─ azure:core:ResourceGroup             windowsrg                created        
     └─ azure:appservice:Plan                linux-asp                **failed**     1 error
 
Diagnostics:
  azure:appservice:Plan (linux-asp):
    error: unexpected unknown property value
```

**Comment by pgavlin** [comment] 2021-01-06 18:29
@mikhailshilkov I cannot repro this at HEAD. Out of curiosity, which version of `pulumi-azure` are you using?

**Comment by mikhailshilkov** [comment] 2021-01-06 18:30
All the latest. A clean stack seems to work for me too.

I get this error with this state https://gist.github.com/mikhailshilkov/7e3e27eb58bfb1fcb5dead363efe4cae

**Comment by mikhailshilkov** [comment] 2021-01-06 22:10
Some context for the error that I got:

1. It happens when a Plan is about to be created.
2. The current Pulumi state contains a resource for the resource group where the plan is about to be created.
3. In reality, that resource group does not exist.
4. The unknown value is `location`.

Here is a dump of inputs:

```
{key:"__defaults"  value:{list_value:{values:{string_value:"location"}  values:{string_value:"name"}}}}  fields:{key:"kind"  value:{string_value:"Linux"}}  fields:{key:"location"  value:{string_value:"04da6b54-80e4-46f7-96ec-b56ff0331ba9"}}  fields:{key:"name"  value:{string_value:"linux-aspda554987"}}  fields:{key:"reserved"  value:{bool_value:true}}  fields:{key:"resourceGroupName"  value:{string_value:"linuxrgd2c3f4d3"}}  fields:{key:"sku"  value:{struct_value:{fields:{key:"__defaults"  value:{list_value:{}}}  fields:{key:"size"  value:{string_value:"Y1"}}  fields:{key:"tier"  value:{string_value:"Dynamic"}}}}}
```

I suspect this may be the culprit:

https://github.com/pulumi/pulumi-azure/blob/2be2bd5c9a57ef3a5792d5c10e2b4cdc56eb7c82/provider/resource.go#L2239-L2246

**Comment by mikhailshilkov** [comment] 2021-01-06 22:45
Reduced the priority as it seems more isolated this time

**Comment by leezen** [comment] 2021-01-14 21:51
Looks like the only place we do this kind of overlay on the provider is in `pulumi-azure` (https://github.com/search?q=org%3Apulumi+TerraformUnknownVariableValue+org%3Apulumi&type=code)

**Comment by bennettp123** [comment] 2021-02-15 06:26
I stumbled across this issue in 2.15.6. It doesn't affect 2.20.0 or 2.16.2, but I specifically wanted 2.15.6 to collect profiling for #6197.

I found workaround below:

```
new aws.cloudwatch.EventTarget(
    'event-target',
    {
        arn: args.clusterArn,
        rule: eventRule.name,
        roleArn: eventRole.arn,
        ecsTarget: {
            taskDefinitionArn: task.taskDefinition.arn,
            group: task.taskDefinitionName,
            launchType: 'FARGATE',
            networkConfiguration: {
                subnets: args.subnetIds,
                securityGroups: args.securityGroupIds,
            },
        },

        // workaround for "unexpected unknown property value" error in pulumi < 2.16.2

        batchTarget: undefined,
        eventBusName: undefined,
        input: undefined,
        inputPath: undefined,
        inputTransformer: undefined,
        kinesisTarget: undefined,
        runCommandTargets: undefined,
        sqsTarget: undefined,
        targetId: undefined,
    },
    { parent: this },
)
```

**Comment by t0yv0** [comment] 2021-03-26 18:38
I'm having difficulty reproducing this.

I've tried pulumi/examples 07543bd6242bc9946c48b5c1f08f98c5ce854526 which is a commit from its history that still has the azure-ts-functions-raw example.

On pulumi version v2.23.1:

1. pulumi preview works
2. pulumi up fails with what seems to be unrelated error
3. a few attempts to partially provision resource groups, behave similarly

Error:

```
    error: Running program '/Users/anton/examples/azure-ts-functions-raw' failed with an unhandled exception:
    Error: Invoke of 'azure:storage/getAccountBlobContainerSAS:getAccountBlobContainerSAS' failed: "container_name": required field is not set ()
	    ..
    error: Running program '/Users/anton/examples/azure-ts-functions-raw' failed with an unhandled exception:
    Error: Invoke of 'azure:storage/getAccountBlobContainerSAS:getAccountBlobContainerSAS' failed: "container_name": required field is not set ()
		..
    error: Running program '/Users/anton/examples/azure-ts-functions-raw' failed with an unhandled exception:
    Error: Invoke of 'azure:storage/getAccountBlobContainerSAS:getAccountBlobContainerSAS' failed: "container_name": required field is not set ()
        at deserializeResponse (/Users/anton/examples/azure-ts-functions-raw/node_modules/@pulumi/pulumi/runtime/invoke.js:196:15)
        at /Users/anton/examples/azure-ts-functions-raw/node_modules/@pulumi/pulumi/runtime/invoke.js:146:20
        at Generator.next (<anonymous>)
        at fulfilled (/Users/anton/examples/azure-ts-functions-raw/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I've checked the Slack links but I do not see the connection to this issue immediately.

Any pointers are appreciated 🙏

**Comment by mikhailshilkov** [comment] 2021-03-27 22:17
@t0yv0 Have you tried reproducing this: https://github.com/pulumi/pulumi/issues/6004#issuecomment-755744270 ?

Specifically, create only a resource group with the first `pulumi up`, then delete it from Azure manually, and try creating all other resources in the resource group that is in the state but not in Azure?

**Comment by t0yv0** [comment] 2021-03-29 14:03
I have not, no, not with deleting it manually. Let me try that.

Question regarding manual edits (drift), is Pulumi in general expected to work correctly i.e. get to desired state in presence of manual edits to the underlying resources? Or does it have "undefined behavior" in that case?

**Comment by mikhailshilkov** [comment] 2021-03-29 14:07
Great question! I think Pulumi does not work for drift situations and the behavior is undefined, so users are required to run `refresh` to update the state. If this case, are you suggesting this issue can be closed as "by design"? FWIW, I don't have other repros for it.

**Comment by t0yv0** [comment] 2021-03-29 14:26
Eh, right. I would like to repro it nonetheless, if we have a repro maybe we find something to improve, even if it's error messages. Let me try it and report back. But yes I'm thinking that if the only repro we have relies on drift this is lower priority in my mind as we're not promising this to work with drift.

**Comment by t0yv0** [comment] 2021-03-30 20:10
Managed to repro and minify the example https://github.com/pulumi/examples/pull/957

Digging in, it's pretty interesting.

**Comment by t0yv0** [comment] 2021-04-02 21:37
@mikhailshilkov your intuition was correct. The issue pertains to the feature of defaulting location in azure provider.

```
	// Provide default values for certain resource properties, to improve usability:
	//     For all resources with `location` properties, default to the resource group's location to which the
	//        resource belongs. This ensures that each resource doesn't need to be given a location explicitly.
```

Specifically for the location field the Azure provider constructs a DefaultInfo.From function, that seems to be part of the interface of the tf-bridge. This fires up, requests a refresh, and hits the branch marked "Refresh returned state == nil".

```
						switch {
						case err != nil:
							return nil, err
						case state == nil:
							barf("Refresh returned state==nil, returning TerraformUnknownVariableValue")
							//return nil, nil
							rgRegion = tfbridge.TerraformUnknownVariableValue
						default:
							obj, err := state.Object(rgRes.Schema())
							if err != nil {
								return nil, err
							}
							rgRegion = azure.NormalizeLocation(obj["location"])
						}
```

The question I have is what should this From function return as `interface{}`? Does it need tor return TerraformUnknownVariableValue sentinel? I played with replacing this branch with returning nil instead. For this particular example this resulted in a better user error message:

```
    azure:appservice:Plan linux-asp  error: azure:appservice/plan:Plan resource 'linux-asp' ha
```

The source coordinates for default application code are here https://github.com/pulumi/pulumi-terraform-bridge/blob/31fb8183136c6830557fb5dc5cd2b8067d64247a/pkg/tfbridge/schema.go#L436 - @pgavlin you last edited that code, perhaps you have some pointers on what .From functions should return in DefaultInfo?

**Comment by t0yv0** [comment] 2021-04-02 21:46
Stepping back for a second, I considered maybe the feature of defaulting location can be implemented in the SDK instead of the Azure provider. For example, in pseudocode:


```
interface PlanArgs {
   readonly location? pulumi.Input<string>;
   readonly resourceGroupName: pulumi.Input<string>;
}

function findResourceGroup(resourceGroupName: string): Output<ResourceGroup> {
   /// is this possible?
}

function effectiveLocation(args: PlanArgs) {
   if (args.location != null) {
       return args.location;
   } else {
       return findResourceGroup(args.resourceGroupName).apply(rg => rg.location);
   }
}

```

If the SDK cannot resolve resource group names to resources, we could take a breaking change to the SDK and require passing ResourceGroup instead of resourceGroupName like this?

```
interface PlanArgs {
   readonly location? pulumi.Input<string>;
   readonly resourceGroup: pulumi.Input<ResourceGroup>;
}
```

That is probably a bad idea but it would be educational for me to understand why.

**Comment by t0yv0** [comment] 2021-04-02 21:50
The advantage of doing it in SDK is that that interacts with engine state (it would find Location in engine state in our example), and most importantly it would be debuggable by the user like an normal program, the defaulting behavior would be discoverable. The disadvantage is replicating it per programming lang.

**Comment by mikhailshilkov** [comment] 2021-04-03 06:43
Can we not catch this error in the Azure provider and fall back gracefully (not assign the location, or give a hint to the user)? I don't think this issue warrants any changes in the bridge or SDKs, the situation is pretty uncommon...

**Comment by t0yv0** [comment] 2021-04-05 15:33
I do not see a good fix in the provider itself, do you see the fix? I am reading `pulumi-azure/provider/resource.go` defaulting code very closely. Does this code know if it is called in Preview or in Apply context? Presumably it returns `tfbridge.TerraformUnknownVariableValue` to make sure things work out okay in Preview context; perhaps the resource group has not provisioned yet, but once it is provisioned, the defaulting will work.

It feels like this really needs to be able to interact with the engine state Input/Output machinery to make a good call.

Since the situation is rare, perhaps close as won't fix and backlog the improvement idea for later? Or do you see a quick win?

**Closed** 2021-04-05 20:32 UTC
Labels: kind/bug, resolution/wont-fix
