### ISSUE TITLE
Unexpected struct type on custom resource

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi#7576] opened 2021-07-20 09:25 UTC
Dynamic resources can fail on update with `Unexpected struct type.`. This issue is being pulled out from #6860 as a specific issue as this is starting to block.

## Steps to reproduce

I have a `pulumi.dynamic.Resource` that I cannot update because the engine (Automation API) fails with "Unexpected struct type".

The resource source is at https://gist.github.com/barclayadam/5fb85a9268be30fcbf1f35709e3e01cb

Given the provider from the link I can successfully create the resource, but if I try to replace it Pulumi fails with `error: Unexpected struct type.`.

Similarly, in the `create` method I want endpoint.secret to be `pulumi.secret`, but that is not possible because of the "Unexpected struct type" error. I have to instead set 'additionalSecretOutputs' on the `pulumi.dynamic.Resource` I create. Not sure why in create I can use `apiKey` which is a secret, but cannot create them myself.

## Environment

Environment: Windows & Ubuntu
Pulumi Version: v3.7 (TypeScript Automation API)

**Comment by kay-is** [comment] 2021-08-01 16:07
Could be that the error is because you return fields that are undefined from provider methods.

#2205

**Comment by mikhailshilkov** [comment] 2022-03-22 13:08
I think this is a dupe of #2205 indeed

**Closed by mikhailshilkov** 2022-03-22 13:08 UTC
Labels: kind/bug, resolution/duplicate
