### ISSUE TITLE
panic whne unprotecting using the CLI

### ISSUE THREAD

**Issue by garethbudden** [pulumi/pulumi#10531] opened 2022-08-30 14:30 UTC
### What happened?

issuing the following command results in a panic
pulumi state unprotect '...' 

Pulumi Version:   v3.38.0
Go Version:       go1.19
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            runtime error: slice bounds out of range [:-2]

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.0/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1d68680, 0xc000352120})
        /opt/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x212
gopkg.in/AlecAivazis/survey%2ev1.paginate(0x7f659a334500?, {0xc000302320?, 0x7f659a48ffff?, 0xc0015b3480?}, 0x400?)
        /home/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:254 +0xb7
gopkg.in/AlecAivazis/survey%2ev1.(*Select).Prompt(0xc0006c4680)
        /home/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/select.go:199 +0x125
gopkg.in/AlecAivazis/survey%2ev1.Ask({0xc0015b3730, 0x1, 0x7f659a005e28?}, {0x1a69be0?, 0xc001482a30}, {0x0, 0x0, 0xc0006c4680?})
        /home/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:148 +0x1e4
gopkg.in/AlecAivazis/survey%2ev1.AskOne({0x22dabc0?, 0xc0006c4680?}, {0x1a69be0?, 0xc001482a30?}, 0x1?, {0x0?, 0xcc?, 0xd4d8675700050500?})
        /home/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:94 +0x8c
main.locateStackResource({{0x1e6fd54, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:113 +0x6aa
main.runStateEdit.func1({{0x1e6fd54, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:129 +0x78
main.runTotalStateEdit({0x22dc488, 0xc000054088}, {0x0, 0x0}, 0x1, 0xc0015b3bf0)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:175 +0x3fe
main.runStateEdit({0x22dc488?, 0xc000054088?}, {0x0?, 0x19?}, 0x70?, {0x7ffe70a89047?, 0x0?}, 0x19?)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:128 +0x68
main.unprotectResource({0x22dc488?, 0xc000054088?}, {0x0?, 0xc0009cf180?}, {0x7ffe70a89047?, 0x0?}, 0x1?)
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:95 +0x4a
main.newStateUnprotectCommand.func1(0xe?, {0xc0000987a0, 0x1, 0x605745?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:59 +0xcf
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc0009d0500?, {0xc0000987a0, 0x1, 0x1})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc0009d0500, {0xc000098780, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000836c80)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45

### Steps to reproduce

unprotect a resource using the CLI

### Expected Behavior

the resource unprotected

### Actual Behavior

panic

### Additional context
This has occurred because a replace operation has failed, this has left me with two resources named the same.  One is protected the other is not.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2022-08-30 14:38
Duplicate of https://github.com/pulumi/pulumi/issues/10450. The fix for this will be in the next release (should be this Wednesday). In the meantime, use a cli version prior to 3.38.0 to run this command.

**Closed by Frassle** 2022-08-30 14:38 UTC
Labels: kind/bug, needs-triage

**Comment by garethbudden** [comment] 2022-08-30 14:40
apologies, i did a search but didn't spot that one.

**Comment by Frassle** [comment] 2022-08-30 14:42
No worries :) Rather get the odd duplicate than discourage people such that we get no report.
