### ISSUE TITLE
Add `--ignore-target` for operations to act on all resources except those in the `ignore-target` list

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#13159] opened 2023-06-13 08:57 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This would look like the inverse of `--target`, so anything in the list would be changed.

For example, `pulumi destroy --ignore-target 'test1'` would destroy all except the resource with URN `test1`

**Comment by Frassle** [comment] 2023-06-13 09:07
Related https://github.com/pulumi/pulumi/issues/6324

**Comment by dixler** [comment] 2023-06-13 15:46
duplicate of https://github.com/pulumi/pulumi/issues/9346

**Closed by dixler** 2023-06-13 15:46 UTC
Labels: area/cli, kind/enhancement, resolution/duplicate, area/engine

**Comment by madsbuch** [comment] 2024-04-23 11:30
Hi @dixler what was the resolution here? I see that it was completed, but I can't seem a way to achieve it.

**Comment by Frassle** [comment] 2024-04-23 12:04
This issue was closed as a duplicate of https://github.com/pulumi/pulumi/issues/9346. That issue is still open.
