### ISSUE TITLE
Panic When Creating Elastic IP using Golang

### ISSUE THREAD

**Issue by alexelent-carta** [pulumi/pulumi#9264] opened 2022-03-16 21:19 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When using `ec2.NewEip()` receiving the following error:

```
    panic: reflect: Elem of invalid type interface {}
    goroutine 11 [running]:
    reflect.(*rtype).Elem(0x102f2bb20)
    	/opt/homebrew/Cellar/go/1.17.5/libexec/src/reflect/type.go:954 +0x194
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.awaitInputs({0x103166dd8, 0x140001aa008}, {0x1030d1a20, 0x14000530580, 0x16}, {0x102f2bb20, 0x1400056e060, 0x194})
    	/Users/alexelent/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:723 +0xb8c
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.awaitInputs({0x103166dd8, 0x140001aa008}, {0x102f2bb20, 0x14000166b90, 0x194}, {0x102f2bb20, 0x1400056e060, 0x194})
    	/Users/alexelent/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:742 +0x102c
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.awaitInputs({0x103166dd8, 0x140001aa008}, {0x102e9dd00, 0x1400052a408, 0x97}, {0x102e9dd00, 0x1400052a420, 0x197})
    	/Users/alexelent/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:778 +0x1734
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.toOutputTWithContext.func3(0x1400047c100, {0x102e9dd00, 0x1400052a408}, {0x1031712c8, 0x1400052ed20}, {0x103166dd8, 0x140001aa008}, {0x102e9dd00, 0x1400052a420, 0x197}, ...)
    	/Users/alexelent/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:849 +0x118
    created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.toOutputTWithContext
    	/Users/alexelent/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.26.1/go/pulumi/types.go:841 +0x27c
    exit status 2

    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

### Steps to reproduce

Here is the sample code to reproduce:
```
package main

import (
    "fmt"
    "github.com/pulumi/pulumi-aws/sdk/v4/go/aws/ec2"
    "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
    "github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// See https://www.pulumi.com/docs/intro/concepts/config
type Data struct {
    Name           string
    CidrBlock      string
    Azs            []string
    PrivateSubnets []string
    PublicSubnets  []string
}

func main() {
    pulumi.Run(func(ctx *pulumi.Context) error {
        // Read config from Pulumi-<stack>.yaml
        // See https://www.pulumi.com/docs/intro/concepts/config/#code
        var d Data
        cfg := config.New(ctx, "")
        cfg.RequireObject("data", &d)
        fmt.Printf("VPC name is: %v\n", d.Name)
        fmt.Printf("VPC cidrBlock is: %v\n", d.CidrBlock)

        // Create Elastic IP's for NAT Gateways
        for _, az := range d.Azs{
            eipArgs := &ec2.EipArgs{
                Vpc:  pulumi.Bool(true),
            }

            eips, eipErr := ec2.NewEip(ctx, fmt.Sprintf("%s-natgw-%s", d.Name, az), eipArgs)
            pulumi.Printf("EIPS are: %s\n", eips)
            if eipErr != nil {
                return eipErr
            }
        }

        return nil
    })
}
```

Here is my config file:
```
encryptionsalt: v1:REDACTED
config:
  aws:region: us-east-1
  vpc:data:
    name: foo-vpc
    cidrBlock: 192.168.0.0/16
    azs:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    privateSubnets:
      - 192.168.1.0/24
      - 192.168.2.0/24
      - 192.168.3.0/24
    publicSubnets:
      - 192.168.101.0/24
      - 192.168.102.0/24
      - 192.168.103.0/24
```

```
$ pulumi version
v3.26.1
```

Note: For what it is worth, I was able to use an identical code structure/loop with `ec2.NewSubnet()` and it worked. So appears specific to `ec2.NewEip()` but I'm not entirely sure.

Expected: EIP creation
Actual: Panic error

**Comment by Frassle** [comment] 2022-03-22 10:26
@iwahbe this might be due to yours or mine recent changes to awaitInputs, I can take a look tomorrow if you don't today

**Comment by iwahbe** [comment] 2022-03-22 17:52
https://github.com/pulumi/pulumi/pull/9106 has not merged yet, so I don't think that's the problem. I'll take a look today

**Comment by iwahbe** [comment] 2022-03-23 22:22
It looks like https://github.com/pulumi/pulumi/pull/9197 may have fixed the issue. I can reproduce the issue easily (thanks for the great repro info by the way), but it goes away when I use the latest pulumi (built from master). We will cut a release tomorrow. I'll close this issue after we release. Let us know if the issue persists on the `v3.27.0`.

**Closed** 2022-03-25 16:29 UTC
Labels: kind/bug, p1, impact/panic
