### ISSUE TITLE
Generated program code does not correctly hydrate complex maps from config in TypeScript

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#8348] opened 2021-11-03 19:50 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

There is a slight problem in programgen for allowing complex types to be configurable and hydrating from pulumi.config. The issue with context on where this is being discovered is https://github.com/pulumi/pulumi-terraform-bridge/pull/406 

Given a realistic minified HCL example that looks like this:

```
                          variable "region_number" {
                            default = {
                              us-east-1 = 1
                            }
                          }
```

PCL looks something like this (after the fix in pulumi/pulumi-terraform-bridge#406):

```
config regionNumber "object({us-east-1 = number})" {
    default = {
        us-east-1 = 1
    }
}
```

Generated TypeScript looks like this:

```
import * as pulumi from "@pulumi/pulumi";

const config = new pulumi.Config();

const regionNumber = config.get("regionNumber") || {
    "us-east-1": 1,
};
```

PCL believes the type to be `object({us-east-1 = number})`. 

The issue with the generated TypeScript is that while it compiles, the type of `config.get` is `string` but perhaps we need `getObject` here so that the expected type hydrates? 

### Steps to reproduce

Expected: generated code is configurable through config
Actual: generated code cannot be configured through config

**Comment by justinvp** [comment] 2023-07-27 07:28
Looks like a duplicate of #13433 that has already been fixed.

```
pulumi convert --from terraform --language typescript
```

```typescript
import * as pulumi from "@pulumi/pulumi";

const config = new pulumi.Config();
const regionNumber = config.getObject("regionNumber") || {
    "us-east-1": 1,
};
```

**Closed by justinvp** 2023-07-27 07:28 UTC
Labels: kind/bug, language/javascript, area/codegen, resolution/duplicate
