### ISSUE TITLE
String attributes that starts with " [ foo ] " interpreted as YAML 

### ISSUE THREAD

**Issue by ollaw** [pulumi/pulumi#10312] opened 2022-08-04 14:01 UTC
### What happened?

When running a preview of Pulumi stack, **any string attribute** (for **any component**) that begins with square brackets is wrongly interpreted as YAML.

### Steps to reproduce

```
aws.ec2.SecurityGroup(
    "foo-sg",
    description=f"[foo] some other text"
)
```

### Expected Behavior

Preview output : 
```
description        : "[foo] some other text"
```

### Actual Behavior

Preview output : 

```
description        : (yaml) [
                [0]: "foo"
            ]
```

### Versions used

v3.37.2

### Additional context

It happens with `{}` too.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment] 2023-01-31 20:34
I was able to reproduce this. 😕 `propertyPrinter` takes each property and tries to code it first as JSON, then as YAML, and falls back to plaintext ([code](https://github.com/pulumi/pulumi/blob/master/pkg/backend/display/object_diff.go#L1199-L1227)). I'm not sure why it was implemented this way, I imagine it was because fields in the schema are tagged as string, without richly being tagged as JSON strings or YAML strings. Thus, the engine just has to guess.

**Comment by Frassle** [comment] 2023-01-31 21:34
The string `[foo] text` isn't valid YAML though? Surely it should only be treating it as YAML if the _entire_ string is valid YAML not just a prefix!?

**Comment by RobbieMcKinstry** [comment] 2023-01-31 21:44
I think this behavior is likely because `decoder` is marshalling into an `interface{}`. Technically, an `interface{}` isn't an allowable target [per the YAML docs](https://pkg.go.dev/gopkg.in/yaml.v3#Unmarshal). I wonder if we tried to marshall into `map[string]yaml.Node`, if that would be _more_ correct.

**Comment by Frassle** [comment] 2023-06-23 08:10
Fixed by https://github.com/pulumi/pulumi/commit/3d59a8f49f72f94e266c4b3e20c5677fd80d104b

**Closed by Frassle** 2023-06-23 08:10 UTC
Labels: kind/bug, area/cli, resolution/fixed
