### ISSUE TITLE
aws.lambda.Function() is a noop

### ISSUE THREAD

**Issue by rofr** [pulumi/pulumi#6394] opened 2021-02-20 12:20 UTC
`pulumi preview` is not listing lambdas.

Here is the index.ts:
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const dotNetApplicationPublishFolder = "../src/MyApi/src/MyApi/bin/Debug/netcoreapp3.1/package.zip";

const globalTags = {
    "Application" : "MyApplication",
    "Stack" : pulumi.getStack()
}
function tags(name:String, costType:string) : any {
    return {...globalTags, Name:name, CostType: costType};
 }

 const role = new aws.iam.Role("myrole", {
    assumeRolePolicy : aws.iam.assumeRolePolicyForPrincipal({ Service: "lambda.amazonaws.com" }),
 });

const myLambda = new aws.lambda.Function('docsapi-core',{
    role : role.arn,
    //publish: true,
    tags: tags("DocsApiCore", "Compute"),
    handler : "MyApi::MyApi.LambdaEntryPoint::FunctionHandlerAsync",
    runtime : aws.lambda.DotnetCore3d1Runtime,
    code: new pulumi.asset.AssetArchive({
        ".": new pulumi.asset.FileArchive(dotNetApplicationPublishFolder),
    }),
    environment : {
        variables : {
            //"TABLE_NAME" : dynamoTable.name
        }
    }
});
```
and here is the CLI output of `pulumi preview`
<img width="462" alt="Screenshot 2021-02-20 at 13 16 38" src="https://user-images.githubusercontent.com/806163/108595043-e4b36380-737d-11eb-9168-d0e1f7f64cae.png">

## Expected behavior
Expect to see the lambda in the list of resources to create.

## Steps to reproduce

1. pulumi new, aws-typescript
2. paste the typescript above
3. run pulumi preview

## Context (Environment)
Running on macos big sur, version 2.21.1

**Comment by rofr** [comment] 2021-02-20 12:22
And when I had dependencies on the lambda arns, `pulumi up` failed with a corrupted state that I was unable to recover.

**Comment by austinbutler** [comment] 2021-03-17 23:25
Sounds like it could be similar to the failure I reported here: https://github.com/pulumi/pulumi-aws/issues/1409.

Try [enabling verbose logging](https://www.pulumi.com/docs/troubleshooting/#verbose-logging) and checking the generated logs.

**Comment by mikhailshilkov** [comment] 2022-04-13 13:14
I'm sorry we haven't responded earlier... I tried the example above locally and got the preview displayed correctly

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1454008/163187926-c72a52d0-231d-4523-b2b7-5147862e674a.png">

I suspect there's something else needed to reproduce the error. Since the issue is one year old, I expect there's no repro anymore, so I'll close the issue for now. Feel free to report back if I'm wrong.

**Closed by mikhailshilkov** 2022-04-13 13:14 UTC
Labels: kind/bug, resolution/no-repro
