### ISSUE TITLE
Property '[Symbol.toPrimitive]' is missing in type 'UnwrappedObject<Date>' but required in type 'Date'.

### ISSUE THREAD

**Issue by dimitor115** [pulumi/pulumi#6631] opened 2021-03-28 19:38 UTC
Because of know issue in TypeScript `keyof`: https://github.com/Microsoft/TypeScript/issues/24622 putting a js Date object into `pulumi.output` causes a compilation error: 
` Property '[Symbol.toPrimitive]' is missing in type 'UnwrappedObject<Date>' but required in type 'Date'.`
This issue has been fixed in the upcoming TS 4.3 release, however, this version is scheduled for May 2021 so IMO it's worth introducing a workaround for it.

## Expected behavior
No compilation errors.

## Current behavior
```index.ts:13:61 - error TS2345: Argument of type 'UnwrappedObject<Artefact>' is not assignable to parameter of type 'Artefact'.
  Types of property 'lastModified' are incompatible.
    Property '[Symbol.toPrimitive]' is missing in type 'UnwrappedObject<Date>' but required in type 'Date'.

13 pulumi.output(artefact).apply((a: Unwrap<Artefact>) => test(a))
                                                               ~

  ../../.npm/_npx/26528/lib/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts:114:5
    114     [Symbol.toPrimitive](hint: "default"): string;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    '[Symbol.toPrimitive]' is declared here.


Found 1 error.
```

## Steps to reproduce
1. Clone: https://github.com/dimitor115/pulumi-unwrapped-error-reproduction
2. Run `npm install`
3. Run `npx typescript@latest `

If you run `npx typescript@next` (the upcoming version) there will be no errors.

## Context (Environment)
- Node 15
- TypeScript 4.2.x
- Pulumi 2.23.x

## Affected feature
pulumi.Output<T>

## Potential fix

There are other projects that were facing this issue too:
- https://github.com/ryansolid/solid/issues/228
- https://github.com/vuejs/vue-next/issues/951

As I understand the implemented workarounds in the projects above, the following modification to the UnwrappedObject type will be enough. At least it is compiling with TypeScript 4.2.x now and I'm able to do the `pulumi up`.

```typescript
type AddSymbolToPrimitive<T> = T extends
    {[Symbol.toPrimitive]: infer V;} ?
    {[Symbol.toPrimitive]: V;} :
    {};

export declare type UnwrappedObject<T> = {
    [P in keyof T]: Unwrap<T[P]>;
} & AddSymbolToPrimitive<T>;
```

**Comment by awoimbee** [comment] 2021-07-18 19:39
This is fixed by using `"typescript": "^4.3.5"` (more specifically https://github.com/microsoft/TypeScript/pull/42543).
Just update your `package.json`:
```
{
    "name": "pulumi-wrapper-error-reproduction",
    "devDependencies": {
        "@types/node": "^10.0.0",
	"typescript": "^4.3.5"
    },
    "dependencies": {
        "@pulumi/pulumi": "^2.0.0",
        "@pulumi/aws": "^3.25.1",
        "@pulumi/awsx": "^0.24.0"
    }
}

```

**Comment by EvanBoyle** [comment] 2021-08-06 23:32
closed as resolution is in typescript as described above

**Closed by EvanBoyle** 2021-08-06 23:32 UTC
Labels: kind/bug, language/javascript, resolution/fixed

**Comment by alaniranjan** [comment] 2024-03-26 06:33
The issue is closed because the resolution is in TypeScript as described above.
