### ISSUE TITLE
Local State: The system cannot move the file to a different disk drive.

### ISSUE THREAD

**Issue by Gonkers** [pulumi/pulumi#15379] opened 2024-02-05 23:41 UTC
### What happened?

I was trying to move local state from my user directory to my project directory which happens to live on a different drive.

### Example

```
PS D:\pulumi-login> pulumi login --local
Logged in to PC as PC\Gonkers (file://~)
PS D:\pulumi-login> pulumi login file://.
error: problem logging in: write ".pulumi\\meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): rename C:\Users\gonkers\AppData\Local\Temp\meta.yaml.17b11bb2665c07b8.tmp D:\pulumi-login\.pulumi\meta.yaml: The system cannot move the file to a different disk drive.
```

### Output of `pulumi about`

PS D:\pulumi-login> pulumi about
CLI
Version      3.104.2
Go Version   go1.21.6
Go Compiler  gc

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64

Backend
Name           TUVOK
URL            file://~
User           PC\Gonkers
Organizations
Token type     personal

### Additional context

I assume this is a common Python dev issue. Use `shutil.move()` rather than `os.rename()`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-02-05 23:43
Duplicate of https://github.com/pulumi/pulumi/issues/15352, this will be fixed in this weeks release.

> I assume this is a common Python dev issue. 

The code doing this is actually written in Go (https://github.com/google/go-cloud), but yes; exactly that problem. Fix in this weeks release works around it by telling gocloud not to use /tmp (which was it's old behavior).

**Closed by Frassle** 2024-02-05 23:44 UTC
Labels: kind/bug, area/backends, resolution/duplicate

**Comment by Gonkers** [comment] 2024-02-05 23:58
Ah, thanks. I did a quick search but didn't get a hit. Quick reply 👍
