### ISSUE TITLE
err: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by punkdata** [pulumi/pulumi#2922] opened 2019-07-11 11:16 UTC
I'm experiencing this error on all of my pulumi python apps when running `pulumi up`. My code hasn't changed and this error is popping up on all my projects. It creates the GKE cluster and 3 nodes but bombs out after that with the panic error shown below.

Pulumi v0.17.21
Operating systems tested:  OSX and Linux

```shell
Previewing update (k8s):

     Type                            Name                      Plan
 +   pulumi:pulumi:Stack             nodejs-cicd-workshop-k8s  create
 +   ├─ gcp:container:Cluster        cicd-app                  create
 +   ├─ pulumi:providers:kubernetes  cicd-app                  create
 +   ├─ kubernetes:core:Namespace    cicd-app                  create
 +   ├─ kubernetes:apps:Deployment   cicd-app                  create
 +   └─ kubernetes:core:Service      cicd-app                  create

Resources:
    + 6 to create

Do you want to perform this update? yes
Updating (k8s):

     Type                      Name                      Status                  Info
 +   pulumi:pulumi:Stack       nodejs-cicd-workshop-k8s  creating...             	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google +   pulumi:pulumi:Stack       nodejs-cicd-workshop-k8s  creating...             	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/resource.go +   pulumi:pulumi:Stack       nodejs-cicd-workshop-k8s  creating...             	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/provider.go +   pulumi:pulumi:Stack       nodejs-cicd-workshop-k8s  creating...             	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider +   pulumi:pulumi:Stack       nodejs-cicd-workshop-k8s  creating...             	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:133 +   pulumi:pulumi:Stack       nodejs-cicd-workshop-k8s  creating...             	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/ser +   pulumi:pulumi:Stack       nodejs-cicd-workshop-k8s  creating...             	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:133 +   pulumi:pulumi:Stack       nodejs-cicd-workshop-k8s  **creating failed**     1 error; 29 messages
 +   └─ gcp:container:Cluster  cicd-app                  **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (nodejs-cicd-workshop-k8s):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x218a339]
    goroutine 14 [running]:
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.flattenMaintenancePolicy(...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:2047
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterRead(0xc000144cb0, 0x27b6f40, 0xc00042e000, 0x25fc500, 0x3e0b2e0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:909 +0x22d9
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterCreate(0xc000144cb0, 0x27b6f40, 0xc00042e000, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:859 +0x18f5
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000372230, 0xc00009a500, 0xc000441ac0, 0x27b6f40, 0xc00042e000, 0xc000441a01, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x351
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0003f6bd0, 0xc000813800, 0xc00009a500, 0xc000441ac0, 0xc000441ac0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0x9c
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc0004d6a00, 0x2d885a0, 0xc0002bc930, 0xc0004c8040, 0xc0004d6a00, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:583 +0x553
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x2d885a0, 0xc0002bc930, 0x29f11e0, 0xc0004c8040, 0x2d885a0, 0xc0002bc930, 0x2d918e0, 0x3eb3370)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1331 +0x86
    github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x2d885a0, 0xc0002bc930, 0x29f11e0, 0xc0004c8040, 0xc00000a7a0, 0xc00000a8e0, 0x0, 0x0, 0x2d745c0, 0xc0004be1f0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57 +0x2b0
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x2acff40, 0xc0004d6a00, 0x2d885a0, 0xc0002bc060, 0xc000144070, 0xc00041f7e0, 0x0, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1333 +0x158
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b81c0, 0x2d8ffa0, 0xc0000d0000, 0xc0002cc100, 0xc0003db620, 0x3e85d90, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:1026 +0x4cd
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001b81c0, 0x2d8ffa0, 0xc0000d0000, 0xc0002cc100, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:1252 +0x1308
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000256440, 0xc0001b81c0, 0x2d8ffa0, 0xc0000d0000, 0xc0002cc100)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:699 +0x9f
    created by github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:697 +0xa1

    error: update failed

  gcp:container:Cluster (cicd-app):
    error: Plan apply failed: transport is closing

Resources:
    + 1 created

Duration: 2m32s
```

**Comment by stack72** [comment] 2019-07-11 16:41
Hi @punkdata 	

Please can you confirm the version of the pulumi-gcp provider that you are using? You will be able to get it from your pip requirements file OR your package.json file

Thanks

Paul

**Comment by punkdata** [comment] 2019-07-12 00:41
Hi @stack72 Here are the python libs I'm using
pulumi-0.17.22 
pulumi-gcp-0.18.12 
pulumi-kubernetes-0.25.2

I reinstalled them but I get the same error when I run pulumi up

```shell
panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25ec08d]
    goroutine 21 [running]:
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.flattenMaintenancePolicy(...)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:2470
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterRead(0xc0002ba460, 0x2cde9c0, 0xc000298d80, 0x2ae82e0, 0x4956da0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:1144 +0x2b8d
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterCreate(0xc0002ba460, 0x2cde9c0, 0xc000298d80, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:1094 +0x218c
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000172180, 0xc0006a8370, 0xc00091b480, 0x2cde9c0, 0xc000298d80, 0xc00091b401, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x3b4
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00050ce00, 0xc00068b840, 0xc0006a8370, 0xc00091b480, 0xc00091b480, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc0004b5680, 0x3513540, 0xc000683ad0, 0xc0009154c0, 0xc0004b5680, 0x2ccb901, 0xc000915700)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:611 +0x550
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x3513540, 0xc000683ad0, 0x2f6d980, 0xc0009154c0, 0x3012fe0, 0x4a09458, 0x3513540, 0xc000683ad0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1516 +0x86
    github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3513540, 0xc000683470, 0x2f6d980, 0xc0009154c0, 0xc00091b080, 0xc00091b0a0, 0x0, 0x0, 0x34c3be0, 0xc0003fd5b0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x30650a0, 0xc0004b5680, 0x3513540, 0xc000683470, 0xc0006a82d0, 0xc00053a020, 0x3513540, 0xc000683470, 0xc0006b2000, 0x33a)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1518 +0x158
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b7200, 0x3525280, 0xc000082780, 0xc0001cae00, 0xc0005381e0, 0x49db9d0, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:972 +0x470
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000b7200, 0x3525280, 0xc000082780, 0xc0001cae00, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:1252 +0xda6
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003f0050, 0xc0000b7200, 0x3525280, 0xc000082780, 0xc0001cae00)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:691 +0x9f
    created by github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:689 +0xa1

  gcp:container:Cluster (cicd-app):
    error: Plan apply failed: transport is closing
```

**Comment by lee-baines** [comment] 2019-07-12 10:04
I've also just received this same error this morning for the first time after creating a GKE cluster:

  pulumi:pulumi:Stack (gke-cdm-gke-medium):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x249f7e0]
    goroutine 148 [running]:
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.flattenMaintenancePolicy(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:2201
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterRead(0xc000241d50, 0x2b31020, 0xc0000acb60, 0x12, 0xc0001ce080)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:998 +0x24e0
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterCreate(0xc000241d50, 0x2b31020, 0xc0000acb60, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:948 +0x1fe6
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0004d6c00, 0xc0002091d0, 0xc0008b2ea0, 0x2b31020, 0xc0000acb60, 0xc0008b2e01, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x3b4
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000011380, 0xc0006b1868, 0xc0002091d0, 0xc0008b2ea0, 0xc0008b2ea0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc0000c9320, 0x32f6960, 0xc000505560, 0xc0005df700, 0xc0000c9320, 0x2b20201, 0xc0005df8c0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:599 +0x550
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x32f6960, 0xc000505560, 0x2d92180, 0xc0005df700, 0x2e2c360, 0x46acfc0, 0x32f6960, 0xc000505560)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1331 +0x86
    github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x32f6960, 0xc000504d80, 0x2d92180, 0xc0005df700, 0xc0008400a0, 0xc0008400c0, 0x0, 0x0, 0x32ac300, 0xc0002cf9a0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x2e77d00, 0xc0000c9320, 0x32f6960, 0xc000504d80, 0xc000209180, 0xc00000c460, 0x32f6960, 0xc000504d80, 0xc000948000, 0x366)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1333 +0x158
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000552480, 0x3307a80, 0xc000552900, 0xc0005a6900, 0xc00051c1e0, 0x467fbd0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:971 +0x470
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000552480, 0x3307a80, 0xc000552900, 0xc0005a6900, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:1250 +0xd25
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000488460, 0xc000552480, 0x3307a80, 0xc000552900, 0xc0005a6900)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:690 +0x9f
    created by github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:688 +0xa1
 
    error: update failed
 
  gcp:container:Cluster (cdm-cluster):
    error: Plan apply failed: transport is closing

**Comment by lee-baines** [comment] 2019-07-12 10:05
"dependencies": {
        "@pulumi/gcp": "^0.18.7",
        "@pulumi/kubernetes": "^0.24.0",
        "@pulumi/pulumi": "^0.17.17"
    }

**Comment by lukehoban** [comment] 2019-07-12 19:22
Just to check - does anyone have a reduced repro of this available?

**Comment by lukehoban** [comment] 2019-07-12 19:35
I tried using https://github.com/pulumi/examples/tree/master/gcp-ts-gke with latest packages and could not reproduce this.

If anyone has a repro - that will be important to narrow down the issue.

**Comment by punkdata** [comment] 2019-07-12 19:41
Hi @lukehoban I noticed your testing this with the JavaScript examples but I'm able to reproduce this on my machines with the python SDK for pulumi. I'm not sure if that makes a difference on your end but I just wanted to point that out to you

**Comment by lukehoban** [comment] 2019-07-12 19:57
It looks like @lee-baines was hitting this from JavaScript, and the error message suggests this should be unrelated to language. So I suspect it is related to some more specific configuration of the cluster. A repro code example would be helpful.

**Comment by lee-baines** [comment] 2019-07-12 21:56
You can see my code @lukehoban here: https://github.com/ForgeRock/forgeops/tree/master/pulumi/gke.
The stack I deployed today was identical to gke-small stack in the above repo.  I get the same error with this stack.  Only way to fix is to delete cluster in GCP console the run Pulumi destroy.

**Comment by punkdata** [comment] 2019-07-13 00:55
@lukehoban @stack72 here is the code that failing for me
👇
https://github.com/datapunkz/orb-pulumi-gcp/tree/master/pulumi/gcp/gke

**Comment by lukehoban** [comment] 2019-07-14 20:53
This is being tracked upstream at https://github.com/terraform-providers/terraform-provider-google/issues/4023 as well.

**Comment by punkdata** [comment] 2019-07-16 00:49
Seem like there is a work around
https://github.com/terraform-providers/terraform-provider-google/issues/4010#issuecomment-511450980

**Comment by punkdata** [comment] 2019-07-16 00:55
Also it looks like they're applying fix soon https://github.com/terraform-providers/terraform-provider-google/issues/4023#issuecomment-511474287

**Comment by stack72** [comment] 2019-07-16 00:56
ah nice one @punkdata - as soon as it hits tomorrow, I will update the provider!

**Comment by punkdata** [comment] 2019-07-16 00:58
That would be great!

**Comment by stack72** [comment] 2019-07-16 01:08
FYI, this is the fix...

https://github.com/terraform-providers/terraform-provider-google-beta/commit/2f8265bfd3c31c9b4d5c97822301926434aa9639

**Comment by lee-baines** [comment] 2019-07-16 08:44
weirdly I've noticed I only get this error with certain regions/zones but not others.  I'm not sure how this correlates with the fix above but I'll test it out too.

**Comment by stack72** [comment] 2019-07-16 22:08
Closed via https://github.com/pulumi/pulumi-gcp/pull/180

**Closed** 2019-07-22 22:58 UTC
Labels: feature/q3, kind/bug
