### ISSUE TITLE
 `panic: interface conversion: interface {} is nil, not map[string]interface {}` while updating AWS SSM parameter

### ISSUE THREAD

**Issue by itsx** [pulumi/pulumi#9907] opened 2022-06-21 13:50 UTC
### What happened?

I'm trying to update **AWS SSM parameter** SecureString in Parameters Store with a new value in existing stack, and I am getting panic from the Pulumi CLI and also from the Pulumi GHA action with an error starting "`panic: interface conversion: interface {} is nil, not map[string]interface {}`" I tried to change other resources in the stack and everything except SSM parameter seem to work ok.

`pulumi up` output:

```
Diagnostics:
    pulumi:pulumi:Stack (project-prod):
      Failed to resolve python version command: fork/exec /home/runner/work/project/project/infra/venv/bin/python: no such file or directory
      E0621 08:35:08.042944994    2431 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers

` panic: interface conversion: interface {} is nil, not map[string]interface {}`
      goroutine 64 [running]:
      github.com/hashicorp/go-cty/cty.Value.GetAttr({{{0xabeb878?, 0xc002580c60?}}, {0x0?, 0x0?}}, {0x9df72ae, 0x4})
        /home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:711 +0x2ed
      github.com/hashicorp/terraform-provider-aws/internal/service/ssm.resourceParameterUpdate(0xc0023dcf80, {0x88cab00?, 0xc000ce0a80})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20220610095326-146e77fb191b/internal/service/ssm/parameter.go:282 +0x3e9
      github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xabeaab0?, {0xabeaab0?, 0xc000058318?}, 0xd?, {0x88cab00?, 0xc000ce0a80?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220505215311-795430389fa7/helper/schema/resource.go:719 +0x178
      github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001471450, {0xabeaab0, 0xc000058318}, 0xc0023df450, 0xc0023dca00, {0x88cab00, 0xc000ce0a80})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220505215311-795430389fa7/helper/schema/resource.go:837 +0x605
      github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0xc001ec38b0?}, {0x9e41e25, 0x11}, {0xabeb920?, 0xc0023e2170}, {0xabf0ed0?, 0xc0023dca00})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.24.1/pkg/tfshim/sdk-v2/provider.go:112 +0x19b
      github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Update(0xc0003bc000, {0xabeab20?, 0xc0023da510?}, 0xc001fe1f80)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.24.1/pkg/tfbridge/provider.go:1052 +0x86f
      github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1({0xabeab20, 0xc0023da510}, {0x9b502a0?, 0xc001fe1f80})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/proto/go/provider.pb.go:2650 +0x7b
      github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xabeab20, 0xc0023da060}, {0x9b502a0, 0xc001fe1f80}, 0xc0023ca780, 0xc0023c8960)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
      github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler({0x9c8ab60?, 0xc0003bc000}, {0xabeab20, 0xc0023da060}, 0xc001fc91a0, 0xc001ba60c0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.33.1/proto/go/provider.pb.go:2652 +0x138
      google.golang.org/grpc.(*Server).processUnaryRPC(0xc000ffee00, {0xabf1108, 0xc000f5da00}, 0xc0023d8000, 0xc001b9d9b0, 0x1174e6d0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
      google.golang.org/grpc.(*Server).handleStream(0xc000ffee00, {0xabf1108, 0xc000f5da00}, 0xc0023d8000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
      google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
      created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

    aws:ssm:Parameter (/project/mongodb_uri):
      error: error reading from server: read tcp 127.0.0.1:37022->127.0.0.1:45037: read: connection reset by peer

    aws:ecr:LifecyclePolicy (project-lifecycle-policy):
      error: error reading from server: read tcp 127.0.0.1:37022->127.0.0.1:45037: read: connection reset by peer
```

### Steps to reproduce

__main__.py:

```
import pulumi
import pulumi_aws as aws

config = pulumi.Config()

# Read the configuration from Pulumi stack config and store it in
# Systems Manager parameters.
mongodb_uri_parameter = aws.ssm.Parameter(
    "/project/mongodb_uri",
    name="/project/mongodb_uri",
    type="SecureString",
    value=config.require_secret("mongodb_uri"),
    overwrite=True,
)
```
Console:

```
pulumi config set mongodb_uri \
  'mongodb:/project:*****@'`
  `'mongo1.company.internal,mongo2.company.internal,mongo3.company.internal/?'`
  `'replicaSet=rs0&connectTimeoutMS=5000&w=1&wtimeoutMS=3000&'`
  `'readPreference=primaryPreferred&maxStalenessSeconds=-1&'`
  `'authSource=istav&authMechanism=SCRAM-SHA-1' --secret
  
  pulumi up
```

### Expected Behavior

Should be able to update SSM parameter via Pulumi stack.

### Actual Behavior

`pulumi up` ends with described error. `pulumi preview` ends without errors

### Versions used

CLI          
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME      VERSION
aws       5.8.0
aws-tags  0.4.1
docker    3.2.0
python    unknown

Host     
OS       ubuntu
Version  18.04
Arch     x86_64

This project is written in python: executable='/home/tom/repos/project/infra/venv/bin/python3' version='3.8.13'

Current Stack: project-prod

TYPE                                                        URN
pulumi:pulumi:Stack                                         urn:pulumi:...
...
...
...
...

Found no pending operations associated with project-prod

Backend        
Name           tom-Lenovo-V310-15IKB
URL            s3://pulumi.company.cz
User           tom
Organizations  

Dependencies:
NAME             VERSION
pip              22.0.4
pulumi-aws-tags  0.4.1
pulumi-docker    3.2.0
setuptools       56.0.0

Pulumi locates its logs in /tmp by default

### Additional context

After I have changed the SSM parameter in AWS console manually,` pulumi up `ends without an error (there was no real update because SSM paramter was manually changed to have the same value).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment] 2022-06-24 23:37
Resolving as duplicate of https://github.com/pulumi/pulumi-aws/issues/2017.  We're working on addressing the underlying cause of that issue in https://github.com/pulumi/pulumi-terraform-bridge/issues/548.

**Closed by lukehoban** 2022-06-24 23:37 UTC
Labels: kind/bug, resolution/duplicate
