### ISSUE TITLE
Error converting TF codebase

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi#13761] opened 2023-08-23 20:40 UTC
### What happened?

I got an error converting https://github.com/aws-samples/hub-and-spoke-with-inspection-vpc-terraform 

### Expected Behavior

No error.

### Steps to reproduce

```bash
$ ﻿﻿pulumi convert --from terraform --out ./pulumi --language typescript
Converting from terraform...
Downloading provider: terraform
warning: failed to install provider "awscc": could not find latest version for provider awscc: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-awscc/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
2023/08/23 13:10:47 [INFO] Creating Provider

warning: /Users/jkodroff/src/aws-samples/hub-and-spoke-with-inspection-vpc-terraform/providers.tf:19,1-15: Failed to evaluate provider config; Could not evaluate expression for aws:region
warning: /Users/jkodroff/src/aws-samples/hub-and-spoke-with-inspection-vpc-terraform/providers.tf:22,1-17: Failed to get provider info; Failed to get provider info for "awscc": could not find mapping information for provider awscc; try installing a pulumi plugin that supports this terraform provider
warning: /Users/jkodroff/src/aws-samples/hub-and-spoke-with-inspection-vpc-terraform/providers.tf:22,1-17: Failed to evaluate provider config; Could not evaluate expression for awscc:region
warning: /Users/jkodroff/src/aws-samples/hub-and-spoke-with-inspection-vpc-terraform/main.tf:105,30-157: Function not yet implemented; Function values not yet implemented
warning: /Users/jkodroff/src/aws-samples/hub-and-spoke-with-inspection-vpc-terraform/main.tf:157,30-158: Function not yet implemented; Function values not yet implemented
Converting to nodejs...
Downloading provider: std
================================================================================
The Pulumi CLI encountered a code generation error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.78.1
error: main.pp:8,1-38,2: circular reference;
error: main.pp:146,1-186,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/network-hubandspoke_2.0.0/main.pp:25,1-44,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/network-hubandspoke_2.0.0/vpc_3.0.1/main.pp:0,0-4,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; , and 20 other diagnostic(s); /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/network-hubandspoke_2.0.0/vpc_3.0.1/main.pp:0,0-4,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; , and 20 other diagnostic(s), and 7 other diagnostic(s); /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/network-hubandspoke_2.0.0/main.pp:25,1-44,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/network-hubandspoke_2.0.0/vpc_3.0.1/main.pp:0,0-4,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; , and 20 other diagnostic(s); /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/network-hubandspoke_2.0.0/vpc_3.0.1/main.pp:0,0-4,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [new_bits name]; , and 20 other diagnostic(s), and 7 other diagnostic(s)
error: main.pp:8,1-38,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/main.pp:0,0-4,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [name new_bits]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [name new_bits]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [name new_bits]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [name new_bits]; , and 27 other diagnostic(s); /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/main.pp:0,0-4,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [name new_bits]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [name new_bits]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/main.pp:14,1-21,2: /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [name new_bits]; ; /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/pulumi-convert3334539032/vpc_3.2.1/modules/calculate_subnets/subnets_1.0.2/main.pp:11,16-24: unknown property 'newBits' among [name new_bits]; , and 27 other diagnostic(s)
error: could not generate output program
```

### Output of `pulumi about`

```text
CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Host     
OS       darwin
Version  13.5
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jkodroff
User           jkodroff
Organizations  jkodroff, oracle-workshop, jkodrofftest, zephyr, demo, pulumi

Pulumi locates its logs in /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment] 2023-08-23 21:33
The main issue here is the circular reference error, which is allowed in terraform module declarations but not in Pulumi (yet) duplicate of #13581

**Closed by Zaid-Ajaj** 2023-08-23 21:33 UTC
Labels: kind/bug, resolution/duplicate
