### ISSUE TITLE
Ctrl-C doesn't stop plugin download

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3718] opened 2020-01-06 12:24 UTC
(spotted from the airplane)

While `pulumi up` is downloading a plugin, Ctrl-C doesn't stop the progress

```
[resource plugin azure-1.5.0-alpha.1573228289+g468fb3d6] installing

System Messages
  ^C received; cancelling. If you would like to terminate immediately, press ^C again.
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
Downloading plugin: 25.57 MiB / 46.03 MiB [============>---------]  55.55% 4m48s
```

I'm on Windows Terminal.

**Comment by lukehoban** [comment] 2020-01-06 16:26
I believe this is a dupe of https://github.com/pulumi/pulumi/issues/3649 (also found on an airplane :-)).

**Closed by lukehoban** 2020-01-06 16:26 UTC

**Comment by mikhailshilkov** [comment] 2020-01-07 00:34
Great! My search on Ctrl-C didn't work for a MacOS issue...

**Comment by joeduffy** [comment] 2020-01-07 05:11
Might I suggest we do a future bug bash entirely from airplanes traveling between different continents?
