### ISSUE TITLE
Remember resource object source locations

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#114] opened 2017-03-03 02:15 UTC
At the moment, in the translation from evaluation to a resource graph, we toss away some very valuable information about source locations.  This means that once we enter "resource realm", we lose our ability to deliver great diagnostics.  And, worst case, automatic edits will be impossible.

There is no technical reason for this limitation; we should preserve this information -- by tracking the "last writes" to resource properties -- and even serialize it so that it's entirely recoverable. 

As part of this, we may also want to consider the moral equivalent of a PDB file so that the source information can be stored optionally elsewhere, so as not to clutter up the checkpoints; it will almost certainly make them enormous, and diffs will be problematic.

**Comment by swgillespie** [comment] 2018-08-14 16:37
Closing as a dupe of https://github.com/pulumi/pulumi/issues/899.

**Closed by swgillespie** 2018-08-14 16:37 UTC
Labels: area/core, area/tools, impact/usability, kind/enhancement
