### ISSUE TITLE
ReplaceOnChanges option isn't applied if provider's diff is unknown

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#8487] opened 2021-11-23 20:33 UTC
The AWS Native provider is somewhat simplistic in diff calculation: it returns `DiffResponse_DIFF_UNKNOWN` and relies on the engine to calculate the actual detailed diff (which is a supported scenario, if I read the docs correctly):

https://github.com/pulumi/pulumi-aws-native/blob/dc7de1c4676854d8cbaaf7a475112f125e52fe9b/provider/pkg/provider/provider.go#L582-L585

It works for the UI experience, but apparently it doesn’t work for `replaceOnChanges` option that users set in their programs as reported in https://github.com/pulumi/pulumi-aws-native/issues/240 

I reproduced it with basic TS and Python programs, e.g.

```ts
import * as aws from "@pulumi/aws-native";

const logGroup = new aws.logs.LogGroup("log-test", {
    retentionInDays: 30,
}, { replaceOnChanges: ["retentionInDays"]});
```

Deploy, change the value of `retentionInDays`, run preview.

I'm advocating for the possibility of having a diff by default, so that new providers don’t have to dive into the details of diff calculation unless they have to. I understand that the engine doesn’t have all the information that the provider could use - but I also think the engine can be a good-enough baseline.

**Comment by iwahbe** [comment] 2021-11-23 23:26
The problem is here:
https://github.com/pulumi/pulumi/blob/4b7985384ce940ce72f256068c6057eb7d0dce80/pkg/resource/deploy/step_generator.go#L1134-L1140
When the engine computes the diff, it doesn't compute the changed fields. https://github.com/pulumi/pulumi/blob/4b7985384ce940ce72f256068c6057eb7d0dce80/pkg/resource/deploy/step_generator.go#L1252 doesn't have anything to act on, and so `replaceOnChanges` does nothing. 

This can be fixed inside the engine by computing the change instead of relying only on `deepEquals` 

I'm pretty sure that the UI experience is driven by the step generator, which does see specific fields.

**Closed** 2021-11-30 20:25 UTC
Labels: kind/bug, size/S, area/core, capacity/quality
