### ISSUE TITLE
Proxy related gRPC failures lead to `pulumi up` failures with no output

### ISSUE THREAD

**Issue by jeusdi** [pulumi/pulumi#2651] opened 2019-04-17 06:28 UTC
I've installed [k3s](https://k3s.io/).

`k3s` installation places a kubeconfig file at `/etc/rancher/k3s/k3s.yaml`. I've set `KUBECONFIG` environment variable to this location.

After that, I've logged in into local `pulumi login --local`.

This is my straightforward code:

```
import * as k8s from "@pulumi/kubernetes";

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: { containers: [{ name: "nginx", image: "nginx" }] }
        }
    }
});
export const name = deployment.metadata.apply(m => m.name);
```

Nevertheless, it seems pulumi is recognizing nothing:

![image](https://user-images.githubusercontent.com/941639/56265684-77cc4400-60ea-11e9-8880-d22f3c822039.png)

**Comment by lukehoban** [comment] 2019-04-17 14:33
Definitely unexpected to see no other output from `pulumi up`. Could you share output of `pulumi update —logtostderr -v=7`?

**Comment by jeusdi** [comment] 2019-04-17 16:59
```
Previewing update (dev):
I0417 18:59:02.262589    9132 plugins.go:75] gatherPluginsFromProgram(): gathering plugins from language host
I0417 18:59:02.262814    9132 plugins.go:372] GetPluginPath(language, nodejs, <nil>): found on $PATH /home/jeusdi/.pulumi/bin/pulumi-language-nodejs
I0417 18:59:02.497556    9132 langruntime_plugin.go:168] langhost[nodejs].GetPluginInfo() executing
I0417 18:59:02.517031    9132 langruntime_plugin.go:83] langhost[nodejs].GetRequiredPlugins(proj=k8slocal,pwd=/home/jeusdi/projects/espaidoc/infrastructure/pulumi,program=.) executing
I0417 18:59:03.203174    9132 langruntime_plugin.go:124] langhost[nodejs].GetRequiredPlugins(proj=k8slocal,pwd=/home/jeusdi/projects/espaidoc/infrastructure/pulumi,program=.) success: #versions=1
I0417 18:59:03.203288    9132 plugins.go:82] gatherPluginsFromProgram(): plugin nodejs <nil> is required by language host
I0417 18:59:03.203332    9132 plugins.go:82] gatherPluginsFromProgram(): plugin kubernetes 0.22.2 is required by language host
I0417 18:59:03.203370    9132 plugins.go:93] gatherPluginsFromSnapshot(): gathering plugins from snapshot
I0417 18:59:03.203404    9132 plugins.go:96] gatherPluginsFromSnapshot(): no snapshot available, skipping
I0417 18:59:03.203440    9132 plugins.go:134] ensurePluginsAreInstalled(): beginning
I0417 18:59:03.203521    9132 plugins.go:372] GetPluginPath(language, nodejs, <nil>): found on $PATH /home/jeusdi/.pulumi/bin/pulumi-language-nodejs
I0417 18:59:03.203559    9132 plugins.go:139] ensurePluginsAreInstalled(): plugin nodejs <nil> already installed
I0417 18:59:03.203661    9132 plugins.go:411] GetPluginPath(resource, kubernetes, 0.22.2): enabling new plugin behavior
I0417 18:59:03.203704    9132 plugins.go:493] SelectCompatiblePlugin(..., kubernetes): beginning
I0417 18:59:03.203739    9132 plugins.go:532] SelectCompatiblePlugin(..., kubernetes): failed to find match
I0417 18:59:03.203801    9132 plugins.go:147] ensurePluginsAreInstalled(): plugin kubernetes 0.22.2 not installed, doing install
I0417 18:59:03.203838    9132 plugins.go:167] installPlugin(kubernetes, 0.22.2): beginning install
I0417 18:59:03.203879    9132 plugins.go:154] ensurePluginsAreInstalled(): completed
I0417 18:59:03.203912    9132 update.go:131] newUpdateSource(): failed to install missing plugins: downloading plugins at runtime not available when using local backend
I0417 18:59:03.203956    9132 plugins.go:238] computeDefaultProviderPlugins(): considering nodejs
I0417 18:59:03.203994    9132 plugins.go:238] computeDefaultProviderPlugins(): considering kubernetes-0.22.2
I0417 18:59:03.204546    9132 plugins.go:267] computeDefaultProviderPlugins(): plugin kubernetes-0.22.2 selected for package kubernetes (first seen)
I0417 18:59:03.204594    9132 plugins.go:273] computeDefaultProviderPlugins(): summary of default plugins:
I0417 18:59:03.204628    9132 plugins.go:275]   kubernetes      = 0.22.2
I0417 18:59:03.205567    9132 plan_executor.go:251] planExecutor.retirePendingDeletes(...): no pending deletions
I0417 18:59:03.205639    9132 plan_executor.go:138] planExecutor.Execute(...): waiting for incoming events

I0417 18:59:03.205755    9132 langruntime_plugin.go:135] langhost[nodejs].Run(pwd=/home/jeusdi/projects/espaidoc/infrastructure/pulumi,program=.,#args=0,proj=k8slocal,stack=dev,#config=0,dryrun=true) executing
I0417 18:59:03.205928    9132 step_executor.go:310] StepExecutor worker(-2): worker coming online
I0417 18:59:03.206368    9132 step_executor.go:310] StepExecutor worker(-2): worker waiting for incoming chains
I0417 18:59:04.361171    9132 langruntime_plugin.go:161] langhost[nodejs].RunPlan(pwd=/home/jeusdi/projects/espaidoc/infrastructure/pulumi,program=.,...,dryrun=true) success: progerr=
I0417 18:59:04.362048    9132 source_eval.go:163] EvalSourceIterator ended with bail.
I0417 18:59:04.362066    9132 plan_executor.go:142] planExecutor.Execute(...): incoming event (nil? true, &{<nil>})
I0417 18:59:04.362139    9132 step_executor.go:310] StepExecutor worker(-1): StepExecutor.waitForCompletion(): waiting for worker threads to exit
I0417 18:59:04.362157    9132 step_executor.go:310] StepExecutor worker(-2): worker exiting due to cancellation
I0417 18:59:04.362187    9132 step_executor.go:310] StepExecutor worker(-1): StepExecutor.waitForCompletion(): worker threads all exited
I0417 18:59:04.362212    9132 plan_executor.go:195] planExecutor.Execute(...): step executor has completed
I0417 18:59:04.362252    9132 ignore.go:44] Explicitly ignoring and discarding error: rpc error: code = Canceled desc = grpc: the client connection is closing
I0417 18:59:04.362334    9132 plan_executor.go:72] planExecutor.Execute(...): exiting provider canceller
```

**Comment by swgillespie** [comment] 2019-04-17 18:26
Hmm, very possible that we dropped an error message from the language host here.

**Comment by lukehoban** [comment] 2019-04-17 18:29
@swgillespie Anything that @jeusdi can do to gather more information to pin down the potential problem here?

**Comment by swgillespie** [comment] 2019-04-17 18:29
I'm not sure, @CyrusNajmabadi do you know?

**Comment by redbaron** [comment] 2019-08-08 10:37
@ellismg , @lukehoban , We have exactly same problem, but with GCP resources. We running Pulumi in a docker container if it makes any difference

**Comment by redbaron** [comment] 2019-08-08 13:15
I started pulumi with `NODE_OPTIONS=--inspect-brk` and attached debugger, there are definitely errors in vars, but they are not reported (nodejs langhost never exits with 1):

![Screenshot from 2019-08-08 14-12-06](https://user-images.githubusercontent.com/16624/62706178-e6f5dd00-b9e6-11e9-96f3-ac2d613dfe15.png)

**Comment by redbaron** [comment] 2019-08-08 13:30
OMG, I think I tracked it down, it is a space in ` no_proxy` env var which throws it off.

Silently fails:

```
https_proxy="proxy"
no_proxy="localhost, 127.0.0.1,.mycorp"
```

Works (no spaces in no_proxy):
```
https_proxy="proxy"
no_proxy="localhost,127.0.0.1,.mycorp"
```

FYO, `curl` is happy with either of them

It seems that errors connecting to engine & monitor are not reported to user by neither nodejs nor pulumi-language-nodejs

**Comment by lukehoban** [comment] 2019-08-08 16:36
Fascinating.  Thanks for tracking that down @redbaron!  We'll look into this.

**Comment by lukehoban** [comment] 2019-08-08 16:55
This looks like it may be a bug in gRPC:

https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/http_proxy.cc#L143

**Comment by redbaron** [comment] 2019-08-08 17:01
I see 2 bugs here:

- first and most important one is that error was not reported to user except by the exit code. this is a bug somewhere in pulumi
- less important, is that values in comma separated `no_proxy` are not stripped  of spaces.

**Comment by lukehoban** [comment] 2019-08-08 17:03
Yes - there is definitely a Pulumi bug that we are not reported this error correctly - we'll fix that.

But the root cause seems to be that gRPC is not trimming spaces in its `no_proxy` parsing. 

FWIW - in contrast `go` HTTP(s) does this correctly https://github.com/golang/net/blob/master/http/httpproxy/proxy.go#L219

**Comment by lunaris** [comment] 2024-09-05 13:28
I think this is now fixed -- the latest version of grpc/grpc works as follows:

* `no_proxy` is used as part of a call to `AddressIncluded`, to see if a given HTTP host is specified in `no_proxy` -- https://github.com/grpc/grpc/blob/master/src/core/handshaker/http_connect/http_proxy_mapper.cc#L242
* `AddressIncluded` splits on `,` and trims each entry (see the `StripAsciiWhitespace` call) -- https://github.com/grpc/grpc/blob/master/src/core/handshaker/http_connect/http_proxy_mapper.cc#L92

This change has been in grpc/grpc since at least March 2023 (https://github.com/grpc/grpc/commit/4110dea333f047b2c9eb89afa3ff3fd045589fc1#diff-eaba5f070837d040ea455acb333196910b2acea2b2a3518d933337cfb0a74cadR202). Consequently, I think Pulumi is using a recent-enough version to pick this up, and can't reproduce it on a recent version:

1. `proxy` is a non-existent hostname, and we only disable proxying on `localhost`. Calls to `api.pulumi.com` (necessary because I'm testing a stack with the Pulumi Cloud backend) fail:
```
(export HTTPS_PROXY=proxy; export NO_PROXY=localhost; pulumi refresh --preview-only)
Error: performing HTTP request: Post "https://api.pulumi.com/api/...": proxyconnect tcp: dial tcp: lookup proxy on 127.0.0.53:53: server misbehaving
```

2. Now we disable proxying for api.pulumi.com. We get a bit further:
```
(export HTTPS_PROXY=proxy; export NO_PROXY="localhost,api.pulumi.com"; pulumi refresh --preview-only)
Previewing refresh (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

...
```
3. Now we introduce a space to `NO_PROXY`. Everything works as before, indicating that hopefully this issue is fixed:
```
(export HTTPS_PROXY=proxy; export NO_PROXY="localhost, api.pulumi.com"; pulumi refresh --preview-only)
Previewing refresh (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/...

...
```

Moreover, whenever connections fail due to a bad proxy, it appears as though we do now report errors. This appears to be true even when the error happens in the provider. E.g. doing an `up` against AWS:

```
Diagnostics:
  pulumi:providers:aws (default_6_37_1):
    error: pulumi:providers:aws resource 'default_6_37_1' has a problem: unable to validate AWS credentials.
    Details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.us-east-1.amazonaws.com/": proxyconnect tcp: dial tcp: lookup proxy on 127.0.0.53:53: server misbehaving
```

Therefore I'm minded to close as fixed -- please feel free to reopen if this is wrong!

**Closed by lunaris** 2024-09-05 13:28 UTC
Labels: kind/bug, area/cli, resolution/fixed
