### ISSUE TITLE
Error enable azure NFS Share

### ISSUE THREAD

**Issue by fsainovich** [pulumi/pulumi#7524] opened 2021-07-14 15:22 UTC
Documentation:
enable_nfs_v3 bool - NFS 3.0 protocol support enabled if set to true.

code (python):
enable_nfs_v3=True

response:
Diagnostics:
  azure-native:storage:StorageAccount (fsainovich):
    error: Code="InvalidRequestPropertyValue" Message="The value 'True' is not allowed for property isNfsv3Enabled.

Other attributes on storage account config accept True boolean value, like:
allow_shared_key_access=True,

**Comment by lukehoban** [comment] 2021-07-15 16:47
The API spec does seem to indicate that this should accept a boolean, but perhaps Azure itself is failing (and their API specs are wrong here)?

**Comment by emiliza** [comment] 2021-07-15 22:55
This is a dupe of https://github.com/pulumi/pulumi-azure-native/issues/817

@fsainovich can you try the workaround outlined here?
https://github.com/pulumi/pulumi-azure-native/issues/817#issuecomment-862417142

**Closed by emiliza** 2021-07-15 22:55 UTC
Labels: kind/bug, resolution/duplicate
