### ISSUE TITLE
Only prompt for secret passphrase if I'm using secrets

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2728] opened 2019-05-14 02:06 UTC
If I opt into using the `passphrase` backend, I'm prompted to enter my passphrase anytime I run `pulumi up`, etc, even when I don't have any secrets. This was surprising to me. It seems we should only prompt if I'm actually storing secrets that'll need to be decrypted.

**Comment by ellismg** [comment] 2019-05-14 02:32
I don’t think we can do this in. Running your program may cause secrets outputs go be generated, either via calling pulumi.secret directly, using the additionalSeceretOutputs field on resource options or in the future from an enlightened resource provider returning outputs marked as secrets.

If any of these things happen, we will need to be able to call encrypt, which means we need to eagerly prompt you for your passphrase.

If we didn’t prompt you for your passphrase before the update, what would you expect to happen when we detect we need it?  It feels like any experience here is going to be worse.

I think instead we should focus on having more secret providers which do not depend on human input to be initialized (like ones backed by KMS).

**Comment by farnoy** [comment] 2019-05-18 10:13
I think this is a regression. I updated from 0.17.9 and it worked fine without asking me for a passphrase. I'm not using secrets, just plain values. After updating to 0.17.12, it always asks me for a passphrase, and adds `encryptionsalt` parameter to the config yaml.

**Comment by ellismg** [comment] 2019-05-20 17:02
If we want to support `pulumi up` not prompting for a passphrase when you don't have secret configuration, what do we want the behavior to be if, as part of your update, we end up needing to actually encrypt a resource input or output?  Does this fail overall?

Previously, we know look at a stack's config statically and determine if there were secret values and decide if we needed to prompt for a passphrase.  Now, running your update can cause secret values to be created (even if your stack has no secret configuration) so we either must be conservative and always ask you for a passphrase or we need to have some strategy for when we end up needing to encrypt something and we don't have a key.  @farnoy what would you have expected here?

**Comment by farnoy** [comment] 2019-05-20 22:45
That's a good point, I wasn't aware that secret values can be added during an update. Can you describe this process? Are these values added in client code, or is it something that Pulumi runtime does during an update, conditionally?

**Comment by Frassle** [comment] 2019-05-27 10:00
Could this be something you need to opt into in the main Pulumi.yaml file? Something like "secrets: false" and then update won't ask for a passphrase and if the program tries to create a secret that's a runtime error.

**Comment by ellismg** [comment] 2019-08-05 18:45
I don't think we are going to make any changes here.  Because secrets can be created "from scratch" during an update (even if you have not encrypted any of your configuration values) by using `pulumi.secret` we need to have a context during an update which allows you to encrypt values, because we may end up needing to write encrypted data into the checkpoint.

This means that at the start of an update, we'll need a passphrase provided. If you are using the passphrase based secrets provider, you'll have to type your password, or set `PULUMI_CONFIG_PASSPHRASE` (which now has an overly specific name) in your environment. The other option is either to continue to use the Pulumi service for managing your stack's encryption, or if you'd prefer to not use the Pulumi service, use one of the providers added in #2994 which allows you to use an external key managed by AWS, GCP, Azure or Vault.  Since all of these providers can be created without end user input, you'll get back the experience you had with the Pulumi service.

**Closed by ellismg** 2019-08-05 18:45 UTC
Labels: area/cli, feature/q3, impact/usability, kind/enhancement
