### ISSUE TITLE
panic trying to create aws.sns.TopicSubscription

### ISSUE THREAD

**Issue by brandonbloom** [pulumi/pulumi#2628] opened 2019-04-05 02:01 UTC
Version: v0.17.4

```typescript

// this is the only strange thing, so providing it in case it is relevant
const provider = new aws.Provider('preprod', {
  assumeRole: {
      roleArn,
      sessionName: 'PulumiSession',
      externalId: 'PulumiApplication',
  },
  region: aws.config.requireRegion(),
});

   const queue = stuffhere;

// this is what fails
    new aws.sns.TopicSubscription('subscription', {
      protocol: 'sqs',
      topic,
      endpoint: queue.arn,
    }, {provider})
```

trace:

```
    panic: fatal: An assertion has failed: expected non-nil error with nil state during Create
    goroutine 133 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc0000d2c80, 0x4c)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23 +0xe9
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc000381600, 0x4b20c23, 0x33, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x126
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc000172100, 0x4e87720, 0xc00071f860, 0xc0006de600, 0xc000172100, 0x1, 0x1)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:585 +0xbda
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x4e87720, 0xc00071f860, 0x486b340, 0xc0006de600, 0x4e87720, 0xc00071f860, 0x4e9c7a0, 0x812a488)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1331 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x4e87720, 0xc00071f860, 0x486b340, 0xc0006de600, 0xc000133040, 0xc000133060, 0x0, 0x0, 0x4e72ee0, 0xc00030cae0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57 +0x2b0
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x498c6e0, 0xc000172100, 0x4e87720, 0xc00071f560, 0xc000e60140, 0xc0003a2e40, 0x0, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1333 +0x158
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000110000, 0x4e8fbe0, 0xc000110160, 0xc000172900, 0xc000650750, 0x80fd370, 0x0, 0x0, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:839 +0x8ec
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000110000, 0x4e8fbe0, 0xc000110160, 0xc000172900, 0x0)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1036 +0x1308
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00048a6d0, 0xc000110000, 0x4e8fbe0, 0xc000110160, 0xc000172900)
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:585 +0x9f
    created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:583 +0xa1
```

**Comment by lukehoban** [comment] 2019-04-06 00:25
This looks like the same underlying issue as https://github.com/pulumi/pulumi-terraform/issues/332.  I'm not sure exactly what is triggering it in this case though.

**Comment by brandonbloom** [comment] 2019-04-06 00:42
This assert eats the error. If somebody wants to send me a build that tweaks the assert to preserve the error message (or walk me through cutting a build locally), I can get you that for diagnosis.

**Comment by jen20** [comment] 2019-05-09 18:58
Hi @brandonbloom! Sorry it's taken a while to reply here. There actually isn't an additional error message being masked here: the panic is because a provider's Create function returning no state _and_ no error message is indicative of a bug upstream in the provider. I'll take a look at reproducing the error with the subscription shortly and see if we can get it fixed (if it's not already), however!

**Comment by jen20** [comment] 2019-05-09 23:33
Hi @brandonbloom - I'm trying to reproduce this at the moment using the following example:

```typescript
import * as aws from "@pulumi/aws";

const queue = new aws.sqs.Queue("queue", {
    tags: {
        Project: "Repro 2628",
    },
});

const topic = new aws.sns.Topic("topic", {
    displayName: "Repro 2628",
});

// this is what fails
new aws.sns.TopicSubscription('subscription', {
    protocol: 'sqs',
    topic: topic,
    endpoint: queue.arn,
});
```

Is there anything other than the custom provider which is unusual about your usage which is not reflected in this example - I can't reproduce it currently?

**Comment by brandonbloom** [comment] 2019-05-21 21:29
I think the main interesting thing is the assume-role in the custom provider.

**Comment by stack72** [comment] 2019-08-26 19:38
Just an FYI, I was able to verify that this is no longer the case:

```
import * as aws from "@pulumi/aws";

const provider = new aws.Provider('preprod', {
  assumeRole: {
      roleArn: "arn:aws:iam::123456789012:user/division_abc/subdivision_xyz/JaneDoe",
      sessionName: 'PulumiSession',
      externalId: 'PulumiApplication',
  },
  region: aws.config.requireRegion(),
});

const queue = new aws.sqs.Queue("queue", {
    tags: {
        Project: "Repro 2628",
    },
}, {
    provider: provider,
});

const topic = new aws.sns.Topic("topic", {
    displayName: "Repro 2628",
}, {
    provider: provider,
});

// this is what fails
new aws.sns.TopicSubscription('subscription', {
    protocol: 'sqs',
    topic: topic,
    endpoint: queue.arn,
}, {
    provider: provider,
});
```

Notice the fake assumeRole IAM ARN that doesn't exist and we get the following:

```
Previewing update (dev):

     Type                     Name               Plan       Info
 +   pulumi:pulumi:Stack      pulum-gh-2628-dev  create
 +   ├─ pulumi:providers:aws  preprod            create
     └─ aws:sqs:Queue         queue                         1 error

Diagnostics:
  aws:sqs:Queue (queue):
    error: The role "arn:aws:iam::123456789012:user/division_abc/subdivision_xyz/JaneDoe" cannot be assumed.

      There are a number of possible causes of this - the most common are:
        * The credentials used in order to assume the role are invalid
        * The credentials do not have appropriate permission to assume the role
        * The role ARN is not valid
```

**Comment by FWirtz** [comment] 2020-05-20 11:44
so I am still having issues with the `aws.sns.TopicSubscription`, getting exactly the same error, slightly different setup though.

My main aws provider is in `eu-west-1`, I want to subscribe to a SNS topic in `eu-west-2` though, so I created a second provider for that region, as per the docs.

```js
const awsLondonProvider = new aws.Provider('provider-eu-west-2', { region: 'eu-west-2' });

const queue = new aws.sqs.Queue("queue");
const queueSubscription = new aws.sns.TopicSubscription("queueSubscription", {
    endpoint: queue.arn,
    protocol: "sqs",
    topic: "arn:aws:sns:eu-west-2:0123456789:some-cool-topic",
}, { provider: awsLondonProvider });
```

Running this results in the same panic. I assume it's related to the second provider, as that's the only similarity with the original issue?

**Comment by stack72** [comment] 2020-06-01 11:45
Hi @brandonbloom 

you can tell me the Pulumi and pulumi-aws version you are using? I am pretty sure(:tm) this is due to not passing any credentials to the second provider but I'd like to verify this though

thanks

Paul

**Comment by brandonbloom** [comment] 2020-06-03 15:20
I no longer have access to the code or machine I was working on at the time. However, my original post states:

Version: v0.17.4

Hope that's helpful.

**Comment by stack72** [comment] 2020-06-04 11:02
Thanks @brandonbloom 

@FWirtz can you tell me what version of Pulumi you were using here?

Paul

**Comment by FWirtz** [comment] 2020-06-10 10:02
@stack72 sure:
```
"@pulumi/pulumi": "^2.0.0",
"@pulumi/aws": "^2.0.0",
"@pulumi/awsx": "^0.18.10"
```

**Comment by stack72** [comment] 2020-12-23 13:32
Hi all

So both @pierskarsenbarg and I have talked about this and tried to recreate it (albeit after a long time waiting!)

Unfortunately neither of us can recreate this anymore. I am going to close this out again as this is something that may have been fixed in the underlying provider

If there are still problems then please do let me know

Thanks again and I am sorry for the time elapsed on this issue

Paul

**Closed** 2020-12-23 13:32 UTC
Labels: area/providers
