### ISSUE TITLE
The Pulumi CLI encountered a snapshot integrity error. This is a bug! (v3.137.0)

### ISSUE THREAD

**Issue by erlichmen** [pulumi/pulumi#17607] opened 2024-10-24 14:32 UTC
### What happened?

when running pulumi up I get the following:

```
error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!

================================================================================
We would appreciate a report: https://github.com/pulumi/pulumi/issues/

NOTE: This error occurred while reading a snaphot. This error was introduced by
a previous operation when it wrote the snapshot. If you have details about that
operation, please include them in your report as well.

Please provide all of the text below in your report.
================================================================================
Pulumi Version:    v3.137.0
Go Version:        go1.23.2
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi up
Error:             could not deserialize deployment: snapshot integrity failure; refusing to use it: resource urn:pulumi:doitintl-cmp-dev::production::gcp:compute/regionNetworkEndpointGroup:RegionNetworkEndpointGroup::cmp-dev-datahub-events-cloud-run's dependency urn:pulumi:doitintl-cmp-dev::production::gcp:cloudrunv2/service:Service::datahub-events comes after it

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.23.2/libexec/src/runtime/debug/stack.go:26 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x1045f0c96?, 0x57?}, {0x14000fbb328?, 0x57?, 0x40?})
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/resource/deploy/snapshot.go:611 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14000504c80)
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/resource/deploy/snapshot.go:497 +0xc64
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x70?, {0x1053f2748, 0x106a19c80}, {0x1053cde60, 0x106a19c80}, {0x1053f2ca0?, 0x14002112640?})
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/httpstate/state.go:235 +0x74
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getTarget(0x14000ef74a0, {0x1053f2748, 0x106a19c80}, {0x1053cde60, 0x106a19c80}, {0x1053f2ca0, 0x14002112640}, 0x14002114930, {0x1053de6d8, 0x14002009830})
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/httpstate/state.go:255 +0xa4
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).newUpdate(_, {_, _}, {_, _}, {0x140013d7970, {0x140020a65f0, 0x37}, {0x0, 0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/httpstate/state.go:202 +0x1c0
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0x140013d7970, {0x140020a65f0, 0x37}, ...}, ...)
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/httpstate/backend.go:1381 +0xf0
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0x140013d7970, {0x140020a65f0, 0x37}, ...}, ...)
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/httpstate/backend.go:1355 +0x3e4
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0x140013d7970, {0x140020a65f0, 0x37}, {0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/apply.go:117 +0x108
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0x140013d7970, {0x140020a65f0, 0x37}, {0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/apply.go:247 +0xb4
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0x140013d7970, {0x140020a65f0, 0x37}, {0x0, 0x0, ...}, ...})
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/httpstate/backend.go:1108 +0x80
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0x140013d7970, {0x140020a65f0, 0x37}, {0x0, 0x0, 0x0}, ...})
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/stack.go:97 +0x78
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0x140013d7970, {0x140020a65f0, 0x37}, {0x0, 0x0, 0x0}, 0x14001fa6d98, ...})
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/backend/httpstate/stack.go:179 +0x5c
main.newUpCmd.func1({_, _}, {_}, {_, _}, {_, _}, {{{0x106a19c80, 0x0, 0x0}, ...}, ...}, ...)
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/cmd/pulumi/up.go:198 +0xa9c
main.newUpCmd.func3(0x14001f97508, {0x106a19c80, 0x0, 0x0?})
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/cmd/pulumi/up.go:574 +0x8d4
main.newUpCmd.runCmdFunc.func4(0x0?, {0x106a19c80?, 0x0?, 0x0?})
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/cmd/pulumi/errors.go:45 +0x28
main.newUpCmd.runCmdFunc.RunFunc.func7(0x14001f97508, {0x106a19c80, 0x0, 0x0})
        /private/tmp/pulumi-20241017-4937-21dpuj/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x14001f97508, {0x106a19c80, 0x0, 0x0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x14001d10608)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /private/tmp/pulumi-20241017-4937-21dpuj/pkg/cmd/pulumi/main.go:55 +0x50
```

### Example

```
pulumi up
```

### Output of `pulumi about`

```
CLI          
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  3.137.0-dev.0

Host     
OS       darwin
Version  15.0.1
Arch     arm64

This project is written in nodejs: executable='/Users/erlichmen/.nvm/versions/node/v20.14.0/bin/node' version='v20.14.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/erlichmen
User           erlichmen
Organizations  erlichmen, doitintl
Token type     personal

Pulumi locates its logs in /var/folders/kc/fc1mmdk955df8lhrx3qybw_h0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by erlichmen** [comment] 2024-10-24 14:55
"pulumi state repair" seem to fix this.
you might want to put the docs about this command in the error message

**Comment by lunaris** [comment] 2024-11-01 17:40
Hi @erlichmen. I'm glad `pulumi state repair` worked for you -- as you suggest, we are adding it to the error message (it's only been recently added so we wanted to make sure that it was actually solving problems before doing so). I was wondering -- do you have any more information on how you came about the snapshot integrity error in the first place? Things that I'm aware of that could have contributed to it:

* Any updates with `--target` you might have run prior
* Use of an older CLI version (e.g. you manually `refresh`ed using your local environment then tried to `up` in Pulumi Cloud or similar), which may have had a bug that introduced the error

Any thoughts you have would be greatly appreciated so we can try and pinpoint the cause -- thanks!

**Comment by lunaris** [comment] 2024-11-11 09:34
Hi @erlichmen; in the absence of any feedback on this I'm going to close this for now since it's difficult for us to reproduce these kinds of issues without further information and we are constantly pushing fixes for snapshot bugs. If you are still blocked or if there is more information that would help us track your problem down please feel free to reopen! 🙏

**Closed by lunaris** 2024-11-11 09:34 UTC
Labels: kind/bug, resolution/no-repro, area/engine, impact/snapshot-integrity
