### ISSUE TITLE
Error in authentication in Azure Pipeline since CLI 3.104.0

### ISSUE THREAD

**Issue by Phil1972** [pulumi/pulumi#15786] opened 2024-03-26 17:40 UTC
### What happened?

Hi,
Since the CLI version 3.104.0 (3.103.1 works fine), we are unbale to run into our azure pipeline.
<img width="485" alt="image" src="https://github.com/pulumi/pulumi/assets/40364427/33fa80df-e1f8-4447-9112-67bffd1b469e">

Are there any breaking changes that have occured or some required extra steps necessary to make this work?

### Example

Cli auth problem

### Output of `pulumi about`

<img width="272" alt="image" src="https://github.com/pulumi/pulumi/assets/40364427/2946c439-5a2a-4e93-b7c9-22df91eb00c9">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Phil1972** [comment] 2024-03-26 19:46
Hi, yes we tried it with a few versions in between as well as the latest 3.111.1

- what are you using azure for? Are you using it for key encryption, state storage or both? both
- which authentication method to azure are you using? we use AzureCLI with AZURE_KEYVAULT_AUTH_VIA_CLI=true using the az login
- 
<img width="432" alt="image" src="https://github.com/pulumi/pulumi/assets/40364427/982d0523-cfa3-44ae-8a0d-0f20a6eb66ec">

**Comment by tgummerer** [comment] 2024-04-02 07:52
@Phil1972 Thanks for those details.  Would you be able to share a bit more of the CI script, i.e. the whole definition of the task?  I'm trying to reproduce this, but reproducing it probably depends on the exact login method, so the more details the better.

Also just to make sure, downgrading to 3.103.1 with the same pulumi program still works?

**Comment by Phil1972** [comment] 2024-04-02 12:25
Yes, we are presently stuck at 3.103.1 since the version right after that has the issue.

**Comment by Phil1972** [comment] 2024-04-02 12:36
This is our full CLI script:

>    - task: AzureCLI@2
     displayName: 'Run Pulumi ${{ command }}'
     inputs:
       azureSubscription: ${{ parameters.azureServiceConnection }}
       scriptType: 'bash'
       scriptLocation: 'inlineScript'
       inlineScript: |
         export PATH=$HOME/.pulumi/bin:$PATH
         helm version
         export AZURE_STORAGE_KEY=$(az storage account keys list -g ${{ parameters.pulumiStateResourceGroup }} -n ${{ parameters.stateStorageAccount }} --query [0].value -o json | tr -d '"')
         export AZURE_STORAGE_ACCOUNT=${{ parameters.stateStorageAccount }}
         export AZURE_KEYVAULT_AUTH_VIA_CLI=true
         export AZDO_ORG_SERVICE_URL=***org url***
         export AZDO_PERSONAL_ACCESS_TOKEN=$(System.AccessToken)
         pulumi login ${{ parameters.stateStorageContainer }}
         export AZURE_CLIENT_ID=$(AzureDevopsClientId)
         export ARM_CLIENT_ID=$(AzureDevopsClientId)
         export AZURE_CLIENT_SECRET =$(AzureDevopsClientSecret)
         export ARM_CLIENT_SECRET=$(AzureDevopsClientSecret)
         export AZURE_TENANT_ID =$(az account show --query tenantId -o json | tr -d '"')
         export ARM_TENANT_ID=$(az account show --query tenantId -o json | tr -d '"')
         export ARM_SUBSCRIPTION_ID=$(az account show --query id -o json | tr -d '"')
         export GITHUB_TOKEN=${{ parameters.gitHubToken }}
         dotnet build
         dotnet run --project ./src/Automation/Automation.csproj ${{ command }} ${{ parameters.environment }} ${{ parameters.region }}

**Comment by Phil1972** [comment] 2024-04-02 12:44
Here is the service connection details:
![image](https://github.com/pulumi/pulumi/assets/40364427/da1377ea-0319-4e44-86c0-8733c7369fba)

**Comment by tgummerer** [comment] 2024-04-02 16:09
Thanks for the additional details!  I'm still trying to reproduce this on my side, with no luck so far.  

A couple of things seem interesting to me based on the details above.  Based on the output and the script above, it looks like the `pulumi login` actually succeeds, and only when running the pulumi program later through Automation API it starts failing.  

You're also setting up additional environment variables after the `pulumi login`.  If the login really succeeds (if it doesn't that would be useful information as well), I don't think you need to set up all these additional environment variables.  Especially the `ARM_*` environment variables are deprecated.  I'd be curious to know if the program succeeds if that variable setup is removed with a newer pulumi version?  (Don't try 3.104.0, only try 3.104.2 or newer versions if you try with newer versions)

**Comment by Phil1972** [comment] 2024-04-02 16:37
ok will try this out by removing the ARM_* and try 3.104.2

**Comment by tgummerer** [comment] 2024-04-02 16:46
Thanks!  I think it might also be worth trying to remove the AZURE_* variables that are being set after `pulumi login`.

**Comment by Phil1972** [comment] 2024-04-02 18:28
if I remove the AZURE_*, ARM_* after the pulumi login, the refresh/preview operation do not work.  The refresh/preview has a lot of error of the sort:     error: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).

and I checked also in your custom task that you are still exporting all those

https://github.com/pulumi/pulumi-az-pipelines-task/blob/master/buildAndReleaseTask/pulumi.ts

**Comment by Phil1972** [comment] 2024-04-02 18:34
Some more info

Here is the output using the 3.103.1:

> version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.21.7"}
W0402 17:03:16.497978    2106 log.go:99] log level 11 will print sensitive information such as api tokens and request headers
W0402 17:03:16.509155    2106 log.go:99] A new version of Pulumi is available. To upgrade from version '3.103.1' to '3.112.0', run 
   $ curl -sSL https://get.pulumi.com/ | sh
or visit https://pulumi.com/docs/install/ for manual instructions and release notes.
I0402 17:03:16.523191    2106 log.go:95] 2024/04/02 17:03:16 azureblob: constructed service URL: https://keyvault.blob.core.windows.net/
I0402 17:03:16.523227    2106 log.go:95] 2024/04/02 17:03:16 azureblob.URLOpener: using shared key credentials
Logged in to fv-az584-897 as vsts (azblob://state)

And the output for 3.104.2:

> version.BuildInfo{Version:"v3.14.3", GitCommit:"f03cc04caaa8f6d7c3e67cf918929150cf6f3f12", GitTreeState:"clean", GoVersion:"go1.21.7"}
W0402 18:31:49.066881    2142 pulumi.go:236] log level 11 will print sensitive information such as api tokens and request headers
W0402 18:31:49.068777    2142 pulumi.go:497] A new version of Pulumi is available. To upgrade from version '3.104.2' to '3.112.0', run 
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/install/ for manual instructions and release notes.
Logged in to fv-az768-960 as vsts (azblob://state)

in the 1.104.2+ versions, I do not see the mention about the azureBlob stuff.

**Comment by tgummerer** [comment] 2024-04-08 09:15
Thanks for the additional info!  It looks like in either case the `pulumi login` succeeds, so it's very strange that the followup pulumi commands don't work.  I'm still unable to reproduce this locally, or in GitHub actions, so I'm now trying to get access to Azure Pipelines and to reproduce it there to see if there's anything especially strange going on with that.  Sorry this is taking so long to try and resolve.

**Comment by tgummerer** [comment] 2024-04-10 09:06
@Phil1972 I have now managed to try this same setup as you have in an Azure Pipeline, however I'm still not having any luck in reproducing the issue.  So one more question: What exactly is the account type of the account where you got the `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` from?

**Comment by Phil1972** [comment] 2024-04-10 13:31
I am not sure how much you use azure devops, but the service connection is done through this:
<img width="519" alt="image" src="https://github.com/pulumi/pulumi/assets/40364427/fa6c7ae3-f620-4613-9c51-37d0c78dfd31">

**Comment by Phil1972** [comment] 2024-04-10 13:46
Here are the roles that we give to that Service Connection in our subscription:
<img width="1550" alt="image" src="https://github.com/pulumi/pulumi/assets/40364427/73d5c3ef-81e4-434e-a554-b2040f0d15d8">

**Comment by tgummerer** [comment] 2024-04-10 14:57
Thanks, I'll keep trying to reproduce with these details.  

One thing to note here is that the account you're using also needs the "Storage Queue Data Contributor" and "Storage Blob Data Contributor" permissions on the storage account you are trying to access.  Though I'm not sure 3.103.x would work without those either, so I suspect that's not the issue here.  Would be great if we can rule that out though.

**Comment by Phil1972** [comment] 2024-04-10 17:05
Yes, would that be new? because the older CLI works fine as is.  I will still try to add those if I am allowed

**Comment by tgummerer** [comment] 2024-04-11 09:01
> Yes, would that be new?

Maybe?  Honestly I'm grasping at straws a little bit with this problem, and I'm pretty stumped on what's going on here.  I'm trying to find out what's special about your setup that makes it fail with the new version, since we have seen operations with `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` set the way you do work just fine and have tests for that.  

One other thing I'm planning here is to upgrade `gocloud.dev` to 0.37 which is the latest version now, to see if that can help with your problem.

**Comment by Phil1972** [comment] 2024-04-11 15:02
What version of gocloud was used by 1.103.1 vs 1.104.x + ?
Can you go back or there are new features that are required?

**Comment by tgummerer** [comment] 2024-04-11 15:41
3.103.1 used gocloud 0.27, while we're at 0.36 now.  I don't think we want to go back anymore at this point, since there are a few issues that are fixed in the newer version, and we can't stay with an older dependency forever.  I do still really want to get to the bottom of what happens here though, and make sure that you can upgrade to newer versions of pulumi.

**Comment by Phil1972** [comment] 2024-04-11 15:45
Yes I did, here is the permissions we have on the storage account:
![image](https://github.com/pulumi/pulumi/assets/40364427/ee2aae2f-57a6-4592-acc6-40423bf1af7c)

**Comment by tgummerer** [comment] 2024-04-12 12:28
> I think this should be fine right?

Yes this seems okay at a first glance.

I think I have finally understood what's happening here.  It looks like the credentials you're providing with the environment variables `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` are wrong in some way.

It looks like v3.103.0 and earlier falls back to using the `az login` method, when the credentials provided via those environment variables are wrong in some way.  (I managed to reproduce that in Azure Pipelines when faking some wrong login details there).  

Meanwhile v3.104.2 and newer (or rather gocloud.dev 0.36) uses the azure SDKs instead of the `az` CLI for requests to Azure, and it no longer seems to fall back in the same way it did before.  

Tying this into the error you were getting when you removed the `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` variables ("Authenticating using the Azure CLI is only supported as a User (not a Service Principal)."), it looks like the preview was actually running in that case, but the errors are coming from the provider doing the actual resource requests to Azure.

So at this point I'm pretty convinced that the user of whatever credentials you are using for the `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` environment variables doesn't have the right permissions to access the storage account that's being used here.

It is a bit unfortunate that the same fallback logic doesn't work anymore, but that will probably need an upstream fix in the gocloud.dev library.

**Comment by tgummerer** [comment] 2024-04-15 08:50
From a quick look unfortunately it doesn't look like there's much in terms of logging inside of the gocloud.dev library.  You can turn on logging in the pulumi CLi with `-v 10` or `-v 11` (note that the latter will also log secrets, so be careful with that).  With `--logtostderr` you can send the log output to stderr, which might be the easiest for CI.

**Comment by tgummerer** [comment] 2024-04-15 09:05
FWIW I opened an upstream issue in https://github.com/google/go-cloud/issues/3414 as well.

**Comment by Phil1972** [comment] 2024-04-15 12:07
Not sure that would help, but here are some more infos as to where the problem could be:

Running stack global_dev
Exception occured during operation
Pulumi.Automation.Commands.Exceptions.CommandException: code: 255
stdout: 
stderr: error: secrets (code=Unknown): DefaultAzureCredential authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "error": "invalid_request",
  "error_description": "Identity not found"
}
--------------------------------------------------------------------------------

>    at Pulumi.Automation.Commands.LocalPulumiCmd.RunAsyncInner(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, EventLogFile eventLogFile, CancellationToken cancellationToken)
>    at Pulumi.Automation.Commands.LocalPulumiCmd.RunAsync(IList`1 args, String workingDir, IDictionary`2 additionalEnv, Action`1 onStandardOutput, Action`1 onStandardError, Action`1 onEngineEvent, CancellationToken cancellationToken)
>    at Pulumi.Automation.LocalWorkspace.GetAllConfigAsync(String stackName, CancellationToken cancellationToken)
>

**Comment by tgummerer** [comment] 2024-04-15 16:27
I'm glad it's working now, thank you for letting me know, and thanks for your patience while we were trying to figure this out.

**Comment by tgummerer** [comment] 2024-04-17 16:34
It looks like upstream won't change the behaviour back there (it's awkward for us, but from a library perspective I think the new behaviour does make sense).  Since we haven't gotten more complaints about this not working, and we understand what happened here I'm going to close this issue out.

**Closed by tgummerer** 2024-04-17 16:34 UTC
Labels: kind/bug, area/backends, resolution/wont-fix, blocked, awaiting-upstream, impact/regression

**Comment by Phil1972** [comment] 2024-04-17 16:36
Perfect, thanks for your time on this. Very appreciated.

________________________________
