### ISSUE TITLE
pulumi up/preview hang with no error messages in the console

### ISSUE THREAD

**Issue by tony-elliott** [pulumi/pulumi#6907] opened 2021-04-28 17:45 UTC
I'm facing an issue when trying to do a pulumi up or a pulumi preview.  The process hangs indefinitely and does not return any errors or information around what is going on when it hangs.  I started a preview last night and let it run until I started again this morning and it was still hanging at the same place again with no messaging on screen of any activity or errors.  I cancelled the process and then I get dozens of these types of error messages back.  The stack was originally created using v2 of the pulumi SDK and I am currently running v3.1.0

I have been able to trace this to issues with either k8s deployments or helm deployments inside the stack as removing these from the project will allow the process to complete.

## Expected behavior
Pulumi up, or pulumi preview should either continue to completion or fail with a relevant error message rather than hanging with no output.

## Current behavior
Process hangs and will not continue until command is cancelled via [CTRL]+C

## Steps to reproduce
1.  Clone existing project created with v2 with either helm deployments k8s direct deployments
2.  Upgrade cli sdk from v2.x to v3.1.0
3.  Run "pulumi up" or "pulumi preview"
4.  Process will hang

## Context (Environment)
Trying to create a new EKS cluster with helm and k8s resources to automate infra deployments.

## Affected feature
Unsure

[debugOutput.txt](https://github.com/pulumi/pulumi/files/6393733/debugOutput.txt)

**Comment by justinvp** [comment] 2021-04-29 19:51
@tony-elliott, you mention using version v3.1.0 of the CLI, but have you tried upgrading your NPM packages as well?

**Comment by 1player** [comment] 2021-05-06 08:55
On my case (WSL2/Arch Linux), hangs even with a simple `pulumi version`: prints the versions and never terminates. Hangs inside my pulumi project and outside of it, so I don't think the NPM packages are the issue here.

Other commands, such as `pulumi state` which prints the supported flags and subcommands, work as intended.

**Comment by 1player** [comment] 2021-05-06 09:25
Sorry for double posting, in my case it seems to have been a WSL2 glitch, I had to reboot the machine and now `pulumi version` works and tells me there's an update available, which probably was the reason of it getting stuck. In fact the whole networking stack of my linux box was borked.

`pulumi up` and `pulumi preview` work again. @tony-elliott are you on WSL by any chance?

**Comment by mikhailshilkov** [comment] 2022-07-28 21:19
I feel like this issue isn't very relevant anymore, so I'll go ahead and close it

**Closed by mikhailshilkov** 2022-07-28 21:19 UTC
Labels: kind/bug, area/cli, resolution/wont-fix
