### ISSUE TITLE
Component deletion continues to show in-progress although all resources have been deleted

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#13357] opened 2023-07-05 19:08 UTC
### What happened?

Pulumi continues to show a component resources as `deleting` even though all the resources within the component has been deleted (see screenshot).

### Expected Behavior

A component should be marked as `deleted` when all resources within a component are deleted.

### Steps to reproduce

I'm unclear on how to repro this, but it seems to occur when a component resource depends on another component resources. Eg- component A creates a kubernetes cluster and component B deploys kubernetes resources into the cluster created by component A.

<img width="1158" alt="image" src="https://github.com/pulumi/pulumi/assets/25461821/0ee5ff7b-7d58-44f8-bacb-25b28e3e0901">

### Output of `pulumi about`

▶ pulumi about
CLI
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.103.0
azuread       4.3.0
kubernetes    3.29.1
nodejs        unknown
random        4.13.2
tls           4.10.0

Host
OS       darwin
Version  13.2.1
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mnlumi** [comment] 2023-08-02 17:53
Hey @dixler It looks like the triage label was removed. Can you please add some details to your findings in a comment here?

**Comment by dixler** [comment] 2023-09-08 21:35
Was able to repro the issue on destroying resources from the program below.
[![asciicast](https://asciinema.org/a/TZNSCyOKF17efW6pZqwS3KNrE.svg)](https://asciinema.org/a/TZNSCyOKF17efW6pZqwS3KNrE)

## Program
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as sleep from "@pulumi/sleep";

class Noop extends pulumi.ComponentResource {
    constructor(name: string, opts?: pulumi.ComponentResourceOptions) {
        super("my:example:Noop", name, {}, opts);
    }
}

const b = new sleep.Sleep("b", {
    seconds: 10,
});

const a = new Noop("a", {
    dependsOn: b,
});

const a_a = new sleep.Sleep("a-a", {
    seconds: 5,
}, {
    parent: a,
});

const a_b = new sleep.Sleep("a-b", {
    seconds: 5,
}, {
    parent: a,
});

const a_c = new sleep.Sleep("a-c", {
    seconds: 5,
}, {
    parent: a,
});
```

**Comment by dixler** [comment] 2023-09-11 21:32
After some thinking, this appears to be intended behavior for destroy. The engine is not deleting the resource until its dependent resources are deleted. I'm going to close this as by-design.

Let me know if there's further questions or feedback!

side-note: I think there are opportunities to make dependencies more clear during updates so users are aware of which resources resources are waiting on
- https://github.com/pulumi/pulumi/issues/11813

The provider I put together to test this is located: https://github.com/dixler/pulumi-sleep

**Comment by phillipedwards** [comment] 2023-09-14 17:34
Hey @dixler thanks for taking a look. I'm not sure I am following how this is correct. Here's my thinking:
- During an update, if A depends on B, Pulumi creates B initially then creates A once B has been fully constructed.
- During a destroy, Pulumi should do things in the reverse order as the above step meaning A should be destroyed before B.

With that in mind, why would an empty component _not_ be deleted if no other resource takes a dependency on that resource. In the above example, B is the resource which is depended on, not A, thus we should be able to fully destroy/delete A without any implications for other resource..

**Closed** 2023-09-29 20:28 UTC
Labels: kind/bug, area/cli, resolution/by-design, customer/feedback, customer/lighthouse
