### ISSUE TITLE
pulumi install for linux does not work

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9660] opened 2022-05-23 16:56 UTC
[community slack thread](https://github.com/pulumi/pulumi-hugo/issues/1534#issuecomment-1133481310)

this happened during a usability study today..

Hello, I just tried running the install pulumi script for Linux I found at https://www.pulumi.com/docs/get-started/aws/begin/

```
curl -fsSL https://get.pulumi.com/ | sh
but got the following error while extracting the file:
=== Installing Pulumi v3.33.1 ===
+ Downloading https://get.pulumi.com/releases/sdk/pulumi-v3.33.1-linux-x64.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Curren
                                 Dload  Upload   Total   Spent    Left  Speed
100 78.7M  100 78.7M    0     0  9856k      0  0:00:08  0:00:08 --:--:-- 10.2M
+ Extracting to /home/max/.pulumi/bin

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

We're sorry, but it looks like something might have gone wrong during installa
If you need help, please join us on https://slack.pulumi.com/
```

https://get.pulumi.com/releases/sdk/pulumi-v3.33.1-linux-x64.tar does not exist

**Comment by t0yv0** [comment] 2022-05-23 17:15
Current hypothesis is that the trimmed log actually has the correct URL (.tar.gz) but network error prevented this script from working.

The workaround for the user would be to try again.

What we need to fix is (1) possibly retrying automatically and (2) definitely indicating network failure as the reason more prominently in the error message.

**Comment by t0yv0** [comment] 2022-05-23 17:15
https://github.com/pulumi/get.pulumi.com/issues/129

**Comment by susanev** [comment] 2022-05-23 17:16
removed p0 as we believe this is a network issue, we are waiting on the person to confirm

**Comment by MaxPowerWasTaken** [comment] 2022-05-23 18:45
per @dixler's request in slack...

```
curl -v https://get.pulumi.com/
*   Trying 143.204.146.85:443...
* Connected to get.pulumi.com (143.204.146.85) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=pulumi.com
*  start date: Jan  9 00:00:00 2022 GMT
*  expire date: Feb  7 23:59:59 2023 GMT
*  subjectAltName: host "get.pulumi.com" matched cert's "*.pulumi.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: get.pulumi.com]
* h2h3 [user-agent: curl/7.82.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x556a5547f380)
> GET / HTTP/2
> Host: get.pulumi.com
> user-agent: curl/7.82.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< content-type: text/plain
< content-length: 6922
< date: Mon, 23 May 2022 06:25:43 GMT
< last-modified: Mon, 12 Apr 2021 16:16:38 GMT
< etag: "1e45ad7804469c77aae20976da3dc576"
< accept-ranges: bytes
< server: AmazonS3
< vary: Accept-Encoding
< x-cache: Hit from cloudfront
< via: 1.1 b078462cffa3a81b6e262ef7f6040412.cloudfront.net (CloudFront)
< x-amz-cf-pop: EWR52-C2
< x-amz-cf-id: BKeaeUyWyOniirjVZf3ncFYKBuyavPxGEI43PymWaHEaS9lFJnZjlQ==
< age: 44278
< 
#!/bin/sh
set -e

RESET="\\033[0m"
RED="\\033[31;1m"
GREEN="\\033[32;1m"
YELLOW="\\033[33;1m"
BLUE="\\033[34;1m"
WHITE="\\033[37;1m"

print_unsupported_platform()
{
    >&2 say_red "error: We're sorry, but it looks like Pulumi is not supported on your platform"
    >&2 say_red "       We support 64-bit versions of Linux and macOS and are interested in supporting"
    >&2 say_red "       more platforms.  Please open an issue at https://github.com/pulumi/pulumi and"
    >&2 say_red "       let us know what platform you're using!"
}

say_green()
{
    [ -z "${SILENT}" ] && printf "%b%s%b\\n" "${GREEN}" "$1" "${RESET}"
    return 0
}

say_red()
{
    printf "%b%s%b\\n" "${RED}" "$1" "${RESET}"
}

say_yellow()
{
    [ -z "${SILENT}" ] && printf "%b%s%b\\n" "${YELLOW}" "$1" "${RESET}"
    return 0
}

say_blue()
{
    [ -z "${SILENT}" ] && printf "%b%s%b\\n" "${BLUE}" "$1" "${RESET}"
    return 0
}

say_white()
{
    [ -z "${SILENT}" ] && printf "%b%s%b\\n" "${WHITE}" "$1" "${RESET}"
    return 0
}

at_exit()
{
    # shellcheck disable=SC2181
    # https://github.com/koalaman/shellcheck/wiki/SC2181
    # Disable because we don't actually know the command we're running
    if [ "$?" -ne 0 ]; then
        >&2 say_red
        >&2 say_red "We're sorry, but it looks like something might have gone wrong during installation."
        >&2 say_red "If you need help, please join us on https://slack.pulumi.com/"
    fi
}

trap at_exit EXIT

VERSION=""
SILENT=""
while [ $# -gt 0 ]; do
    case "$1" in
        --version)
            if [ "$2" != "latest" ]; then
                VERSION=$2
            fi
            ;;
        --silent)
            SILENT="--silent"
            ;;
     esac
     shift
done

if [ -z "${VERSION}" ]; then

    # Query pulumi.com/latest-version for the most recent release. Because this approach
    # is now used by third parties as well (e.g., GitHub Actions virtual environments),
    # changes to this API should be made with care to avoid breaking any services that
    # rely on it (and ideally be accompanied by PRs to update them accordingly). Known
    # consumers of this API include:
    #
    # * https://github.com/actions/virtual-environments
    #

    if ! VERSION=$(curl --fail --silent -L "https://www.pulumi.com/latest-version"); then
        >&2 say_red "error: could not determine latest version of Pulumi, try passing --version X.Y.Z to"
        >&2 say_red "       install an explicit version"
        exit 1
    fi
fi

OS=""
case $(uname) in
    "Linux") OS="linux";;
    "Darwin") OS="darwin";;
    *)
        print_unsupported_platform
        exit 1
        ;;
esac

ARCH=""
case $(uname -m) in
    "x86_64") ARCH="x64";;
    "arm64") ARCH="arm64";;
    "aarch64") ARCH="arm64";;
    *)
        print_unsupported_platform
        exit 1
        ;;
esac

TARBALL_URL="https://get.pulumi.com/releases/sdk/pulumi-v${VERSION}-${OS}-${ARCH}.tar.gz"

if ! command -v pulumi >/dev/null; then
    say_blue "=== Installing Pulumi v${VERSION} ==="
else
    say_blue "=== Upgrading Pulumi $(pulumi version) to v${VERSION} ==="
fi

say_white "+ Downloading ${TARBALL_URL}..."

TARBALL_DEST=$(mktemp -t pulumi.tar.gz.XXXXXXXXXX)

# shellcheck disable=SC2046
# https://github.com/koalaman/shellcheck/wiki/SC2046
# Disable to allow the `--silent` option to be omitted.
if curl --fail $(printf %s "${SILENT}") -L -o "${TARBALL_DEST}" "${TARBALL_URL}"; then
    say_white "+ Extracting to $HOME/.pulumi/bin"

    # If `~/.pulumi/bin exists, clear it out
    if [ -e "${HOME}/.pulumi/bin" ]; then
        rm -rf "${HOME}/.pulumi/bin"
    fi

    mkdir -p "${HOME}/.pulumi"

    # Yarn's shell installer does a similar dance of extracting to a temp
    # folder and copying to not depend on additional tar flags
    EXTRACT_DIR=$(mktemp -d pulumi.XXXXXXXXXX)
    tar zxf "${TARBALL_DEST}" -C "${EXTRACT_DIR}"

    # Our tarballs used to have a top level bin folder, so support that older
    # format if we detect it. Newer tarballs just have all the binaries in
    # the top level Pulumi folder.
    if [ -d "${EXTRACT_DIR}/pulumi/bin" ]; then
        mv "${EXTRACT_DIR}/pulumi/bin" "${HOME}/.pulumi/"
    else
        cp -r "${EXTRACT_DIR}/pulumi/." "${HOME}/.pulumi/bin/"
    fi

    rm -f "${TARBALL_DEST}"
    rm -rf "${EXTRACT_DIR}"
else
    >&2 say_red "error: failed to download ${TARBALL_URL}"
    exit 1
fi

# Now that we have installed Pulumi, if it is not already on the path, let's add a line to the
# user's profile to add the folder to the PATH for future sessions.
if ! command -v pulumi >/dev/null; then
    # If we can, we'll add a line to the user's .profile adding $HOME/.pulumi/bin to the PATH
    SHELL_NAME=$(basename "${SHELL}")
    PROFILE_FILE=""

    case "${SHELL_NAME}" in
        "bash")
            # Terminal.app on macOS prefers .bash_profile to .bashrc, so we prefer that
            # file when trying to put our export into a profile. On *NIX, .bashrc is
            # prefered as it is sourced for new interactive shells.
            if [ "$(uname)" != "Darwin" ]; then
                if [ -e "${HOME}/.bashrc" ]; then
                    PROFILE_FILE="${HOME}/.bashrc"
                elif [ -e "${HOME}/.bash_profile" ]; then
                    PROFILE_FILE="${HOME}/.bash_profile"
                fi
            else
                if [ -e "${HOME}/.bash_profile" ]; then
                    PROFILE_FILE="${HOME}/.bash_profile"
                elif [ -e "${HOME}/.bashrc" ]; then
                    PROFILE_FILE="${HOME}/.bashrc"
                fi
            fi
            ;;
        "zsh")
            if [ -e "${ZDOTDIR:-$HOME}/.zshrc" ]; then
                PROFILE_FILE="${ZDOTDIR:-$HOME}/.zshrc"
            fi
            ;;
    esac

    if [ -n "${PROFILE_FILE}" ]; then
        LINE_TO_ADD="export PATH=\$PATH:\$HOME/.pulumi/bin"
        if ! grep -q "# add Pulumi to the PATH" "${PROFILE_FILE}"; then
            say_white "+ Adding \$HOME/.pulumi/bin to \$PATH in ${PROFILE_FILE}"
            printf "\\n# add Pulumi to the PATH\\n%s\\n" "${LINE_TO_ADD}" >> "${PROFILE_FILE}"
        fi

        EXTRA_INSTALL_STEP="+ Please restart your shell or add $HOME/.pulumi/bin to your \$PATH"
    else
        EXTRA_INSTALL_STEP="+ Please add $HOME/.pulumi/bin to your \$PATH"
    fi
elif [ "$(command -v pulumi)" != "$HOME/.pulumi/bin/pulumi" ]; then
    say_yellow
    say_yellow "warning: Pulumi has been installed to $HOME/.pulumi/bin, but it looks like there's a different copy"
    say_yellow "         on your \$PATH at $(dirname "$(command -v pulumi)"). You'll need to explicitly invoke the"
    say_yellow "         version you just installed or modify your \$PATH to prefer this location."
fi

say_blue
say_blue "=== Pulumi is now installed! 🍹 ==="
if [ "$EXTRA_INSTALL_STEP" != "" ]; then
    say_white "${EXTRA_INSTALL_STEP}"
fi
say_green "+ Get started with Pulumi: https://www.pulumi.com/docs/quickstart"
* Connection #0 to host get.pulumi.com left intact
```

**Comment by t0yv0** [comment] 2022-05-23 18:54
Does retrying resolve the issue for you? @MaxPowerWasTaken 

Now that we've verified the URL is correct in the install script, the suspicion is that network connection is interrupted during your download, so perhaps trying again can work around that.

**Comment by MaxPowerWasTaken** [comment] 2022-05-23 19:05
Hi @t0yv0, thanks for the quick response. I've tried it four or five times now (including restarting my computer before the latest retry), still keep getting the same error.

If it's a network issue, we wouldn't expect to see curl output of: 
```
Downloading:
% Total % Received
100 78.7M 100 78.7M
```
right? Or maybe I'm misunderstanding the nature of the potential network issue. Sorry for the annoyingly hard to reproduce error.

**Comment by AaronFriel** [comment] 2022-05-23 19:09
@MaxPowerWasTaken 

Can you try this for me, to ensure you're getting the same tar.gz we see:

```
wget https://get.pulumi.com/releases/sdk/pulumi-v3.33.1-linux-x64.tar.gz
sha256sum pulumi-v3.33.1-linux-x64.tar.gz
```

You should get:

1ef6d4581fdf2b0862c40ba40b1df4c21ab8447cc763ec100c0cd06fe964d6c8  pulumi-v3.33.1-linux-x64.tar.gz

**Comment by MaxPowerWasTaken** [comment] 2022-05-23 19:11
1ef6d4581fdf2b0862c40ba40b1df4c21ab8447cc763ec100c0cd06fe964d6c8  pulumi-v3.33.1-linux-x64.tar.gz

**Comment by AaronFriel** [comment] 2022-05-23 19:14
Hmm, and then can you give us:

```
mktemp --version
tar --version
gzip --version
```

And also check that you have free space & that the Pulumi dir is accessible & writable:

```
stat ~/.pulumi/bin
df -h ~/.pulumi/bin
ls -la ~/.pulumi/bin
```

**Comment by AaronFriel** [comment] 2022-05-23 19:40
@MaxPowerWasTaken to try to get you going sooner with Pulumi, please try this minimal install script:


```sh
wget https://get.pulumi.com/releases/sdk/pulumi-v3.33.1-linux-x64.tar.gz
mkdir -p ~/.pulumi/bin
tar -xzvf pulumi-v3.33.1-linux-x64.tar.gz -C ~/.pulumi/bin --strip-components=2
echo 'export PATH="$HOME/.pulumi/bin:$PATH"' >> ~/.bashrc
```

**Comment by AaronFriel** [comment] 2022-05-23 20:07
I can confirm we have the same versions and that makes sense, I'm also using Ubuntu 20.04.4 LTS.

**Comment by AaronFriel** [comment] 2022-05-24 01:33
@MaxPowerWasTaken did the modified script work?

**Comment by MaxPowerWasTaken** [comment] 2022-05-24 17:39
@AaronFriel appears so - 

```
 ~ pulumi about                                         1 ✘  base Py  13:15:47 
Manage your Pulumi stacks by logging in.
Run `pulumi login --help` for alternative login options.
Enter your access token from https://app.pulumi.com/account/tokens
    or hit <ENTER> to log in using your browser
```

**Comment by AaronFriel** [comment] 2022-05-24 22:02
Curious. I'm not sure what more I can ask about the install script or how to reproduce the error you saw.

If you could retry the install script at some point, perhaps we can close this if it was a fluke.

**Comment by nhobin219** [comment] 2022-10-12 18:26
Just as an FYI, I experienced this exact same issues on `Ubuntu 22.04.1 LTS`. The Linux install command does not work for me.

**Comment by Frassle** [comment] 2022-10-12 18:46
@nhobin219 did you work out why? Could you install it manually? Do you have any logs/output/diagnostics to share to help diagnose why it didn't work?

**Comment by nhobin219** [comment] 2022-10-12 18:54
> @nhobin219 did you work out why? Could you install it manually? Do you have any logs/output/diagnostics to share to help diagnose why it didn't work?

Apologies for the unhelpful comment lol. I didn't dig too much into it, but let me go ahead and run the commands from the above thread and see if I can get any useful information. I will post back here in a bit.

I ended up manually installing using the linux binary with no issues.

**Comment by AaronFriel** [comment] 2022-10-12 21:22
@nhobin219 if you or anyone else reading this can reproduce the issue, please let us know and provide us with any logs, the version #s requested above and we'll reopen the issue.

**Comment by nhobin219** [comment] 2022-10-12 21:39
Ok, I spent some time debugging and this is what I've found. The `curl` command downloads the script seemingly successfully. The script executes everything without error until line 145 `tar zxf "${TARBALL_DEST}" -C "${EXTRACT_DIR}"`. I took a look at what exactly is failing here and it seems that the tarball file `/tmp/pulumi.tar.gz.*` doesn't actually seem to be a valid gzipped file. Running that command results in the error above i.e.
```
user@hostname:~$ tar zxf /tmp/pulumi.tar.gz.Y8GDmiht3E -C pulumi.Wm9L31NIDq

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Running `unzip` manually on that file results in the following:
```
user@hostname:~$ unzip /tmp/pulumi.tar.gz.Y8GDmiht3E
Archive:  /tmp/pulumi.tar.gz.Y8GDmiht3E
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/pulumi.tar.gz.Y8GDmiht3E or
        /tmp/pulumi.tar.gz.Y8GDmiht3E.zip, and cannot find /tmp/pulumi.tar.gz.Y8GDmiht3E.ZIP, period.
```
So, something appears to be off with the tarball downloaded from `https://get.pulumi.com/releases/sdk/pulumi-v3.42.0-linux-x64.tar.gz`.

**Comment by AaronFriel** [comment] 2022-10-12 21:47
Could you upload that tar.gz to Google Drive/Dropbox/etc and share a link with me?

At the same time, what's the sha256sum of it? It should be:

db0154d8866b0a4dfc3dae4bb67211c291e4ed3ac729376bbfa0f5c231d72ed3

That's what our GitHub release has and I've just checked by pulling the tarball and that's what I got. What I don't understand is why some folks might be getting incomplete or invalid tars.

**Comment by nhobin219** [comment] 2022-10-12 22:17
> Could you upload that tar.gz to Google Drive/Dropbox/etc and share a link with me?
> 
> At the same time, what's the sha256sum of it? It should be:
> 
> db0154d8866b0a4dfc3dae4bb67211c291e4ed3ac729376bbfa0f5c231d72ed3
> 
> That's what our GitHub release has and I've just checked by pulling the tarball and that's what I got. What I don't understand is why some folks might be getting incomplete or invalid tars.

Ok, so, this is what `sha256sum` outputs:
```
user@hostname:~$ sha256sum /tmp/pulumi.tar.gz.Y8GDmiht3E
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  /tmp/pulumi.tar.gz.Y8GDmiht3E
```

Here is a link to the file: https://drive.google.com/file/d/1ZK7l1wp5WjaV0yveTECLj71_Ev827OU0/view?usp=sharing

**Comment by nhobin219** [comment] 2022-10-14 15:34
@AaronFriel I think I finally figured out what's  going on here and it has nothing to do with Pulumi. It turns out that attached file is actually just an empty file (`curl` wasn't saving the data to the output file in the `/tmp/` directory). I'm not sure why, but _snap_ `curl` seems to have issues writing to output files in various types of directories (as an example see: https://askubuntu.com/questions/1356327/cant-write-to-a-hidden-path-using-curl).

In case anyone runs into this issue in the future, the resolution for me was the solution documented in the linked thread:
```
$ sudo snap remove curl
$ sudo apt install curl
```

The pulumi install script should work just fine afterwards with _apt_ `curl` installed.

**Comment by AaronFriel** [comment] 2022-11-10 20:24
We're doing away with the auto-close bot in the future, but I think this one is still safe for us to close as no-repro. 

I'm not sure if we're going to be able to fix snap curl or how to address this. It may be worth making a ticket upstream on the Snap to allow it to write to tmp dirs.

**Closed** 2022-11-10 20:24 UTC
Labels: kind/bug, resolution/no-repro

**Comment by MaxPowerWasTaken** [comment] 2022-11-11 01:02
just ducking back in to say it is wild to me that the issue was curl being installed via snap instead of apt on my machine (apparently). very impressed with the digging @nhobin219!

**Comment by dtlary25** [comment] 2022-11-15 13:52
> @AaronFriel I think I finally figured out what's going on here and it has nothing to do with Pulumi. It turns out that attached file is actually just an empty file (`curl` wasn't saving the data to the output file in the `/tmp/` directory). I'm not sure why, but _snap_ `curl` seems to have issues writing to output files in various types of directories (as an example see: https://askubuntu.com/questions/1356327/cant-write-to-a-hidden-path-using-curl).
> 
> In case anyone runs into this issue in the future, the resolution for me was the solution documented in the linked thread:
> 
> ```
> $ sudo snap remove curl
> $ sudo apt install curl
> ```
> 
> The Pulumi install script should work just fine afterwards with _apt_ `curl` installed.

this worked for me. :) thank you

**Comment by garethdl83** [comment] 2024-07-26 01:10
Hi. I've just found this thread, and had the same problem... in Ubuntu 24.04. Indeed it was the `snap` version of `curl` that was the problem. 

Surprised it's still an issue after this long.
