### ISSUE TITLE
Always fault in missing plugins by default

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#5619] opened 2020-10-23 16:13 UTC
Currently, we *sometimes* automatically acquire plugins, but other times do not.  Specifically - we automatically acquire plugins based on whats defined in the packages the program uses (NPM, PyPI, Nuget, Go Mod, etc.).  But Pulumi also requires plugin versions that match what's in the state file for existing resources.  These should also trigger the automatic plugin acquisition.

This is a pretty serious limitation, as it means that Pulumi more or less can't reliably be used inside CI/CD - because it's very difficult to know exactly what versions of plugins will be needed ahead of time - it changes over time as the version in the state file changes.

**Comment by migueloller** [comment] 2020-10-23 20:14
To add some more detail to what @lukehoban is describing. I ran into an issue where in a CI pipeline the required plugin wasn't installed. Here's some of the stuff I concluded:

- Some plugins (e.g., GCP) are automatically installed when needed but others (e.g., Kubernetes) are not.
- Running `pulumi plugin install` does nothing, even though the documentation states the following (adding `--verbose=5` still does nothing):
>It may be run either with a specific KIND, NAME, and VERSION, or by omitting these and letting Pulumi compute the set of plugins that may be required by the current project.
- Pulumi state will be upgraded to use a new version of a plugin if there's at least one update done where both the old and new versions are present. Because in CI one can't rely on a warm cache, this means that upgrading provider versions is likely to fail.
- One can add hard-coded `pulumi plugin install [KIND NAME VERSION]` during the transition period, but this isn't very ergonomic.

So, our current workaround is to do `pulumi plugin install [KIND NAME VERSION]` so that CI will pass and then we can remove that. Ideally we could've just done `pulumi plugin install` and let Pulumi take care of figuring out which plugins are missing but for some reason that's not working. And even better, if there's a plugin detected in the state that isn't present locally, Pulumi can automatically acquire it, removing the need to run `pulumi plugin install` manually.

**Comment by migueloller** [comment] 2020-10-23 21:11
A quick update:

I tried all of the following:
- `pulumi plugin install resource kubernetes 2.2.2`
- `pulumi plugin install resource kubernetes 2.2.2 --exact`
- `yarn add @pulumi/kubernetes@2.2.2`

But no luck on getting `pulumi up` working. The only thing that worked was running `pulumi stack export`, manually tweaking the version of the provider, and then running `pulumi stack import`.

**Comment by justinvp** [comment] 2020-11-10 18:24
Note that Python doesn't currently automatically acquire plugins: https://github.com/pulumi/pulumi/issues/4848

**Comment by timmyers** [comment] 2021-01-12 22:38
I am also running into this limitation, particularly in CI jobs that are trying to `destroy` old ephemeral stacks that are no longer needed.

**Comment by infin8x** [comment] 2021-03-15 22:25
At the moment, we're not able to reproduce this. We think there may still be instances of it in the wild, though - if you're hitting it, please comment here and we'll get this reopened and work with you to get your repro.

**Comment by shreecodes** [comment] 2021-09-29 01:49
I think we just hit this issue in our CI pipeline:

```
stderr: error: could not load plugin for datadog provider 'urn:pulumi:dev::web::pulumi:providers:datadog::datadog': no resource plugin 'datadog' found in the workspace or on your $PATH
```

Our datadog provider resource was created in an earlier execution of our CI/CD pipeline, but now, subsequent `pulumi refresh` operations are not working.

**Comment by bbstilson** [comment] 2022-01-27 19:38
I just hit this issue:

```
Diagnostics:
  pulumi:providers:aws (default_4_21_2):
    error: no resource plugin 'aws-v4.21.2' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.21.2`
```

I believe this error is non-deterministic. I have experienced it randomly in the same project. As other have mentioned, this is a huge issue for using pulumi in CI

**Comment by justinvp** [comment] 2022-01-27 19:56
@bbstilson, what version of the Pulumi CLI was used when you hit this?

**Comment by lukehoban** [comment] 2022-01-27 20:01
@bbstilson One additional question - what `pulumi` operation were you running when you hit this?  Was it an `update` or a `destroy` or something else?  If a `destroy` this might be related to https://github.com/pulumi/pulumi/issues/8768.

**Comment by bbstilson** [comment] 2022-01-27 20:13
Thanks for the prompt responses @lukehoban / @justinvp . I really appreciate it!

Let me add more context. I'm running pulumi in a Docker container with the following Dockerfile:

```docker
FROM alpine:3

WORKDIR /usr/src

# install npm (and node), curl
RUN apk add --update npm curl

# cache package json and libraries
COPY package.json .
RUN npm install

# install pulumi
RUN curl -fsSL https://get.pulumi.com | sh

# add pulumi to PATH
ENV PATH="/root/.pulumi/bin:${PATH}"

WORKDIR /usr/src/pulumi
```

I run that container, and mount the specific pulumi project that I want to develop.

```bash
docker run -it --rm -v my-pulumi-project:/usr/src/pulumi my-pulumi-image
```

The full command I'm running when I hit the plugin error is:

```bash
pulumi up --stack $STACK  --show-config  --yes
```

I saw this error both on Pulumi version `3.17.0` and `3.22.1`.

**Comment by bbstilson** [comment] 2022-01-27 20:21
Another scenario I forgot: In CI, I run the same docker container but in non-interactive mode (without the `-it`) flag by running a pulumi command. I've seen this error in both cases, however.

**Comment by chrisui** [comment] 2022-01-28 11:24
I'm also having issues today. Due to various issues we need specific versions of various plugins. How we install in github actions is shared below. In bash it cant find pulumi-resource-aws and bails in a later step.

```
- uses: pulumi/action-install-pulumi-cli@v1.0.1
  with:
    pulumi-version: 3.17.1
- run: |
    pulumi plugin install resource aws v4.27.2
    pulumi plugin install resource datadog v4.3.0 
    pulumi plugin install resource docker-buildkit v0.1.12 \
      --server https://github.com/MaterializeInc/pulumi-docker-buildkit/releases/download/v0.1.12
```

Later error

```
2022-01-28T11:09:28.4708504Z Error: Command failed with exit code 127: pulumi-resource-aws --version
2022-01-28T11:09:28.4709003Z /bin/bash: pulumi-resource-aws: command not found
```

**Comment by lukehoban** [comment] 2022-01-28 15:34
Reopening this - as continued reports suggest this is still an issue.

**Comment by austinbutler** [comment] 2022-02-04 02:11
I don't really understand how plugins are supposed to be managed. OK so let's say two years ago I installed `aws 1.0.0`. Do I need to worry about updating that ever? Does the plugin version have any relation to the Node package `@pulumi/aws` version? Do their versions need to be kept in sync? 

The other challenge I face is that when I build a Docker container with Pulumi in it, I run `yarn install` in the Dockerfile so everything is ready to go when the user runs the container. Except not _everything_ is ready to go, it downloads hundreds of megabytes of plugins on first usage of Pulumi. The workaround would seem to be hardcoding something like `pulumi plugin install resource aws 1.0.0` for each plugin, but now there's separate versioning baked in to the Dockerfile we have to maintain.

I'd rather see either:
1. Running `pulumi plugin install` installs whatever plugins are needed, as someone already mentioned here
2. If for some reason we must install manually specified specific versions, at least there should be a way to track that in a file like `Pulumi.plugins.yaml` or something

**Comment by justinvp** [comment] 2022-02-04 17:47
@bbstilson, thanks for the details! One thing you may want try in your Dockerfile is installing Pulumi and adding it to `PATH` _before_ running `npm install`. The reason: The `@pulumi/*` NPM packages include an install script that runs `pulumi plugin install ...` to install the associated plugin as part of installing the NPM package. This should "prime" these plugins in the cache so won't be missing and need to be installed when running a Pulumi deployment.

> Due to various issues we need specific versions of various plugins

@chrisui, can you share why you need to install these specific versions manually? What language(s) are you using for you Pulumi program(s)?

> I don't really understand how plugins are supposed to be managed.

@austinbutler, you generally do not need to manage Pulumi plugins manually. NPM packages have an associated Pulumi plugin with the same version. See my response to @bbstilson above. When running `npm install` or `yarn install`, the `@pulumi/*` packages shell out to `pulumi plugin install ...` to install the associated plugin. You may want to check your Dockerfile to see if is installing the Pulumi CLI and making it available on `PATH` _before_ running `yarn install`. Otherwise, if a plugin isn't installed, when running Pulumi, it will install any missing plugins.

**Comment by austinbutler** [comment] 2022-02-04 18:25
@justinvp thanks, but `pulumi` was already on the PATH. To be sure I changed it from `yarn install` to `which pulumi && yarn install`. Maybe because I am using Yarn Berry?

**Comment by simwak** [comment] 2022-04-02 10:33
I'm also quite confused how the plugin handling is done. I wanted to optimize the CI job and marked the path `node_modules` as cachable (GitLab CI), so `npm install` does not download everything each job. But that apparently broke every job which used this cache. `npm install` just said that everything is already installed, but it shows that the plugin is missing.

**Comment by Frassle** [comment] 2022-04-02 11:27
The plugin binaries aren't installed in node_modules but in ~/.pulumi/plugins. pulumi just searches node_modules to see what plugins it needs to download and install to it's plugin cache.

**Comment by simwak** [comment] 2022-04-02 11:46
@Frassle But shouldn't it check `~/.pulumi/plugins` for installed plugins and not `node_modules` and then download it? As even if `node_modules` is still cached, `~/.pulumi/plugins` is maybe not and then it fails like I described. Seems like a bit counterproductive to assume that when all packages from `package.json` are present in `node_modules` , that also all plugins are installed in `~/.pulumi/plugins`.

**Comment by Frassle** [comment] 2022-04-02 12:58
> But shouldn't it check ~/.pulumi/plugins for installed plugins and not node_modules and then download it? 

How would it know what to download? There are hundreds of pulumi plugins, some not even published by pulumi we're not going to download them all. `node_modules` is looked at to tell us which plugins are wanted.

> ~/.pulumi/plugins is maybe not and then it fails like I described.

Yes that's what this issue is tracking. `pulumi up` should be finding and installing all the plugins it needs up front, but it seems that some are missed and then you get a fault that a plugin binary isn't found.

> Seems like a bit counterproductive to assume that when all packages from package.json are present in node_modules , that also all plugins are installed in ~/.pulumi/plugins.

This is not an assumption the engine makes, you have misunderstood.

**Comment by aterreno** [comment] 2022-04-08 11:38
I am experiencing this using pulumi actions, I've just raised this here https://github.com/pulumi/actions/issues/568

**Comment by ducka** [comment] 2022-04-25 17:00
@lukehoban I've been experiencing this issue myself over the past couple of days. Apologies if you're already well aware of the solution for this. 

I think I've discovered a way to reproduce this issue with dotnet infrastructure projects. In our environment we use AppVeyor to build and package the pulumi infrastructure projects. We then use Octopus Deploy to extract and deploy the infrastructure project using the `binary` option in pulumi.yaml.

Steps to reproduce.
1. Reference an old version of a pulumi plugin (like azure-native v1.58) in your pulumi c# project.
2. Execute `pulumi up ` in the root directory of your #c project. This will deploy your infrastructure, and record azure-native v1.58 as a required resource in the app.pulumi.io state.
3. Update the plugin in your pulumi project to the latest version (like azure-native 1.63).
4. Compile the c# infrastructure project locally, and copy all of the assemblies into a standalone directory on your local machine.
5. Copy the project's pulumi.*.yaml files into the standalone directory along side your assemblies.
6. In the standalone directory configure the pulumi.yaml file with the `binary` option, referencing the assembly of your infrastructure project.
7. Execute `pulumi plugin rm --all --yes to clear your local pulumi plugin cache
8. Execute `pulumi up` in the standalone directory. Pulumi will attempt to use the compiled assembly to deploy the infrastructure. It will install the old version of the plugin (azure-native v1.58)  as that's what is referenced in the app.pulumi.io state, and it will fail to deploy the infrastructure because the local binary requires the newer version of the plugin (azure-native v1.63).
9. This issue is resolved when you execute `pulumi up` in the root directory of the c# project, because it's able to resolve the updated plugin version from the csproj files. The plugin version in the app.pulumi.io cloud state is then updated to the latest version (azure-native v1.63). If you then attempt to execute `pulumi up` on the standalone directory again (containing the binaries), the deployment will succeed.

The issue here is how pulumi resolve plugin versions when deploying infrastructure using the `binary` option.

I feel like this issue would be resolved for .Net projects if pulumi resolved the plugin version from the *.deps.json file that is co-located with the binaries, or if some sort of plugin manifest (perhaps stored in the pulumi.yaml file) was co-located with the assemblies.

I think a workaround for this issue at the moment (for c# projects anyways) is to interrogate the *.deps.json file on the deployment server for Pulumi.* dependencies, and then to execute a `pulumi plugin install <dependency> <version>` for every pulumi plugin dependency you encounter in the deps file. At least this way you can be certain that the dependencies required by your infrastructure binary are installed on the deployment machine.

**Comment by iAmAdamReid** [comment] 2022-04-28 20:34
I wanted to share something that worked for me with this issue. 

For context, I'm using:
- Github Actions for CI/CD
- Node JS application
- Pulumi + AWS infra

I was running into the same issue where any time the `@pulumi/aws` dependency was updated, the `pulumi up` step in the CI deployment would fail and output this error:

```
error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v4.38.1 or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.38.1`
```

The initial attempt to fix this was to add a step in the GH Actions workflow before the `pulumi up` step:

`pulumi plugin install resource aws v4.38.1`

Since this is what the error message prescribes, you'd expect it to resolve the issue. It does not, however, as I'm sure many of you have discovered. 

What _did_ end up resolving this for me was to add a `pulumi plugin rm` step _before_ the `pulumi plugin install` step. 

Additionally, I added a `refresh: true` flag to the `pulumi up` action. I can't say for certain if it has any relevance, but this combination of steps in GitHub Actions seems to have resolved the issue:

```
runs:
  using: "composite"
  steps:
    # ... setup aws credentials, do whatever else needs to be done ...
    - name: Install Pulumi CLI
      uses: pulumi/setup-pulumi@v2
    - name: Remove any old instances of Pulumi AWS resource provider plugins
      run: pulumi plugin rm resource aws
      shell: bash
    - name: Install Pulumi AWS resource provider plugins
      run: pulumi plugin install resource aws v4.38.1 --exact --reinstall
      # Use whatever aws version you need here to match the version of @pulumi/aws in your package.json
      shell: bash
    - name: Configure Pulumi
      uses: pulumi/actions@v3
      with:
        command: up
        # stack-name: whatever-stack
        # work-dir: whatever-dir
        refresh: true
```

Once I added the `pulumi plugin rm` step before the `pulumi plugin install` step, the GHA CI runner seems to handle the version update on its own without needing to do any manual deploys, or edits of the stack export json, or etc. 

I'm not 100% certain whether the `--reinstall` flag has any use here since I'm using `rm` prior to it anyway. 

Same with the `refresh: true` flag, I'm not 100% certain whether it's directly relevant.

You could try just adding the `plugin rm` step before the `plugin install` step, and if it doesn't work, try adding those two flags and see if that does it. 

This is obviously not ideal to have to `rm` and `install` the plugin with every workflow run, so once the plugin version update is successful you can probably remove the `rm` step until you need to update the dependency again. 

Ideally you'd want to have some kind of check to do something like:
```
# If the Pulumi aws plugin version does not match the package.json version
# Run the pulumi plugin rm step before the install step
# Otherwise, just run the pulumi plugin install step
```

But I haven't gotten that far yet. 

Let me know if this helps!

**Comment by aterreno** [comment] 2022-05-05 12:52
@iAmAdamReid  I'd probably try to remove the refresh because all that does it query aws and refresh the pulumi state.. 
it's quite time consuming, I'd probably go for just having
```run: pulumi plugin install resource aws v4.38.1 --exact --reinstall```

We also resolved this, what I did learn/notice is that we were not using properly the yarn cache and packaging properly the node_modules (we work with a monorepo). 

Effectively the provider is just an NPM dependency, so the root cause seem to be that, a missing dep.

**Comment by austinbutler** [comment] 2022-06-22 01:36
Running into the same issue with Pulumi v3.34.1. Previously I believe this project was working.

```console
Diagnostics:
  pulumi:providers:newrelic (default_4_17_0):
    error: no resource plugin 'pulumi-resource-newrelic' found in the workspace at version v4.17.0 or on your $PATH, install the plugin using `pulumi plugin install resource newrelic v4.17.0`
```

For whatever reason `pulumi preview` or `pulumi up` will automatically download `newrelic-4.10.0` (probably the version I was using before doing updates), but it won't download the new version, `newrelic-4.17.0`. Running `pulumi plugin install` does nothing. If I run `pulumi plugin install resource newrelic v4.17.0` as the output suggests, Pulumi works again.

**Comment by aterreno** [comment] 2022-07-01 07:52
One more on this, I think I've found a fix that works and it's decent enough (also adds just about 8 secs of overhead) 

```yaml
      - name: Install packages
        run: yarn install
      - name: Install pulumi aws plugin
        run: pulumi plugin install resource aws v5.9.2 # matching package.json "@pulumi/aws"        
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ inputs.stack }}
          cloud-url: s3://.... 
          message: ${{ github.event.head_commit.message }}
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
```

**Comment by bradyburke** [comment] 2022-08-17 21:07
Recently ran into the same issue with EKS:
``` "    pulumi:providers:eks default  error: no resource plugin 'pulumi-resource-eks' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource eks`\n" +
      '@ Updating........\n' +
      ' +  aws:ec2:NatGateway akeyless-eu-central-1-vpc-0 created \n' +
      '    pulumi:providers:eks default **failed** 1 error\n' +
      ' +  pulumi:pulumi:Stack akeyless-main-akeyless.prod-infra.eu-central-1 created \n' +
      ' +  eks:index:Cluster akeyless-eu-central-1-cluster created \n' +
      ' \n' +
      'Diagnostics:\n' +
      '  pulumi:providers:eks (default):\n' +
      "    error: no resource plugin 'pulumi-resource-eks' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource eks`\n" +
      ' \n' +
      'Resources:\n' +
      '    + 40 created\n' +
      '\n' +
      'Duration: 2m9s\n' +
      '\n',
    stderr: '',
    code: 255,
    err: undefined
  }
}```
Using typescript/nodejs to install `"@pulumi/eks": "^0.41.2",` from NPM, but then pulumi fails to notice that the resource plugin is missing.

**Comment by mike-chen-samsung** [comment] 2022-08-18 23:12
Also running into this issue on a new stack (empty state) in a clean env (no plugins or node_modules initially).

```
error: no resource plugin 'pulumi-resource-eks' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource eks`
```

Then when I removed the stack and cleaned the env again, it happened with a different provider

```
error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v5.9.2 or on your $PATH, install the plugin using `pulumi plugin install resource aws v5.9.2`
```

**Closed** 2022-08-31 11:23 UTC
Labels: area/cli, kind/enhancement, area/plugins
