### ISSUE TITLE
Pulumi Go automation API replaces secrets_providers in a state file stored in an S3 bucket

### ISSUE THREAD

**Issue by mraszplewicz** [pulumi/pulumi#7278] opened 2021-06-11 10:23 UTC
I am trying to use Pulumi automation API in Go with an S3 bucket backend and awskms secret provider. The secrets_providers part of the state file is being replaced after the second run.

## Steps to reproduce
1. Run this code:
```go
package main

import (
	"context"
	"fmt"
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/auto"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optup"
	"github.com/pulumi/pulumi/sdk/v3/go/common/tokens"
	"github.com/pulumi/pulumi/sdk/v3/go/common/workspace"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"os"
)

func main() {
	deployFunc := func(ctx *pulumi.Context) error {
		bucket, err := s3.NewBucket(ctx, "s3-bucket", &s3.BucketArgs{
		})
		if err != nil {
			return err
		}
		ctx.Export("bucketArn", bucket.Arn)
		return nil
	}

	ctx := context.Background()

	projectName := "inlineS3Project"
	stackName := "dev"

	cwd, err := os.Getwd()
	if err != nil {
		fmt.Printf("Failed to get working directory: %v\n", err)
		os.Exit(1)
	}
	opts := []auto.LocalWorkspaceOption{
		auto.Project(workspace.Project{
			Name:    tokens.PackageName(projectName),
			Runtime: workspace.NewProjectRuntimeInfo("go", nil),
			Main:    cwd,
			Backend: &workspace.ProjectBackend{
				URL: "s3://devopsbox-test-pulumi-backend",
			},
		}),
		auto.SecretsProvider("awskms://alias/pulumi-secret-encryption"),
	}

	s, err := auto.UpsertStackInlineSource(ctx, stackName, projectName, deployFunc, opts...)

	w := s.Workspace()

	err = w.InstallPlugin(ctx, "aws", "v4.0.0")
	if err != nil {
		fmt.Printf("Failed to install program plugins: %v\n", err)
		os.Exit(1)
	}

	s.SetConfig(ctx, "aws:region", auto.ConfigValue{Value: "eu-west-1"})

	_, err = s.Refresh(ctx)
	if err != nil {
		fmt.Printf("Failed to refresh stack: %v\n", err)
		os.Exit(1)
	}

	stdoutStreamer := optup.ProgressStreams(os.Stdout)

	res, err := s.Up(ctx, stdoutStreamer)
	if err != nil {
		fmt.Printf("Failed to update stack: %v\n\n", err)
		os.Exit(1)
	}

	bucketArn, ok := res.Outputs["bucketArn"].Value.(string)
	if !ok {
		fmt.Println("Failed to unmarshall output")
		os.Exit(1)
	}

	fmt.Printf("bucketArn: %s\n", bucketArn)
}
```
2. Check the state file in the S3 bucket. It should be something similar to:
```json
"secrets_providers": {
  "type": "cloud",
  "state": {
    "url": "awskms://alias/pulumi-secret-encryption",
    "encryptedkey": "AQICAHiHq/OyuGslCBTaqYO+UOVn19Ob+AfaT5XqVvyrEZ688wEdkG0y8M9LUeYpVORmIPVXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMbdujk7shVsubHivAgEQgDvKvGe1L/GwU01AGBFO2sqZtnAM6XEJpS7h1JFVRtQV6Sal3kaa/aI6bFIhwzwkoqICTxi0lbtgFYiGCQ=="
  }
}
```
3. Run the code again. There is an error:
```
Failed to refresh stack: code: 255
, stdout: 
, stderr: error: getting secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables

: failed to refresh stack: exit status 255
exit status 1
```
4. Add PULUMI_CONFIG_PASSPHRASE to the code and run it again:
```go
package main

import (
	"context"
	"fmt"
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/auto"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optup"
	"github.com/pulumi/pulumi/sdk/v3/go/common/tokens"
	"github.com/pulumi/pulumi/sdk/v3/go/common/workspace"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"os"
)

func main() {
	deployFunc := func(ctx *pulumi.Context) error {
		bucket, err := s3.NewBucket(ctx, "s3-bucket", &s3.BucketArgs{
		})
		if err != nil {
			return err
		}
		ctx.Export("bucketArn", bucket.Arn)
		return nil
	}

	ctx := context.Background()

	projectName := "inlineS3Project"
	stackName := "dev"

	cwd, err := os.Getwd()
	if err != nil {
		fmt.Printf("Failed to get working directory: %v\n", err)
		os.Exit(1)
	}
	opts := []auto.LocalWorkspaceOption{
		auto.Project(workspace.Project{
			Name:    tokens.PackageName(projectName),
			Runtime: workspace.NewProjectRuntimeInfo("go", nil),
			Main:    cwd,
			Backend: &workspace.ProjectBackend{
				URL: "s3://devopsbox-test-pulumi-backend",
			},
		}),
		auto.SecretsProvider("awskms://alias/pulumi-secret-encryption"),
		auto.EnvVars(map[string]string{
			"PULUMI_CONFIG_PASSPHRASE": "password",
		}),
	}

	s, err := auto.UpsertStackInlineSource(ctx, stackName, projectName, deployFunc, opts...)

	w := s.Workspace()

	err = w.InstallPlugin(ctx, "aws", "v4.0.0")
	if err != nil {
		fmt.Printf("Failed to install program plugins: %v\n", err)
		os.Exit(1)
	}

	s.SetConfig(ctx, "aws:region", auto.ConfigValue{Value: "eu-west-1"})

	_, err = s.Refresh(ctx)
	if err != nil {
		fmt.Printf("Failed to refresh stack: %v\n", err)
		os.Exit(1)
	}

	stdoutStreamer := optup.ProgressStreams(os.Stdout)

	res, err := s.Up(ctx, stdoutStreamer)
	if err != nil {
		fmt.Printf("Failed to update stack: %v\n\n", err)
		os.Exit(1)
	}

	bucketArn, ok := res.Outputs["bucketArn"].Value.(string)
	if !ok {
		fmt.Println("Failed to unmarshall output")
		os.Exit(1)
	}

	fmt.Printf("bucketArn: %s\n", bucketArn)
}
```

Expected: The secrets_providers part of the state file remains unchanged.
Actual: The secrets_providers is replaced with:
```json
"secrets_providers": {
  "type": "passphrase",
  "state": {
    "salt": "v1:79xX7+zBATU=:v1:7uniBTL7+zi9pSz6:9YRv/LuCjg4kYg7L9iwyR7n15GxpWQ=="
  }
}
```

If I have PULUMI_CONFIG_PASSPHRASE uncommented from the beginning, the result is exactly the same - the first run with awskms secrets_providers and the second with a passphrase.

**Comment by mraszplewicz** [comment] 2021-06-11 11:49
Digging a little bit into the automation API and debugging:
It looks like when the stack exists, it is not refreshing the config and sets all the values from scratch (here only the `aws:region`). I tried to refresh manually but `pulumi config refresh` does not download `secretsprovider` and `encryptedkey` fields from the remote state file.

**Comment by leezen** [comment] 2021-06-11 22:43
Duplicate of https://github.com/pulumi/pulumi/issues/5432 -- you'll want to set the secrets provider within the stack settings. There's no Go example (per #5432) but you'll want to do the equivalent of https://github.com/pulumi/automation-api-examples/blob/main/nodejs/inlineSecretsProvider-ts/index.ts#L94 in Go (see https://github.com/pulumi/pulumi/issues/5432#issuecomment-828027576)

**Comment by leezen** [comment] 2021-06-11 22:48
We've also opened https://github.com/pulumi/pulumi/issues/7282 to track the other part of what you've brought up regarding config.

**Closed by leezen** 2021-06-11 22:48 UTC
Labels: area/automation-api, kind/bug, resolution/duplicate

**Comment by mraszplewicz** [comment] 2021-06-13 18:53
@leezen thanks for your help!

I have checked your suggested solution and it works. I had to add `auto.Stacks` to the `auto.LocalWorkspaceOption`:
```go
secretsProvider := "awskms://alias/pulumi-secret-encryption"
opts := []auto.LocalWorkspaceOption{
	auto.Project(workspace.Project{
		Name:    tokens.PackageName(projectName),
		Runtime: workspace.NewProjectRuntimeInfo("go", nil),
		Main:    cwd,
		Backend: &workspace.ProjectBackend{
			URL: "s3://devopsbox-test-pulumi-backend",
		},
	}),
	auto.SecretsProvider(secretsProvider),
	auto.Stacks(map[string]workspace.ProjectStack{
		stackName: {
			SecretsProvider: secretsProvider,
		},
	}),
}
```
and that's all. Each time I run the stack, the `encryptedkey` field in the state file changes, but I don't know if it affects anybody.

There was a typo in earlier versions of `local_workspace.go` fixed by this commit: https://github.com/pulumi/pulumi/commit/4b3d2a57c77a934a03bbb6cb3b1cc233a45d7bb9, so I had to upgrade Pulumi version.

I am posting this for anyone having a similar problem.
