### ISSUE TITLE
Issue unprotecting a gcp app engine

### ISSUE THREAD

**Issue by jchs** [pulumi/pulumi#10450] opened 2022-08-19 11:11 UTC
### What happened?
```
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.38.0
Go Version:       go1.19
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: slice bounds out of range [:-2]


goroutine 1 [running]:
runtime/debug.Stack()
        /Users/runner/hostedtoolcache/go/1.19.0/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x34
panic({0x104085880, 0x1400047a0d8})
        /Users/runner/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x204
gopkg.in/AlecAivazis/survey%2ev1.paginate(0x140003e16fa?, {0x140004f27a0?, 0x14000859438?, 0x102873fe0?}, 0x14000859408?)
        /Users/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:254 +0xe0
gopkg.in/AlecAivazis/survey%2ev1.(*Select).Prompt(0x1400067e5b0)
        /Users/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/select.go:199 +0xf8
gopkg.in/AlecAivazis/survey%2ev1.Ask({0x140008596f0, 0x1, 0x5?}, {0x103d87520?, 0x14000635300}, {0x0, 0x0, 0x1400067e5b0?})
        /Users/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:148 +0x1b0
gopkg.in/AlecAivazis/survey%2ev1.AskOne({0x1041ab5f0?, 0x1400067e5b0?}, {0x103d87520?, 0x14000635300?}, 0x1?, {0x0?, 0x0?, 0x0?})
        /Users/runner/go/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.9-0.20200217094205-6773bdf39b7f/survey.go:94 +0x6c
main.locateStackResource({{0x103826e75, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:113 +0x614
main.runStateEdit.func1({{0x103826e75, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:129 +0x50
main.runTotalStateEdit({0x1041ace68, 0x140001a2000}, {0x0, 0x0}, 0x1, 0x14000859bc8)
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:175 +0x378
main.runStateEdit({0x1041ace68?, 0x140001a2000?}, {0x0?, 0x19?}, 0x48?, {0x16d91b89f?, 0x0?}, 0x19?)
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:128 +0x54
main.unprotectResource({0x1041ace68?, 0x140001a2000?}, {0x0?, 0x14000a67180?}, {0x16d91b89f?, 0x0?}, 0x1?)
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:95 +0x48
main.newStateUnprotectCommand.func1(0xe?, {0x1400036e710, 0x1, 0x1026ce674?})
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:59 +0xc4
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000a68500?, {0x1400036e710, 0x1, 0x1})
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000a68500, {0x1400036e6e0, 0x1, 0x1})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x14000576c80)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x3c
```

### Steps to reproduce

```
Diagnostics:
  gcp:appengine:Application (app):
    error: Preview failed: unable to delete resource "urn:pulumi:staging::***::gcp:appengine/application:Application::app"
    as it is currently marked for protection. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumi program and run `pulumi up` or use the command:
    `pulumi state unprotect 'urn:pulumi:staging::***::gcp:appengine/application:Application::app'`
 
  pulumi:pulumi:Stack (***):
    error: preview failed
``` 

`❯ pulumi state unprotect 'urn:pulumi:staging::***::gcp:appengine/application:Application::app'`

### Expected Behavior

I expected the state of "datastore" to be unprotected

### Actual Behavior

The Pulumi CLI encountered a fatal error.

### Output of `pulumi about`
```
pulumi about
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.34.0
python  unknown

Host     
OS       darwin
Version  12.5
Arch     arm64

This project is written in python: executable='/Users/***/Documents/Git/***/venv/bin/python3' version='3.10.5
'

Backend        
Name           ***
URL            file://~
User           ***
Organizations  

Dependencies:
NAME        VERSION
pip         22.2.2
pulumi-gcp  6.34.0
setuptools  63.4.2
wheel       0.37.1

Pulumi locates its logs in /var/folders/bz/fllf5g610_qcjl8tq1nws6vc0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2022-08-23 17:53
Looks like we have a fix - https://github.com/pulumi/pulumi/pull/10475 - this regression was introduced in 3.38.0 and will be fixed in the next release. You can downgrade Pulumi CLI to pre-3.38.0 in the meanwhile as a workaround.

**Closed** 2022-08-23 20:45 UTC
Labels: kind/bug, area/cli, p1, impact/panic, awaiting-upstream

**Comment by jchs** [comment] 2022-08-26 05:47
Thank you @t0yv0! 

That worked :)
