### ISSUE TITLE
Provider plugins version mismatch

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi#7532] opened 2021-07-15 08:12 UTC
Hi, I changed a code bit and `pulumi up` and `preview` suddenly stopped to work completely.

```$ pulumi preview
Previewing update (production):
     Type                                                Name                                         Plan        Info
     pulumi:pulumi:Stack                                 devops-production                                        
 +   ├─ azuread:index:Application                        devops-testing                               create      
 +   ├─ random:index:RandomString                        devops-testing                               create      
 +   ├─ random:index:RandomString                        devops-production                            create      
 +   ├─ azuread:index:ServicePrincipal                   devops-testing                               create      
 +   ├─ azuread:index:Application                        devops-testing-cr                            create      
 +   ├─ azuread:index:ServicePrincipalPassword           devops-testing                               create      
 +   ├─ azuread:index:ServicePrincipal                   devops-testing-cr                            create      
 +   ├─ azure-native:containerregistry:Registry          devops-testing                               create      
 +   ├─ azure-native:authorization:RoleAssignment        devops-testing                               create      
 +   ├─ azure-native:containerregistry:Registry          devops-production                            create      
 +   ├─ azuread:index:Application                        devops-testing-cr-pull                       create      
 +   ├─ azuread:index:ServicePrincipalPassword           devops-testing-cr                            create      
 ~   ├─ azuredevops:index:ServiceEndpointDockerRegistry  devops                                       update      [diff: ~dockerRegistry]
 +   ├─ azure-native:authorization:RoleAssignment        devops-testing-service_principal_cr-acrpush  create      
 +-  ├─ azure-native:authorization:RoleAssignment        devops-service_principal_cr-acr_pull         replace     [diff: ~scope]
 +-  ├─ azure-native:authorization:RoleAssignment        devops-service_principal_cr-acrpush          replace     [diff: ~scope]
 +   ├─ random:index:RandomString                        devops-pipeline-ci                           create      
 +   ├─ azuread:index:Application                        adminportal-testing                          create      
 +   ├─ random:index:RandomString                        apcustomermanagement-pipeline-ci             create      
 +   ├─ random:index:RandomString                        adminportal-pipeline-ci                      create      
 +   ├─ random:index:RandomString                        devopspipelines-pipeline-ci                  create      
 +   ├─ azuread:index:ServicePrincipal                   devops-testing-cr-pull                       create      
     └─ pulumi:providers:random                          default_1_13_0                                           1 error
 
Diagnostics:
  pulumi:providers:random (default_1_13_0):
    error: no resource plugin 'random-v1.13.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource random v1.13.0`
 

$ pulumi plugin install resource random v1.13.0
[resource plugin random-1.13.0] installing
error: [resource plugin random-1.13.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-random-v1.13.0-linux-amd64.tar.gz 
```
For the provider `random` there is in a state file: 
```{
    "urn": "urn:pulumi:production::devops::pulumi:providers:random::default_4_2_0",
    "custom": true,
    "id": "c7d84f93-085e-41fa-9820-f6990ec2bc48",
    "type": "pulumi:providers:random",
    "inputs": {
        "version": "4.2.0"
    },
    "outputs": {
        "version": "4.2.0"
    }
},
```

However there is a provider `azure-native` with that version:
```
{
    "urn": "urn:pulumi:production::devops::pulumi:providers:azure-native::default",
    "custom": true,
    "id": "6be14437-1fa3-45e8-9b31-25b461982793",
    "type": "pulumi:providers:azure-native",
    "inputs": {
        "version": "1.13.0"
    },
    "outputs": {
        "version": "1.13.0"
    }
},
```
And when I updated `pulumi-azure-native` to v1.16.0 with `$ pip install pulumi-azure-native==1.16.0`

Now I'm getting demand for `random-v1.16.0 `!:
```
$ pulumi up
Previewing update (production):
     Type                                                Name                                         Plan        Info
     pulumi:pulumi:Stack                                 devops-production                                        
 +   ├─ azuread:index:Application                        devops-testing                               create      
 +   ├─ random:index:RandomString                        devops-testing                               create      
 +   ├─ random:index:RandomString                        devops-production                            create      
 +   ├─ azuread:index:ServicePrincipal                   devops-testing                               create      
 +   ├─ azuread:index:Application                        devops-testing-cr                            create      
 +   ├─ azuread:index:ServicePrincipalPassword           devops-testing                               create      
 +   ├─ azuread:index:ServicePrincipal                   devops-testing-cr                            create      
 +   ├─ azure-native:containerregistry:Registry          devops-testing                               create      
 +   ├─ azure-native:authorization:RoleAssignment        devops-testing                               create      
 +   ├─ azure-native:containerregistry:Registry          devops-production                            create      
 +   ├─ azuread:index:Application                        devops-testing-cr-pull                       create      
 +   ├─ azuread:index:ServicePrincipalPassword           devops-testing-cr                            create      
 ~   ├─ azuredevops:index:ServiceEndpointDockerRegistry  devops                                       update      [diff: ~dockerRegistry]
 +   ├─ azuread:index:ServicePrincipal                   devops-testing-cr-pull                       create      
 +   ├─ azuredevops:index:ServiceEndpointDockerRegistry  devops-testing                               create      
 +   ├─ azure-native:authorization:RoleAssignment        devops-testing-service_principal_cr-acrpush  create      
 +-  ├─ azure-native:authorization:RoleAssignment        devops-service_principal_cr-acr_pull         replace     [diff: ~scope]
 +-  ├─ azure-native:authorization:RoleAssignment        devops-service_principal_cr-acrpush          replace     [diff: ~scope]
 +   ├─ random:index:RandomString                        devops-pipeline-ci                           create      
 +   ├─ random:index:RandomString                        devopspipelines-pipeline-ci                  create      
 +   ├─ azuread:index:Application                        adminportal-testing                          create      
 +   ├─ random:index:RandomString                        adminportal-pipeline-ci                      create      
 +   ├─ random:index:RandomString                        apcustomermanagement-pipeline-ci             create      
 +   ├─ azuread:index:ServicePrincipalPassword           devops-testing-cr-pull                       create      
     └─ pulumi:providers:random                          default_1_16_0                                           1 error
 
Diagnostics:
  pulumi:providers:random (default_1_16_0):
    error: no resource plugin 'random-v1.16.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource random v1.16.0`
 ```
 So obviously there is a mismatch between providers plugins and their versions :thinking: 
 
 For complete picture here is a pulumi version and plugin list:
 ```
$ pulumi version
v3.7.0
$ pulumi plugin ls
NAME          KIND      VERSION  SIZE    INSTALLED  LAST USED
azure         resource  4.10.0   234 MB  n/a        1 day ago
azure         resource  4.7.0    230 MB  n/a        1 month ago
azure         resource  4.6.0    229 MB  n/a        1 month ago
azure         resource  4.3.0    228 MB  n/a        1 month ago
azure         resource  4.2.0    227 MB  n/a        2 months ago
azure         resource  4.1.0    225 MB  n/a        2 months ago
azure-native  resource  1.16.0   42 MB   n/a        39 minutes ago
azure-native  resource  1.14.0   42 MB   n/a        3 weeks ago
azure-native  resource  1.13.0   42 MB   n/a        3 weeks ago
azure-native  resource  1.12.0   42 MB   n/a        4 weeks ago
azure-native  resource  1.11.0   42 MB   n/a        1 month ago
azure-native  resource  1.9.0    42 MB   n/a        1 month ago
azure-native  resource  1.7.0    42 MB   n/a        1 month ago
azure-native  resource  1.5.0    41 MB   n/a        2 months ago
azure-native  resource  1.3.0    41 MB   n/a        2 months ago
azuread       resource  4.3.0    41 MB   n/a        1 day ago
azuread       resource  4.2.1    41 MB   n/a        4 weeks ago
azuread       resource  4.2.0    41 MB   n/a        1 month ago
azuread       resource  4.0.0    40 MB   n/a        2 months ago
azuredevops   resource  2.1.1    43 MB   n/a        3 weeks ago
azuredevops   resource  2.1.0    42 MB   n/a        1 month ago
azuredevops   resource  2.0.0    42 MB   n/a        2 months ago
kubernetes    resource  3.5.0    67 MB   n/a        18 hours ago
kubernetes    resource  3.4.0    67 MB   n/a        2 weeks ago
kubernetes    resource  3.3.1    78 MB   n/a        4 weeks ago
kubernetes    resource  2.8.2    77 MB   n/a        4 months ago
random        resource  4.2.0    31 MB   n/a        1 month ago
random        resource  4.1.1    31 MB   n/a        2 months ago
random        resource  4.0.0    31 MB   n/a        2 months ago

TOTAL plugin cache size: 2.4 GB
```

**Comment by jancespivo** [comment] 2021-07-15 08:34
I founded the root cause! I'm heavily changing resource names via aliases and using this construct:
```
opts_kwargs["opts"] = pulumi.ResourceOptions(
      aliases=[pulumi.Alias(name="original_resource_name")]
)

resource_group = resources.ResourceGroup(
      ...
       **opts_kwargs,
  )
random_string = random.RandomString(
      ...
      **opts_kwargs,
)
```
to save typing. However it doesn't work because it reuses one single instance of `pulumi.ResourceOptions` for every resource.
It started to work when I changed this snippet for each resource to  ```
...
opts=pulumi.ResourceOptions(
      aliases=[pulumi.Alias(name="original_resource_name")]
)
...
```

**Comment by Frassle** [comment] 2022-06-13 10:53
Duplicate of https://github.com/pulumi/pulumi/issues/9801

**Closed by Frassle** 2022-06-13 10:53 UTC
Labels: kind/bug, resolution/duplicate
