### ISSUE TITLE
Add flag to the `pulumi stack` command to show the fully qualified name

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#11379] opened 2022-11-16 18:09 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

At the moment you can run `pulumi stack --show-name` and get the name of the stack, but would be useful to be able to get the "fully-qualified" stack name (so `{organisation name}/{project name}/{stack name}`)

**Comment by aq17** [comment] 2022-11-16 18:39
Closing as duplicate of https://github.com/pulumi/pulumi/issues/11081, pinned on other issue for flag suggestion.

**Closed** 2022-11-16 18:39 UTC
Labels: kind/enhancement, resolution/duplicate
