### ISSUE TITLE
Node multi-lang components dropping dependencies unless included in state. 

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#6913] opened 2021-04-29 00:28 UTC
I have a multi-lang provider component written in typescript that creates a `awsx.ecs.FargateService`. The component looks roughly like:

```ts
@PulumiComponent(typeToken)
export class FargateContainerApp extends pulumi.ComponentResource implements IContainerApp {
    @ComponentState
    endpoint: pulumi.Output<string>;
    @ComponentState // this decorator causes the prop to be stored in state
    fargateService: awsx.ecs.FargateService;

    constructor(name: string, args: IContainerAppArgs, opts?: pulumi.ComponentResourceOptions) {
        super(typeToken, name, args, opts);

        this.fargateService = new awsx.ecs.FargateService(name, {
            taskDefinitionArgs: {
                taskRole: role,
                container: {
                    image,
                    environment,
                    applicationListener: {
                        port: args.port,
                        protocol: "HTTP",
                        external: true,
                    },
                }
            }
        }, { parent: this });

        this.endpoint = pulumi.output("");
        for (const [k, v] of Object.entries(this.fargateService.applicationListeners)) {
            this.endpoint = pulumi.interpolate`http://${v.endpoint.hostname}:${v.endpoint.port}`;
            break;
        }
       
        this.registerOutputs({
            endpoint: this.endpoint
        });
    }
}
```

On first update, everything is created fine. One second update, the ecs service and ecs task attached the the `awsx.ecs.FargateService` components get deleted:

```
I0428 17:14:13.488947   99018 deployment_executor.go:314] performDeletes(...): beginning
I0428 17:14:13.488976   99018 step_generator.go:703] Planner decided to delete 'urn:pulumi:repro::astro-ts::astro-containerApp-fargate:index:ContainerApp$awsx:x:ecs:FargateService$aws:ecs/service:Service::ui'
I0428 17:14:13.489001   99018 step_generator.go:703] Planner decided to delete 'urn:pulumi:repro::astro-ts::astro-containerApp-fargate:index:ContainerApp$awsx:x:ecs:FargateTaskDefinition$aws:ecs/taskDefinition:TaskDefinition::ui'
I0428 17:14:13.489028   99018 step_generator.go:703] Planner decided to delete 'urn:pulumi:repro::astro-ts::astro-containerApp-fargate:index:ContainerApp$awsx:x:ecs:FargateService$aws:ecs/service:Service::api'
I0428 17:14:13.489045   99018 step_generator.go:703] Planner decided to delete 'urn:pulumi:repro::astro-ts::astro-containerApp-fargate:index:ContainerApp$awsx:x:ecs:FargateTaskDefinition$aws:ecs/taskDefinition:TaskDefinition::api'
```

In order to work around this, I also have to include the service and task in the state:

```ts
      ....
      @ComponentState      
      service: aws.ecs.Service;
      @ComponentState
      taskDefinition: aws.ecs.TaskDefinition;
        ...
        this.service = this.fargateService.service;
        this.taskDefinition = this.fargateService.taskDefinition.taskDefinition;
```

**Comment by pgavlin** [comment] 2021-05-26 19:54
I cannot reproduce this. Here's the code for my component and my program: https://gist.github.com/pgavlin/71df0b1a55a8b7a03b4eea287e9e28f9

Each of those scripts lives in its own package (separate directories, package.json files, etc. etc.). I'm running the program like so:

```bash
$ PATH=$PATH:/path/to/component pulumi up
```

Both the first and subsequent updates work as expected. @EvanBoyle are you still able to reproduce this using your original setup?

**Comment by EvanBoyle** [comment] 2021-05-26 21:25
The exact configuration had one additional layer. `FargateContainerApp` was created from within a separate provider and an instance of that component was init'd from the program. 

I will try my repro again shortly and report back.

**Comment by EvanBoyle** [comment] 2021-05-27 19:43
I can confirm the original repro is still working. I will follow up via email with instructions.

**Comment by pgavlin** [comment] 2021-05-27 20:44
Awesome; thanks!

**Comment by pgavlin** [comment] 2021-07-20 22:05
I strongly suspect that this was fixed with https://github.com/pulumi/pulumi/pull/7541. I'm going to go ahead and close this out--if it rears its head again, we can go ahead and reopen.

**Closed** 2021-07-20 22:43 UTC
Labels: area/multi-language-components, kind/bug, resolution/duplicate, size/L
