### ISSUE TITLE
Self Hosted State should distinguish projects and stacks

### ISSUE THREAD

**Issue by ShedPlant** [pulumi/pulumi#11320] opened 2022-11-10 17:14 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Using S3 for storing state doesn't use project name for disambiguation, but should.

The core concept of project and stack is still applicable to self-hosted backend, even if organisation arguably isn't.

#### Hosted State Backend

When using the Pulumi Hosted backend, there is a organisation/project/stack convention e.g.:
- `fruit_company/apple/production`
- `fruit_company/apple/staging`
- `fruit_company/banana/production`
- `fruit_company/banana/staging`

With example folder structure:
- `fruit_company_repo/apple/deployment/__main__.py`
- `fruit_company_repo/apple/deployment/Pulumi.yaml`
- `fruit_company_repo/apple/deployment/Pulumi.production.yaml`
- `fruit_company_repo/apple/deployment/Pulumi.staging.yaml`
- `fruit_company_repo/banana/deployment/__main__.py`
- `fruit_company_repo/banana/deployment/Pulumi.yaml`
- `fruit_company_repo/banana/deployment/Pulumi.production.yaml`
- `fruit_company_repo/banana/deployment/Pulumi.staging.yaml`

Pulumi deployment files can reference the outputs of other upstream stacks with full namespace . For example, the banana production project can reference something in the apple production project with `pulumi.StackReference("fruit_company/apple/production")`.

This all works and makes perfect sense to me 👍 .

#### AWS S3 State Backend

I am experimenting with using AWS S3 state backend as per https://www.pulumi.com/docs/intro/concepts/state/ .

I configure both project `apple`'s and project `banana`'s `Pulumi.yaml` file with:
```yaml
backend:
  url: s3://fruit_company.pulumi-state/
```

If I deploy project `apple`, stack `staging`, it's saved to:
`s3://fruit_company.pulumi-state/.pulumi/stacks/staging.json`

`apple` isn't in the path! This is a problem because if I want to deploy project `banana`, stack `staging`, it will overwrite to the same file ⚠️ !

The documentation says "The bucket-name value can include multiple folders, such as my-bucket/app/project1. This is useful when storing multiple projects’ state in the same bucket."

I tried this, so `apple`'s `Pulumi.yaml`  had:
```yaml
backend:
  url: s3://fruit_company.pulumi-state/apple/
```

whereas `banana`'s `Pulumi.yaml` had:
```yaml
backend:
  url: s3://fruit_company.pulumi-state/banana/
```

This prevents the direct clash but is no good because when `banana` tries to get an output from `apple`, it fails to find the stack.

As a workaround I can copy the project name into the stack name e.g. 
- `fruit_company_repo/apple/deployment/__main__.py`
- `fruit_company_repo/apple/deployment/Pulumi.yaml`
- `fruit_company_repo/apple/deployment/Pulumi.apple.production.yaml`
- `fruit_company_repo/apple/deployment/Pulumi.apple.staging.yaml`
- `fruit_company_repo/banana/deployment/__main__.py`
- `fruit_company_repo/banana/deployment/Pulumi.yaml`
- `fruit_company_repo/banana/deployment/Pulumi.banana.production.yaml`
- `fruit_company_repo/banana/deployment/Pulumi.banana.staging.yaml`

banana project can `pulumi.StackReference("apple.staging")`.

This naming convention does work but is clumsy and prone to disaster if I accidentally uses the same stack name in future.

**Comment by Frassle** [comment] 2022-11-11 10:07
Thanks for the very detailed write up. I think this is a duplicate of https://github.com/pulumi/pulumi/issues/2522, or if that doesn't get fixed then https://github.com/pulumi/pulumi/issues/3395.

**Closed by Frassle** 2022-11-11 10:07 UTC
Labels: kind/enhancement, resolution/duplicate
