### ISSUE TITLE
pulumi 3.32 upgrade (from 3.31) breaks deployment 

### ISSUE THREAD

**Issue by joeypunzel** [pulumi/pulumi#9546] opened 2022-05-05 00:39 UTC
### What happened?

using the latest pulumi version (self hosted), after upgrade from 3.31 to 3.32 our deployments failed - error below. have always kept PULUMI_CONFIG_PASSPHRASE env var as null and do not use PULUMI_CONFIG_PASSPHRASE_FILE. 

to continue keeping our deployments running reverted back to 3.31. any idea what I can do with my current stack to get past this issue and upgrade to 3.32? 

```
Successfully initialized stack
Installing plugins...
CommandError: code: 255
 stdout: 
 stderr: error: getting secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
```

### Steps to reproduce

using pulumi/setup-pulumi@v2 in github actions to generate deployment. if not specified this will use the latest version, in this case 3.32. our deployment failed after this upgrade due to the error pasted above but worked prior to this upgrade

### Expected Behavior

Honestly it's difficult finding release notes for 3.32 so it is not clear what changes in this release are causing this issue . Happy to modify our settings on the current stack to get past this issue and upgrade to 3.32. 

### Actual Behavior

Upon upgrade to 3.32, receive deployment failure with error " stderr: error: getting secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables"

### Versions used

3.31 (working) vs 3.32 (not working)

**Comment by Frassle** [comment] 2022-05-05 04:04
> PULUMI_CONFIG_PASSPHRASE env var as null

Do you mean the env var is set but is "" (an env car can't actually be null), if so this is a duplicate of https://github.com/pulumi/pulumi/issues/9541

**Comment by mikhailshilkov** [comment] 2022-05-05 08:13
Closing as dupe of https://github.com/pulumi/pulumi/issues/9541 - let me know if it's not

**Closed by mikhailshilkov** 2022-05-05 08:13 UTC
Labels: kind/bug, resolution/duplicate

**Comment by joeypunzel** [comment] 2022-05-05 11:28
thanks, confirmed it is the same issue so I will track that one
