### ISSUE TITLE
Bug within pulumi CLI

### ISSUE THREAD

**Issue by mirkoruzic** [pulumi/pulumi#14148] opened 2023-10-10 09:33 UTC
### What happened?

On Pulumi cloud we are trying to run Pulumi Refresh, Pulumi Preview and Pulumi Update. We have pulumi compiler error on any pulumi cli command.

The error is pasted bellow and docker image that is using for Pulumi. 

 Preparing environment 
 Pulling container image "pulumi/pulumi:3.88.0" 
 3.88.0: Pulling from pulumi/pulumi 
 Digest: sha256:f9437719a6a2929ad5c28de28fdddff6cb7f90f8690dec02d385b29b05d805e9 
 Status: Image is up to date for pulumi/pulumi:3.88.0 
 Starting container 

### Example

 $ /pulumi-deploy-executor pulumi refresh --stackIdentity="application/staging" --workDir="/deployment/application"

Error: Refresh failed: ================================================================================ 
 The Pulumi CLI encountered a fatal error. This is a bug! 
 We would appreciate a report: https://github.com/pulumi/pulumi/issues/ 
 Please provide all of the below text in your report. 
 ================================================================================ 
 Pulumi Version:   v3.88.0 
 Go Version:       go1.21.1 
 Go Compiler:      gc 
 Architecture:     amd64 
 Operating System: linux 
 Panic:            fatal: A failure has occurred: unexpected wire type <nil> 
 goroutine 1 [running]: 
 runtime/debug.Stack() 
 	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e 
 main.panicHandler(0xc001fbff07) 

### Output of `pulumi about`

Error: Refresh failed: ================================================================================ 
 The Pulumi CLI encountered a fatal error. This is a bug! 
 We would appreciate a report: https://github.com/pulumi/pulumi/issues/ 
 Please provide all of the below text in your report. 
 ================================================================================ 
 Pulumi Version:   v3.88.0 
 Go Version:       go1.21.1 
 Go Compiler:      gc 
 Architecture:     amd64 
 Operating System: linux 
 Panic:            fatal: A failure has occurred: unexpected wire type <nil> 
 goroutine 1 [running]: 
 runtime/debug.Stack() 
 	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e 
 main.panicHandler(0xc001fbff07) 
 	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:35 +0x45 
 panic({0x251a320?, 0xc001e17060?}) 
 	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f 
 gopkg.in/yaml%2ev3.handleErr(0xc001fbea78) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x6d 
 panic({0x251a320?, 0xc001e17060?}) 
 	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f 
 gopkg.in/yaml%2ev3.handleErr(0xc001fbe120) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x6d 
 panic({0x251a320?, 0xc001e17060?}) 
 	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f 
 github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23 
 github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x2ad658a?, 0xb?}, {0xc001fbd730?, 0x4cd02d?, 0x2a?}) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/fail.go:32 +0xcb 
 github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.unmarshalObject({0x0?, 0x0?}) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/object.go:492 +0x54a 
 github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.unmarshalObject({0x2626a00?, 0xc00159d770?}) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/object.go:468 +0x5b1 
 github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.unmarshalObject({0x2626a00?, 0xc00159d740?}) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/object.go:468 +0x5b1 
 github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.(*object).UnmarshalYAML(0xc001fbdbf0, 0xc001521de0) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/object.go:435 +0x5b 
 github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.(*Value).UnmarshalYAML(0xc001590ae0, 0xc001590ae0?) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/value.go:152 +0x28 
 gopkg.in/yaml%2ev3.(*decoder).callObsoleteUnmarshaler(0xc0000cf490, 0xc0015dcd20, {0x7f7f912b3860, 0xc001590ae0}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:379 +0x94 
 gopkg.in/yaml%2ev3.(*decoder).prepare(0xc001fbdd88?, 0x410565?, {0x2998d40?, 0xc001590ae0?, 0x18?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:427 +0x21e 
 gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc0000cf490, 0xc0015dcd20, {0x2998d40?, 0xc001590ae0?, 0xc001e16250?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:502 +0x2b2 
 gopkg.in/yaml%2ev3.(*decoder).mapping(0xc0000cf490, 0xc0015c1f40, {0x262c280?, 0xc00007b6d0?, 0x249a509?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:848 +0x98e 
 gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc0000cf490, 0xc0015c1f40, {0x24e3dc0?, 0xc00007b6d0?, 0x7f7fd82205b8?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:510 +0x3ea 
 gopkg.in/yaml%2ev3.(*decoder).callObsoleteUnmarshaler.func1({0x24e3dc0?, 0xc00007b6d0?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:381 +0xe5 
 github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.(*Map).UnmarshalYAML(0xc001592a50, 0xc001521da0) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/map.go:239 +0x82 
 gopkg.in/yaml%2ev3.(*decoder).callObsoleteUnmarshaler(0xc0000cf490, 0xc0015c1f40, {0x7f7f912b3820, 0xc001592a50}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:379 +0x94 
 gopkg.in/yaml%2ev3.(*decoder).prepare(0x251a320?, 0xc0015c1ea0?, {0x29251e0?, 0xc001592a50?, 0x251a320?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:427 +0x21e 
 gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc0000cf490, 0xc0015c1f40, {0x29251e0?, 0xc001592a50?, 0x9f980f?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:502 +0x2b2 
 gopkg.in/yaml%2ev3.(*decoder).mappingStruct(0xc0000cf490, 0xc0015c1e00, {0x2952ae0?, 0xc001592a20?, 0x40dc5f?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:935 +0xf74 
 gopkg.in/yaml%2ev3.(*decoder).mapping(0xc0000cf490, 0xc0015c1e00, {0x2952ae0?, 0xc001592a20?, 0x0?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:786 +0xa5 
 gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc0000cf490, 0xc0015c1e00, {0x2952ae0?, 0xc001592a20?, 0x9fa8a5?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:510 +0x3ea 
 gopkg.in/yaml%2ev3.(*decoder).document(...) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:527 
 gopkg.in/yaml%2ev3.(*decoder).unmarshal(0xc0000cf490, 0xc0015c1d60, {0x2952ae0?, 0xc001592a20?, 0x0?}) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:498 +0x28a 
 gopkg.in/yaml%2ev3.unmarshal({0xc0015da000, 0x877, 0x1000}, {0x26f92a0, 0xc001592a20}, 0x58?) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:167 +0x3b1 
 gopkg.in/yaml%2ev3.Unmarshal(...) 
 	/home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:89 
 github.com/pulumi/pulumi/sdk/v3/go/common/encoding.(*yamlMarshaler).Unmarshal(0xc001ff82c0?, {0xc0015da000?, 0xc00159ce70?, 0x47eff60?}, {0x26f92a0?, 0xc001592a20?}) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/encoding/marshal.go:113 +0x39 
 github.com/pulumi/pulumi/sdk/v3/go/common/workspace.LoadProjectStack(0xc001fcf210?, {0xc00158e600, 0x2b}) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/loaders.go:192 +0x1f9 
 github.com/pulumi/pulumi/sdk/v3/go/common/workspace.DetectProjectStack({0xc001fcf210?, 0x0?}) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/workspace/paths.go:162 +0x30 
 main.loadProjectStack(0x0?, {0x329b0e8?, 0xc001fea5b0?}) 
 	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/config.go:738 +0x3c 
 main.getStackConfigurationWithFallback({0x32830d0, 0x4874ea0}, {0x329b0e8, 0xc001fea5b0}, 0x32830d0?, {0x0, 0x0}, 0x0) 
 	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/config.go:1113 +0xa5 
 main.getStackConfiguration(...) 
 	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/config.go:1024 
 main.newRefreshCmd.func1(0x0?, {0xc001ee1f10, 0x0, 0x0?}) 
 	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:177 +0x889 
 main.newRefreshCmd.RunResultFunc.func2(0xc001f0ec00?, {0xc001ee1f10, 0x0, 0x7}) 
 	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x38 
 github.com/spf13/cobra.(*Command).execute(0xc001f10900, {0xc001ee1ea0, 0x7, 0x7}) 
 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863 
 github.com/spf13/cobra.(*Command).ExecuteC(0xc001cac900) 
 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 
 github.com/spf13/cobra.(*Command).Execute(...) 
 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 
 main.main() 
 	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:56 +0x58 
  

  

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment] 2023-10-10 11:51
Thanks for the report!  This looks like a duplicate of https://github.com/pulumi/pulumi/issues/14146, so I'm closing this out, so we just have one issue to work with.

**Closed by tgummerer** 2023-10-10 11:51 UTC
Labels: kind/bug, needs-triage, resolution/duplicate
