### ISSUE TITLE
[Go Program Gen] Long multi-line strings are not readable

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#4898] opened 2020-06-25 19:33 UTC
Since we render it all on one line with newline characters, it's kind of a mess. We could at a minimum use better formatting here to put each argument to sprintf on its own line. This is not an error, more of a usability concern. 

Example:

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v2/go/aws"
	"github.com/pulumi/pulumi-aws/sdk/v2/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		main, err := aws.GetBillingServiceAccount(ctx, nil, nil)
		if err != nil {
			return err
		}
		_, err = s3.NewBucket(ctx, "billingLogs", &s3.BucketArgs{
			Acl:    pulumi.String("private"),
			Policy: pulumi.String(fmt.Sprintf("%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v%v", "{\n", "  \"Id\": \"Policy\",\n", "  \"Version\": \"2012-10-17\",\n", "  \"Statement\": [\n", "    {\n", "      \"Action\": [\n", "        \"s3:GetBucketAcl\", \"s3:GetBucketPolicy\"\n", "      ],\n", "      \"Effect\": \"Allow\",\n", "      \"Resource\": \"arn:aws:s3:::my-billing-tf-test-bucket\",\n", "      \"Principal\": {\n", "        \"AWS\": [\n", "          \"", main.Arn, "\"\n", "        ]\n", "      }\n", "    },\n", "    {\n", "      \"Action\": [\n", "        \"s3:PutObject\"\n", "      ],\n", "      \"Effect\": \"Allow\",\n", "      \"Resource\": \"arn:aws:s3:::my-billing-tf-test-bucket/*\",\n", "      \"Principal\": {\n", "        \"AWS\": [\n", "          \"", main.Arn, "\"\n", "        ]\n", "      }\n", "    }\n", "  ]\n", "}\n", "\n")),
		})
		if err != nil {
			return err
		}
		return nil
	})
}

```

**Comment by mikhailshilkov** [comment] 2022-06-13 14:40
@iwahbe Has this been fixed by #9726?

**Comment by iwahbe** [comment] 2022-06-13 20:55
@mikhailshilkov Yes. I'm going to close this as a duplicate of https://github.com/pulumi/pulumi/issues/9725.

**Closed by iwahbe** 2022-06-13 20:55 UTC
Labels: kind/enhancement, language/go, area/codegen, resolution/duplicate
