### ISSUE TITLE
ComponentResource constructor should no longer take 'props'.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2635] opened 2019-04-09 21:56 UTC
We already drop this value on the ground because we do not think it makes sense for a Component to have inputs.  We never removed the value though because of hte sxs break this could cause.  

However, now that we have a model for making breaking changes at the `@pulumi/pulumi` level, we can remove this as long as we rev our package version and update all downstream clients.

**Comment by joeduffy** [comment] 2021-07-10 16:01
I'm not following why we wouldn't preserve input properties for components, for purposes of policy as code, displaying in the service UX, and so on. Should this be closed as "by design"?

**Closed** 2022-03-23 13:03 UTC
Labels: kind/enhancement, resolution/by-design
