### ISSUE TITLE
Add version changelog to the github release

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi#6189] opened 2021-01-25 09:47 UTC
Currently, the [github release page](https://github.com/pulumi/pulumi/releases) doesn't include the changelog.

It's possible to include it, which have severals benefits:
- Get the changelog directly on the release page
- People who subscribed to the release notification will get an email with the changelog (currently, we need to clic on the release link, and then navigate manually to the chagelog file)

You can see what is looks on [my project here](https://github.com/boillodmanuel/markdown-link-check/releases)
![image](https://user-images.githubusercontent.com/621455/105689001-891ac500-5efa-11eb-991c-9868667c93f4.png)
And a link to my [github action](https://github.com/boillodmanuel/markdown-link-check/blob/master/.github/workflows/publish-tag.yml#L48). Note that the extract script is pretty “weak” but it’s working for me, and it's a good starting point ;)

**Comment by leezen** [comment] 2021-02-04 05:08
Dupe of https://github.com/pulumi/pulumi/issues/5063

**Closed by leezen** 2021-02-04 05:08 UTC
Labels: resolution/duplicate
