### ISSUE TITLE
Python program can hang when creating a helm `Chart` component with explicit provider

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15462] opened 2024-02-16 23:19 UTC
Here's a reduced repro based on a real customer program. I haven't had a chance to reduce it further to a more minimal repro.

```sh
python -m venv venv
source venv/bin/activate
python -m pip install pulumi>=3.5.1,<4.0.0
python -m pip install pulumi-kubernetes>=3.4.0,<5.0.0
python -m pip install pulumi-azure-native==v2.27.0
python -m pip install pytest
```

test_infra.py:

```python
import base64
import time

import pulumi
import pulumi_azure_native as azure_native
import pulumi_kubernetes as k8s


class MyMocks(pulumi.runtime.Mocks):
    def new_resource(self, args: pulumi.runtime.MockResourceArgs):
        outputs = args.inputs
        if args.typ == "azure-native:resources:ResourceGroup":
            outputs = {
                **args.inputs,
                "name": "azure-preview-foobar",
            }
        return [args.name + '_id', outputs]

    def call(self, args: pulumi.runtime.MockCallArgs):
        print(f"MyMocks: {args.token} called")

        if args.token == "kubernetes:helm:template":
            return {
                "result": [
                    {
                        "apiVersion": "v1",
                        "kind": "Namespace",
                        "metadata": {
                            "name": "vault"
                        }
                    },
                ]
            }
        if args.token == "azure-native:containerservice:listManagedClusterUserCredentials":
            time.sleep(1)

            return {
                "kubeconfigs":[{
                    "name": "clusterUser",
                    "value": base64.b64encode("some kubeconfig".encode()).decode(),
                }]
            }
        return {}


pulumi.runtime.set_mocks(MyMocks())


resource_group = azure_native.resources.ResourceGroup("rg")

def get_kubeconfig(name):
    # Note: In the real program, another input was used for the resource_name
    # but this is sufficient for the repro.
    creds = azure_native.containerservice.list_managed_cluster_user_credentials(
        resource_group_name=name,
        resource_name=name,
    )
    return base64.b64decode(list(creds.kubeconfigs)[0].value).decode()

kubeconfig = resource_group.name.apply(get_kubeconfig)

k8s_provider = k8s.Provider("k8s-provider", kubeconfig=kubeconfig)


vnet = azure_native.network.VirtualNetwork("vnet",
    resource_group_name=resource_group.name,
)

helm_values = {
    "fake": {
        "vnet": vnet.id,
        "something": "else",
        # "something": k8s_provider.urn.apply(lambda urn: "else"),
    },
}

chart = k8s.helm.v3.Chart("chart",
    k8s.helm.v3.LocalChartOpts(path="", values=helm_values),
    pulumi.ResourceOptions(provider=k8s_provider),
)


@pulumi.runtime.test
def test_server_tags():
    def check_urn(urn):
        assert urn

    return chart.urn.apply(check_urn)
```

Run the following and notice it will hang.

```
pytest --disable-pytest-warnings -s --log-cli-level=DEBUG
```

When the mock implementation of `azure-native:containerservice:listManagedClusterUserCredentials` does not have `time.sleep(1)`, it does not hang.

With the `time.sleep(1)`, the hang can be avoided by passing the value of `"something"` in `helm_values` as `k8s_provider.urn.apply(lambda urn: "else")` to wait on the `k8s_provider`.

One possible workaround in the Kubernetes SDK: if a provider is specified for the chart, include it in the `apply` on the `Chart`’s inputs before invoking `kubernetes:helm:template` to avoid the potential hang if the inputs also depend on things that the provider depends on.

**Comment by MitchellGerdisch** [comment] 2024-02-25 15:12
Until the issue is addressed in Pulumi, a workaround one can use is to add an apply() on the k8s provider as part of the chart declaration. The apply() isn't used to return a value to be consumed but to simply force the chart resource to wait until the provider is ready.

E.g. 
```
nginx_ingress = Chart(
    "nginx-ingress",
    ChartOpts(
        chart=k8s_provider.urn.apply(lambda urn: "nginx-ingress"),
        version="1.24.4",
        namespace="test-namespace",
        fetch_opts=FetchOpts(
            repo="https://charts.helm.sh/stable",
        ),
    ),
)
```

**Closed** 2024-03-07 23:43 UTC
Labels: kind/bug, area/sdks, p1, language/python
