### ISSUE TITLE
Optionally specify resource suffix

### ISSUE THREAD

**Issue by ferguscan** [pulumi/pulumi#15491] opened 2024-02-22 02:52 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

During local development, I use Pulumi to deploy resources to [localstack](https://www.localstack.cloud/).  I want these resources to have predictable names, so I can easily interact with them via test scripts, etc.

On the other hand, when I deploy my infrastructure to AWS, I want my resources to have unique names (Pulumi's default behaviour).  For this reason, I don't want to manually specify a `name` for each of my resources.

Instead, I would like to be able to (optionally) control the suffix that Pulumi applies to resource names.  For my local deployment, i would specify a known, predictable suffix (e.g. `dev`).  When deploying to AWS, I would not specify a suffix at all (letting Pulumi choose a random suffix, as per usual).

### Affected area/feature

Unknown

**Comment by Frassle** [comment] 2024-02-22 07:58
Duplicate of https://github.com/pulumi/pulumi/issues/1518. Long standing issue but due to the distributed and non-systemic way names are handled today it's a tricky one to fix.

**Closed by Frassle** 2024-02-22 07:58 UTC
Labels: kind/enhancement, resolution/duplicate

**Comment by wouter-b** [comment] 2024-02-23 12:54
Well four years later, the first issue I encountered when starting with pulumi today ;-)
