### ISSUE TITLE
Newly created TypeScript program fails to compile

### ISSUE THREAD

**Issue by robwruck** [pulumi/pulumi#13838] opened 2023-08-31 08:38 UTC
### What happened?

A newly created Pulumi TypeScript project fails to compile, probably because pulumi still depends on TypeScript 3.x while @types/node now depends on TypeScript 4:

```
node_modules/@types/node/ts4.8/buffer.d.ts:340:48 - error TS2694: Namespace 'global.NodeJS' has no exported member 'ArrayBufferView'.

340             byteLength(string: string | NodeJS.ArrayBufferView | ArrayBuffer | SharedArrayBuffer, encoding?: BufferEncoding): number;
                                                   ~~~~~~~~~~~~~~~


Found 1 error.
```

### Expected Behavior

`npx tsc` compiles the project.

### Steps to reproduce

```
docker run --rm -it --entrypoint /bin/bash pulumi/pulumi-nodejs:3.79.0 -c \
"pulumi new -g aws-typescript -n test -d test && npm install && npx tsc"
```

### Output of `pulumi about`

CLI          
Version      3.79.0
Go Version   go1.21.0
Go Compiler  gc

Host     
OS       debian
Version  11.7
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment] 2023-08-31 19:17
Hey. Thanks for filing this and having a very easy to use repro. I believe this is a duplicate of https://github.com/pulumi/pulumi/issues/12117 as `npx tsc` is selecting typescript 4.8 when I run it.

Let me know if you have other questions.

**Closed by dixler** 2023-08-31 19:17 UTC
Labels: kind/bug, area/sdks, language/javascript, resolution/duplicate
