### ISSUE TITLE
sdk/workspace: DownloadToFile multiplies retries

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#12456] opened 2023-03-18 01:07 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`workspace.DownloadToFile` attempts to download with retries:

https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L1130-L1132
However,
`DownloadToFile` [calls](https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L1089) [PluginSpec.Download](https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L910)
which calls [source.Download](https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L936) with [getHTTPResponse](https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L955)
which also downloads with retries:

https://github.com/pulumi/pulumi/blob/638c35aa4503615f585a8939694e466af06a7683/sdk/go/common/workspace/plugins.go#L955-L961

This results in a lot more retries than we want.

Discovered while reviewing #12441

**Comment by RobbieMcKinstry** [comment] 2023-03-20 19:24
Nice find!
I'm marking this as a bug instead of an enhancement since it's unlikely retry multiplication is the intended behavior.

**Closed** 2023-03-28 18:17 UTC
Labels: kind/bug, impact/performance, area/plugins
