### ISSUE TITLE
Retry provider operations

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#16141] opened 2024-05-07 15:08 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Allow a resource operation to be retried if it initially fails. Occasionally a resource creation, update or delete can fail with transient errors (which resolve themselves after a short amount of time). Retry mechanisms are sometimes implemented by specific providers, but we could also make this behaviour available to all resource via a generic resource option.

Examples of reasons to need retry:
- Service unavailable during brief maintanance period.
- Internal replication delays causing one service to not see another newly created resource in a different service.

**Comment by justinvp** [comment] 2024-05-08 08:27
Closing as dupe of https://github.com/pulumi/pulumi/issues/7932

**Closed by justinvp** 2024-05-08 08:27 UTC
Labels: kind/enhancement, resolution/duplicate, area/engine, area/resource-options
