### ISSUE TITLE
`pulumi convert` warns about `required` field on config

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#9890] opened 2022-06-18 18:45 UTC
If I declare a config variable that is required, as with this program:

```yaml
name: yamyam
runtime: yaml
configuration:
  foo:
    type: String
    required: true
```

And I run `pulumi convert`, e.g. say `pulumi convert --language python`, I get a warning:

```
Warning: Field 'required' does not exist on Object 'configuration.foo'

  on Pulumi.yaml line 6:
   6:     required: true

Existing fields are: 'secret', 'type', 'default'
```

That seems like a bug, especially as the metadata seemed to flow through since the Python program uses `config.require`.

**Comment by mikhailshilkov** [comment] 2022-06-28 12:56
Hey @joeduffy thank you for reporting this. I believe `required` is not a valid property, as it's not described in the [spec](https://github.com/pulumi/pulumi-yaml#configuration).

> especially as the metadata seemed to flow through since the Python program uses config.require

This is because there's no `default` is specified. If you set it like 

```
configuration:
  foo:
    type: String
    default: "123"
```

it will generate 

```
const foo = config.get("foo") || "123";
```

Should we close it as by design? cc @AaronFriel

**Closed** 2022-06-29 15:34 UTC
Labels: kind/bug, area/codegen, resolution/by-design, area/config
