### ISSUE TITLE
Support other CI systems from Pulumi

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1943] opened 2018-09-14 14:43 UTC
Probe local environment variables, and set the update's metadata bag to indicate different CI systems as appropriate. See:
https://github.com/pulumi/pulumi/blob/792c316e5e563b500173792d9ef93d6a81ae85a0/cmd/util.go#L449

- [x] Travis
- [x] GitLab
- [ ] Jenkins
- [ ] TeamCity
- [x] Azure DevOps
- [x] Circle CI
- [ ] Atlassian Bamboo
- [ ] Others...

**Comment by joeduffy** [comment] 2018-10-02 23:10
GitLab added in https://github.com/pulumi/pulumi/commit/5ed33c691509571c03cbf44f22c6f05391f238ba.

**Comment by nesl247** [comment] 2019-04-05 22:35
For reference, https://github.com/pulumi/pulumi/blob/5ed33c691509571c03cbf44f22c6f05391f238ba/pkg/util/ciutil/systems.go is the latest. Several of the systems in the original post are now supported including Jenkins.

With that in mind, https://pulumi.io/reference/cd-github.html#ci-integration needs to be updated.

**Comment by praneetloke** [comment] 2019-05-31 00:41
@chrsmith I think we should close this issue. It looks like a duplicate of #2106. I have merged the info form this issue in 2106.

**Closed** 2019-05-31 02:45 UTC
