### ISSUE TITLE
Pulumi doesn't sanitize URNs

### ISSUE THREAD

**Issue by NinoFloris** [pulumi/pulumi#3219] opened 2019-09-12 03:30 UTC
Pulumi doesn't sanitize URNs
Somehow I got an encoded backspace in my urn leading to the following name in stack export
`
 "urn": "urn:pulumi:dev::gcp-services::gcp:sql/sslCert:SslCert::name-a3e1c8c-services-\u0008clientcert",
`
This obviously breaks tooling that informs you of the actual URN and trying to delete it via state delete would be futile as well.

**Comment by lukehoban** [comment] 2019-09-12 05:10
> Somehow I got an encoded backspace in my urn 

Do you have any idea how?  This looks like it came from user code - but unless you exploratory inserted this character in the name, I’m not sure how Pulumi would have ended up with it there. 

That said, we should definitely constrain resource names to a reasonable grammar.

**Comment by Frassle** [comment] 2022-03-17 11:23
Closing as duplicate of https://github.com/pulumi/pulumi/issues/8949

**Closed by Frassle** 2022-03-17 11:23 UTC
Labels: resolution/duplicate
