### ISSUE TITLE
Resource lost during deleteBeforeReplace error

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#16629] opened 2024-07-11 08:59 UTC
### What happened?

When performing a replacement, where we're using `deleteBeforeReplace` and the creation fails, then we revert the change, then the resource is not re-created.

1. Deploy code - succeeds
2. Remove the `WebApp` `kind` property triggers a replacement, but the create will fail after the deletion has already happened.
3. Revert the code change to put the `WebApp` `kind` property back.
4. Running `pulumi up` shows "Resources: 4 unchanged" and does not re-create the deleted resource.

I would expect the last step should re-create the resource deleted ahead of the replacement.

### Example

```typescript
import * as web from "@pulumi/azure-native/web";
import * as resources from "@pulumi/azure-native/resources";

const resourceGroup = new resources.ResourceGroup("rg");

const functionAppServicePlan = new web.AppServicePlan(`asp-func`, {
  resourceGroupName: resourceGroup.name,
  kind: "functionapp",
  reserved: true,
  sku: {
    name: "Y1",
    tier: "Dynamic",
  },
});

// Create empty initial webapps
const functionsApp = new web.WebApp(
  `as-function`,
  {
    resourceGroupName: resourceGroup.name,
    serverFarmId: functionAppServicePlan.id,
    kind: "functionapp,linux", // Remove this property and redeploy
    siteConfig: {
      linuxFxVersion: "DOTNET-ISOLATED|8.0",
      alwaysOn: false,
    },
  },
  {
    deleteBeforeReplace: true,
  }
);
```

### Output of `pulumi about`

```
CLI          
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  aws           6.28.2
resource  aws-native    0.100.0
resource  azure-native  2.47.0
language  nodejs        unknown
resource  random        4.16.0

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/Users/dan/.nodenv/shims/node' version='v18.14.0'

Current Stack: daniel-pulumi-corp/scratch/dev

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:dev::scratch::pulumi:pulumi:Stack::scratch-dev
pulumi:providers:azure-native         urn:pulumi:dev::scratch::pulumi:providers:azure-native::default_2_47_0
azure-native:resources:ResourceGroup  urn:pulumi:dev::scratch::azure-native:resources:ResourceGroup::rg
azure-native:web:AppServicePlan       urn:pulumi:dev::scratch::azure-native:web:AppServicePlan::asp-func
azure-native:web:WebApp               urn:pulumi:dev::scratch::azure-native:web:WebApp::as-function


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/daniel-pulumi-corp
User           daniel-pulumi-corp
Organizations  daniel-pulumi-corp, demo, pulumi
Token type     personal

Dependencies:
NAME                          VERSION
@aws-sdk/client-cloudcontrol  3.540.0
@pulumi/aws                   6.28.2
@pulumi/aws-native            0.100.0
@pulumi/azure-native          2.47.0
@pulumi/random                4.16.0
@smithy/middleware-retry      2.3.0
typescript                    4.9.5
@types/node                   14.18.63
ts-node                       10.9.2

Pulumi locates its logs in /var/folders/40/n23_nmpj47n3fxxpqls5h9tw0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment] 2024-07-11 11:07
Looks like this might actually be a duplicate of:
- https://github.com/pulumi/pulumi/issues/16179
- https://github.com/pulumi/pulumi/issues/8354

**Comment by justinvp** [comment] 2024-07-15 00:33
Going to close this as a dupe of #16179 and see if we can pick that up soon.

**Closed by justinvp** 2024-07-15 00:33 UTC
Labels: kind/bug, resolution/duplicate
