### ISSUE TITLE
deduplicate runtime error messages

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9237] opened 2022-03-17 13:39 UTC
## overview
we sandwhich error messages with..

```
error: Program failed with an unhandled exception:
```

and...

```
error: an unhandled error occurred: Program exited with a non-zero exit code: 1
```

are these useful to users? if not, should we consider removing them to reduce the wall of error text that many users hit?

**Comment by susanev** [comment] 2022-04-08 16:53
Notes from Pat:
- `error: an unhandled error occurred: Program exited with a non-zero exit code: 1` is maybe useful if there was no other output at all, otherwise this is not helpful or useful to folks

**Comment by dixler** [comment] 2022-07-20 14:56
sample error message in c#

![Image](https://user-images.githubusercontent.com/25750473/180013137-c3e2791b-65fe-4d30-a2b6-99e3ef6107ee.png)

**Comment by dixler** [comment] 2022-07-20 19:23
notes:
- charp (1 line of error output)
  - [ ] continues to execute despite hitting an exception
- go (3 lines of error output)
  - [ ] breaks progress display
- javascript (1 line of error output)
  - [ ] breaks progress display
- python (3 lines of error output)
  - [ ] emits a traceback
- java (
  - [ ] emits build info logs
- yaml (3 error logs)
  - [ ] duplicated error messages

**Comment by dixler** [comment] 2022-07-20 21:03
Component Provider
https://github.com/pulumi/pulumi-component-provider-py-boilerplate

error dedup

[![asciicast](https://asciinema.org/a/qnJyz7FiaUoeSHXiysKjgQH4l.svg)](https://asciinema.org/a/qnJyz7FiaUoeSHXiysKjgQH4l)

**Comment by mikhailshilkov** [comment] 2022-07-21 10:33
> C#: continues to execute despite hitting an exception

Do you have a link to your program? I get the following and the CLI stops:

```
Type                 Name          Plan     Info
     pulumi:pulumi:Stack  azure-cs-dev           1 error
 
Diagnostics:
  pulumi:pulumi:Stack (azure-cs-dev):
    error: Running program '/play/azure-cs/bin/Debug/netcoreapp3.1/Infra.dll' failed with an unhandled exception:
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       at object RuntimeTypeHandle.CreateInstance(RuntimeType type, bool publicOnly, bool wrapExceptions, ref bool canBeCached, ref RuntimeMethodHandleInternal ctor, ref bool hasNoDefaultCtor)
       at object RuntimeType.CreateInstanceDefaultCtorSlow(bool publicOnly, bool wrapExceptions, bool fillCache)
       at object RuntimeType.CreateInstanceDefaultCtor(bool publicOnly, bool skipCheckThis, bool fillCache, bool wrapExceptions)
       at T Activator.CreateInstance<T>()
       at Task<int> Pulumi.Deployment+Runner.Pulumi.IRunner.RunAsync<TStack>(IServiceProvider serviceProvider)+() => { }
       at Task<int> Pulumi.Deployment+Runner.RunAsync<TStack>(Func<TStack> stackFactory) ---> System.Exception: boo
       at new MyStack() in /play/azure-cs/Program.cs:line 26
       --- End of inner exception stack trace ---
```

**Comment by mikhailshilkov** [comment] 2022-07-21 10:36
Ah, I reproduced it with

```
using System;
using System.Threading.Tasks;
using Pulumi;

await Deployment.RunAsync(() =>
{
    throw new Exception("boo");
    return Task.CompletedTask;
});
```

**Comment by t0yv0** [comment] 2022-07-21 16:59
Chatting with @dixler about this.

The first approach to fix was considering embedding more info in type of event (error event) to see where it's coming from. We should consider a more tactical "quick fix" by recognizing and omitting error message strings that show up here that are not super helpful instead - less rearchitecting, quicker to complete...

The other issue that shows up here is that there is duplication of error messages at the top of display. Like in golang#2 - every resource displays the same message in it. It could be screwed up rendering, or it could be something else. I worry that it might be root-caused by the SDKs sending the same exception multiple times over the engine log channel when this exception is duplicated by a failing graph Output promises: if you find it's true please let's take that to separate issues 🙏

**Comment by t0yv0** [comment] 2022-07-22 16:58
@dixler do you have a repro (program) for the JavaScript output above?

**Comment by t0yv0** [comment] 2022-07-22 18:06
It'd be lovely if we could maybe close this one issue in favor of the specific ones. I think these cover it - but need help making sure:

  https://github.com/pulumi/pulumi/issues/10222 py
  https://github.com/pulumi/pulumi/issues/10226 yaml
  https://github.com/pulumi/pulumi/issues/10227 go
  https://github.com/pulumi/pulumi/issues/10202 csharp

  https://github.com/pulumi/pulumi/issues/10224 (bonus related)


I'll write one for Java to go in pulumi-java.

The JavaScript one looks like the remaining one - that need a repro.

**Comment by t0yv0** [comment] 2022-07-22 19:19
https://github.com/pulumi/pulumi-java/issues/763 java

**Comment by mikhailshilkov** [comment] 2022-07-25 13:42
Agreed to close in favor of more specific issues

**Closed by mikhailshilkov** 2022-07-25 13:42 UTC
Labels: area/cli, kind/enhancement, impact/usability, resolution/duplicate
