### ISSUE TITLE
Cannot read properties of undefined (reading 'invoke') in aws-apigateway

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#18057] opened 2024-12-16 22:17 UTC
### What happened?

When upgrading `    "@pulumi/pulumi": "3.142.0", ` to `    "@pulumi/pulumi": "3.143.0", ` in aws-apigateway, tests such as `examples/simple` start failing on `pulumi preview` with:

```
    error: aws-apigateway:index:RestAPI resource 'api' has a problem: Cannot read properties of undefined (reading 'invoke')

```

I've noticed on https://github.com/pulumi/pulumi-aws-apigateway/pull/177 but was able to narrow it down to just that one dependency, flipping it to 3.143.0 reproduces and 3.142.0 works fine.

The error is under Construct :

```
{
  "method": "/pulumirpc.ResourceProvider/Construct",
  "request": {
    "project": "simple",
    "stack": "anton-test-dec-16",
    "dryRun": true,
    "parallel": 48,
    "monitorEndpoint": "127.0.0.1:62117",
    "type": "aws-apigateway:index:RestAPI",
    "name": "api",
    "parent": "urn:pulumi:anton-test-dec-16::simple::pulumi:pulumi:Stack::simple-anton-test-dec-16",
    "inputs": {
      "binaryMediaTypes": [
        "application/json"
      ],
      "description": "test one two three",
      "routes": [
        {
          "eventHandler": {
            "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
            "id": "",
            "urn": "urn:pulumi:anton-test-dec-16::simple::aws:lambda/function:Function::f"
          },
          "method": "GET",
          "path": "/"
        }
      ]
    },
    "inputDependencies": {
      "binaryMediaTypes": {},
      "description": {},
      "routes": {
        "urns": [
          "urn:pulumi:anton-test-dec-16::simple::aws:lambda/function:Function::f"
        ]
      }
    },
    "dependencies": [
      "urn:pulumi:anton-test-dec-16::simple::aws:lambda/function:Function::f"
    ],
    "customTimeouts": {},
    "acceptsOutputValues": true
  },
  "errors": [
    "rpc error: code = Unknown desc = Cannot read properties of undefined (reading 'invoke')"
  ],
  "metadata": {
    "kind": "resource",
    "mode": "client",
    "name": "aws-apigateway"
  }
}
```

I've not yet debugged further.

Possibly tangentially related:

https://github.com/pulumi/pulumi/issues/13505
https://github.com/pulumi/pulumi/issues/17074

### Example

See https://github.com/pulumi/pulumi-aws-apigateway/pull/177

### Output of `pulumi about`

```
CLI          
Version      3.141.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME            VERSION
resource  aws             6.65.0
resource  aws-apigateway  2.6.1
language  nodejs          unknown

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in nodejs: executable='/run/current-system/sw/bin/node' version='v20.18.0'

Current Stack: anton-pulumi-corp/simple/anton-test-dec-16

Found no resources associated with anton-test-dec-16

Found no pending operations associated with anton-test-dec-16

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, demo, pulumi
Token type     personal

Dependencies:
NAME                    VERSION
@pulumi/aws-apigateway  2.6.1
@pulumi/aws             6.65.0
@pulumi/pulumi          3.143.0
@types/node             18.19.68

Pulumi locates its logs in /var/folders/gd/3ncjb1lj5ljgk8xl5ssn_gvc0000gn/T/com.apple.shortcuts.mac-helper// by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2024-12-17 15:11
@corymhall if you have seen any instances of this please cross-link.

**Comment by justinvp** [comment] 2024-12-18 00:30
This can happen when there are multiple copies of `@pulumi/pulumi`, e.g. a top-level `node_modules/@pulumi/pulumi` and another one like `node_modules/@pulumi/aws/node_modules/@pulumi/pulumi`.

Indeed that appears to be the case from looking at the `yarn.lock` in from https://github.com/pulumi/pulumi-aws-apigateway/pull/177

https://github.com/pulumi/pulumi-aws-apigateway/blob/6a28cbd710334bd2e49f1e96c22a323332b2ad46/provider/cmd/pulumi-resource-aws-apigateway/yarn.lock#L569

https://github.com/pulumi/pulumi-aws-apigateway/blob/6a28cbd710334bd2e49f1e96c22a323332b2ad46/provider/cmd/pulumi-resource-aws-apigateway/yarn.lock#L574

https://github.com/pulumi/pulumi-aws-apigateway/blob/6a28cbd710334bd2e49f1e96c22a323332b2ad46/provider/cmd/pulumi-resource-aws-apigateway/yarn.lock#L610

```
"@pulumi/aws@6.65.0":
  version "6.65.0"
  resolved "https://registry.yarnpkg.com/@pulumi/aws/-/aws-6.65.0.tgz#d61ea68d0ae5e7908f939cd92d29005efbbf3f5d"
  integrity sha512-KAxyH5QJnmyr51Rz9nPWuakaAA6ssWJNaiMvHINTgm29zasfpegrt3C99Q93r/s/g7ehlQ8SUKuunAvLW1Aoww==
  dependencies:
    "@pulumi/pulumi" "^3.136.0" <----------------------------------------
    builtin-modules "3.0.0"
    mime "^2.0.0"
    resolve "^1.7.1"

"@pulumi/pulumi@3.143.0": <----------------------------------------
  version "3.143.0"
  resolved "https://registry.yarnpkg.com/@pulumi/pulumi/-/pulumi-3.143.0.tgz#da3e5e97a598e3a2b7784c3ee3b1564e517056e5"
  integrity sha512-t3xSiq+B0FAJfELszBJYV+saTO4Po1g9jC7pCowi7UhmAhHebkixnGSUBhTCx/neCKeer4rX6hDCZ6b/1LUWfg==
  dependencies:
    ...

"@pulumi/pulumi@^3.136.0": <----------------------------------------
  version "3.142.0"
  resolved "https://registry.yarnpkg.com/@pulumi/pulumi/-/pulumi-3.142.0.tgz#dd7bb330576f170365fa711f0b5f87394b964885"
  integrity sha512-2RP4EDIDj4A980u/KThEUe5h5b0LcSaOqw9cA8Cxi3SiP+GC91zecJNbko4GOSR8kxsNd8EY327pVxt7fjTKhA==
  dependencies:
    ...
```

I think the fix is to use a version range in apigateway so it collapses on a single copy of `@pulumi/pulumi`.

We should probably close this as a dupe of https://github.com/pulumi/pulumi/issues/13505, and use https://github.com/pulumi/pulumi/issues/13505 to track:

1. Seeing if there's a way we can make `getMonitor()` work even in the face of multiple copies of `@pulumi/pulumi`
2. If that's not easy, at a minimum provide a better error message when the result of `getMonitor` is `undefined`, which can happen in cases like this, or if you try to run the program directly rather than via `pulumi up` or inline automation API.

**Comment by justinvp** [comment] 2024-12-18 00:43
Preemptively closing as a dupe of https://github.com/pulumi/pulumi/issues/13505. Happy to re-open if it's something else.

**Closed by justinvp** 2024-12-18 00:43 UTC
Labels: kind/bug, resolution/duplicate
