### ISSUE TITLE
Issue with Alias's when name of component is derived from another class. 

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#13324] opened 2023-06-29 20:44 UTC
### What happened?

When you derive the name of a component resource, `Alias(parent=component)` seems to be broken and you are forced to use fstring alias in python. 

Code: 
```
"""A Random Python Pulumi program"""

from pulumi import ComponentResource, ResourceOptions, export, Alias, ROOT_STACK_RESOURCE
import pulumi_random as random
from typing import List

class ProjectStackConfiguration:
    def __init__(self):
        self.long_name = "long-name"
        self.short_name = "short-name"

class Cluster(ComponentResource):
    def __init__(self, name: str, opts=None):
        stack = ProjectStackConfiguration()
        super().__init__("my:modules:A", stack.long_name, {}, opts)
        random.RandomString("a-random", length=16, opts=ResourceOptions(parent=self))

class StandardCluster(ComponentResource):
    def __init__(self, name: str, opts=None):
        stack = ProjectStackConfiguration()
        super().__init__("my:modules:B", stack.short_name, {}, opts)
        a = Cluster(
            "a",
            opts=ResourceOptions(
                # parent=self, #uncomment me to need the alias
                # aliases=[Alias(parent=ROOT_STACK_RESOURCE)] # show the alias resolves
            )
        )
        self.b: List = []
        for i in range(0,500,1):
            # first run uncomment me
            # self.b.append(random.RandomString(f"b-random-{i}", length=16, opts=ResourceOptions(
            #     parent=a, 
            # )))

            #second run, uncomment me
            self.b.append(random.RandomString(f"b-random-{i}", length=16, opts=ResourceOptions(
                parent=self, 
                aliases=[Alias(parent=a)]
            )))

b = StandardCluster("b-an-example")
#export("string", b.b)
```

### Expected Behavior

Aliases should find the existing resources. 

### Steps to reproduce

Us the code above, create the resources, then uncomment the sections.

### Output of `pulumi about`

 pulumi about
CLI
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown
random  4.13.2

Host
OS       ubuntu
Version  20.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2023-06-30 21:11
```python
from pulumi import ComponentResource, ResourceOptions, export, Alias, ROOT_STACK_RESOURCE, Config
import pulumi_random as random
from typing import List

config = Config()
step = config.get_int('step') or 0

class ProjectStackConfiguration:
    def __init__(self):
        self.long_name = "long-name"
        self.short_name = "short-name"

class Cluster(ComponentResource):
    def __init__(self, name: str, opts=None):
        stack = ProjectStackConfiguration()
        super().__init__("my:modules:A", stack.long_name, {}, opts)
        random.RandomString("a-random", length=16, opts=ResourceOptions(parent=self))

class StandardCluster(ComponentResource):
    def __init__(self, name: str, opts=None):
        stack = ProjectStackConfiguration()
        super().__init__("my:modules:B", stack.short_name, {}, opts)
        ropts = ResourceOptions()
        if step != 0:
            ropts = ResourceOptions(
                parent=self,
                aliases=[Alias(parent=ROOT_STACK_RESOURCE)]
            )
        a = Cluster(
            "a",
            opts=ropts
        )
        self.b: List = []
        for i in range(0,1,1):
            if step == 0:
                self.b.append(random.RandomString(f"b-random-{i}", length=16, opts=ResourceOptions(
                    parent=a,
                )))

            if step != 0:
                self.b.append(random.RandomString(f"b-random-{i}", length=16, opts=ResourceOptions(
                    parent=self,
                    aliases=[Alias(parent=a)]
                )))

StandardCluster('x')
```

```bash
#!/usr/bin/env bash

set -euo pipefail

pulumi destroy --yes
rm -rf *rpc.json

pulumi config set step 0
PULUMI_DEBUG_GRPC="$PWD/step0-rpc.json" pulumi up --yes
pulumi stack export > step0.json

pulumi config set step 1
PULUMI_DEBUG_GRPC="$PWD/step1-rpc.json" pulumi up --yes
pulumi stack export > step1.json
```

With the above I can't get b-random-{I} alias to be accepted, it keeps generating replace plans for these. This doesn't look like an issue with Python SDK but something in the engine perhaps.

The gRPC call is something like this:

```
{
  "method": "/pulumirpc.ResourceMonitor/RegisterResource",
  "request": {
    "type": "my:modules:A",
    "name": "long-name",
    "parent": "urn:pulumi:dev2::rshade-2::my:modules:B::short-name",
    "aliases": [
      {
        "spec": {
          "noParent": true
        }
      }
    ]
  },
  "response": {
    "urn": "urn:pulumi:dev2::rshade-2::my:modules:B$my:modules:A::long-name",
    "object": {}
  }
}

{
  "method": "/pulumirpc.ResourceMonitor/RegisterResource",
  "request": {
    "type": "random:index/randomString:RandomString",
    "name": "b-random-0",
    "parent": "urn:pulumi:dev2::rshade-2::my:modules:B::short-name",
    "aliases": [
      {
        "spec": {
          "parentUrn": "urn:pulumi:dev2::rshade-2::my:modules:B$my:modules:A::long-name"
        }
      }
    ]
  },
```

So this RandomString is registered with an alias to the *new* correct URN of `long-name`, which the engine correctly figures out has an alias.. The *old* URN of the parent was `urn:pulumi:dev2::rshade-2::my:modules:A::long-name` but is available in the state. It seems to me that the engine should have been able to figure this out.

**Comment by justinvp** [comment] 2023-07-01 01:17
I was also able to repro this. Looks like a bug in the engine's computed aliases.

**Comment by lukehoban** [comment] 2023-07-11 15:57
This appears to be a regression related to the transition from SDK to Engine based alias computation. Marking as P1.

**Closed** 2023-07-17 17:11 UTC
Labels: kind/bug, p1, impact/regression, customer/feedback, area/engine, customer/lighthouse
