### ISSUE TITLE
403 error when setting Azure secrets provider

### ISSUE THREAD

**Issue by Stadly** [pulumi/pulumi#16319] opened 2024-06-04 12:31 UTC
### What happened?

I get an error when trying to set Azure Key Vault as secrets provider for my stack:

```sh
error: secrets (code=Unknown): DefaultAzureCredential authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 403 connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: Det ble forsøkt en kontaktoperasjon til et nettverk som ikke kunne nås.
--------------------------------------------------------------------------------
connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: Det ble forsøkt en kontaktoperasjon til et nettverk som ikke kunne nås.
--------------------------------------------------------------------------------
```

### Example

```
pulumi stack -s test change-secrets-provider "azurekeyvault://vault-name.vault.azure.net/keys/key-name" -v3
```

### Output of `pulumi about`

```
CLI          
Version      3.118.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       debian
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v20.14.0'

Backend        
Name           782fbe30d237
URL            file://~
User           root
Organizations  
Token type     personal

Pulumi locates its logs in /tmp by default
```

### Additional context

I can get an access token and connect to the key vault like this:

```sh
ACCESS_TOKEN=$(az account get-access-token --resource https://vault.azure.net --query accessToken --output tsv)
curl -H "Authorization: Bearer $ACCESS_TOKEN" https://vault-name.vault.azure.net/keys?api-version=7.2
```

So it seems that pulumi does not use the `az login` credentials correctly.

As a workaround, is there a way to provide an access token when changing secrets provider?

I get the same issue when creating a new stack and specifyting the secrets provider.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Stadly** [comment] 2024-06-04 12:49
I'm running the command locally.

**Comment by tgummerer** [comment] 2024-06-04 13:21
Do you have a `MSI_ENDPOINT` env variable set locally?  I haven't completely understood how the detection works, but that seems one piece.  

Also how are you trying to authenticate to azure? Are you using the `az` cli, or otherwise which `AZURE_*` env variables are you setting?

**Comment by Stadly** [comment] 2024-06-04 18:35
I have not set `MSI_ENDPOINT`. I use `az login` to authenticate. I have not set any authentication related env vars.

**Comment by tgummerer** [comment] 2024-06-06 10:05
Another question, is the above output the full output you're getting for the failure, or is there any more output?

I'm pretty puzzled what's happening here, and am so far unable to reproduce it locally.

**Comment by Stadly** [comment] 2024-06-06 11:13
Does this info help?

I am using Azure Blob Storage as backend for Pulumi. If I do `export AZURE_STORAGE_SAS_TOKEN=` and run `pulumi stack ls`, I get the following output:

```
error: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): DefaultAzureCredential authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 403 connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: Det ble forsøkt en kontaktoperasjon til et nettverk som ikke kunne nås.
--------------------------------------------------------------------------------
connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: Det ble forsøkt en kontaktoperasjon til et nettverk som ikke kunne nås.
--------------------------------------------------------------------------------
```

So the output is very similar to what I get when running changing secrets provider. But I don't think there is any way to set a SAS token for a Key Vault?

If I set `AZURE_STORAGE_SAS_TOKEN` correctly, `pulumi stack ls` works as expected.

**Comment by tgummerer** [comment] 2024-06-12 12:13
Sorry for losing track of this issue.  I just realized that there was already an open issue that describes similar problems in https://github.com/pulumi/pulumi/issues/11854.  Are you also running this on Windows in a devcontainer by any chance?

**Comment by Stadly** [comment] 2024-06-12 20:15
Yes, I am using a Dev Container on Windows!

As mentioned, I also ran into the backend issue as described in that ticket. I set ut a SAS token to work around it. Was not able to find a similar workaround for the secrets provider.

Interesting that it seems to be a network issue. How does then the SAS token solve it?

**Comment by tgummerer** [comment] 2024-06-13 09:38
What I *think* is happening is that the underlying windows machine is setting up an `IMDS` authentication service which the Azure SDK which we are using under the hood is detecting in the dev container, but that can't actually be reached from the dev container for some reason.  

I don't know much about how networking works on windows, but I'm guessing the workaround in https://github.com/pulumi/pulumi/issues/11854#issuecomment-1397019565 is setting this up correctly in the dev container, so it works.

Setting the SAS token solves the issue because that's another authentication method that's getting prioritized, and thus the library never tries to use the `IMDS` authentication method, so it works just fine.

**Comment by tgummerer** [comment] 2024-06-13 10:04
I've opened an upstream issue for the Azure SDK, where I think the bug is: https://github.com/Azure/azure-sdk-for-go/issues/23058

**Comment by Stadly** [comment] 2024-06-13 12:43
> I've opened an upstream issue for the Azure SDK, where I think the bug is: [Azure/azure-sdk-for-go#23058](https://github.com/Azure/azure-sdk-for-go/issues/23058)

Thanks!

**Comment by tgummerer** [comment] 2024-06-13 16:19
From the response [here](https://github.com/Azure/azure-sdk-for-go/issues/23058#issuecomment-2166021932) it looks like it's going to be hard to do something about this.  Switching away from the DefaultCredential would mean a bunch of other backwards compatibility issues.  So I think your best option here is to either try the workaround described in https://github.com/pulumi/pulumi/issues/11854#issuecomment-1397019565, or use the environment credentials as discussed in https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#EnvironmentCredential, or not using the devcontainer.  Do any of these options work for you?

**Comment by tgummerer** [comment] 2024-09-19 11:43
Closing based on the response above.

**Closed by tgummerer** 2024-09-19 11:43 UTC
Labels: kind/bug, area/secrets, awaiting-feedback, resolution/wont-fix
