### ISSUE TITLE
Missing plugin in Github Action CI pipeline

### ISSUE THREAD

**Issue by simonlevy5** [pulumi/pulumi#6256] opened 2021-02-05 01:41 UTC
Our Github action for running `pulumi preview` started failing with the following Diagnostic output:
```
Diagnostics:
  pulumi:providers:aws (default_3_26_1):
    error: no resource plugin 'aws-v3.26.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v3.26.1`
```

This works locally for some of our developers but does not for others. (more detail below)

## Expected Behavior

The pipeline should install pulumi and run `pulumi preview` with no errors

## Current Behavior

Pipeline fails with the diagnostic:
```
Diagnostics:
  pulumi:providers:aws (default_3_26_1):
    error: no resource plugin 'aws-v3.26.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v3.26.1`
```

## Steps to Reproduce
1. Run our CI pipeline which uses the Pulumi Github Action (`pulumi/actions@v1`) with the command `preview`. Pipeline code below:
```
name: Preview
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - uses: pulumi/actions@v1
        with:
          command: preview
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          IS_PR_WORKFLOW: true
          PULUMI_ROOT: deploy/legacy

```

For the developer where `pulumi preview` runs locally without issue running `pulumi plugin ls` produces:
```
aws         resource  3.26.1                            260 MB  3 days ago   3 days ago
aws         resource  3.25.1                            259 MB  1 week ago   1 week ago
aws         resource  3.24.0                            259 MB  2 weeks ago  2 weeks ago
aws         resource  3.23.0                            259 MB  3 weeks ago  3 weeks ago
aws         resource  3.21.0                            253 MB  1 month ago  1 month ago
aws         resource  3.20.0-alpha.1607556814+e40d2a9c  253 MB  1 month ago  1 month ago
aws         resource  3.20.0-alpha.1607454742+261742f4  253 MB  1 month ago  1 month ago
docker      resource  2.6.1                             43 MB   2 weeks ago  2 weeks ago
docker      resource  2.5.0                             43 MB   1 month ago  1 month ago
docker      resource  2.3.0                             45 MB   1 month ago  1 month ago
okta        resource  2.7.1                             45 MB   2 weeks ago  2 weeks ago
postgresql  resource  2.5.3                             41 MB   2 weeks ago  2 weeks ago
postgresql  resource  2.5.2                             41 MB   4 weeks ago  4 weeks ago
random      resource  3.0.1                             31 MB   2 weeks ago  2 weeks ago
random      resource  3.0.0                             31 MB   1 month ago  1 month ago
tls         resource  3.0.0                             31 MB   4 weeks ago  4 weeks ago
```

They are using brew installed version of pulumi `2.20.0`.

For the developer who can reproduce this locally, running `pulumi plugin ls` produces:
```
aws resource 3.25.1 259 MB 2 hours ago 2 hours ago
aws resource 3.21.0 253 MB 4 weeks ago 4 weeks ago
random resource 3.0.1 31 MB 2 hours ago 2 hours ago
```

The project contains the following dependencies:
```
        "@pulumi/aws": "^3.25.1",
        "@pulumi/awsx": "^0.24.0",
        "@pulumi/okta": "^2.7.1",
        "@pulumi/postgresql": "^2.5.2",
        "@pulumi/pulumi": "^2.17.2",
        "@pulumi/random": "^3.0.0",
        "@pulumi/tls": "^3.0.0",
```

The project running in the pipeline uses a stackReference.

## Context (Environment)

Our CI can't run pulumi

A suggested solution is to add the command to our pipeline:
`pulumi plugin install resource aws v3.26.1`

This would only affect one pipeline

**Comment by berickso240** [comment] 2021-02-05 01:54
This failure also happens when I run pulumi preview on my local machine.

When I run "pulumi plugin ls", this is the output:
NAME    KIND      VERSION  SIZE    INSTALLED    LAST USED
aws     resource  3.25.1   259 MB  2 hours ago  2 hours ago
aws     resource  3.21.0   253 MB  4 weeks ago  4 weeks ago
random  resource  3.0.1    31 MB   2 hours ago  2 hours ago

TOTAL plugin cache size: 543 MB

**Comment by leezen** [comment] 2021-02-09 18:48
Closing as a duplicate of https://github.com/pulumi/pulumi/issues/5619

**Closed by leezen** 2021-02-09 18:48 UTC
Labels: needs-triage

**Comment by justinvp** [comment] 2021-02-19 18:30
> For the developer who can reproduce this locally, running `pulumi plugin ls` produces:

@simonlevy5, I'm trying to reproduce this behavior. I know it's been a while, but is it possible to collect more detailed logs from the developer who can reproduce this locally?

```
pulumi preview --logtostderr -v=9
```

I'm mainly interested in the logs emitted from `plugins.go` that will be emitted at the beginning. They'll look something like:

```
I0219 10:15:16.334439   29990 plugins.go:77] gatherPluginsFromProgram(): gathering plugins from language host
I0219 10:15:16.334562   29990 plugins.go:588] GetPluginPath(language, nodejs, <nil>): found on $PATH /opt/pulumi/bin/pulumi-language-nodejs
I0219 10:15:16.334594   29990 plugin.go:124] Launching plugin 'nodejs' from '/opt/pulumi/bin/pulumi-language-nodejs' with args: 127.0.0.1:60281
I0219 10:15:16.504598   29990 langruntime_plugin.go:178] langhost[nodejs].GetPluginInfo() executing
I0219 10:15:16.505105   29990 langruntime_plugin.go:91] langhost[nodejs].GetRequiredPlugins(proj=awsdeps,pwd=/Users/user/Desktop/awsdeps,program=.) executing
I0219 10:15:16.540300   29990 pulumi.go:393] error determining if the running executable was installed with brew: lstat /usr/local/Cellar/pulumi: no such file or directory
I0219 10:15:16.623538   29990 langruntime_plugin.go:133] langhost[nodejs].GetRequiredPlugins(proj=awsdeps,pwd=/Users/user/Desktop/awsdeps,program=.) success: #versions=2
I0219 10:15:16.623560   29990 plugins.go:89] gatherPluginsFromProgram(): plugin nodejs <nil> () is required by language host
I0219 10:15:16.623578   29990 plugins.go:89] gatherPluginsFromProgram(): plugin aws 3.29.1 () is required by language host
I0219 10:15:16.623585   29990 plugins.go:89] gatherPluginsFromProgram(): plugin docker 2.8.1 () is required by language host
I0219 10:15:16.623593   29990 plugins.go:101] gatherPluginsFromSnapshot(): gathering plugins from snapshot
I0219 10:15:16.623624   29990 plugins.go:133] ensurePluginsAreInstalled(): beginning
I0219 10:15:16.623762   29990 plugins.go:588] GetPluginPath(language, nodejs, <nil>): found on $PATH /opt/pulumi/bin/pulumi-language-nodejs
I0219 10:15:16.623788   29990 plugins.go:138] ensurePluginsAreInstalled(): plugin nodejs <nil> already installed
I0219 10:15:16.624061   29990 plugins.go:627] GetPluginPath(resource, aws, 3.29.1): enabling new plugin behavior
I0219 10:15:16.624082   29990 plugins.go:709] SelectCompatiblePlugin(..., aws): beginning
I0219 10:15:16.624091   29990 plugins.go:748] SelectCompatiblePlugin(..., aws): failed to find match
I0219 10:15:16.624313   29990 plugins.go:627] GetPluginPath(resource, docker, 2.8.1): enabling new plugin behavior
I0219 10:15:16.624326   29990 plugins.go:709] SelectCompatiblePlugin(..., docker): beginning
I0219 10:15:16.624332   29990 plugins.go:748] SelectCompatiblePlugin(..., docker): failed to find match
I0219 10:15:16.624368   29990 plugins.go:146] ensurePluginsAreInstalled(): plugin docker 2.8.1 not installed, doing install
I0219 10:15:16.624380   29990 plugins.go:146] ensurePluginsAreInstalled(): plugin aws 3.29.1 not installed, doing install
I0219 10:15:16.624396   29990 plugins.go:165] installPlugin(docker, 2.8.1): beginning install
I0219 10:15:16.624398   29990 plugins.go:165] installPlugin(aws, 3.29.1): beginning install
I0219 10:15:16.624404   29990 plugins.go:172] installPlugin(docker, 2.8.1): initiating download
I0219 10:15:16.624404   29990 plugins.go:172] installPlugin(aws, 3.29.1): initiating download
I0219 10:15:16.624727   29990 plugins.go:236] docker downloading from https://get.pulumi.com/releases/plugins
I0219 10:15:16.624738   29990 plugins.go:236] aws downloading from https://get.pulumi.com/releases/plugins
I0219 10:15:16.624767   29990 plugins.go:243] full plugin download url: https://get.pulumi.com/releases/plugins/pulumi-resource-docker-v2.8.1-darwin-amd64.tar.gz
I0219 10:15:16.624794   29990 plugins.go:253] plugin install request headers: map[User-Agent:[pulumi-cli/1 (; darwin)]]
I0219 10:15:16.625001   29990 plugins.go:243] full plugin download url: https://get.pulumi.com/releases/plugins/pulumi-resource-aws-v3.29.1-darwin-amd64.tar.gz
I0219 10:15:16.625022   29990 plugins.go:253] plugin install request headers: map[User-Agent:[pulumi-cli/1 (; darwin)]]
I0219 10:15:16.815262   29990 plugins.go:260] plugin install response headers: map[Accept-Ranges:[bytes] Age:[243716] Content-Disposition:[attachment; filename=pulumi-resource-aws-v3.29.1-darwin-amd64.tar.gz] Content-Length:[78483457] Content-Type:[application/x-gzip] Date:[Tue, 16 Feb 2021 22:33:21 GMT] Etag:["b1e3145c1f5dab95769c0881d5781699-15"] Last-Modified:[Tue, 16 Feb 2021 22:13:46 GMT] Server:[AmazonS3] Via:[1.1 653091ac0195c12aece44bebed9fcff9.cloudfront.net (CloudFront)] X-Amz-Cf-Id:[H6ojb-dLvigd7sxMPmJuWrYy7EUpXR-xi8mVmIAXxTfzJl5LHaNGeg==] X-Amz-Cf-Pop:[YVR50-C1] X-Cache:[Hit from cloudfront]]
[resource plugin aws-3.29.1] installing
Downloading plugin: 0 B / 74.85 MiB [----------------------------------]   0.00%I0219 10:15:16.816430   29990 plugins.go:182] installPlugin(aws, 3.29.1): extracting tarball to installation directory
I0219 10:15:16.850535   29990 plugins.go:260] plugin install response headers: map[Accept-Ranges:[bytes] Age:[253300] Content-Disposition:[attachment; filename=pulumi-resource-docker-v2.8.1-darwin-amd64.tar.gz] Content-Length:[18846722] Content-Type:[application/x-gzip] Date:[Tue, 16 Feb 2021 19:53:37 GMT] Etag:["2e951fcc0801ffd421df93fcbc2299dc-4"] Last-Modified:[Tue, 16 Feb 2021 19:26:05 GMT] Server:[AmazonS3] Via:[1.1 653091ac0195c12aece44bebed9fcff9.cloudfront.net (CloudFront)] X-Amz-Cf-Id:[xqRdZzsuRjN0-ZpTAiIJAWkhoQItEKzb1NVCrgY3Eug6tc9ILpn_pg==] X-Amz-Cf-Pop:[YVR50-C1] X-Cache:[Hit from cloudfront]]
[resource plugin docker-2.8.1] installing
Downloading plugin: 0 B / 17.97 MiB [----------------------------------]   0.00%I0219 10:15:16.850622   29990 plugins.go:182] installPlugin(docker, 2.8.1): extracting tarball to installation directory
Downloading plugin: 17.97 MiB / 17.97 MiB [=========================] 100.00% 5s
I0219 10:15:21.863158   29990 plugins.go:189] installPlugin(docker, 2.8.1): successfully installed
Downloading plugin: 74.85 MiB / 74.85 MiB [========================] 100.00% 13s
I0219 10:15:30.335233   29990 plugins.go:189] installPlugin(aws, 3.29.1): successfully installed
I0219 10:15:30.335248   29990 plugins.go:153] ensurePluginsAreInstalled(): completed
I0219 10:15:30.335290   29990 plugins.go:241] computeDefaultProviderPlugins(): considering nodejs
I0219 10:15:30.335297   29990 plugins.go:244] computeDefaultProviderPlugins(): skipping nodejs, not a resource provider
I0219 10:15:30.335301   29990 plugins.go:241] computeDefaultProviderPlugins(): considering docker-2.8.1
I0219 10:15:30.335307   29990 plugins.go:272] computeDefaultProviderPlugins(): plugin docker-2.8.1 selected for package docker (first seen)
I0219 10:15:30.335311   29990 plugins.go:241] computeDefaultProviderPlugins(): considering aws-3.29.1
I0219 10:15:30.335317   29990 plugins.go:272] computeDefaultProviderPlugins(): plugin aws-3.29.1 selected for package aws (first seen)
I0219 10:15:30.335321   29990 plugins.go:278] computeDefaultProviderPlugins(): summary of default plugins:
I0219 10:15:30.335324   29990 plugins.go:280]   docker          = 2.8.1
I0219 10:15:30.335329   29990 plugins.go:280]   aws             = 3.29.1
```

**Comment by aterreno** [comment] 2022-04-08 11:55
this is closed but happens to me every time I update the pulumi aws provider
