### ISSUE TITLE
Short names in export graphviz file

### ISSUE THREAD

**Issue by solomonshorser** [pulumi/pulumi#10663] opened 2022-09-08 20:11 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When I export a dependency graph to a file for visualization, the nodes have very long names, based on their URNs. This makes them easy to identify, but makes the resulting graphs very hard to read since the node labels are very long.

It would be nice if there was an option that would let me use "short" names (only the last part of the URN, the part which contains the resource name as defined in the program) when generating the graph file.

I would prefer it if node names were short and simple; instead of "urn:pulumi:my_very_long_stack_name::my_very_long_project_name::gcp:secretmanager/secretVersion:SecretVersion::some-secret-version", I would rather just see "some-secret-version". 

### Affected area/feature

CLI

**Comment by iwahbe** [comment] 2022-09-09 14:04
Hi @solomonshorser. Thanks for filing this issue. I think it is a good suggestion.

For clarity, this is in reference to the `pulumi stack graph` command.

**Comment by solomonshorser** [comment] 2022-09-09 15:21
@iwahbe Yes. Maybe a `-s | --short-name` flag could be passed to `pulumi stack graph` to use short names in the graph output.

**Comment by krupaJari** [comment] 2022-09-10 18:21
Hey @solomonshorser, 
I looked into your project and would like to contribute to this issue.
If possible, can you please assign this issue to me?

**Comment by iwahbe** [comment] 2022-09-12 10:23
Thanks @krupaJari! You are assigned. Let me know if you have any questions.

**Comment by krupaJari** [comment] 2022-09-18 12:15
@iwahbe Thanks a lot for assigning me this issue. Could you please let me know the workflow or point me to the files? I know that the issue is related to pulumi stack graph command but I'm confused due to the related files in different languages. So, could you please guide me through the design and point where the changes should be reflected.

**Comment by Frassle** [comment] 2022-09-18 13:47
I think the only changes needed will be in 'pkg/cmd/pulumi/stack_graph.go'. The main thing to change being lines [180-182](https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/stack_graph.go#L180-L182) which decide the label for the graph nodes, which currently just returns the full URN. Just need to pass a flag down to there such that rather than returning the full URN it just uses the name part of the URN instead.

**Comment by krupaJari** [comment] 2022-09-25 09:54
Thanks a lot @Frassle.

**Comment by heagma** [comment] 2022-11-13 14:20
@krupaJari you working on this?. There is some other changes to be done if we want to keep both URNS and short names. I got a PR ready for this, so let me know if I can go ahead and push it. 

cc @iwahbe

**Comment by krupaJari** [comment] 2022-11-13 15:51
@heagma I'm working on it. I was facing some issues, so not fully done with it.

**Comment by iwahbe** [comment] 2022-11-14 23:42
@heagma If you already have a branch ready, feel free to make it public and open a PR. We're going to give @krupaJari priority on this, since they asked to be assigned first.

@krupaJari It would be great if you could post your branch as a draft PR so we could see what you have so far. If you're blocked somewhere, let us know and we can help you get moving again.

If either of you want to review each-others PRs (once posted), that would be super helpful as well. We would be happy to add commit marking a reviewer as a co-author.

**Comment by heagma** [comment] 2022-11-15 02:24
sounds about right. Just opened the PR.

**Comment by krupaJari** [comment] 2022-11-15 20:25
@iwahbe I'm working on the draft PR. I'm currently trying the integration testing for the changes made but when I run the 'make ensure' command, the build fails because of dotnet. Also, when I 'run and debug' the modified 'stack_graph.go' file, errors pop up because of go ("message": "go.sum is out of sync with go.mod. Please update it by applying the quick fix.", "source": "go list"). I tried the quick fixes and manually updated the go version to 1.18.8 but to no avail.
(I'm using gitpod for making the changes and testing).

**Comment by iwahbe** [comment] 2022-11-15 21:27
> I'm working on the draft PR.

@krupaJari You can open a PR with what you have right now, even if it doesn't pass all tests. That way we can collaborate on the branch.

> I'm currently trying the integration testing for the changes made but when I run the 'make ensure' command, the build fails because of dotnet. 

If you don't have `dotnet` installed then `make ensure` will fail, but thats ok. `make build` will only build the `pulumi` binary, which should be all you need.

> Also, when I 'run and debug' the modified 'stack_graph.go' file, errors pop up because of go ("message": "go.sum is out of sync with go.mod. Please update it by applying the quick fix.", "source": "go list"). I tried the quick fixes and manually updated the go version to 1.18.8 but to no avail.

I'm not sure about this. I don't think you will need to touch `go.mod` or `go.sum`. Like I said, we can debug it together if you post your branch.

**Comment by krupaJari** [comment] 2022-11-16 20:15
@iwahbe I've done a draft PR. And as per your suggestion, I tried doing make build but I'm getting the following errors : 
```BUILD:
Protobuffer interfaces are ....... up to date
Checking for go . ✓
cd pkg && go install -ldflags "-X github.com/pulumi/pulumi/pkg/v3/version.Version=3.46.2-dev.0" github.com/pulumi/pulumi/pkg/v3/cmd/pulumi
# runtime/internal/sys
/home/gitpod/go/src/runtime/internal/sys/consts.go:13:7: StackGuardMultiplier redeclared in this block
        /home/gitpod/go/src/runtime/internal/sys/arch.go:27:7: other declaration of StackGuardMultiplier
/home/gitpod/go/src/runtime/internal/sys/consts.go:16:7: DefaultPhysPageSize redeclared in this block
        /home/gitpod/go/src/runtime/internal/sys/arch.go:36:7: other declaration of DefaultPhysPageSize
/home/gitpod/go/src/runtime/internal/sys/consts.go:20:7: PCQuantum redeclared in this block
        /home/gitpod/go/src/runtime/internal/sys/arch.go:40:7: other declaration of PCQuantum
/home/gitpod/go/src/runtime/internal/sys/consts.go:23:7: Int64Align redeclared in this block
        /home/gitpod/go/src/runtime/internal/sys/arch.go:43:7: other declaration of Int64Align
/home/gitpod/go/src/runtime/internal/sys/consts.go:30:7: MinFrameSize redeclared in this block
        /home/gitpod/go/src/runtime/internal/sys/arch.go:50:7: other declaration of MinFrameSize
/home/gitpod/go/src/runtime/internal/sys/consts.go:34:7: StackAlign redeclared in this block
        /home/gitpod/go/src/runtime/internal/sys/arch.go:54:7: other declaration of StackAlign
make: *** [Makefile:64: build] Error 2```

**Comment by iwahbe** [comment] 2022-11-16 22:05
@krupaJari It looks like `go` is having some problems building on gitpod. I'm not sure what's wrong there. Your branch builds fine on my machine, and it looks like it works. I left a small comment on the PR. Let me know if you want to fix it or add to the branch. Otherwise I can get it merged.

**Comment by krupaJari** [comment] 2022-11-17 04:28
@iwahbe I've made the changes. Please let me know if any other changes are required.

**Comment by iwahbe** [comment] 2022-11-17 17:42
@krupaJari It looks good to me.

**Closed** 2022-12-13 03:48 UTC
Labels: area/cli, kind/enhancement, good-first-issue, help-wanted

**Comment by krupaJari** [comment] 2022-12-13 05:24
Thank you @iwahbe for all the help!!

**Comment by iwahbe** [comment] 2022-12-13 09:41
My pleasure @krupaJari. Thank you for your patience. Next time it should be quicker to merge.
