### ISSUE TITLE
Import should not require specifying all properties

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#6146] opened 2021-01-20 00:49 UTC
Currently, importing a resource requires specifying all properties or explicitly using `ignoreChanges` to ignore certain inputs. Instead, it should be possible to import a resource without specifying all the fields. See also https://github.com/pulumi/pulumi/issues/5878 which we're using to track ensuring that the `ignoreChanges` scenario does work.

Related issues:
- [ ] https://github.com/pulumi/pulumi/issues/5878
- [ ] https://github.com/pulumi/pulumi-azure-nextgen/issues/159
- [x] https://github.com/pulumi/pulumi-azure-native/issues/794
- [ ] https://github.com/pulumi/pulumi/issues/6145
- [x] https://github.com/pulumi/pulumi-gcp/issues/505
- [x] https://github.com/pulumi/pulumi/issues/6131
- [x] https://github.com/pulumi/pulumi-aws/issues/1589
- [x] https://github.com/pulumi/pulumi-aws/issues/1591
- [x] https://github.com/pulumi/pulumi-aws/issues/1379

**Comment by lukehoban** [comment] 2022-03-20 21:51
AFAICT - this is now just a duplicate of #5878 and #6145 which are a bit clearer on what is being tracked.  Closing this out as a duplicate.

**Closed by lukehoban** 2022-03-20 21:51 UTC
Labels: kind/enhancement, area/core, resolution/duplicate, area/import
