### ISSUE TITLE
If no stack is selected, cannot select organisation stack in menu that has both underscore and period in name

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#11355] opened 2022-11-15 12:56 UTC
### What happened?

When trying to run an update with no stack selected, on a stack belonging to an organisation that has both a period and an underscore in the name, getting the following error message: `error: parsing selected stack: stack names may only contain alphanumeric, hyphens, underscores, and periods`

### Steps to reproduce

1. Create new project: `pulumi new typescript -y`
2. Create new organisation stack with both a period and an underscore (because it's an org stack, it _also_ has a slash in the name): `pulumi stack init demo/piers.piers_test`
3. Delete the dev stack so no stacks are selected (there might be a better way to replicate this part) `pulumi stack rm dev`
4. Run `pulumi up` and select the new stack from the list

### Expected Behavior

Update should run

### Actual Behavior

Error message: `error: parsing selected stack: stack names may only contain alphanumeric, hyphens, underscores, and periods`

### Output of `pulumi about`

```
CLI
Version      3.46.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  13.0
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg, karsenbarg, team-ce, demo

Pulumi locates its logs in /var/folders/69/3w1gr05s2pq36wn49bhyknym0000gn/T/ by default
warning: Failed to get information about the project runtime: unknown method About for service pulumirpc.LanguageRuntime
warning: Failed to get information about the Pulumi program's dependencies: unknown method GetProgramDependencies for service pulumirpc.LanguageRuntime
warning: Failed to get information about the current stack: No current stack
```

### Additional context

If you downgrade to v3.46.0 this works

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2022-11-15 13:10
> Delete the dev stack so no stacks are selected (there might be a better way to replicate this part) pulumi stack rm dev

`pulumi stack unselect`

> error: parsing selected stack: stack names may only contain alphanumeric, hyphens, underscores, and periods

This might just be https://github.com/pulumi/pulumi/issues/11334 which I've raised a fix for.

**Comment by pierskarsenbarg** [comment] 2022-11-15 13:11
I can do `pulumi stack select demo/piers.piers_test`and then an update and I can run `pulumi up -s demo/piers.piers_test` and the update works

**Comment by aq17** [comment] 2022-11-15 17:30
Closing as duplicate of https://github.com/pulumi/pulumi/issues/11334

**Closed** 2022-11-15 17:29 UTC
Labels: kind/bug, resolution/duplicate
