### ISSUE TITLE
Poor error messages from misuse of ResourceOptions(dependencies) in Python

### ISSUE THREAD

**Issue by iamahern** [pulumi/pulumi#10353] opened 2022-08-11 08:52 UTC
### What happened?

If a user accidentally passes an object that is a deferred output instead of (deferred) resource to resource option dependencies, it leads to an ambiguous and hard to debug issues for users. This issue is specific to the Python language binding.

During `pulumi up`, an error is raised from this line of code attempting to resolve the `urn` field (which is available from the `Resource` object):

https://github.com/pulumi/pulumi/blob/09d67511dd356fa7b77c7d0ac03d40b99d22c937/sdk/python/lib/pulumi/runtime/resource.py#L809

The resulting stack trace does not bring the user back to the line of code where they created the issue (see below).
![stack_trace](https://user-images.githubusercontent.com/1237164/184095355-0690cd9c-5ba1-4382-9fee-e707d60a5ff1.png)

### Steps to reproduce

```
# read_creds is not a resource. The return type is data class wrapped in an Output
read_creds = azure_native.eventhub.list_event_hub_keys_output(
    opts=ResourceOptions(depends_on=[eventhub_read]),
    authorization_rule_name=eventhub_read.name,
    event_hub_name=eventhub.name,
    namespace_name=eventhub_namespace.name,
    resource_group_name=resource_group_name)

secret_eventhub_read = azure_native.keyvault.Secret("eventhub-T1-read-endpoint",
    # The user introduces a defect in this line in the `depends_on` - `read_creds` is not a Resource so it fails to look up the urn 
   # The actual urn lookup occurs in an async run loop, so there is no traceback to this line of code in the stack trace
    opts=ResourceOptions(depends_on=[read_creds, vault]),  
    properties=azure_native.keyvault.SecretPropertiesArgs(
        value=read_creds.primary_connection_string,
    ),
    #secret_name="eventhub-T1-read-endpoint",
    vault_name=vault.name,
    resource_group_name=resource_group_name)
```

### Expected Behavior

Given how it challenging it is for newbie users to trace this problem. I think the Resource constructor should proactively check that the values of check the types of the inputs to ensure they are Resources in order to generate a meaningful stack trace.

Additionally, it should be noted that `mypy` does catch this error. However, because the error involved the Azure Native provider it takes 20+ mins to run mypy over this code if we let mypy resolve imports as required.

There is a proposal (See: #6837) to fix / improve the mypy experience of the Azure native component. If this was actioned, it would allow users to catch these form of errors via mypy and mitigate the edge cases needing such defensive coding to disambiguate deferred behaviours.

### Actual Behavior

Error is made with the stack trace showing only `Resource` code involved. No reference back to the line where the user introduced the error.

### Versions used

CLI          
Version      3.37.2
Go Version   go1.18.4
Go Compiler  gc

Plugins
NAME    VERSION
azure   5.14.0
python  unknown

Host     
OS       darwin
Version  12.5
Arch     x86_64

This project is written in python: executable='/Users/.../<our-repo>/.venv/bin/python3' version='3.10.5'

Backend        
Name           macpro8c
URL            azblob://<redacted>
User           iamahern
Organizations  

Dependencies:
NAME                                     VERSION
<shared-code-lib-from-our-team>  0.3
pip                                      22.2.2
setuptools                               63.4.2
wheel                                    0.37.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2022-08-11 09:44
> I think the Resource constructor should proactively check that the values of check the types of the inputs to ensure they are Resources in order to generate a meaningful stack trace.

This sounds very reasonable.

**Comment by justinvp** [comment] 2023-09-30 10:52
Closing this as a duplicate of #13917 as there's more details in that issue. See https://github.com/pulumi/pulumi/issues/13917#issuecomment-1715630212

**Closed by justinvp** 2023-09-30 10:52 UTC
Labels: kind/bug, area/sdks, language/python, resolution/duplicate
