### ISSUE TITLE
local build env: golangci-link related issues causing make failure

### ISSUE THREAD

**Issue by keen99** [pulumi/pulumi#2841] opened 2019-06-18 20:28 UTC
first time trying to get a local build env setup.   

first: 

`make ensure` runs cleanly, even without `golangci-lint` installed.    that should probably be addressed.   I'll also open a PR to add this to the `brew install`...

next:

brew installed with `brew install golangci/tap/golangci-lint`
and got:
`golangci-lint has version 1.17.1 built from 4ba2155 on 2019-06-10T09:07:35Z`

when running `make` I get multiple linting failures (clean master at `4833fe1045cad8440705505bc6bf32b3a9b2ba28`:

```
LINT:
golangci-lint run
cmd/pulumi-language-nodejs/main.go:87:56: `langauge` is a misspelling of `language` (misspell)
	cmdutil.InitTracing("pulumi-language-nodejs", "pulumi-langauge-nodejs", tracing)
	                                                      ^
make[1]: *** [lint] Error 1
make: *** [sdk/nodejs_default] Error 2
```

if I fix that one, it moves on to more typos:

```
cheese:~/git/github/pulumi/pulumi(master)%% make lint
LINT:
golangci-lint run
pkg/resource/plugin/provider_plugin_test.go:106:62: `properites` is a misspelling of `properties` (misspell)
		assert.Truef(t, reflect.DeepEqual(fromVal, val), "expected properites %s to be deeply equal", key)
		                                                           ^
tests/integration/integration_test.go:226:54: `sould` is a misspelling of `could` (misspell)
	contract.AssertNoErrorf(err, "resource.NewUniqueHex sould not fail with no maximum length is set")
	                                                    ^
tests/integration/integration_test.go:268:54: `sould` is a misspelling of `could` (misspell)
	contract.AssertNoErrorf(err, "resource.NewUniqueHex sould not fail with no maximum length is set")
	                                                    ^
make: *** [lint] Error 1
```

comparing that to a recent travis build - https://travis-ci.com/pulumi/pulumi/builds/115992790

which just does:

```LINT:
golangci-lint run
./node_modules/.bin/tslint -c tslint.json -p tsconfig.json
TEST ALL:```

the travis build doesnt mention (that I saw) what version of `golangci-lint` is being run - so there could be a version issue.   (I haven't dug into try to see if it's defined somewhere else)

otherwise - I'd suspect there's a config file somewhere that's missing from the repo that defines the linting rules?

**Comment by ellismg** [comment] 2019-06-18 21:28
We use a slightly older version (1.16.0)

https://github.com/pulumi/scripts/blob/master/ci/install-common-toolchain.sh#L24

> otherwise - I'd suspect there's a config file somewhere that's missing from the repo that defines the linting rules?

We should have our configuration file checked in (see `.golangci.yml` in the root).  I think the issue is that golangci-lint vendors in all the linters it runs and so newer versions may have better analysis.  Upgrading my local copy to 1.17.1 I can see the same issues you see.

I would be fine if we made these warnings locally but failed them in CI?  We'll also can upgrade our version of the linter to the newest version (I opened https://github.com/pulumi/scripts/issues/71 to track that)

**Closed** 2019-06-18 22:30 UTC
