### ISSUE TITLE
`aws.config.region` not populated for multi-language component authored in Node.js and consumed by Python

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#6087] opened 2021-01-11 21:45 UTC
It appears that the language host that runs mutli-language component programs is not initialized with the configuration of the current deployment, so any usage of APIs like `aws.config.region` returns `undefined` even if the setting is provided by the user.

**Comment by mikhailshilkov** [comment] 2021-01-21 18:49
Dupe of #5582

**Closed by mikhailshilkov** 2021-01-21 18:49 UTC
Labels: needs-triage
