### ISSUE TITLE
option to prompt pulumi CLI upgrade to latest master commit

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#9946] opened 2022-06-23 18:43 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Adding an option to prompt interested users to automatically upgrade the CLI to the latest master version.

**Comment by Frassle** [comment] 2022-06-24 12:10
Duplicate of https://github.com/pulumi/pulumi/issues/9952

**Closed by Frassle** 2022-06-24 12:10 UTC
Labels: area/cli, kind/enhancement, resolution/duplicate
