### ISSUE TITLE
Updating AppSettings in AppService fails

### ISSUE THREAD

**Issue by OleAlbers** [pulumi/pulumi#6289] opened 2021-02-09 13:46 UTC
Modifying the AppSettings of an Azure AppService  (Azure.AppService.AppService) fails with the errormessage 
> panic: interface conversion: interface {} is nil, not map[string]interface {}

when trying to update. Changes are even published but update fails nonetheless. On other Resources like FunctionApps (Azure.AppService.FunctionApp) this error does *not* occur.

TL;DR: 1. Changed AppSettings of AppServices are being stored in Azure
2. Pulumi crashes afterwards

## Expected Behavior
AppSettings being deployed without an error.

## Current Behavior
AppSettings are being deployed but an exception is thrown afterwards preventing any other updates to be executed

## Steps to Reproduce
1. Create any AppService containing AppSettings:

```
            var service= AppService(appserviceName, new AppServiceArgs
            {
                Location = _resourceGroup.Location,
                AppServicePlanId = _servicePlan.Id,
                ResourceGroupName = "rsgroupname"
                SiteConfig = new Pulumi.Azure.AppService.Inputs.AppServiceSiteConfigArgs
                {
                    DotnetFrameworkVersion = "v5.0",
                    ScmType = "None",
                },
                AppSettings = { { "anything","goes"}}
            });
```
2. deploy changes using `pulumi up`
3. Change the Appsettings in the code:
...              `AppSettings = { { "anything","goes"},{"something","happens"}}`
4. redeploy changes using `pulumi up`
5. Error is thrown

>  panic: interface conversion: interface {} is nil, not map[string]interface {}
>     goroutine 104 [running]:
>     github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/web.expandAppServiceLogs(0x57ef5c0, 0xc002a09300, 0x4, 0x57ef5c0, 0xc002a09300, 0x1)

**Comment by mikhailshilkov** [comment] 2021-02-09 13:52
Dupe of https://github.com/pulumi/pulumi-azure/issues/740

**Closed by mikhailshilkov** 2021-02-09 13:52 UTC
Labels: needs-triage
