### ISSUE TITLE
Local backend does not permit slashes for stack names proj/stack

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi#6267] opened 2021-02-06 16:22 UTC
When developing locally, we may have multiple projects with the same stack names (dev,test,prod), would be nice to be able to create those stacks with the same names in each project, but when qualifying by project name I get the following error:

```
$ pulumi stack init ProjectName/dev
error: stack names may not contain slashes
$ pulumi stack init DummyOrgName/ProjectName/dev
error: stack names may not contain slashes
```

That forces me to create stacks with the name of the project in the stack name (ProjectName-dev,ProjectName-test).

It would be nice to be able to have stacks per project also locally.

Thank you

**Comment by leezen** [comment] 2021-02-09 18:49
Closing as a duplicate of https://github.com/pulumi/pulumi/issues/2522

**Closed by leezen** 2021-02-09 18:49 UTC
Labels: resolution/duplicate
