### ISSUE TITLE
Add a Rust SDK

### ISSUE THREAD

**Issue by LukeMathWalker** [pulumi/pulumi#5310] opened 2020-09-09 14:26 UTC
Pulumi's FAQs point to https://github.com/pulumi/pulumi/pull/1456 as the recommended path to add support for a new language.
Is that still the case or does the team need to "approve" the effort considering they might have to support it down the line?

It would be ideal to get that clarified before starting to implement :grin:

**Comment by LukeMathWalker** [comment] 2020-09-09 14:27
See https://github.com/pulumi/pulumi/issues/1539 and https://github.com/pulumi/pulumi/issues/1566

**Comment by stack72** [comment] 2020-09-09 14:55
Hi @LukeMathWalker 

thanks for opening this issue - I am going to close it as a dupe of #3622 - as you can see there, it was mentioned that we would welcome a community contribution to add the new language if needed

Paul

**Closed by stack72** 2020-09-09 14:55 UTC
Labels: area/codegen, area/languages, kind/enhancement, kind/question

**Comment by lukehoban** [comment] 2020-09-09 16:01
> Pulumi's FAQs point to #1456  

That is a little out of date - this list is possible more up to date - and includes a broader set of tools and content that will be affected.  BTW - which FAQ did you see that pointed to #1456?  I'll make sure it's updated.

**Comment by joeduffy** [comment] 2020-09-21 16:07
> BTW - which FAQ did you see that pointed to #1456? I'll make sure it's updated.

I'm not sure, however, I did notice https://www.pulumi.com/docs/troubleshooting/faq/#how-can-i-add-support-for-my-favorite-language refers to a non-existent wiki page: https://github.com/pulumi/pulumi/wiki/New-Language-Bringup

**Comment by lukehoban** [comment] 2020-09-21 16:16
Looks like the URL is missing a `-`.  The page is here: https://github.com/pulumi/pulumi/wiki/New-Language-Bring-Up.  I'll fix.
