### ISSUE TITLE
'Unknown' error when replacing NodePool leads to incorrect state

### ISSUE THREAD

**Issue by jsravn** [pulumi/pulumi#8354] opened 2021-11-01 15:05 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I modified a GKE cluster definition, which triggered its NodePool to be recreated. I am using DeleteBeforeReplace for everything. However this is in an IP constrained shared network, and so it takes a little while for the prior NodePools resources to be reclaimed by GCP.

Upon trying to create the replacement NodePool the pulumi provider got this error:
```
I1101 12:16:58.335823   42263 provider_plugin.go:1531] provider received rpc error `Unknown`: `1 error occurred:
        * Error waiting for creating GKE cluster: Requested resource is exhausted: Not all instances running in IGM after 27.758180507s. Expected 1, running 0, transitioning 1. Current errors: [IP_SPACE_EXHAUSTED]: Instance 'gke-sandbox2-test-default-pool-REDACTED' creation failed: IP space
 of 'projects/REDACTED/subnetworks/gke-subnetwork-sandbox2' is exhausted. .

`
I1101 12:16:58.335828   42263 provider_plugin.go:1534] rpc error kind `Unknown` may not be recoverable
I1101 12:16:58.335832   42263 provider_plugin.go:760] Provider[gcp, 0xc00066d1a0].Create(urn:pulumi:sandbox2::cloud-infra-pulumi::gcp:container/cluster:Cluster::primary) failed: 1 error occurred:
        * Error waiting for creating GKE cluster: Requested resource is exhausted: Not all instances running in IGM after 27.758180507s. Expected 1, running 0, transitioning 1. Current errors: [IP_SPACE_EXHAUSTED]: Instance 'gke-sandbox2-test-default-pool-REDACTED' creation failed: IP space
 of 'projects/REDACTED/subnetworks/gke-subnetwork-sandbox2' is exhausted. .

I1101 12:16:58.335845   42263 eventsink.go:86] eventSink::Error(<{%reset%}>1 error occurred:
        * Error waiting for creating GKE cluster: Requested resource is exhausted: Not all instances running in IGM after 27.758180507s. Expected 1, running 0, transitioning 1. Current errors: [IP_SPACE_EXHAUSTED]: Instance 'gke-sandbox2-test-default-pool-REDACTED' creation failed: IP space
 of 'projects/REDACTED/subnetworks/gke-subnetwork-sandbox2' is exhausted. .

<{%reset%}>)
 ++ gcp:container:Cluster primary creating replacement [diff: ~name]; error: 1 error occurred:
```

After pulumi finished with the above error, the state file still has the cluster, nodepool, and all dependencies despite the fact they have all been deleted.

I'd expect it to have recorded all the resources being deleted, but simply fail in the creation, so I can retry the pulumi up. As is I have to manually remove all resources from the statefile for it to work again.

### Steps to reproduce

1. Create gke cluster with a small subnet, such as /29.
2. Create nodepool such that subnet is used up.
3. Try to recreate cluster by changing its name, and observe the above issue.

Expected: Deleted resources are successfully updated in the state.
Actual: Deleted resources remain in the state.

**Comment by emiliza** [comment] 2021-11-04 21:52
Which language are you using @jsravn, and which versions of the CLI and SDKs?

**Comment by jsravn** [comment] 2021-11-19 13:45
> Which language are you using @jsravn, and which versions of the CLI and SDKs?

golang

```
        github.com/pulumi/pulumi-gcp/sdk/v5 v5.18.0
        github.com/pulumi/pulumi-kubernetes/sdk/v3 v3.6.3
        github.com/pulumi/pulumi-random/sdk/v4 v4.2.0
        github.com/pulumi/pulumi/sdk/v3 v3.12.0
```

**Comment by lunaris** [comment] 2024-09-09 08:01
Hi @jsravn; I've taken a look at this issue and as far as I can tell/assuming I understand correctly, this behaviour is by design:

* You have a resource with delete-before-replace semantics
* Pulumi deletes the resource in the cloud provider (here, GCP)
* Pulumi leaves the deleted resource in the state, but it is marked with `pendingReplacement: true` (more on this in a bit)
* Pulumi attempts to create a replacement but fails

We want to leave the resource in the state in cases like this for a number of reasons:

* If other resources depend on the resource being deleted, removing them from the state would result in dangling dependencies/an invalid snapshot
* When we next run a `pulumi up`, for instance, the presence of resources that are `pendingReplacement` is exactly the information Pulumi needs to resume and retry the operation.

Does this make sense? Or have I missed the point and something else is going on here where e.g. deletions have succeeded but Pulumi is still leaving things in state? Or perhaps you are hitting a snapshot integrity error already? Thanks for any information and feedback you can provide!

**Comment by lunaris** [comment] 2024-09-27 09:14
I'm going to close this -- if you have more information that could help us work on this, please feel free to reopen 🙏

**Closed by lunaris** 2024-09-27 09:14 UTC
Labels: kind/bug, awaiting-feedback, resolution/no-repro
