### ISSUE TITLE
Python programs aren't modules

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1641] opened 2018-07-17 00:23 UTC
Because of the way we simply execute `__main__.py` without using modules, you cannot use relative imports of other Python modules.  Unless I'm missing something -- totally possible -- this effectively means all Pulumi programs need to be single-module `__main__py` programs, which is seriously limiting.  I believe we can instead use an `-m` approach to launching programs that will be more module friendly.  We use `runpy`, so I'm sure we have lots of control here, and it would be great if we can support both modes (prefer a real module where available, and a plain old `__main__.py` otherwise).

**Comment by joeduffy** [comment] 2018-07-17 17:48
I actually found a workaround for this, at least for Python 2, since you can just use a non-relative import and the module will be found on the search path. I don't believe this will work for Python 3.

Thanks to the workaround, the priority of this is a bit lesser, and so moving it out a bit.

**Comment by swgillespie** [comment] 2019-01-10 21:37
> I don't believe this will work for Python 3.

I've confirmed that this does work with Python 3, as long as you use the relative import syntax `from <thing> import <symbol>`. For example, this program runs as expected (i.e. it produces a single `s3.Bucket` registration:

## foo.py

```python
import pulumi
from pulumi_aws import s3

def doit():
    s3.Bucket("bukkit")
```

## __main__.py

```python
from foo import doit

doit()
```

Treating Pulumi Python programs as modules is subtle and there's some potential for downstream breakage (for example - packages must have an `__init__.py` file in them, while Pulumi programs today don't require them). Since there's a reasonable workaround in-place, moving this out to M21.

**Comment by swgillespie** [comment] 2019-05-06 18:27
The more I write Pulumi programs in Python, the less I'm convinced this is an issue. I'm leaving this open for people to chime in, but I'm not planning to do anything here for the time being.

**Comment by astronouth7303** [comment] 2019-07-03 21:23
This is how vanilla python scripts behave, too? Like, if you define a script somewhere, or a `__main__` in a package, you can't do relative imports from there either. The errors are different, but the end result is the same.

If imported modules also can't do relative imports, then that's a bug.

**Comment by lukehoban** [comment] 2020-01-15 01:32
I'm going to close this as "by design" - the way this works is fairly standard for Python scripts, and consistent with our general approach of treating Pulumi entry points more as "running a script" than "loading a module" across all language environments.

**Closed by lukehoban** 2020-01-15 01:32 UTC
Labels: area/languages, kind/enhancement, language/python3

**Comment by b4stien** [comment] 2021-05-15 18:02
Currently struggling with this (especially code, modules and folders layout) building a PoC with Pulumi. Maybe you could add a non-trivial example to https://github.com/pulumi/examples of how you expect users to organize their projects?

As a project pass its initial stage and quickly balloon to several hundred lines of code, the "everything in the base folder" becomes difficult for readability.

**Comment by nat-n** [comment] 2023-10-11 19:29
If you're using [poetry](https://python-poetry.org/) or similar to manage the virtualenv configured in your Pulumi.yaml (generally a good idea IMO), then you can simply import any other packages defined in your project because poetry will install then into the virtualenv in dev mode.

**Comment by eric-mcdonald-blackbirdai** [comment] 2024-03-24 20:54
> If you're using [poetry](https://python-poetry.org/) or similar to manage the virtualenv configured in your Pulumi.yaml (generally a good idea IMO), then you can simply import any other packages defined in your project because poetry will install then into the virtualenv in dev mode.

Your suggestion helps for _common_ modules that are shared across Pulumi projects, but does not help for modules used within a _specific_ project. In our case, we treat our common modules as a publishable package (managed via Hatch rather than Poetry) and each Pulumi project in the same repo can access them by adding `-e ..` to its `requirements.txt` (assuming `pyproject.toml` is one directory level higher). But, the project-specific modules are not considered part of the common package and thus not listed as sources for it.

Here are several minor reasons against closing this issue:
1. Imports of project-local modules within a project increase the chance of a namespace collision with an upstream package. For example, `import github` could be problematic if someone has a local `github.py` module but wants the upstream `github` package. (Yes, the local module could be renamed, but that feels like unnecessary effort.)
2. Tools, like `isort`, do not inherently understand that imports of project-local modules are not third-party modules and will place imports of them in the wrong section ("third party" rather than "local folder"). The use of relative imports would ensure that they are in the correct section, for improved discoverability.

That said, to support relative imports of project-local modules from within `__main__.py` would probably require some `importlib` hook-building on the part of Pulumi, if a seamless developer experience is desired around this particular request. Not sure if it is worth the development effort, given that the gains are relatively minor.
