### ISSUE TITLE
Improve include component names and provider names in Exception: cannot construct components if the provider is configured with unknown values

### ISSUE THREAD

**Issue by ecerulm** [pulumi/pulumi#17002] opened 2024-08-17 10:19 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I get the `Exception: cannot construct components if the provider is configured with unknown values` but nothing in the traceback/stracktrace tells me which component or which provider the error is about. 

```
  pulumi:pulumi:Stack (pulumi-test-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/Users/ecerulm/git/pulumi-test/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 138, in run_in_stack
        await run_pulumi_func(run)
      File "/Users/ecerulm/git/pulumi-test/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 52, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/ecerulm/git/pulumi-test/venv/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 85, in wait_for_rpcs
        raise exn from cause
      File "/Users/ecerulm/git/pulumi-test/venv/lib/python3.12/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
                 ^^^^^^^^^
      File "/Users/ecerulm/git/pulumi-test/venv/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 1015, in do_register
        resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/ecerulm/git/pulumi-test/venv/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 1012, in do_rpc_call
        handle_grpc_error(exn)
      File "/Users/ecerulm/git/pulumi-test/venv/lib/python3.12/site-packages/pulumi/runtime/settings.py", line 307, in handle_grpc_error
        raise grpc_error_to_exception(exn)
    Exception: cannot construct components if the provider is configured with unknown values
```

**Comment by Frassle** [comment] 2024-08-17 14:20
@tgummerer was working on a fix so this wouldn't be an error at all.

**Comment by justinvp** [comment] 2024-08-17 21:43
> this wouldn't be an error at all

I'm going to close this as a dupe of https://github.com/pulumi/pulumi/issues/16331 since we're looking at addressing this such that it's no longer an error.

**Closed by justinvp** 2024-08-17 21:43 UTC
Labels: kind/enhancement, resolution/duplicate
