### ISSUE TITLE
[codegen/docs] Wrapped input type properties are rendered incorrectly

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#6806] opened 2021-04-19 07:17 UTC
Input types for typescript and python etc. now accurately represented as inputs (e.g. `pulumi.Input<string>` instead of `string`) in docs through https://github.com/pulumi/pulumi/pull/6686 but since we inject `<wbr>` to wrap long types (https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/gen.go#L922) and treat the `displayName` as safe html, we end up with just `pulumi.Input` being rendered when the actual html source contains: `pulumi.<wbr>Input<string>`.

See attached image for example rendered or visit http://pulumi-docs-origin-pr-5779-b7d0e45c.s3-website.us-west-2.amazonaws.com/docs/reference/pkg/google-native/container/v1beta1/cluster/#inputs. 

This affects any re-rendered provider docs (reproduced on google-native, aws etc.)

![Example](https://user-images.githubusercontent.com/1454008/115124941-737ede00-9fc5-11eb-8df7-e6990880e516.png)

**Comment by viveklak** [comment] 2021-04-19 08:08
Closing duplicate of https://github.com/pulumi/pulumi/issues/6806

**Comment by mikhailshilkov** [comment] 2021-04-19 12:31
I think you closed it as a duplicate of itself?

**Comment by viveklak** [comment] 2021-04-19 16:04
> I think you closed it as a duplicate of itself?

Yup 🤦🏾 . Fixed.

**Closed** 2021-04-19 16:04 UTC
Labels: area/docs, kind/bug, resolution/duplicate
