### ISSUE TITLE
NewStackReference for different Backend

### ISSUE THREAD

**Issue by giacomo-pati** [pulumi/pulumi#7069] opened 2021-05-17 06:47 UTC
## Affected feature

pulumi.NewStackReference

We have organized our Pulumi Golang Stack development in a layered approach similar to [Playbooks for Kubernetes](https://www.pulumi.com/docs/guides/crosswalk/kubernetes/playbooks/) where higher level layer Stacks might have references to output of lower level layer Stacks via NewStackReference.

As we are using the azblob Backend to store the Stacks (this Backend doesn't allow for a hierarchical naming of Stacks like the default Pulumi Backend), over time the amount of stacks in a single Azure Blob Container becomes messy and needs to have a strict naming convention for Stacks to have an idea which Stacks belongs to which layer. So we wanted to spread the Stacks of the layers among different Azure Blob Containers. But then it seems not anymore possible to reference lower level Stacks via NewStackReferece without specifying which backend URL that stack is stored with (to specify the respective Azure Blob Container the referenced Stack is stored to).

As I couldn't find any documentation to the topic nor did I found in the code whether this is possible, I'd like to request the feature for NewStackReference to allow passing a alternative Backend for a referenced Stack name.

As a solution I was thinking of either 
1. an added member 'backend-url' in the pulumi.StackReferenceArgs struct 
2. via the ResourceOption argument pulumi.Provider (which would require a respective factory method for such new Backends)

From a design perspective I would prefer option 2 as it seems more to the design of Pulumi to me.
If you would provide some pointers I could potentially provide an initial implementation for such as a Pull Request.

**Comment by Frassle** [comment] 2022-11-11 10:07
Duplicate of https://github.com/pulumi/pulumi/issues/3395

**Closed by Frassle** 2022-11-11 10:07 UTC
Labels: kind/enhancement, resolution/duplicate
