### ISSUE TITLE
Write more tests for --targets

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#10056] opened 2022-07-06 15:25 UTC
We had a p0 issue https://github.com/pulumi/pulumi/issues/10020 due to change in how --targets worked. None of our tests picked this up before release, and in the investigation afterwards there appear to be quite a few things that haven't been fully considered with regards to how targets should work.

We should write some more tests to cover these cases.
- [x] Write a test that repro's #10020 
- [ ] Write tests for each SDK to check how their outputs behave when resources are skipped due to --targets

**Comment by dixler** [comment] 2023-05-24 18:56
Closing as we've added a test that addresses the first issue since we now understand the root cause.
- https://github.com/pulumi/pulumi/pull/12973

A resource's inputs has a field called `__defaults` and were not being populated when provider.Check was skipped on untargeted resources.

The targeted update saves the `same`d resources with missing `__defaults`. Same'd resources are not shown to the user because it's assumed that they have the "same state" as before.

With the next update, the resources are missing `__defaults` causing the provider to indicate that the resource should be updated/replaced.

**Closed by dixler** 2023-05-24 18:56 UTC
Labels: area/testing, kind/engineering, resolution/fixed
