### ISSUE TITLE
Pulumi v3.22.0 rewrites Pulumi.<stack>.yaml in invalid ways

### ISSUE THREAD

**Issue by pquerna** [pulumi/pulumi#8760] opened 2022-01-14 21:31 UTC
## Hello!
When running `pulumi preview --stack x`, my file `Pulumi.x.yaml` is being rewritten.

This is generally bad, but, specifically fields that are numbers are being "de-quoted" by Pulumi:
```
-  c1:image_ecr_account: "314626158150"
+  c1:image_ecr_account: 314626158150
```
This is also going _very_ wrong with a specific value, that is a quoted string of the pattern "1234..1234", pulumi is stripping the quotes, and then... formatting it as a number in exponential notation:
```
-  c1:project_client_id: "13[REDACTED].22[REDACTED]"
+  c1:project_client_id: 1.31592653589793e+12
```

Did not see this behavior with Pulumi 3.21

**Comment by t0yv0** [comment] 2022-01-14 22:15
Apologies for this regression! We've released https://github.com/pulumi/pulumi/tree/v3.22.1 to fix and this is a duplicate of https://github.com/pulumi/pulumi/issues/8752

**Closed by t0yv0** 2022-01-14 22:15 UTC
Labels: kind/bug
