### ISSUE TITLE
Severe (❗) memory leak since version `v3.49.0`

### ISSUE THREAD

**Issue by dotansimha** [pulumi/pulumi#11650] opened 2022-12-14 11:53 UTC
### What happened?

Since `v3.49.0`, it seems like Pulumi CLI is suffering from a **severe** memory leak. 

### Steps to reproduce

1. Have a Pulumi project (we are using NodeJS, but I'm not sure it's related to it) 
3. Use latest Pulumi CLI `v3.49.0` 
4. Run `pulumi up` (memory grow starts after the approval of the prompt) 
5. Trach the `pulumi` process

### Expected Behavior

No memory leak, and no crashing processes. 

### Actual Behavior

We noticed it because our GitHub Actions workflows started to fail due to `The operation was canceled.`. This usually happens when the GitHub Actions runner are exceeding the memory limit and reaches the maximum allowed (https://github.com/actions/runner-images/issues/1918). 

The actual exit code of the Pulumi process in that case (running in GH Actions) is `143`, with not additional details (due to the kill signal coming from GH Actions). 

I was running the same version (`v3.49.0`) locally on my Macbook M1 with 64GB RAM, deployment runtime was super slow (10 minutes, compared to ~3 minute before) and the `pulumi` process got to almost 30GB of RAM:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/3680083/207582924-8957cd79-52e0-4254-b91c-57e123a8a4e9.png">

### Output of `pulumi about`

```
CLI
Version      3.49.0
Go Version   go1.19.4
Go Compiler  gc

Host
OS       darwin
Version  12.6
Arch     arm64
```

### Additional context

Our project is a NodeJS project, we are running Node 16 LTS, and using the following NodeJS packages:

```
    "@pulumi/azure": "5.23.0",
    "@pulumi/cloudflare": "4.12.1",
    "@pulumi/kubernetes": "3.22.0",
    "@pulumi/kubernetesx": "0.1.6",
    "@pulumi/pulumi": "3.44.1",
    "@pulumi/random": "4.8.2",
```

In GitHub Actions, we are running `pulumi/actions@v3.20.0` (latest). 

Downgrading Pulumi CLI to version `v3.48.0` seems to solve the issue locally (memory was stable on `~350MB`), and pinning the version in `pulumi/actions` using `pulumi-version: '3.48.0'` seems to solve it in CI. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2022-12-14 12:22
Thank you for confirming @dotansimha.
I'll request our service team disable the server side capability that triggered this option to turn on.

**Comment by kwohlfahrt** [comment] 2022-12-14 16:27
I think I'm seeing the same issue on my laptop (M1 MacBook, 16 GiB memory). Running `pulumi up` fails with a `SIGKILL`. Setting `PULUMI_OPTIMIZED_CHECKPOINT_PATCH=0` works around this issue.

**Comment by blampe** [comment] 2022-12-14 17:29
We're deploying the revert server-side now, so if you're still experiencing this it should be resolved within an hour.

**Comment by t0yv0** [comment] 2022-12-14 20:07
Closing as the change has been rolled back from the Pulumi Service. Filed #11653 to address the root cause.

**Closed by t0yv0** 2022-12-14 20:07 UTC
Labels: kind/bug, p0, area/backends
