### ISSUE TITLE
Pulumi Up fails with Go error and EOF on Azure Provider

### ISSUE THREAD

**Issue by thorpgeek** [pulumi/pulumi#6093] opened 2021-01-12 14:56 UTC
Trying to run pulumi up on pulumi project on windows environment, Started to get Go error and EOF on Azure provider. remove and install pulumi to see if resolved no luck.

## Expected Behavior
Running a Pulumi Up without error

## Current Behavior
Running a Pulumi Up/Preview get the following error

```
   Exception 0xc0000005 0x0 0x7fffb74b0fff 0x1bef8280000
    PC=0x1bef8280000
    syscall.loadsystemlibrary(0xc00004a3e0, 0xc000048380, 0xc000048380, 0x20)
        /opt/hostedtoolcache/go/1.15.6/x64/src/runtime/syscall_windows.go:136 +0xe7
    syscall.LoadDLL(0x5f6f063, 0xb, 0xc000062000, 0xc000058000, 0xc000553b50)
        /opt/hostedtoolcache/go/1.15.6/x64/src/syscall/dll_windows.go:81 +0x16a
    syscall.(*LazyDLL).Load(0xc000098160, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.6/x64/src/syscall/dll_windows.go:245 +0xc8
    syscall.(*LazyProc).Find(0xc00008bbf0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.6/x64/src/syscall/dll_windows.go:300 +0xbf
    syscall.(*LazyProc).mustFind(...)
        /opt/hostedtoolcache/go/1.15.6/x64/src/syscall/dll_windows.go:318
    syscall.(*LazyProc).Addr(...)
        /opt/hostedtoolcache/go/1.15.6/x64/src/syscall/dll_windows.go:327
    syscall.GetUserProfileDirectory(0x1a8, 0xc00033c4e0, 0xc000553c30, 0xc00033c4e0, 0x1bed28d6940)
        /opt/hostedtoolcache/go/1.15.6/x64/src/syscall/zsyscall_windows.go:1910 +0x3e
    syscall.Token.GetUserProfileDirectory(0x1a8, 0xc000048340, 0x32, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.6/x64/src/syscall/security_windows.go:368 +0x8f
    os/user.current(0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.6/x64/src/os/user/lookup_windows.go:217 +0x1c7
    os/user.Current.func1()
        /opt/hostedtoolcache/go/1.15.6/x64/src/os/user/lookup.go:15 +0x29
    sync.(*Once).doSlow(0x9e650a0, 0x6160c88)
        /opt/hostedtoolcache/go/1.15.6/x64/src/sync/once.go:66 +0xf7
    sync.(*Once).Do(...)
        /opt/hostedtoolcache/go/1.15.6/x64/src/sync/once.go:57
    os/user.Current(0xc00004c150, 0xc, 0x5f5c8d5)
        /opt/hostedtoolcache/go/1.15.6/x64/src/os/user/lookup.go:15 +0x105
    github.com/golang/glog.init.1()
        /home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog_file.go:63 +0x4b
    goroutine 19 [select]:
    go.opencensus.io/stats/view.(*worker).start(0xc00012c900)
        /home/runner/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0x107
    created by go.opencensus.io/stats/view.init.0
        /home/runner/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x72
    goroutine 8 [chan receive]:
    github.com/golang/glog.(*loggingT).flushDaemon(0x9e65b20)
        /home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x92
    created by github.com/golang/glog.init.0
        /home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x27a
    rax     0x7fffb409ce56
    rbx     0x7fffb409ce54
    rcx     0x41
    rdi     0xffffffffffbadd11
    rsi     0x0
    rbp     0x1bed28e6900
    rsp     0xb90d1ff0c0
    r8      0x0
    r9      0x0
    r10     0x0
    r11     0x94b
    r12     0x7fffb72c0000
    r13     0x0
    r14     0x7fffb409ce56
    r15     0xc000007a
    rip     0x1bef8280000
    rflags  0x10206
    cs      0x33
    fs      0x53
    gs      0x2b
```

## Steps to Reproduce
1. Install pulumi
2. Go to directory of pre-existing pulumi stack 
3. Pulumi up

## Context (Environment)
How has this issue affected you?
Change from Windows to WSL environment to carry on working

Windows 2004
Pulumi 2.17.0
Dotnet SDK
Pulumi.Azure 3.40.0 and 3.41.1

**Comment by viveklak** [comment] 2021-02-03 19:41
Thanks for opening the issue @thorpgeek!
I tried reproducing this on a AWS windows Workspace as well as a Windows 10 VM with pulumi 2.19.0 and the pulumi-azure 3.41.1 dotnet SDK. I haven't been able to get it to panic as yet.

How easily/frequently does this occur? Does it happen more frequently on specific programs? Anything more you can share on being able to reproduce this would be great!

**Comment by viveklak** [comment] 2021-02-04 01:18
So we have tried to repro this multiple ways across different machines and environments and no luck. I wonder if you have a particular antivirus installed? Specifically - seems like something similar triggered for the mongodb driver as well and was caused by webroot? See https://github.com/golang/go/issues/41492

**Comment by viveklak** [comment] 2021-02-04 20:20
I believe this issue is caused by an antivirus or system setting misbehaving for code compiled with Address Space Location Randomization (ASLR). Starting in Sept. 2020 we switched our build system to use Go 1.15 which enabled ASLR support by default: https://golang.org/doc/go1.15#windows. All our resent providers and binaries are now built with ASLR support. Another user mentioned the same issue reported on this ticket occurring for provider binaries built starting Sept. 2020, while switching to pulumi-azure provider version `3.16.0` seems to work fine (built Aug. 2020 on Go 1.14.x). 

Given the above, and the similar issue hitting mongodb go driver (https://github.com/golang/go/issues/41492) and known incompatibility with antivirus such as webroot with ASLR enabled binaries (https://github.com/golang/go/issues/41138) - this looks like an issue with an antivirus software running on the system. I will close this for now but please reopen if you are seeing the same behavior without webroot or another antivirus.

**Closed by viveklak** 2021-02-04 20:20 UTC
Labels: kind/panic, priority/P1

**Comment by dnadle** [comment] 2021-02-06 05:07
Webroot is a legitimate application to run on a Windows machine. I don't think "uninstall Webroot" is a good resolution to this bug.
