### ISSUE TITLE
Preview of resources to be replaced/destroyed fails to show diff

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi#6226] opened 2021-01-30 11:44 UTC
When running a `pulumi preview` or `pulumi preview --diff`, the CLI can fail if a resource is protected and a replacement/deletion is required without showing the diff, hence hiding the reason for resource deletion. This is especially problematic during imports as resources are not yet in code and automatically protected. 

## Expected Behavior
Error, but still show the diff that explains why the resource needs to be deleted

## Current Behavior
Error and no explanation: `Preview failed: refusing to delete protected resource 'urn:pulumi:production::TvShowRss::azure-nextgen:resources/latest:ResourceGroup::resourceGroup'`

## Steps to Reproduce
1. Import/create a resource with protected flag
2. Add code in the Pulumi project to reflect that resource, but have any property that force a replacement changed
3. Error with no explanation on which one is the property that causes replacement

## Context (Environment)
Using Pulumi 2.18.2 and AzureNextGen provider 0.5.1 (although I believe that may apply to any provider)
Running on Linux 64bit

Thank you

**Comment by leezen** [comment] 2021-02-23 18:11
I believe this is a dupe of https://github.com/pulumi/pulumi/issues/5749

**Closed by leezen** 2021-02-23 18:11 UTC
Labels: resolution/duplicate
