### ISSUE TITLE
"pulumi destroy" left resources around and now panics.

### ISSUE THREAD

**Issue by mpp-oliverh** [pulumi/pulumi#1984] opened 2018-09-25 08:38 UTC
I had an azure k8 stack and when I `pulumi destroy`ed it it didn't delete the primary resource group.

If i do `up`/`up -r`/`destroy`/`destroy -r` I get the following:

```
Diagnostics:
  pulumi:pulumi:Stack: Babylon-4
    info: panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x0 pc=0x128929d]
    goroutine 13 [running]:
    github.com/pulumi/pulumi-kubernetes/pkg/provider.checkpointObject(0xc042004148, 0x0, 0xc042232580)
        /home/travis/gopath/src/github.com/pulumi/pulumi-kubernetes/pkg/provider/provider.go:731 +0x2d
    github.com/pulumi/pulumi-kubernetes/pkg/provider.(*kubeProvider).Read(0xc0420c8150, 0x1f57400, 0xc0422cf470, 0xc0422a21e0,
0xc0420c8150, 0x1, 0x1)
```

**Comment by hausdorff** [comment] 2018-09-25 17:35
Ah, ok, I'm able to reproduce this in the following way.

* `pulumi up` some Kubernetes app on cluster 1.
* Switch to some cluster 2 that does not exist. For example, if you have minikube, but have run `minikube stop`, you could do something `kubectl config use-context minikube`.
* `pulumi destroy -r --yes` panics in the way above because the master is unavailable, and this error is neither a 404 nor an `await.InitializationError`.

**Comment by hausdorff** [comment] 2018-09-25 17:45
Ok, this issue will be resolved in https://github.com/pulumi/pulumi-kubernetes/pull/221. Thanks for your patience. :)

**Closed** 2018-09-26 05:35 UTC
Labels: area/kubernetes, kind/bug
