### ISSUE TITLE
Consider allowing `pulumi plugin install resource aws` without specifying a version

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5726] opened 2020-11-10 18:14 UTC
Right now when running `pulumi plugin install resource <foo> <version>` you are required to specify a version. But what version should be used? You have to go figure out what a valid version is. We should make it so you can leave off the version to get the latest version.

**Comment by Frassle** [comment] 2022-03-11 09:50
Duplicate of https://github.com/pulumi/pulumi/issues/9001

**Closed by Frassle** 2022-03-11 09:50 UTC
Labels: kind/enhancement, impact/usability, area/providers, resolution/duplicate
