### ISSUE TITLE
Pulumi stack rm does not abide by the confirmation dialog

### ISSUE THREAD

**Issue by eshamay** [pulumi/pulumi#2194] opened 2018-11-12 22:21 UTC
My stack was deleted even though I didn't type the correct confirmation

```
[1006][eks-cluster]$ pulumi stack select poc
[1007][eks-cluster]$ pulumi stack rm
This will permanently remove the 'poc' stack!
Please confirm that this is what you'd like to do by typing ("poc"): podc
Stack 'poc' has been removed!
```

**Comment by ellismg** [comment] 2018-11-12 23:01
Yikes!  Sorry that happened!

I'm having problems reproducing this issue, can you let me know what version of `pulumi` you are running (`pulumi version` will tell you).

I tried the same thing on my local machine and it failed as expected:

```
[matell@matell tmp.FU1r1i0DhH]$ pulumi version
v0.16.2
[matell@matell tmp.FU1r1i0DhH]$ pulumi stack rm
This will permanently remove the 'poc' stack!
Please confirm that this is what you'd like to do by typing ("poc"): pocd
error: confirmation declined
```

**Comment by eshamay** [comment] 2018-11-13 00:30
```
$ pulumi version
v0.16.2
```

**Comment by ellismg** [comment] 2018-11-13 17:46
Thanks @eshamay.  Can you tell me what platform you're on and if you use a special shell or terminal emulator?  Reading the code I'm having a hard time understanding how this could have happened.  It looks like when we read the string "pocd" which you typed in, we must have read it incorrectly, but it's going to be hard for me to debug this unless I can reproduce this locally.

**Comment by ellismg** [comment] 2018-11-16 00:30
@eshamay After more testing and code inspection I'm still unable to reproduce this issue or understand how we might have gotten into this state, so I'm going to close it for now. If you can give me some more details about your setup, I will try to reproduce it again and if I can, fix it.

**Closed by ellismg** 2018-11-16 00:30 UTC
Labels: area/cli, kind/bug, priority/P1
