### ISSUE TITLE
 Api to get current organization from context programmatically

### ISSUE THREAD

**Issue by amichel** [pulumi/pulumi#4365] opened 2020-04-10 18:53 UTC
Api is missing to get current organization from context programmatically, similar to pulumi.getProject() and pulumi.getStack() methods.
e.g. we need this for tagging and to create a StackReference()

**Comment by nesl247** [comment] 2020-04-10 19:02
Duplicate of #2800 I think

**Comment by amichel** [comment] 2020-04-11 05:18
I'm closing this as duplicate then

**Closed** 2020-04-11 05:17 UTC
Labels: resolution/duplicate
