### ISSUE TITLE
Poor feedback from `up` if compilation error

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#4181] opened 2020-03-25 22:13 UTC
#### Problem

If my Go Pulumi application has a syntax/compilation error, then `pulumi up` fails with an error, but the error is not informative or helpful about the actual error.

#### Suggestion

Provide the actual error message to the user.

#### Current output

```
% pulumi up         
Previewing update (dev):
 
error: failed to discover plugin requirements: failed to execute program cmd: exit status 2
```

#### Code to reproduce

```golang
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/go/aws/ec2"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		ec2.NewVpc(ctx, "main", &ec2.VpcArgs{
			CidrBlock: pulumi.String("10.0.0.0/16") // missing comma
		})
		return nil
	})
}
```

**Comment by lukehoban** [comment] 2020-03-25 22:18
Dupe of https://github.com/pulumi/pulumi/issues/4139 which is fixed but not released.

**Closed by lukehoban** 2020-03-25 22:18 UTC
Labels: language/go
