### ISSUE TITLE
`up` after empty `refresh` wants to replace a cluster

### ISSUE THREAD

**Issue by jeffijoe** [pulumi/pulumi#2739] opened 2019-05-17 11:52 UTC
Been playing around with Pulumi for a bit and ran into something scary.

Running `up` didn't want to change anything. Just to see what would happen, I run `pulumi refresh` and get the following (TLDR: no change, as expected).

```
Previewing refresh (pancakes-infrastructure-production):

     Type                             Name                                                          Plan
     pulumi:pulumi:Stack              pancakes-infrastructure-pancakes-infrastructure-production
     ├─ pulumi:pulumi:StackReference  pancakes-identity-production
     ├─ random:index:RandomString     password
     ├─ gcp:compute:Network           production
     ├─ gcp:compute:Subnetwork        production
     └─ gcp:container:Cluster         production

Resources:
    6 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be. yes
Refreshing (pancakes-infrastructure-production):

     Type                             Name                                                          Status
     pulumi:pulumi:Stack              pancakes-infrastructure-pancakes-infrastructure-production
     ├─ pulumi:pulumi:StackReference  pancakes-identity-production
     ├─ gcp:compute:Network           production
     ├─ random:index:RandomString     password
     ├─ gcp:compute:Subnetwork        production
     └─ gcp:container:Cluster         production

Outputs:
    masterPassword: "[secret]"
    region        : "us-east1"

Resources:
    6 unchanged

Duration: 3s
```

Then I run `pulumi up` *right after*, and it wants to replace my Cluster:

```
Previewing update (pancakes-infrastructure-production):

     Type                             Name                                                          Plan        Info
     pulumi:pulumi:Stack              pancakes-infrastructure-pancakes-infrastructure-production
 >   ├─ pulumi:pulumi:StackReference  pancakes-identity-production                                 read
 +-  ├─ gcp:container:Cluster         production                                                    replace     [diff: -additionalZones,addonsConfig,clusterAutoscaling,clusterIpv4C
 +   ├─ pulumi:providers:kubernetes   production                                                    create
 +   ├─ kubernetes:apps:Deployment    hello-kubernetes                                              create
 +   └─ kubernetes:core:Service       hello-kubernetes                                              create
```

Here's the relevant bits of my `index.ts`:

```ts
const name = config.envName;

/**
 * Grabs the region from the zone name.
 *
 * Me gusta TypeScript.
 */
export const region = config.region;

// The master password for the K8S cluster.
export const masterPassword = pulumi.secret(
  new random.RandomString("password", {
    length: 16,
    special: true
  }).result
);

// Default values for constructing the `Cluster` object.
const defaultClusterOptions = {
  nodeCount: 1,
  nodeVersion: "latest",
  nodeMachineType: "n1-standard-1",

  minMasterVersion: "latest",
  masterUsername: "admin",
  masterPassword
};

// Not gonna lie I have no idea what this networking shenanigans is about.
const network = new gcp.compute.Network(name, {
  project: config.project,
  autoCreateSubnetworks: false
});

const subnet = new gcp.compute.Subnetwork(name, {
  project: config.project,
  region,
  ipCidrRange: "10.0.0.0/24",
  network: network.name,
  secondaryIpRanges: [{ rangeName: "pods", ipCidrRange: "10.1.0.0/16" }]
});

const cluster = new gcp.container.Cluster(name, {
  project: config.project,
  region,
  initialNodeCount: config.nodeCount || defaultClusterOptions.nodeCount,
  nodeVersion: defaultClusterOptions.nodeVersion,
  minMasterVersion: defaultClusterOptions.minMasterVersion,
  masterAuth: {
    username: defaultClusterOptions.masterUsername,
    password: defaultClusterOptions.masterPassword
  },
  network: network.name,
  subnetwork: subnet.name,
  nodeConfig: {
    machineType:
      config.nodeMachineType || defaultClusterOptions.nodeMachineType,
    oauthScopes: [
      "https://www.googleapis.com/auth/compute",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring"
    ]
  }
});
```

**Comment by lukehoban** [comment] 2019-05-17 13:48
Just out of curiosity, are you using the latest release of `@pulumi/gcp`?  I know there was at least one bug in the upstream Terraform provider that was causing this to happen which was fixed and incorporated in recently.

**Comment by jeffijoe** [comment] 2019-05-17 13:49
I did a `yarn upgrade-interactive --latest` and everything was up to date.

**Comment by lukehoban** [comment] 2019-05-17 13:51
Cross referencing https://github.com/pulumi/pulumi-gcp/issues/88#issuecomment-483930091 which has details on similar issues.

**Comment by lukehoban** [comment] 2019-05-31 06:38
Looking at verbose logs, I see ` #replaces=[masterAuth]` indicating that it is a change in the `masterAuth` property that is triggering the replacement.

The values for that property in `olds` and `news` are:

```
I0530 23:23:21.594179   18669 rpc.go:69] Marshaling property for RPC[Provider[gcp, 0xc000487200].Diff(urn:pulumi:dev::pulumi2739::gcp:container/cluster:Cluster::foobarbaz,foobarbaz-be9eb33).olds]: masterAuth={map[clientCertificate:{} clientCertificateConfig:{map[issueClientCertificate:{false}]} clientKey:{} clusterCaCertificate:{LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU1MT0thT0xnRWpLa3p1bjVRUFlCeHN3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1lUYzJaREF4T1dNdFlXUTFNaTAwWkdJM0xUazBNRGt0WldZMVpEQmtOakpsTWprMQpNQjRYRFRFNU1EVXpNVEF6TXprd05Gb1hEVEkwTURVeU9UQTBNemt3TkZvd0x6RXRNQ3NHQTFVRUF4TWtZVGMyClpEQXhPV010WVdRMU1pMDBaR0kzTFRrME1Ea3RaV1kxWkRCa05qSmxNamsxTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcmVvMWY1c04rcUJtMjJUQzNKU0xLajBNV0kralRJUVY2VC8yUEhRNQpna0hqazd0M3ExK1dCNU5PTXpjWDIwUWNJMDhVRzA1aWFKeGhxM3RJY1ZNUzFQVkY5dkZSQXNtS2o3UXliY0xDCkIvUFUrRnVUdFRxVVZlTW0waUhJb2g1OTZOYVNMaTI2NC8rbFQ0SkF1dXgxaHpLZUxVdEU2SkNyN1Job1FvcjEKTllmSUJ2U05UM2V1ejhnSTlvOHBlSDl2RFhVcjNhZ2wrcUNNVVB5alZzV2NDVFdUaDBFNlg5M2U0R0VXMXhOUgoyN1hMS1BhZTBuODg1YzB6b1c5U2IrWFZRTWhYNm9oUDFPNHRkMmtXQkdMMEc4VUV1MEIyei81QXdwZWdxV2EvClJId28ydXY5YVVXdWZXWml4Y1NwTUx2QWNpWTJrU2dndWJ3SDhRNS9CSkpPeVFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQppL05JbUdya0pDNG9FTTFXSHBDM2gwWlphOEJvVEgrM0IzN25hdVRlLzVzOEhJVTkxYnYzMXlvcVQxQWFJSWRXCk5ibkhlYTEzYm5ZUzZRc2NydFIzeHB3eWVxZmcrYzVZdE1BRWJub2E2QUE0TGNPd1RVdFFuTUliZ3h2Zm9NL0IKUGZJVHlqYkEzL2xQUHZDWW92cXlySWViRVdFZGZJc0xZeFBUN000Z0dmdnJEWjlwYnI2VzEzajRYa0V2UWxoagpjQlYrTzVXbFdFZzg4YzVyRVZBNTVUbFBma3lraGdCNGZiNlJvOWNzanl2TDFMc0FVbkp6ai83L3QrU3IwTk9XCjh0WDlFd0lza1N5dkJqWFFweEppRDV5azBndnpwQVQ5T054eGxtT3daOG9HS2o2eEFXMHN1aHFPRGNmM2QwTVUKTEpjVml5T2IrV1oxVE9qb0dUNXYwQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K} password:{{{1Nw>e::$qJQ>e+9m}}} username:{admin}]}

I0530 23:23:21.594730   18669 rpc.go:69] Marshaling property for RPC[Provider[gcp, 0xc000487200].Diff(urn:pulumi:dev::pulumi2739::gcp:container/cluster:Cluster::foobarbaz,foobarbaz-be9eb33).news]: masterAuth={map[__defaults:{[]} password:{{{1Nw>e::$qJQ>e+9m}}} username:{admin}]}
```

Looking at the terraform provider schema, the only `ForceNew` property in `masterAuth` is `clientCertificateConfig`, which we see getting added above.

This appears to be the standard issue where the Terraform provider `Read` sets a `ForceNew` and not `Computed` property, which forces replacements after refreshes.

cc @pgavlin to take a deeper look.

**Comment by lukehoban** [comment] 2019-05-31 16:52
@pat pointed me at https://github.com/terraform-providers/terraform-provider-google/issues/3369#issuecomment-487226330, which notes that this is a bug in the Terraform GCP provider.  There appears to be a fix in the works in https://github.com/GoogleCloudPlatform/magic-modules/pull/1855.  I'll close this out as effectively a dupe of that issue.

**Closed by lukehoban** 2019-05-31 16:52 UTC
