### ISSUE TITLE
pulumi up --target errors on code not related to the resource(s) being targeted

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#11563] opened 2022-12-06 17:34 UTC
### What happened?

Used `pulumi up --target` to update specific resources but other resource declarations that are NOT currently part of the stack (but part of the project) and are NOT targeted by the `pulumi up --target` are being validated on the up and failing due to missing resource output properties.

### Steps to reproduce

1. Using the code provided below, with the comments in place, run `pulumi up`
2. This will create a small stack with just the `mitch-sa-pre` service account created.
3. Run `pulumi stack export |grep urn |grep pre` to get the URN for the service account.
4. Uncomment all the commented lines in the code provided
5. Run `pulumi up --target URN_FROM_STEP_3`
    e.g. `pulumi up --target "urn:pulumi:dev::gcp-iam::gcp:serviceAccount/account:Account::mitch-sa-pre"`
6. The preview step will appear to be fine.
7. Select `y` to allow the update to run
8. See error related to resources not being targeted by the `pulumi up --target` command.
```
Diagnostics:
  gcp:serviceAccount:IAMMember (mitch-iam):
    error: gcp:serviceAccount/iAMMember:IAMMember resource 'mitch-iam' has a problem: "service_account_id" ("") doesn't match regexp "projects/(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?)|-)/serviceAccounts/((?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))@[a-z]+.gserviceaccount.com$|[0-9]{1,20}-compute@developer.gserviceaccount.com|[a-z](?:[-a-z0-9]{4,28}[a-z0-9])@[-a-z0-9\\.]{1,63}\\.iam\\.gserviceaccount\\.com$)". Examine values at 'IAMMember.ServiceAccountId'.
```

----- REPRO CODE -----
```
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/serviceaccount"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	// "fmt"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		saResourceName := "mitch-sa-pre"
		saName := "mitch-sa-pre"
		sapre, err := serviceaccount.NewAccount(ctx, saResourceName, &serviceaccount.AccountArgs{
			AccountId: pulumi.String(saName),
		})
		if err != nil {
			return err
		}

		ctx.Export("sapre", sapre.Name)

		// saResourceName = "mitch-sa"
		// saName = "mitch-sa"
		// sa, err := serviceaccount.NewAccount(ctx, saResourceName, &serviceaccount.AccountArgs{
		// 	AccountId: pulumi.String(saName),
		// })
		// if err != nil {
		// 	return err
		// }
	
		// iamResourceName := "mitch-iam"
		// saiam, err := serviceaccount.NewIAMMember(ctx, iamResourceName, &serviceaccount.IAMMemberArgs{
		// 		ServiceAccountId: sa.Name,
		// 		Member: sa.Email.ApplyT(func(email string) (string, error) {
		// 			return fmt.Sprintf("serviceAccount:%v", email), nil
		// 			}).(pulumi.StringOutput),
		// 		Role:   pulumi.String("roles/iam.serviceAccountTokenCreator"),
		// 	})
		// if err != nil {
		// 	return err
		// }

		// ctx.Export("role", saiam.Role)
		// ctx.Export("member", saiam.Member)
		// ctx.Export("saName", saiam.ServiceAccountId)

		return nil
	})
}
```

### Expected Behavior

The `pulumi up --target` command should ignore other resources in the stack and not throw the error.

### Actual Behavior

Throws error about empty strings related to resources not being targeted and not part of the current stack.

### Output of `pulumi about`

CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME  VERSION
gcp   6.41.0
go    unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in go: executable='/usr/local/bin/go' version='go version go1.18.4 darwin/amd64'

Current Stack: dev

TYPE                                URN
pulumi:pulumi:Stack                 urn:pulumi:dev::gcp-iam::pulumi:pulumi:Stack::gcp-iam-dev
pulumi:providers:gcp                urn:pulumi:dev::gcp-iam::pulumi:providers:gcp::default
gcp:serviceAccount/account:Account  urn:pulumi:dev::gcp-iam::gcp:serviceAccount/account:Account::mitch-sa-pre

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-gcp/sdk/v6  6.41.0
github.com/pulumi/pulumi/sdk/v3      3.44.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment] 2022-12-06 18:46
@MitchellGerdisch looks like this is a known issue https://github.com/pulumi/pulumi/issues/9869. There was originally a fix attempted but caused a regression in `v3.35.2` so was reverted in `v3.35.3`.

Going to close this as a duplicate if no objections

**Closed** 2022-12-06 18:46 UTC
Labels: kind/bug, resolution/duplicate
