### ISSUE TITLE
Dry-run/fake import of resource

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi#11770] opened 2023-01-04 20:01 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be nice, to have the option in the command `pulumi import` to run it in a `dry-run/fake` mode just for the code-generation side.

This was requested from customers to recreate the resource in code.

### Affected area/feature

- CLI

**Comment by Frassle** [comment] 2023-01-04 20:06
Duplicate of https://github.com/pulumi/pulumi/issues/8836

**Closed by Frassle** 2023-01-04 20:06 UTC
Labels: kind/enhancement, resolution/duplicate, area/import
