### ISSUE TITLE
Golang: isTaggable function not implemented

### ISSUE THREAD

**Issue by universam1** [pulumi/pulumi#7034] opened 2021-05-12 14:08 UTC
This tutorial https://www.pulumi.com/blog/automatically-enforcing-aws-resource-tagging-policies/#automatically-applying-tags 
does not build, the function `isTaggable` is not existing?

## Expected behavior
to be working as described

## Current behavior
not existing function

## Steps to reproduce
following this blog https://www.pulumi.com/blog/automatically-enforcing-aws-resource-tagging-policies/#automatically-applying-tags in Golang

## Affected feature

Automatic tagging is not possible

**Comment by stack72** [comment] 2021-05-12 14:48
Hi @universam1 

So the code in this actually points to the following repo

https://github.com/joeduffy/aws-tags-example

and you can see the isTaggable code in the go based example here - blob/master/autotag-go/taggable.go

isTaggable isn't anything built into Pulumi directly

I hope this helps?

Paul

**Comment by universam1** [comment] 2021-05-12 15:36
Thank you @stack72 

Indeed this helps incredibly :smile: 

Without your hint I would have no idea where to look for this routines. Did I miss something? Would it make sense to add a ref to the blog? If so I'll keep the issue open for reference.

Thanks again for the prompt support, appreciated!

**Comment by stack72** [comment] 2021-05-12 17:45
So there are plans - in another issue - to make this a library available in the pulumi-aws go sdk - https://github.com/pulumi/pulumi-aws/issues/1134

I am going to close this one as a duplicate of that and we will have a link between them

Let me know if you have any other issues here

Paul

**Closed by stack72** 2021-05-12 17:45 UTC
Labels: resolution/duplicate
