### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2835] opened 2019-06-17 16:34 UTC
A few specific things:
- [ ] Specific versions of dependencies (presumably kept up-to-date with https://github.com/pulumi/scripts/blob/master/ci/install-common-toolchain.sh)
- [ ] Clarity that sources must be in `$GO_HOME`

**Comment by pgavlin** [comment] 2019-11-06 17:49
Closing this as a dupe of https://github.com/pulumi/pulumi/issues/1559

**Closed by pgavlin** 2019-11-06 17:49 UTC
