### ISSUE TITLE
`pulumi up` fails when using custom plugin provider since v3.104.0

### ISSUE THREAD

**Issue by johnmoarr** [pulumi/pulumi#15467] opened 2024-02-19 15:24 UTC
### What happened?

We are using a custom plugin provider which is re-used in different pulumi projects. This worked flawlessly ever since until updating to v3.104.0 or beyond.

Our pulumi code is written in C#.

The project structure is as follows:

Pulumi/
├─ deployment.sln
├─ internalprovider/
│   ├─ InternalProvider.csproj
│   ├─ PulumiPlugin.yaml
│   ├─ ...
├─ deployment_proj1/
│   ├─ deployment_proj1.csproj
│   ├─ Pulumi.yaml
│   ├─ ...
├─ deployment_proj2/
│   ├─ deployment_proj2.csproj
│   ├─ Pulumi.yaml
│   ├─ ...

_deployment_proj1_ and _deployment_proj2_ both depend on _internalprovider_ (which containts out custom resources).

Pulumi.yaml of _deployment_proj1_ for example looks like this:
```yaml
# Pulumi.yaml
name: deployment_proj1
runtime: dotnet
description: Deployment of the infrastructure
plugins:
  providers:
    - name: internalprovider
      path: ../internalprovider
```

From v3.104.0, `pulumi up` fails with the following error:

```console
panic: rootDirectory '..\internalprovider' is not a valid path when creating ProgramInfo

goroutine 218 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.NewProgramInfo({0xc0023ff540, 0x13}, {0xc0023ff540, 0x13}, {0x30621b0, 0x1}, 0x0)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/langruntime.go:49 +0x2a8
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.execPlugin(0xc00202ce60, {0xc0023ff540, 0x38}, {0xc0018adb00, 0x1b}, {0x271dd6a, 0x8}, {0xc002746af0, 0x1, 0x1}, ...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/plugin.go:349 +0x556
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.newPlugin(0xc00202ce60, {0xc001367d10, 0x48}, {0xc0023ff540, 0x38}, {0xc0018adb00, 0x1b}, {0x271dd6a, 0x8}, {0xc002746af0, ...}, ...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/plugin.go:201 +0x4b0
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.NewProvider({0x30b2cb8, 0xc0024abd40}, 0xc00202ce60, {0xc002c8341b, 0x10}, 0x0, 0x0, 0x0, {0xc002673b5f, 0x2})
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/provider_plugin.go:148 +0x825
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).Provider.func1()
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:371 +0x2b3
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).loadPlugin.func1()
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:282 +0x1f
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.NewDefaultHost.func1()
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:151 +0x3d
created by github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.NewDefaultHost in goroutine 1
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:149 +0x2e5
```

We were able to track the issue down to this commit: #15191 introducing the re-usage of the `ProgramInfo-struct`, and to these lines: [commit bd4e50efdd9844a2e9593bb382d3d732db169194](https://github.com/pulumi/pulumi/commit/bd4e50efdd9844a2e9593bb382d3d732db169194#diff-c6f93f65caec6acbca1fe08b431cb167455b61d66f37491a712aa378ff7f51d4R41-R43).

The `isValidPath`-function is calling filepath.IsLocal(), which again is checking for a `..\`-prefix (see [golang filepath.isLocal()](https://github.com/golang/go/blob/5c92f43c51e9313504ff86bec9b0cd0e5eb1c1bc/src/path/filepath/path_windows.go#L52-L54)).

@Zaid-Ajaj is it really necessary to do a `isLocal()`-Check here or can the path be verified in a different way, still allowing a relative path that is pointing to a parent directory? What's the purpose of this restriction here?

### Example

Minimal repro-repo can be provided if the problem is not described clearly enough.

### Output of `pulumi about`

CLI
Version      3.106.0
Go Version   go1.22.0
Go Compiler  gc

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19045 Build 19045
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-02-19 17:00
I think the `NewProgramInfo` checks are correct, the issue is `getPluginInfoAndPath` not resolving the relative paths for a project plugin before handing it off to the rest of the system.

**Comment by johnmoarr** [comment] 2024-02-20 06:28
I updated the _Pulumi.yaml_-sample since there was a typo (_./internalprovider_ instead of _../internalprovider_ like in the errormessage).

What I can also tell is, that `pulumi up` is still working with v3.104.0 (or greater) when putting an absolute path to the _internalprovider_-folder into the _Pulumi.yaml_ instead of a relative path.

**Closed** 2024-02-22 12:55 UTC
Labels: kind/bug, impact/regression, area/plugins
