### ISSUE TITLE
Destroy does not download plugins

### ISSUE THREAD

**Issue by chainlink** [pulumi/pulumi#8768] opened 2022-01-14 20:15 UTC
## Issue details

When I try running `destroy` the necessary plugins are not downloaded (Running `up` downloads plugins and succeeds) 

Error message:

```
stderr: error: could not load plugin for kubernetes provider 'urn:pulumi:pulumi-preview::jupyter-test::pulumi:providers:kubernetes::k8sprovider': no resource plugin 'kubernetes' found in the workspace or on your $PATH
```
### Steps to reproduce

Github action setup:
```
jobs:
  up:
    name: remove-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
         with:
           go-version: '^1.17.2'
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: blah
          work-dir: infra
```

Expected: Destroy to run sucessfully
Actual: Destroy failed with above error

**Comment by lukehoban** [comment] 2022-01-18 19:08
FWIW - this is also what https://github.com/pulumi/pulumi/issues/5619 was tracking, it sounds like the issue described there is perhaps unique to "destroy" operations, which might be why it was not reproduced during investigation?

**Comment by dixler** [comment] 2022-01-24 17:51
@mikhailshilkov do you have CLI repro steps?

**Note**: I'm on a linux machine if there is any weirdness

I tried:
- bringing up a stack from [examples](https://github.com/pulumi/examples/blob/master/kubernetes-ts-exposed-deployment/)
- deleting the `~/.pulumi/plugins` directory
- running destroy.

```
kdixler@kdixler-20xw004aus ..mples/kubernetes-ts-exposed-deployment (git)-[master] % ~/.pulumi/bin/pulumi version
v3.22.1
kdixler@kdixler-20xw004aus ..mples/kubernetes-ts-exposed-deployment (git)-[master] % pulumi up --yes; rm -rf ~/.pulumi/plugins; pulumi destroy --yes
Please choose a stack, or create a new one: issue8768
Previewing update (issue8768)

View Live: https://app.pulumi.com/kyle/exposed-deployment/issue8768/previews/df073e10-b8db-4db1-a181-a8d96d550f8c

     Type                              Name                          Plan       
 +   pulumi:pulumi:Stack               exposed-deployment-issue8768  create     
 +   ├─ kubernetes:apps/v1:Deployment  nginx                         create     
 +   └─ kubernetes:core/v1:Service     nginx                         create     
 
Resources:
    + 3 to create

Updating (issue8768)

View Live: https://app.pulumi.com/kyle/exposed-deployment/issue8768/updates/9

     Type                              Name                          Status      
 +   pulumi:pulumi:Stack               exposed-deployment-issue8768  created     
 +   ├─ kubernetes:apps/v1:Deployment  nginx                         created     
 +   └─ kubernetes:core/v1:Service     nginx                         created     
 
Outputs:
    frontendIp: "10.103.229.171"

Resources:
    + 3 created

Duration: 14s

Please choose a stack: issue8768
Previewing destroy (issue8768)

View Live: https://app.pulumi.com/kyle/exposed-deployment/issue8768/previews/84dafa29-9040-4f56-bbf8-318f9b44fc15

[resource plugin kubernetes-3.14.1] installing
Downloading plugin: 30.18 MiB / 30.18 MiB [=========================] 100.00% 8s
     Type                              Name                          Plan       
 -   pulumi:pulumi:Stack               exposed-deployment-issue8768  delete     
 -   ├─ kubernetes:core/v1:Service     nginx                         delete     
 -   └─ kubernetes:apps/v1:Deployment  nginx                         delete     
 
Outputs:
  - frontendIp: "10.103.229.171"

Resources:
    - 3 to delete

Destroying (issue8768)

View Live: https://app.pulumi.com/kyle/exposed-deployment/issue8768/updates/10

     Type                              Name                          Status      
 -   pulumi:pulumi:Stack               exposed-deployment-issue8768  deleted     
 -   ├─ kubernetes:core/v1:Service     nginx                         deleted     
 -   └─ kubernetes:apps/v1:Deployment  nginx                         deleted     
 
Outputs:
  - frontendIp: "10.103.229.171"

Resources:
    - 3 deleted

Duration: 2s

The resources in the stack have been deleted, but the history and configuration associated with the stack are still maintained. 
If you want to remove the stack completely, run 'pulumi stack rm issue8768'.
```

**Comment by mikhailshilkov** [comment] 2022-01-24 22:29
Hmm, yeah, that's what I did - I deleted all files from `~/.pulumi/plugins` (empty dir) and then ran `pulumi destroy`. It failed for me...

**Comment by mikhailshilkov** [comment] 2022-01-25 15:57
I tried again but I can't reproduce it this time. Odd. I must have done something differently or my state was somewhat different but I can't figure out what that was yet.

**Comment by dixler** [comment] 2022-01-25 23:00
Failed to repro using the pulumi/actions repo by stripping down the entrypoint. It still destroyed. This was after a couple of runs so my environment might be dirty or it may be looking somewhere else for plugins

The following test used AWS resources. The logs are commented in the gist.

https://gist.github.com/dixler/2ea418da0dab0b561f4e9e670e8c983f

**Comment by justinvp** [comment] 2023-07-27 07:39
Closing as no repro. If you're running into this, please open a new issue.

**Closed by justinvp** 2023-07-27 07:39 UTC
Labels: kind/bug, area/cli, resolution/no-repro, needs-repro
