### ISSUE TITLE
Process hanging in NodeJS Automation API as a result of .up()

### ISSUE THREAD

**Issue by robertf224** [pulumi/pulumi#13737] opened 2023-08-19 04:59 UTC
### What happened?

I'm using the automation API in a custom CLI.  My CLI (which is running `.up()`) runs to completion, but the process hangs.  I used the `why-is-node-running` and `wtfnode` packages to dig into why.  I wasn't positive it was Pulumi (there's a bunch of other things going on in this CLI), but the results I got from `wtfnode` suggest it probably is (given the `grpc-js` connection, suspecting something in [here](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/automation/stack.ts#L211-L233) isn't getting cleaned up properly).

Results from `why-is-node-running`:
```
There are 4 handle(s) keeping the process running

# TTYWRAP
node:internal/async_hooks:205
node:internal/bootstrap/switches/is_main_thread:47
node:internal/bootstrap/switches/is_main_thread:135
/Users/robertfidler/Documents/code/spine/common/temp/node_modules/.pnpm/siginfo@2.0.0/node_modules/siginfo/index.js:3                           - if (process.stderr.isTTY || force === true) {
/Users/robertfidler/Documents/code/spine/common/temp/node_modules/.pnpm/why-is-node-running@2.2.2/node_modules/why-is-node-running/include.js:3 - require('siginfo')(why, true)
node:internal/modules/cjs/loader:1101
node:internal/modules/cjs/loader:1153
node:internal/modules/cjs/loader:981

# TTYWRAP
node:internal/async_hooks:205
node:internal/bootstrap/switches/is_main_thread:47
node:internal/bootstrap/switches/is_main_thread:123
/Users/robertfidler/Documents/code/spine/common/temp/node_modules/.pnpm/colors@1.2.5/node_modules/colors/lib/system/supports-colors.js:149 - stdout: getSupportLevel(process.stdout),
node:internal/modules/cjs/loader:1101
node:internal/modules/cjs/loader:1153
node:internal/modules/cjs/loader:981
node:internal/modules/cjs/loader:822

# TTYWRAP
node:internal/async_hooks:205
node:internal/bootstrap/switches/is_main_thread:152
node:internal/bootstrap/loaders:182
node:internal/bootstrap/loaders:294
node:internal/bootstrap/loaders:274
node:internal/bootstrap/loaders:279
node:internal/bootstrap/loaders:259

# DNSCHANNEL
node:internal/async_hooks:205
node:internal/dns/utils:56
node:internal/dns/utils:141
node:internal/bootstrap/loaders:312
node:internal/bootstrap/loaders:341
node:internal/bootstrap/loaders:312
node:internal/bootstrap/loaders:252
node:internal/modules/cjs/helpers:49
```

And from `wtfnode`:
```
^C[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
  - fd 0 (tty)
- Timers:
  - (21669.84073802321 ~ 21 s) (anonymous) @ /Users/robertfidler/Documents/code/spine/common/temp/node_modules/.pnpm/@grpc+grpc-js@1.9.0/node_modules/@grpc/grpc-js/src/backoff-timeout.ts:104

  - (29588.02077831931 ~ 29 s) (anonymous) @ /Users/robertfidler/Documents/code/spine/common/temp/node_modules/.pnpm/@grpc+grpc-js@1.9.0/node_modules/@grpc/grpc-js/src/backoff-timeout.ts:104
```

I noticed when I left the CLI running for a while it did eventually exit (maybe after 10-20 minutes) which aligns with the `backoff-timeout.ts` entry here.

### Expected Behavior

For the process not to hang.

### Steps to reproduce

Don't know that I'll be able to produce a full repro (I had played around with the automation API in simple examples before and didn't notice this), but recording in case anyone else runs into this / any maintainers have any ideas!

### Output of `pulumi about`

```
CLI
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  13.5.1
Arch     x86_64

This project is written in nodejs: executable='/Users/robertfidler/.nvm/versions/node/v16.13.0/bin/node' version='v16.13.0'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2023-08-19 09:34
Probably a duplicate of https://github.com/pulumi/pulumi/issues/13687

**Comment by Zaid-Ajaj** [comment] 2023-08-19 14:01
@Frassle Yeah probably, I also used `why-is-node-running` to debug the issue and it pointed me to the internal `backoff-timeout.js` code from the gRPC-js library. @robertf224 I actually tinkered with the code from grpc-js inside `node_modules` and disabled the `backoff-timeout` instantiation from `subchannel.js` (where it was called from) but the process kept hanging anyways 😓 

The workaround was to simply call `process.exit(0);` at the end of your entry point but this is far from ideal

**Comment by robertf224** [comment] 2023-08-19 15:52
Yep that’s what I ended up doing haha

**Comment by roderik** [comment] 2023-10-27 18:02
Okay, it took me two days because our workers went to 100% CPU after an automation pulumi-up call was done. Luckily, after much searching, I had an image that still worked and a git tag on our end of all the dependencies, etc.

When I rebuilt that git tag, it still happened; when I used the old image, it worked as designed.
After 120 million different tries, finally compared the entire filesystem of the two images.

I found that there was a difference.

![CleanShot 2023-10-27 at 19 13 59@2x](https://github.com/pulumi/pulumi/assets/16780/ede74139-78d5-446d-bccc-138e3b3f1eec)

Lo and behold, a new release from a week ago when our issues started https://github.com/grpc/grpc-node/releases and an issue that looks very similar https://github.com/grpc/grpc-node/issues/2604

I stacked a bunch of resolutions where needed as a workaround

```
  "resolutions": {
    "@grpc/grpc-js": "1.9.6"
  }
```

My suggestion would be to lock the version here https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/package.json#L12 until a fix has been released.

**Comment by roderik** [comment] 2023-10-28 05:36
Renovate picked up a new version (not listed in github) with what looks like the fix: https://app.renovatebot.com/package-diff?name=@grpc/grpc-js&from=1.9.7&to=1.9.8

**Comment by jitbasemartin** [comment] 2023-12-16 01:05
I got a similar issue because I use Pulumi inside another NodeJS project

My original structure when Pulumi **hangs**:
```
.
├── node_modules/
│   └── ...
├── src/
│   ├── ...
│   └── pulumi/
│       └── workspace/
│           └── index.ts
├── package.json
└── ...
```

My new structure with the `package.json` added:

```
.
├── node_modules/
│   └── ...
├── src/
│   ├── ...
│   └── pulumi/
│       └── workspace/
│           ├── index.ts
│           └── package.json
├── package.json
└── ...
```

The added file:

```
# src/pulumi/workspace/package.json
{
  "name": "pulumi-workspace",
  "version": "1.0.0",
  "description": "Fake package.json to stop Pulumi to recursively check for parent package.json",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT"
}
```

**Comment by justinvp** [comment] 2024-09-27 18:06
Closing this as fixed. The `@pulumi/pulumi` package depends on a more recent version of `@grpc/grpc-js` which includes the upstream fix.

**Closed by justinvp** 2024-09-27 18:06 UTC
Labels: kind/bug, language/javascript, area/automation-api, resolution/fixed
