### ISSUE TITLE
'update' fails on Node 10.4.X due to missing method

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#1502] opened 2018-06-12 18:51 UTC
Note: this is likely because hte latest windows drop is v0.12.2 and things aren't up to date with all our packages.  However, when it try to do a "pulumi update" of a little toy app, i get:

```
Diagnostics:
  pulumi:pulumi:Stack: todo-cywincrawl
    error: Running program 'C:\GitHub\pulumi\pulumi-cloud\examples\crawler' failed with an unhandled exception:

    error: TypeError: script.locationFromPosition is not a function
        at Object.getFunctionLine (C:\GitHub\pulumi\pulumi-cloud\examples\crawler\node_modules\@pulumi\pulumi\runtime\closure\v8.js:107:29)
        at createFunctionInfo (C:\GitHub\pulumi\pulumi-cloud\examples\crawler\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:153:21)
        at Object.<anonymous> (C:\GitHub\pulumi\pulumi-cloud\examples\crawler\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:93:26)
        at Generator.next (<anonymous>)
        at C:\GitHub\pulumi\pulumi-cloud\examples\crawler\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:20:71
        at new Promise (<anonymous>)
        at __awaiter (C:\GitHub\pulumi\pulumi-cloud\examples\crawler\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:16:12)
        at Object.createFunctionInfoAsync (C:\GitHub\pulumi\pulumi-cloud\examples\crawler\node_modules\@pulumi\pulumi\runtime\closure\createClosure.js:56:12)
        at Object.<anonymous> (C:\GitHub\pulumi\pulumi-cloud\examples\crawler\node_modules\@pulumi\pulumi\runtime\closure\serializeClosure.js:49:44)
        at Generator.next (<anonymous>)
```

**Comment by dwdii** [comment] 2018-06-22 02:01
I'm getting the same error on Windows 10 with pulumi 0.14.0, and Node v10.5.0 using the hello-aws-javascript template (unedited).

**Comment by lukehoban** [comment] 2018-06-28 18:40
Closing this one our as a duplicate of https://github.com/pulumi/pulumi/issues/1270 since that issue covers a few more areas we'll need to look at as part of addressing this.

**Closed by lukehoban** 2018-06-28 18:40 UTC
Labels: language/javascript
