### ISSUE TITLE
Resources created inside a ComponentResource is not visible to mock monitor

### ISSUE THREAD

**Issue by JakeGinnivan** [pulumi/pulumi#5461] opened 2020-09-27 05:43 UTC
When creating a `pulumi.ComponentResource`, when `parent` is set, the child resources become invisible to the mock monitor.

## Expected Behavior
All resources which are created `new Resource` should be visible to the mock monitor even if they have a parent set

## Current Behavior
Only the top level resources which do not have a parent set to a component resource will have `newResource` called.

## Context (Environment)
I am trying to write a unit test for my lambdas created against API gateway, I want to verify that if a handler file is created the appropriate registration is made with Pulumi.

All our Pulumi programs make extensive use of ComponentResources to organise our infrastructure, it appears the unit testing features in Pulumi cannot be used when Pulumi programs are written in this way?

**Comment by thecodetinker** [comment] 2021-09-03 10:19
Is this related to / duplicate of #7822  ?

**Comment by joeduffy** [comment] 2021-12-31 17:31
I too am surprised by this behavior. Indeed, I'm surprised we took the path we did, for this reason (among others like wanting to see component inputs and properties in the service console, being available to run Policy as Code rules against, etc). Funny enough, multiple years later I guess I haven't changed my opinion on this, as I had described this same concern way back when: https://github.com/pulumi/pulumi/pull/2296#issuecomment-447709691.

The culprit here is: https://github.com/pulumi/pulumi/blob/6723272dcf4cbd25f4e26ba9cbdd2fca4daa9d30/sdk/nodejs/resource.ts#L860-L868

**Comment by joeduffy** [comment] 2021-12-31 17:36
I tried reproducing this, but I was able to mock child resources as expected. For instance, given this component:

```typescript
import * as aws from "@pulumi/aws";
import * as pulumi from "@pulumi/pulumi";

export class MegaBucket extends pulumi.ComponentResource {
    public readonly buckets: aws.s3.Bucket[];

    constructor(name: string, bucketCount: number, opts?: pulumi.ComponentResourceOptions) {
        super("mega:b:Bucket", name, { bucketCount: bucketCount }, opts);

        this.buckets = [];

        for (let i = 0; i < bucketCount; i++) {
            this.buckets.push(new aws.s3.Bucket(`${name}-${i}`, {}, { parent: this }));
        }
    }
}
```

And this mock test file:

```typescript
import "mocha";
import {setMocks, MockCallArgs, MockResourceArgs} from "@pulumi/pulumi/runtime";

setMocks({
    call: (args: MockCallArgs): any => {
        return args.inputs;
    },
    newResource: (args: MockResourceArgs): { id: string, state: any } => {
        console.log("==newResource==");
        console.log(JSON.stringify(args));
        return {
            id: args.inputs.name,
            state: args.inputs,
        };
    },
});

describe("Infra", () => {
    let megabucket: typeof import("./megabucket");

    before(async () => {
        megabucket = await import("./megabucket");
    });

    describe("#megabucket", () => {
        it("must have correct bucket count", (done) => {
            const c = 3;
            const mb = new megabucket.MegaBucket("foo", c);
            if (mb.buckets.length != c) {
                done(new Error(`Incorrect MegaBucket count; got ${mb.buckets.length}, expected ${c}`));
            } else {
                done();
            }
        });
    });
});
```

The `newResource` callback is invoked for the `MegaBucket` as well as all three child `Bucket`s.

@JakeGinnivan Do you have a more complete repro of the issue? There might be something more subtle afoot. Also, am I correct in assuming you're trying to do this in TypeScript?

**Comment by JakeGinnivan** [comment] 2021-12-31 23:46
This also maybe has just been fixed over time. Happy to close and will recreate the issue if I hit it again

**Closed** 2021-12-31 23:48 UTC
Labels: kind/bug, area/testing
