### ISSUE TITLE
Snapshot integrity failure when redeploying a Kubernetes cluster

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi#4996] opened 2020-07-13 08:23 UTC
I changed properties on an azure kubernetes cluster which required it to be redeployed, but when running the update the cluster was replaced and then I got the following error:

```
error: .pulumi\stacks\deveu.json: snapshot integrity failure; refusing to use it: resource urn:pulumi:deveu::deveu::kubernetes:yaml:ConfigFile$kubernetes:core/v1:Namespace::cert-manager refers to unknown provider urn:pulumi:deveu::deveu::pulumi:providers:kubernetes::deveu1::f2568e12-b0c3-42c3-8900-357f6d9c218b
```

The cluster was replaced but then the update immediately threw an error and wouldn't proceed until I manually edited the state file to remove all the kubernetes resources. All of these resources had "pendingReplacement: true" but referenced the old provider which had been deleted.

```
    const kubeCluster = new azure.containerservice.KubernetesCluster(args.Name, {
        name: args.ClusterArgs.name,
        resourceGroupName: args.ResourceGroup.name,
        location: args.Location,
        defaultNodePool: {
            name: args.AgentPoolProfileName,
            vmSize: args.NodeSize,
            nodeCount: args.NodeCount,
            maxPods: args.MaxPods
        },
        networkProfile: {
            loadBalancerSku: args.LoadBalancerSku,
            networkPlugin: "azure"
        },
        dnsPrefix: args.DnsPrefix,
        servicePrincipal: {
            clientId: principal.Application.applicationId,
            clientSecret: principal.ServicePrincipalPassword.value
        },
        roleBasedAccessControl: {
            enabled: true
        }
    }, {
        dependsOn: [secret, acrRole, ...dependsOn],
        protect: true,
        parent: args.Parent,
        aliases: [{ parent: pulumi.rootStackResource }],
        additionalSecretOutputs: ["kubeConfigs", "kubeConfigRaw", "kubeAdminConfigs", "kubeAdminConfigRaw"],
        ignoreChanges: ["defaultNodePool.nodeCount"]
    });

    const provider = new kubernetes.Provider(args.Name, {
        kubeconfig: kubeCluster.kubeConfigRaw
    }, {
        parent: args.Parent,
        aliases: [{ parent: pulumi.rootStackResource }]
    });

    const certManager = new kubernetes.yaml.ConfigFile(
        "cert-manager",
        { file: "https://github.com/jetstack/cert-manager/releases/download/v0.9.1/cert-manager.yaml", },
        { providers: { kubernetes: provider } }
    );
```

**Comment by ninja-** [comment] 2020-07-28 12:47
same bug after replace with EKS

**Comment by DeV1L** [comment] 2020-11-25 13:35
I have the same bug after renaming AKS cluster

**Comment by DeV1L** [comment] 2020-11-25 14:51
My error was
```
error: .pulumi\stacks\ml-cluster.json: snapshot integrity failure; refusing to use it: resource urn:pulumi:ml-cluster::ml-cluster::azure-nextgen:containerservice/latest:ManagedCluster$kubernetes:core/v1:Namespace::apps refers to unknown provider urn:pulumi:ml-cluster::ml-cluster::pulumi:providers:kubernetes::provider::4299278d-f00b-4efe-b1f1-ee7f0040b1c8
```

I did:
1. 

```
pulumi state delete "urn:pulumi:ml-cluster::ml-cluster::azure-nextgen:containerservice/latest:ManagedCluster$kubernetes:core/v1:Namespace::apps" --disable-integrity-checking
```

2.  `pulumi refresh`

3. `pulumi up`

And it helped.

**Comment by jsravn** [comment] 2021-09-22 14:32
Still an issue - it seems provider dependencies are not being respected properly? This happens on GKE too.

**Comment by jsravn** [comment] 2021-09-22 14:35
I'm guessing its a kubernetes provider bug?

**Comment by lukehoban** [comment] 2022-08-04 23:10
My guess is this is due to https://github.com/pulumi/pulumi/issues/2948.  Note that the second example in the description there is very similar to the stated cases with AKS and EKS outlined in this issue.

**Comment by defyjoy** [comment] 2022-10-12 01:13
I lost my all resources due to this bug . The entire stack got corrupted and I couldn't do anything about it nor export neither edit it . I can't even delete the urn which was causing this issue .

**Comment by lenardchristopher** [comment] 2022-11-17 13:43
This is a bug that Pulumi should fix, imo.

For now, I think understanding the bug will help anyone work around the issue safely. If you have a single stack creating a cluster and k8s resources together, then you must be configuring the k8s provider using the cluster's certs. When you recreate a cluster, the cert's change. The bug is the k8s provider doesn't pick up these new certs. It is still someone attached to old (bad) certs. When it tries to recreate the new k8s resources, it fails.

[These steps](https://github.com/pulumi/pulumi/issues/4996#issuecomment-733753536) are a workaround. You have to remove all k8s resources from the stack. After that, run again and it will work.

**Comment by Hanyman8** [comment] 2023-03-16 17:56
This is still an issue, when we are redeploying our cluster. We are using GKE.

A lot of our resources depends on the kubernetes provider and we need to delete almost all resources to recreate the cluster.

**Comment by hugbubby** [comment] 2024-07-06 02:54
Four years later, attempting to redeploy k8s resources to a new kubernetes cluster completely assrapes your entire stack and forces you to delete it and start anew

**Comment by EronWright** [comment] 2024-07-09 17:45
I have an idea for a possible workaround, it is to suppress the logic that causes the provider to be replaced when the cluster's configuration is updated. This should avoid the (premature) deletion of the old provider (#2948).  To suppress the logic, use this new feature of the Kubenetes provider:
https://github.com/pulumi/pulumi-kubernetes/pull/3068

**Comment by blampe** [comment] 2024-07-09 18:14
For anyone experiencing this issue, please include the output of running `pulumi about`. That should include your CLI version as well as the version of pulumi/kubernetes you're using, which will help us reproduce the problem.

Also a friendly reminder to please keep comments respectful and in line with our [code of conduct](https://github.com/pulumi/pulumi/blob/master/CODE-OF-CONDUCT.md).

**Comment by mausch** [comment] 2024-07-12 07:59
Just got this too:

```
error: snapshot integrity failure; refusing to use it: resource urn:pulumi:vcluster-develop::infra::kubernetes:batch/v1:Job::restore-postgres's dependency urn:pulumi:vcluster-develop::infra::kubernetes:core/v1:ConfigMap::postgres-restore-scripts refers to missing resource
```

output of `pulumi about`:

```
CLI          
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.5.0
resource  aws         5.31.0
resource  aws-native  0.97.0
resource  command     0.9.2
resource  docker      4.4.5
resource  eks         1.0.4
resource  kubernetes  4.5.4
resource  kubernetes  3.30.2
language  nodejs      unknown
resource  random      4.14.0

Host     
OS       nixos
Version  24.05 (Uakari)
Arch     x86_64

This project is written in nodejs: executable='/nix/store/ilkfhnqz4xczrliqjva8770x2svbfznd-nodejs-20.14.0/bin/node' version='v20.14.0'

Backend        
Name           RYOGA
URL            s3://elevate-pulumi-nonprod
User           mauricio
Organizations  
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/eks         1.0.4
@pulumi/kubernetes  4.5.4
js-yaml             4.1.0
tmp                 0.2.1
@pulumi/aws-native  0.97.0
@pulumi/aws         6.5.0
@pulumi/command     0.9.2
@pulumi/docker      4.4.5
@types/node         14.18.35
@pulumi/random      4.14.0
@types/js-yaml      4.0.8
node-fetch          3.3.2
ts-node             10.9.1
typescript          5.2.2

Pulumi locates its logs in /tmp/nix-shell.Az5sU3 by default
warning: Failed to get information about the current stack: snapshot integrity failure; refusing to use it: resource urn:pulumi:vcluster-develop::infra::kubernetes:batch/v1:Job::restore-postgres's dependency urn:pulumi:vcluster-develop::infra::kubernetes:core/v1:ConfigMap::postgres-restore-scripts refers to missing resource
```

**Comment by blampe** [comment] 2024-07-16 16:59
@mausch out of curiosity, which properties on the provider did you change to trigger the replacement? Did you happen to be upgrading from v3.30.2 to 4.5.4 of p/k?

**Comment by blampe** [comment] 2024-07-16 20:36
So far I haven't been able to reproduce the snapshot integrity failure, although I am seeing  unexpected behavior possibly related to https://github.com/pulumi/pulumi/issues/14650.

I'm basing this on the original description from @oliverholliday (assuming Azure/EKS/GVP is irrelevant -- although that could be wrong). For folks affected by this, is there anything that stands out as different between the minimal example below and your own stacks? (It would also be helpful to know how the example below behaves for other folks.)

```ts
import * as k8s from "@pulumi/kubernetes";
import * as eks from "@pulumi/eks";

const cluster = new eks.Cluster("eks-cluster", {
  name: "replace-me", // Change to trigger a replacement.
});

const provider = new k8s.Provider("provider", {
  kubeconfig: cluster.kubeconfig,
});

new k8s.core.v1.Pod(
  "pod",
  {
    metadata: {
      name: "foo",
    },
    spec: {
      containers: [
        {
          name: "nginx",
          image: "nginx",
        },
      ],
    },
  },
  { provider: provider }
);
```

<details>
CLI
Version      3.124.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.44.0
resource  eks         2.7.3
resource  kubernetes  4.15.0
language  nodejs      unknown

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/Users/bryce/.nvm/versions/node/v18.17.0/bin/node' version='v18.17.0'

Current Stack: organization/pulumi-4996/dev

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:dev::pulumi-4996::pulumi:pulumi:Stack::pulumi-4996-dev
eks:index:Cluster                                  urn:pulumi:dev::pulumi-4996::eks:index:Cluster::eks-cluster
eks:index:ServiceRole                              urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:ServiceRole::eks-cluster-instanceRole
pulumi:providers:aws                               urn:pulumi:dev::pulumi-4996::pulumi:providers:aws::default_6_44_0
eks:index:ServiceRole                              urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:ServiceRole::eks-cluster-eksRole
pulumi:providers:eks                               urn:pulumi:dev::pulumi-4996::pulumi:providers:eks::default_2_7_3
aws:iam/role:Role                                  urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::eks-cluster-eksRole-role
eks:index:RandomSuffix                             urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:RandomSuffix::eks-cluster-cfnStackName
aws:iam/role:Role                                  urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:ServiceRole$aws:iam/role:Role::eks-cluster-instanceRole-role
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::eks-cluster-eksRole-4b490823
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::eks-cluster-instanceRole-e1b295bd
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::eks-cluster-instanceRole-03516f97
aws:iam/rolePolicyAttachment:RolePolicyAttachment  urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:ServiceRole$aws:iam/rolePolicyAttachment:RolePolicyAttachment::eks-cluster-instanceRole-3eb088f2
aws:iam/instanceProfile:InstanceProfile            urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:iam/instanceProfile:InstanceProfile::eks-cluster-instanceProfile
aws:ec2/securityGroup:SecurityGroup                urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::eks-cluster-eksClusterSecurityGroup
aws:ec2/securityGroupRule:SecurityGroupRule        urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-cluster-eksClusterInternetEgressRule
aws:eks/cluster:Cluster                            urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:eks/cluster:Cluster::eks-cluster-eksCluster
pulumi:providers:kubernetes                        urn:pulumi:dev::pulumi-4996::eks:index:Cluster$pulumi:providers:kubernetes::eks-cluster-eks-k8s
aws:ec2/securityGroup:SecurityGroup                urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:ec2/securityGroup:SecurityGroup::eks-cluster-nodeSecurityGroup
aws:ec2/securityGroupRule:SecurityGroupRule        urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-cluster-eksNodeInternetEgressRule
aws:ec2/securityGroupRule:SecurityGroupRule        urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-cluster-eksClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule        urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-cluster-eksNodeIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule        urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-cluster-eksExtApiServerClusterIngressRule
aws:ec2/securityGroupRule:SecurityGroupRule        urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:ec2/securityGroupRule:SecurityGroupRule::eks-cluster-eksNodeClusterIngressRule
kubernetes:core/v1:ConfigMap                       urn:pulumi:dev::pulumi-4996::eks:index:Cluster$kubernetes:core/v1:ConfigMap::eks-cluster-nodeAccess
eks:index:VpcCni                                   urn:pulumi:dev::pulumi-4996::eks:index:Cluster$eks:index:VpcCni::eks-cluster-vpc-cni
aws:ec2/launchConfiguration:LaunchConfiguration    urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:ec2/launchConfiguration:LaunchConfiguration::eks-cluster-nodeLaunchConfiguration
aws:cloudformation/stack:Stack                     urn:pulumi:dev::pulumi-4996::eks:index:Cluster$aws:cloudformation/stack:Stack::eks-cluster-nodes
pulumi:providers:kubernetes                        urn:pulumi:dev::pulumi-4996::pulumi:providers:kubernetes::provider
pulumi:providers:kubernetes                        urn:pulumi:dev::pulumi-4996::eks:index:Cluster$pulumi:providers:kubernetes::eks-cluster-provider
kubernetes:core/v1:Pod                             urn:pulumi:dev::pulumi-4996::kubernetes:core/v1:Pod::pod


Found no pending operations associated with dev

Backend
Name           Bryces-Work-MBP
URL            file:///Users/bryce/src/test/pulumi-4996/
User           bryce
Organizations
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/eks         2.7.3
@pulumi/kubernetes  4.5.4
@pulumi/pulumi      3.122.0
@types/node         18.19.39
typescript          5.5.3
</details>

Steps:
1. Perform the initial `up`.
2. Edit the program and change the cluster's name to force a replacement.
3. Preview the update:
```
❯ pulumi up -s dev --logflow -v=10 --show-replacement-steps
Previewing update (dev):
     Type                                Name                                 Plan        Info
     pulumi:pulumi:Stack                 pulumi-4996-dev
     ├─ eks:index:Cluster                eks-cluster
 +-  │  ├─ aws:eks:Cluster               eks-cluster-eksCluster               replace     [diff: ~name]
 +-  │  ├─ pulumi:providers:kubernetes   eks-cluster-eks-k8s                  replace     [diff: ~kubeconfig]
 +-  │  ├─ pulumi:providers:kubernetes   eks-cluster-provider                 replace     [diff: ~kubeconfig]
 +-  │  ├─ aws:ec2:LaunchConfiguration   eks-cluster-nodeLaunchConfiguration  replace     [diff: ~iamInstanceProfile,imageId,name,userData]
 +-  │  ├─ kubernetes:core/v1:ConfigMap  eks-cluster-nodeAccess               replace     [diff: ~provider]
 ~   │  ├─ aws:ec2:SecurityGroup         eks-cluster-nodeSecurityGroup        update      [diff: ~tags,tagsAll]
 ~   │  └─ aws:cloudformation:Stack      eks-cluster-nodes                    update      [diff: ~templateBody]
 +-  ├─ pulumi:providers:kubernetes      provider                             replace     [diff: ~kubeconfig]
 +-  └─ kubernetes:core/v1:Pod           pod                                  replace     [diff: ~metadata,provider]

Resources:
    ~ 2 to update
    +-7 to replace
    9 changes. 20 unchanged
```
4. This looks expected (replace the cluster as well as the resource inside it) so perform the update:
```
Do you want to perform this update? yes
Updating (dev):
     Type                       Name             Status                  Info
     pulumi:pulumi:Stack        pulumi-4996-dev  **failed**              1 error
 --  └─ kubernetes:core/v1:Pod  pod              **deleting failed**     1 error

Diagnostics:
  kubernetes:core/v1:Pod (pod):
    error: grpc: the client connection is closing

  pulumi:pulumi:Stack (pulumi-4996-dev):
    error: update failed

Resources:
    14 unchanged

Duration: 3s
```

For some reason we attempt to delete the pod first. From the logs, `DiffConfig` succeeded by `Configure` did not?

```
}
I0716 12:08:50.047882   66321 provider_plugin.go:557] Provider[kubernetes, 0x14001c1a3c0].DiffConfig(urn:pulumi:dev::pulumi-4996::eks:index:Cluster$pulumi:providers:kubernetes::eks-cluster-eks-k8s) success: changes=2 #replaces=[kubeconfig] #stables=[] delbefrepl=false, diffs=#[kubeconfig]
I0716 12:08:50.047977   66321 provider_plugin.go:781] Provider[kubernetes, 0x14001c1a3c0].Configure() failed: err=grpc: the client connection is closing
``` 

Resources in state are marked `pendingDelete`, although subsequent `up`s all fail with this error.

I would expect to see the new provider created first, then a new cluster, etc. until old resources and finally the original provider are torn down.

**Comment by lunaris** [comment] 2024-09-05 13:40
Hey all; is this still an issue on the latest version (3.131.0) of Pulumi CLI? We've recently fixed several snapshot integrity bugs and it looks like this might be related to some of those we've addressed.

**Comment by lunaris** [comment] 2024-09-16 12:51
Hi all; I'm going to close this as I suspect it has been fixed in the latest release, but if it resurfaces please reopen this issue and I'll investigate. Thanks!

**Closed by lunaris** 2024-09-16 12:51 UTC
Labels: kind/bug, p1, area/providers, area/backends, awaiting-feedback, resolution/fixed, impact/snapshot-integrity
