### ISSUE TITLE
Unable to use mergeOptions for resource arguments in transformation

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3774] opened 2020-01-20 20:05 UTC
It seems our current [`pulumi.mergeOptions`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#mergeOptions) implements don't support the necessary types for merging resource arguments when used in a transformation.

Can we add another implementation of `mergeOptions` that supports this?

#### Compile Error
```
aws-ts-eks % pulumi up -s dev2
Previewing update (dev2):

     Type                 Name             Plan       Info
 +   pulumi:pulumi:Stack  aws-ts-eks-dev2  create     1 error

Diagnostics:
  pulumi:pulumi:Stack (aws-ts-eks-dev2):
    error: Running program '/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-eks' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(40,21): error TS2769: No overload matches this call.
      Overload 1 of 3, '(opts1: CustomResourceOptions | undefined, opts2: CustomResourceOptions | undefined): CustomResourceOptions', gave the following error.
        Argument of type '{ vpcConfig: { publicAccessCidrs: string[]; }; }' is not assignable to parameter of type 'CustomResourceOptions'.
          Object literal may only specify known properties, and 'vpcConfig' does not exist in type 'CustomResourceOptions'.
      Overload 2 of 3, '(opts1: ComponentResourceOptions | undefined, opts2: ComponentResourceOptions | undefined): ComponentResourceOptions', gave the following error.
        Argument of type '{ vpcConfig: { publicAccessCidrs: string[]; }; }' is not assignable to parameter of type 'ComponentResourceOptions'.
          Object literal may only specify known properties, and 'vpcConfig' does not exist in type 'ComponentResourceOptions'.
      Overload 3 of 3, '(opts1: ResourceOptions | undefined, opts2: ResourceOptions | undefined): ResourceOptions', gave the following error.
        Argument of type '{ vpcConfig: { publicAccessCidrs: string[]; }; }' is not assignable to parameter of type 'ResourceOptions'.
          Object literal may only specify known properties, and 'vpcConfig' does not exist in type 'ResourceOptions'.

        at createTSError (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-eks/node_modules/ts-node/src/index.ts:421:12)
        at reportTSError (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-eks/node_modules/ts-node/src/index.ts:425:19)
        at getOutput (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-eks/node_modules/ts-node/src/index.ts:530:36)
        at Object.compile (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-eks/node_modules/ts-node/src/index.ts:735:32)
        at Module.m._compile (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-eks/node_modules/ts-node/src/index.ts:814:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Object.require.extensions.(anonymous function) [as .ts] (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-eks/node_modules/ts-node/src/index.ts:817:12)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)

aws-ts-eks %
```

#### Code
```ts
import * as awsx from "@pulumi/awsx";
import * as eks from "@pulumi/eks";
import * as pulumi from "@pulumi/pulumi";

const vpc = new awsx.ec2.Vpc("vpc", {});

const cluster = new eks.Cluster("cluster", {
    vpcId: vpc.vpc.id,
    subnetIds: vpc.publicSubnetIds,
    instanceType: "t2.medium",
    desiredCapacity: 2,
    minSize: 1,
    maxSize: 2,
    storageClasses: "gp2",
    deployDashboard: true,
}, {
    transformations: [args => {
        if (args.type === "aws:eks/cluster:Cluster") {
            return {
                props: pulumi.mergeOptions(args.props, {
                    vpcConfig: { publicAccessCidrs: ["5.5.5.5/32"], }
                }),
                opts: args.opts,
            };
        }
        return undefined;
    }],
});
```

#### Workaround without using `mergeOptions`
```ts
import * as awsx from "@pulumi/awsx";
import * as eks from "@pulumi/eks";
import * as pulumi from "@pulumi/pulumi";

const vpc = new awsx.ec2.Vpc("vpc", {});

const cluster = new eks.Cluster("cluster", {
    vpcId: vpc.vpc.id,
    subnetIds: vpc.publicSubnetIds,
    instanceType: "t2.medium",
    desiredCapacity: 2,
    minSize: 1,
    maxSize: 2,
    storageClasses: "gp2",
    deployDashboard: true,
}, {
    transformations: [args => {
        if (args.type === "aws:eks/cluster:Cluster") {
            return {
                props: {
                    ...args.props,
                    vpcConfig: {
                        ...args.props.vpcConfig,
                        publicAccessCidrs: ["0.0.0.0/0"],
                    },
                },
                opts: args.opts,
            };
        }
        return undefined;
    }],
});
```

**Comment by lukehoban** [comment] 2020-01-20 20:56
`pulumi.mergeOptions` is for merging `ResourceOptions`, not for generally merging argument bags for inputs.

The use case you seem to be using it for here is for manipulating the inputs to a resource constructor.  That is just a different use cases, and `...` (splat) operators (as in your workaround above) are indeed the right way to handle that.   We could try to offer something similar to `mergeOptions` for this use case, but it would be more fragile, as we do not have a fixed schema to use to drive a type-directed smart merge as we do with `ResourceOptions`.

For now at least, closing as "by design".

**Closed by lukehoban** 2020-01-20 20:56 UTC
