### ISSUE TITLE
Python generating incorrect if statement

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#11171] opened 2022-10-27 19:38 UTC
### What happened?

I have generated a python SDK for a bridged provider. Unfortunately, the generated python code isn't valid

### Steps to reproduce

See this line

https://github.com/lbrlabs/pulumi-grafana/blob/main/sdk/python/lbrlabs_pulumi_grafana/provider.py#L455

### Expected Behavior

I can create a provider

### Actual Behavior

```
Diagnostics:
  pulumi:pulumi:Stack (pulumi_grafana_service_account_python-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/lbriggs/src/github/lbrlabs/pulumi-grafana/examples/python/service_account/./__main__.py", line 4, in <module>
        import lbrlabs_pulumi_grafana as grafana
      File "/Users/lbriggs/src/github/lbrlabs/pulumi-grafana/sdk/python/bin/lbrlabs_pulumi_grafana/__init__.py", line 57, in <module>
        from .provider import *
      File "/Users/lbriggs/src/github/lbrlabs/pulumi-grafana/sdk/python/bin/lbrlabs_pulumi_grafana/provider.py", line 455
        __props__.__dict__["http_headers"] = None if pulumi.Output.from_input(http_headers).apply(pulumi.runtime.to_json) if http_headers is not None else None is None else pulumi.Output.secret(pulumi.Output.from_input(http_headers).apply(pulumi.runtime.to_json) if http_headers is not None else None)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: expected 'else' after 'if' expression
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jaxxstorm** [comment] 2022-10-28 15:16
Okay, this might actually be a python bug

https://bugs.python.org/issue44838

**Comment by jaxxstorm** [comment] 2022-10-28 15:20
We still need to fix this unfortunately as it effects python 3.10

**Comment by jaxxstorm** [comment] 2022-10-28 15:36
I fixed this by omitting the values from the schema for now

**Comment by justinvp** [comment] 2023-07-27 19:03
This is a duplicate of https://github.com/pulumi/pulumi/issues/11278 which was fixed by https://github.com/pulumi/pulumi/pull/11494

**Closed by justinvp** 2023-07-27 19:03 UTC
Labels: kind/bug, language/python, area/codegen, resolution/duplicate
