### ISSUE TITLE
Using old CLI on a stack with passphrase encryption sort of works

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2730] opened 2019-05-14 04:01 UTC
I created a stack with passphrase encryption.

Then I used an old CLI to deploy it - which worked, without requiring the passphrase.

I was also able to set secret config values using the old CLI, which were stored using service-backed encryption - not passphrase.

However, when I then used the *new* CLI to do an update, I got:

```
$ ~/go/bin/pulumi up
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember):
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember):
Previewing update (withsecrets):
error: failed to decrypt encrypted configuration value 'secrets:mysecret': bad value
This can occur when a secret is copied from one stack to another. Encryption of secrets is done per-stack and
it is not possible to share an encrypted configuration value across stacks.

You can re-encrypt your configuration buy running 'pulumi config set secrets:mysecret [value] --secret' with your
new stack selected.

refusing to proceed
```

I can see an argument for this all being "correct" (and arguably this is a weird set of steps to take) but it was surprising.

**Comment by ellismg** [comment] 2019-05-14 22:43
I agree this is somewhat surprising, but I am not sure what we can do here.  Before 0.17.11, the CLI used the type of backend to understand what encryption strategy to use for secret configuration values. Critically, it did not inspect the `pulumi.<stack-name>.yaml` file to determine information about the secrets provider to use, as it does today.

When you create a stack with 0.17.11 as set `secrets-provider` to be passphrase, we write the `EncryptionSalt` member into your `Pulumi.<app-name>.yaml` file.  Whenever we need to get the encryption scheme for a stack, we consult that file, if EncryptionSalt is present, we use the passphrase based secrets provider, otherwise we pick the secrets provider based on your backend type: (see: https://github.com/pulumi/pulumi/blob/120bf897ed29db936c5fc1a442126ee01b748c91/cmd/crypto.go#L45)

So, when you move to the older CLI and add another secret configuration value, it simply uses the currently configured backend (in this case, the web backend) and writes the value.  Ideally it would have noticed "hey, you already have this encryption salt thing in here which seems very weird because I never expect to see that for stacks managed by the service" but we never did that check.

When you move forward and try to run the deploy, the newer CLI correctly detects that since you have the EncryptionSalt and so it creates a provider based on your passphrase.  But, of course, that is going to be unable to decrypt any values that were set from the older CLI, since they used a different provider.

I think the only thing we can do here is augment the above message to note that this also may happen in cases like the above.  But it feels very esoteric and I'm not really sure a concise way to report this:  Would see say something like "This can occur when a secret is copied from one stack to another or when a secret was encrypted with a different provider"?  It feels like pushing that concept so in the face of the user here is very confusing.

So, yes, this is wonky, but yes, it makes sense.  If you think changes to the message would be helpful, I am happy to make them, but I am not really sure how much more we can do here.  The root cause of the problem is that we should have had the foresight to have older versions of the CLI blow up when they saw this case (an EncryptionSalt member on the config file for a stack that was managed by the service) but we didn't.

**Comment by lukehoban** [comment] 2019-05-15 16:44
I think you are right that this is sufficiently uncommon that it doesn't warrant any specific new callout here.

If we did want to though - I could imagine something like:

> This can occur when a secret is copied from one stack to another or when secrets were stored using an older version of the CLI that did not support the current stack's secrets provider.

**Comment by ellismg** [comment] 2019-05-16 20:53
Gonna close this but if we start getting more feedback on this being more common, I'll adopt wording similar to the above.

**Closed by ellismg** 2019-05-16 20:53 UTC
