### ISSUE TITLE
Setting config with path should not change order and remove comments

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#3613] opened 2019-12-05 22:11 UTC
When running `pulumi config set --path path.key` the contents of the file should only change for the path. Pulumi today is actually rewriting the entire file alphabetically, and also stripping comments.

**Comment by stack72** [comment] 2019-12-05 22:18
Hi @nesl247 

Please can you give me an example of this so I can test it? Is this regarding a provider configuration or something else?

Paul

**Comment by nesl247** [comment] 2019-12-05 22:20
I haven't tested this specific bit out, but give it a shot:

```
config:
  test-project:test:
    z:z
    a:a
```

Will most likely turn into:

```
config:
  test-project:test:
    a:a
    z:z
```

when you run `pulumi config set --path test.z test`

I can provide a real world example if necessary.

**Comment by justinvp** [comment] 2019-12-05 22:40
Thanks, @nesl247! Looks like a dupe of #423.

**Closed by justinvp** 2019-12-05 22:40 UTC
