### ISSUE TITLE
Stop the recreation of resources if a new provider is attached to them

### ISSUE THREAD

**Issue by katcosgrove** [pulumi/pulumi#8959] opened 2022-02-09 16:58 UTC
### Discussed in https://github.com/pulumi/pulumi/discussions/7596

<div type='discussions-op-text'>

<sup>Originally posted by **mate201** July 21, 2021</sup>
We recently found ourselves in need of adding a new AWS provider in place of a default one. The problem is that after the actual addition, Pulumi tries to recreate all resources with a new provider. I was trying to solve the issue, and the only hackaround I've found is to run Pulumi up specifying only a new provider. Thus Pulumi will create a new provider in a stack and update resources with a new provider without replacing them.

Recommendations:

- Run pulumi up before provider addition to update the state and not make any other change except provider later on.

- Back up you stack with `pulumi stack export`

- Add new provider in code and run `pulumi up --target <urn_of your_new_provider>` e.g., ` pulumi up --target urn:pulumi:mate201-test-cluster-uat::uat::pulumi:providers:aws::commonAwsProvider`</div>

**Comment by itay** [comment] 2022-02-09 17:27
I ran into the same issue - and no matter how much I tried to edit the stack JSON manually, I could not get it to recognize the new provider. I did not try what @katcosgrove mentioned above, so perhaps next time I need to do this.

**Comment by NWCalvank** [comment] 2022-10-17 19:29
My team currently has a number of Pulumi projects that are only in us-east-1 (aws), using the default provider. We want to support multi-region, so I'm trying to switch over from using the default, disabling the default provider along the way.

Despite running a `pulumi up` to add the provider, as per @katcosgrove above, Pulumi still wants to replace all my S3 buckets.

Is there a way to avoid this that doesn't involve trying to perform state surgery on the stack export JSON?

I've been reading up on related (open and closed) Pulumi issues/blog posts, with my best lead being aliasing the explicit provider to "replace" the default one. But I couldn't find any documentation on that, so my guessing of how it might work did not succeed.

Do y'all have any articles or guides on how to migrate off of the default providers?

**Comment by F3LDS** [comment] 2022-12-13 03:39
Coming across this issue on my own adventure into disabling the default provider. My team is also looking to go multi-region and multi-account so we needed to switch to explicit providers, but replacing all existing resources just wasn't an option.

After much trial and error I found that disabling the default provider through the `pulumi:disable-default-providers` config option, and making sure to name the new provider resource 'default' seems to have kept everything in place. Not the most confidence-inspiring fix, but it has allowed me to move forward.

Aliasing the new provider to the old default one doesn't seem to make a difference, and doesn't allow me to change the resource name to something other than 'default'.

**Comment by lukehoban** [comment] 2023-03-09 05:18
I tried this out - and was not able to reproduce the issue.  It's possible this was addressed by other work in the last few months - but it should indeed be posible to alias an explicit provider to a preivous uage of a default provider to migrate a resource to use the explicit provider - and then subsequently to turn on `pulumi:disable-default-providers` to prevent future usage of default providers.

I first deployed this:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const bucket = new aws.s3.Bucket("my-bucket", {
    serverSideEncryptionConfiguration: {
        rule: {
            applyServerSideEncryptionByDefault: {
                sseAlgorithm: "AES256"
            },
        },
    },
});

export const bucketName = bucket.id;
```

Then updated it to this:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config = new pulumi.Config("aws");
const provider = new aws.Provider("aws", {
    region: <aws.Region>config.require("region"),
}, { 
    aliases: ["urn:pulumi:dev::fasdsad::pulumi:providers:aws::default_5_30_0"] 
});

const bucket = new aws.s3.Bucket("my-bucket", {
    serverSideEncryptionConfiguration: {
        rule: {
            applyServerSideEncryptionByDefault: {
                sseAlgorithm: "AES256"
            },
        },
    },
}, { 
    provider: provider 
});

export const bucketName = bucket.id;
```

This did show a diff on the provider, but one that didn't affect any resources (or require any replacements).

After applying that update, I was able to add `pulumi:disable-default-providers` on `aws` and there were no errors.

If anyone is still able to reproduce something similar to this - please do open a new issue with a repro case.

**Closed by lukehoban** 2023-03-09 05:18 UTC
Labels: kind/bug, resolution/no-repro

**Comment by NWCalvank** [comment] 2024-08-15 23:02
I tried this at the time, and it didn't work. But I figured it was my mistake somehow, and so I gave up.

Over a year later, and I'm trying it again on a different set of resources, and it still requires a `create-replacement`.

Despite the preview showing a `create-replacement`, I decided to proceed - just to see - and it did, in fact, attempt a replacement (most failed due to a naming conflict when creating new resources).

I'm using the Python client. Is it possible that it's been working in JavaScript, but failing in Python?

If anyone else, outside of the Pulumi team, sees this... were you able to do this?

**Comment by rio** [comment] 2024-08-16 09:58
I'm running into a similar thing with python and aws. I'm onboarding on a codebase built by a single person. It's not big, only 13 resources or so. We're getting AWS SSO/IAM into a more workable state and up until now I've just used my IAM access keys. When switching over to SSO all the resources will be recreated, even though that SSO user has access to all the resources and pulumi state in S3.

I'm not sure why this hasn't popped up more often for people. Is nobody using pulumi python + aws and have more than 1 engineer working on it? Even if pulumi is only run through CI, people still need to develop and run pulumi preview, which is currently useless because of all the recreates it wants to make.
