### ISSUE TITLE
Error using convert in Pulumi CLI

### ISSUE THREAD

**Issue by sswist** [pulumi/pulumi#17590] opened 2024-10-21 14:05 UTC
### What happened?

Trying to convert a vendor provided .tf file into a pulumi program using python and I get the following output.

### Example

Command entered:
`pulumi convert --from terraform --language python --out pulumi`

Output:
`Converting from terraform...
Converting to python...

The Pulumi CLI encountered a code generation error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.

Pulumi Version:   v3.137.0
error: main.pp:144,1-148,2: /var/folders/63/3hjqknf55yvc2g49z9_60t8h0000gp/T/pulumi-convert1933058223/acm_4.3.1/main.pp:36,28-45: the first argument to 'element' must be a list or tuple; , and 2 other diagnostic(s); /var/folders/63/3hjqknf55yvc2g49z9_60t8h0000gp/T/pulumi-convert1933058223/acm_4.3.1/main.pp:36,28-45: the first argument to 'element' must be a list or tuple; , and 2 other diagnostic(s)
error: main.pp:27,1-68,2: /var/folders/63/3hjqknf55yvc2g49z9_60t8h0000gp/T/pulumi-convert1933058223/terraform?ref=tf-mod-root-v1.11.1/main.pp:1,1-26,2: /var/folders/63/3hjqknf55yvc2g49z9_60t8h0000gp/T/pulumi-convert1933058223/terraform?ref=tf-mod-root-v1.11.1/vpc_5.1.2/main.pp:102,55-104,12: the first argument to 'element' must be a list or tuple; , and 14 other diagnostic(s); /var/folders/63/3hjqknf55yvc2g49z9_60t8h0000gp/T/pulumi-convert1933058223/terraform?ref=tf-mod-root-v1.11.1/vpc_5.1.2/main.pp:102,55-104,12: the first argument to 'element' must be a list or tuple; , and 14 other diagnostic(s), and 2 other diagnostic(s); /var/folders/63/3hjqknf55yvc2g49z9_60t8h0000gp/T/pulumi-convert1933058223/terraform?ref=tf-mod-root-v1.11.1/main.pp:1,1-26,2: /var/folders/63/3hjqknf55yvc2g49z9_60t8h0000gp/T/pulumi-convert1933058223/terraform?ref=tf-mod-root-v1.11.1/vpc_5.1.2/main.pp:102,55-104,12: the first argument to 'element' must be a list or tuple; , and 14 other diagnostic(s); /var/folders/63/3hjqknf55yvc2g49z9_60t8h0000gp/T/pulumi-convert1933058223/terraform?ref=tf-mod-root-v1.11.1/vpc_5.1.2/main.pp:102,55-104,12: the first argument to 'element' must be a list or tuple; , and 14 other diagnostic(s), and 2 other diagnostic(s)
error: could not generate output program`

### Output of `pulumi about`

`CLI
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  3.137.0

Host
OS       darwin
Version  15.0.1
Arch     arm64

This project is written in python: executable='/usr/bin/python3' version='3.9.6'

Backend
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations
Token type     personal

Dependencies:
NAME        VERSION
colorama    0.4.6
Django      4.2.1
Flask       2.2.3
future      0.18.2
macholib    1.15.2
moviepy     1.0.3
pip         24.2
pulumi      3.137.0
pygame      2.3.0
pylance     0.4.9
setuptools  75.2.0
termcolor   2.3.0
wheel       0.44.0

Pulumi locates its logs in /var/folders/63/3hjqknf55yvc2g49z9_60t8h0000gp/T/ by default
warning: Failed to get information about the current stack: No current stack`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2024-10-28 05:02
Thanks for opening the issue @sswist, and sorry for the trouble! This is a duplicate of https://github.com/pulumi/pulumi-converter-terraform/issues/202

**Closed by justinvp** 2024-10-28 05:02 UTC
Labels: kind/bug, resolution/duplicate
