### ISSUE TITLE
An "exclude" flag for commands like preview and up

### ISSUE THREAD

**Issue by solomonshorser** [pulumi/pulumi#13549] opened 2023-07-20 16:23 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like to be able to run commands such as `pulumi up` and `pulumi preview` but excluding one or two resources. Currently, I can target individual resources with `-t`: 

```bash
pulumi up -t 'urn:to:some_resource'
```

And ONLY that resource will be created/updated. But I want to create/update my entire stack _except_ for one or two resources. I'd like to be able to do this:

```bash
pulumi up -x 'urn:to:some_resource' 
```

and I would want pulumi to update/create everything _except_ for this specified resource.

The reason? I currently have some cloud resources that are not updating properly, and I would like to apply the changes in the rest of the stack and simply ignore this one resource. Ignoring this one resource won't have a serious impact on the rest of this stack. I suppose I could update the whole stack except for this resource by doing this:

```bash
pulumi up -t 'urn:to:resource1' -t 'urn:to:resource2' -t 'urn:to:resource3' ... -t 'urn:to:resource_n-1'
```

but for stacks with many resources, this is not very practical.

### Affected area/feature

CLI

**Comment by Frassle** [comment] 2023-07-20 16:30
Duplicate of https://github.com/pulumi/pulumi/issues/9346

**Closed by Frassle** 2023-07-20 16:30 UTC
Labels: kind/enhancement, resolution/duplicate
