### ISSUE TITLE
pulumi convert unable to handle terraform's "jsondecode" function

### ISSUE THREAD

**Issue by figadore** [pulumi/pulumi#17601] opened 2024-10-23 17:03 UTC
### What happened?

`pulumi convert --from terraform --language go` generates `notImplemented` code for jsondecode function

### Example

relevant terraform
```hcl
locals {
  env_config = jsondecode(data.google_storage_bucket_object_content.env_config.content)
}
```

relevant cli output
> warning: /path/to/main.tf:50,16-88: Function not yet implemented; Function jsondecode not yet implemented

relevant generated code
```go
envConfig := notImplemented("jsondecode(data.google_storage_bucket_object_content.env_config.content)")
```

### Output of `pulumi about`

```
CLI          
Version      3.137.0
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME  VERSION
resource  gcp   8.2.0
language  go    unknown

Host     
OS       darwin
Version  15.0
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.23.2 darwin/arm64'

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-gcp/sdk/v8  v8.2.0
github.com/pulumi/pulumi/sdk/v3      v3.130.0

Pulumi locates its logs in /var/folders/73/2r6x3pzs5mx1xhzgnv6bxn3c0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2024-10-28 05:39
Duplicate of https://github.com/pulumi/pulumi-converter-terraform/issues/136

**Closed by justinvp** 2024-10-28 05:39 UTC
Labels: kind/bug, resolution/duplicate
