### ISSUE TITLE
pulumi plugin install --server keep looking for the main repo url not one I used 

### ISSUE THREAD

**Issue by yoyoraso** [pulumi/pulumi#15480] opened 2024-02-21 17:00 UTC
### What happened?

so I used pulumi plugin install --server https://github.com/***/pulumi-resource-kubernetes-v4.7.1-linux-amd64.tar.gz to install plugin from different source other than https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v4.7.1-linux-amd64.tar.gz and it showed me 
[resource plugin kubernetes-4.7.1] installing , then it kept trying to reach https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v4.7.1-linux-amd64.tar.gz again and again which was blocked by my network 

### Example

pulumi plugin install --server https://PRIVET_GIT/ORG_NAME/***/uploads/***/pulumi-resource-kubernetes-v4.7.1-linux-amd64.tar.gz
[resource plugin kubernetes-4.7.1] installing
warning: Error downloading plugin: Get "https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v4.7.1-linux-amd64.tar.gz": dial tcp IP:443: connect: network is unreachable
Will retry in 80ms [1/5]
warning: Error downloading plugin: Get "https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v4.7.1-linux-amd64.tar.gz": dial tcp IP:443: connect: network is unreachable
Will retry in 160ms [2/5]
warning: Error downloading plugin: Get "https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v4.7.1-linux-amd64.tar.gz": dial tcp IP:443: connect: network is unreachable
Will retry in 320ms [3/5]
warning: Error downloading plugin: Get "https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v4.7.1-linux-amd64.tar.gz": dial tcp IP:443: connect: network is unreachable
Will retry in 640ms [4/5]
warning: Error downloading plugin: Get "https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v4.7.1-linux-amd64.tar.gz": dial tcp IP:443: connect: network is unreachable
Will retry in 1.28s [5/5]
error: [resource plugin kubernetes-4.7.1] downloading from : failed to download plugin: kubernetes-4.7.1: failed all 5 attempts

### Output of `pulumi about`

pulumi about
CLI          
Version      3.92.0
Go Version   go1.21.3
Go Compiler  gc

Host     
OS       debian
Version  11.8
Arch     x86_64

Backend        
Name           pulumi-kubernetes-operator-564b7f869d-84qrl
URL            file://~
User           pulumi-kubernetes-operator
Organizations  
Token type     personal

Pulumi locates its logs in /tmp by default

### Additional context

this was used manually from inside pulumi operator pod  in the stack directlry 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2024-03-02 07:34
@yoyoraso, does it work if you try to specify the custom URL without the filename in the URL?

Something like:

```
pulumi plugin install resource kubernetes 4.7.1 --server https://PRIVET_GIT/ORG_NAME/uploads/
```

**Comment by yoyoraso** [comment] 2024-03-05 14:58
> @yoyoraso, does it work if you try to specify the custom URL without the filename in the URL?
> 
> Something like:
> 
> ```
> pulumi plugin install resource kubernetes 4.7.1 --server https://PRIVET_GIT/ORG_NAME/uploads/
> ```

so when I tried your command it actually seems to be trying to download the plugin from my link but it can't as I made te plugin as release folder in privet repo so how to set authentication method to be able to access the repo + how to change default url that pulumi uses to download plugins (as I am trying the pulumi operator in privet cluster so when I try anything it fails in the plugin install step thats why I tried downloading plugins manually in first place ) thank you

**Comment by mikhailshilkov** [comment] 2024-06-03 14:24
As mentioned above, the `server` command currently expects a remote folder where plugin files are stored, not a concrete file name. Also, that folder is expected to be publicly accessible and no extra authentication is currently supported.

As a workaround, you could download your plugin files manually and the use the `--file` option of `pulumi plugin install` to install it from a local file.

Since this behavior is by design, I'll close the issue as such. If you want to request an authentication mechanism, please open a new Enhancement issue. Thank you!

**Closed by mikhailshilkov** 2024-06-03 14:24 UTC
Labels: kind/bug, resolution/by-design, area/plugins
