### ISSUE TITLE
default `pulumi convert` invocation is destructive

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#13198] opened 2023-06-17 22:36 UTC
Running pulumi convert in a directory that has a `Pulumi.yaml` file/program overwrites the `Pulumi.yaml` without prompting. Luckily I had the file open and could `ctrl+z` to get my changes back. 

Not sure what the behavior should be here, maybe prompt the user saying `this will overwrite your Pulumi.yaml file, do you want to proceed?`

**Comment by Frassle** [comment] 2023-06-17 22:48
Duplicate of https://github.com/pulumi/pulumi/issues/12842

**Closed by Frassle** 2023-06-17 22:48 UTC
Labels: kind/bug, resolution/duplicate
