### ISSUE TITLE
`pulumi preview --import-file...` against a stack with resources produces a panic

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#15041] opened 2024-01-04 03:42 UTC
### What happened?

A panic occurs when running `pulumi preview --import-file ...` against a stack that contains resources.

### Example

`pulumi up` the below program to ensure the stack has resources:
```
import * as awsx from "@pulumi/awsx";

new awsx.ec2.Vpc("vpc", {
    cidrBlock: "10.100.0.0/16"
});
```

next, execute `pulumi preview --import-file some-json.json`

panic:
```
panic: runtime error: index out of range [0] with length 0

goroutine 65 [running]:
main.newPreviewCmd.func1.buildImportFile.func1()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:91 +0x140a
github.com/pulumi/pulumi/sdk/v3/go/common/promise.Run[...].func1()
	/home/runner/work/pulumi/pulumi/sdk/go/common/promise/promise.go:150 +0x2c
created by github.com/pulumi/pulumi/sdk/v3/go/common/promise.Run[...] in goroutine 1
	/home/runner/work/pulumi/pulumi/sdk/go/common/promise/promise.go:149 +0x90
```

### Output of `pulumi about`

pulumi/pulumi 3.99

### Additional context

cc @Frassle 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by phillipedwards** [comment] 2024-01-04 03:46
Additionally, following the same flow as above, using a smaller program such as the below one results in the import file successful being created. That said, the `resources` array is `null`.

```
import * as aws from "@pulumi/aws";

new aws.s3.Bucket("my-bucket");
```

import file
```
{
    "resources": null
}

```

**Comment by dixler** [comment] 2024-01-05 18:06
The panic in the initial description appears to be a duplicate of:
- https://github.com/pulumi/pulumi/issues/15002

It no longer panics as of v3.100.0, but, as for the problem described in the follow-up comment, the initial program also has the same issue where `"resources": null` after the panic is fixed.

```
% pulumi up         
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/kyle-pulumi-corp/import/dev/previews/50be94eb-bed7-49b1-9b7c-5d2caa380f8e

     Type                                          Name           Plan       
 +   pulumi:pulumi:Stack                           import-dev     create     
 +   └─ awsx:ec2:Vpc                               vpc            create     
 +      └─ aws:ec2:Vpc                             vpc            create     
 +         ├─ aws:ec2:Subnet                       vpc-private-3  create     
 +         │  └─ aws:ec2:RouteTable                vpc-private-3  create     
 +         │     ├─ aws:ec2:RouteTableAssociation  vpc-private-3  create     
 +         │     └─ aws:ec2:Route                  vpc-private-3  create     
 +         ├─ aws:ec2:InternetGateway              vpc            create     
 +         ├─ aws:ec2:Subnet                       vpc-private-1  create     
 +         │  └─ aws:ec2:RouteTable                vpc-private-1  create     
 +         │     ├─ aws:ec2:RouteTableAssociation  vpc-private-1  create     
 +         │     └─ aws:ec2:Route                  vpc-private-1  create     
 +         ├─ aws:ec2:Subnet                       vpc-private-2  create     
 +         │  └─ aws:ec2:RouteTable                vpc-private-2  create     
 +         │     ├─ aws:ec2:RouteTableAssociation  vpc-private-2  create     
 +         │     └─ aws:ec2:Route                  vpc-private-2  create     
 +         ├─ aws:ec2:Subnet                       vpc-public-2   create     
 +         │  ├─ aws:ec2:RouteTable                vpc-public-2   create     
 +         │  │  ├─ aws:ec2:RouteTableAssociation  vpc-public-2   create     
 +         │  │  └─ aws:ec2:Route                  vpc-public-2   create     
 +         │  ├─ aws:ec2:Eip                       vpc-2          create     
 +         │  └─ aws:ec2:NatGateway                vpc-2          create     
 +         ├─ aws:ec2:Subnet                       vpc-public-1   create     
 +         │  ├─ aws:ec2:Eip                       vpc-1          create     
 +         │  ├─ aws:ec2:RouteTable                vpc-public-1   create     
 +         │  │  ├─ aws:ec2:RouteTableAssociation  vpc-public-1   create     
 +         │  │  └─ aws:ec2:Route                  vpc-public-1   create     
 +         │  └─ aws:ec2:NatGateway                vpc-1          create     
 +         └─ aws:ec2:Subnet                       vpc-public-3   create     
 +            ├─ aws:ec2:Eip                       vpc-3          create     
 +            ├─ aws:ec2:RouteTable                vpc-public-3   create     
 +            │  ├─ aws:ec2:RouteTableAssociation  vpc-public-3   create     
 +            │  └─ aws:ec2:Route                  vpc-public-3   create     
 +            └─ aws:ec2:NatGateway                vpc-3          create     

Resources:
    + 34 to create

Do you want to perform this update? yes
Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/kyle-pulumi-corp/import/dev/updates/1

     Type                                          Name           Status              
 +   pulumi:pulumi:Stack                           import-dev     created (1s)        
 +   └─ awsx:ec2:Vpc                               vpc            created (1s)        
 +      └─ aws:ec2:Vpc                             vpc            created (1s)        
 +         ├─ aws:ec2:Subnet                       vpc-private-3  created (1s)        
 +         │  └─ aws:ec2:RouteTable                vpc-private-3  created (1s)        
 +         │     ├─ aws:ec2:RouteTableAssociation  vpc-private-3  created (1s)        
 +         │     └─ aws:ec2:Route                  vpc-private-3  created (1s)        
 +         ├─ aws:ec2:Subnet                       vpc-private-1  created (1s)        
 +         │  └─ aws:ec2:RouteTable                vpc-private-1  created (1s)        
 +         │     ├─ aws:ec2:RouteTableAssociation  vpc-private-1  created (0.93s)     
 +         │     └─ aws:ec2:Route                  vpc-private-1  created (1s)        
 +         ├─ aws:ec2:InternetGateway              vpc            created (1s)        
 +         ├─ aws:ec2:Subnet                       vpc-private-2  created (1s)        
 +         │  └─ aws:ec2:RouteTable                vpc-private-2  created (1s)        
 +         │     ├─ aws:ec2:RouteTableAssociation  vpc-private-2  created (13s)       
 +         │     └─ aws:ec2:Route                  vpc-private-2  created (1s)        
 +         ├─ aws:ec2:Subnet                       vpc-public-3   created (12s)       
 +         │  ├─ aws:ec2:RouteTable                vpc-public-3   created (0.81s)     
 +         │  │  ├─ aws:ec2:RouteTableAssociation  vpc-public-3   created (2s)        
 +         │  │  └─ aws:ec2:Route                  vpc-public-3   created (2s)        
 +         │  ├─ aws:ec2:Eip                       vpc-3          created (1s)        
 +         │  └─ aws:ec2:NatGateway                vpc-3          created (105s)      
 +         ├─ aws:ec2:Subnet                       vpc-public-1   created (13s)       
 +         │  ├─ aws:ec2:RouteTable                vpc-public-1   created (1s)        
 +         │  │  ├─ aws:ec2:RouteTableAssociation  vpc-public-1   created (1s)        
 +         │  │  └─ aws:ec2:Route                  vpc-public-1   created (1s)        
 +         │  ├─ aws:ec2:Eip                       vpc-1          created (1s)        
 +         │  └─ aws:ec2:NatGateway                vpc-1          created (105s)      
 +         └─ aws:ec2:Subnet                       vpc-public-2   created (13s)       
 +            ├─ aws:ec2:RouteTable                vpc-public-2   created (1s)        
 +            │  ├─ aws:ec2:RouteTableAssociation  vpc-public-2   created (2s)        
 +            │  └─ aws:ec2:Route                  vpc-public-2   created (2s)        
 +            ├─ aws:ec2:Eip                       vpc-2          created (2s)        
 +            └─ aws:ec2:NatGateway                vpc-2          created (106s)      

Resources:
    + 34 created

Duration: 2m14s

% pulumi preview --import-file some-json.json
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/kyle-pulumi-corp/import/dev/previews/2611e7b9-9c6e-451d-bae9-52452107d554

     Type                 Name        Plan     
     pulumi:pulumi:Stack  import-dev           

Resources:
    34 unchanged

% cat some-json.json 
{
    "resources": null
}
```

**Comment by dixler** [comment] 2024-01-05 18:12
@Frassle should this be `[]` instead of `null`?

**Comment by Frassle** [comment] 2024-01-05 19:28
> should this be [] instead of null as there will be no creates in the preview described?

It should probably not write out at all. Missing an "omitempty" on the struct tag I expect.

**Comment by phillipedwards** [comment] 2024-01-05 19:43
@dixler important to note, the program in which `preview --import-file...` generates the null resource object actually contains a single s3 bucket, so I'd expect resources to be populated with a single object that represents the s3 bucket. Or maybe I'm missing something?

**Comment by Frassle** [comment] 2024-01-07 10:05
> Or maybe I'm missing something?

`--import-file` only fills in imports for resource that the preview want's to create. So if you've run `up` to create the bucket then run `preview --import-file` that _should_ return an empty import file.

**Comment by phillipedwards** [comment] 2024-01-07 14:50
The panic on the other example (awsx vpc) had me a bit confused, but producing a no-op import file if nothing needs to be imported makes sense.

**Comment by phillipedwards** [comment] 2024-01-09 04:53
@dixler I'm in favor of closing this out as the panic is tracked by #15002 unless you see otherwise.

**Closed** 2024-01-16 16:02 UTC
Labels: kind/bug, area/import
