### ISSUE TITLE
Unable to try/except azure.storage.CustomerManagedKey in python

### ISSUE THREAD

**Issue by edstancu** [pulumi/pulumi#16893] opened 2024-08-06 19:47 UTC
### What happened?

In our use case we have the need to deploy key vaults and storage accounts, the order an HSM key from another team and finally encrypt the storages with the HSM key.
We do the following in a pulumi program
- deploy the storage
- assign the storage managed identity RBAC role on the KV that gives permission on the keys
- create a azure.storage.CustomerManagedKey resource to encrypt the storage.
- the azure.storage.CustomerManagedKey has a dependsOn the role assignment created one step before.

However, it seems the role assignment does not have effect immediately and for the first pulumi up we always get AuthenticationError on the Kv for the storage account. Immediately re-running pulumi up works.
I have tries to create the azure.storage.CustomerManagedKey resource inside a for loop and a try/except block, where it should theoretically try 3 times to encrypt with a sleep of 3 minutes between the tries (more than enough for the role assignment to come into effect)
However, this does not work and the azure.storage.CustomerManagedKey returns error after the first try, meaning that the error is not catchable.
Do you have any suggestion?
We would either need the resource creation errors to be catchable in try/except blocks or a retry resource option possibility.

Thanks,
Elena

### Example

```python
def encrypt_byok(storage_name, storage_id, key_vault_id, kv_key_name: str, role_assignment, preview):
    for i in range(5):
        try:
            if not preview:
                time.sleep(180)
            encryption = pulumi_azure.storage.CustomerManagedKey(
                f"storageAccount_{storage_name}_encryption",
                storage_account_id=storage_id,
                key_vault_id=key_vault_id,
                key_name=kv_key_name,
                opts=pulumi.ResourceOptions(depends_on=[role_assignment]),
            )
            return encryption.id

        except Exception:
            pass
```

### Output of `pulumi about`

```
[tool.poetry.dependencies]
python = "^3.9"
pulumi = "^3.109"
msal = "^1.27"
requests = "^2.32"
rauth = "0.7.3"

# Pulumi Plugin versions
# (must be consistent with versions in stack.py)
pulumi-azure-native = "^2.32"
pulumi-azuread = "^5.47"
pulumi-azure = "^5.68"
ediri-azapi = "~1.11" # AzAPI 1.12 is broken, see https://github.com/dirien/pulumi-azapi/issues/206
setuptools = "^70.0.0"
pulumi-databricks = "^1.45.0"
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-08-06 20:21
I suspect this is already covered by issues such as https://github.com/pulumi/pulumi/issues/7932 and https://github.com/pulumi/pulumi/issues/9041.

I do think this is probably something we have the foundations in place to go look at now. In the meantime you could take one of the outputs of the role and call `apply` on it and inside poll using the azure sdk to see if the role is "ready" (I'm not an azure expert so not sure exactly what this would look like). If you use that resulting output as an input to the azure.storage.CustomerManagedKey resource then the resource won't actually send to the engine to create till your loop finishes.

**Comment by justinvp** [comment] 2024-08-09 22:07
Closing as duplicate of those issues. The approach Fraser mentions should allow working around this in the meantime.

**Closed by justinvp** 2024-08-09 22:07 UTC
Labels: kind/bug, resolution/duplicate
