### ISSUE TITLE
Run Pulumi from different machines referencing local paths

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi#5066] opened 2020-07-27 20:50 UTC
I am creating a resource in a remote CI pipeline,

the stack uses a `FileAsset`;

the path of the file on my local machine differs from the one on the build agent, therefore Pulumi forces a change to the stack when the last run was from a different machine (remote/local). This is not ideal as you can't debug/run locally and then push changes to the CI pipeline.

I tried to use `IgnoreChanges`, but that doesn't work as it ignores the change, but still wants to access to the path in the stack which is not available.

Is there any way around this?

Thank you

my code:

```fsharp
Blob("blobName",
     BlobArgs(
                 StorageAccountName = (io storage.Name),
                 StorageContainerName = (io buildContainer.Name),
                 Source = (input (Config().Require("ApiBuild") |> FileAsset :> AssetOrArchive)),
                 Type = input "Block"
             ),
     CustomResourceOptions(
                              // With this line uncommented, I get: 
                              //           error: failed to open asset file '/home/vsts/work/1/a/...': open /home/vsts/work/1/a/...: no such file or directory
                              // With the line commented I get a replace result as the path/file differ from the one described in the stack
                              //IgnoreChanges = (new List<string>(["source"]))
                          ))
```

**Comment by leezen** [comment] 2020-07-27 23:16
I'm a bit confused since it reads like you're reading the config to provide the path, so I would expect that to be the same both locally and remotely in CI? What is the diff you're seeing? Typically, I would expect the path to be a relative path for some file and these to be the same both locally and in CI.

**Comment by UnoSD** [comment] 2020-07-28 04:46
@leezen I am setting the config in the pipeline before `pulumi preview` (and one off locally).

Even if it was relative, that would mean that I need to have the same number of levels in the structure. Forcing it still feels wrong.

I am quite new to Pulumi so I may be approaching this the wrong way, please let me know if there is a preferred way to achieve the same.

**Comment by leezen** [comment] 2020-07-28 15:41
There's technically nothing wrong with what you're trying to do. The underlying provider translates the `FileAsset` to a path, so the paths will need to match in order for it not to diff. One workaround for your scenario might be to read the file into memory and use `sourceContent` instead.

**Comment by UnoSD** [comment] 2020-07-28 20:26
Thanks, I can try that, it's 4MB, shouldn't really impact the duration of the run.

**Comment by UnoSD** [comment] 2020-07-28 22:58
Somehow, that did not work. I exported the exact same file from the pipeline and used it locally and somehow it picks up the change in DevOps

**Comment by mikhailshilkov** [comment] 2022-06-14 13:07
I feel like this is by design and Lee has explained it well, including the workaround. I'll go ahead and close the issue.

**Closed by mikhailshilkov** 2022-06-14 13:07 UTC
Labels: kind/question, resolution/by-design, area/file
