### ISSUE TITLE
Add ability to include and exclude files from a file archive based on glob patterns

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#14456] opened 2023-10-31 10:40 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

If a user has a folder they want to zip but ignores some of the contents, they can't use `pulumi.asset.FileArchive` unless they do work upfront. 

I'm thinking something like this:

```typescript
let assetArchive = new pulumi.asset.AssetArchive({
    ".": new pulumi.asset.FileArchive("./folder", 
            "*", // include
             "**/**/node_modules"),// exclude
});
```

So this would include everything except the `node_modules` folders.

**Comment by Frassle** [comment] 2023-10-31 10:43
Duplicate of https://github.com/pulumi/pulumi/issues/9059

**Closed by Frassle** 2023-10-31 10:43 UTC
Labels: kind/enhancement, resolution/duplicate
