### ISSUE TITLE
Pulumi MSI Installer for 3.110.0 Flagged as containing a Trojan

### ISSUE THREAD

**Issue by jmthomas73** [pulumi/pulumi#15728] opened 2024-03-19 18:50 UTC
### What happened?

When prompted for a new version at the cli, after directly downloading the 64-bit MSI installer from the provided link, Windows Defender blocked it for containing "Trojan:Script/Wacatac.B!ml". I stopped trying to install rather than overriding, because the MSI package also isn't code signed, so I had no way to verify it wasn't a valid alert.

### Example

![image](https://github.com/pulumi/pulumi/assets/145070128/27892421-8411-46df-b2c1-e1273c7b9792)

### Output of `pulumi about`

No longer relevant. I've now installed 3.111.1 without issue (other than still not being signed).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-03-19 22:07
I tried downloading the msi for 3.110 and running defender on it yesterday when this came up on community slack but it didn't flag anything for me.

**Comment by justinvp** [comment] 2024-03-22 10:19
Sorry for the trouble @jmthomas73 and thanks for reporting this! This looks like a duplicate of https://github.com/pulumi/pulumi-winget/issues/20. We're actually actively working on getting new releases of the .msi installer signed, which should mitigate this.

**Closed by justinvp** 2024-03-22 10:19 UTC
Labels: kind/bug, resolution/duplicate
