### ISSUE TITLE
replaceOnChanges with asterisk not parsed

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi#8546] opened 2021-12-05 15:12 UTC
## Issue details

I'm trying to use replaceOnChanges for an item in a list as stated with the [docs](https://www.pulumi.com/docs/intro/concepts/resources/#replaceonchanges):
```
	cluster, err := containerservice.NewManagedCluster(ctx, "aks", clusterArgs, 
 pulumi.ReplaceOnChanges([]string{"agentPoolProfiles[*].vmSize"}), pulumi.DeleteBeforeReplace(true))
```

It fails to parse:
```
Diagnostics:
  azure-native:containerservice/v20210501:ManagedCluster (aks):
    error: invalid array index: strconv.ParseInt: parsing "*": invalid syntax
```

I'm using CLI & SDK version v3.19.0 and azure-native version v1.48.0

**Comment by emiliza** [comment] 2021-12-08 22:23
Interesting - that looks valid. @iwahbe you've been in this area recently, any ideas on what's going on?

**Comment by emiliza** [comment] 2021-12-08 22:29
Looks like this may be a dupe of https://github.com/pulumi/pulumi/issues/8197 which also has a workaround. I'll close this issue in favor of that one, and can bring the conversation there.

**Closed** 2021-12-08 22:29 UTC
Labels: kind/bug, resolution/duplicate
