### ISSUE TITLE
Pluggable Config

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#12528] opened 2023-03-27 19:32 UTC
Currently, configuration is set in a YAML file and doesn't have a whole bunch of flexibility.

```
// read from stack yaml file
const config = pulumi.Config()
```

What if config was _pluggable_ ?

```
stack_name = pulumi.get_stack()
const config = pulumi.Config({
  reader: readFileSync(`./Pulumi.{stack_name}.json`
})
```

You could essentially resolve config from anywhere, including a database or parameter store 🤔

**Comment by Frassle** [comment] 2023-03-27 20:09
Isn't this https://github.com/pulumi/pulumi/issues/11550?

**Comment by justinvp** [comment] 2023-03-29 12:59
Closing as duplicate of https://github.com/pulumi/pulumi/issues/11550

**Closed by justinvp** 2023-03-29 12:59 UTC
Labels: kind/enhancement, needs-triage, resolution/duplicate

**Comment by matusnovak** [comment] 2023-06-07 22:30
The #11550 is not a duplicate. That is about hierarchical config values in the yaml file. I believe OP here is suggesting to load config values programmatically.

**Comment by Frassle** [comment] 2023-06-08 08:19
> That is about hierarchical config values in the yaml file.

Yes but the point of that hierarchy is to load the values form other locations/stores. That would be extendable via a plugin system.

> I believe OP here is suggesting to load config values programmatically.

I see the pulumi concept of "config" as "data that the engine can understand and manipulate". If you want to load further data inside your program to manipulate how it runs you can also do that, but I don't see how the engine or framework would understand that in general, or why it would need to (your programs already running).

So this is either a duplicate if the request is "some way to load config values from other stores" or a (probably) wont-do if the request is "framework support to load config programmatically".
