### ISSUE TITLE
Using pulumi latest fails in combination with terraform-bridge

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi#13114] opened 2023-06-07 00:24 UTC
### What happened?

I ran `make tfgen` using pulumi latest and received the following errors:

```
# github.com/pulumi/pulumi/pkg/v3/resource/deploy/deploytest
../../pulumi/pkg/resource/deploy/deploytest/languageruntime.go:31:9: cannot use &languageRuntime{…} (value of type *languageRuntime) as plugin.LanguageRuntime value in return statement: *languageRuntime does not implement plugin.LanguageRuntime (wrong type for method GenerateProject)
                have GenerateProject(string, string, string) (hcl.Diagnostics, error)
                want GenerateProject(string, string, map[string]string) error
# github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tf2pulumi/il
/Users/guin/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.49.0/pkg/tf2pulumi/il/plugin_info.go:53:46: not enough arguments in call to mapper.mapper.GetMapping
        have (string, string)
        want ("context".Context, string, string)
make: *** [tfgen] Error 1
```

### Expected Behavior

I expected my schema to get generated.

### Steps to reproduce

1. Pull pulumi master
2. Pick any provider; in provider/go.mod add a replace statement:
`replace github.com/pulumi/pulumi/pkg/v3 => <local-path>/pulumi/pkg`
3. go mod tidy
4. cd .. && make tfgen

### Output of `pulumi about`

CLI          
Version      3.65.2-dev.0
Go Version   go1.19.2
Go Compiler  gc

Host     
OS       darwin
Version  11.7.1
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/guinevere-pulumi-corp
User           guinevere-pulumi-corp
Organizations  guinevere-pulumi-corp, pulumi

### Additional context

[This function changed recently](https://github.com/pulumi/pulumi/blob/master/proto/pulumi/language.proto#L154).

Checking out `sdk/v0.69.0` works nicely, so I'm personally unblocked.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2023-06-07 00:32
See https://github.com/pulumi/pulumi/pull/13102

> This will require a small fix up in terraform-bridge when it updates to this version of pulumi/pkg.

**Comment by Frassle** [comment] 2023-06-07 07:39
This is fixed in the latest terraform-bridge (https://github.com/pulumi/pulumi-terraform-bridge/commit/66d3adaa5e22aec92432d03fbff418e42cf7c1a2#diff-f59e8b34f2f141c66c113954feb871f24561e975627761aa4570df7576796aac). So if you update both dependencies things should build fine.

We'll probably want to break this one more time to move these interfaces to sdk/go instead of pkg and rewrite them with struct parameters in case we need to add more inputs or outputs in the future.

**Comment by guineveresaenger** [comment] 2023-06-07 17:26
unfortunately I updated both and it does not work with the tip of p/p:

go.mod:
```
require(
...
github.com/pulumi/pulumi-terraform-bridge/v3 v3.49.0
github.com/pulumi/pulumi/pkg/v3 v3.69.0 
github.com/pulumi/pulumi/sdk/v3 v3.69.0
)
replace( 
github.com/pulumi/pulumi/pkg/v3 => ../../pulumi/pkg
)
```

**Comment by Frassle** [comment] 2023-06-07 17:41
I commented this internally in slack, but worth posting here as well:

We do not expect different versions of sdk and pkg to work with each other. sdk/go/common is a bit of an odd codebase because some of it's used externally but a lot is core stuff only used by the engine and we often change that code in API breaking ways because we're changing the engine at the same time.

If your using tip of pkg you also need to be using tip of sdk.

**Comment by justinvp** [comment] 2023-07-26 22:14
I'm going to close this by design per Fraser's comment:

> If your using tip of pkg you also need to be using tip of sdk

**Closed by justinvp** 2023-07-26 22:14 UTC
Labels: kind/bug, area/sdks, area/codegen, resolution/by-design
