### ISSUE TITLE
Nodejs >v18 throws exception

### ISSUE THREAD

**Issue by j-fulbright** [pulumi/pulumi#16596] opened 2024-06-24 17:53 UTC
### What happened?

Upgrading my dependencies to latest, pulled in Azure Native v2.47.0 and builds were all failing. I thought this was due to my changes but removing my changes still caused failures. 

Downgrading and pinning to 2.46.0 fixed all issues

![image](https://github.com/pulumi/pulumi-azure-native/assets/10793868/c698a9e3-ccbc-48cc-8f27-5fd439790e26)

### Example

```typescript
resourceGroupName: `rg-${suffix}`,
    location: 'centralus',
});

// TODO figure out how to handle password if we intend to do those
const sqlServer = new azureNative.sql.Server(
    `sql-${pulumi.getStack()}`,
    {
        serverName: `${suffix}`,
        resourceGroupName: resourceGroup.name,
        location: resourceGroup.location,
        administratorLogin: ######
        administratorLoginPassword: #######
        publicNetworkAccess: ServerPublicNetworkAccessFlag.Enabled,
        restrictOutboundNetworkAccess: ServerNetworkAccessFlag.Disabled,
        // minimalTlsVersion: '1.2',

        version: '12.0',
    },
    { parent: resourceGroup },
);
```

### Output of `pulumi about`

This was running via github action but i can run again to verify versions if needed

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by julienp** [comment] 2024-07-08 15:43
From the stack trace it looks like this is somewhere in the nodejs/v8 debugger API, which we use for function serialisation. This is used for "magic functions" (where you inline Serverless function code right in your Pulumi program), and dynamic providers.

@yuft @j-fulbright do you use this functionality in your programs? Do you see the errors only on Linux machines in CI, or also locally? On other platforms than Linux?

**Comment by j-fulbright** [comment] 2024-07-08 23:13
@julienp I dont believe I'm using anything special. I'm not sure about the "magic functions", but the only providers we use are the default Azure classic and Native ones. Nothing special.

**Comment by yuft** [comment] 2024-07-08 23:26
In our cases where we see the v8 error often when running nodejs Linux containers on our self-hosted K8s clusters, we have a custom function that executes [kubelogin](https://github.com/Azure/kubelogin) command. We use both Pulumi Azure native and Kubernetes providers. I am not sure if this is a "magic function".

example code is [here](https://github.com/yuft/pulumi-quick-start/blob/main/src/infrastructure/src/azure/k8s-provider.ts)

We experience the errors only in the self-hosted CI enviroment.
- Linux container(experienced the error using both official node 20 and 22 images). The pulumi nodejs image has no issue because it has node 18.
- AKS 1.27.9, Ubuntu 22.04.
- I suspected it was caused by https://github.com/nodejs/node/issues/48444, but setting `export UV_USE_IO_URING=0` did not make any differences.

**Comment by UnstoppableMango** [comment] 2024-07-09 03:56
I'm getting this in GitHub actions deploying to Azure. I'd been slowly downgrading Node to see if that fixed anything until finding this issue, but I'll give v18 a try now. My program is pretty small, this occurs _nearly_ every time when running in GitHub actions, but rarely when running locally.

<details>
<summary><code>pulumi about</code> with some info redacted</summary>

```text
CLI          
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.48.0
language  nodejs        unknown

Host     
OS       debian
Version  bookworm/sid
Arch     x86_64

This project is written in nodejs: executable='/home/<username>/.nvm/versions/node/v20.15.1/bin/node' version='v20.15.1'

Current Stack: UnstoppableMango/<my-project-name>/prod

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:prod::<my-project-name>::pulumi:pulumi:Stack::<my-stack-name>
pulumi:providers:azure-native         urn:pulumi:prod::<my-project-name>::pulumi:providers:azure-native::default_2_49_0
azure-native:resources:ResourceGroup  urn:pulumi:prod::<my-project-name>::azure-native:resources:ResourceGroup::rg
azure-native:web:StaticSite           urn:pulumi:prod::<my-project-name>::azure-native:web:StaticSite::app


Found no pending operations associated with prod

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/UnstoppableMango
User           UnstoppableMango
Organizations  UnstoppableMango
Token type     personal

Dependencies:
NAME                  VERSION
@pulumi/azure-native  2.49.0
@pulumi/pulumi        3.122.0
@types/node           20.14.10
typescript            5.5.3
```
</details>

<details>
<summary>index.ts</summary>
```typescript
import * as az from '@pulumi/azure-native';
import * as pulumi from '@pulumi/pulumi';

const stack = pulumi.getStack().toUpperCase();
const resourceGroup = new az.resources.ResourceGroup('rg', {
	resourceGroupName: `MyResourceGroup-${stack}`,
});

const site = new az.web.StaticSite('app', {
	resourceGroupName: resourceGroup.name,
	sku: {
		tier: 'Free',
		name: 'Free',
	},
	provider: 'Other',
	repositoryUrl: 'https://github.com/UnstoppableMango/<my-repo-name>',
	branch: 'main',
	buildProperties: {
		skipGithubActionWorkflowGeneration: true,
	},
});

export const resourceGroupId = resourceGroup.id;
export const appName = site.name;
export const scmProvider = site.provider;
```
</details>

**Comment by aureq** [comment] 2024-07-09 04:22
@UnstoppableMango If this is possible, could you share with us the declaration of your GitHub Action please? It would be helpful to us to replicate this on our own with your exact settings.

Additionally, if you could update your comment above and past the crash, that would be most helpful.

**Comment by UnstoppableMango** [comment] 2024-07-09 05:03
Sure, I've updated my comment.

Node v18 seems to be working better, but I don't have as many CI runs under my belt to verify that yet

**Comment by julienp** [comment] 2024-07-09 12:45
Thank you everyone for the additional information. I was able to reproduce this in Github Actions. After patching out our usage of the debugger API (which is what is showing up in the original stack traces), I get a much more familiar stack trace:

```
    pulumi:pulumi:Stack (pulumi-16596-repro-prod):
      <--- Last few GCs --->
      [1801:0x62c2d70]    32167 ms: Scavenge (reduce) 2045.5 (2080.9) -> 2045.0 (2081.2) MB, 18.84 / 0.00 ms  (average mu = 0.098, current mu = 0.003) allocation failure;
      [1801:0x62c2d70]    33511 ms: Mark-Compact (reduce) 2045.8 (2081.2) -> 2045.2 (2081.7) MB, 1341.76 / 0.00 ms  (average mu = 0.066, current mu = 0.034) allocation failure; scavenge might not succeed
      <--- JS stacktrace --->
      FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
      ----- Native stack trace -----
       1: 0xb80c78 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [/opt/hostedtoolcache/node/20.15.0/x64/bin/node]
       2: 0xeee1b0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/opt/hostedtoolcache/node/20.15.0/x64/bin/node]
...
``` 

We're running out of memory! Given that it does not fail 100% of the time, we must be right on the edge of the limit. 

Github Actions runners have 7GB of memory for private repos, and 16GB for public repos https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

Nodejs configures the default limit for the heap based on the system it's running on. I remember this heuristic having occasionally changed in the past. Additionally, in containerised environments, this tries to take into account the available memory for the container, as opposed to total system memory. However this detection does not always work, for example older versions of nodejs (before 20.x) don't detect container memory limits when using cgroups v2 https://github.com/nodejs/node/issues/47259. This was fixed in Nodejs 20.


```
# simulate private runner with 7GB of memory
docker run --rm -it --memory 7168m node:18 node -e 'console.log(require("v8").getHeapStatistics().heap_size_limit)'
> 4345298944
docker run --rm -it --memory 7168m node:20 node -e 'console.log(require("v8").getHeapStatistics().heap_size_limit)'
> 2197815296

# simulate public runner with 16GB of memory
docker run --rm -it --memory 16384m node:18 node -e 'console.log(require("v8").getHeapStatistics().heap_size_limit)'
> 4345298944
docker run --rm -it --memory 16384m node:20 node -e 'console.log(require("v8").getHeapStatistics().heap_size_limit)'
> 4345298944
```

The result is that when running with Nodejs 20, we have less memory available for the heap. Since the azure provider is very large, we run into the limit.

To work around this, you can explicitly set the heap size for nodejs in `Pulumi.yaml`

```yaml
runtime:
  name: nodejs
  options:
    nodeargs: --max-old-space-size=4096
```

**Comment by aureq** [comment] 2024-07-09 22:45
@julienp thanks a lot for the thorough investigation and the clear explanation. Given the cryptic error message and the increased risk of bumping onto this issue, is there anything we should do to 1) try to mitigate this issue without user intervention? and 2) increase awareness and visibility so people find the workaround you proposed more easily?

**Comment by julienp** [comment] 2024-07-12 16:27
> is there anything we should do to 1) try to mitigate this issue without user intervention? and 2) increase awareness and visibility so people find the workaround you proposed more easily?

Definitely! I am not sure yet what the best way forward is, but at a minimum if we can't handle this automatically, we should be able to tell users via a warning or other message to apply the workaround.

**Closed** 2024-07-23 17:15 UTC
Labels: kind/bug, language/javascript
