### ISSUE TITLE
Show clear indication when making changes that delete data

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1420] opened 2018-05-23 19:11 UTC
Some changes to dynamo DB properties will cause it to be deleted and recreated, along with any data that was stored. Unfortunately, the preview does not make this clear.

Beta user feedback:

> When I changed my table's primary key, all of my data was unceremoniously deleted, while the preview made it sound like "changes: ~ primary key" or such, which sounds safe.  Any table delete should require extreme confirmation, since you may well be deleting years of user data

**Comment by lukehoban** [comment] 2018-07-12 22:17
Closing this out as mostly a dupe of #782.

**Closed by lukehoban** 2018-07-12 22:17 UTC
Labels: customer/feedback, impact/usability
