### ISSUE TITLE
Multi-lang components can't access config

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7150] opened 2021-05-27 05:24 UTC
Inside multi-lang components, `aws.config.region` is not defined, because `let __config = new pulumi.Config("aws"); __config.get("region")` does not work, presumably because the Node language host used for multi-lang components is not being passed `PULUMI_CONFIG` correctly.

It is likely this is the same root cause as https://github.com/pulumi/pulumi/issues/5582, but impacting multi-lang components instead of automation API.

**Comment by pierskarsenbarg** [comment] 2021-05-27 07:47
There's probably a use case that I'm not seeing, however, is this such a problem?

 If I'm building a component, be it multi-lang or not, I wouldn't expect the component to be reliant on what's in the config. I would expect it to be passed in through the args parameter. Or (in the case of the region) as a provider if it's different from the one I've got in `aws:region`. I would hope that the component wouldn't have a dependency on what's in the config which would mean a working knowledge of how the component worked rather than the black box I would hope it to be.

**Comment by lukehoban** [comment] 2021-05-27 09:00
The specific case I hit is https://github.com/lukehoban/pulumi-package-aws-apigateway/blob/main/provider/cmd/pulumi-resource-apigateway/restAPI.ts#L36 which is due to https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/utils.ts#L130. 

That may be a slightly unusual pattern - but I expect it's largely necessary to do thing somewhat like this to pick up the AWS region to use.

**Comment by lukehoban** [comment] 2021-05-27 09:02
> I would expect it to be passed in through the args parameter

AWS region never has to be passed as a parameter for other resources today. I would not expect it to have to be an explicit parameter. I would expect it to be inherited from the provider. 

Arguably, the default provider configuration should be directly accessible so that `AWS.config.region` doesn't need to be used as the fallback here. It might be that is another improvement we should make here. But I'd be surprised if we actually *want* config to be inaccessible to components.

**Comment by pierskarsenbarg** [comment] 2021-05-27 09:14
I wouldn't expect the region to be passed through in the args: 

> Or (in the case of the region) as a provider if it's different from the one I've got in aws:region

Having the config accessible in the components means that the user has to know exactly what is going on within the component. If you're passing the value in as an argument, you can document it that way and the end user doesn't need to know or care.

As long as the default provider (or any provider I choose to pass in through args or `ComponentResourceOptions`) should be accessible (if it's not already). In my opinion.

Also, assuming that our native providers are going to follow the same route as the Azure Native one, `azure-native.config.location` doesn't exist in the same way that `azure.config.location` exists so it's possibly not future-proof either.

**Comment by justinvp** [comment] 2021-05-27 16:57
The workaround is to not use `aws.config.region` and instead get the value explicitly via `new pulumi.Config("aws").("region")`.

**Comment by infin8x** [comment] 2021-06-11 21:13
Duplicate of #5882

**Closed by infin8x** 2021-06-11 21:13 UTC
Labels: area/multi-language-components, feature/multi-language, kind/bug, resolution/duplicate

**Comment by lukehoban** [comment] 2021-06-11 21:16
#5882 doesn’t seem to be related. Is there another issue tracking this?

**Comment by justinvp** [comment] 2021-06-11 21:59
I think @infin8x meant #5582
