### ISSUE TITLE
Import renders at top of resource docs page

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi#12843] opened 2023-05-08 14:20 UTC
### What happened?

Import sections, which should appear at the bottom of a docs page, are rendering first for some resources in the registry:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/410614/236848611-5cad717a-cb3b-404d-b105-b75b3f54a43f.png">

### Expected Behavior

Import should be rendered last, not first.

### Steps to reproduce

See: https://www.pulumi.com/registry/packages/snowflake/api-docs/externalfunction/

### Output of `pulumi about`

n/a

### Additional context

I've seen this issue many times in the past, and I could've sworn there was already an issue for it, but I could not find it.

Filing the issue here because I am assuming that the issue is in tfgen incorrectly identifying the Import section and that the Registry just renders whatever is in the schema.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment] 2023-05-10 12:21
Looking at the resource template which generates these pages, it seems correct: the [import](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/templates/resource.tmpl#L316) part is at the end of the markdown file so I am not exactly sure why it took import at the beginning 🤔

**Comment by lukehoban** [comment] 2023-05-10 13:05
Closing as dupe of https://github.com/pulumi/docs/issues/4793. Though the problem itself is most likely in tfbridge or docsgen.

**Closed by lukehoban** 2023-05-10 13:05 UTC
Labels: kind/bug, resolution/duplicate
