### ISSUE TITLE
Bad request when renaming stack

### ISSUE THREAD

**Issue by fernandocarletti** [pulumi/pulumi#2873] opened 2019-06-24 17:35 UTC
While trying to rename a stack, a bad request message is shown:

```bash
$ pulumi --verbose 4 stack rename prod
error: [400] Bad Request: could not deserialized deployment
```

**Comment by stack72** [comment] 2019-06-24 19:27
So I am seeing something slightly different here...

I have created a new stack and I can rename it but it throws an error when it can't find the yaml file

```
Code/pulumi-testing/newrelic-gh-10
▶ pulumi stack init test-stack
Created stack 'test-stack'

Code/pulumi-testing/newrelic-gh-10
▶ ls -la
total 128
drwxr-xr-x   9 stacko  staff    288 24 Jun 20:59 .
drwxr-xr-x  18 stacko  staff    576 24 Jun 20:52 ..
-rw-------   1 stacko  staff     21 24 Jun 20:52 .gitignore
-rw-------   1 stacko  staff     86 24 Jun 20:52 Pulumi.yaml
-rw-------   1 stacko  staff    505 24 Jun 20:59 index.ts
drwxr-xr-x  79 stacko  staff   2528 24 Jun 20:53 node_modules
-rw-r--r--   1 stacko  staff  44498 24 Jun 20:53 package-lock.json
-rw-------   1 stacko  staff    196 24 Jun 20:53 package.json
-rw-------   1 stacko  staff    522 24 Jun 20:52 tsconfig.json

Code/pulumi-testing/newrelic-gh-10
▶ pulumi stack rename prod
error: renaming Pulumi.test-stack.yaml to Pulumi.prod.yaml: rename /Users/stacko/Code/pulumi-testing/newrelic-gh-10/Pulumi.test-stack.yaml /Users/stacko/Code/pulumi-testing/newrelic-gh-10/Pulumi.prod.yaml: no such file or directory

Code/pulumi-testing/newrelic-gh-10                                                                                                                          ⍉
▶ pulumi stack ls
NAME   LAST UPDATE     RESOURCE COUNT  URL
prod*  51 seconds ago  0               https://app.pulumi.com/stack72/newrelic-gh-10/prod
```

**Comment by fernandocarletti** [comment] 2019-06-24 20:33
I'm wondering if the issue I'm having happens because the stack belongs to an organization. Right now I have an error if I put the stack name with the organization slug:

```bash
# The original stack is called "myorg/root"
$ pulumi stack rename myorg/prod
error: [400] Bad Request: A stack name may only contain alphanumeric, hyphens, underscores, or periods.
```

**Comment by stack72** [comment] 2019-06-24 20:35
ok @fernandocarletti 

This is super useful!! This could be related to another bug we are seeing with org/stack combos!

Thanks for this

**Comment by clstokes** [comment] 2019-07-15 22:09
I get this same error for stacks that are not within an organization, so it does not seem limited to just that use case.

```
$ pulumi stack
Current stack is dev:
    Owner: clstokes
    Last updated: 13 minutes ago (2019-07-15 14:55:01.181572 -0700 PDT)
    Pulumi version: v0.17.22
Current stack resources (1):
    TYPE                 NAME
    pulumi:pulumi:Stack  pulumi-template-file-dev

More information at: https://app.pulumi.com/clstokes/pulumi-template-file/dev

Use `pulumi stack select` to change stack; `pulumi stack ls` lists known ones
$ pulumi stack rename asdf
error: [400] Bad Request: could not deserialized deployment
```

**Comment by chrsmith** [comment] 2019-07-19 15:19
Nabbing this one while Matt is OOO

**Comment by chrsmith** [comment] 2019-07-19 16:00
So I took a look into this, and while there are a some UX type issues related to stack renames (called out in #2952), this particular `error: [400] Bad Request: could not deserialized deployment` comes from the Pulumi Service not being able to parse the checkpoint file.

Specifically, and surprisingly, this function is failing:
https://github.com/pulumi/pulumi/blob/master/pkg/resource/stack/deployment.go#L139

@fernandocarletti , you should be able to confirm/reject this theory if you did the following:

```
# Export the checkpoint file for the stack.
pulumi stack select <stack-you-can't-rename>
pulumi stack export > checkpoint.json

# Switch to the file-backend and try to import.
pulumi login --local
pulumi stack init bug-repo
pulumi stack import < checkpoint.json

# Cleanup (remove the stack from the local backend, log into Pulumi)
pulumi stack rm bug-repro --yes # Will not remove stack resources
pulumi logout
pulumi login --cloud-url https://api.pulumi.com
```

I suspect that when you try to do that `stack import` for the local file backend, you will get an error message explaining whatever is "wrong" with the checkpoint. (Unknown version, of perhaps a JSON encoding error?)

I still cannot explain how you were able to get a stack's checkpoint into this state using the Pulumi Service, but it would be nice to at least determine if that (the state file being at some odd version) is the root cause.

**Comment by fernandocarletti** [comment] 2019-07-22 15:00
@chrsmith Here's the output I got following your instructions:

```bash
$ pulumi stack select organization/oldstack
$ pulumi stack export > checkpoint.json

$ pulumi login --local
Logged into foo.local as foouser (file:///Users/foouser)

$ pulumi stack init bug-repo
Enter your passphrase to protect config/secrets:
Re-enter your passphrase to confirm:
Created stack 'bug-repo'

$ pulumi stack import < checkpoint.json
error: 8 errors occurred:
    1) resource 'urn:pulumi:oldstack::fooproject::pulumi:pulumi:Stack::fooproject-oldstack' is from a different stack (oldstack != bug-repo)
    2) resource 'urn:pulumi:oldstack::fooproject::pulumi:providers:aws::default' is from a different stack (oldstack != bug-repo)
    3) resource 'urn:pulumi:oldstack::fooproject::aws:kms/key:Key::fooproject' is from a different stack (oldstack != bug-repo)
    4) resource 'urn:pulumi:oldstack::fooproject::aws:kms/alias:Alias::fooproject' is from a different stack (oldstack != bug-repo)
    5) resource 'urn:pulumi:oldstack::fooproject::pulumi:providers:mysql::fooproject' is from a different stack (oldstack != bug-repo)
    6) resource 'urn:pulumi:oldstack::fooproject::mysql:index/user:User::mysql-user' is from a different stack (oldstack != bug-repo)
    7) resource 'urn:pulumi:oldstack::fooproject::mysql:index/grant:Grant::mysql-user' is from a different stack (oldstack != bug-repo)
    8) importing this file could be dangerous; rerun with --force to proceed anyway

$ pulumi stack rm bug-repro --yes
error: failed to load checkpoint: blob (code=NotFound): stat /Users/foouser/.pulumi/stacks/bug-repro.json: no such file or directory

$ pulumi logout

$ pulumi login --cloud-url https://api.pulumi.com
Logged into pulumi.com as foouser (https://app.pulumi.com/foouser)

```

**Comment by geekflyer** [comment] 2019-07-24 01:05
getting that error as well:
```
➜  dialog-manager git:(cirrus-ci) p version            
v0.17.25
➜  dialog-manager git:(cirrus-ci) p stack rename foo-bar                   
error: [400] Bad Request: could not deserialized deployment
```

This is an org stack

**Comment by chrsmith** [comment] 2019-07-29 18:39
Thanks for the patience here, the `[400] Bad Request: could not deserialized deployment` error has to do with a bad interaction between the recent secrets provider work and the Pulumi Service. I'm working on a simplified repro and fix, I should have this resolved in the next day or so.

**Closed** 2019-08-03 17:47 UTC
Labels: feature/q3, kind/bug

**Comment by chrsmith** [comment] 2019-08-03 17:54
Sorry for the delay getting this out, but this should be fixed with the next Pulumi Service release this Tuesday. The underlying problem was related to the recent support for client-side secrets.

Renaming a stack is one of the few (only, actually) places where we need to deserialize the checkpoint file. (Since we need to update URNs to reflect the new stack name.) So if you were using client-side secrets, that deserialization would fail.

For future code archeologists, the fix here was to land https://github.com/pulumi/pulumi/pull/3001 and provide a way to provide a custom secrets manager when we deserialize the checkpoint file on the Pulumi Service. Specifically for the rename case, we don't need to see any encrypted data, just URNs for resources. So it's safe to use a "noop" type decrypter, and operate on the checkpoint file with cipher text for its secrets.

An alternate design would be to do that decrypt+edit+update entirely client-side (like other commands like `pulumi state unprotect`). But this approach caused the least amount of churn.  Though we may need to do that later if this "noop decrypter" causes problems down the road.
