### ISSUE TITLE
Run after Helm-Chart Rollout is completed (ex. RabbitMq)

### ISSUE THREAD

**Issue by haarchri** [pulumi/pulumi#5290] opened 2020-09-05 07:36 UTC
We have coded that uses the kuberentes and rabbitmq provider for rollout a rabbitmq in our kubernetes cluster. 
Would love if there was a flag or setting to run rabbitmq provider after the kubernetes provider completes - or did you guys have a idea to wait till helm chart is deployed ?

## Expected Behavior
rabbitmq provider: configur flag or setting to wait till rabbitmq is deployed via kubernetes provider / helm chart / endpoint available o.a.

## Steps to Reproduce
Rollout the following code: 
problem here is kubernetes and rabbitmq provider steps executed in parallel - unable to use depends on or something like that :/

```
import * as k8s from "@pulumi/kubernetes";
import * as rabbitmq from "@pulumi/rabbitmq";
import * as pulumi from "@pulumi/pulumi";

let config = new pulumi.Config();

//// helm-chart ////

const rmq = new k8s.helm.v3.Chart("rmq", {
    path: "./rabbitmq",
    namespace: pulumi.getStack(),
    values: {
        replicaCount: 2,
        image: {
            registry: "docker.io",
            repository: "bitnami/rabbitmq",
            tag: "3.8.8-debian-10-r0",
        },
        resources: {
            limits: {
                cpu: "2000m",
                memory: "2048M",
            },
            requests: {
                cpu: "500m",
                memory: "256M",
            }
        },
        extraPlugins: "rabbitmq_prometheus rabbitmq_web_stomp",
        auth: {
            username: "rabbitmq",
            password: "rabbitmq",
        },
        extraPorts: [
            {
                name: "stomp",
                port: 15674,
                targetPort: 15674,
            },           
        ],
        metrics: {
            enabled: true
        },
        memoryHighWatermark: {
            enabled: true,
            type: "relative",
            value: "0.2",
        },
        enabled: true
    },
});

//// vhost ////

const rabbitMqVhost = new rabbitmq.VHost("/", { name: "/"});

//// policys //// 

const HaPolicy = new rabbitmq.Policy("hapolicy", {
    name: "hapolicy",
    policy: {
        pattern: "^ha\\.",
        applyTo: "all",
        definition: {
            "ha-mode": "exactly",
            "ha-params": 2,
            "ha-sync-mode": "automatic"
        },
        "priority": 0
    },
    vhost: rabbitMqVhost.name,
});

//// queues ////

const QueueJobsStartAll = new rabbitmq.Queue("ha.jobs.start.all", {
    name: "ha.jobs.start.all",
    settings: {
        autoDelete: false,
        durable: true,
        arguments: {
            "x-queue-type": "classic",
        }
    },
    vhost: rabbitMqVhost.name,
});

```

**Comment by haarchri** [comment] 2020-09-24 19:29
did someone has an Idea how to proceed ?

**Comment by lblackstone** [comment] 2020-09-24 19:45
This is related to https://github.com/pulumi/pulumi-kubernetes/issues/861

You should be able to use the `getResource` method to force a dependency, similarly to this:

# Using `getResource` to depend on one or more chart resources that must be ready
https://github.com/pulumi/pulumi-kubernetes/blob/9878c2923626660766c5eef17095de6354529af9/tests/sdk/nodejs/istio/step1/istio.ts#L55

# Explicitly specifying these resources in the `dependsOn` opt
https://github.com/pulumi/pulumi-kubernetes/blob/9878c2923626660766c5eef17095de6354529af9/tests/sdk/nodejs/istio/step1/istio.ts#L68

**Comment by inglkruiz** [comment] 2021-03-19 11:52
@haarchri Did @lblackstone suggestion solve your issue? I'm trying more or less the same: I have a Chart, the Chart has a Secret where I declared a dummy value which I update in an initContainer, and I expect to be able to get the Secret Resource with its updated value BUT what I'm getting is the Secret with its dummy Value. Does Pulumi wait for initContainers and returns Artefacts' most recent data OR just the declared data? Am I trying something Pulumi is not capable of?

**Comment by haarchri** [comment] 2021-04-16 19:10
in our environment it is **only** working in kubernetes provider - and only in one provider - not between for example aws and kubernetes provider

**Comment by lblackstone** [comment] 2021-06-23 01:12
Closing as a dupe of https://github.com/pulumi/pulumi-kubernetes/issues/861

**Closed by lblackstone** 2021-06-23 01:12 UTC
Labels: kind/enhancement, resolution/duplicate
