### ISSUE TITLE
Project name in stack identity inconsistent between backends

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#2522] opened 2019-03-06 15:30 UTC
In https://github.com/pulumi/pulumi/pull/2386 it was changed so that http backends use the project in the stack identity. Why was this only done for http instead of for local backends? This is very inconsistent.

**Comment by ellismg** [comment] 2019-03-06 17:01
It was just an oversight, but we will be addressing it shortly.  There was already some skew here (the Pulumi service further scopes things by username, where as the local backend does not) but we should keep these in sync as possible.

**Comment by nesl247** [comment] 2019-03-06 17:14
Curious, does this type of skew not imply that the architecture could be improved? I would think this type of logic would not need to be implemented in each backend, but in a higher layer. The backend would only be responsible for the execution of whatever command it is receiving.

**Comment by rhyek** [comment] 2020-02-22 03:45
Any workarounds for this? I was planning to use multiple pulumi projects and during local development (using local pulumi state) I hit this road-block.

**Comment by JakeGinnivan** [comment] 2020-02-22 03:59
We fully qualify our stack names, ie project.env as the stack name. Bit clunky but works fine
________________________________

**Comment by nguyenxndaidev** [comment] 2020-03-01 11:59
For local development with local pulumi state, I organize my projects follow [Inter-Stack Dependencies](https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/#inter-stack-dependencies).

For all related projects, I configure `Pulumi.yaml` to point to the same `.pulumi` directory.

For example:
```
backend:
  url: file://../
```
This will use the `.pulumi` directory in the parent directory.

Then for each stack, I also add environment separated with a dot. For example: `Pulumi.network.dev.yaml`, `Pulumi.services.dev.yaml`, `Pulumi.network.prod.yaml`, `Pulumi.services.prod.yaml`

**Comment by rafaribe** [comment] 2020-03-17 20:38
I can also hope to see some development into addressing this problem. @nguyenxndaidev 's solution is somewhat of a workaround but feels a bit clunky :)

**Comment by adriantorrie** [comment] 2020-04-27 08:11
Any word on when this will be resolved?

Want to know how much effort to factor in for establishing our local environments, and our CI/CD workflows.

Workarounds so far are clunky, as they've said, and not sure it would help if we chose to migrate to the pulumi cloud at some point. Seems like it would be a right PITA trying to map to [inter-stack-dependencies](https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/#inter-stack-dependencies) which are correctly namespaced when/if a decision to migrate was made.

**Comment by confiq** [comment] 2020-05-08 11:01
![image](https://user-images.githubusercontent.com/277770/81399307-162eab80-912b-11ea-8a1c-cca31ac3a784.png)

This is not in `2.1` either, do we know in which version will we support this? 
Documentation is very confusing when you have inconsistency like this.

**Comment by shousper** [comment] 2020-05-22 01:24
I've just come full circle identifying this issue while investigating adoption of pulumi 👋 

The CLI help describes orgs like a baseline feature however the error:

```
$ pulumi stack init beans/ordering.uat
error: stack names may not contain slashes
```

indicates the CLI help is wrong. So I wasn't sure if the issue is the docs & help or not, lol.

Awesome tool though guys! I hope you can tighten this up before it gets out of control & amend those docs 🙏

**Comment by EvanBoyle** [comment] 2020-09-06 17:37
Just a note, that this is causing issues in Automation API. We're requiring fully qualified stack names and validating this in the API, but when you try to use it with local backends you get this error:

```
failed to create stack: code: 255
, stdout: 
, stderr: error: stack names may not contain slashes
: exit status 255: failed to select stack: code: 255
, stdout: 
, stderr: error: no stack named 'user/project-name/stack-name' found
: exit status 255
```

**Comment by jelleklaver** [comment] 2021-01-15 14:58
There is one more inconsistency for naming stacks using a self-managed/file backend:

```sh
$ pulumi stack init project/stack
error: stack names may not contain slashes
```
However, the following does succeed:
```sh
$ pulumi stack rename project/stack
```
Now the stack's state is put in a subfolder for `project`, but the Pulumi.stack.yaml doesn't seem to properly reflect the stack's name, it is modified to `Pulumi.project-stack.yaml`.

As a work-around, we use @nguyenxndaidev's [solution](https://github.com/pulumi/pulumi/issues/2522#issuecomment-593088942) with `<project>.<stack>` naming of stacks.

**Comment by dotansimha** [comment] 2021-01-18 16:29
Same here. @EvanBoyle have you found a nice workaround for the automation API? 

I noticed another thing here: when you use inline-program with the automation API, you can set `projectName` and `stackName`, but actually, `projectName` doesn't really do anything, since it will store it eventually in `~/.pulumi/stacks/STACK_NAME`, and will ignore `projectName` completely.

**Comment by schmurfy** [comment] 2021-08-06 16:45
I just gave pulumi a try a ran into this after 10min, seeing a bug open for so long is really depressing...
Any fix on the horizon ? As a newcomer requiring the stack name to be unique across multiple projects make absolutely no sense.

**Comment by salmr0** [comment] 2021-09-09 18:06
Any update on when this might get fixed?

**Comment by tomachristian** [comment] 2021-10-12 21:48
That is awesome! Thank you, @emiliza!

**Comment by atrauzzi** [comment] 2021-11-12 02:15
Are there any pains people are going to face when upgrading from the current backend to the fixed one?  Will the new implementation offer a way to migrate over?

We're just about to begin using Pulumi and I'm afraid we'll be jumping on just before a pretty high impact fix lands.

**Comment by DonKannalie** [comment] 2022-02-25 10:51
Any news? I'm still getting the "stack 'dev' already exists" error...

**Comment by Frassle** [comment] 2022-02-25 11:07
> Any news? 

Sorry no, it is still quite high on our priority list and will probably be the next thing I work on but other issues have been taking up my time so far.

> Are there any pains people are going to face when upgrading from the current backend to the fixed one?

We will endeavor for these changes to be backwards compatible.

**Comment by silasdavis** [comment] 2022-03-09 12:54
Are you open to contributions on this?

If so could you provide any pointers/constraints on implementation?

**Comment by Frassle** [comment] 2022-03-09 13:04
> Are you open to contributions on this?

We are actively working on it! If you check the project history you'll see I've made a number of commits in this area in preparation for adding project support to the filestate backend and unifying other differences between the backends (e.g. `pulumi cancel` can now unlock filestate locks).

**Comment by lkt82** [comment] 2022-05-10 22:45
Any updates on this?

**Comment by Halytskyi** [comment] 2022-06-27 19:49
No, it's almost July 2022...

**Comment by yoanisgil** [comment] 2022-07-03 04:44
It's already July 2022 ...

**Comment by orionstudt** [comment] 2022-07-05 14:19
@yoanisgil There is a roadmap you can view to get an idea of what Pulumi is working on https://github.com/orgs/pulumi/projects/44

**Comment by DominicRoyStang** [comment] 2022-08-22 18:28
> Yes, but I went and checked the roadmap and couldn't tell what items contribute to resolve this issue (most likely I'm missing something).

Second item in "backlog": https://github.com/pulumi/pulumi/issues/4605

So it looks like it's not planned in Q3 nor Q4 2022

**Comment by benlongo** [comment] 2023-01-28 02:23
The PR fixing this (#9262) has been sitting in approved for 311 days - what's preventing the merge?

**Comment by justinvp** [comment] 2023-02-02 23:49
We're temporarily reverting the change that landed in `master` to keep the branch in a releasable state while we finalize some aspects of the design. More details in https://github.com/pulumi/pulumi/pull/12052, but the main summary is we're discussing some design alternatives that would make stack identities in the Self-Managed (i.e. filestate) backend more consistent with the Service backend, and will reintroduce the changes with the adjusted design soon.

**Comment by dschoeni** [comment] 2023-02-08 16:10
Is there a timeline for this (given this issue is open since 2019)? To be honest, this inconsistency has led to a lot of frustration while trying out pulumi. 

I opted for a local backend first to test out the tool overall, but quickly got really frustrated because many examples talk about `stack = environment` and `project = repo` and this metaphor is completely broken without this fix, as you cannot have multiple projects with same-named stacks without splitting their backend. I only understood and managed to workaround these limitations after discovering this issue thread.

I think the docs would profit extremely from a hint in the local backend section.

**Comment by justinvp** [comment] 2023-02-09 00:58
We are finalizing a design proposal and aiming to share it this week.

**Comment by justinvp** [comment] 2023-02-10 23:41
Here's our plan for enabling project-scoped stacks in the filestate backend:

Internally, filestate backends will support being in a new "project mode." In this mode, stacks are scoped by project.

The filestate backend will default into "project mode" when a backend is first initialized (i.e. when a stack is initialized and there are no existing stacks in the backend). This way, new users and newly initialized backends get the new preferred behavior going forward.

Existing filestate backends with existing non-scoped stacks can migrate the non-scoped stacks to being project-scoped via a new CLI command (tentatively `pulumi state migrate`). The command will prompt the user to confirm (when interactive; otherwise, the user must confirm via a flag), warning that older CLIs will no longer see the migrated project-scoped stacks. On confirmation, all stacks will be migrated to project-scoped stacks and the backend will be in "project mode" going forward. If users have prefixed their stack names with the name of the project (e.g. "myproj-mystack", or in other similar ways) as a way of namespacing the stacks, the existing `pulumi stack rename` command can be used to clean up the stack name.

Older CLIs will not be able to select or list project-scoped stacks. Any non-scoped stacks saved by older CLIs in a backend in "project mode" cannot be selected or listed by newer CLIs. However, we're considering making newer CLIs output a warning when non-scoped stacks are detected when the backend is in "project mode", informing the user with instructions on how to run `pulumi state migrate` to migrate the non-scope stacks.

All project-scoped stacks are scoped under a virtual organization, a constant value (still TBD, but we're considering "organization" or "default"). This allows for a consistent stack identify format across both filestate and httpstate backends, e.g. you can refer to a fully-qualified stack with `organization/project/stack`, or using the shorthands `organization/stack` or `stack` (depending on context), just like with the httpstate backend.

We've started the implementation and should be able to deliver it before the end of the quarter (very likely sooner).

**Comment by yoanisgil** [comment] 2023-02-11 00:26
@justinvp out of curiosity: what's the permission model under this new model? For instance, does that mean that all projects in the same stack will share the same encryption key?

**Comment by justinvp** [comment] 2023-02-11 00:34
@yoanisgil, nothing is changing w.r.t. encryption. The secret provider is still per stack, even when there are multiple stacks scoped under the same project.

**Comment by abhinav** [comment] 2023-04-03 20:34
Hey folks, thanks for your patience.
We just released v3.61 with support for project-scoped stacks that addresses this concern.
Check out the [announcement blog post](https://www.pulumi.com/blog/project-scoped-stacks-in-self-managed-backend/) for more information.

Closing as resolved.

**Closed by abhinav** 2023-04-03 20:34 UTC
Labels: kind/enhancement, area/backends, resolution/fixed, impact/quality

**Comment by Weinell** [comment] 2023-04-03 20:58
> Hey folks, thanks for your patience. We just released v3.61 with support for project-scoped stacks that addresses this concern. Check out the [announcement blog post](https://www.pulumi.com/blog/project-scoped-stacks-in-self-managed-backend/) for more information.
> 
> Closing as resolved.

Nice. Good work!

**Comment by pawelprazak** [comment] 2024-01-03 12:37
Should this work for `stack init`?:
```
pulumi --non-interactive --logtostderr stack init --stack organization/localworkspacetest/tests-new-stack-inline-source
error: could not create stack: [404] Not Found: Organization 'organization' not found
```

**Comment by Frassle** [comment] 2024-01-03 15:31
> Should this work for stack init?:

With the filestate backend yes. But that 404 error is that your still logged into the cloud backend.
