### ISSUE TITLE
Panic in display logic on Windows+AWSSessionManager+CentOS7+bash

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#4904] opened 2020-06-25 21:17 UTC
A user reported hitting the crash below when running `pulumi up` from Windows using AWS Session Manager to connect to Cent OS 7 running bash using Pulumi 1.14.1.

This is the same sympton as https://github.com/pulumi/pulumi/issues/3935, but that was fixed before in 1.11.0, so this may be another way to trigger the underlying issue.

```
panic: fatal: An assertion has failed: action must be non empty
goroutine 32 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0x0, 0x16d97be, 0x18, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x197
github.com/pulumi/pulumi/pkg/backend/display.makeActionProgress(0x2659b50, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:60 +0xe8
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).refreshColumns(0xc001238000, 0x2659b50, 0x1, 0xc0012cc230, 0x5, 0x5, 0xc0012c2d80, 0x5, 0x5)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:373 +0x10d
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).refreshAllRowsIfInTerminal(0xc001238000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:591 +0x36e
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).processNormalEvent(0xc001238000, 0x16c72e0, 0xc, 0x1559ec0, 0xc000aba640)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:966 +0x45a
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).processEvents(0xc001238000, 0xc000108050, 0xc000041020)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:1033 +0x13d
github.com/pulumi/pulumi/pkg/backend/display.ShowProgressEvents.func1(0xc001238000, 0xc000108050, 0xc000041020, 0xc000394000)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:277 +0x3f
created by github.com/pulumi/pulumi/pkg/backend/display.ShowProgressEvents
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:276 +0x44b
```

**Comment by leezen** [comment] 2020-12-16 06:55
As part of investigating #5957, I tried to reproduce this. I ran session manager in Windows and connected to a CentOS 7 instance via AWS SSM. Pulumi ran fine, though the Windows command terminal itself did not handle some of the characters well, everything ran correctly. I'm closing this for now since I can't reproduce it, though it's possible it may also be a 0-width terminal detection issue as with #5957.

**Closed by leezen** 2020-12-16 06:55 UTC
Labels: area/cli, kind/panic
