### ISSUE TITLE
Python Dynamic Provider in a separate file does not support consuming config

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#17050] opened 2024-08-22 16:26 UTC
### What happened?

Using the attached code which is structured as such:
- `__main__.py`: A simple pulumi program to invoke a dynamic provider resource 
- `SimpleProvider.py`: A simple Dynamic Provider that needs to consume a password and is doing so via Pulumi config. (A more real-world example here would be the credentials needed to call the API that the dynamic provider is calling.)

When running `pulumi up` one gets the error:
```
  pulumi-python:dynamic:Resource (foo):
    error: Exception calling application: Missing required configuration variable 'project:password'
        please set a value using the command `pulumi config set --secret project:password <value>`
```

Note that the project is NOT called `project` and so the error message is not correct either in saying the config property is called `project:password`.

Also note that if the dynamic provider code is changed to use just `.get...()` instead of `require...()` the error doesn't fire, but the value is not set (because it appears to be getting `project:password`).

Also note that trying to fool it by setting a `project:` namespace in the Pulumi.stack.yaml file doesn't work either.

[Archive.zip](https://github.com/user-attachments/files/16714910/Archive.zip)

### Example

Use code attached above and run `pulumi up`

### Output of `pulumi about`

CLI          
Version      3.128.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  unknown

Host     
OS       darwin
Version  13.6.9
Arch     x86_64

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME        VERSION
pip         24.2
pulumi      3.129.0
setuptools  73.0.1
wheel       0.44.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2024-09-05 10:35
Likely a duplicate of https://github.com/pulumi/pulumi/issues/4512 although I do note that the TypeScript version works for me:

```ts
import * as pulumi from "@pulumi/pulumi";

const config = new pulumi.Config();
const password = config.require("password");

interface SimpleResourceInputs {
    authenticated?: pulumi.Input<string>;
}

interface SimpleResourceOutputs {
    authenticated: pulumi.Output<string>;
}

class SimpleProvider implements pulumi.dynamic.ResourceProvider {
    async create(inputs: SimpleResourceInputs): Promise<pulumi.dynamic.CreateResult> {
        return {
            id: "0",
            outs: { authenticated: password === "s3cret" ? "200" : "401" }
        };
    }
}

class SimpleResource extends pulumi.dynamic.Resource {
    public readonly authenticated!: pulumi.Output<string>;

    constructor(name: string, opts?: pulumi.CustomResourceOptions) {
        super(new SimpleProvider(), name, { authenticated: undefined }, opts);
    }
}

export { SimpleResource };
```

and then 


```
import { SimpleResource } from "./SimpleProvider";
export const res = new SimpleResource("simple");
```

gives 

```
 res: {
        authenticated: "200"
        id           : "0"
        urn          : "urn:pulumi:dev::azure-ts::pulumi-nodejs:dynamic:Resource::simple"
    }
```

**Closed** 2024-11-07 10:54 UTC
Labels: kind/bug, language/python, customer/feedback, area/dynamic-providers

**Comment by julienp** [comment] 2024-11-07 16:35
Documentation for the `configure` method is at https://github.com/pulumi/docs/pull/13276
