### ISSUE TITLE
Error: determine_state_recovery_action_forward_branches

### ISSUE THREAD

**Issue by l1x** [pulumi/pulumi#8381] opened 2021-11-08 18:49 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Trying to get Pulumi working.

### Steps to reproduce

```
> pulumi up
Previewing update (datadeft/prod)

View Live: https://app.pulumi.com/datadeft/infra/prod/previews/02330f90-3490-4b1f-bc66-81718b2ddb80

     Type                 Name         Plan     Info
     pulumi:pulumi:Stack  infra-prod            2 messages
     └─ aws:route53:Zone  datadeft.eu           1 error

Diagnostics:
  pulumi:pulumi:Stack (infra-prod):
    assertion failed [inst.has_value()]: failed to decode instruction: 0x0
    (StateRecovery.cpp:336 determine_state_recovery_action_forward_branches)

  aws:route53:Zone (datadeft.eu):
    error: transport is closing
```

Expected: Pulumi deploying changes to our infra
Actual: CPP assertion failed.

**Comment by leezen** [comment] 2021-11-10 17:07
This looks related to Rosetta translation issues. Closing as a dupe of #5859. Do you mind indicating what OS and hardware you're using in that #5859?

**Closed by leezen** 2021-11-10 17:07 UTC
Labels: kind/bug, resolution/duplicate
