### ISSUE TITLE
Go SDK fails to compile due to duplicate type

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#11626] opened 2022-12-12 15:42 UTC
### What happened?

I tried to upgrade the pulumi-azure bridged provider. The Go SDK fails to compile, and I think the error is legit and has been present for a while. We recently pulled in a new ci-mgmt and now we build the SDK as part of `make` thanks to [Vivek’s commit](https://github.com/pulumi/ci-mgmt/pull/278/commits/b16612d10266fb7ed675a28af6818156049d6739).

```
cd sdk && go list `grep -e "^module" go.mod | cut -d ' ' -f 2`/go/... | xargs go build
# github.com/pulumi/pulumi-azure/sdk/v5/go/azure/logicapps
go/azure/logicapps/integrationAccountMap.go:79:6: IntegrationAccountMap redeclared in this block
	go/azure/logicapps/integrationAccount.go:238:6: other declaration of IntegrationAccountMap
go/azure/logicapps/integrationAccountMap.go:205:6: IntegrationAccountMapInput redeclared in this block
	go/azure/logicapps/integrationAccount.go:231:6: other declaration of IntegrationAccountMapInput
go/azure/logicapps/integrationAccountMap.go:212:31: IntegrationAccountMap.ElementType redeclared in this block
	go/azure/logicapps/integrationAccount.go:240:30: other declaration of ElementType
go/azure/logicapps/integrationAccountMap.go:216:33: IntegrationAccountMap.ToIntegrationAccountMapOutput redeclared in this block
	go/azure/logicapps/integrationAccount.go:244:32: other declaration of ToIntegrationAccountMapOutput
go/azure/logicapps/integrationAccountMap.go:220:33: IntegrationAccountMap.ToIntegrationAccountMapOutputWithContext redeclared in this block
	go/azure/logicapps/integrationAccount.go:248:32: other declaration of ToIntegrationAccountMapOutputWithContext
go/azure/logicapps/integrationAccountMap.go:274:6: IntegrationAccountMapOutput redeclared in this block
	go/azure/logicapps/integrationAccount.go:316:6: other declaration of IntegrationAccountMapOutput
go/azure/logicapps/integrationAccountMap.go:276:36: IntegrationAccountMapOutput.ElementType redeclared in this block
	go/azure/logicapps/integrationAccount.go:318:36: other declaration of ElementType
go/azure/logicapps/integrationAccountMap.go:280:38: IntegrationAccountMapOutput.ToIntegrationAccountMapOutput redeclared in this block
	go/azure/logicapps/integrationAccount.go:322:38: other declaration of ToIntegrationAccountMapOutput
go/azure/logicapps/integrationAccountMap.go:284:38: IntegrationAccountMapOutput.ToIntegrationAccountMapOutputWithContext redeclared in this block
	go/azure/logicapps/integrationAccount.go:326:38: other declaration of ToIntegrationAccountMapOutputWithContext
go/azure/logicapps/init.go:39:7: cannot use &IntegrationAccountMap{} (value of type *IntegrationAccountMap) as type pulumi.Resource in assignment:
	*IntegrationAccountMap does not implement pulumi.Resource (missing URN method)
go/azure/logicapps/init.go:39:7: too many errors
```

I tried to bisect when the issue was introduced but it’s present all the way back to v4.21.0 from October 2021. Earlier than that I get other compile errors at an earlier point that I haven’t looked into. My process was

```
git co vX.Y.0
cd sdk && go list `grep -e "^module" go.mod | cut -d ' ' -f 2`/go/... | xargs go build
```
(same command from the Makefile)

### Steps to reproduce

Since the issue has been present for a while, it's enough to check out `master` and `make build_go`.

### Expected Behavior

SDK compiles

### Actual Behavior

see above

### Additional context

```
rg '\+ ?"Map"' pkg/codegen/go/
pkg/codegen/go/gen.go
475:		return strings.TrimSuffix(en, "Args") + "Map"
1062:	genOutputType(w, baseName+"Map", "map[string]"+elementType, false)
1149:		pkg.genInputInterface(w, name+"Map")
1153:		genInputImplementation(w, name+"Map", name+"Map", "map[string]"+name, false)
1440:	if details.mapInput && !pkg.names.Has(name+"Map") {
1441:		pkg.genInputInterface(w, name+"Map")
1445:		genInputImplementation(w, name+"Map", name+"Map", "map[string]"+name, false)
1541:	if details.mapOutput && !pkg.names.Has(name+"Map") {
2032:		pkg.genInputInterface(w, name+"Map")
2034:		genInputImplementation(w, name+"Map", name+"Map", "map[string]*"+name, false)
2444:		elementTypeName = strings.TrimSuffix(elementTypeName, "Args") + "Map"
2520:		return pkg.nestedTypeToType(t.ElementType) + "Map"
2550:			if details.mapInput && !pkg.names.Has(name+"Map") {
3262:				names = append(names, rawResourceName(r)+suffix+"Map")
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2022-12-12 16:03
Since it's the case from October 2021, I removed p1

**Comment by iwahbe** [comment] 2022-12-12 16:49
Duplicate of [10551](https://github.com/pulumi/pulumi/pull/10551)

**Closed by iwahbe** 2022-12-12 16:49 UTC
Labels: kind/bug, language/go, area/codegen, needs-triage, resolution/duplicate
