### ISSUE TITLE
Cluster changes to mutable properties causes conservative replaces in previews that don't get done in updates

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi#4326] opened 2020-03-18 00:29 UTC
### Problem description

A [community](https://pulumi-community.slack.com/archives/CRFURDVQB/p1584480254083600) user is experiencing changes being proposed to kubeconfig and its dependencies during previews, when in fact mutable cluster properties are being updated (e.g. [tags](https://github.com/pulumi/pulumi-eks/issues/338#issuecomment-589998046), or the k8s version used) and the kubeconfig and children remain unchanged.

This is due to the use of outputs and trickling that down the dependency chain. In practice resources like the kubeconfig and provider do not actually get replaced, but this proposal is alarming for users who are not expecting to see these changes.

Preview:

```
Previewing update (dev-43vwhsxbqgqn):
     Type                                  Name                                                Plan        Info
     pulumi:pulumi:Stack                   example-nodegroup-dev-43vwhsxbqgqn                              2 messages
     └─ eks:index:Cluster                  example-nodegroup-iam-simple
 ~      ├─ aws:eks:Cluster                 example-nodegroup-iam-simple-eksCluster             update      [diff: ~version]
 +-     ├─ pulumi:providers:kubernetes     example-nodegroup-iam-simple-provider               replace     [diff: ~kubeconfig]
 +-     ├─ pulumi:providers:kubernetes     example-nodegroup-iam-simple-eks-k8s                replace     [diff: ~kubeconfig]
 +-     ├─ kubernetes:core:ConfigMap       example-nodegroup-iam-simple-nodeAccess             replace     [diff: ~metadata,provider]
 ~      ├─ pulumi-nodejs:dynamic:Resource  example-nodegroup-iam-simple-vpc-cni                update      [diff: ~kubeconfig]
        └─ eks:index:NodeGroup             example-ng-simple-ondemand
 +-        ├─ aws:ec2:LaunchConfiguration  example-ng-simple-ondemand-nodeLaunchConfiguration  replace     [diff: ~userData]
 ~         └─ aws:cloudformation:Stack     example-ng-simple-ondemand-nodes                    update      [diff: ~templateBody]

Diagnostics:
  pulumi:pulumi:Stack (example-nodegroup-dev-43vwhsxbqgqn):
    Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided

    Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided

Outputs:
  - kubeconfig1: {
      - apiVersion     : "v1"
      - clusters       : [
      -     [0]: {
              - cluster: {
                  - certificate-authority-data: "omitted"
                  - server                    : "omitted"
                }
              - name   : "kubernetes"
            }
        ]
      - contexts       : [
      -     [0]: {
              - context: {
                  - cluster: "kubernetes"
                  - user   : "aws"
                }
              - name   : "aws"
            }
        ]
      - current-context: "aws"
      - kind           : "Config"
      - users          : [
      -     [0]: {
              - name: "aws"
              - user: {
                  - exec: {
                      - apiVersion: "client.authentication.k8s.io/v1alpha1"
                      - args      : [
                      -     [0]: "token"
                      -     [1]: "-i"
                      -     [2]: "example-nodegroup-iam-simple-eksCluster-d447714"
                        ]
                      - command   : "aws-iam-authenticator"
                    }
                }
            }
        ]
    }
  + kubeconfig1: output<string>
```

Update:

```
Updating (dev-43vwhsxbqgqn):
     Type                   Name                                     Status      Info
     pulumi:pulumi:Stack    example-nodegroup-dev-43vwhsxbqgqn                   2 messages
     └─ eks:index:Cluster   example-nodegroup-iam-simple
 ~      └─ aws:eks:Cluster  example-nodegroup-iam-simple-eksCluster  updated     [diff: ~version]

Diagnostics:
  pulumi:pulumi:Stack (example-nodegroup-dev-43vwhsxbqgqn):
    Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided

    Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided

Outputs:
    kubeconfig1: {
        apiVersion     : "v1"
        clusters       : [
            [0]: {
                cluster: {
                    certificate-authority-data: "omitted"
                    server                    : "omitted"
                }
                name   : "kubernetes"
            }
        ]
        contexts       : [
            [0]: {
                context: {
                    cluster: "kubernetes"
                    user   : "aws"
                }
                name   : "aws"
            }
        ]
        current-context: "aws"
        kind           : "Config"
        users          : [
            [0]: {
                name: "aws"
                user: {
                    exec: {
                        apiVersion: "client.authentication.k8s.io/v1alpha1"
                        args      : [
                            [0]: "token"
                            [1]: "-i"
                            [2]: "example-nodegroup-iam-simple-eksCluster-d447714"
                        ]
                        command   : "aws-iam-authenticator"
                    }
                }
            }
        ]
    }

Resources:
    ~ 1 updated
    27 unchanged

Duration: 10m25s
```

### Reproducing the issue

1. Stand up an eks cluster
2. Add or change a property on the cluster e.g. add `tags: {"org":"foo"}` and then run a follow-up update.

### Related Issues

https://github.com/pulumi/pulumi-eks/issues/338

**Comment by lblackstone** [comment] 2023-01-26 01:31
I wasn't able to reproduce this issue with current provider versions, so this seems to be fixed. I tested with both tag changes, and by changing the cluster version. 

I believe that a k8s Provider replacement will still preview resource replacements for anything deployed using that Provider, but it happens less commonly now. Closing this issue as fixed.

**Closed by lblackstone** 2023-01-26 01:31 UTC
Labels: kind/enhancement, resolution/fixed, area/engine
