### ISSUE TITLE
Pulumi stack is broken due duplicated resources (somehow)

### ISSUE THREAD

**Issue by bacek** [pulumi/pulumi#11271] opened 2022-11-07 04:55 UTC
### What happened?

I was trying pulumi for k8s deployment, refactoring code including StackRef to stach which actually created k8s cluster in GKE.

After few successful `pulumi up` I started to receive failure messages due inability to delete Namespace.

```
Previewing update (gcp__us-west1__test-deployment):
     Type                              Name                                                 Plan        Info
     pulumi:pulumi:Stack               pulumi-k8s-gcp__us-west1__test-deployment  running..   read pulumi:pulumi:StackReference gcp__us
 ~   ├─ kubernetes:apps/v1:Deployment  nginx                                                update      [diff: ~spec]
 +-  ├─ kubernetes:core/v1:Namespace   test                                                 replace     
 +-  └─ pulumi:providers:kubernetes    gcp                                                  replace     

Diagnostics:
  pulumi:pulumi:Stack (pulumi-k8s-gcp__us-west1__test-deployment):
    Creating new deployment in test for tag XXXXXX

Do you want to perform this update? yes
Updating (gcp__us-west1__test-deployment):
     Type                              Name                                                 Status                            Info
     pulumi:pulumi:Stack               pulumi-k8s-gcp__us-west1__test-deployment  running                           error: update faile
 ~   ├─ kubernetes:apps/v1:Deployment  nginx                                                updated (19s)                     [diff: ~spec]; 
 --  └─ kubernetes:core/v1:Namespace   test                                                 **deleting failed (-19.81s)**     error: configur

Diagnostics:
  kubernetes:core/v1:Namespace (test):
    error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://35.197.35.77/openapi/v2?timeout=32s": dial tcp 35.197.35.77:443: i/o timeout
    If the cluster has been deleted, you can edit the pulumi state to remove this resource

  pulumi:pulumi:Stack (pulumi-k8s-gcp__us-west1__test-deployment):
    Creating new deployment in test for tag XXXXXX
    error: update failed

Resources:
    ~ 1 updated
    3 unchanged

Duration: 1m1s

```

Stack shows duplicated resources:

```
$ pulumi stack 
Current stack is gcp__us-west1__test-deployment:
    Managed by sunburst
    Last updated: 39 minutes ago (2022-11-07 15:09:14.138776342 +1100 AEDT)
    Pulumi version used: v3.46.0
Current stack resources (9):
    TYPE                              NAME
    pulumi:pulumi:Stack               pulumi-k8s-gcp__us-west1__test-deployment
    ├─ pulumi:providers:pulumi        default
    ├─ pulumi:pulumi:StackReference   gcp__us-west1__k8s
    ├─ pulumi:providers:kubernetes    gcp
    ├─ kubernetes:core/v1:Namespace   test
    ├─ kubernetes:apps/v1:Deployment  nginx
    ├─ pulumi:pulumi:StackReference   pulumi-gke
    ├─ pulumi:providers:kubernetes    gcp
    └─ kubernetes:core/v1:Namespace   test

Current stack outputs (0):
    No output values currently in this stack

Use `pulumi stack select` to change stack; `pulumi stack ls` lists known ones

```

(I did change original StackReference once and did `pulumi up` multiple times succcessfully)

Manually removing resources doesn't work either;

```
pulumi state delete urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::kubernetes:core/v1:Namespace::test
 warning: This command will edit your stack's state directly. Confirm? Yes
 Multiple resources with the given URN exist, please select the one to edit:  [Use arrows to move, enter to select, type to filter]
> "test"
  "test" (Pending Deletion)

```
```
 Multiple resources with the given URN exist, please select the one to edit: "test" (Pending Deletion)
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.46.0
Go Version:       go1.19.2
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            fatal: error An assertion has failed: state edit produced an invalid snapshot. source error: resource urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::kubernetes:apps/v1:Deployment::nginx dependency urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::kubernetes:core/v1:Namespace::test refers to missing resource

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1e72c40, 0xc000a91f00})
	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoErrorf({0x2862740?, 0xc000a91ed0?}, {0x231d4b1?, 0x0?}, {0x0?, 0x0?, 0x0?})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:47 +0x139
main.totalStateEdit({0x2880e08, 0xc0000540d8}, {0x2891fa0, 0xc0007ed590}, 0x1, {{0x22beb84, 0x6}, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:180 +0x31e
main.runTotalStateEdit({0x2880e08, 0xc0000540d8}, {0x0, 0x0}, 0xc0?, 0x1d07308?)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:142 +0x1a5
main.runStateEdit({0x2880e08?, 0xc0000540d8?}, {0x0?, 0x0?}, 0x0?, {0x7fff15df112c?, 0x0?}, 0x0?)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:120 +0x68
main.newStateDeleteCommand.func1(0x0?, {0xc000a91af0, 0x1, 0x0?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_delete.go:60 +0x13d
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000d32280?, {0xc000a91af0, 0x1, 0x1})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc000d32280, {0xc000a91ad0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc000c30c80)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

### Steps to reproduce

No idea how to reproduce it.

### Expected Behavior

Either:
* No duplicated resource created.
* Deletion of duplicates succeeded

### Actual Behavior

pulumi cli crash

### Output of `pulumi about`

```
pulumi about 
CLI          
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.22.1
nodejs      unknown

Host     
OS       debian
Version  11.5
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v16.18.0'

Current Stack: gcp__us-west1__neara-sce-test-deployment

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::pulumi:pulumi:Stack::pulumi-k8s-gcp__us-west1__neara-sce-test-deployment
pulumi:providers:pulumi        urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::pulumi:providers:pulumi::default
pulumi:pulumi:StackReference   urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::pulumi:pulumi:StackReference::gcp__us-west1__k8s
pulumi:providers:kubernetes    urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::pulumi:providers:kubernetes::gcp
kubernetes:core/v1:Namespace   urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::kubernetes:core/v1:Namespace::test
kubernetes:apps/v1:Deployment  urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::kubernetes:apps/v1:Deployment::nginx
pulumi:pulumi:StackReference   urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::pulumi:pulumi:StackReference::pulumi-gke
pulumi:providers:kubernetes    urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::pulumi:providers:kubernetes::gcp
kubernetes:core/v1:Namespace   urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::kubernetes:core/v1:Namespace::test


Found no pending operations associated with gcp__us-west1__test-deployment

Backend        
Name           sunburst
URL            s3://com-neara-bacek-test/pulumi/
User           bacek
Organizations  

Dependencies:
NAME                 VERSION
@pulumi/pulumi       3.46.0
@pulumi/kubernetes   3.22.1
@pulumi/kubernetesx  0.1.6
@types/node          14.18.33

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2022-11-07 10:14
> Stack shows duplicated resources:

That's expected, your program had triggered a replace of the Namespace and k8s provider but by default pulumi tries to create the new versions before deleting the old ones. So you end up with two entries for their state but the old entries will be tagged as "to be deleted".

> fatal: error An assertion has failed: state edit produced an invalid snapshot. source error: resource urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::kubernetes:apps/v1:Deployment::nginx dependency urn:pulumi:gcp__us-west1__test-deployment::pulumi-k8s::kubernetes:core/v1:Namespace::test refers to missing resource

That's a bug, we shouldn't panic here but it does look like you tried to delete the namespace that was still in use by the nginx dependency.

> configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://35.197.35.77/openapi/v2?timeout=32s": dial tcp 35.197.35.77:443: i/o timeout

Are you sure your new kubernetes config was correct? Looks like that just timed out trying to connect to the k8s server.

**Comment by bacek** [comment] 2022-11-07 20:57
> That's expected, your program had triggered a replace of the Namespace and k8s provider but by default pulumi tries to create the new versions before deleting the old ones. So you end up with two entries for their state but the old entries will be tagged as "to be deleted".

First run did get partially through:

```
Updating (gcp__us-west1__neara-sce-test-deployment):
     Type                              Name                                                 Status                  Info
     pulumi:pulumi:Stack               pulumi-k8s-gcp__us-west1__test-deployment  running                 error: update failed
 +-  ├─ pulumi:providers:kubernetes    gcp                                                  replaced (0.00s)        
 +-  ├─ kubernetes:core/v1:Namespace   test                                                 replaced (0.00s)        [diff: ~provider]; 
 +   └─ kubernetes:apps/v1:Deployment  nginx                                                **creating failed**     error: 4 errors occurred:

Diagnostics:
  pulumi:pulumi:Stack (pulumi-k8s-gcp__us-west1__test-deployment):
    Creating new deployment in test for tag XXXXXX
    error: update failed

  kubernetes:apps/v1:Deployment (nginx):
    error: 4 errors occurred:
    	* resource test/nginx was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'nginx' timed out waiting to be Ready
    	* [MinimumReplicasUnavailable] Deployment does not have minimum availability.
    	* Minimum number of live Pods was not attained
    	* [Pod test/nginx-77d4cb755-2q5v5]: containers with unready status: [nginx] -- [ImagePullBackOff] Back-off pulling image "nginx:XXXXXX"

Resources:
    +-2 replaced
    1 unchanged

Duration: 10m4s

```

I messed up docker image tag, but according to logs Namespace was replaced.

> That's a bug, we shouldn't panic here but it does look like you tried to delete the namespace that was still in use by the nginx dependency.

Because after first attempt Namespace was duplicated, not replaced. So pulumi was showing 2 "test" Namespaces. And I feel that it didn't distinguish dependency on nginx.

>  configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://35.197.35.77/openapi/v2?timeout=32s": dial tcp 35.197.35.77:443: i/o timeout

I am. It was running successfully on creating new resources.

**Comment by kpitzen** [comment] 2022-11-08 17:22
Hi @bacek - I'm digging into this issue now.  We definitely shouldn't be panicking here.  Would you mind sharing an example program which resulted in this issue?  It doesn't have to be a full repro, since it can be hard to coerce this behavior directly, but it'd be helpful to at least see the state we ended up in here. It _does_ look like we got here due to k8s resource constraints, though the desired fix will be to allow Pulumi to recover from that state gracefully.  Thank you!

**Comment by kpitzen** [comment] 2022-11-08 20:57
I opened #11286 to resolve the panic we're seeing here.  Unfortunately that won't resolve the state issue you're seeing in this case.  Once we have a little more information about that, we can determine what the correct resolution should be.

**Comment by bacek** [comment] 2022-11-08 23:22
@kpitzen this is what I did:

Create simple k8s stack. Trimmed down version from example.

```
// Copyright 2016-2019, Pulumi Corporation.  All rights reserved.

import * as gcp from "@pulumi/gcp";
import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

const name = "helloworld";

const config = new pulumi.Config();
export const masterVersion =
  config.get("masterVersion") ||
  gcp.container.getEngineVersions().then((it) => it.latestMasterVersion);

// Create a GKE cluster
export const cluster = new gcp.container.Cluster(name, {
  name: name,
  // We can't create a cluster with no node pool defined, but we want to only use
  // separately managed node pools. So we create the smallest possible default
  // node pool and immediately delete it.
  initialNodeCount: 1,
  removeDefaultNodePool: true,

  minMasterVersion: masterVersion,
});

const nodePool = new gcp.container.NodePool(
  `primary-node-pool`,
  {
    cluster: cluster.name,
    initialNodeCount: 2,
    location: cluster.location,
    nodeConfig: {
      preemptible: true,
      machineType: "n1-standard-1",
      oauthScopes: [
        "https://www.googleapis.com/auth/compute",
        "https://www.googleapis.com/auth/devstorage.read_only",
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
      ],
    },
    version: masterVersion,
    management: {
      autoRepair: true,
    },
  },
  {
    dependsOn: [cluster],
  },
);

// Export the Cluster name
export const clusterName = cluster.name;

// Manufacture a GKE-style kubeconfig. Note that this is slightly "different"
// because of the way GKE requires gcloud to be in the picture for cluster
// authentication (rather than using the client cert/key directly).
export const kubeconfig = pulumi
  .all([cluster.name, cluster.endpoint, cluster.masterAuth])
  .apply(([name, endpoint, masterAuth]) => {
    const context = `${gcp.config.project}_${gcp.config.zone}_${name}`;
    return `apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${masterAuth.clusterCaCertificate}
    server: https://${endpoint}
  name: ${context}
contexts:
- context:
    cluster: ${context}
    user: ${context}
  name: ${context}
current-context: ${context}
kind: Config
preferences: {}
users:
- name: ${context}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      provideClusterInfo: true
`;
  });
```

Created another stack:
```
import * as pulumi from "@pulumi/pulumi";
import * as k8s from "@pulumi/kubernetes";
import * as kx from "@pulumi/kubernetesx";

const config = new pulumi.Config();
// Reference to another stack.
// I just created "default" gke cluster in sce-sandbox project using
// https://github.com/pulumi/examples/blob/master/gcp-ts-gke-hello-world/index.ts
// as skeleton.
// Name should be configurable. But this will do as PoC.
const stackRef = new pulumi.StackReference(
  nearaConfig.stackRef,
  {},
  {
    aliases: [
      {
        name: "pulumi-gke",
      },
    ],
  },
);
const kubeconfig = stackRef.getOutput("kubeconfig");

// Create a Kubernetes provider instance that uses kubeconfig created by "pulumi-gke"
// stack. kubconfig contains endpoint and credentials.
const clusterProvider = new k8s.Provider("gcp", {
  kubeconfig: kubeconfig,
  namespace: nearaConfig.environment,
  // enableServerSideApply: true,
});

const ctx: Context = {
  provider: clusterProvider,
  ns: new k8s.core.v1.Namespace(
    nearaConfig.environment,
    {
      metadata: {
        name: nearaConfig.environment,
      },
    },
    {
      provider: clusterProvider,
      // WE SHOULD NEVER CHANGE IT
      ignoreChanges: [],
    },
  ),
};

const ns = new k8s.core.v1.Namespace(
    nearaConfig.environment,
    {
      metadata: {
        name: nearaConfig.environment,
      },
    },
    {
      provider: clusterProvider,
      // WE SHOULD NEVER CHANGE IT
      ignoreChanges: [],
    },
  );

const deployment = new k8s.apps.v1.Deployment(
    "nginx",
    {
      metadata: {
        name: "nginx",
        namespace: ns.metadata.name,
      },
      spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
          metadata: { labels: appLabels },
          spec: {
            containers: [
              {
                name: name,
                image: `nginx`,
              },
            ],
          }
        },
      },
    },
    {
      provider: clusterProvider,
    },
  );

```

After setting up first and second stacks, I renamed first one (and put name into second's stack config).

Setting up second stack failed with symptoms in the first message.

**Comment by kpitzen** [comment] 2022-11-09 18:42
@bacek I've updated the linked PR above to (hopefully) prevent this issue from appearing in the future.  In the meantime, is it possible to delete the current stack and remake it?  As in - `pulumi down` followed by `pulumi up`?  I suspect the change in StackReferences may have caused the downstream issues in the rest of your state.  Alternately, manually deleting the deployment via `kubectl` and removing it from state should allow the deletion of its dependent namespace from state, and a subsequent `pulumi up` should then succeed from there.  Does that make sense?  Let me know if I can provide any further assistance!

**Comment by bacek** [comment] 2022-11-09 22:26
@kpitzen it was playground stack. I just destroyed it and re-imported created resources back.

**Comment by kpitzen** [comment] 2022-11-10 19:17
Thanks for the extra context @bacek - given we've found a workaround for this issue, and aren't exactly sure how to reproduce, I'm going to close this issue for now.  After discussing the issue, it seems like changing the diffing logic on StackReferences wouldn't resolve or prevent this issue.  If this occurs again, please feel free to re-open and we'll be more than happy to work through a resolution.  Thanks again!

**Closed by kpitzen** 2022-11-10 19:17 UTC
Labels: kind/bug, p1, awaiting-feedback, area/engine
