### ISSUE TITLE
Pulumi Version:   v3.39.0, Panic when refresh empty stack

### ISSUE THREAD

**Issue by parryian** [pulumi/pulumi#10600] opened 2022-09-02 12:36 UTC
### What happened?

Traceback (most recent call last):
  File "customers.py", line 73, in <module>
    stack.refresh(on_output=print)
  File "/usr/local/lib/python3.8/site-packages/pulumi/automation/_stack.py", line 457, in refresh
    refresh_result = self._run_pulumi_cmd_sync(args, on_output)
  File "/usr/local/lib/python3.8/site-packages/pulumi/automation/_stack.py", line 683, in _run_pulumi_cmd_sync
    result = _run_pulumi_cmd(args, self.workspace.work_dir, envs, on_output)
  File "/usr/local/lib/python3.8/site-packages/pulumi/automation/_cmd.py", line 78, in _run_pulumi_cmd
    raise create_command_error(result)
pulumi.automation.errors.CommandError: 
 code: 1
 stdout: 
 stderr: ================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.39.0
Go Version:       go1.19
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.0/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1b8a520, 0x3112060})
	/opt/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x212
main.filterMapPendingCreates.func1({{0x1e66ac0, 0x5}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:330 +0x2a
main.totalStateEdit({0x22d4e68, 0xc00005c0c8}, {0x22e4dc0, 0xc00083e8d0}, 0x1, {{0x1e66ac0, 0x5}, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state.go:172 +0x2dd
main.filterMapPendingCreates({0x22d4e68?, 0xc00005c0c8?}, {0x22e4dc0?, 0xc00083e8d0?}, {{0x1e66ac0, 0x5}, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:328 +0xab
main.pendingCreatesToImports({0x22d4e68, 0xc00005c0c8}, {0x22e4dc0, 0xc00083e8d0}, 0x1?, {{0x1e66ac0, 0x5}, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:364 +0x291
main.newRefreshCmd.func1(0x20?, {0xc00026eea0?, 0xc000937d78?, 0x604ba5?})
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:165 +0xadb
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc00099db80?, {0xc00097c850, 0x0, 0x7})
	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc00099db80, {0xc00097c7e0, 0x7, 0x7})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc00081ec80)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45

### Steps to reproduce

create a stack and refresh before create

### Expected Behavior

no-op, nothing to refresh so exit cleanly

### Actual Behavior

Panic:            runtime error: invalid memory address or nil pointer dereference

### Output of `pulumi about`

$ pulumi about
CLI
Version      3.39.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME           VERSION
command        0.4.1
datadog        4.10.0
gcp            6.27.0
google-native  0.20.0
python         unknown
random         4.4.2
vault          5.4.1

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.8.10
'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2022-09-02 12:59
This is a duplicate of https://github.com/pulumi/pulumi/issues/10569. We'll have a new release out shortly to patch this.

**Closed** 2022-09-02 12:59 UTC
Labels: kind/bug, resolution/duplicate
