### ISSUE TITLE
Enable local debugging of Lambdas when using function serialization

### ISSUE THREAD

**Issue by rustinlewis** [pulumi/pulumi#7812] opened 2021-08-20 15:54 UTC
This relates to these two closed issues:
https://github.com/pulumi/pulumi/issues/2287
https://github.com/pulumi/pulumi/issues/2580

Using Function Serialization as a way to separate our lambda like in [your examples](https://www.pulumi.com/docs/intro/concepts/function-serialization/#customizing-the-lambda) works well with `pulumi up`, but when using a debugger (like webstorm) we're unable to get past any code that uses pulumi because it throws an error:

`"Program run without the Pulumi engine available; re-run using the 'pulumi' CLI"`

Could you add a mode that allows node to run the process knowing that we don't want to actually `pulumi up` we just want to debug.

**Comment by emiliza** [comment] 2021-08-20 23:01
Sounds like a duplicate of https://github.com/pulumi/pulumi/issues/1372

Please upvote and check out that issue - there are various workarounds listed in the comments.

**Closed by emiliza** 2021-08-20 23:01 UTC
Labels: kind/enhancement, resolution/duplicate
