### ISSUE TITLE
TestPythonTypes fails on Windows

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#10189] opened 2022-07-20 14:35 UTC
See https://github.com/pulumi/pulumi/runs/7430501050?check_suite_focus=true#step:33:243

```
command.go:83: Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe stack export --file C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az192-6-declared-e8d3fa071148438160\stack.json' failed: exit status 2
panic: Failed to load user32.dll: A dynamic link library (DLL) initialization routine failed.
goroutine 1 [running]:
syscall.MustLoadDLL(...)
	/opt/hostedtoolcache/go/1.17.12/x64/src/syscall/dll_windows.go:106
github.com/xanzy/ssh-agent.winAPI({0x254dca6, 0x3824eb0}, {0x254e721, 0xb})
	/home/runner/go/pkg/mod/github.com/xanzy/ssh-agent@v0.3.1/pageant_windows.go:68 +0xb4
github.com/xanzy/ssh-agent.init()
	/home/runner/go/pkg/mod/github.com/xanzy/ssh-agent@v0.3.1/pageant_windows.go:62 +0x1ac
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az192-6-declared-e8d3fa07-2679856236\command-output\pulumi-export.20220720-141819.f0baa.log
    program.go:1221: Destroying stack
    command.go:34: **** Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az192-6-declared-e8d3fa07-2679856236'
    command.go:83: Invoke 'D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' failed: exit status 2
panic: Failed to load user32.dll: A dynamic link library (DLL) initialization routine failed.
goroutine 1 [running]:
syscall.MustLoadDLL(...)
	/opt/hostedtoolcache/go/1.17.12/x64/src/syscall/dll_windows.go:106
github.com/xanzy/ssh-agent.winAPI({0x254dca6, 0x3824eb0}, {0x254e721, 0xb})
	/home/runner/go/pkg/mod/github.com/xanzy/ssh-agent@v0.3.1/pageant_windows.go:68 +0xb4
github.com/xanzy/ssh-agent.init()
	/home/runner/go/pkg/mod/github.com/xanzy/ssh-agent@v0.3.1/pageant_windows.go:62 +0x1ac
    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az192-6-declared-e8d3fa07-2679856236\command-output\pulumi-destroy.20220720-141819.d0268.log
    program.go:1083: 
        	Error Trace:	program.go:1083
        	            				program.go:1094
        	Error:      	Received unexpected error:
        	            	[D:\a\pulumi\pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview] did not succeed after 1 tries
        	Test:       	TestPythonTypes/python\declared
    program.go:692: 
        	Error Trace:	program.go:692
        	            				types_test.go:22
        	Error:      	Received unexpected error:
        	            	running test preview, update, and edits: expected to export stack to file: C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az192-6-declared-e8d3fa071148438160\stack.json: exit status 2
        	Test:       	TestPythonTypes/python\declared
    --- FAIL: TestPythonTypes/python\declared (32.29s)
=== FAIL: integration/types TestPythonTypes (0.00s)
```

**Comment by dixler** [comment] 2022-07-20 14:37
assigning @AaronFriel since he's secondary and has a windows machine.

**Comment by dixler** [comment] 2022-07-20 14:51
@Zaid-Ajaj mentioned that re-running tests has fixed this in the past. currently rerunning.

**Comment by mikhailshilkov** [comment] 2022-07-20 15:33
Yeah I believe that. This is not a proper fix though...

**Comment by AaronFriel** [comment] 2022-07-20 17:59
This is an OOM in Windows and not a single flaky test. Suggest we rename the issue or mark it as a duplicate of #8820 and close that issue. This issue has more detail in the form of logs.

**Closed** 2022-07-21 08:26 UTC
Labels: os/windows, area/build, kind/engineering, resolution/duplicate
