### ISSUE TITLE
Import panics when type token is malformed

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#5699] opened 2020-11-06 16:40 UTC
If you use an incorrect type token with the `import` command, Pulumi will panic.

## Expected Behavior

Any malformed token, URN, etc, should fail gracefully.

## Current Behavior

Pulumi panics:

```
panic: fatal: A precondition has failed for urn

goroutine 100 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20201104-59212-ndj8ey/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Require(0xc000d10200, 0x58bbc65, 0x3)
	/private/tmp/pulumi-20201104-59212-ndj8ey/sdk/go/common/util/contract/require.go:26 +0x13f
github.com/pulumi/pulumi/pkg/v2/resource/deploy/providers.(*Registry).Check(0xc001006f00, 0xc000d10200, 0x32, 0x0, 0xc000c14ed0, 0x0, 0x7, 0xc000d10200, 0x32, 0x58, ...)
	/private/tmp/pulumi-20201104-59212-ndj8ey/pkg/resource/deploy/providers/registry.go:225 +0x8a
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*importer).registerProviders(0xc0005d1b00, 0x5c0b800, 0xc0005bfb80, 0xc000d10180, 0x37, 0x101, 0x0)
	/private/tmp/pulumi-20201104-59212-ndj8ey/pkg/resource/deploy/import.go:233 +0x4c6
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*importer).importResources(0xc0005d1b00, 0x5c0b800, 0xc0005bfb80, 0xc0001c9720, 0x5c0bdc0)
	/private/tmp/pulumi-20201104-59212-ndj8ey/pkg/resource/deploy/import.go:279 +0x105
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*planExecutor).importResources(0xc000c92f20, 0x5c0b8c0, 0xc000c14ae0, 0x5c0bdc0, 0xc000884640, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20201104-59212-ndj8ey/pkg/resource/deploy/plan_executor.go:446 +0x167
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*planExecutor).Execute(0xc000c92f20, 0x5c0b8c0, 0xc000c14ae0, 0x5c0bdc0, 0xc000884640, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20201104-59212-ndj8ey/pkg/resource/deploy/plan_executor.go:137 +0x1247
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*Plan).Execute(...)
	/private/tmp/pulumi-20201104-59212-ndj8ey/pkg/resource/deploy/plan.go:390
github.com/pulumi/pulumi/pkg/v2/engine.(*planResult).Walk.func1(0x5c0bdc0, 0xc000884640, 0xc000884500, 0x5c0b8c0, 0xc000c14ae0, 0xc000c14a01, 0xc0016a3ec0, 0xc000cea4e0)
	/private/tmp/pulumi-20201104-59212-ndj8ey/pkg/engine/plan.go:236 +0x247
created by github.com/pulumi/pulumi/pkg/v2/engine.(*planResult).Walk
	/private/tmp/pulumi-20201104-59212-ndj8ey/pkg/engine/plan.go:222 +0x17a
```

## Steps to Reproduce

Run `pulumi import "aws.s3.Bucket" testing123 testing-import-123`. (Yes, I know the type token is wrong, but I wasn't able to get `aws:s3:Bucket` to work, so was trying to figure this out when I triggered the panic...)

## Context (Environment)

This happens with Pulumi v2.13.0.

**Comment by clstokes** [comment] 2020-11-06 16:43
Dupe of https://github.com/pulumi/pulumi/issues/5688.

**Closed by clstokes** 2020-11-06 16:43 UTC
Labels: needs-triage
