### ISSUE TITLE
Resource alias seems to be creating duplicate resources in pulumi state

### ISSUE THREAD

**Issue by supreethrao** [pulumi/pulumi#12788] opened 2023-04-28 16:20 UTC
### What happened?

In our codebase, there were some pulumi resources without an explicit parent association For e.g without the `parent: this` option. When we tried to change that status for such resources and associate them with a parent resource creating an alias in order not to recreate the resource, it resulted in duplicate resources and hence corrupting the pulumi state. The result of which no further pulumi changes can be applied as any pulumi commands reading/modifying the state (up, stack etc) resulted in an error like this:

```
error: .pulumi/stacks/<stack-name>.json.gz: snapshot integrity failure; refusing to use it: duplicate resource urn:pulumi:<stack-name>::<project-name>::<path-1>:aws:eks_cluster$aws:ec2/routeTableAssociation:RouteTableAssociation::sandbox-pod-rt-association-<aws-region>-a (not marked for deletion)
```

Initial investigation seems to indicate that the resource applied with and without the alias might have resulted in the duplicate, which is quite easy to happen in a continuous integration environment with multiple branch builds running

### Expected Behavior

Duplicate resources under the same parent should not be created/allowed.

### Steps to reproduce

1. Apply change which adds a resource alias. i.e run build for Branch A, which adds the alias
2. Then, apply the change to not have the alias on the same resource. This is similar to running 2 separate branch builds which apply pulumi changes to the same stack 
     - Branch build to apply alias change runs and so the existing parentless `RouteTableAssociation` has got a parent
     - A branch without the change (i.e parentless) ran. This then creates 3 new resources (just in pulumi state) which will be parentless
     - So, at the end of step2, we have 6 set of resources. 3 with parent and 3 parentless
3. Apply change with alias once again. i.e Run build for Branch A once again
    - This ends up creating the duplicate resources under the same parent and should also fail in the post-step phase with duplicate errors already.
4. Query stack and that should fail  with integrity failure caused by step 2.

```
➜ pulumi stack -s <stack-name> --show-urns --disable-integrity-checking | grep pod-rt-association
    │  ├─ aws:ec2/routeTableAssociation:RouteTableAssociation                                 sandbox-pod-rt-association-<aws-region>-a
    │  │     URN: urn:pulumi:<stack-name>::<project-name>::<path-1>:aws:eks_cluster$aws:ec2/routeTableAssociation:RouteTableAssociation::sandbox-pod-rt-association-<aws-region>-a
    │  ├─ aws:ec2/routeTableAssociation:RouteTableAssociation                                 sandbox-pod-rt-association-<aws-region>-c
    │  │     URN: urn:pulumi:<stack-name>::<project-name>::<path-1>:aws:eks_cluster$aws:ec2/routeTableAssociation:RouteTableAssociation::sandbox-pod-rt-association-<aws-region>-c
    │  ├─ aws:ec2/routeTableAssociation:RouteTableAssociation                                 sandbox-pod-rt-association-<aws-region>-b
    │  │     URN: urn:pulumi:<stack-name>::<project-name>::<path-1>:aws:eks_cluster$aws:ec2/routeTableAssociation:RouteTableAssociation::sandbox-pod-rt-association-<aws-region>-b
    │  ├─ aws:ec2/routeTableAssociation:RouteTableAssociation                                 sandbox-pod-rt-association-<aws-region>-b
    │  │     URN: urn:pulumi:<stack-name>::<project-name>::<path-1>:aws:eks_cluster$aws:ec2/routeTableAssociation:RouteTableAssociation::sandbox-pod-rt-association-<aws-region>-b
    │  ├─ aws:ec2/routeTableAssociation:RouteTableAssociation                                 sandbox-pod-rt-association-<aws-region>-a
    │  │     URN: urn:pulumi:<stack-name>::<project-name>::<path-1>:aws:eks_cluster$aws:ec2/routeTableAssociation:RouteTableAssociation::sandbox-pod-rt-association-<aws-region>-a
warning: A new version of Pulumi is available. To upgrade from version '3.60.0' to '3.64.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Output of `pulumi about`

```
CLI
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.13.0
kubernetes  3.23.1
nodejs      unknown
random      4.8.2

Host
OS       darwin
Version  12.2.1
Arch     x86_64

This project is written in nodejs: executable='/nix/store/y016y4mfzhiy49krg5qjiw2669zwjlzy-nodejs-16.18.1/bin/node' version='v16.18.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by supreethrao** [comment] 2023-05-10 08:25
Hey @abhinav Sorry, was on holiday and am back today. I will try and get a working resource/script which should help you recreate the issue.

**Comment by supreethrao** [comment] 2023-05-12 09:47
Hello @abhinav I tried recreating the issue with the contrived example but has been unable to do so. This makes me think if it could be an issue with the aws provider which is not deleting the parentless state after step 2 ? Hence causing the duplicate after step 3. 

I used the below code for my attempt, which is just a translation of your code from go to Typescript. 

NOTE: The option which contains the `parent` and `aliases` field were removed to create the parentless step.

<details>
<summary> Component resource code</summary>

```
import * as pulumi from "@pulumi/pulumi";
import { RandomInteger } from "@pulumi/random";

export interface PulumiBugReportArgs {
  min: number;
  max: number;
}

export class PulumiBugReport extends pulumi.ComponentResource {
  public readonly intVal: RandomInteger;

  constructor(name: string, args: PulumiBugReportArgs, opts?: pulumi.ComponentResourceOptions) {
    super("pkg:index:Component", name, args, opts);

    this.intVal = new RandomInteger(
      name,
      {
        min: args.min,
        max: args.max,
      },
      {
        parent: this,
        aliases: [
          {
            parent: "urn:pulumi:my-stack::infra-aws::random:index/randomInteger:RandomInteger::comp",
          },
        ],
      }
    );
  }
}

```
</details>

<details>
<summary>Invoking code</summary>

```
    new PulumiBugReport("comp", {
      min: 0,
      max: 100,
    });
```
</details>

<details>
<summary>outputs</summary>

```
    ├─ random:index/randomInteger:RandomInteger                                                    comp
    │     URN: urn:pulumi:my-stack::infra-aws::random:index/randomInteger:RandomInteger::comp
    ├─ pulumi:providers:random                                                                     default_4_8_2
    │     URN: urn:pulumi:my-stack::infra-aws::pulumi:providers:random::default_4_8_2
warning: A new version of Pulumi is available. To upgrade from version '3.60.0' to '3.66.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

```

```
    │  └─ random:index/randomInteger:RandomInteger                                                 comp
    │        URN: urn:pulumi:my-stack::infra-aws::pkg:index:Component$random:index/randomInteger:RandomInteger::comp
    ├─ pulumi:providers:random                                                                     default_4_8_2
    │     URN: urn:pulumi:my-stack::infra-aws::pulumi:providers:random::default_4_8_2
warning: A new version of Pulumi is available. To upgrade from version '3.60.0' to '3.66.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```
</details>

**Comment by abhinav** [comment] 2023-05-12 20:32
Much of the relevant code for the Pulumi AWS provider is generated by Pulumi—similarly to the Random provider—so I'm not sure that this would be a bug in the provider itself.

**Comment by lunaris** [comment] 2024-09-27 09:16
Given that it seems we reached a point where we couldn't reproduce this, and that we have fixed a lot of snapshot integrity error causes since 3.65 was released, I'm going to close this. If it resurfaces, or you are still blocked on this, apologies, and please feel free to reopen! 🙏

**Closed by lunaris** 2024-09-27 09:16 UTC
Labels: kind/bug, p1, resolution/no-repro, impact/regression, area/engine, impact/snapshot-integrity
