### ISSUE TITLE
Side-by-side Pulumi modules lead to blank parents

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1704] opened 2018-08-04 17:46 UTC
@jen20 wrote a program that led to a component resource having an empty parent property. This should never happen, since we default to the "root" `pulumi:pulumi:Stack` resource. I vaguely recall an old bug we had where if a resource got created too late, we had already reset the global root resource object, due to the way the root resource is managed. This looks fine, however

https://github.com/pulumi/pulumi/blob/48aa5e73f82b6635d0f236ffcd98e77e705a99c3/sdk/nodejs/runtime/stack.ts#L42-L50

but perhaps there's something else going on here. I wonder if it could be something about multiple `@pulumi/pulumi` modules getting loaded into memory?

**Comment by joeduffy** [comment] 2018-08-04 17:46
Repro is here https://gist.github.com/jen20/83256db5b6a3d4bc6c948c5116e32f06.

**Comment by joeduffy** [comment] 2018-08-04 17:54
I believe we've figured out the root cause. Indeed, my guess at the end of the note appears correct

> I wonder if it could be something about multiple @pulumi/pulumi modules getting loaded into memory?

I asked @jen20 to run `find -L node_modules 'pulumi'`, and there are indeed two:

```
❯ find -L node_modules -name 'pulumi'
node_modules/@pulumi/pulumi
node_modules/@operator-error/pulumi-lambda-cert/node_modules/@pulumi/pulumi
```

In this case, the second is a symlink created by `npm link`, but I think the symlink-nature is a red herring. I suspect this would happen no matter how you ended up with multiple.

The fix here is going to be a little tricky. I think it means we cannot rely on the language host to do the management of the global stack object, and instead will need to push that into the engine. Then any blank parents can be reliably wired up to this stack object.

In principle, this is not difficult, and has the slight benefit that it removes yet another responsibility from the language host that could be done accidentally different between different languages.

**Comment by joeduffy** [comment] 2018-08-04 17:56
Hmm, explicitly setting the parent with `runtime.getRootResource` actually seems to have worked around the issue, so perhaps my understanding isn't as correct as I thought it was ...

**Comment by swgillespie** [comment] 2018-08-06 16:40
> Hmm, explicitly setting the parent with runtime.getRootResource actually seems to have worked around the issue, so perhaps my understanding isn't as correct as I thought it was ...

No, I think you are correct. It's likely that the context in which you invoked `runtime.getRootResource` was the "correct" one, the one that had already been successfully initialized.

I am all for pushing code into the engine wherever possible. Doing so reduces the amount of code that has to be written for each language, which in my mind is a win as we push to support more languages.

**Comment by swgillespie** [comment] 2018-08-06 16:41
I agree that the fix here will be tricky and we will need to think hard about the implications here. Moving this out to M17, I don't think I have time to fully wrap my head around this problem until them.

**Comment by swgillespie** [comment] 2018-08-14 16:38
Closing as a dupe of https://github.com/pulumi/pulumi/issues/1476.

**Closed by swgillespie** 2018-08-14 16:38 UTC
Labels: area/core, kind/bug
