### ISSUE TITLE
pulumi new python fails on M1 processors

### ISSUE THREAD

**Issue by hipertracker** [pulumi/pulumi#14976] opened 2023-12-20 22:31 UTC
### What happened?

When I attempt to create a minimalistic Python project using the `pulumi new python` command, it fails while trying to compile the `grpcio` library from source on my MBP16 M1Max laptop. It appears that Pulumi is utilizing a significantly outdated version of grpcio (specifically, grpcio==1.56.2), which cannot be compiled on M1 family processors. However, newer versions like 1.59 or 1.60 work perfectly fine.

### Example

```
$ pulumi new python
...
Collecting grpcio==1.56.2 (from pulumi<4.0.0,>=3.0.0->-r requirements.txt (line 1))
  Using cached grpcio-1.56.2.tar.gz (24.3 MB)
...
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
```

### Output of `pulumi about`

❯ pulumi about
CLI
Version      3.98.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown

Host
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in python: executable='/Users/hipertracker/.asdf/shims/python3' version='3.12.1'

Current Stack: hipertracker/tst/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/hipertracker
User           hipertracker
Organizations  hipertracker
Token type     personal

Dependencies:
NAME        VERSION
pip         23.3.2
setuptools  69.0.2
wheel       0.42.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2023-12-21 00:07
Hi @hipertracker, thanks for opening the issue and sorry for the trouble. I'm closing this as a duplicate of #14258. Unfortunately, we can't support Python 3.12 until there's a new grpcio release which contains https://github.com/grpc/grpc/pull/34877.

**Closed by justinvp** 2023-12-21 00:07 UTC
Labels: kind/bug, resolution/duplicate
