### ISSUE TITLE
Azure key vaukt as secrets manager stop working on the latest version (3.72.0)

### ISSUE THREAD

**Issue by MonaMoravej** [pulumi/pulumi#13182] opened 2023-06-16 13:48 UTC
### What happened?

We have storage account as pulumi backend, and azure key vault for secret manager, here is our typical stack:

secretsprovider: azurekeyvault://{Azure_Keyvault_Name_That_Has_The_Key}.vault.azure.net/keys/{Our_Key_Name}
encryptedkey:  {Generated_Key_During_pulumi_init}

then we do login with az cli:
$env:AZURE_STORAGE_ACCOUNT="{Azure_Storage_Account_As_Pulumi_Backend}"
$env:AZURE_STORAGE_KEY={Azure_Shared_Storage_Account_Key}
$env:AZURE_KEYVAULT_AUTH_VIA_CLI="true"

pulumi preview/up is working on pulumi 3.71.0 but stop working on pulumi 3.72.0 with the error message of: 

error: getting stack configuration: get stack secrets manager: secrets (code=InvalidArgument): POST https://{Azure_Keyvault_Name_That_Has_The_Key}.vault.azure.net/keys/{Our_Key_Name}/decrypt
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadParameter
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadParameter",
    "message": "The parameter is incorrect.\r\n"
  }
}
--------------------------------------------------------------------------------
I was wondering what has been changed?

### Expected Behavior

pulumi preview working without any issue of decryption of the key

### Steps to reproduce

1. create an storage account
2. create a key vault with a key 
3. make env variables of :

> $env:AZURE_STORAGE_ACCOUNT="{Azure_Storage_Account_Name}"
> $env:AZURE_STORAGE_KEY={Azure_Shared_Storage_Account_Key}
> $env:AZURE_KEYVAULT_AUTH_VIA_CLI="true"

pulumi int, so you have any stack to work with 
make  dummy code for any azure resources to provision (we use azure-native)
4. az login
5. pulumi login az described above
6. pulumi preview 

try with both version, you will get the error on 3.72.0 only

### Output of `pulumi about`

error: getting stack configuration: get stack secrets manager: secrets (code=InvalidArgument): POST https://{Azure_Keyvault_Name_That_Has_The_Key}.vault.azure.net/keys/{Our_Key_Name}/decrypt
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadParameter
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadParameter",
    "message": "The parameter is incorrect.\r\n"
  }
}
--------------------------------------------------------------------------------

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tpschmidt** [comment] 2023-06-16 13:51
Duplicate of https://github.com/pulumi/pulumi/issues/13181

**Closed** 2023-06-16 13:52 UTC
Labels: kind/bug, resolution/duplicate
