### ISSUE TITLE
Pulumi up delete every resource in stack

### ISSUE THREAD

**Issue by BenjaminZ** [pulumi/pulumi#14838] opened 2023-12-13 01:23 UTC
### What happened?

`pulumi up` deleted every resource in the stack.

In one case `preview` and `up` have same outputs `52 deleted`

In another case they ave different output. `preview` showing `5 changes, 51 unchanged`, while `up` ends up `50 deleted`.

### Example

There is no clear way to reproduce this problem. We've run workflows lots of times so far and this issue happened 3 times.

### Output of `pulumi about`

```
Version      3.95.0
Go Version   go1.21.4
Go Compiler  gc
Plugins
NAME          VERSION
azure-native  2.21.2
azuread       5.46.0
dotnet        unknown
random        4.15.0
Host     
OS       ubuntu
Version  22.04
Arch     x86_64
This project is written in dotnet: executable='/usr/share/dotnet/dotnet' version='8.0.100'
Backend        
Name           fv-az[43](https://github.com/WillowInc/Infrastructure-and-Application-Deployment/actions/runs/7189412215/job/19580884337#step:7:43)6-936
URL            file://~
User           runner
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2023-12-16 07:17
@BenjaminZ, are you specifying any other flags, like `pulumi up --refresh`? Can you list the types of the 52 and 50 deleted resources?

**Comment by BenjaminZ** [comment] 2023-12-18 00:13
We are using [Pulumi GH actions](https://github.com/pulumi/actions), the input is

```
with:
    command: up
    work-dir: Applications/***
    stack-name: ***
    secrets-provider: azurekeyvault://***.vault.azure.net/keys/pulumi
    cloud-url: azblob://pulumi/twin/infra?storage_account=***
    refresh: true
    comment-on-pr: true
    upsert: true
    diff: true
    pulumi-version: 3.95.0)
    comment-on-summary: false
    github-token: ***
    expect-no-changes: false
    target-dependents: false
    remove: false
    edit-pr-comment: true
    color: auto
    exclude-protected: false
```

types:

```
azure-native:authorization:RoleAssignment
azure-native:eventgrid:EventSubscription
azure-native:eventgrid:SystemTopicEventSubscription
azure-native:storage:BlobContainer
azure-native:storage:Queue
azure-native:web:WebApp
azure-native:kusto:DatabasePrincipalAssignment
azure-native:storage:Queue
azure-native:web:AppServicePlan
azure-native:keyvault:Vault
azure-native:kusto:Script
azure-native:storage:StorageAccount
azure-native:datafactory:Factory
pulumi:providers:azure-native
azure-native:sql:FirewallRule
azure-native:eventgrid:Topic
```

everything except for the stack references

**Comment by curtdept** [comment] 2024-03-27 19:31
this frequently happens to me if I try and added to many new things at once, I usually have to comment it into chunks and then its fine

**Comment by justinvp** [comment] 2024-03-28 23:14
@curtdept, are you also using the GitHub Action? Are you using `pulumi up --refresh` (`refresh: true` if using the GH action)?

**Comment by curtdept** [comment] 2024-03-29 01:23
> @curtdept, are you also using the GitHub Action? Are you using `pulumi up --refresh` (`refresh: true` if using the GH action)?

No I'm CLI for this, although we do use actions, too scared with this lol

**Comment by curtdept** [comment] 2024-03-29 16:50
> @curtdept, are you also using the GitHub Action? Are you using `pulumi up --refresh` (`refresh: true` if using the GH action)?

I was wrong, its not a race, the planner is terminating early and then comparing that to the snapshot and identifying the differences for deletion, the logs to seem to give any indication as to why the early termination though.

**Comment by Frassle** [comment] 2024-03-29 17:14
Is it maybe an out of memory crash in the JavaScript program that the engine is seeing as just a normal exit?

**Comment by curtdept** [comment] 2024-04-01 15:28
> Is it maybe an out of memory crash in the JavaScript program that the engine is seeing as just a normal exit?

I had a similar thought having seen that before elsewhere, I tried bumping up the old-space and stack params of NODE_OPTIONS with no effect.

**Comment by curtdept** [comment] 2024-04-01 20:55
@justinvp @Frassle 
think I debugged enough to figure out the cause (but not the solution)

We had a helper template function similar to

`
export function GetValue(output) {
  return new Promise((resolve) => {
    output.apply((value) => {
      resolve(value);
    });
  });
}
`

to turn things like Output<string> into string.

After migrating everything to pulumi.jsonStringifiy and pulumi.interpolate I no longer have this issue

**Comment by lunaris** [comment] 2024-09-06 11:13
I'm minded to close this since it seems the early termination is not down to the Pulumi CLI in this case. Please reopen if this is wrong or I've missed anything!

**Closed by lunaris** 2024-09-06 11:13 UTC
Labels: kind/bug, resolution/wont-fix, area/engine
