### ISSUE TITLE
Pulumi replace the aks by seeing diff ~windowsProfile while this is optional

### ISSUE THREAD

**Issue by toanxyz** [pulumi/pulumi#4151] opened 2020-03-22 05:06 UTC
I'm provisioning the AKS cluster and when running pulumi up, it requires replace all the time and the ~diff is showing windowsProfile.
![image](https://user-images.githubusercontent.com/6207857/77242789-04ee1600-6c35-11ea-9d0f-670d55faf4df.png)

We don't declare the windowsProfile property because it was optional as well as we don't need it.
After setting ignoreChanges: ["windowsProfile"] in azure.containerservice.KubernetesCluster, the issues was gone.

This is my aks cluster:
```
const aksCluster = new azure.containerservice.KubernetesCluster(
    `${config.prefix}-aks`,
    {
      location: config.location,
      resourceGroupName: parameters.resourceGroup!.name,
      dnsPrefix: `${config.prefix}-aks`,
      kubernetesVersion: "1.16.7",

      defaultNodePool: {
        name: "pool001",
        osDiskSizeGb: 30,
        nodeCount: 1,
        vmSize: "Standard_D4_v3",
        maxPods: 30,
        enableAutoScaling: true,
        minCount: 1,
        maxCount: 3,
        vnetSubnetId: parameters.subnetGeneral!.id
      },

      servicePrincipal: {
        clientId: clusterServicePrinciple!.applicationId,
        clientSecret: config.randomPassword.result
      },

      addonProfile: {
        omsAgent: {
          enabled: true,
          logAnalyticsWorkspaceId: logAnalyticWorkspace!.id
        }
      },

      networkProfile: {
        networkPlugin: "azure",
        networkPolicy: "azure",
        dockerBridgeCidr: "172.17.0.1/16",
        dnsServiceIp: "10.2.0.10",
        serviceCidr: "10.2.0.0/16",
        loadBalancerSku: "standard"
      },

      roleBasedAccessControl: {
        enabled: true,

        azureActiveDirectory: {
          clientAppId: aad4Client!.applicationId,
          serverAppId: aad4Server!.applicationId,
          serverAppSecret: serverServicePrinciplePassword!.value,
          tenantId: config.tenantId
        }
      }
    },
    {
      ignoreChanges: ["windowsProfile"]
    }
  );
```

**Comment by mikhailshilkov** [comment] 2020-03-23 08:08
Hi @toanxyz 
This seems to be caused by an issue in the upstream terraform provider. Let's track the fix in https://github.com/terraform-providers/terraform-provider-azurerm/issues/6215 and we'll get the fix as soon as it's fixed and released upstream. I'll close this issue as there isn't much we can do here.

**Closed by mikhailshilkov** 2020-03-23 08:08 UTC

**Comment by sfmskywalker** [comment] 2020-03-29 10:55
Running into the same issue. @toanxyz that tip about `ignoreChanges` worked wonders, thanks!
