### ISSUE TITLE
Generated Python names for ALL_CAPS enum values are awkward

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7187] opened 2021-06-01 22:44 UTC
The following type in `schema.json`:

```json
        "apigateway:index:RequestValidator": {
            "type": "string",
            "enum": [
                {
                    "value": "ALL"
                },
                {
                    "value": "PARAMS_ONLY"
                },
                {
                    "value": "BODY_ONLY"
                }
            ]
        }
```

Leads to this in Python:

```py
class RequestValidator(str, Enum):
    ALL = "ALL"
    PARAM_S_ONLY = "PARAMS_ONLY"
    BOD_Y_ONLY = "BODY_ONLY"
```

It is not clear why the Python codegen is inserting additional `_` semi-randomly in the name.

**Comment by lukehoban** [comment] 2021-06-01 22:46
BTW - including `"name": "BODY_ONLY"` as well also leads to the same result.

**Comment by mikhailshilkov** [comment] 2022-07-27 20:22
I believe this is a dupe of #6463

**Closed by mikhailshilkov** 2022-07-27 20:22 UTC
Labels: kind/bug, language/python, area/codegen, resolution/duplicate
