### ISSUE TITLE
Assets and Archives fail silently when they point to a non-existent path

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5577] opened 2020-10-15 22:27 UTC
When using FileArchive, it appears that passing in a non-existent path will cause it to fail silently and the related resource won't be created.

## Expected Behavior
Error message indicating an invalid path.

## Current Behavior
Silent failure and the relevant resource is not created.

## Steps to Reproduce
```
const fn = new aws.lambda.Function("webapp-api-callback", {
        handler: "handler",
        role: role.arn,
        runtime: aws.lambda.NodeJS12dXRuntime,

        code: new pulumi.asset.AssetArchive({
            ".": new pulumi.asset.FileArchive("./lambda"),
        }),
    });
```

where in the above example, `./lambda` does not exist.

There are no errors and no attempt to create the function (preview doesn't show it).

**Comment by MarkusKramer** [comment] 2020-11-26 16:15
I can confirm this bug. Silent failures are very annoying.

**Comment by joeduffy** [comment] 2021-01-05 01:07
I looked a bit into this over the holiday break, since I agree wholeheartedly, silent failures are very annoying -- and silent failures that make resources go missing even worse.

The failure here occurs at https://github.com/pulumi/pulumi/blob/8e8129012e5c1f2883de86478620e9e32474e660/pkg/resource/deploy/source_eval.go#L805-L815 due to the failure to locate the asset path during unmarshaling (which needs to compute the asset hash).

I have two questions

1) Why does the failure go entirely missing (at least in the Node.js SDK)? I assumed it would be handled in some manner by rejecting the output values associated with the resource. It seems to go missing somewhere around here https://github.com/pulumi/pulumi/blob/8e8129012e5c1f2883de86478620e9e32474e660/sdk/nodejs/runtime/resource.ts#L341-L356 The fact that this gets swallowed has deeper implications, which is that _any_ of those `return ..., err`s in the engine will lead to similarly swallowed errors, unless I am missing something.

2) How should the engine be communicating this failure? Should it simply `return ..., err` in this manner? Should it instead be issuing an error in the engine diagnostics similar to how `Check` failures work, so a buggy language SDK can't get this wrong? Or should it be communicating the errors in a domain-specific RPC payload, similar to `Read`?

In any case, this seems fairly serious. @leezen I would love to see this prioritized soonish. To me, silent failures are equally as bad as panics, especially if they have implications to the resource graph like this.

**Comment by joeduffy** [comment] 2021-01-05 01:09
By the way, we could always validate asset paths more eagerly in the language SDK, to offer a nicer experience. Even if we did, we'd still need a robust failure mode here, due to TOCTOU issues.

**Comment by austinbutler** [comment] 2021-03-18 18:00
I couldn't find this issue because the error in the debug logs isn't included so pasting it here:

`I0317 20:03:21.201805 860 eventsink.go:59] RegisterResource RPC finished: resource:my-lambda[aws:lambda/function:Function]; err: Error: 2 UNKNOWN: f ailed to compute archive hash: '/opt/infrastructure/src/lambda/main.py' is neither a recognized archive type nor a director y, resp: undefined
`

**Comment by komalali** [comment] 2021-05-02 20:20
I tried to repro this with the code specified in the description and was not able to reproduce the issue. I get this error:

```
Error: failed to register new resource webapp-api-callback [aws:lambda/function:Function]: 2 UNKNOWN: failed to compute archive hash: couldn't read archive path './lambda': stat ./lambda: no such file or directory
        at Object.registerResource (/Users/komal/code/pulumi-examples/bad-asset/node_modules/@pulumi/pulumi/runtime/resource.js:219:27)
        at new Resource (/Users/komal/code/pulumi-examples/bad-asset/node_modules/@pulumi/pulumi/resource.js:215:24)
        at new CustomResource (/Users/komal/code/pulumi-examples/bad-asset/node_modules/@pulumi/pulumi/resource.js:307:9)
        at new Function (/Users/komal/code/pulumi-examples/bad-asset/node_modules/@pulumi/lambda/function.ts:394:9)
        at Object.<anonymous> (/Users/komal/code/pulumi-examples/bad-asset/index.ts:4:12)
        at Module._compile (internal/modules/cjs/loader.js:1138:30)
        at Module.m._compile (/Users/komal/code/pulumi-examples/bad-asset/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/komal/code/pulumi-examples/bad-asset/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:986:32)
```

**Comment by joeduffy** [comment] 2021-05-04 02:00
> I get this error, which looks like the desired behavior.

It's possible the recent fixes to swallowing RPC errors also fixed this. Does this also lead to a non-zero exit code? (I assume yes since the resource registration failed, but probably worth double checking given our inconsistent history here.)

**Comment by komalali** [comment] 2021-05-04 03:36
>Does this also lead to a non-zero exit code?

Yup, exit code `255`

**Comment by komalali** [comment] 2021-05-04 03:39
I'm going to close this issue as I am unable to reproduce it.

**Closed by komalali** 2021-05-04 03:39 UTC
Labels: area/core, impact/reliability, kind/bug, resolution/fixed, resolution/no-repro
