### ISSUE TITLE
Pulumi embeded

### ISSUE THREAD

**Issue by bytecod3r** [pulumi/pulumi#3697] opened 2019-12-23 15:59 UTC
Is there any way to use the pulumi all in the code without using 'pulumi up' command?

I saw the following issue but couldn't find the answer.
https://github.com/pulumi/pulumi/issues/2506

**Comment by leezen** [comment] 2020-02-27 07:16
Not currently. I'm going to close this as a dupe of the issue you mentioned.

**Closed by leezen** 2020-02-27 07:16 UTC
