### ISSUE TITLE
[Automation API] support setting list and nested fields to SetConfig 

### ISSUE THREAD

**Issue by chuan137** [pulumi/pulumi#6123] opened 2021-01-15 18:02 UTC
Working with list and netsted struct is supported on the cli with the `path` flag, i.e.,`pulumi config set --path`.  But currently the auto.Stack.SetConfig API supports only "key-value". Maybe add an extra bool parameter to SetConfig, and set config with the `--path` flag when it is true.

**Comment by tmehlinger** [comment] 2021-02-15 22:32
I would also like to have this. My team is looking at porting some of our config tooling to use the automation pipeline and this would save us a fair bit of refactoring effort.

**Comment by komalali** [comment] 2021-02-16 03:13
Closing this issue as it's a dupe of https://github.com/pulumi/pulumi/issues/5506 

Working with lists and nested structs is possible with the currently exposed API, the list or struct needs to be parsed to and from json for the top-level config key - discussed more in the other issue.

**Closed by komalali** 2021-02-16 03:13 UTC
Labels: area/automation-api, kind/enhancement
