### ISSUE TITLE
Secret handing with the Automation API weirdness

### ISSUE THREAD

**Issue by roderik** [pulumi/pulumi#6153] opened 2021-01-20 21:22 UTC
The following standalone code works

```
import * as k8s from '@pulumi/kubernetes';
import * as pulumi from '@pulumi/pulumi';
// get the cluster stack from infra-launchpad-cluster package
const clusterStack = new pulumi.StackReference(`settlemint/bpaas-clusters/production`);
// fetch the correct kubeconfig file
const kubeconfig = clusterStack.requireOutput(`${'GKE'}${'EUROPE'}kubeconfig`.toLowerCase());
// create a k8s provider to talk to the cluster for this service based on provider and region
const provider = new k8s.Provider(`kdkdkdkdkdkd`, {
  kubeconfig,
});
console.log(provider);
```

Putting it in the automation code gives me

```
In the automation api the error reported is an unhandled error occurred: The Pulumi runtime detected that 58 promises were still active
```

when i use the promises debug env var i see this: https://gist.github.com/roderik/b02c97d0e904f9eee48f0b6a603cf4d4

I found one error that is different https://gist.github.com/roderik/b02c97d0e904f9eee48f0b6a603cf4d4#file-gistfile1-txt-L634

But the “program” is just this https://gist.github.com/roderik/2a403214c855e3e48aaccea816f4a58e

I tried version 2.17.0 1 and 2, same issue

Adding the following make the snippet program work: `const readableKubeconfig = unsecret(kubeconfig);`  

This feels like either a bug or a doc issue

**Comment by roderik** [comment] 2021-01-20 21:23
FYI, the output in question is a GKE kubeconfig like the docs tutorials

**Comment by lukehoban** [comment] 2021-01-21 04:12
@roderik The underlying change that made this a secret was https://github.com/pulumi/pulumi-terraform-bridge/issues/323.  That was a change we were expecting to make soon to address https://github.com/pulumi/pulumi-terraform-bridge/issues/10, but it appears it was introduced already in at least this case.

That said - that alone should not lead to the promise leaks you are seeing here.  Your callout of the issue with calling `toString` on an `Output` in https://gist.github.com/roderik/b02c97d0e904f9eee48f0b6a603cf4d4#file-gistfile1-txt-L634 is right on - that is what is triggering this (and in particular, that failure happening inside a promise that is not handled anywhere.  

Unfortunately, from the details here, I can't quite tell where exactly that `toString` call is being triggered, or why it happens only in the automation API harness.

One question though - if you remove `console.log(provider);` from the code - does the problem go away?

**Comment by roderik** [comment] 2021-01-21 06:20
> One question though - if you remove `console.log(provider);` from the code - does the problem go away?

No it does not.

I feel the issue is somewhere here:

- eks kubeconfig = 1 secret
- aks kubeconfig = 1 secret
- gke kubeconfig, is custom made like described here https://www.pulumi.com/docs/tutorials/kubernetes/gke/#new-gke-cluster, is actually not a secret but a string, and in that string, I think there is at least one secret while the output shows all values in the backend/output

I literally just fetch the other stack (works), get the Output out (works), pass the output as kubeconfig param into new k8s.Provider -> error

My guess is that something gets confuses on the string with secrets in it, it tries to serialize it, and then it hits an output in the string that is a secret and tries to serialize that, hitting that error.

By doing `const readableKubeconfig = unsecret(kubeconfig);` manually, I guess it first resolves the secrets in the output, and then when I pass it to the k8s.Provider, it all checks out. 

ps. I have not tried the failing case with eks/aks, I needed it to work with gke first. The unsecret workaround works for eks/aks as well.

**Comment by lukehoban** [comment] 2021-01-21 22:18
This whole scenario actually appears quite similar to https://github.com/pulumi/pulumi/issues/5853, which is also Automation API, also promise leaks, also triggered by "toString of an Output", and also using StackReference.

**Comment by lukehoban** [comment] 2021-01-22 02:51
I can reproduce this with the following.  And in fact, this both reports the "promises were still active" error and hangs the Node process (something I've seen a few other times in error cases with Node.js Automation API).

```ts
import { LocalWorkspace } from "@pulumi/pulumi/x/automation";
import * as k8s from '@pulumi/kubernetes';
import * as pulumi from '@pulumi/pulumi';

async function run() {
    const stack = await LocalWorkspace.createOrSelectStack({
        stackName: "dev",
        projectName: "inlineNode",
        program: async () => {
            const clusterStack = new pulumi.StackReference(`lukehoban/gke-demo/dev`);
            const kubeconfig = clusterStack.requireOutput("kubeconfig");
            const provider = new k8s.Provider(`kdkdkdkdkdkd`, { kubeconfig });
            // Uncomment this and it works
            // return {
            //     provid: provider.id,
            // };
        }
    });
    const upRes = await stack.up({ onOutput: console.info });
}

run().catch(err => console.log(err));
```

The issue goes away if I uncomment the `return {provid: provider.id}` from the program callback, which should be a fix/workaround for anyone seeing this. The equivalent program deployed without Automation API doesn't fail with or without a stack export.

**Comment by lukehoban** [comment] 2021-01-22 03:25
The "Calling [toString] on an [Output<T>] is not supported" part of this was a red herring.  It is due to https://github.com/pulumi/pulumi/pull/6174, but does not otherwise affect the actual repro case - it just causes noise in the debugging output.

**Comment by barclayadam** [comment] 2021-01-22 12:09
As per #5853 wanted to record here that adding the provider id as an output property has fixed "promises were still active" issues I was seeing on a single stack (for now). I never saw a hang. Sometimes running the same stack more than once would solve the issue, which points towards a race condition perhaps. All stacks are executed through the Automation API

**Comment by EvanBoyle** [comment] 2021-01-27 01:23
I spent quite a bit of time today looking into this issue, and promise leaks/errors in general as related to automation API:
https://github.com/pulumi/pulumi/issues/5853
https://github.com/pulumi/pulumi/issues/6057

I discovered two things:

First, I think the automation API runtime is checking for leaks too early

https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/server.ts#L120

I would've expected the call to `runtime.disconnect()` to ensure that all outstanding requests are complete. There seems to be an element at play there that I don't quite understand. 

To verify this, I removed the call to check for leaked promises. The leak detector is still scheduled to run [when the process exits](https://github.com/pulumi/pulumi/blob/7d171917ead72d73531927b01e236523a1f7b276/sdk/nodejs/runtime/debuggable.ts#L87). After that change (plus some logging to show that the leak detector was actually running) the [repro program](https://github.com/pulumi/pulumi/issues/6153#issuecomment-765078008) now succeeds. In my WIP branch I've moved the leak detection check to run after the CLI command returns (we can't rely on `onExit` as this check needs to happen after every `stack.up()`). This seems to be working fine. 

Second, I have found the source of the hangs. Pretty simple error, but the cleanup code that tears down the grpc server should be running in a finally block. https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/stack.ts#L175 The hang happens if the promise in the previous line (running the CLI command) is rejected. Moving this to a finally block got rid of any hangs induced by errors, program errors, bad promises, etc. 

I've found a few other improvements to error messages and clarity that I have in my WIP branch. I'll try to get these fixes out for review tomorrow.

**Closed** 2021-02-02 22:37 UTC
Labels: needs-triage

**Comment by EvanBoyle** [comment] 2021-02-02 22:38
This has been fixed and will go out with the next CLI release later this week. If you continue seeing issues after upgrading, please reopen this issue.

**Comment by EvanBoyle** [comment] 2021-02-03 23:25
Fix has been released in https://www.npmjs.com/package/@pulumi/pulumi
