### ISSUE TITLE
Generated Python bindings don't appear to be correct

### ISSUE THREAD

**Issue by emrul** [pulumi/pulumi#14013] opened 2023-09-21 17:49 UTC
### What happened?

We upgraded our [Twingate Pulumi](https://github.com/Twingate-Labs/pulumi-twingate) provider to a more recent version of our Terraform provider. We found that the generated Python bindings don't work for a particular resource and attribute.

The equivalent code via TypeScript works fine.

### Example

Within our Terraform provider we now have a typed attribute (named `Protocols`) marked as [optional](https://github.com/Twingate/terraform-provider-twingate/blob/c876791435469f3a7e0dc972078fbaed3ba5d966/twingate/internal/provider/resource/resource.go#L123). The [schema](https://github.com/Twingate/terraform-provider-twingate/blob/c876791435469f3a7e0dc972078fbaed3ba5d966/twingate/internal/provider/resource/resource.go#L46-L67) it references has 2 required attributes (`TCP` and `UDP`).

The tfgen build process is fine and everything works when we test with Typescript. However, with the generated Python code it seems there is a mistake - in [this](https://github.com/Twingate-Labs/pulumi-twingate/blob/60c969317f3911b8a9278699cc9f81bb196c6659/sdk/python/pulumi_twingate/twingate_resource.py#L467-L470) block `protocols` is initialised with an empty dictionary if not provided:

```
protocols = protocols or {}
```

The problem itself arises in the call to `TwingateResourceProtocolsArgs._configure` ([here](https://github.com/Twingate-Labs/pulumi-twingate/blob/60c969317f3911b8a9278699cc9f81bb196c6659/sdk/python/pulumi_twingate/_inputs.py#L78-L81)):

```
        TwingateResourceProtocolsArgs._configure(
            lambda key, value: pulumi.set(__self__, key, value),
            tcp=tcp,
            udp=udp,
```

You can see `tcp` and `udp` are required positional attributes and this causes the Python binding to fail since the empty initialised dictionary doesn't have those attributes. We get the error `TypeError: TwingateResourceProtocolsArgs._configure() missing 2 required positional arguments: 'tcp' and 'udp'`

### Output of `pulumi about`

We detected this on 2 machines internally and 1 external user has also reported it so far.

```
(____) (base) ____-MBP:python c____p$ pulumi about
CLI          
Version      3.84.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME          VERSION
aws           6.0.4
azure-native  2.6.0
gcp           6.58.0
kubernetes    3.29.1
python        unknown
twingate      0.0.47

Host     
OS       darwin
Version  13.5.2
Arch     arm64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.10/bin/python3' version='3.10.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/c____p
User           c____p
Organizations  c____p, twingate-labs

Dependencies:
NAME                 VERSION
pip                  21.2.3
pulumi-aws           6.0.4
pulumi-azure-native  2.6.0
pulumi-gcp           6.58.0
pulumi-kubernetes    3.29.1
pulumi-twingate      0.0.47
setuptools           57.4.0

Pulumi locates its logs in /var/folders/lb/k_q_pywj2sq49wfpyl2k7s280000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

We tried to set a default value override in the Pulumi Go provider itself but it seems to have not made a difference to the generated Python code.

What we're not sure is if we've done something incorrect here and whether we can correct the issue ourselves somehow by updating the Pulumi/TF bridge code.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2023-09-22 07:24
Duplicate of https://github.com/pulumi/pulumi/issues/14012. Fix available: https://github.com/pulumi/pulumi/pull/14014

**Closed by justinvp** 2023-09-22 07:24 UTC
Labels: kind/bug, resolution/duplicate
