### ISSUE TITLE
Failure on initial `pulumi new` doesn't allow for re-use of project name on subsequent `new`

### ISSUE THREAD

**Issue by emiliza** [pulumi/pulumi#7040] opened 2021-05-12 23:20 UTC
Initial `pulumi new` failures wont allow for re-using of a project name.

## Expected behavior
Cleanup after initial `new` fails, to force the user to re-run `new` after fixing the issues.

## Current behavior
CLI expects you to run an `up` command

## Steps to reproduce
1. Run `$ pulumi new hello-aws-javascript` on a machine that doesn't have NPM installed
2. Go through onboarding, wait for the failure...
3. Install NPM, and re-run `$ pulumi new hello-aws-javascript` onboarding with the same project name.

Get: `Sorry, '<insert project name>' is not a valid project name. A project with this name already exists.`

**Comment by EvanBoyle** [comment] 2021-08-04 01:06
The error message is specific to running `npm install` again, not `pulumi new`. 

```
error: npm install failed; rerun manually to try again, then run 'pulumi up' to perform an initial deployment:
```

This does leave you in a state with the project created, a valid pulumi program, a stack, etc. Trying to create the same project twice should fail. Going to close this as by design.

**Closed by EvanBoyle** 2021-08-04 01:06 UTC
Labels: kind/bug, resolution/by-design
