### ISSUE TITLE
Creating a new project with a name that already exists throws missing-name error

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#8964] opened 2022-02-09 22:57 UTC
When I run `pulumi new` using an inferred project name (e.g., the name of the directory I'm in), and a project with that name already exists, I get an error that says `'' is not a valid project name.`

![image](https://user-images.githubusercontent.com/274700/153304305-71a4a12d-87a4-4f65-8fe4-c6aee25d5bdc.png)

I had to guess at the possibility that I might've created something by this name in the past; if I hadn't, I'm not sure I'd have been able to figure out from the error that a conflict had occurred. After deleting the old project and stack, `pulumi new` was able to create the new one.

Ideally, this error should tell me something like "a project with this name already exists."

**Comment by stack72** [comment] 2022-02-09 23:12
@cnunciato i *think* this is already opened as a bug here but can't find the issue easily

**Comment by markodjukic** [comment] 2022-03-09 12:34
@stack72 maybe you thinking of this: #8747 ?

**Comment by Frassle** [comment] 2022-03-09 13:37
Yeh this is duplicate of https://github.com/pulumi/pulumi/issues/8747.

**Closed** 2022-03-09 23:45 UTC
Labels: kind/bug, resolution/duplicate
