### ISSUE TITLE
import fails with PCL in error message if multiple resources in a batch import JSON share the same name

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi#12382] opened 2023-03-08 22:09 UTC
### What happened?

Running `pulumi import` against the following JSON:

```json
{
  "resources": [
   {
      "type": "gcp:compute/disk:Disk",
      "name": "test2-wireguard-instance-1436674",
      "id": "australia-southeast2-a/test2-wireguard-instance-1436674"
    },
    {
      "type": "gcp:compute/instance:Instance",
      "name": "test2-wireguard-instance-1436674",
      "id": "pulumi-ce-team/australia-southeast2-a/test2-wireguard-instance-1436674"
    }
  ]
}
,
```

Results in the following error:

```text
error: internal error: Error: "test2-wireguard-instance-1436674" already declared

  on anonymous.pp line 31:
  32: resource test2-wireguard-instance-1436674 "gcp:compute/disk:Disk" {
  33:     image = "https://www.googleapis.com/compute/beta/projects/debian-cloud/global/images/debian-11-bullseye-v20220406"
  34:     name = "test2-wireguard-instance-1436674"
  35:     physicalBlockSizeBytes = 4096
  36:     project = "pulumi-ce-team"
  37:     size = 10
  38:     zone = "australia-southeast2-a"
  39: options {
  40: protect =true
  42: }
  44: }

"test2-wireguard-instance-1436674" already declared
```

### Expected Behavior

Since this program runs:

```typescript
const bucket = new aws.s3.Bucket("foo");
const vpc = new aws.ec2.Vpc("foo", {cidrBlock: "10.0.0.0/16"});
```

It looks like the combo of (name, type) are what actually needs to be unique.

### Steps to reproduce

See above.

### Output of `pulumi about`

```text
CLI          
Version      3.56.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.50.0
nodejs  unknown

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v19.5.0'

Current Stack: jkodrofftest/pulumi-import-google-cloud-import-target/dev

TYPE                                         URN
pulumi:pulumi:Stack                          urn:pulumi:dev::pulumi-import-google-cloud-import-target::pulumi:pulumi:Stack::pulumi-import-google-cloud-import-target-dev
pulumi:providers:gcp                         urn:pulumi:dev::pulumi-import-google-cloud-import-target::pulumi:providers:gcp::default_6_50_0
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::gke-helloworld-2a71d4f-pvc-1e6aa931-d742-437e-a52b-413999ace2be
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::gke-helloworld-66f6fac-pvc-f7fa39bc-cb41-410c-8a9e-6272c1f58fd4
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::gke-us-west2-airflow-5-pvc-9b7103e7-7a83-4886-a7d4-0316ff560a48
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::gke-helloworld-2a71d4f-pvc-c006043a-d83c-4fba-a03b-4b5e5d36d0ee
gcp:artifactregistry/repository:Repository   urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:artifactregistry/repository:Repository::gcf-artifacts
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::gke-helloworld-66f6fac-pvc-899f36e5-bf25-4f9a-be5a-38e38a1a89f2
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::test2-wireguard-instance-1436674
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-0bf0fa7
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-422f784
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::gke-helloworld-5050543-pvc-34aaab12-d1b5-4276-aff5-60286550fc5a
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::instance-5807a0d
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::gke-us-west2-airflow-2-pvc-40079bef-3a9f-4504-82f8-e23cb3a561c6
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-472eb90
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::gke-helloworld-5050543-pvc-aaac78fe-5b4a-4f05-84e4-aa2a3704d09c
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-3b0b6fc
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-3eefd5a
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-41d5d42
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-56ee3e1
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-4ee50ae
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-0f70b7b
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-202280b
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-7f184e9
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-922765c
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-75d9343
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-962b747
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-7f79c72
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-789d6f9
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-a11f915
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-84259d3
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-aca5ee4
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-a3cf679
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-703f079
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-99530b1
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-aa8ea2c
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-8acb9ec
gcp:projects/iAMPolicy:IAMPolicy             urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:projects/iAMPolicy:IAMPolicy::pulumi-ce-team-iampolicy
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-b96282d
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-c31848c
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-d9cc98d
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-cf2861a
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-e166c3a
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-b37202a
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-ce7c59f
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-47c851b
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-5e6d62e
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-49436b0
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-ec5f8af
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-f0e97bc
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-1e10c37
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-3bf0e07
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-e787d3e
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-c45fce2
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-e624f4f
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-4e3366a
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-4f03cab
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-41fae7d
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-0d1e384
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-e578dec
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-295a4c2
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-fd806dc
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-65322a5
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-c6c77b8
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-fdcfc5f
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-12e713e
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-f766b51
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-053a353
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-632563f
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-6bc113a
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-ff3743e
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-05a0912
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-eec40de
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-a5e20be
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-9c8ba22
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-9ae32eb
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-be38143
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-82b3db2
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-8146f4a
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-8bb74d6
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-fb965a8
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-5084c3b
gcp:compute/firewall:Firewall                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/firewall:Firewall::k8s-fw-aba25a55d5e684826acb4827cbed47c9
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-613bd84
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-e31d6c2
gcp:compute/firewall:Firewall                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/firewall:Firewall::default-allow-icmp
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-eb1494e
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-fbb7702
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-03171c8
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-e0e0549
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-a305071
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-ccbc237
gcp:compute/firewall:Firewall                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/firewall:Firewall::default-allow-rdp
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-c9a2821
gcp:compute/network:Network                  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/network:Network::network-d3d354f
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-dffd509
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-dac0a2a
gcp:compute/firewall:Firewall                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/firewall:Firewall::default-allow-ssh
gcp:compute/forwardingRule:ForwardingRule    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/forwardingRule:ForwardingRule::aba25a55d5e684826acb4827cbed47c9
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-1b1f24d
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-f49c8b7
gcp:compute/firewall:Firewall                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/firewall:Firewall::test2-fw-8002b8c
gcp:compute/forwardingRule:ForwardingRule    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/forwardingRule:ForwardingRule::ac414228f9af1452d9c749260f268b7b
gcp:compute/instance:Instance                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/instance:Instance::test2-wireguard-instance-1436674
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-c866c2f
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-96b983e
gcp:compute/instanceGroup:InstanceGroup      urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/instanceGroup:InstanceGroup::k8s-ig--6f38578513260ca4
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-e8161ba
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-770b1da
gcp:compute/firewall:Firewall                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/firewall:Firewall::default-allow-internal
gcp:compute/subnetwork:Subnetwork            urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/subnetwork:Subnetwork::subnet-b495e37
gcp:compute/firewall:Firewall                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/firewall:Firewall::firewall-8c24290
gcp:compute/httpHealthCheck:HttpHealthCheck  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/httpHealthCheck:HttpHealthCheck::k8s-b0ac09ee6330ed02-node
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-b05cee4
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-1-d0bba2d
gcp:compute/firewall:Firewall                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/firewall:Firewall::k8s-fw-ac414228f9af1452d9c749260f268b7b
gcp:compute/snapshot:Snapshot                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/snapshot:Snapshot::snapshot-3
gcp:compute/disk:Disk                        urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/disk:Disk::webserver-0-0-fd67b0e
gcp:compute/firewall:Firewall                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/firewall:Firewall::k8s-b0ac09ee6330ed02-node-http-hc
gcp:serviceAccount/account:Account           urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:serviceAccount/account:Account::codefresh-ci-cd-access
gcp:serviceAccount/account:Account           urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:serviceAccount/account:Account::demos-weekly-test
gcp:compute/targetPool:TargetPool            urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/targetPool:TargetPool::aba25a55d5e684826acb4827cbed47c9
gcp:serviceAccount/account:Account           urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:serviceAccount/account:Account::aureq-test-sa
gcp:compute/targetPool:TargetPool            urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/targetPool:TargetPool::ac414228f9af1452d9c749260f268b7b
gcp:compute/instance:Instance                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/instance:Instance::instance-5807a0d
gcp:compute/snapshot:Snapshot                urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:compute/snapshot:Snapshot::snapshot-2
gcp:serviceAccount/account:Account           urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:serviceAccount/account:Account::tushar
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::demo-k8s-ts-nginx-6356eb8-iampolicy
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::gcf-sources-438338752289-us-east1-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::gcf-sources-438338752289-us-east4
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::artifacts.pulumi-ce-team.appspot.com-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::asia.artifacts.pulumi-ce-team.appspot.com
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::gcf-sources-438338752289-us-east4-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::gcf-sources-438338752289-us-east1
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::asia.artifacts.pulumi-ce-team.appspot.com-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::demo-k8s-ts-nginx-6356eb8
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::gcf-sources-438338752289-us-central1
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::artifacts.pulumi-ce-team.appspot.com
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::phil-cosmic-test-oauth-iampolicy
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::gcf-sources-438338752289-us-central1-iampolicy
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::gcf-v2-sources-438338752289-europe-west1-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::gcf-v2-sources-438338752289-europe-west1
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::phil-cosmic-test-oauth
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::mitch-selfhosted
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::mitch-selfhosted-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::gcf-sources-438338752289-europe-west2
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::gcf-sources-438338752289-europe-west1-iampolicy
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::gcf-sources-438338752289-europe-west2-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::us-west2-airflow-2e495e3-fa6253b7-bucket
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::gcf-sources-438338752289-europe-west1
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::us-west2-airflow-2e495e3-fa6253b7-bucket-iampolicy
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::staging.pulumi-ce-team.appspot.com-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::staging.pulumi-ce-team.appspot.com
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::us-west2-airflow-5692738-c5f8c96c-bucket-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::us-west2-airflow-5692738-c5f8c96c-bucket
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::gcf-sources-438338752289-us-west2-iampolicy
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::bucket-32dfc2d-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::gcf-sources-438338752289-us-west2
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::mitchgerdisch-python-unit-testing-bucket-731c995
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::mitchgerdisch-python-unit-testing-bucket-731c995-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::pulumi-ce-team.appspot.com
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::us.artifacts.pulumi-ce-team.appspot.com
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::us-west2-airflow-bf5db84-87f2014c-bucket
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::us.artifacts.pulumi-ce-team.appspot.com-iampolicy
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::eu.artifacts.pulumi-ce-team.appspot.com-iampolicy
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::bucket-32dfc2d
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::us-west2-airflow-3be5969-c0e88aad-bucket
gcp:storage/bucket:Bucket                    urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucket:Bucket::eu.artifacts.pulumi-ce-team.appspot.com
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::us-west2-airflow-bf5db84-87f2014c-bucket-iampolicy
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::pulumi-ce-team.appspot.com-iampolicy
gcp:storage/bucketIAMPolicy:BucketIAMPolicy  urn:pulumi:dev::pulumi-import-google-cloud-import-target::gcp:storage/bucketIAMPolicy:BucketIAMPolicy::us-west2-airflow-3be5969-c0e88aad-bucket-iampolicy


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jkodroff
User           jkodroff
Organizations  jkodroff, jkodrofftest, demo, pulumi

Dependencies:
NAME            VERSION
@pulumi/gcp     6.50.0
@pulumi/pulumi  3.56.0
@types/node     16.18.14

Pulumi locates its logs in /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/ by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment] 2023-03-08 22:17
Closing as duplicate of https://github.com/pulumi/pulumi/issues/6032.

**Closed by lukehoban** 2023-03-08 22:17 UTC
Labels: kind/bug, resolution/duplicate
