### ISSUE TITLE
Don't require CLI to be installed if using RemoteWorkspace

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#13533] opened 2023-07-19 12:50 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Automation API requires the Pulumi CLI to be installed as it uses it to run the updates.

If I'm using a RemoteWorkspace (so Pulumi Deployments), I'm not running the update on my local machine, I'm running it in Pulumi Cloud, so (in theory) this means I shouldn't need the CLI on my local machine.

**Comment by EvanBoyle** [comment] 2023-07-19 15:01
Duplicate of https://github.com/pulumi/pulumi/issues/11330

**Closed by EvanBoyle** 2023-07-19 15:01 UTC
Labels: kind/enhancement, area/automation-api, resolution/duplicate
