### ISSUE TITLE
When import bucket , error: anonymous.pp:27,12-20: undefined variable provider;

### ISSUE THREAD

**Issue by a523** [pulumi/pulumi#16759] opened 2024-07-23 03:35 UTC
### What happened?

```shell
Do you want to perform this import? yes
Importing (prod-layer-zero):
     Type                 Name                        Status            Info
     pulumi:pulumi:Stack  layer-zero-prod-layer-zero                    
 =   └─ aws:s3:Bucket     athena_result_bucket        imported (1s)     2 warnings

Diagnostics:
  aws:s3:Bucket (athena_result_bucket):
    warning: Type checking failed. If any of these are incorrect, please let us know by creating anissue at https://github.com/pului/pulumi-terraform-bridge/issues.
    warning: urn:pulumi:xxxx::aws:s3/bucket:Bucket::athena_result_bucket verification warning: expected string type, got [] type: Examine values at tags.__defaults

Outputs:
 xxxx

Resources:
    = 1 imported
    23 unchanged

Duration: 13s




error: anonymous.pp:27,12-20: undefined variable provider; 
```

There is no code display!

### Example

```shell
pulumi import --provider="urn:pulumi:xxx::xxx::pulumi:providers:aws::sgProvider" "aws:s3/bucket:Bucket" bucket s3-bucket-3b5b4ba
```

### Output of `pulumi about`

CLI          
Version      3.125.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.36.0
language  python  unknown

Host     
OS       darwin
Version  13.6.1
Arch     x86_64

This project is written in python: executable='xxxx/venv/bin/python' version='3.11.9'

Backend        
Name           hisnn1645.ad.harman.com
URL            s3://bucket/?profile=xxxx
User           yolei
Organizations  
Token type     personal

Dependencies:
NAME        VERSION
pip         22.3.1
pulumi_aws  6.36.0
setuptools  65.5.1
wheel       0.38.4

Pulumi locates its logs in /var/folders/gd/tqy86p5n2cq64p0wghxk2w400000gn/T/ by default
warning: Failed to get information about the current stack: No current stack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment] 2024-07-23 06:38
I think this is the import codegen not correctly adding the requested provider resource to the block of intermediate code to generate out into python code.

**Comment by justinvp** [comment] 2024-07-23 14:08
Closing this as a duplicate of https://github.com/pulumi/pulumi/issues/13339

**Closed by justinvp** 2024-07-23 14:08 UTC
Labels: kind/bug, area/codegen, resolution/duplicate, area/import
