### ISSUE TITLE
C# Codegen fails for array input type

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#6868] opened 2021-04-24 20:26 UTC
I have a multi language component with an `inputPropeties` like so:

```
                "availabilityZoneNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "List of availability zones to use for your VPC."
                },
```
This is also a required, plain input:

```
"requiredInputs": [
                "baseCidr",
                "availabilityZoneNames"
            ],
            "plainInputs": [
                "createPrivateZone",
                "baseCidr",
                "availabilityZoneNames"
            ],
```

When I go to generate this component, I get the following error:

```
  Restored /Users/lbriggs/src/git/jaxxstorm/pulumi-awsvpc/sdk/dotnet/Pulumi.Awsvpc.csproj (in 351 ms).
/Users/lbriggs/src/git/jaxxstorm/pulumi-awsvpc/sdk/dotnet/Vpc.cs(69,20): error CS0266: Cannot implicitly convert type 'System.Collections.Immutable.ImmutableArray<string>?' to 'System.Collections.Immutable.ImmutableArray<string>'. An explicit conversion exists (are you missing a cast?) [/Users/lbriggs/src/git/jaxxstorm/pulumi-awsvpc/sdk/dotnet/Pulumi.Awsvpc.csproj]
```

Which seems to refer to this:

```
  /// <summary>
          /// List of availability zones to use for your VPC.
          /// </summary>
>>        public ImmutableArray<string> AvailabilityZoneNames
          {
              get => _availabilityZoneNames ?? (_availabilityZoneNames = new ImmutableArray<string>()); <---- 69 here
              set => _availabilityZoneNames = value;
          }
```

**Comment by jaxxstorm** [comment] 2021-04-24 20:29
This only seems to happen with the DotNet SDK for what it's worth

**Comment by justinvp** [comment] 2021-04-26 15:32
Dupe of #6813

**Closed by justinvp** 2021-04-26 15:32 UTC
Labels: area/multi-language-components, kind/bug, resolution/duplicate
