### ISSUE TITLE
Snapshot integrity failure

### ISSUE THREAD

**Issue by pmayn** [pulumi/pulumi#17404] opened 2024-09-27 11:23 UTC
### What happened?

Created a dev clone stack of our development environment (stack -> stackdev), destroyed the development-developer stack resources after finishing feature development and removed developer stack, started encountering this issue in our development env with pulumi preview

Pulumi Version:    v3.134.1
Go Version:        go1.23.1
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi preview
Error:             snapshot integrity failure; refusing to use it: resource urn:pulumi:dev::xxx::azure-native:compute:VirtualMachineExtension::adfshir-vm-install-ir's dependency urn:pulumi:dev::xxx::azure-native:storage:Blob::install-shir-file refers to missing resource

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.23.1/x64/src/runtime/debug/stack.go:26 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x101f9f701?, 0x47?}, {0x140016a43b8?, 0x47?, 0x40?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:324 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x140023ec480)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0xcd4
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getSnapshot(0x140015bd290, {0x102d87a68, 0x1043a1340}, {0x102d631a0, 0x1043a1340}, 0x140020297c0)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:180 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Snapshot(0x14001ba36c8, {0x102d87a68, 0x1043a1340}, {0x102d631a0, 0x1043a1340})
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:62 +0x84
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).getTarget(0x140015bd290, {0x102d87a68, 0x1043a1340}, {0x102d631a0, 0x1043a1340}, 0x140020297c0, 0x14001bdbaa0, {0x102d739f8, 0x1400219b350})
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:128 +0xac
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).newUpdate(_, {_, _}, {_, _}, _, {0x140020520b0, {0x14002017100, 0x29}, {0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/state.go:101 +0x8c
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).apply(_, {_, _}, {_, _}, {_, _}, {0x140020520b0, {0x14002017100, 0x29}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:1061 +0x1ec
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).Preview(_, {_, _}, {_, _}, {0x140020520b0, {0x14002017100, 0x29}, {0x0, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/backend.go:934 +0x70
github.com/pulumi/pulumi/pkg/v3/backend.PreviewStack({_, _}, {_, _}, {0x140020520b0, {0x14002017100, 0x29}, {0x0, 0x0, 0x0}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/stack.go:91 +0x80
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyStack).Preview(_, {_, _}, {0x140020520b0, {0x14002017100, 0x29}, {0x0, 0x0, 0x0}, 0x14002044ab0, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/diy/stack.go:85 +0x60
main.newPreviewCmd.func1(0x1400160cf08, {0x1043a1340, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/preview.go:461 +0x1088
main.newPreviewCmd.runCmdFunc.func2(0x0?, {0x1043a1340?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:45 +0x28
main.newPreviewCmd.runCmdFunc.RunFunc.func5(0x1400160cf08, {0x1043a1340, 0x0, 0x0})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x1400160cf08, {0x1043a1340, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x14001b6b208)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x50

### Example

pulumi stack init devpm  --copy-config-from dev   
pulumi config set azure-native:location 'West Europe'   
pulumi preview
pulumi up

13 created, 1 failed
    error: 1 error occurred:
        * Creating group "xxx": GroupsClient.BaseClient.Post(): unexpected status 400 with OData error: Request_BadRequest: The property is missing a required prefix/suffix per your organization's Group naming requirements.
-> commented out entra id group creation

pulumi up
16 created, 13 unchanged

pulumi destroy

Diagnostics:
  azure-native:network:PublicIPAddress (xxx-egress-pip):
    error: Preview failed: resource "urn:pulumi:devpm::xxx::azure-native:network:PublicIPAddress::xxx-egress-pip" cannot be deleted
    because it is protected. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`, or use the command:
    `pulumi state unprotect 'urn:pulumi:devpm::xxx::azure-native:network:PublicIPAddress::xxx-egress-pip'`

  pulumi:pulumi:Stack (xxx-data-devpm):
    error: preview failed

  azure-native:storage:StorageAccount (adfvmdiagnostics):
    error: Preview failed: resource "urn:pulumi:devpm::xxx-data::azure-native:storage:StorageAccount::adfvmdiagnostics" cannot be deleted
    because it is protected. To unprotect the resource, either remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`, or use the command:
    `pulumi state unprotect 'urn:pulumi:devpm::xxx-data::azure-native:storage:StorageAccount::adfvmdiagnostics'`

pulumi state unprotect mentioned resources

pulumi destroy

29 deleted

pulumi stack rm devstack

xxx@xxx-MBP infra % pulumi preview
Please choose a stack, or create a new one: dev
Previewing update (dev):
error: snapshot integrity failure; refusing to use it: resource urn:pulumi:dev::xxx::azure-native:compute:VirtualMachineExtension::adfshir-vm-install-ir's dependency urn:pulumi:dev::xxx::azure-native:storage:Blob::install-shir-file refers to missing resource

### Output of `pulumi about`

CLI          
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.60.1
resource  azuread       5.53.3
language  python        unknown
resource  random        4.16.3

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in python: executable='/Users/xxx/repos/xxx/infra/venv/bin/python' version='3.12.5'

Backend        
Name           xxx-MacBook-Pro.local
URL            azblob://state
User           xxx
Organizations  
Token type     personal

Dependencies:
NAME                      VERSION
azure-identity            1.4.1
azure-mgmt-authorization  4.0.0
azure-mgmt-datafactory    9.0.0
pip                       24.2
pulumi_azure_native       2.60.1
pulumi_azuread            5.53.3
pulumi_random             4.16.3
setuptools                74.1.2
wheel                     0.44.0

Pulumi locates its logs in /var/folders/p7/v_rf6psd6dndrr95y5vxnbk00000gq/T/ by default
warning: Failed to get information about the current stack: No current stack

### Additional context

Noticed that the install-shir-file URN/resource is indeed missing from the development stack file, it is present in the other dev clone stack we have for another developer

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pmayn** [comment] 2024-09-30 06:16
Hi, is there something we could try on our end to try and fix our currently completely unusable pulumi dev stack?

**Comment by Frassle** [comment] 2024-09-30 07:02
You can try running with integrity checks disabled.  `pulumi up --disable-integrity-checking` this can often fix it if there's not too much difference between your current state file and the cloud state. Generally the main problem this hits is deletes running in the wrong order and so not succeeding.

Stacks are supposed to be segregated, so I'm not sure how a destroy on your devpm stack could have affected anything on your dev stack. I suspect something was already up with your dev stack before the operations on the devpm stack happened.

**Comment by lunaris** [comment] 2024-10-04 12:16
Hi @pmayn, I don't suppose you have any further information following @Frassle's comment, do you? In particular, from the logs you've provided it seems like you are hitting an error in one stack (`dev`) but providing a sequence of commands that affect another (`devpm`). In practice they should have completely distinct states, so if you are able to provide more information on the `dev` stack and any commands that lead to a reproduction, that'd be amazing. If not, we might have to close this since it could be very tricky to track down without a consistent way to hit the bug.

**Comment by pmayn** [comment] 2024-10-07 09:22
Hey, 

quick update, we managed to restore the dev stack by manually fixing the state file (we removed all the references to the blob that was missing)

But yeah, that's the part that confused me as well, ie the "Official" dev stack starting to act up after working with the separate devpm stack, I've no explanation for that, it would make more sense that something was already cooking before cloning the stack


What information would be most beneficial to you regarding the "dev" stack?

Here is the zsh_history (unfortunately did not have timestamps on for the shell)


pulumi stack init devpm  --copy-config-from dev
pulumi preview
pulumi config set azure-native:location 'West Europe'
pulumi preview
pulumi up 
pulumi up 
pulumi destroy
pulumi state unprotect 'urn:pulumi:devpm::xxx::azure-native:network:PublicIPAddress::adf-egress-pip'
pulumi state unprotect 'urn:pulumi:devpm::xxx::azure-native:storage:StorageAccount::adfvmdiagnostics'
pulumi destroy
pulumi stack rm devpm ##after which, switching back to the dev stack, noticed the problem
pulumi preview
pulumi preview
pulumi refresh
pulumi up
pulumi preview
pulumi state delete urn:pulumi:dev::xxx::azure-native:storage:Blob::install-shir-file --disable-integrity-checking
pulumi preview
pulumi preview
pulumi preview
pulumi about
pulumi stack
pulumi preview
pulumi preview
pulumi preview
pulumi preview
pulumi preview
pulumi preview --disable-integrity-checking
pulumi prevew
pulumi preview
pulumi preview
pulumi preview

**Comment by lunaris** [comment] 2024-10-07 09:31
Thanks for the reply @pmayn. Is there any chance that before your report you were using an older version of the Pulumi CLI locally? Or rather, did you upgrade your Pulumi CLI at any point during the sequence of commands you've shared, perhaps in respond to the CLI prompting you to? It is possible that you were previously on such an old version that the issue was caused and not reported on (we have only recently introduced changes that print loud errors when snapshot integrity is violated), meaning that the error was introduced silently and then only picked up later on. The shell history is appreciated but again I don't think it is possible (famous last words) for actions on one stack to affect the state of another (I will go hunting for such issues but I feel like we would have seen them sooner were it possible 🤔 ).

**Comment by pmayn** [comment] 2024-10-07 09:46
Hey, 

My apologies for failing to mention that, yeah, I was using an older CLI version beforehand that gave me a much more vague error message when trying to run pulumi preview and/or pulumi up. I think the version I was on was like 3.116.1? 

I think I saw in one of the other issues with the same header that one should update their CLI as to get the correct error message which I did. The new CLI version then led me to report this issue as instructed :)

Currently everything is however working on our end, just hoping it won't pop up again!

**Comment by lunaris** [comment] 2024-10-07 09:52
That's incredibly helpful -- thanks for mentioning it. It is _very_ likely that the issue was caused by this, and since that release (~5 months ago) we have fixed a lot of these issues, so hopefully you won't see them again. I'm minded to close this as a result if that's OK.

If it does happen again, please of course open an issue/reopen this one. Additionally, in the next release (this week) we are rolling out the `state repair` command, which should help automate some of the fixes you applied this time (e.g. deleting dangling references).

**Comment by pmayn** [comment] 2024-10-07 10:31
Sounds great! Feel free to close the issue and thank you for your prompt assistance :)

Excited to try out the new repair command when the need arises!

Have a great week!

**Comment by lunaris** [comment] 2024-10-07 10:34
You too! All the best, and hopefully you won't need it 😂

**Closed by lunaris** 2024-10-07 10:34 UTC
Labels: kind/bug, p1, area/engine, impact/snapshot-integrity
