### ISSUE TITLE
Allow package schemas to define component resources.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#5046] opened 2020-07-23 21:27 UTC
Just what it says on the tin. Part of #2430.

**Comment by pgavlin** [comment] 2020-07-23 21:29
This also involves updating the code generators to emit component resource types into the SDK with appropriate calls to the `Construct` API that will be added by #5044.

**Comment by lblackstone** [comment] 2020-09-22 22:53
I think this is a dupe of #5357 
That issue has more details, so closing this one out.

**Closed by lblackstone** 2020-09-22 22:53 UTC
Labels: area/multi-language
