### ISSUE TITLE
Numeric-Like Strings Written as Unquoted Numbers in YAML Config with Path set

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#17586] opened 2024-10-18 18:24 UTC
### What happened?

When attempting to use the Automation API to set my config with my Path set and using numeric like strings, it is setting the values to be unquoted numbers. This behavior seems to be present both in the automation api and the cli command `pulumi config set --path`. 

It has been pointed out that users could be depending on this functionality, so we might need to consider a way to prevent this from being a breaking change for existing users.

### Example

```go
	s.SetConfigWithOptions(ctx, "SetConfigWithOptions[0]", auto.ConfigValue{Value: "100"}, &auto.ConfigOptions{Path: true})
	s.SetConfigWithOptions(ctx, "SetConfigWithOptions[1]", auto.ConfigValue{Value: "200"}, &auto.ConfigOptions{Path: true})
	s.SetConfigWithOptions(ctx, "SetConfigWithOptions[2]", auto.ConfigValue{Value: "\"300\""}, &auto.ConfigOptions{Path: true})
	s.SetAllConfigWithOptions(ctx, auto.ConfigMap{"SetAllConfigWithOptions[0]": auto.ConfigValue{Value: "400"}, "SetAllConfigWithOptions[1]": auto.ConfigValue{Value: "500"}, "SetAllConfigWithOptionsNoIndex": auto.ConfigValue{Value: "600"}}, &auto.ConfigOptions{Path: true})
```
will result in the following config
```yaml
config:
  AutomationAPIBucket:SetAllConfigWithOptions:
    - 400
    - 500
  AutomationAPIBucket:SetAllConfigWithOptionsNoIndex: "600"
  AutomationAPIBucket:SetConfigWithOptions:
    - 100
    - 200
    - '"300"'
```

There doesn't appear to be any reasonable way to get the numeric values to be quoted strings like "400"

### Output of `pulumi about`

N/A

### Additional context

I did find one workaround. If you set the config to have a string value and then overwrite it, you can get the quoted numeric value as desired. 

### Example
```go
	s.SetConfigWithOptions(ctx, "SetConfigWithOptions[0]", auto.ConfigValue{Value: "0100"}, &auto.ConfigOptions{Path: true})
	s.SetConfigWithOptions(ctx, "SetConfigWithOptions[0]", auto.ConfigValue{Value: "100"}, &auto.ConfigOptions{Path: true})
```

results in 

```yaml
  AutomationAPIBucket:SetConfigWithOptions:
    - "100"
```

Also worth noting, it has to be a numeric value with a leading zero to force the quotes. If you use a regular string like a word, it won't include quotes.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by joeduffy** [comment] 2024-10-19 16:02
This appears to be due to the way path-based configuration works. It treats the value as a JSON object and does quite a few conversions in the process of setting and retrieving values.

The value enters `marshalValue` and its friend `MarshalString` quoted as intended, and departs either converted to a number, or doubly quoted string (i.e., `'"300"'`):

https://github.com/pulumi/pulumi/blob/fd07f42c6116ea9685b24ca35ba5832994196fc5/sdk/go/common/resource/config/object.go#L353-L357

This is called from the config map's `Set` function:

https://github.com/pulumi/pulumi/blob/fd07f42c6116ea9685b24ca35ba5832994196fc5/sdk/go/common/resource/config/map.go#L173

It looks like this has been this way [since the beginning of time](https://github.com/pulumi/pulumi/commit/c08714ffb494154ab3fce2da9175760c8119cda9), so it's probably worth asking @justinvp if these are the intended semantics and/or whether there's an easy solution to this.

Note: At first, I suspected a shell quoting issue in the way we're invoking the Automation API, but ruled that out pretty quickly. Just mentioning that here to hopefully save someone a few minutes in case they're tempted to wonder about that too!

**Comment by justinvp** [comment] 2024-10-20 23:29
The behavior is intentional. This issue is a dupe of https://github.com/pulumi/pulumi/issues/5442.

Some [background](https://github.com/pulumi/pulumi/issues/8401#issuecomment-973672546):

> This behavior is actually intentional with how `--path` was originally designed, where values that are integers are saved as numbers, and "true" and "false" are saved as boolean values, which is based on how `helm install --set` works. But I understand how that can be unexpected (see related issues [#4295](https://github.com/pulumi/pulumi/issues/4295) and [#5442](https://github.com/pulumi/pulumi/issues/5442)), especially since top-level values are always just stored as strings (but can be parsed as other types in programs via `config.GetInt` or `config.GetBool`).
> 
> One suggestion was to add a `--string` flag to `pulumi config set` which would keep the `--path` value as a string, similar to helm's `--set-string`. Though, `--string` may not lend itself as well with the `pulumi config set-all` command where multiple values are being set. We may want to look into keeping it a string when the value is wrapped in quotes, but I'm not sure how easy that will be for us to implement with the library we use for parsing command line arguments.
> 
> In the meantime, the best workaround is to just edit the values directly in the yaml file, rather than going through the config set/set-all commands.

We should consider adding the `--string` flag and then expose that as an option in Automation API to force the value to be a string.

**Comment by justinvp** [comment] 2024-10-24 16:36
Closing as a dupe of #5442.

**Closed by justinvp** 2024-10-24 16:36 UTC
Labels: kind/bug, area/cli, area/automation-api, resolution/duplicate, customer/feedback, customer/lighthouse
