### ISSUE TITLE
Pulumi up failing caused some resources to be not matched and pulumi wants to recreate them on next run

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#13903] opened 2023-09-08 19:02 UTC
### What happened?

A pulumi up runs where there are alias's created, and it fails during the up cycle. On the next pulumi up it detects that it needs to create/delete some of the resources it changed in state already. 

### Expected Behavior

It should match the resources correctly and not try the create/delete cycle.

### Steps to reproduce

Working On Reproduction

### Output of `pulumi about`

pulumi about
CLI          
Version      3.81.0
Go Version   go1.21.0
Go Compiler  gc

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by omercnet** [comment] 2023-09-11 08:52
I have a similar issue where pulumi wants to delete everything

**Comment by omercnet** [comment] 2023-09-11 09:21
found the issue, I don't think it's related to this - will open a different issue

**Comment by justinvp** [comment] 2023-09-20 19:06
Customer is reporting they're still seeing this behavior on 3.83.0.

**Comment by Frassle** [comment] 2023-09-21 12:32
Customer issue was due to a state file being written out by a version of Pulumi older than [3.83](https://github.com/pulumi/pulumi/releases/tag/v3.83.0). Before 3.83 Pulumi could lose track of parents in the presence of aliases, this was fixed by https://github.com/pulumi/pulumi/pull/13935 but the engine can't retroactively fix issues caused by deployments from before this fix.

This issue arises when you have a resource graph such as C with parent B with parent A. If you then change B to have a different parent (or no parent) but then the update stops before C can be updated old version of Pulumi would update the parent reference for C, but not it's URN. This would result in URNs going from something like "stack:proj:typeA$typeB:B" and "stack:proj:typeA$typeB$typeC:C" to "stack:proj:typeB:B" and "stack:proj:typeA$typeB$typeC:C". On the next run that updated C it would calculate it's URN as "stack:proj:typeB$typeC:C" and fail to find that in the state and so think it needed to be created.

New version of Pulumi update both the parent reference and the URN so the later update can still find C. I'm looking to see if we can also automatically fix these when we load state files.

**Comment by justinvp** [comment] 2023-09-25 22:23
Closing this as fixed per https://github.com/pulumi/pulumi/issues/13903#issuecomment-1729475965

**Closed by justinvp** 2023-09-25 22:23 UTC
Labels: kind/bug, p0, resolution/fixed, customer/feedback, area/engine, customer/lighthouse
