### ISSUE TITLE
Validation error when importing Azure SQL Server using pulumi import command

### ISSUE THREAD

**Issue by OlegKarasik** [pulumi/pulumi#5903] opened 2020-12-09 11:46 UTC
Executing `pulumi import azure:sql/sqlServer:SqlServer <name> /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myresourcegroup/providers/Microsoft.Sql/servers/<name>` returns an error.

## Expected Behavior
Resource is imported.

## Current Behavior
The command fails with the following error:

```
azure:sql:SqlServer (<name>):
  error: azure:sql/sqlServer:SqlServer resource '<name>' has a problem: Missing required property 'administratorLoginPassword'
  error: Preview failed: one or more inputs failed to validate
```

## Steps to Reproduce
1. Execute `pulumi import azure:sql/sqlServer:SqlServer <name> /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myresourcegroup/providers/Microsoft.Sql/servers/<name>` command

## Context (Environment)
Pulumi CLI 2.15.4
Cloud Login

**Comment by leezen** [comment] 2020-12-11 07:09
I think this may be an interesting case where the necessary properties aren't returned on a read of the resource. As a workaround, you should be able to import this resource using the programmatic import method documented in https://www.pulumi.com/docs/guides/adopting/import/#pulumi-import-resource-operation

**Comment by OlegKarasik** [comment] 2020-12-11 11:17
Hi @leezen,

Correct me if I am wrong, but will programmatic approach change admin password on SQL server?

**Comment by leezen** [comment] 2020-12-11 16:28
As long as the input matches what's already there, it should not.

**Comment by OlegKarasik** [comment] 2020-12-11 16:56
Thanks.

Do you have any plans to update `pulumi import` to support SQL server and similar scenarios?

**Comment by leezen** [comment] 2020-12-12 02:11
I'm not sure there's an easy way to support that as it'd require reading in the sensitive value and putting that into the generated source, which is not what we'd want to do. I'm going to close this issue and cut a new one tracking the desire to do this in general where the idea is we'd want to import resources that have inputs that we wouldn't want to (or cannot) project into the code (a good example being `userData` in EC2).

**Closed by leezen** 2020-12-12 02:11 UTC

**Comment by andrekiba** [comment] 2021-04-30 11:20
Hello and thanks in advance. Regarding Azure SQL Server seems that the programmatic import doesn't work also.
If you know something different @leezen or @mikhailshilkov could you please explain which is the correct way to do this?
`administratorLoginPassword` always fails.
My scenario is caused by the fact that I need to re-sync the Pulumi state with what is inside Azure, due to a move to another subscription. In this case (I already have the c# stack in code) which is the correct way to proceed?
