### ISSUE TITLE
deleteBeforeReplace with failed create - inconsistent state

### ISSUE THREAD

**Issue by jesse-triplewhale** [pulumi/pulumi#16179] opened 2024-05-12 15:43 UTC
### What happened?

If I use `deleteBeforeReplace: true` and the resource deletion succeeds, but the creation fails, the result is inconsistent state. The resource does *not* exist in the provider, but *does* exist in pulumi state

### Example

1. 
```
new gcp.secretmanager.Secret(
  'testsecret',
  {
    secretId: 'my-test-secret',
    replication: {
      auto: {},
    },
  },
  {
    deleteBeforeReplace: true,
  }
);
```
2. `pulumi up`
resource now exists in pulumi state and in provider
3. change `secretId` to a taken value, `my-existing-secret`
4. `pulumi up`
resource is successfully deleted, but then not created. resource now exists in pulumi state but not in provider

### Output of `pulumi about`

❯ pulumi about                                                                                                

CLI          
Version      3.94.2
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME           VERSION
clickhouse     0.0.26
cloudflare     5.27.0
datadog        4.28.0
docker         4.5.3
ec             0.8.0
gcp            7.21.1
gcp            7.21.1
google-native  0.32.0
kafka          3.7.3
kubernetes     4.11.0
kubernetes     4.11.0
mongodbatlas   3.15.0
mongodbatlas   3.15.0
nodejs         unknown
postgresql     3.11.0
rabbitmq       3.3.2
random         4.16.1
slack          0.4.4

Host     
OS       darwin
Version  14.4.1
Arch     arm64

This project is written in nodejs: executable='/Users/.../.nvm/versions/node/v18.17.1/bin/node' version='v18.17.1'

Current Stack: ...

Found no pending operations associated with shofifi

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/...
User           ...
Organizations  ...
Token type     organization: ...
Token type     cloud-build

Pulumi locates its logs in /var/folders/q5/.../T/ by default
warning: Failed to get information about the Pulumi program's dependencies: failed to run "/Users/.../.nvm/versions/node/v18.17.1/bin/npm ls --json --depth=0": exit status 1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment] 2024-05-20 23:43
Thanks for opening the issue and sorry for the trouble!

I was able to reproduce the same behavior with a `Bucket` resource in AWS. I would expect the resource to be removed from the state after it was deleted (and not remain when the create fails).

This looks like it's potentially the same as https://github.com/pulumi/pulumi/issues/8354 (very old issue).

We'll look into picking this up soon.

**Comment by ianze-k** [comment] 2024-08-08 17:10
I wanted to add that I have noticed this behavior (getting a resource in inconsistent state) even when not setting `deleteBeforeReplace: True`.

In my experience, when working with GCP provider with NodePool and K8S cluster resources using Python I have noticed when these resources need to be recreated they are first deleted before a new one is created. If there is an error on the creation then the state becomes inconsistent.

**Comment by lunaris** [comment] 2024-09-09 08:01
Hi all; I've taken a look at this issue and as far as I can tell/assuming I understand correctly, this behaviour is by design:

* You have a resource with delete-before-replace semantics
* Pulumi deletes the resource in the cloud provider (here, GCP)
* Pulumi leaves the deleted resource in the state, but it is marked with `pendingReplacement: true` (more on this in a bit)
* Pulumi attempts to create a replacement but fails

We want to leave the resource in the state in cases like this for a number of reasons:

* If other resources depend on the resource being deleted, removing them from the state would result in dangling dependencies/an invalid snapshot
* When we next run a `pulumi up`, for instance, the presence of resources that are `pendingReplacement` is exactly the information Pulumi needs to resume and retry the operation.

Does this make sense? Or have I missed the point and something else is going on here where e.g. deletions have succeeded but Pulumi is still leaving things in state? Thanks for any information and feedback you can provide!

**Comment by jesse-triplewhale** [comment] 2024-09-09 08:36
Hey, thanks for taking a look at this. I'm not in the details right now, but it could be that this is no longer an issue after https://github.com/pulumi/pulumi/issues/16288 and https://github.com/pulumi/pulumi/pull/16510 - one of which was yours!

**Comment by lunaris** [comment] 2024-09-09 08:54
For sure depending on your exact issue those could resolve it for you, though as I say -- the resource will still "be in the state" after it's been deleted, it's just that's by design since it'll be marked `pendingReplacement`. I'll close this issue but we can always reopen if I've missed something 🙏

**Closed by lunaris** 2024-09-09 08:54 UTC
Labels: kind/bug, resolution/by-design, area/engine, area/resource-options
