### ISSUE TITLE
Running pulumi up produces output missing the project

### ISSUE THREAD

**Issue by graywolf-at-work** [pulumi/pulumi#5447] opened 2020-09-23 13:41 UTC
Output of the pulumi command is missing the project. Based on reading the code, it looks intentional but leads to confusing and not that clear output.

For example, we would like to have multiple projects, `foo-infra`, `bar-infra` and each of them `dev`, `stage`, and `prod` environments. That leads to confusion since you would just see `xxx/dev`, but not the project.

## Expected Behavior

```
Updating (xxx/infra/dev)
```

## Current Behavior

```
Updating (xxx/dev)
```

## Steps to Reproduce

1. pulumi new
2. project: foo-infra
3. stack: xxx/foo-infra/dev
4. pulumi up (and see just xxx/dev)

**Comment by lukehoban** [comment] 2020-09-23 15:01
I assume you are using the local or cloud storage backends - not the Pulumi service backed?

If so - then this is due to the issue tracked in https://github.com/pulumi/pulumi/issues/2522.

**Comment by graywolf-at-work** [comment] 2020-09-23 15:03
We are using the pulumi service backend. Or at least there is link to app.pulumi.com in the Live View section of the output. That is what you have meant?

**Comment by mikhailshilkov** [comment] 2022-04-12 11:52
I'm seeing `Updating (dev)` when running updates with the Pulumi backend. As this issue is 2 years old, I'll go ahead and close it as either fixed in these two years or not reproducible. If anyone has details about where this confusion still happens, please report back.

**Closed by mikhailshilkov** 2022-04-12 11:52 UTC
Labels: kind/question, resolution/no-repro
