### ISSUE TITLE
Consider generating output-versioned invokes for zero-arg functions

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#13112] opened 2023-06-06 19:50 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently SDK generators follow a default policy where a function without any input parameters never generates an Output-versioned form in the target language. The original motivations here are probably erring on the side of keeping the generated code size minimal, as larger providers are stretching the tooling to the limits.

For example in AWS:

```typescript
// Output-versioned invoke.
export const x1: pulumi.Output<aws.iam.GetGroupResult> = aws.iam.getGroupOutput({groupName: "my-group"});

// Regular invoke workaround - user wraps a Promise-returning invoke into an Output.
export const x2: pulumi.Output<aws.iam.GetGroupResult> = pulumi.output(aws.iam.getGroup({groupName: "my-group"}));
```

For user functions without any inputs the user currently has to always go for the workaround:

```
export const x3: pulumi.Output<mypkg.SomethingResult> = pulumi.output(mypkg.getSomething({}));
```

This limitation is likely coming from this code:

https://github.com/pulumi/pulumi/blob/2f3e1657eb37b6c0980765a4e0055e5655b35c0d/pkg/codegen/schema/schema.go#L565

For small providers however this is inconvenient.  Consider adding a switch so that community providers can opt into generating such Output-versioned functions always.

**Comment by Zaid-Ajaj** [comment] 2023-06-06 22:36
I think we actually talked about this during platform ideation and was in favour of implementing this for sure

**Comment by justinvp** [comment] 2023-06-15 21:15
Duplicate of #12449

**Closed by justinvp** 2023-06-15 21:15 UTC
Labels: kind/enhancement, area/codegen, resolution/duplicate
