### ISSUE TITLE
Very slow deploy to AWS

### ISSUE THREAD

**Issue by Leonti** [pulumi/pulumi#5371] opened 2020-09-15 03:06 UTC
We have a stack of 140 resources deployed to a private VPC.
It has about 9 lambda functions, a couple of s3 buckets, Fargate cluster, task definition and a bunch of roles and policies.

When running `pulumi up --refresh` without *any* changes the command completes in about 26 minutes, sometimes even longer.
It seems like it's stuck on refreshing AWS Lambdas.
On my teammates machines the same stack completes in about 10 minutes.
The stack is saved to an s3 bucket and its size is about 1.6MB.

## Expected Behavior
Stack should be deployed/refreshed in reasonable amount of time and consistent between mahcines

## Current Behavior
On my machine it takes about 27 minutes for the stack to refresh while on my coworker's machine it takes 10 minutes.

## Steps to Reproduce
Tried it with a completely new stack with a single function deployed in a private VPC and I can't reproduce it.
It takes 2m32s to deploy a one line change to a function, which I think is reasonable, but not sure if it's too slow in general.
Unfortunately can't share company's stack for debugging.

## Context (Environment)
The stack worked fine on my machine until one day. It might have coincided with upgrade of Pulumi to 2.9.2, but I'm not certain.
Upgraded to Pulumi 2.10.0, but the issue persists.
I'm running macOS Catalina(10.15.6).

Tried running it with `--tracing` and with `--logtostderr -v=9 2> out.txt`

Tracing shows very slow calls to `/pulumirpc.ResourceMonitor/RegisterResource`, for example:
`"gRPC request":"type:\"aws:iam/policy:Policy\"...` took `6m49s`. The trace doesn't have any subtraces, all I can see is that it took almost 7m, but the request succeeded.
Everything works, it's just extremely slow.  

Not sure how I can debug it.

Any ideas what might be causing this and what steps I can take to fix it?

**Comment by stack72** [comment] 2020-09-16 17:38
@lukehoban I know you have spent some time looking at similar style issues in the past that you found some interesting things with, can you give your thoughts on this issue?

**Comment by Sodki** [comment] 2021-02-23 16:37
I think this is a duplicate of #6197

**Comment by doug65536** [comment] 2021-07-16 23:57
Two minutes to deploy a tiny file is utterly, utterly ridiculous, and AWS ought to be ashamed of the glacial performance of cloud9. Cloud9 is probably the biggest waste of developer time in this project, by far.

**Comment by lukehoban** [comment] 2021-07-17 01:47
I think it’s most likely this was indeed a duplicate of https://github.com/pulumi/pulumi/issues/6197. I’m going to close this out as I expect it no longer repros. But if anyone is seeing similarly slow updates, please do open a new issue with details.

**Closed by lukehoban** 2021-07-17 01:47 UTC
Labels: impact/performance, kind/bug, resolution/duplicate
