### ISSUE TITLE
Permit dependsOn on Outputs (In Python)

### ISSUE THREAD

**Issue by Panaetius** [pulumi/pulumi#3972] opened 2020-02-25 14:14 UTC
https://github.com/pulumi/pulumi/issues/991 fixed this in the typescript sdk, but https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/resource.py#L438 in the python sdk only accepts type `Resource`.

**Comment by lukehoban** [comment] 2021-07-07 19:58
Closing as duplicate of  #5642.

**Closed by lukehoban** 2021-07-07 19:58 UTC
Labels: kind/bug, resolution/duplicate
