### ISSUE TITLE
Python 3.6: Sporadic "Can't get attribute [ProviderName] on module" error with Python dynamic provider on `pulumi refresh`

### ISSUE THREAD

**Issue by cloudspeak** [pulumi/pulumi#5621] opened 2020-10-23 21:27 UTC
I have a project with a dynamic provider.  I recently discovered that on my stack, `pulumi refresh` causes the following error:

```
  pulumi-python:dynamic:Resource (test_item):
    error: Exception calling application: Can't get attribute 'TestProvider' on <module 'test_provider' from '/path/to/project/test_provider.py'>
```

The error is very difficult to pin down because it does not occur in every situation.  However, I found that it is far more likely to occur when there are multiple instances of the resource in the stack (just two resources for me was almost guaranteed to cause the problem).  More significantly, as I removed chunks of code to find the culprit, I found that I could very predictably cause or prevent it by adding or removing my import of `boto3` which I am using in the provider.

My suspicion is that there is nothing special about boto itself, but that there is some kind of correlation with the size(?) of the provider's module, or some other indirect effect of its inclusion, which is why the combination of boto3 and mutliple instances of the resource seem more likely to cause this message.

Here is a minimal example:

**__main__.py**
```python
from test_resource import TestResource
test_resource = TestResource(resource_name="test_instance", param1="value1", param2={})
test_resource = TestResource(resource_name="test_instance_2", param1="value1", param2={})
```

**test_resource.py**
```python
from typing import Optional
from pulumi import Input, Output, ResourceOptions
from pulumi.dynamic import Resource

from test_provider import TestProvider

class TestResource(Resource):
    param1: Output[str]
    id: Output[str]

    def __init__(
        self,
        resource_name: str,
        param1: Input[str],
        param2: Input[dict] = None,
        opts: Optional[ResourceOptions] = None,
    ):
        super().__init__(
            provider=TestProvider(),
            name=resource_name,
            props={
                "param1": param1,
                "param2": param2,
                "id": None,
            },
            opts=opts,
        )
```

**test_provider.py**
```python
import boto3
from typing import Any
from pulumi.dynamic import CreateResult, UpdateResult, DiffResult, ReadResult, ResourceProvider

class TestProvider(ResourceProvider):

    def create(self, props: Any) -> CreateResult:
        return CreateResult(id_="id123", outs={})

    def diff(self, id: str, olds: Any, news: Any) -> DiffResult:
        return DiffResult(changes=True)

    def update(self, _id: str, _olds: Any, _news: Any) -> UpdateResult:
        return UpdateResult(outs={**_news, "id": _id})

    def delete(self, _id: str, _props: Any) -> None:
        pass

    def read(self, id, props):
        return ReadResult(id_=id, outs=props)
```

If I run `pulumi up` followed by `pulumi refresh`, the error will almost certainly occur.  If it doesn't, a second `pulumi refresh` is (so far) guaranteed to cause it.  But if I comment out the `import boto3` and then run `pulumi destroy && pulumi up && pulumi refresh`, it will work fine almost every time. Occasionally, stacks which cause the error will successfully refresh, so it is definitely random in behaviour.

Note it may be related to [this issue](https://github.com/pulumi/examples/issues/692), although their problem was apparently caused by the name of their dynamic provider changing.

## Context (Environment)
I am on Pulumi v2.12.1, Python 3.6.9, Ubuntu Linux.

**Comment by dannielshalev** [comment] 2021-06-07 09:38
I have a similar issue, sporadic failure when using the dynamic providers.
I'm getting the following error:
`Exception calling application: Can't get attribute 'SchemaProvider'`

**Comment by cheribral** [comment] 2021-06-16 05:07
Any update on when this might be looked at?  It was assigned 8 months ago, but it is still an issue in v3.4.0, and seems like a fairly significant bug.  It basically stops anyone using dynamic resources if they ever want check their state against reality.

**Comment by lukehoban** [comment] 2021-06-16 07:19
@cheribral This does appear to be the same issue as pulumi/examples#692 so I've duped that to this.

However, I tried reproducing both that issue and the repo steps listed here - and can't trigger either failure.  I used Pulumi 3.4.0 and both Python 3.9.5 and Python 3.7.10.  

If anyone is able to reproduce this, could you share a minimal repro that consistently triggers this still on latest Pulumi CLI and SDK versions, and any additional environment details to help with debugging?

If possible, could you also capture verbose diagnostics and see if there are any additional details of the error that is reported above?  https://www.pulumi.com/docs/troubleshooting/#verbose-logging

**Comment by cheribral** [comment] 2021-06-16 23:01
Ok, this appears to be related to the python version.  I was using the default python3 from CentOS 7 which is 3.6 (this is listed as ok at https://www.pulumi.com/docs/intro/languages/python/).  Using this python, the original example in this issue reproduces the problem reliably.  If I rebuild the venv using python 3.9, there are no issues. 

I have attached the result of running ` TF_LOG=TRACE pulumi refresh --logtostderr -v=9 2> out.txt` with python3.6 which shows the error.
[out.txt](https://github.com/pulumi/pulumi/files/6666244/out.txt)

**Comment by lukehoban** [comment] 2021-06-17 02:47
@cheribral Thanks for confirming.  Is it possible you are switching between Python versions between updates?  Dynamic providers work by pickling your code and storing it in the checkpoint.  This pickled code is used during refresh and destroy operations (when the program itself is not run).  I believe there have been some breaking changes between minor Python 3.x releases to pickling, which could in principle cause a failure mode like this.  

The error message that is being reported here just shouldn't be possible - the module does have class mentioned.  Which leads me to suspect this is some issue in Python itself - and the most likely culprit I can imagine is breaking changes in pickling between minor versions.

Could you confirm whether your repro case on 3.6 happens if you work 100% in Python 3.6?  That is, stand up the stack originally with Python 3.6, and do the refresh still with Python 3.6?

**Comment by cheribral** [comment] 2021-06-17 04:06
Yes, I reproduced it working 100% with python 3.6.  In my real project, I only use python 3.6 and have this problem.

I only switched python versions as en experiment when trying the example code given by @cloudspeak.  I ran the initial 'up' with 3.6, and I could consistently reproduce the problem by running 'refresh' with his example, still using 3.6.  

After noticing that you mentioned you had no problem with python 3.7 and 3.9, I used a locally compiled python 3.9 to create a new venv.  After recreating the venv, I could refresh as many times as I wanted with no error.

If you have a CentOS vm to try with, the stock python3 package should reproduce the problem.

```
Name        : python3
Version     : 3.6.8
Release     : 18.el7
Architecture: x86_64
Install Date: Wed 27 Jan 2021 21:24:13 UTC
Group       : Unspecified
Size        : 39896
License     : Python
Signature   : RSA/SHA256, Wed 18 Nov 2020 14:19:51 UTC, Key ID 24c6a8a7f4a80eb5
Source RPM  : python3-3.6.8-18.el7.src.rpm
Build Date  : Mon 16 Nov 2020 17:41:58 UTC
Build Host  : x86-02.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
```

**Comment by jamesfmilne** [comment] 2021-11-08 21:17
I can corroborate. I had the same issue on CentOS 8.4 with python 3.6.8.
Upgraded to python 3.8.3 (python38 package) and this error has gone.

**Comment by justinvp** [comment] 2021-11-08 21:25
Just a note that Python 3.6 will be EOL'd in December 2021 at which point we are planning to drop support for it. More info at https://github.com/pulumi/pulumi/issues/8131

**Comment by justinvp** [comment] 2023-03-23 14:25
Closing this issue since Python 3.6 is no longer supported.

**Closed by justinvp** 2023-03-23 14:25 UTC
Labels: kind/bug, language/python, resolution/no-repro, area/dynamic-providers
