### ISSUE TITLE
`watch` panics with component 

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5625] opened 2020-10-26 17:20 UTC
#### Problem

`pulumi watch` panics and exits if my Pulumi application has a `ComponentResource` with a name that only has two parts - e.g. `custom:LandingZone` (which panics) vs `custom:x:LandingZone` (which doesn't panic). This panic does not occur in `preview` or `update` commands.

#### Error output

```
% pulumi watch     
Watching (demo/dev):
10:15:02.150[                    ] Updating...
10:15:10.434[demo-aws-ts-webserve] create pulumi:pulumi:Stack
10:15:11.428[demo-aws-ts-webserve] done create pulumi:pulumi:Stack
10:15:11.494[                main] create custom:LandingZone
10:15:11.931[                main] done create custom:LandingZone
10:15:12.452[                    ] Update complete.
panic: fatal: An assertion has failed: Module member token 'custom:LandingZone' missing module member delimiter

goroutine 72 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /private/tmp/pulumi-20201023-71015-8nrcuf/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0xc000d92800, 0x5914d03, 0x38, 0xc00169cc40, 0x1, 0x1)
        /private/tmp/pulumi-20201023-71015-8nrcuf/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/sdk/v2/go/common/tokens.ModuleMember.Module(0xc000d92840, 0x12, 0xc00128e080, 0xf764390)
        /private/tmp/pulumi-20201023-71015-8nrcuf/sdk/go/common/tokens/tokens.go:192 +0xd2
github.com/pulumi/pulumi/sdk/v2/go/common/tokens.ModuleMember.Package(0xc000d92840, 0x12, 0x58b5aff, 0x1)
        /private/tmp/pulumi-20201023-71015-8nrcuf/sdk/go/common/tokens/tokens.go:187 +0x35
github.com/pulumi/pulumi/sdk/v2/go/common/tokens.Type.Package(0xc000d92840, 0x12, 0xc000122d08, 0x40131d8)
        /private/tmp/pulumi-20201023-71015-8nrcuf/sdk/go/common/tokens/tokens.go:227 +0x70
github.com/pulumi/pulumi/pkg/v2/operations.(*resourceOperations).getOperationsProvider(0xc0006289a0, 0x0, 0x1, 0xc00006ed80, 0x0)
        /private/tmp/pulumi-20201023-71015-8nrcuf/pkg/operations/resources.go:252 +0x65
github.com/pulumi/pulumi/pkg/v2/operations.(*resourceOperations).GetLogs(0xc0006289a0, 0xc000a319e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/pulumi-20201023-71015-8nrcuf/pkg/operations/resources.go:147 +0xb65
github.com/pulumi/pulumi/pkg/v2/operations.(*resourceOperations).GetLogs.func1(0xc0006289a0, 0xc000a78fa0, 0xc0013e24e0, 0xc0013e2540)
        /private/tmp/pulumi-20201023-71015-8nrcuf/pkg/operations/resources.go:175 +0x5f
created by github.com/pulumi/pulumi/pkg/v2/operations.(*resourceOperations).GetLogs
        /private/tmp/pulumi-20201023-71015-8nrcuf/pkg/operations/resources.go:174 +0x1bb
% 
```

#### Code to reproduce 

```ts
import * as pulumi from "@pulumi/pulumi";

class LandingZone extends pulumi.ComponentResource {
    constructor(name: string, args: {}, opts?: pulumi.ComponentResourceOptions) {
        super("custom:LandingZone", name, args, opts); // panics with `watch`
        // super("custom:x:LandingZone", name, args, opts); // does not panic
        this.registerOutputs();
    }
};

const lz = new LandingZone("main", {});
```

**Comment by leezen** [comment] 2020-11-02 17:48
Closing as dupe of https://github.com/pulumi/pulumi/issues/3432

**Closed by leezen** 2020-11-02 17:48 UTC
Labels: area/cli, kind/bug, kind/panic
