### ISSUE TITLE
We don't seem to be updating our Homebrew tap with the most recent version

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#10793] opened 2022-09-19 21:44 UTC
```
$ which pulumi
/opt/homebrew/bin/pulumi

$ brew upgrade pulumi
Warning: pulumi/tap/pulumi 3.39.3 already installed

$ pulumi version
v3.39.3
warning: A new version of Pulumi is available. To upgrade from version '3.39.3' to '3.40.1', run
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

**Comment by AaronFriel** [comment] 2022-09-20 00:15
Duplicate of #10696.

**Closed by AaronFriel** 2022-09-20 00:15 UTC
Labels: area/build, resolution/duplicate, kind/task
